"""Encyclopedia: Gram-positive cocci and rods."""
from ecore import E, S, P, H

ENTRIES = [
E("s-aureus", "Staphylococcus aureus", "Gram-Positive Cocci",
  "The most versatile pyogenic pathogen in medicine: abscesses anywhere, toxin syndromes, and the archetype of acquired antibiotic resistance.",
  aka=["staph aureus", "MRSA", "MSSA"],
  keywords=["abscess", "TSST-1", "toxic shock", "scalded skin", "endocarditis", "osteomyelitis", "food poisoning", "protein A", "PVL"],
  treatment="MSSA: nafcillin, oxacillin, or cefazolin. MRSA: vancomycin, daptomycin (not for pneumonia), linezolid, ceftaroline; oral doxycycline or TMP-SMX for skin.",
  quick=[("Stain", "Gram-positive cocci in grape-like clusters"),
         ("Catalase", "Positive (separates staph from strep)"),
         ("Coagulase", "Positive (separates S. aureus from CoNS)"),
         ("Hemolysis", "Beta on blood agar"),
         ("Selective media", "Mannitol salt agar - yellow colonies"),
         ("Reservoir", "Anterior nares of ~30% of healthy people")],
  images=[("saureus-gram.jpg", "Gram stain: Gram-positive cocci in irregular clusters."),
          ("msa-agar.jpg", "Mannitol salt agar: S. aureus ferments mannitol and turns the medium yellow."),
          ("coagulase.jpg", "Tube coagulase: a solid clot (left) is positive.")],
  sections=[
    S("Structure and identification", [
      H("Gram-positive cocci in clusters, catalase-positive and coagulase-positive. Catalase separates staphylococci from streptococci; coagulase separates S. aureus from the coagulase-negative staphylococci."),
      P("The wall is the standard Gram-positive design: a thick multilayer peptidoglycan sacculus threaded with wall teichoic acid and membrane-anchored lipoteichoic acid. Those teichoic acids are the principal ligands for TLR2 and drive much of the early cytokine response. The thickness of the peptidoglycan is what traps the crystal violet-iodine complex during decolorization, giving the purple Gram reaction."),
      P("Coagulase exists in two forms. Free (secreted) coagulase binds prothrombin to form staphylothrombin, which converts fibrinogen to fibrin without the usual clotting cascade; this is what the tube test detects. Bound coagulase, or clumping factor A, is a surface protein that binds fibrinogen directly and gives the rapid slide agglutination test. The fibrin coat produced is thought to shield the organism from phagocytes and helps wall off the abscesses this organism is famous for."),
      P("Colonies are golden because of staphyloxanthin, a carotenoid pigment. It is not decorative: it is an antioxidant that quenches the reactive oxygen species of the neutrophil respiratory burst. Pigment-deficient mutants are markedly more susceptible to neutrophil killing, and the same logic explains why catalase, which destroys hydrogen peroxide, matters so much in chronic granulomatous disease."),
    ]),
    S("Adhesion, immune evasion, and abscess formation", [
      P("A family of surface proteins called MSCRAMMs (microbial surface components recognizing adhesive matrix molecules) binds host fibronectin, fibrinogen, and collagen. This is why S. aureus colonizes damaged endothelium, prosthetic material, and exposed bone so efficiently, and why it, rather than a commensal, causes acute endocarditis on previously normal valves."),
      H("Protein A binds the Fc region of IgG, holding antibody in the wrong orientation so its Fc cannot engage neutrophil Fc receptors or fix complement efficiently. The result is impaired opsonization."),
      P("Additional evasion tools include a leukocidal arsenal, staphylokinase (which activates plasminogen to dissolve fibrin and also degrades IgG and C3b), nuclease that dismantles neutrophil extracellular traps, and chemotaxis inhibitory protein that blocks C5a and formyl-peptide receptors. The organism also forms biofilm on catheters and prosthetic joints, where slow growth and a polysaccharide matrix blunt both antibiotics and phagocytes."),
      P("The characteristic lesion is the abscess: a central core of dead neutrophils and bacteria, walled by fibrin. That wall is a double-edged structure - it limits spread but also excludes antibiotics and phagocytes, which is why drainage, not antibiotics alone, is the therapeutic cornerstone."),
    ]),
    S("Toxins and toxin-mediated disease", [
      H("TSST-1 is a superantigen: it bridges MHC class II outside the peptide groove to the variable beta region of the T-cell receptor, activating up to 20% of T cells at once. The resulting IL-2, IFN-gamma, and TNF storm produces fever, a diffuse erythroderma, hypotension, and multiorgan failure, with desquamation of palms and soles one to two weeks later."),
      P("Staphylococcal toxic shock is classically culture-negative because the toxin is made at a colonized site - a retained tampon, nasal packing, or a surgical wound - rather than in the bloodstream. Management is source control, aggressive fluids, an antistaphylococcal agent, and clindamycin, which shuts off toxin synthesis at the ribosome even in stationary-phase organisms. IVIG is used to neutralize circulating toxin in severe cases."),
      H("Exfoliative toxins A and B are serine proteases that cleave desmoglein 1, the desmosomal protein holding keratinocytes together in the superficial epidermis. This produces staphylococcal scalded skin syndrome: flaccid bullae, a positive Nikolsky sign, a split at the granular layer, and sparing of mucosa (which depends on desmoglein 3 instead). The bullae are sterile because the toxin acts at a distance."),
      H("Preformed, heat-stable enterotoxins cause food poisoning with vomiting 1-6 hours after eating, classically from mayonnaise, custard, or ham handled by a carrier. Reheating kills the organism but not the toxin, so illness still occurs."),
      P("Panton-Valentine leukocidin is a two-component pore-forming toxin encoded by lukS-PV and lukF-PV, strongly associated with community-acquired MRSA lineages such as USA300. It lyses neutrophils and macrophages and is linked to recurrent furunculosis and to necrotizing pneumonia following influenza. Alpha-hemolysin is a separate heptameric pore former that binds ADAM10 on epithelium, endothelium, and platelets."),
    ]),
    S("Clinical syndromes", [
      H("Skin and soft tissue: folliculitis, furuncles, carbuncles, purulent cellulitis, and abscesses. Purulence points to S. aureus; non-purulent spreading cellulitis is more often streptococcal."),
      H("Acute bacterial endocarditis on a normal valve, and the classic cause of tricuspid (right-sided) endocarditis in people who inject drugs, presenting with fever and septic pulmonary emboli rather than a murmur."),
      H("Osteomyelitis - the most common cause at all ages except in sickle cell disease, where Salmonella rises in importance - and the most common cause of septic arthritis in adults."),
      P("Pneumonia is typically a secondary, post-influenza event, producing patchy or cavitary infiltrates; influenza denudes respiratory epithelium and impairs neutrophil function. S. aureus also causes pyomyositis, epidural abscess, prosthetic device infection, and surgical site infection, most of which arise from the patient's own nasal flora."),
      P("S. aureus bacteremia is never dismissed as a contaminant. Management requires source removal, repeat blood cultures to document clearance, and echocardiography to exclude endocarditis, with at least 14 days of intravenous therapy."),
    ]),
    S("Resistance and its mechanisms", [
      P("Over 90% of isolates now produce blaZ-encoded penicillinase, which hydrolyzes the beta-lactam ring of penicillin G. This was answered by the penicillinase-resistant penicillins - methicillin, nafcillin, oxacillin, dicloxacillin - whose bulky side chains sterically block the enzyme."),
      H("MRSA carries mecA on the SCCmec mobile element. mecA encodes PBP2a, an alternative transpeptidase with low affinity for essentially all beta-lactams, so resistance extends to every penicillin and cephalosporin except ceftaroline. The laboratory screens for it with a cefoxitin disk."),
      P("Vancomycin-intermediate strains (VISA) thicken the cell wall, filling it with free D-Ala-D-Ala termini that act as decoys and sequester vancomycin before it reaches the membrane where wall synthesis occurs. Fully vancomycin-resistant strains (VRSA) are rare and arise by acquiring the vanA operon from enterococci, which replaces the terminal D-Ala with D-lactate and drops binding affinity a thousandfold."),
      P("Inducible clindamycin resistance is mediated by erm methylases, which methylate 23S rRNA and block macrolides, lincosamides, and streptogramin B. An isolate that is erythromycin-resistant but clindamycin-susceptible is tested with a D-test; a flattened zone between the disks reveals induction and predicts treatment failure."),
    ]),
  ]),

E("cons", "Coagulase-Negative Staphylococci", "Gram-Positive Cocci",
  "Skin commensals that turn pathogenic on plastic: S. epidermidis on devices, S. saprophyticus in the urine of young women, S. lugdunensis behaving like S. aureus.",
  aka=["S. epidermidis", "S. saprophyticus", "S. lugdunensis", "CoNS"],
  keywords=["biofilm", "prosthetic valve", "catheter", "novobiocin", "contaminant", "cystitis"],
  treatment="S. epidermidis: vancomycin (usually methicillin-resistant) plus device removal. S. saprophyticus: nitrofurantoin or TMP-SMX. S. lugdunensis: often penicillin-susceptible; treat like S. aureus.",
  quick=[("Stain", "Gram-positive cocci in clusters"),
         ("Catalase", "Positive"),
         ("Coagulase", "Negative"),
         ("Novobiocin", "S. epidermidis sensitive; S. saprophyticus resistant"),
         ("Urease", "S. saprophyticus positive")],
  sections=[
    S("Identification", [
      H("Novobiocin separates the two common species: 'on the staph retreat, there is NO StRESS' - Novobiocin: Saprophyticus Resistant, Epidermidis Sensitive."),
      P("All staphylococci are catalase-positive; absence of coagulase defines this group. Modern laboratories identify species by MALDI-TOF mass spectrometry rather than by biochemical panels, which matters because species identity changes how seriously a positive blood culture is taken."),
    ]),
    S("S. epidermidis and device infection", [
      H("The leading cause of prosthetic valve endocarditis within the first year, of CSF shunt infection, and of catheter-related bacteremia. It is also the most common blood culture contaminant, so interpretation depends on the number of positive sets and whether prosthetic material is present."),
      P("Its virulence is almost entirely biofilm. Polysaccharide intercellular adhesin, a poly-N-acetylglucosamine polymer made by the ica operon, glues cells to plastic and to each other. Within the biofilm, bacteria enter a slow-growing, metabolically quiet state in which beta-lactams (which need active wall synthesis) and phagocytes are largely ineffective, while the matrix itself impedes drug penetration."),
      P("This is why cure usually requires removing the device. Rifampin is often added for retained hardware because it penetrates biofilm well, but it is never given alone because resistance emerges within days through a single rpoB point mutation."),
    ]),
    S("S. saprophyticus and S. lugdunensis", [
      H("S. saprophyticus is the second most common cause of uncomplicated cystitis in young sexually active women, after E. coli. It is urease-positive and novobiocin-resistant, and urine nitrite is often negative because Gram-positive organisms do not reduce nitrate."),
      H("S. lugdunensis is coagulase-negative but behaves like S. aureus: aggressive native-valve endocarditis with perivalvular abscess and valve destruction. It should never be written off as a contaminant. It is PYR-positive and ornithine decarboxylase-positive, and most isolates remain penicillin-susceptible."),
    ]),
  ]),

E("s-pyogenes", "Streptococcus pyogenes (Group A)", "Gram-Positive Cocci",
  "Pharyngitis and impetigo that matter mostly for what follows them: rheumatic fever and glomerulonephritis, plus the most feared soft-tissue infection in medicine.",
  aka=["group A strep", "GAS", "strep throat", "S. pyogenes"],
  keywords=["pharyngitis", "scarlet fever", "rheumatic fever", "PSGN", "necrotizing fasciitis", "erysipelas", "M protein", "ASO"],
  treatment="Penicillin or amoxicillin remains uniformly effective. Necrotizing fasciitis: urgent debridement plus penicillin and clindamycin.",
  quick=[("Stain", "Gram-positive cocci in chains"),
         ("Catalase", "Negative"),
         ("Hemolysis", "Beta"),
         ("Bacitracin", "Sensitive"),
         ("PYR", "Positive"),
         ("Resistance", "No penicillin resistance has ever been documented")],
  images=[("beta-hemolysis.jpg", "Beta-hemolysis: complete clearing of blood agar around the colonies."),
          ("erysipelas.jpg", "Erysipelas: a raised, sharply demarcated plaque involving superficial dermis and lymphatics."),
          ("strep-tongue.jpg", "Strawberry tongue in scarlet fever."),
          ("scarlet-rash.jpg", "Scarlet fever: a diffuse sandpaper-textured rash accentuated in skin folds."),
          ("necrotizing-fasciitis.jpg", "Necrotizing fasciitis - note how modest the skin looks relative to the patient's pain.")],
  sections=[
    S("Identification and structure", [
      H("Beta-hemolytic, catalase-negative, bacitracin-sensitive, and PYR-positive. Group B strep is the mirror image: bacitracin-resistant, CAMP-positive, hippurate-positive."),
      P("Lancefield grouping is based on the C carbohydrate in the cell wall; the rapid antigen test detects exactly this antigen from a throat swab. Rapid tests are highly specific but only about 85% sensitive, so a negative test in a child or adolescent is backed up with culture, because missing group A strep risks rheumatic fever."),
      H("M protein is the major virulence factor. It recruits complement factor H and C4b-binding protein to the surface, accelerating C3b degradation and preventing opsonization. Immunity is type-specific and there are more than 200 emm types, so reinfection is routine - and M protein is also the antigen implicated in rheumatic cross-reactivity."),
    ]),
    S("Toxins and enzymes", [
      P("Streptolysin O is oxygen-labile and strongly immunogenic; antibody to it is the ASO titer. Because it is inactivated by skin lipids, ASO rises reliably after pharyngitis but poorly after impetigo, which is why anti-DNase B is the better marker after skin infection. Streptolysin S is oxygen-stable and non-immunogenic and produces the surface beta-hemolysis seen on the plate."),
      H("Streptococcal pyrogenic exotoxins (SpeA, SpeC), encoded by lysogenic bacteriophages, are superantigens. They cause scarlet fever - a sandpaper rash beginning on the neck, circumoral pallor, Pastia lines in the flexures, strawberry tongue, then desquamation - and streptococcal toxic shock syndrome."),
      P("Spreading factors explain why streptococcal infection diffuses where staphylococcal infection walls off: hyaluronidase degrades ground substance, streptokinase activates plasminogen to dissolve fibrin barriers, and DNase (streptodornase) liquefies the DNA-rich viscosity of pus. C5a peptidase cleaves C5a and blunts neutrophil chemotaxis."),
    ]),
    S("Suppurative disease", [
      H("Pharyngitis with fever, tonsillar exudate, tender anterior cervical nodes, and no cough. Also impetigo (honey-colored crusts), erysipelas (raised, sharply demarcated, superficial dermal and lymphatic involvement), and cellulitis."),
      H("Necrotizing fasciitis: pain grossly out of proportion to modest overlying erythema, rapid progression, systemic toxicity, and gray necrotic fascia that separates easily from muscle at operation. It is a surgical emergency; clindamycin is added to penicillin to halt toxin production."),
      P("Penicillin can fail in high-burden invasive infection through the Eagle effect: in stationary phase, bacteria are barely synthesizing cell wall, so a drug that needs active transpeptidation has little to attack. Clindamycin is unaffected by growth phase, which is the second reason it is added."),
    ]),
    S("Non-suppurative sequelae", [
      H("Acute rheumatic fever follows pharyngitis only - never skin infection - and is prevented by treating the pharyngitis within nine days. It is a type II hypersensitivity: antibodies and T cells raised against M protein cross-react with cardiac myosin and valve glycoproteins (molecular mimicry). Jones criteria: Joints (migratory polyarthritis), heart (carditis, the 'O' of a heart shape), Nodules (subcutaneous), Erythema marginatum, Sydenham chorea."),
      P("Histology shows Aschoff bodies with Anitschkow cells, sometimes called caterpillar cells for their wavy chromatin. The mitral valve is affected most often, and recurrent attacks progressively scar it, which is why secondary prophylaxis with benzathine penicillin every 3-4 weeks continues for at least 10 years or until age 21, longer with residual valve disease."),
      H("Post-streptococcal glomerulonephritis follows either pharyngitis or skin infection, arises from specific nephritogenic strains, and is a type III (immune complex) disease. Two to four weeks later the patient has cola-colored urine, periorbital edema, hypertension, and low C3. Electron microscopy shows subepithelial 'humps'; immunofluorescence is granular ('lumpy-bumpy') IgG and C3. Children usually recover fully, and unlike rheumatic fever it is not prevented by treating the infection."),
    ]),
  ]),

E("s-agalactiae", "Streptococcus agalactiae (Group B)", "Gram-Positive Cocci",
  "The dominant cause of neonatal sepsis and meningitis, and an increasingly common invasive pathogen in diabetics and the elderly.",
  aka=["group B strep", "GBS", "S. agalactiae"],
  keywords=["neonatal sepsis", "neonatal meningitis", "CAMP test", "hippurate", "intrapartum prophylaxis"],
  treatment="Penicillin or ampicillin. Intrapartum prophylaxis: IV penicillin; cefazolin for low-risk allergy, clindamycin or vancomycin for high-risk allergy.",
  quick=[("Stain", "Gram-positive cocci in chains"),
         ("Hemolysis", "Beta (narrow zone)"),
         ("Bacitracin", "Resistant"),
         ("CAMP test", "Positive"),
         ("Hippurate", "Hydrolyzed"),
         ("Screening", "Rectovaginal culture at 36-37 weeks")],
  images=[("camp-test.jpg", "Positive CAMP test: an arrowhead of enhanced hemolysis where GBS meets the S. aureus streak.")],
  sections=[
    S("Identification", [
      H("Beta-hemolytic, bacitracin-resistant, CAMP-positive, hippurate-positive. The CAMP factor acts synergistically with staphylococcal beta-hemolysin to produce an arrowhead of enhanced hemolysis pointing at the S. aureus streak."),
      P("Listeria can also give a positive CAMP reaction, but it is a Gram-positive rod with tumbling motility, so the Gram stain resolves the ambiguity immediately."),
    ]),
    S("Neonatal disease", [
      H("Early-onset disease (day 0-6) is acquired during passage through a colonized birth canal and presents as sepsis and pneumonia. Late-onset disease (1 week to 3 months) is acquired from maternal or environmental contact afterwards and presents more often as meningitis."),
      H("Intrapartum intravenous penicillin, given at least four hours before delivery to women with a positive rectovaginal screen at 36-37 weeks, prevents early-onset disease but has no effect on late-onset disease."),
      P("The capsule is the key virulence factor and is rich in sialic acid, which mimics host surface carbohydrate and recruits factor H to inactivate C3b. Protective anti-capsular IgG crosses the placenta mostly in the third trimester, which is why infants born before 34 weeks are at substantially higher risk. Other risk factors are prolonged rupture of membranes, intrapartum fever, and heavy maternal colonization."),
    ]),
    S("Adult disease", [
      H("In adults, group B strep causes skin and soft-tissue infection, osteomyelitis, bacteremia, and endocarditis, particularly in diabetics, the elderly, and patients with cirrhosis or malignancy. It remains uniformly penicillin-susceptible."),
    ]),
  ]),

E("s-pneumoniae", "Streptococcus pneumoniae", "Gram-Positive Cocci",
  "The most common cause of community-acquired pneumonia, adult bacterial meningitis, otitis media, and sinusitis - and the classic killer of the asplenic patient.",
  aka=["pneumococcus", "diplococcus"],
  keywords=["lobar pneumonia", "rusty sputum", "meningitis", "otitis media", "asplenia", "quellung", "optochin", "vaccine"],
  treatment="Amoxicillin or ceftriaxone for pneumonia. Meningitis: vancomycin plus ceftriaxone, with dexamethasone given before or with the first dose.",
  quick=[("Stain", "Lancet-shaped Gram-positive diplococci"),
         ("Hemolysis", "Alpha (green)"),
         ("Optochin", "Sensitive"),
         ("Bile", "Soluble (autolysin activated)"),
         ("Capsule", "~100 serotypes; the main virulence factor"),
         ("Quellung", "Capsular swelling with type-specific antiserum")],
  images=[("spneumo-gram.jpg", "Gram stain: lancet-shaped Gram-positive diplococci."),
          ("optochin.jpg", "Optochin disk: a wide zone of inhibition identifies pneumococcus."),
          ("lobar-pneumonia.jpg", "Lobar pneumonia - consolidation confined to one lobe.")],
  sections=[
    S("Identification", [
      H("Alpha-hemolytic, optochin-sensitive, and bile-soluble. Viridans streptococci are the mirror image: optochin-resistant and bile-insoluble. Mnemonic OVRPS - Optochin: Viridans Resistant, Pneumococcus Sensitive."),
      P("Bile solubility works because deoxycholate activates the organism's own autolysin (LytA), which digests its wall; the colonies literally dissolve. That same autolysin gives older colonies their umbilicated, 'draughtsman' appearance, and it is also what releases pneumolysin and inflammatory wall fragments during infection."),
      P("The quellung reaction uses type-specific anticapsular antiserum to make the capsule appear swollen and sharply outlined, allowing serotyping. Serotype matters because vaccines target the most invasive types."),
    ]),
    S("Virulence", [
      H("The polysaccharide capsule is the dominant virulence factor: it prevents phagocytosis, and antibody against it is the basis of protection and of both vaccines. Unencapsulated pneumococci are essentially avirulent."),
      P("IgA1 protease cleaves secretory IgA at its hinge, permitting mucosal colonization of the nasopharynx - the necessary first step for every pneumococcal disease. Pneumolysin is a cholesterol-dependent cytolysin that punches pores in host membranes, damages respiratory epithelium and cilia, activates complement, and in meningitis contributes to cochlear hair cell death and hearing loss."),
      P("Because control of encapsulated organisms depends on opsonization with antibody and complement followed by clearance in the spleen, loss of splenic function is catastrophic. Overwhelming post-splenectomy infection is most often pneumococcal, and asplenic patients, including those with sickle cell disease and functional autosplenectomy, need pneumococcal, meningococcal, and Hib vaccination."),
    ]),
    S("Clinical disease", [
      H("Classic lobar pneumonia with abrupt fever, rigors, pleuritic pain, and rust-colored sputum; radiographically a lobar consolidation. Also the leading cause of otitis media and sinusitis in children and of bacterial meningitis in adults."),
      P("Pathology of lobar pneumonia passes through congestion, red hepatization (neutrophils and red cells filling alveoli), gray hepatization (red cells lysed, fibrinopurulent exudate), and resolution. Because the alveolar architecture is preserved, healing is usually complete."),
      P("The urinary antigen test detects C-polysaccharide and stays positive for days to weeks after antibiotics begin, so it is useful when cultures were taken too late."),
    ]),
    S("Vaccines and resistance", [
      H("Pure polysaccharide vaccine (PPSV23) is a T-independent antigen: it produces IgM without memory and works poorly under two years of age. Conjugating the polysaccharide to a carrier protein recruits T-cell help, giving class-switched IgG and memory, which is why conjugate vaccines protect infants and reduce carriage."),
      H("Penicillin resistance is caused by mosaic PBP genes acquired by natural transformation from related streptococci - not by beta-lactamase. Adding a beta-lactamase inhibitor therefore does not help; the answer is a higher dose or a different drug. This is why empiric meningitis therapy pairs vancomycin with ceftriaxone."),
    ]),
  ]),

E("viridans", "Viridans Streptococci & S. gallolyticus", "Gram-Positive Cocci",
  "Oral and gut commensals that cause dental caries, subacute endocarditis on damaged valves, and - for one species - a warning of colon cancer.",
  aka=["S. mutans", "S. sanguinis", "S. mitis", "S. bovis", "S. gallolyticus", "S. anginosus", "milleri group", "Viridans strep", "Viridans streptococci"],
  keywords=["subacute endocarditis", "dental caries", "dextran", "colon cancer", "brain abscess"],
  treatment="Penicillin or ceftriaxone for endocarditis (4 weeks, or 2 weeks with gentamicin). S. anginosus abscesses need drainage.",
  quick=[("Stain", "Gram-positive cocci in chains"),
         ("Hemolysis", "Alpha or gamma"),
         ("Optochin", "Resistant"),
         ("Bile", "Insoluble"),
         ("S. gallolyticus", "Bile esculin-positive, but does not grow in 6.5% NaCl")],
  images=[("alpha-hemolysis.jpg", "Alpha-hemolysis - partial, greenish discoloration of the agar."),
          ("osler-nodes.jpg", "Osler nodes: tender pulp nodules of endocarditis.")],
  sections=[
    S("Subacute endocarditis", [
      H("Viridans streptococci are the classic cause of subacute bacterial endocarditis on previously damaged or prosthetic valves, typically after dental work, with an indolent course of low-grade fever, weight loss, and immune phenomena."),
      P("The mechanism is adherence. S. mutans and S. sanguinis convert dietary sucrose into extracellular dextrans using glucosyltransferase; dextran binds the fibrin-platelet vegetation that forms on damaged endocardium. The same polymer is what makes dental plaque adhere to enamel, which is why one organism explains both caries and endocarditis."),
      P("Immune phenomena of subacute disease - Osler nodes (tender, immune complex-mediated), Roth spots, and glomerulonephritis - reflect weeks of antigenemia. Janeway lesions, by contrast, are painless septic emboli and are more typical of acute S. aureus disease. Mnemonic: Osler is Ouchy, Janeway is not."),
    ]),
    S("S. gallolyticus and S. anginosus", [
      H("Streptococcus gallolyticus (formerly S. bovis biotype I) bacteremia or endocarditis demands a colonoscopy: it is strongly associated with colorectal adenoma and carcinoma. It is bile esculin-positive like enterococci but, unlike them, does not grow in 6.5% salt."),
      H("The S. anginosus (milleri) group - S. anginosus, S. intermedius, S. constellatus - has a distinct tendency to form abscesses in the brain, liver, lung, and pleura. Cultures often smell of butterscotch or caramel."),
    ]),
  ]),

E("enterococcus", "Enterococcus faecalis & faecium", "Gram-Positive Cocci",
  "Hardy gut commensals whose importance is almost entirely about resistance: intrinsically resistant to cephalosporins, and the source of vancomycin resistance genes.",
  aka=["enterococci", "VRE", "group D strep"],
  keywords=["UTI", "biliary", "endocarditis", "vancomycin resistance", "vanA", "bile esculin", "cephalosporin"],
  treatment="E. faecalis: ampicillin, often with ceftriaxone for endocarditis. VRE (usually E. faecium): linezolid or daptomycin.",
  quick=[("Stain", "Gram-positive cocci in pairs and short chains"),
         ("Hemolysis", "Usually gamma"),
         ("Bile esculin", "Positive"),
         ("6.5% NaCl", "Grows (unlike S. gallolyticus)"),
         ("PYR", "Positive"),
         ("Cephalosporins", "Intrinsically resistant")],
  sections=[
    S("Identification and ecology", [
      H("Enterococci grow in 6.5% sodium chloride and in 40% bile, and hydrolyze esculin. Both enterococci and S. gallolyticus are bile esculin-positive; only enterococci tolerate 6.5% salt."),
      P("This hardiness is ecological: they are gut and biliary commensals that survive bile, wide temperature ranges, drying, and surface disinfection, which is why they persist on hospital surfaces and on the hands of staff."),
    ]),
    S("Clinical disease", [
      H("Urinary tract infection (especially catheter-associated), biliary and intra-abdominal infection, and subacute endocarditis, usually following genitourinary or gastrointestinal instrumentation."),
      P("E. faecalis causes most enterococcal infections and is usually ampicillin-susceptible. E. faecium causes fewer infections but accounts for most ampicillin- and vancomycin-resistant isolates."),
    ]),
    S("Resistance mechanisms", [
      H("Intrinsic cephalosporin resistance comes from low-affinity penicillin-binding proteins, chiefly PBP5. Cephalosporin exposure therefore selects for enterococcal superinfection. The LAME mnemonic lists what cephalosporins miss: Listeria, Atypicals, MRSA, Enterococci."),
      P("Aminoglycosides cannot cross the enterococcal envelope alone, so they are useless as monotherapy; a cell-wall agent must first breach the wall, which is the classical basis of ampicillin-plus-gentamicin synergy. High-level aminoglycoside resistance abolishes that synergy, and ampicillin plus ceftriaxone - two beta-lactams saturating different PBPs - is now preferred for E. faecalis endocarditis because it is equally effective and far less nephrotoxic."),
      H("vanA resistance replaces the terminal D-Ala-D-Ala of the peptidoglycan precursor with D-Ala-D-lactate. Vancomycin binds this depsipeptide about a thousand times less tightly, so it can no longer block transpeptidation. This is the operon that, transferred to S. aureus, creates VRSA."),
    ]),
  ]),

E("c-diphtheriae", "Corynebacterium diphtheriae", "Gram-Positive Rods",
  "A toxin, not an invasion: a pharyngeal pseudomembrane plus myocarditis and neuritis from a phage-encoded ADP-ribosyltransferase.",
  aka=["diphtheria"],
  keywords=["pseudomembrane", "bull neck", "myocarditis", "toxoid", "Elek test", "tellurite"],
  treatment="Equine antitoxin on clinical suspicion, without waiting for cultures, plus erythromycin or penicillin, airway protection, cardiac monitoring, and later active immunization.",
  quick=[("Stain", "Club-shaped Gram-positive rods in V and L 'Chinese letter' arrangements"),
         ("Granules", "Metachromatic (Babes-Ernst) volutin granules"),
         ("Media", "Loeffler medium; black colonies on cystine-tellurite"),
         ("Toxin test", "Elek immunodiffusion or PCR for tox"),
         ("Vaccine", "Toxoid - prevents disease, not carriage")],
  images=[("cdiphtheriae-gram.jpg", "Club-shaped rods in angular 'Chinese letter' clusters."),
          ("diphtheria-membrane.jpg", "The adherent gray pharyngeal pseudomembrane.")],
  sections=[
    S("Toxin mechanism", [
      H("Diphtheria toxin is an A-B toxin whose A fragment ADP-ribosylates elongation factor 2, halting host protein synthesis. Pseudomonas exotoxin A uses exactly the same mechanism."),
      P("Fragment B binds the heparin-binding EGF-like growth factor receptor and delivers fragment A into the cytosol. EF-2 is required to translocate the growing peptide along the ribosome, so modifying it shuts down translation completely. A single molecule of fragment A can inactivate enough EF-2 to kill a cell, which is why so little toxin does so much damage."),
      H("The tox gene is carried by a lysogenic beta-corynephage, so only phage-infected strains are toxigenic. Toxin production is repressed by iron acting through the DtxR regulator, and rises sharply when iron is scarce - as it is on an inflamed mucosal surface."),
    ]),
    S("Clinical disease", [
      H("A thick, adherent gray pseudomembrane over the tonsils and pharynx that bleeds when scraped, with cervical lymphadenopathy producing a 'bull neck.' The membrane is fibrin, dead epithelium, and neutrophils, and it can obstruct the airway."),
      P("Absorbed toxin reaches the heart and nerves. Myocarditis with arrhythmia and heart block appears in the second week and is the usual cause of death; neuritis begins with palatal paralysis and blurred vision and may progress to a peripheral polyneuropathy that eventually recovers."),
      P("Antitoxin neutralizes only toxin that is still circulating, never toxin already internalized, which is why it is given on clinical suspicion rather than after laboratory confirmation. Antibiotics stop further toxin production and transmission but do not substitute for antitoxin. Disease does not confer immunity, so survivors still need the toxoid."),
    ]),
    S("Other corynebacteria", [
      P("Non-diphtherial corynebacteria ('diphtheroids') are usually skin contaminants, but C. jeikeium causes genuine, highly drug-resistant bacteremia in neutropenic patients with indwelling lines, and is treated with vancomycin. C. minutissimum causes erythrasma, a red-brown intertriginous patch that fluoresces coral-red under Wood lamp."),
    ]),
  ]),

E("listeria", "Listeria monocytogenes", "Gram-Positive Rods",
  "A facultative intracellular rod that grows in the refrigerator, crosses the placenta and the blood-brain barrier, and resists every cephalosporin.",
  aka=["listeriosis"],
  keywords=["neonatal meningitis", "pregnancy", "deli meat", "soft cheese", "tumbling motility", "actin rockets", "ampicillin"],
  treatment="Ampicillin, often with gentamicin for synergy. TMP-SMX for penicillin allergy. Cephalosporins never work.",
  quick=[("Stain", "Small Gram-positive rods"),
         ("Motility", "Tumbling at 25°C, umbrella pattern in semisolid agar; non-motile at 37°C"),
         ("Growth", "Multiplies at 4°C (cold enrichment)"),
         ("Catalase", "Positive"),
         ("Hemolysis", "Narrow beta zone; CAMP-positive"),
         ("Cephalosporins", "Intrinsically resistant")],
  images=[("listeria-gram.jpg", "Short Gram-positive rods, easily mistaken for diphtheroids.")],
  sections=[
    S("Cell biology - the reason it matters", [
      H("Listeria is a facultative intracellular organism that spreads directly from cell to cell, so antibody and complement contribute little and control depends on cell-mediated immunity. That is why the risk groups are neonates, pregnant women, the elderly, and anyone on steroids, TNF inhibitors, or chemotherapy."),
      P("Internalin A binds E-cadherin on intestinal epithelium, placental syncytiotrophoblast, and brain endothelium - which is a compact explanation for gut invasion, transplacental passage, and meningitis in one molecule. Once phagocytosed, listeriolysin O, a cholesterol-dependent pore-forming toxin, ruptures the phagosome and releases the organism into the cytosol before it can be killed."),
      P("In the cytosol, the surface protein ActA mimics host nucleation-promoting factors and recruits the Arp2/3 complex to polymerize an actin 'comet tail.' The resulting propulsion drives the bacterium into the neighboring cell inside a double membrane, which it again lyses. Because the organism never re-enters the extracellular space, it is invisible to antibody."),
    ]),
    S("Clinical disease", [
      H("In pregnancy, maternal illness is usually a mild flu-like febrile episode, but transplacental infection causes miscarriage, stillbirth, preterm labor, or granulomatosis infantiseptica - disseminated microabscesses and granulomas in the newborn."),
      H("It is a leading cause of neonatal meningitis (with group B strep and E. coli) and of meningitis in adults over 50 and the immunosuppressed. CSF often shows a mixed or mononuclear pleocytosis rather than a purely neutrophilic one."),
      P("Transmission is food-borne: unpasteurized milk and soft cheeses, deli meats, hot dogs, smoked fish, and cut melon. Its ability to grow at refrigerator temperature is what makes ready-to-eat refrigerated food the classic vehicle."),
    ]),
  ]),

E("bacillus", "Bacillus anthracis & B. cereus", "Gram-Positive Rods",
  "Large aerobic spore-formers: one a tripartite-toxin bioterror agent, the other a cause of two distinct food poisonings.",
  aka=["anthrax", "B. cereus", "B. anthracis", "fried rice syndrome"],
  keywords=["eschar", "woolsorter", "widened mediastinum", "cereulide", "spores", "poly-D-glutamate"],
  treatment="Anthrax: ciprofloxacin or doxycycline; severe systemic disease adds a protein synthesis inhibitor and antitoxin. B. cereus: supportive.",
  quick=[("Stain", "Large boxcar-shaped Gram-positive rods with spores"),
         ("B. anthracis", "Non-motile; poly-D-glutamate (protein) capsule"),
         ("B. cereus", "Motile; no such capsule"),
         ("Oxygen", "Aerobic (Clostridia are the anaerobic spore formers)"),
         ("Spores", "Survive decades in soil; need autoclaving to kill")],
  images=[("anthrax-gram.jpg", "Boxcar-shaped Gram-positive rods in chains."),
          ("anthrax-eschar.jpg", "Cutaneous anthrax: a painless black eschar with marked surrounding edema.")],
  sections=[
    S("Anthrax toxins", [
      H("Anthrax has a tripartite toxin. Protective antigen forms the pore that delivers the two enzymes. Edema factor is a calmodulin-dependent adenylyl cyclase that raises cAMP and causes the massive edema; lethal factor is a zinc metalloprotease that cleaves MAP kinase kinases, killing cells and driving shock."),
      H("It is the only Bacillus with a capsule of poly-D-glutamic acid - a polypeptide, not a polysaccharide. Being D-amino acid based, it resists proteolysis and is poorly immunogenic, so antibody responses to it are weak. The vaccine therefore targets protective antigen instead."),
    ]),
    S("Anthrax syndromes", [
      H("Cutaneous anthrax (>95% of cases): a painless papule becomes a vesicle and then a black eschar with impressive non-pitting edema. Painlessness is the key clue. Excision is avoided; antibiotics are the treatment."),
      H("Inhalational anthrax ('woolsorter's disease'): spores are carried by macrophages to mediastinal nodes, producing hemorrhagic mediastinitis with a widened mediastinum and bloody pleural effusions on imaging. There is no true pneumonia. Hemorrhagic meningitis may follow, and mortality is very high."),
    ]),
    S("Bacillus cereus", [
      H("Two syndromes from two toxins. Cereulide is preformed in food, heat-stable, and causes vomiting 1-6 hours after eating - classically reheated fried rice. A separate heat-labile enterotoxin is made in the small bowel and causes watery diarrhea at 8-16 hours."),
      P("B. cereus also causes severe keratitis after eye trauma or in contact lens wearers, and catheter-related bacteremia in the immunocompromised; its spores survive routine disinfection."),
    ]),
    S("Spore biology", [
      H("Endospores have a dehydrated core stabilized by calcium dipicolinate and small acid-soluble proteins that shield DNA, plus a cortex and keratin-like coat. They survive boiling, drying, radiation, and alcohol, and require autoclaving at 121°C or ethylene oxide. This is why alcohol hand gel does not kill C. difficile spores."),
    ]),
  ]),

E("clostridia", "Clostridium Species", "Gram-Positive Rods",
  "Anaerobic spore-formers defined by their toxins: tetanus, botulism, gas gangrene, and antibiotic-associated colitis.",
  aka=["C. tetani", "C. botulinum", "C. perfringens", "C. difficile", "Clostridioides difficile"],
  keywords=["tetanospasmin", "botulinum", "lecithinase", "gas gangrene", "pseudomembranous colitis", "SNARE"],
  treatment="Tetanus: debridement, metronidazole, immune globulin, benzodiazepines. Botulism: antitoxin (BabyBIG in infants). Gas gangrene: debridement plus penicillin and clindamycin. C. difficile: oral vancomycin or fidaxomicin.",
  quick=[("Stain", "Gram-positive rods, anaerobic, spore-forming"),
         ("C. perfringens", "Double zone of hemolysis; Nagler (lecithinase) positive"),
         ("C. difficile", "Toxins A and B; detected by NAAT or EIA with GDH"),
         ("Spores", "Alcohol-resistant - requires soap and water, bleach surfaces")],
  images=[("ctetani.jpg", "Clostridium tetani with terminal spores giving the drumstick appearance."),
          ("opisthotonus.jpg", "Opisthotonus - the arched rigidity of tetanus."),
          ("gas-gangrene.jpg", "Clostridial myonecrosis with gas in the soft tissues."),
          ("pmc.jpg", "Pseudomembranous colitis: yellow-white plaques on the colonic mucosa.")],
  sections=[
    S("Tetanus and botulism - one target, opposite results", [
      H("Both tetanospasmin and botulinum toxin are zinc metalloproteases that cleave SNARE proteins and block synaptic vesicle fusion. The difference is location: botulinum acts at the neuromuscular junction and autonomic synapses, blocking acetylcholine release and causing flaccid paralysis; tetanospasmin acts on inhibitory interneurons in the spinal cord, blocking glycine and GABA release and causing rigidity."),
      P("Tetanospasmin is made in a contaminated wound, binds motor nerve terminals, and travels by retrograde axonal transport to the cord - the bacteria themselves never leave the wound. The result is trismus, risus sardonicus, opisthotonus, and autonomic instability, with sensation and consciousness fully intact."),
      H("Botulism comes in three forms: food-borne from preformed toxin in home-canned goods, wound botulism, and infant botulism from ingested spores (classically honey) that germinate in a colon without a protective microbiome. Infants get human-derived immune globulin (BabyBIG); aminoglycosides are avoided because they worsen neuromuscular blockade."),
    ]),
    S("Clostridium perfringens", [
      H("Alpha toxin is a lecithinase (phospholipase C) that hydrolyzes membrane phospholipids, producing myonecrosis, hemolysis, and platelet destruction. Gas gangrene presents with severe pain, bronze discoloration, hemorrhagic bullae, and crepitus from fermentative gas."),
      P("Treatment is urgent, wide surgical debridement - the tissue is dead and avascular, so antibiotics alone cannot reach the organisms - plus penicillin and clindamycin. The Nagler reaction on egg yolk agar demonstrates lecithinase activity in the laboratory."),
      H("A separate syndrome is food poisoning: large numbers of vegetative cells in reheated meat or gravy sporulate in the small bowel and release enterotoxin, giving watery diarrhea and cramps at 8-16 hours with little vomiting, resolving within a day."),
    ]),
    S("Clostridioides difficile", [
      H("Toxins A (enterotoxin) and B (cytotoxin) glucosylate Rho-family GTPases. Rho normally maintains the actin cytoskeleton, so inactivating it collapses actin filaments, breaks tight junctions, and rounds up and kills enterocytes. The result is the pseudomembrane of fibrin, mucin, and neutrophils."),
      P("Risk follows antibiotic disruption of the colonic microbiome - clindamycin, fluoroquinolones, and broad-spectrum cephalosporins are classic - as well as proton pump inhibitors, age, and hospitalization. Diagnosis uses NAAT for toxin genes or an EIA for toxin combined with glutamate dehydrogenase; asymptomatic carriers are neither tested nor treated."),
      H("First-line treatment is oral vancomycin or fidaxomicin, both of which stay in the colonic lumen. Metronidazole is now second-line. Fulminant disease with ileus adds intravenous metronidazole and rectal vancomycin. Multiply recurrent disease is cured in about 85-90% by fecal microbiota transplantation, which restores colonization resistance."),
    ]),
  ]),

E("actino-nocardia", "Actinomyces & Nocardia", "Gram-Positive Rods",
  "Two branching filamentous bacteria that are easy to confuse and are separated by three questions: oxygen, acid-fastness, and where the patient got it.",
  aka=["actinomycosis", "nocardiosis", "sulfur granules", "Actinomyces", "Nocardia"],
  keywords=["branching filaments", "sulfur granules", "sinus tract", "brain abscess", "TMP-SMX", "partially acid-fast"],
  treatment="Actinomyces: prolonged high-dose penicillin (months). Nocardia: TMP-SMX, often with a carbapenem or amikacin, for 6-12 months.",
  quick=[("Actinomyces", "Anaerobic, NOT acid-fast, normal oral flora, penicillin"),
         ("Nocardia", "Aerobic, partially acid-fast, soil, TMP-SMX"),
         ("Mnemonic", "SNAP - Sulfa for Nocardia, Actinomyces for Penicillin"),
         ("Both", "Gram-positive branching filaments")],
  images=[("actinomyces.jpg", "Branching filamentous Gram-positive rods."),
          ("actino-histo.jpg", "A sulfur granule ringed by neutrophils - a bacterial colony, not mineral sulfur."),
          ("nocardia.jpg", "Nocardia: beaded, branching, partially acid-fast filaments.")],
  sections=[
    S("Actinomyces israelii", [
      H("An anaerobic, non-acid-fast branching rod that is normal oral flora. Cervicofacial actinomycosis follows dental extraction, trauma, or poor dentition and produces an indurated mass that crosses tissue planes and drains through sinus tracts."),
      P("The yellow 'sulfur granules' in the pus are macroscopic colonies of filaments with surrounding neutrophils - the name refers only to their color, as they contain no elemental sulfur. Actinomyces also causes thoracic disease after aspiration, abdominal disease after appendicitis or surgery, and pelvic disease associated with intrauterine devices."),
      P("Because the organism is walled off in dense fibrous tissue with poor drug penetration, treatment is high-dose penicillin for months, often with surgical drainage."),
    ]),
    S("Nocardia", [
      H("An aerobic, partially acid-fast (weakly acid-fast, because it has shorter-chain mycolic acids) soil organism. It causes pulmonary disease that mimics tuberculosis, frequently cavitary, in immunocompromised hosts - transplant recipients, patients on chronic steroids, and those with malignancy or advanced HIV."),
      H("Nocardia disseminates to the brain in up to a third of immunocompromised patients, often without neurologic symptoms, so brain imaging is standard whenever pulmonary nocardiosis is diagnosed."),
      P("It also causes cutaneous disease after soil inoculation, including actinomycetoma, a chronic grain-forming infection of the foot. Distinguishing actinomycetoma (bacterial, responds to TMP-SMX) from eumycetoma (fungal, needs antifungals and surgery) changes management entirely."),
    ]),
  ]),
]
