"""Encyclopedia: Gram-negative cocci, respiratory rods, and enteric rods."""
from ecore import E, S, P, H

ENTRIES = [
E("neisseria", "Neisseria meningitidis & gonorrhoeae", "Gram-Negative Cocci",
  "Two oxidase-positive diplococci with opposite strategies: one encapsulated and vaccine-preventable, one endlessly antigenically variable and not.",
  aka=["meningococcus", "gonococcus", "gonorrhea", "meningitis"],
  keywords=["Waterhouse-Friderichsen", "petechiae", "urethritis", "PID", "complement deficiency", "IgA protease", "Thayer-Martin"],
  treatment="Meningococcal disease: ceftriaxone. Gonorrhea: one IM dose of ceftriaxone (500 mg), plus doxycycline if chlamydia is not excluded.",
  quick=[("Stain", "Gram-negative diplococci, kidney-bean shaped"),
         ("Oxidase", "Positive"),
         ("Sugars", "MeninGococcus: Maltose + Glucose; Gonococcus: Glucose only"),
         ("Media", "Thayer-Martin (VPN: vancomycin, polymyxin, nystatin)"),
         ("Capsule", "Meningococcus yes; gonococcus no"),
         ("Vaccine", "MenACWY and MenB; none for gonorrhea")],
  images=[("gc-gram.jpg", "Gram-negative diplococci inside neutrophils in urethral exudate."),
          ("nmen-gram.jpg", "Meningococci in CSF, many intracellular."),
          ("nmen-csf.jpg", "Purulent CSF in meningococcal meningitis."),
          ("wfs-adrenal.jpg", "Waterhouse-Friderichsen syndrome: bilateral adrenal hemorrhage."),
          ("ophthalmia.jpg", "Ophthalmia neonatorum from N. gonorrhoeae.")],
  sections=[
    S("Shared biology", [
      P("Both are fastidious, capnophilic (needing added CO2) Gram-negative diplococci that colonize mucosal surfaces. Both secrete IgA1 protease, which cleaves secretory IgA at the hinge and permits attachment to mucosal epithelium, and both use type IV pili for adherence and for DNA uptake by natural transformation."),
      P("Their endotoxin is lipooligosaccharide (LOS) rather than the full LPS of enteric rods: it has lipid A and a core but no long repeating O antigen. Lipid A is still the toxic moiety, and meningococcal LOS is shed in large amounts in membrane blebs, which is why meningococcemia produces such fulminant shock."),
      H("Complement is the critical defense. Deficiency of the terminal components C5-C9 (the membrane attack complex), or treatment with eculizumab, causes recurrent Neisseria bacteremia - these are the only organisms for which MAC lysis is essential, because their thin wall and outer membrane are directly vulnerable."),
    ]),
    S("Neisseria meningitidis", [
      H("Carried asymptomatically in the nasopharynx, especially by adolescents in crowded settings such as dormitories and barracks. Invasive disease occurs when a susceptible person without bactericidal anticapsular antibody acquires a new virulent strain."),
      H("Meningococcemia produces abrupt fever with a petechial or purpuric rash, DIC, and shock. Waterhouse-Friderichsen syndrome is bilateral adrenal hemorrhage with acute adrenal insufficiency superimposed on the septic shock."),
      P("The polysaccharide capsule is the main virulence factor and the vaccine target. MenACWY conjugate vaccines cover serogroups A, C, W, and Y. Serogroup B could not be approached this way because its capsule is polysialic acid that mimics human neural cell adhesion molecule - it is essentially a self antigen - so MenB vaccines use surface proteins such as factor H binding protein instead."),
      P("Close contacts (household, childcare, anyone exposed to oral secretions) receive chemoprophylaxis with rifampin, ciprofloxacin, or ceftriaxone, which eradicates nasopharyngeal carriage. Penicillin treats disease but does not reliably clear carriage."),
    ]),
    S("Neisseria gonorrhoeae", [
      H("No capsule and no vaccine. The organism varies its pilin and Opa surface proteins by recombination among silent gene cassettes, so antibody from one infection does not protect against the next - repeat infection is the rule."),
      H("Men get purulent urethritis; women are often asymptomatic or have cervicitis, which is why untreated infection ascends to cause pelvic inflammatory disease, tubo-ovarian abscess, infertility, ectopic pregnancy, and Fitz-Hugh-Curtis perihepatitis."),
      P("Disseminated gonococcal infection takes two forms. The arthritis-dermatitis syndrome has migratory polyarthralgia, tenosynovitis, and scattered pustular lesions, with frequently negative blood and joint cultures, so NAAT of mucosal sites is the best test. The purulent form is a true septic monoarthritis with positive synovial cultures."),
      H("Ophthalmia neonatorum is a purulent conjunctivitis in the first 2-5 days of life, prevented by erythromycin ointment at birth; chlamydial conjunctivitis appears later, at 5-14 days. Resistance has eliminated penicillins and fluoroquinolones, leaving ceftriaxone as the single recommended agent."),
    ]),
  ]),

E("haemophilus", "Haemophilus influenzae", "Gram-Negative Rods",
  "Once the leading cause of childhood meningitis and epiglottitis; conjugate vaccination turned it into a nontypeable mucosal pathogen.",
  aka=["Hib", "H. flu", "H. ducreyi", "H. influenzae"],
  keywords=["epiglottitis", "thumbprint sign", "otitis media", "COPD exacerbation", "factor X", "factor V", "chocolate agar", "chancroid"],
  treatment="Invasive disease: ceftriaxone. Otitis/sinusitis: amoxicillin-clavulanate. Contacts of invasive Hib: rifampin.",
  quick=[("Stain", "Small pleomorphic Gram-negative coccobacilli"),
         ("Growth", "Requires factor X (hemin) and factor V (NAD)"),
         ("Media", "Chocolate agar; satellites around S. aureus on blood agar"),
         ("Capsule", "Type b = polyribosylribitol phosphate (PRP)"),
         ("Vaccine", "PRP conjugated to a carrier protein, from 2 months")],
  images=[("hflu-gram.jpg", "Small pleomorphic Gram-negative coccobacilli."),
          ("epiglottitis.jpg", "Lateral neck film: the thumbprint sign of a swollen epiglottis.")],
  sections=[
    S("Growth requirements", [
      H("H. influenzae needs factor X (hemin) and factor V (NAD). Sheep blood agar contains NADases, so it grows only as satellite colonies beside S. aureus, which lyses red cells and releases NAD. Chocolate agar is blood agar heated to lyse the cells and release both factors."),
    ]),
    S("Disease before and after the vaccine", [
      H("Type b, whose capsule is polyribosylribitol phosphate, caused meningitis, epiglottitis, septic arthritis, and periorbital cellulitis in young children. Conjugate vaccination has nearly eliminated it."),
      H("Epiglottitis is an airway emergency: drooling, dysphagia, distress, a muffled 'hot potato' voice, and the tripod position. The pharynx is not examined and the child is taken to the operating room for controlled intubation, because examination can precipitate complete obstruction. The lateral neck film shows the thumbprint sign."),
      H("Most remaining disease is from nontypeable (unencapsulated) strains, which the vaccine does not cover: otitis media, sinusitis, conjunctivitis, and exacerbations of COPD. They spread locally across mucosa rather than invading the blood."),
    ]),
    S("Haemophilus ducreyi", [
      H("Causes chancroid: a painful genital ulcer with ragged, undermined edges and a soft base, with tender, suppurative inguinal buboes. Mnemonic: you 'do cry' with H. ducreyi. Gram stain shows a 'school of fish' pattern. Treatment is a single dose of azithromycin or ceftriaxone."),
    ]),
  ]),

E("bordetella", "Bordetella pertussis", "Gram-Negative Rods",
  "Whooping cough: a toxin-driven illness in three stages where antibiotics help transmission far more than they help the cough.",
  aka=["pertussis", "whooping cough"],
  keywords=["paroxysmal cough", "whoop", "lymphocytosis", "Tdap", "apnea", "Bordet-Gengou"],
  treatment="Azithromycin (also for close contacts). Prevention: DTaP in children, Tdap in adults and in every pregnancy at 27-36 weeks.",
  quick=[("Stain", "Small Gram-negative coccobacillus"),
         ("Media", "Bordet-Gengou (potato) or Regan-Lowe (charcoal) agar"),
         ("Blood count", "Marked absolute lymphocytosis"),
         ("Diagnosis", "Nasopharyngeal PCR")],
  images=[("bpertussis.jpg", "Bordetella pertussis, a small Gram-negative coccobacillus.")],
  sections=[
    S("Toxins", [
      H("Pertussis toxin ADP-ribosylates the inhibitory alpha subunit of Gi. With Gi disabled, adenylyl cyclase is no longer restrained and intracellular cAMP rises. This impairs neutrophil and lymphocyte chemotaxis and blocks lymphocyte entry into lymph nodes, producing the characteristic peripheral lymphocytosis."),
      P("Three other factors matter. Adenylate cyclase toxin is itself an enzyme that enters phagocytes and generates cAMP, disabling them. Tracheal cytotoxin, a peptidoglycan fragment, kills ciliated respiratory epithelial cells - the loss of the mucociliary escalator is the direct cause of the intractable cough. Filamentous hemagglutinin and pertactin mediate attachment; both are components of the acellular vaccine."),
    ]),
    S("Clinical course", [
      H("Three stages: catarrhal (1-2 weeks, indistinguishable from a cold and the most contagious), paroxysmal (2-6 weeks, fits of coughing with an inspiratory whoop and post-tussive vomiting), and convalescent (weeks to months of a waning cough)."),
      H("Antibiotics alter the illness only when started in the catarrhal stage. By the paroxysmal stage the symptoms are driven by epithelial damage already done, so treatment is given mainly to stop transmission; close contacts get prophylaxis regardless."),
      P("In infants under six months the presentation is often apnea, cyanosis, or gagging rather than a whoop, and this is the group with the highest mortality. Because infants are not fully immunized until several months of age, protection depends on maternal Tdap in the third trimester - transferring antibody across the placenta - and on cocooning close contacts."),
    ]),
  ]),

E("legionella", "Legionella pneumophila", "Gram-Negative Rods",
  "An intracellular water-borne pathogen that stains poorly, grows on special medium, and presents with pneumonia plus diarrhea, confusion, and hyponatremia.",
  aka=["Legionnaires disease", "Pontiac fever"],
  keywords=["hyponatremia", "air conditioning", "cooling tower", "urinary antigen", "charcoal yeast extract", "smoker"],
  treatment="Azithromycin or a respiratory fluoroquinolone such as levofloxacin. Beta-lactams fail.",
  quick=[("Stain", "Stains poorly with Gram stain; silver stain shows it"),
         ("Media", "Buffered charcoal yeast extract with iron and cysteine"),
         ("Rapid test", "Urinary antigen - serogroup 1 only"),
         ("Transmission", "Aerosols from water; no person-to-person spread"),
         ("Labs", "Hyponatremia, elevated transaminases")],
  images=[("legionella.jpg", "Legionella pneumophila - poorly visualized by routine Gram stain.")],
  sections=[
    S("Why it behaves as it does", [
      H("Legionella stains poorly with the Gram method because of its branched-chain cell wall fatty acids, so the classic finding is a sputum smear full of neutrophils with no visible organisms. It requires buffered charcoal yeast extract agar supplemented with iron and cysteine."),
      P("It is a facultative intracellular parasite of freshwater amoebae; humans are an accidental host whose alveolar macrophages resemble amoebae closely enough for the same strategy to work. A Dot/Icm type IV secretion system injects effectors that remodel the phagosome, prevent lysosomal fusion, and recruit endoplasmic reticulum membrane to build a replicative vacuole."),
      H("Because the organism lives inside cells, effective drugs must penetrate cells - macrolides and fluoroquinolones do, beta-lactams do not. That is the practical consequence of its cell biology."),
    ]),
    S("Clinical syndromes", [
      H("Legionnaires disease: pneumonia with high fever, relative bradycardia, diarrhea, confusion, hyponatremia, and elevated transaminases, classically in an older smoker after exposure to aerosolized water from cooling towers, hot tubs, or plumbing."),
      H("Pontiac fever is the same organism producing a self-limited flu-like illness without pneumonia, resolving in days without treatment."),
      P("The urinary antigen test detects serogroup 1 only, which accounts for most but not all clinical disease, and stays positive for weeks. There is no person-to-person transmission, so outbreak control targets the water system, not the patients."),
    ]),
  ]),

E("pseudomonas", "Pseudomonas aeruginosa", "Gram-Negative Rods",
  "An environmental opportunist with a huge genome, intrinsic multidrug resistance, and a syndrome for nearly every compromised host.",
  aka=["pseudomonas"],
  keywords=["burn wound", "cystic fibrosis", "otitis externa", "ecthyma gangrenosum", "hot tub folliculitis", "exotoxin A", "pyocyanin"],
  treatment="Antipseudomonal beta-lactam (piperacillin-tazobactam, cefepime, ceftazidime, meropenem) - note ertapenem does NOT cover it. Severe infection often uses two agents initially.",
  quick=[("Stain", "Gram-negative rod, single polar flagellum"),
         ("Oxidase", "Positive"),
         ("Lactose", "Non-fermenter (obligate aerobe)"),
         ("Pigments", "Pyocyanin (blue-green), pyoverdine (yellow-green)"),
         ("Odor", "Grape-like or corn tortilla"),
         ("Growth", "42°C; thrives in water, sinks, ventilators")],
  images=[("pseudomonas-pigment.jpg", "Blue-green pyocyanin pigment diffusing into the agar.")],
  sections=[
    S("Virulence", [
      H("Exotoxin A ADP-ribosylates elongation factor 2 and halts host protein synthesis - the same mechanism as diphtheria toxin."),
      P("Phospholipase C, elastases, and proteases destroy tissue and are largely responsible for the hemorrhagic necrosis of ecthyma gangrenosum. Pyocyanin is not merely a pigment: it generates reactive oxygen species that damage host cells and impair ciliary function. A type III secretion system injects ExoU and ExoS directly into host cells."),
      H("In cystic fibrosis, chronic airway infection selects mucoid strains that overproduce alginate, forming a biofilm. Biofilm bacteria grow slowly, tolerate antibiotics and phagocytes, and cannot realistically be eradicated - therapy suppresses rather than cures, using inhaled tobramycin or aztreonam."),
    ]),
    S("Clinical syndromes", [
      H("Pneumonia (ventilator-associated and in cystic fibrosis), burn wound infection, catheter-associated UTI, and neutropenic sepsis. Ecthyma gangrenosum - a painless necrotic ulcer with a black eschar arising from a pustule - is essentially pathognomonic of pseudomonal bacteremia in a neutropenic patient."),
      H("Malignant (necrotizing) otitis externa in older diabetics: severe ear pain with granulation tissue at the bone-cartilage junction, progressing to skull base osteomyelitis with cranial nerve palsies. It needs systemic therapy, not drops."),
      P("Other associations worth carrying: hot tub folliculitis (a pruritic pustular rash sparing areas covered by a swimsuit), osteomyelitis after a nail puncture through a sneaker, keratitis in contact lens wearers, and endocarditis in people who inject drugs."),
    ]),
    S("Resistance", [
      H("Resistance is intrinsic and multifactorial: a relatively impermeable outer membrane with restrictive porins, constitutive and inducible efflux pumps (MexAB-OprM), an inducible chromosomal AmpC beta-lactamase, and a genome large enough to acquire almost any additional mechanism."),
      P("Because it can develop resistance during therapy, severe infection is often started on two active agents from different classes, then de-escalated once susceptibilities return. Ertapenem is the one carbapenem without antipseudomonal activity."),
    ]),
  ]),

E("e-coli", "Escherichia coli", "Enteric Gram-Negative Rods",
  "One species, many diseases: the leading cause of UTI and Gram-negative sepsis, plus five distinct diarrheal pathotypes.",
  aka=["E. coli", "EHEC", "ETEC", "EIEC", "EPEC", "STEC", "O157:H7"],
  keywords=["UTI", "traveler's diarrhea", "HUS", "neonatal meningitis", "K1 capsule", "Shiga toxin", "sepsis"],
  treatment="Cystitis: nitrofurantoin, TMP-SMX, or fosfomycin. Pyelonephritis/sepsis: ceftriaxone, or a carbapenem if ESBL. EHEC: supportive only - never antibiotics.",
  quick=[("Stain", "Gram-negative rod, facultative anaerobe"),
         ("Lactose", "Fermenter - pink on MacConkey, green sheen on EMB"),
         ("Antigens", "O (somatic), H (flagellar), K (capsular)"),
         ("Neonatal meningitis", "K1 capsule"),
         ("EHEC", "Does not ferment sorbitol; Shiga-like toxin")],
  images=[("ecoli-emb.jpg", "Green metallic sheen of E. coli on eosin-methylene blue agar."),
          ("macconkey.jpg", "Pink (lactose-fermenting) versus colorless colonies on MacConkey agar.")],
  sections=[
    S("Extraintestinal disease", [
      H("The most common cause of urinary tract infection at every age and of Gram-negative sepsis. Uropathogenic strains use type 1 fimbriae to colonize the bladder and P fimbriae, which bind the P blood group antigen on uroepithelium, to ascend to the kidney and cause pyelonephritis."),
      H("Neonatal meningitis is caused by strains bearing the K1 capsule, a polysialic acid that resembles host neural antigen and resists complement - the same immunologic trick used by serogroup B meningococcus."),
      P("Endotoxin from the outer membrane drives Gram-negative sepsis. Lipid A engages CD14 and the TLR4/MD-2 complex on macrophages, releasing IL-1, IL-6, and TNF-alpha, which produce fever and vasodilation; complement activation gives C3a and C5a, and tissue factor expression drives DIC."),
    ]),
    S("Diarrheal pathotypes", [
      H("ETEC (traveler's diarrhea): heat-labile toxin activates adenylyl cyclase and raises cAMP, like cholera toxin; heat-stable toxin activates guanylate cyclase and raises cGMP. Watery diarrhea, no invasion, no fever or blood. Mnemonic: Labile/Air (adenylate), Stable/Ground (guanylate)."),
      H("EHEC (STEC), typically O157:H7 from undercooked beef: Shiga-like toxin cleaves an adenine from 28S rRNA, halting protein synthesis. It produces bloody diarrhea without much fever and can cause hemolytic uremic syndrome - microangiopathic hemolytic anemia, thrombocytopenia, and acute kidney injury. Antibiotics and antimotility agents increase HUS risk and are avoided."),
      P("EIEC invades colonic mucosa and behaves like Shigella, causing dysentery with fever. EPEC attaches and effaces microvilli using a type III secretion system to insert its own receptor (Tir), causing watery diarrhea in infants. EAEC forms a stacked-brick aggregative pattern and causes persistent diarrhea."),
      P("EHEC is distinguished in the laboratory because O157:H7 does not ferment sorbitol, so it forms colorless colonies on sorbitol-MacConkey agar, and by direct assay for Shiga toxin."),
    ]),
  ]),

E("klebsiella", "Klebsiella, Enterobacter, Serratia & Proteus", "Enteric Gram-Negative Rods",
  "The remaining Enterobacterales worth knowing individually: one for currant-jelly sputum, two for inducible AmpC, and one for staghorn stones.",
  aka=["Klebsiella pneumoniae", "Proteus mirabilis", "Serratia marcescens", "Enterobacter", "Citrobacter", "Klebsiella", "Serratia", "Proteus"],
  keywords=["currant jelly", "aspiration", "liver abscess", "struvite", "swarming", "AmpC", "carbapenemase", "KPC"],
  treatment="Guided by susceptibility. ESBL producers need a carbapenem; carbapenemase producers need ceftazidime-avibactam or similar. Proteus UTI: usually TMP-SMX or a cephalosporin, plus stone removal.",
  quick=[("Klebsiella", "Lactose+, non-motile, large capsule, urease+"),
         ("Proteus", "Swarming motility, urease+, H2S+, burnt-chocolate odor"),
         ("Serratia", "Red pigment (prodigiosin), lactose-negative or slow"),
         ("Enterobacter/Citrobacter", "Lactose+, motile, inducible AmpC")],
  images=[("kleb-mucoid.jpg", "Klebsiella: strikingly mucoid colonies from its thick capsule."),
          ("proteus-swarm.jpg", "Proteus swarming in concentric waves across the agar."),
          ("he-agar.jpg", "Hektoen enteric agar - a selective medium for Salmonella and Shigella.")],
  sections=[
    S("Klebsiella pneumoniae", [
      H("A heavily encapsulated, non-motile lactose fermenter causing aspiration pneumonia in alcohol-dependent and diabetic patients, with thick 'currant jelly' sputum and a tendency to cavitate and form abscesses. It is also a common cause of UTI and of hospital-acquired infection."),
      P("The thick polysaccharide capsule gives the mucoid colony, resists phagocytosis, and explains the necrotizing, abscess-forming character of the pneumonia. Hypervirulent hypermucoviscous strains, most common in East Asia, cause community-acquired pyogenic liver abscess with metastatic spread to eye and meninges in people without biliary disease."),
      H("Klebsiella is a leading source of extended-spectrum beta-lactamases (ESBL), which hydrolyze third-generation cephalosporins and mandate a carbapenem, and of KPC carbapenemases, which defeat carbapenems as well."),
    ]),
    S("Proteus", [
      H("Proteus urease splits urea into ammonia and CO2, alkalinizing the urine. Alkaline urine precipitates magnesium ammonium phosphate (struvite), forming staghorn calculi that shelter bacteria and make cure impossible without removing the stone."),
      P("It swarms across agar in concentric waves because of coordinated flagellar differentiation, and has a distinctive burnt-chocolate odor. Other urease producers to keep together: Klebsiella, S. saprophyticus, Ureaplasma, H. pylori, and Nocardia - mnemonic PUNCH SK."),
    ]),
    S("AmpC and resistance logic", [
      H("Enterobacter, Serratia, Citrobacter, and related organisms carry an inducible chromosomal AmpC beta-lactamase. Exposure to a third-generation cephalosporin can select derepressed mutants, so an isolate reported susceptible may develop resistance during treatment. Cefepime or a carbapenem is preferred."),
      P("Serratia marcescens produces a red pigment, prodigiosin, and is a classic cause of hospital outbreaks from contaminated solutions, as well as endocarditis and osteomyelitis in people who inject drugs."),
    ]),
  ]),

E("salm-shig", "Salmonella & Shigella", "Enteric Gram-Negative Rods",
  "Two non-lactose-fermenting invaders separated by dose, dissemination, and whether antibiotics help or harm.",
  aka=["Salmonella typhi", "typhoid", "Shigella", "dysentery"],
  keywords=["rose spots", "dysentery", "reactive arthritis", "sickle cell osteomyelitis", "HUS", "gallbladder carrier"],
  treatment="Typhoid: ceftriaxone or azithromycin. Shigella: azithromycin or ceftriaxone. Non-typhoidal Salmonella gastroenteritis: supportive - antibiotics prolong carriage.",
  quick=[("Both", "Lactose non-fermenters, invade via M cells"),
         ("Salmonella", "Motile, H2S-producing, has a capsule (Vi in S. Typhi)"),
         ("Shigella", "Non-motile, no H2S, no capsule"),
         ("Dose", "Salmonella ~10^5; Shigella as few as 10-100"),
         ("Spread", "Salmonella disseminates; Shigella rarely does")],
  images=[("rose-spots.jpg", "Rose spots: faint salmon-colored macules on the trunk in typhoid fever."),
          ("shigella-stool.jpg", "Bloody mucoid stool of bacillary dysentery.")],
  sections=[
    S("What separates them", [
      H("Salmonella survives inside macrophages and disseminates, causing bacteremia, osteomyelitis (classically in sickle cell disease), and endovascular infection. Shigella invades epithelium, escapes into the cytosol, and spreads cell to cell using actin polymerization, but triggers macrophage pyroptosis rather than surviving inside them - so bacteremia is rare."),
      H("Shigella needs as few as 10-100 organisms because it is acid-resistant, which is why person-to-person spread in daycares and households is routine. Salmonella needs a much larger inoculum and is acid-labile, so reduced gastric acidity - proton pump inhibitors, antacids, gastrectomy - is a major risk factor."),
      P("Because Salmonella is motile and Shigella is not, and because Salmonella produces H2S while Shigella does not, they separate readily on Hektoen or XLD agar, where Salmonella forms black-centered colonies."),
    ]),
    S("Typhoid fever", [
      H("S. Typhi causes enteric fever: a week of rising fever with relative bradycardia, abdominal pain, and constipation more often than diarrhea, with rose spots on the trunk and hepatosplenomegaly. Complications in the third week are intestinal hemorrhage and perforation from necrosis of Peyer patches."),
      P("The Vi capsular antigen resists complement and phagocytosis and is the target of the injectable polysaccharide vaccine; an oral live attenuated Ty21a vaccine also exists. Humans are the only reservoir."),
      H("A minority become chronic gallbladder carriers, where the organism persists in biliary biofilm, often on gallstones, shedding in stool for years - the mechanism behind Typhoid Mary. Cholecystectomy may be required to clear it."),
    ]),
    S("Shigella and non-typhoidal Salmonella", [
      H("Shigella causes dysentery: fever, crampy pain, tenesmus, and scant bloody mucoid stools. S. dysenteriae type 1 produces Shiga toxin, which inactivates 28S rRNA and can cause HUS. Seizures occur in young children."),
      P("Non-typhoidal Salmonella (Enteritidis, Typhimurium) comes from poultry, eggs, and reptiles and causes self-limited gastroenteritis. Antibiotics are avoided in healthy hosts because they prolong fecal carriage without shortening illness; they are reserved for infants, the elderly, the immunocompromised, and those with sickle cell disease or prosthetic material."),
      P("Both organisms can trigger reactive arthritis - conjunctivitis, urethritis, and arthritis in an HLA-B27-positive host - as can Campylobacter and Yersinia."),
    ]),
  ]),

E("vibrio-campy-hpylori", "Vibrio, Campylobacter & Helicobacter", "Enteric Gram-Negative Rods",
  "Three curved Gram-negative rods: one causes secretory diarrhea, one is the leading bacterial enteritis, one causes ulcers and gastric cancer.",
  aka=["Vibrio cholerae", "Campylobacter jejuni", "Helicobacter pylori", "cholera", "V. vulnificus", "Vibrio", "Campylobacter", "Helicobacter", "H. pylori"],
  keywords=["rice water stool", "Guillain-Barre", "urease", "MALT lymphoma", "oysters", "poultry"],
  treatment="Cholera: aggressive oral rehydration; doxycycline shortens shedding. Campylobacter: azithromycin if needed. H. pylori: quadruple therapy (PPI, bismuth, metronidazole, tetracycline) or clarithromycin triple therapy.",
  quick=[("Shape", "Comma or S-shaped Gram-negative rods"),
         ("Vibrio", "Oxidase+, grows on TCBS, alkaline-tolerant, needs salt (V. vulnificus)"),
         ("Campylobacter", "Oxidase+, grows at 42°C, microaerophilic"),
         ("H. pylori", "Urease+, oxidase+, lives in gastric mucus")],
  images=[("vibrio-gram.jpg", "Comma-shaped Gram-negative rods."),
          ("tcbs.jpg", "Yellow colonies of V. cholerae on TCBS agar."),
          ("campy-sem.jpg", "Campylobacter jejuni - curved and flagellated."),
          ("hpylori.jpg", "Helicobacter pylori in gastric mucosa.")],
  sections=[
    S("Vibrio cholerae", [
      H("Cholera toxin is an AB5 toxin: five B subunits bind GM1 ganglioside on the enterocyte, and the A subunit ADP-ribosylates the alpha subunit of Gs. Modified Gs cannot hydrolyze GTP, so it stays permanently active, adenylyl cyclase runs continuously, cAMP rises, and protein kinase A phosphorylates CFTR, pumping chloride into the lumen with sodium and water following."),
      H("The result is massive painless 'rice water' diarrhea with no invasion - so no fever, no blood, and no inflammatory cells in stool. Death is from hypovolemic shock and metabolic acidosis, and the treatment that saves lives is rehydration, not antibiotics."),
      P("Oral rehydration solution works because cholera toxin leaves the SGLT1 sodium-glucose cotransporter intact; glucose-coupled sodium absorption pulls water back across the mucosa even while secretion continues. V. parahaemolyticus and V. vulnificus come from raw shellfish; V. vulnificus causes fulminant sepsis with hemorrhagic bullae in patients with cirrhosis or iron overload."),
    ]),
    S("Campylobacter jejuni", [
      H("The most common bacterial cause of diarrhea in many countries, from undercooked poultry, unpasteurized milk, and puppies. It causes a bloody, inflammatory diarrhea often preceded by a day of fever and severe cramping that can mimic appendicitis."),
      H("It is the leading antecedent of Guillain-Barre syndrome: lipooligosaccharide on certain strains mimics host gangliosides (GM1), so the antibody response cross-reacts with peripheral nerve, causing ascending symmetric weakness with areflexia and albuminocytologic dissociation in CSF. It also triggers reactive arthritis."),
      P("It is microaerophilic and grows best at 42°C, matching the body temperature of birds, its natural reservoir - which is why selective culture is incubated at that temperature."),
    ]),
    S("Helicobacter pylori", [
      H("Urease is the central adaptation: it splits urea into ammonia, which neutralizes gastric acid around the organism and lets it survive in mucus over the epithelium. This is also the basis of the urea breath test and the rapid urease (CLO) test on biopsy."),
      H("Antral-predominant infection lowers somatostatin from D cells, so gastrin and acid rise and the duodenum receives an excess acid load - producing duodenal ulcer. Body-predominant infection causes atrophic gastritis with reduced acid, and carries the risk of gastric adenocarcinoma. It is also the cause of gastric MALT lymphoma, which frequently regresses with eradication alone."),
      P("CagA is injected by a type IV secretion system and disrupts cell polarity and signaling; VacA induces vacuolation and apoptosis. Proton pump inhibitors, bismuth, and antibiotics suppress the organism and cause false negative urease-based and antigen tests, so they are stopped before testing. Serology cannot distinguish current from past infection."),
    ]),
  ]),

E("zoonotic-gneg", "Zoonotic Gram-Negative Rods", "Gram-Negative Rods",
  "Yersinia, Francisella, Brucella, Pasteurella, and Bartonella - defined by the animal exposure in the stem.",
  aka=["Yersinia pestis", "plague", "tularemia", "brucellosis", "cat scratch disease", "Pasteurella", "Yersinia", "Francisella", "Brucella", "Bartonella"],
  keywords=["bubo", "rabbit", "undulant fever", "cat bite", "bacillary angiomatosis", "unpasteurized milk"],
  treatment="Plague and tularemia: streptomycin or gentamicin (doxycycline alternative). Brucellosis: doxycycline plus rifampin or streptomycin, 6 weeks. Pasteurella: amoxicillin-clavulanate. Bartonella: azithromycin or doxycycline.",
  quick=[("Y. pestis", "Fleas from rodents; bipolar 'safety pin' staining"),
         ("F. tularensis", "Rabbits, ticks; infectious dose ~10 organisms"),
         ("Brucella", "Unpasteurized dairy; undulant fever; lab hazard"),
         ("Pasteurella", "Cat/dog bite; cellulitis within 24 hours"),
         ("Bartonella", "Cat scratch; bacillary angiomatosis in AIDS")],
  images=[("ypestis-wayson.jpg", "Bipolar 'safety pin' staining of Yersinia pestis."),
          ("bubo.jpg", "An inguinal bubo - the exquisitely tender node of bubonic plague."),
          ("tularemia.jpg", "Ulceroglandular tularemia: an ulcer at the inoculation site."),
          ("catscratch.jpg", "Regional lymphadenopathy of cat scratch disease.")],
  sections=[
    S("Yersinia pestis", [
      H("Transmitted by fleas from rodents (prairie dogs and ground squirrels in the southwestern United States). Bubonic plague produces an exquisitely tender, swollen regional node - the bubo - with fever and prostration. Wayson or Giemsa stain shows bipolar 'safety pin' organisms."),
      P("Untreated infection progresses to septicemic plague with DIC and acral gangrene, and to secondary pneumonic plague, which then spreads person to person by respiratory droplets and requires droplet precautions. It is a tier 1 select agent. The F1 capsular antigen and a type III secretion system delivering Yop effectors block phagocytosis."),
    ]),
    S("Francisella and Brucella", [
      H("Francisella tularensis needs as few as 10 organisms, making it a serious bioterror and laboratory-acquired infection risk. Exposures are rabbits and other lagomorphs, tick and deer fly bites, contaminated water, and aerosols from mowing over an animal carcass. Ulceroglandular disease - an ulcer at the bite with tender regional nodes - is most common."),
      H("Brucella comes from unpasteurized dairy or animal contact and causes undulant fever with night sweats, malaise, sacroiliitis, and spondylitis. It is a facultative intracellular organism that survives in macrophages, which is why therapy is two drugs for six weeks and relapse is common. The laboratory must be warned, because it is a leading cause of laboratory-acquired infection."),
    ]),
    S("Pasteurella and Bartonella", [
      H("Pasteurella multocida causes rapidly progressive cellulitis within 24 hours of a cat or dog bite, often with tenosynovitis or osteomyelitis. Amoxicillin-clavulanate covers it along with oral anaerobes; cephalexin alone does not."),
      H("Bartonella henselae causes cat scratch disease - tender regional lymphadenopathy with stellate necrotizing granulomas - in immunocompetent hosts. In advanced HIV the same organism instead causes bacillary angiomatosis: friable vascular papules that mimic Kaposi sarcoma but resolve with antibiotics. The difference is the host's cell-mediated immunity, not the organism."),
      P("Other bite organisms to keep adjacent: Eikenella corrodens after a human bite or clenched-fist injury, and Capnocytophaga canimorsus, which causes fulminant sepsis after a dog bite in asplenic patients."),
    ]),
  ]),
]
