"""Encyclopedia: spirochetes, mycobacteria, and obligate intracellular / atypical bacteria."""
from ecore import E, S, P, H, HISTORY, RESEARCH, TL, REVIEW

ENTRIES = [
E("treponema", "Treponema pallidum (Syphilis)", "Spirochetes",
  "The great imitator: a spirochete too thin to see on Gram stain and impossible to culture, staged by clinical findings and tracked by two very different blood tests.",
  aka=["syphilis", "lues"],
  keywords=["chancre", "condyloma lata", "gumma", "tabes dorsalis", "Argyll Robertson", "Jarisch-Herxheimer", "VDRL", "RPR", "FTA-ABS"],
  treatment="Benzathine penicillin G - single dose for early syphilis, three weekly doses for late latent, and IV aqueous penicillin for neurosyphilis. Pregnant women with allergy must be desensitized.",
  quick=[("Stain", "Too thin for Gram stain; seen by dark-field, DFA, or silver stain"),
         ("Culture", "Cannot be grown on artificial media"),
         ("Screening", "Treponemal (FTA-ABS, TP-PA, EIA) - positive for life"),
         ("Monitoring", "Nontreponemal (RPR, VDRL) - titers fall with cure"),
         ("Transmission", "Sexual contact and transplacental")],
  images=[("chancre.webp", "Primary chancre: a single painless ulcer with indurated edges and a clean base."),
          ("syph-palms.webp", "Secondary syphilis: a copper-colored maculopapular rash involving the palms."),
          ("congenital-syphilis.webp", "Congenital syphilis in a newborn.")],
  sections=[
    S("Stages", [
      H("Primary: a single painless, indurated ulcer (chancre) with a clean base at the inoculation site, 3 weeks after exposure, with painless regional adenopathy. It heals spontaneously, which is why it is so often missed."),
      H("Secondary (6 weeks to 6 months later): a diffuse maculopapular rash that characteristically involves the palms and soles, condyloma lata (moist, broad, highly infectious plaques in intertriginous areas), mucous patches, patchy alopecia, and constitutional symptoms. This is the stage of highest spirochete burden and greatest infectivity."),
      H("Tertiary (years later): gummas (granulomatous destructive lesions of skin, bone, and viscera), cardiovascular syphilis from obliterative endarteritis of the vasa vasorum producing ascending aortic aneurysm and aortic regurgitation, and neurosyphilis - tabes dorsalis with posterior column degeneration, sensory ataxia, and a positive Romberg; general paresis; and Argyll Robertson pupils, which accommodate but do not react to light."),
      P("Latent syphilis is seropositivity without clinical findings, divided into early latent (within a year of infection, still potentially infectious) and late latent. Neurosyphilis can occur at any stage, including early, which is why neurologic or ocular symptoms always prompt lumbar puncture."),
    ]),
    S("Serology - the part that is actually tested", [
      H("Nontreponemal tests (RPR, VDRL) detect antibody to cardiolipin released from damaged host cells. They are cheap, quantitative, and used to monitor treatment: a fourfold titer fall indicates cure. They become negative after successful treatment."),
      H("Treponemal tests (FTA-ABS, TP-PA, EIA) detect antibody against the organism itself. They are more specific and stay positive for life, so they cannot be used to judge response or to diagnose reinfection."),
      H("Biologic false positive RPR occurs in lupus and antiphospholipid syndrome, pregnancy, viral infections, tuberculosis, malaria, injection drug use, and old age - because the target antigen is a host lipid, not a treponemal one. A negative treponemal test then excludes syphilis."),
      P("The prozone phenomenon is a false negative RPR caused by antibody excess: so much antibody is present that lattice formation is blocked. Diluting the serum restores the reaction. It matters most in secondary syphilis and pregnancy, where titers are highest."),
    ]),
    S("Congenital syphilis and treatment reactions", [
      H("Transplacental infection causes stillbirth, hydrops, or a live infant with snuffles (infectious rhinitis), a desquamating rash on palms and soles, hepatosplenomegaly, and osteochondritis. Late signs are Hutchinson teeth (notched incisors), mulberry molars, saddle nose, saber shins, and the Hutchinson triad of interstitial keratitis, deafness, and notched teeth."),
      H("The Jarisch-Herxheimer reaction is fever, chills, myalgia, and worsening rash within hours of the first dose of penicillin, caused by the sudden release of treponemal lipoproteins and a burst of cytokines as organisms are killed. It is not an allergy and is managed with antipyretics; treatment continues."),
      P("Penicillin has no documented resistance in T. pallidum and remains the only regimen proven to prevent congenital infection, which is why pregnant patients with a penicillin allergy undergo desensitization rather than receiving an alternative."),
    ]),
  ],
  history=HISTORY([
    "Syphilis appeared in Europe as an explosive, highly lethal epidemic starting around 1494-1495, during and after the French invasion of Naples, which is why the disease was called 'the French disease' by the Italians, 'the Neapolitan disease' by the French, and a dozen other nationality-blaming names across Europe within a decade. Where it came from before that is still debated: the 'Columbian hypothesis' holds that it came back to Europe with Columbus's crews from the Americas in 1493, while a competing view holds that it existed in Europe earlier in a milder or unrecognized form and simply became more virulent or more noticed. Skeletal evidence has been used to argue both sides and the question is not fully settled.",
    "For roughly four centuries the cause was unknown and treatment was mercury, given by ointment, fumigation, or injection, which was toxic and only marginally effective - the old joke that medicine let you 'be in Venus for a night and pay for it with Mercury for a lifetime' describes a real and common clinical experience. Syphilis, gonorrhea, and other conditions were also not reliably distinguished from each other for most of this period, muddying both diagnosis and the historical record of what was actually being treated.",
    "The causative organism was only identified in 1905, when the zoologist Fritz Schaudinn and the dermatologist Erich Hoffmann, examining material from syphilitic lesions in Berlin, found thin corkscrew-shaped organisms under dark-field microscopy and named them Spirochaeta pallida (later reclassified to the genus Treponema) for how faintly they stained. Within a year, August von Wassermann developed a complement-fixation blood test for antibody to the organism - the first practical syphilis blood test and the ancestor of the nontreponemal tests still used for monitoring treatment today.",
    "Treatment improved stepwise rather than all at once: Paul Ehrlich's arsenical compound Salvarsan (1910) was a genuine advance over mercury and one of the first deliberately designed chemotherapeutic drugs in medical history, but it was still toxic and required a long course. Penicillin, shown to cure syphilis by John Mahoney's US Public Health Service group in 1943, was the real turning point and remains, more than eighty years and billions of treated infections later, a drug the organism has still never evolved resistance to. The same decades also produced one of the most notorious ethical failures in the history of American medicine: the US Public Health Service's Tuskegee study (1932-1972) tracked the natural history of untreated syphilis in Black men in Alabama without their informed consent, and continued withholding known-effective penicillin from study participants long after 1943, a scandal that still shapes research-ethics regulation today.",
  ], timeline=[
    TL("1494-1495", "Syphilis explodes across Europe", "A severe, rapidly lethal epidemic of a new-seeming disease spreads with French and other armies in and after the siege of Naples; contemporaries disagree about where it came from but agree it is new and terrifying, and nationality-blaming names for it spread across Europe within a decade."),
    TL("1905", "Schaudinn and Hoffmann find the organism", "Working in Berlin, zoologist Fritz Schaudinn and dermatologist Erich Hoffmann identify a thin, corkscrew-shaped spirochete in material from syphilitic lesions and name it Spirochaeta (later Treponema) pallidum.", img="hist-schaudinn.webp"),
    TL("1905", "Hoffmann, the clinician of the pair", "Erich Hoffmann, a dermatologist, supplied the diseased clinical material and the clinical framing; Schaudinn, a zoologist studying protozoa, supplied the microscopy eye that spotted the spirochete moving in it - the discovery needed both specialties.", img="hist-hoffmann.webp"),
    TL("1906", "Wassermann develops the first blood test", "August von Wassermann introduces a complement-fixation test for antitreponemal antibody, making syphilis the first major infection diagnosable by a standardized blood test rather than clinical appearance alone.", img="hist-wassermann.webp"),
    TL("1910", "Salvarsan: an early designed chemotherapy", "Paul Ehrlich's arsenical compound Salvarsan becomes the first real alternative to centuries of mercury treatment, though it is still toxic and a precursor to, rather than a solution for, modern antimicrobial therapy.", img="hist-ehrlich.webp"),
    TL("1932-1972", "The Tuskegee study", "The US Public Health Service begins observing the untreated natural history of syphilis in Black men in Macon County, Alabama, without informed consent, and continues withholding treatment for decades after penicillin is shown to cure the disease; the study is exposed by press reporting in 1972 and later prompts the Belmont Report and modern human-subjects research regulation."),
    TL("1943", "Penicillin cures syphilis", "John Mahoney and colleagues at the US Public Health Service demonstrate that penicillin cures syphilis, replacing arsenicals as first-line treatment; T. pallidum has not developed clinically significant penicillin resistance in the more than eight decades since.", img="hist-mahoney.webp"),
  ]),
  research=RESEARCH([
    "Global case counts have risen sharply since the 2000s, including congenital syphilis, which has driven renewed interest in a vaccine - something that has never existed for this disease, partly because T. pallidum cannot be cultured in standard artificial media, which has historically slowed laboratory study of its surface proteins and limited reagent availability.",
    "Current work focuses on the organism's small set of rare outer-membrane proteins (which it minimizes, likely as an immune-evasion strategy, making them harder to target but also attractive vaccine candidates), antigenic variation in the TprK protein as a mechanism of immune escape and reinfection, and genomic surveillance of circulating strains, including monitoring for macrolide resistance (already common, which is why azithromycin is no longer first-line) and watching closely for any sign of emerging penicillin resistance.",
  ], reviews=[
    REVIEW("Resurgence of syphilis: focusing on emerging clinical strategies and preclinical models", "Journal of Translational Medicine", "2023", "https://translational-medicine.biomedcentral.com/articles/10.1186/s12967-023-04685-4"),
  ]),
),

E("borrelia", "Borrelia (Lyme & Relapsing Fever)", "Spirochetes",
  "Tick- and louse-borne spirochetes: one causes a staged multisystem illness across weeks to years, the other recurring fevers by changing its coat.",
  aka=["Lyme disease", "Borrelia burgdorferi", "relapsing fever", "Borrelia recurrentis", "Borrelia"],
  keywords=["erythema migrans", "bull's eye", "Bell palsy", "heart block", "Ixodes", "antigenic variation"],
  treatment="Early Lyme: doxycycline (or amoxicillin/cefuroxime in children under 8 and pregnancy). Neurologic or cardiac Lyme: IV ceftriaxone. Relapsing fever: doxycycline.",
  quick=[("Vector", "Ixodes tick (Lyme); body louse or soft tick (relapsing fever)"),
         ("Reservoir", "White-footed mouse; deer maintain the tick population"),
         ("Attachment", "Tick must feed >36-48 h to transmit Lyme"),
         ("Diagnosis", "Erythema migrans is clinical; otherwise two-tier serology"),
         ("Co-infections", "Babesia and Anaplasma share the Ixodes vector")],
  images=[("em-rash.webp", "Erythema migrans: an expanding annular lesion with central clearing."),
          ("ixodes.webp", "Ixodes scapularis, the deer tick vector."),
          ("borrelia-smear.webp", "Borrelia spirochetes on a Giemsa-stained blood film in relapsing fever.")],
  sections=[
    S("Lyme disease stages", [
      H("Early localized (days to a month): erythema migrans, an expanding annular lesion with central clearing at the bite site, often with flu-like symptoms. This is a clinical diagnosis - serology is frequently negative this early because antibody has not yet developed, and treatment should not wait for it."),
      H("Early disseminated (weeks to months): multiple secondary annular lesions, cranial neuropathy - especially facial nerve palsy, which may be bilateral - lymphocytic meningitis, radiculopathy, and carditis with atrioventricular block."),
      H("Late (months to years): a monoarticular or oligoarticular arthritis, typically of the knee, with large effusions, and rarely a subtle encephalopathy or polyneuropathy."),
      P("Lyme carditis causes AV block at the level of the AV node and almost always resolves with intravenous ceftriaxone; temporary pacing may be needed but permanent pacemakers rarely are. This contrasts with Chagas disease, where conduction damage is irreversible."),
    ]),
    S("Diagnosis and prevention", [
      H("Serology uses a two-tier algorithm: a sensitive EIA first, then a more specific second test (immunoblot or a second EIA) on reactive samples. This limits false positives from cross-reacting antibody. Neither tier distinguishes active from past infection, so testing is reserved for patients with a compatible illness."),
      P("Transmission requires prolonged attachment, generally more than 36-48 hours, because the spirochete must migrate from the tick midgut to the salivary glands. A single dose of doxycycline can be offered as prophylaxis after a high-risk bite - an identified Ixodes nymph attached 36 hours or more in an endemic area, removed within the last 72 hours."),
      P("Persistent subjective symptoms after adequate treatment ('post-treatment Lyme disease syndrome') do not respond to prolonged antibiotics, which carry real harm; multiple randomized trials have shown no benefit."),
    ]),
    S("Relapsing fever", [
      H("Recurring 3-day febrile episodes separated by afebrile intervals of about a week, with spirochetes visible on a Giemsa-stained blood film during fever. Relapses occur because the organism rearranges variable major protein genes, so each antibody response clears one antigenic variant and a new one emerges."),
      P("Louse-borne disease (B. recurrentis) is epidemic, associated with crowding and poor sanitation, and has fewer relapses; tick-borne disease from soft Ornithodoros ticks is endemic and relapses more often. Treatment commonly triggers a Jarisch-Herxheimer reaction."),
    ]),
  ]),

E("leptospira", "Leptospira interrogans", "Spirochetes",
  "A water-borne spirochete from animal urine, classically in returning travelers, triathletes, and after flooding.",
  aka=["leptospirosis", "Weil disease"],
  keywords=["conjunctival suffusion", "freshwater", "rat urine", "jaundice", "kidney injury", "surfers"],
  treatment="Doxycycline for mild disease; IV penicillin or ceftriaxone for severe disease.",
  quick=[("Shape", "Tightly coiled spirochete with hooked ends"),
         ("Source", "Urine of rats, dogs, livestock contaminating fresh water"),
         ("Entry", "Abraded skin or mucous membranes"),
         ("Clue", "Conjunctival suffusion without exudate"),
         ("Severe form", "Weil disease")],
  images=[("lepto-sem.webp", "Leptospira: a tightly coiled spirochete with hooked ends.")],
  sections=[
    S("Clinical course", [
      H("A biphasic illness. The first (leptospiremic) phase has abrupt high fever, severe myalgia - especially calves - headache, and conjunctival suffusion, which is redness without discharge and is the classic examination clue. After a brief defervescence the immune phase brings meningitis and, in severe cases, organ failure."),
      H("Weil disease is the severe icteric form: jaundice with markedly raised bilirubin but only modestly raised transaminases, acute kidney injury, and hemorrhage, particularly pulmonary. Mortality is substantial."),
      P("Exposure is the giveaway in a question: freshwater swimming or triathlon, flooding, sewer or abattoir work, or travel to Hawaii and Southeast Asia. There is no person-to-person transmission."),
    ]),
  ]),

E("mtb", "Mycobacterium tuberculosis", "Mycobacteria",
  "A slow-growing acid-fast aerobe contained by cell-mediated immunity - which is why anything that weakens T cells or TNF lets it back out.",
  aka=["TB", "tuberculosis", "Koch bacillus"],
  keywords=["caseating granuloma", "Ghon complex", "cavitary", "night sweats", "PPD", "IGRA", "RIPE", "latent"],
  treatment="Active disease: RIPE (rifampin, isoniazid, pyrazinamide, ethambutol) for 2 months, then rifampin and isoniazid for 4 months. Latent: rifampin 4 months, or isoniazid plus rifapentine weekly for 12 doses.",
  quick=[("Stain", "Acid-fast (Ziehl-Neelsen); auramine-rhodamine is more sensitive"),
         ("Wall", "Mycolic acids - the basis of acid-fastness"),
         ("Oxygen", "Obligate aerobe - hence the lung apices"),
         ("Growth", "Slow: 3-8 weeks on Lowenstein-Jensen"),
         ("Rapid test", "NAAT with rpoB probes detects rifampin resistance in hours")],
  images=[("tb-zn.webp", "Ziehl-Neelsen stain: red beaded acid-fast bacilli."),
          ("afb-smear.webp", "Acid-fast bacilli in a concentrated sputum smear."),
          ("tb-granuloma.webp", "Caseating granuloma with epithelioid macrophages and Langhans giant cells."),
          ("miliary-tb.webp", "Miliary tuberculosis: innumerable small nodules throughout both lungs."),
          ("mantoux.webp", "Mantoux tuberculin skin test - induration, not erythema, is measured.")],
  sections=[
    S("Cell wall and virulence", [
      H("Mycolic acids - very long-chain branched fatty acids - make the wall waxy, impermeable, and acid-fast. They also explain the slow growth, the resistance to drying and disinfectants, and the need for multidrug therapy over months."),
      P("Cord factor (trehalose 6,6'-dimycolate) makes the organism grow in serpentine cords in culture, inhibits phagosome maturation, and induces macrophage TNF-alpha release - the cytokine that builds and maintains the granuloma but also produces the fever, night sweats, and wasting. Sulfatides further block phagosome-lysosome fusion, allowing survival inside macrophages."),
      P("Lipoarabinomannan modulates macrophage signaling and is the target of a urine antigen test useful in advanced HIV. The organism is an obligate aerobe, which is why reactivation favors the lung apices, where the ventilation-perfusion ratio gives the highest oxygen tension."),
    ]),
    S("Immunology and the granuloma", [
      H("Containment requires CD4 Th1 cells releasing IFN-gamma, which activates macrophages into epithelioid cells and Langhans giant cells, walling the organism into a caseating granuloma. Losing CD4 cells (HIV) or blocking TNF-alpha (infliximab and other TNF inhibitors) breaks containment and causes reactivation - which is why both are screened before treatment."),
      P("Primary infection typically seeds a subpleural lower-lobe focus with hilar nodal involvement: the Ghon complex. Most people contain it, leaving a calcified scar and a positive skin test. Reactivation occurs years later in the apices, producing cavitary disease with cough, hemoptysis, night sweats, and weight loss."),
      P("The caseous center is acellular, acidic, and hypoxic, which is why sterilizing it takes months and why pyrazinamide, which works best at acid pH, shortens therapy so effectively."),
    ]),
    S("Testing", [
      H("The tuberculin skin test measures induration at 48-72 hours and reflects type IV hypersensitivity. Cut-offs: 5 mm for HIV, recent contacts, organ transplant recipients, and those with fibrotic changes on imaging; 10 mm for recent immigrants, injection drug users, healthcare and prison staff, and children under 4; 15 mm for everyone else."),
      H("False negatives occur with anergy - advanced HIV, overwhelming disease, malnutrition, recent viral infection - and in the first 2-8 weeks after exposure. False positives come from BCG vaccination and nontuberculous mycobacteria; an interferon-gamma release assay avoids BCG cross-reactivity because it uses antigens absent from BCG."),
      P("Neither test distinguishes latent infection from active disease, so a positive result always requires a chest radiograph and symptom assessment before latent treatment is started."),
    ]),
    S("Drugs and their toxicities", [
      H("Isoniazid is a prodrug activated by mycobacterial catalase-peroxidase (KatG); the active form inhibits InhA in mycolic acid synthesis. It causes hepatitis, drug-induced lupus, and peripheral neuropathy from pyridoxine depletion - hence B6 supplementation. Resistance arises from katG or inhA mutations."),
      H("Rifampin inhibits bacterial DNA-dependent RNA polymerase, turns secretions orange, and is a potent CYP450 inducer, so it lowers levels of oral contraceptives, warfarin, and protease inhibitors. Rifabutin induces less and is preferred with antiretroviral therapy."),
      H("Pyrazinamide works in the acidic phagolysosome, causes hepatotoxicity, and raises uric acid, precipitating gout. Ethambutol inhibits arabinosyl transferase and causes dose-dependent optic neuritis with red-green color blindness."),
      P("Multidrug-resistant TB is resistant to at least isoniazid and rifampin; extensively drug-resistant TB adds resistance to a fluoroquinolone and a second-line injectable. Directly observed therapy is used to protect against the resistance that intermittent adherence breeds."),
    ]),
  ],
  history=HISTORY([
    "Tuberculosis is ancient - DNA evidence and characteristic skeletal lesions (Pott disease of the spine) place it in human populations for thousands of years, and it was a leading cause of death in industrializing Europe by the 18th and 19th centuries, when it was known as 'consumption' or 'phthisis' for the way it visibly wasted its victims. Before the organism was known, tuberculosis was widely believed to be hereditary, or a disease of poets and artists linked to a particular temperament (the Romantic-era 'consumptive' image), rather than a contagious infection - an idea that persisted in lay culture even after the scientific case for contagion was made.",
    "Robert Koch changed that on March 24, 1882, when he announced to the Berlin Physiological Society that he had identified, stained, and cultured a specific bacillus from tubercular tissue and shown it caused the disease in animals - fulfilling what became known as Koch's postulates, a set of criteria for proving a microbe causes a specific disease that he had developed partly through this very work. The announcement is considered one of the foundational moments of medical microbiology, and March 24 is marked as World Tuberculosis Day for exactly this reason. Koch's bacillus was slow to grow and difficult to stain by ordinary methods, which is why acid-fast staining (developed soon after by Paul Ehrlich and refined by Franz Ziehl and Friedrich Neelsen) became essential to working with it.",
    "For sixty years after Koch's discovery, treatment remained primarily environmental: sanatoriums offering rest, fresh air, and good nutrition, sometimes combined with collapse therapy (deliberately collapsing a lung, surgically or by inducing a pneumothorax, to 'rest' diseased tissue) - measures that helped some patients but had no direct antimicrobial effect and left mortality high. The era of real chemotherapy began with streptomycin, isolated from Streptomyces griseus by Albert Schatz working in Selman Waksman's lab and first used against TB in 1944; isoniazid followed in the early 1950s and rifampin in the 1960s, and the combination regimens built from these drugs are the direct ancestors of the RIPE therapy used today.",
    "The BCG vaccine, derived by Albert Calmette and Camille Guerin from an attenuated strain of Mycobacterium bovis, was first given to humans in 1921 and remains the only TB vaccine in widespread use a century later - it protects children against severe disseminated and meningeal disease reasonably well but gives inconsistent, often poor protection against adult pulmonary disease, which is the single biggest reason TB remains a leading infectious killer worldwide despite a century of vaccination and seventy years of effective drugs.",
  ], timeline=[
    TL("1882", "Koch identifies the tubercle bacillus", "Robert Koch announces to the Berlin Physiological Society that he has isolated, cultured, and demonstrated the causative role of Mycobacterium tuberculosis, applying what became known as Koch's postulates and marking one of the founding moments of medical microbiology; the date is now observed as World Tuberculosis Day.", img="hist-koch.webp"),
    TL("1908-1910s", "Acid-fast staining refined", "Franz Ziehl and Friedrich Neelsen refine an acid-fast staining method (building on earlier work by Paul Ehrlich and Robert Koch) that remains, in essentially its original form, the standard rapid stain for AFB smears today."),
    TL("1921", "Calmette and Guerin give the first BCG dose", "Albert Calmette, after years developing an attenuated Mycobacterium bovis strain with veterinarian Camille Guerin, gives the first human dose of what becomes the BCG vaccine, still the only TB vaccine in routine use a century later.", img="hist-calmette.webp"),
    TL("1921", "Guerin, the other half of BCG", "Camille Guerin, a veterinary microbiologist, spent over a decade with Calmette subculturing the bovine strain some 230 times to attenuate it - unglamorous, repetitive bench work that is easy to leave out of the story but is most of what actually produced the vaccine.", img="hist-guerin.webp"),
    TL("1943-1944", "Streptomycin: the first effective anti-TB drug", "Albert Schatz, working in Selman Waksman's laboratory, isolates streptomycin from Streptomyces griseus; it is first used clinically against tuberculosis in 1944 and is the first antibiotic shown to cure the disease, ending the sanatorium era.", img="hist-waksman.webp"),
    TL("1952", "Isoniazid introduced", "Isoniazid is introduced into clinical use and rapidly becomes a backbone drug once combination therapy is shown necessary to prevent the resistance that emerged quickly with streptomycin used alone."),
    TL("1960s", "Rifampin and the modern multidrug regimen", "Rifampin's introduction completes the drug set that, combined with pyrazinamide and ethambutol, forms the modern short-course RIPE regimen still used for drug-susceptible disease today."),
  ]),
  research=RESEARCH([
    "Current priorities include shorter and simpler treatment regimens (four-month and even shorter all-oral regimens for drug-susceptible and drug-resistant disease have shown promise in recent trials), new or improved vaccines beyond century-old BCG (several candidates, including M72/AS01E, are in late-stage trials aiming for better protection against adult pulmonary disease), and better point-of-care diagnostics for rifampin and isoniazid resistance in low-resource settings.",
    "A central unsolved problem is latent infection itself: roughly a quarter of the world's population is estimated to carry latent M. tuberculosis, the biology of what keeps most of those infections dormant for life while a minority reactivate is incompletely understood, and there is no reliable biomarker that distinguishes a latent infection likely to reactivate from one that never will - which is why current practice treats latency as a binary risk category rather than a graded one.",
  ], reviews=[
    REVIEW("Mycobacterium tuberculosis: Pathogenesis and therapeutic targets", "MedComm", "2023", "https://pmc.ncbi.nlm.nih.gov/articles/PMC10477518/"),
  ]),
),

E("ntm", "Nontuberculous Mycobacteria & M. leprae", "Mycobacteria",
  "The other mycobacteria: MAC in advanced AIDS, M. marinum in aquarium keepers, and leprosy as a spectrum set by the host's T-cell response.",
  aka=["MAC", "Mycobacterium avium", "leprosy", "Hansen disease", "M. marinum", "M. scrofulaceum"],
  keywords=["CD4 below 50", "fish tank granuloma", "lepromatous", "tuberculoid", "leonine facies", "armadillo"],
  treatment="MAC: azithromycin plus ethambutol, often with rifabutin. Leprosy: dapsone plus rifampin (tuberculoid); add clofazimine for lepromatous.",
  quick=[("MAC", "Disseminated when CD4 <50; fever, weight loss, diarrhea, high alk phos"),
         ("M. marinum", "Aquariums and pools; prefers cooler skin"),
         ("M. scrofulaceum", "Cervical lymphadenitis in children - excise"),
         ("M. leprae", "Cannot be cultured; grown in armadillos and mouse footpads"),
         ("Leprosy spectrum", "Tuberculoid = strong Th1; lepromatous = Th2")],
  images=[("leprosy-ll.webp", "Lepromatous leprosy with diffuse nodular infiltration.")],
  sections=[
    S("MAC and other environmental mycobacteria", [
      H("Disseminated Mycobacterium avium complex occurs when the CD4 count falls below 50, presenting with fever, night sweats, weight loss, diarrhea, anemia, and a raised alkaline phosphatase. Treatment is a macrolide plus ethambutol, with antiretroviral therapy - which can then precipitate IRIS."),
      P("MAC also causes chronic cavitary lung disease in patients with COPD and a nodular bronchiectatic pattern in the right middle lobe and lingula of older thin women, historically called Lady Windermere syndrome. M. kansasii mimics tuberculosis. Rapid growers such as M. abscessus and M. fortuitum cause infections after cosmetic procedures and surgery."),
      H("M. marinum grows best at cooler temperatures and causes nodular lesions in a sporotrichoid (ascending lymphatic) pattern on the hands of aquarium keepers and swimmers. Nontuberculous mycobacterial cervical lymphadenitis in a young child is treated by complete surgical excision, not by antimycobacterial drugs - incision and drainage risks a chronically draining sinus."),
    ]),
    S("Leprosy", [
      H("M. leprae grows best at 27-30°C, so it targets cool tissues: skin, superficial peripheral nerves, the nose, earlobes, and testes, while sparing the warm axilla and groin. It invades Schwann cells, producing thickened nerves and anesthetic skin lesions; the trauma and deformity that follow are consequences of sensory loss, not of the organism."),
      H("Tuberculoid leprosy reflects a strong Th1 response: few well-demarcated anesthetic plaques, few organisms on biopsy, marked nerve damage, and a positive lepromin test. Lepromatous leprosy reflects a Th2-skewed response with poor macrophage activation: diffuse nodular skin thickening, leonine facies, numerous bacilli, and a negative lepromin test."),
      P("Transmission requires prolonged close contact and probably occurs by nasal droplets. Armadillos are a natural reservoir in the southern United States. Dapsone can cause hemolysis in G6PD deficiency, and clofazimine causes a red-brown skin discoloration."),
    ]),
  ]),

E("chlamydia", "Chlamydia & Chlamydophila", "Intracellular & Atypical Bacteria",
  "Obligate intracellular bacteria with a two-form life cycle, no muramic acid in the wall, and the most common reportable STI in many countries.",
  aka=["Chlamydia trachomatis", "C. pneumoniae", "C. psittaci", "psittacosis"],
  keywords=["urethritis", "cervicitis", "PID", "trachoma", "LGV", "neonatal pneumonia", "elementary body", "reticulate body"],
  treatment="Genital infection: doxycycline 7 days (azithromycin single dose in pregnancy). LGV: doxycycline 21 days. Trachoma: azithromycin. Neonatal: oral erythromycin.",
  quick=[("Forms", "Elementary body = infectious; reticulate body = replicating"),
         ("Wall", "Lacks muramic acid - beta-lactams are useless"),
         ("Energy", "An energy parasite: uses host ATP"),
         ("A-C", "Trachoma (chronic conjunctivitis, blindness)"),
         ("D-K", "Urethritis, cervicitis, PID, neonatal disease"),
         ("L1-L3", "Lymphogranuloma venereum")],
  images=[("chlamydia-incl.webp", "Intracytoplasmic chlamydial inclusions in cell culture."),
          ("trachoma.webp", "Trachomatous trichiasis: scarring has turned the lashes onto the cornea.")],
  sections=[
    S("Life cycle", [
      H("The elementary body is small, dense, metabolically inert, and infectious; it enters the cell and transforms into the larger reticulate body, which divides by binary fission inside a cytoplasmic inclusion using host ATP. Reticulate bodies then condense back into elementary bodies and are released."),
      P("Because the wall lacks muramic acid (and therefore classic peptidoglycan cross-linking), beta-lactams have no target - a fact that follows directly from the structure rather than being an arbitrary rule. Treatment uses agents that enter cells and inhibit protein synthesis: tetracyclines and macrolides."),
    ]),
    S("Serovars and syndromes", [
      H("Serovars A-C cause trachoma, the leading infectious cause of blindness worldwide: repeated childhood conjunctival infection scars the lid, turning lashes inward (trichiasis) so they abrade the cornea. Control uses the SAFE strategy - Surgery, Azithromycin, Facial cleanliness, Environmental improvement."),
      H("Serovars D-K cause urethritis, cervicitis, and pelvic inflammatory disease with its sequelae of infertility, ectopic pregnancy, and Fitz-Hugh-Curtis perihepatitis. Infection is frequently asymptomatic, which is why annual screening is recommended for sexually active women under 25."),
      H("Serovars D-K also cause neonatal disease acquired at delivery: conjunctivitis at 5-14 days (later than gonococcal ophthalmia, which appears at 2-5 days) and a staccato-cough afebrile pneumonia with eosinophilia at 4-12 weeks. Erythromycin ointment at birth does not prevent chlamydial pneumonia, because it is acquired in the nasopharynx."),
      H("Serovars L1-L3 cause lymphogranuloma venereum: a small painless ulcer followed by large, painful, matted inguinal buboes that may suppurate, and proctocolitis in receptive anal intercourse."),
      P("Chlamydophila pneumoniae causes atypical pneumonia in young adults; C. psittaci causes atypical pneumonia with severe headache after exposure to birds, especially parrots and parakeets."),
    ]),
  ]),

E("rickettsia", "Rickettsiae, Ehrlichia, Anaplasma & Coxiella", "Intracellular & Atypical Bacteria",
  "Obligate intracellular Gram-negatives transmitted by arthropods (except one), all treated with doxycycline regardless of the patient's age.",
  aka=["Rocky Mountain spotted fever", "typhus", "Q fever", "ehrlichiosis", "anaplasmosis", "Rickettsia", "Ehrlichia", "Anaplasma", "Coxiella", "RMSF"],
  keywords=["rash wrists ankles", "Weil-Felix", "morulae", "culture-negative endocarditis", "tick", "louse"],
  treatment="Doxycycline for all of them - including in children, because the risk of untreated rickettsial disease far exceeds the dental risk. Chronic Q fever: doxycycline plus hydroxychloroquine for 18 months.",
  quick=[("Rickettsia", "Infects endothelium; vasculitis and rash"),
         ("Ehrlichia", "Morulae in monocytes; Amblyomma; southeastern US"),
         ("Anaplasma", "Morulae in granulocytes; Ixodes; northeastern US"),
         ("Coxiella", "Inhaled, no vector, spore-like form, no rash")],
  images=[("rmsf.webp", "Rocky Mountain spotted fever: petechial rash on the palm."),
          ("ehrlichia.webp", "Morulae - clusters of organisms - within a leukocyte.")],
  sections=[
    S("Rickettsia", [
      H("Rocky Mountain spotted fever (R. rickettsii, Dermacentor tick) begins with fever and severe headache, then a rash that starts on the wrists and ankles and spreads centrally, involving palms and soles. Despite the name it is most common in the southeastern and south-central United States."),
      H("Endemic (murine) typhus is spread by fleas from rats and epidemic typhus by the human body louse (R. prowazekii); both cause a rash that starts centrally on the trunk and spreads outward, sparing palms and soles. Brill-Zinsser disease is a milder recrudescence of epidemic typhus years later."),
      P("Rickettsiae infect vascular endothelium, so the underlying lesion is a vasculitis: rash, increased vascular permeability, hypotension, and in severe cases DIC and end-organ damage. They are obligate intracellular because they rely on host CoA and NAD and cannot be grown on cell-free media, so diagnosis is serologic or by PCR - and treatment is always started empirically, because serology is negative in the first week."),
    ]),
    S("Ehrlichia and Anaplasma", [
      H("Both cause an undifferentiated febrile illness with headache, leukopenia, thrombocytopenia, and raised transaminases, usually without a rash - a useful contrast with RMSF. Ehrlichia chaffeensis forms morulae in monocytes and is spread by Amblyomma; Anaplasma phagocytophilum forms morulae in granulocytes and is spread by Ixodes."),
      P("Because Anaplasma shares the Ixodes vector, it can coexist with Lyme disease and babesiosis in the same patient, which is worth remembering when a patient with erythema migrans has unexpectedly severe cytopenias."),
    ]),
    S("Coxiella burnetii (Q fever)", [
      H("The exception to nearly every rickettsial rule: it is inhaled rather than vector-borne, forms a spore-like resistant particle, and causes no rash. Exposure is to aerosols from parturient livestock - placenta, birth fluids, and contaminated dust - so the classic patients are veterinarians, farmers, and abattoir workers."),
      P("Acute Q fever is pneumonia with hepatitis and a high fever. Chronic Q fever is a major cause of culture-negative endocarditis, often on a previously abnormal valve, and requires prolonged doxycycline with hydroxychloroquine, which alkalinizes the phagolysosome and makes doxycycline bactericidal."),
    ]),
  ]),

E("mycoplasma", "Mycoplasma & Ureaplasma", "Intracellular & Atypical Bacteria",
  "The smallest free-living bacteria: no cell wall at all, sterols in the membrane instead, and therefore no response to any beta-lactam.",
  aka=["Mycoplasma pneumoniae", "walking pneumonia", "Ureaplasma", "Mycoplasma genitalium"],
  keywords=["cold agglutinins", "atypical pneumonia", "military recruits", "erythema multiforme", "bullous myringitis"],
  treatment="Macrolide (azithromycin), doxycycline, or a respiratory fluoroquinolone. Beta-lactams and vancomycin have no effect.",
  quick=[("Wall", "None - the only bacteria with no peptidoglycan"),
         ("Membrane", "Contains cholesterol (unique among bacteria)"),
         ("Gram stain", "Does not stain - too small and no wall"),
         ("Media", "Eaton agar; colonies look like fried eggs"),
         ("Epidemiology", "Young adults in close quarters: dorms, barracks, prisons")],
  sections=[
    S("Structure explains the pharmacology", [
      H("Mycoplasma has no cell wall, so every drug that targets wall synthesis - penicillins, cephalosporins, carbapenems, vancomycin - is useless. It also cannot be seen on Gram stain. Its membrane uniquely contains cholesterol, taken up from the host."),
    ]),
    S("Clinical disease", [
      H("Atypical ('walking') pneumonia: an insidious illness with headache, malaise, low-grade fever, and a persistent dry cough, in a patient who looks far better than the chest film suggests, which classically shows diffuse interstitial infiltrates far out of proportion to examination findings."),
      H("Cold agglutinins - IgM antibodies against the I antigen on erythrocytes - develop in many patients and can cause a cold autoimmune hemolytic anemia. They arise because the organism's membrane antigens cross-react with the I antigen."),
      P("Other associations are bullous myringitis, erythema multiforme and Stevens-Johnson-like mucositis, and rarely Guillain-Barre syndrome or encephalitis. Ureaplasma urealyticum causes non-gonococcal urethritis and is urease-positive; Mycoplasma genitalium is an increasingly recognized cause of persistent urethritis and cervicitis with rising macrolide resistance."),
    ]),
  ]),

E("other-bacteria", "Gardnerella, Tropheryma & Other Bacteria", "Intracellular & Atypical Bacteria",
  "Bacterial vaginosis, Whipple disease, and the HACEK group - small topics that appear reliably.",
  aka=["bacterial vaginosis", "Whipple disease", "HACEK", "Gardnerella vaginalis", "Tropheryma whipplei"],
  keywords=["clue cells", "whiff test", "foamy macrophages", "PAS-positive", "culture-negative endocarditis"],
  treatment="Bacterial vaginosis: metronidazole. Whipple disease: ceftriaxone then long-term TMP-SMX. HACEK endocarditis: ceftriaxone.",
  quick=[("BV", "pH >4.5, clue cells, positive whiff test, thin gray discharge"),
         ("Whipple", "PAS-positive foamy macrophages in lamina propria"),
         ("HACEK", "Haemophilus, Aggregatibacter, Cardiobacterium, Eikenella, Kingella")],
  images=[("clue-cells.webp", "Clue cells: epithelial cells so coated with bacteria that their borders are obscured."),
          ("whipple.webp", "Whipple disease: PAS-positive foamy macrophages distending intestinal villi.")],
  sections=[
    S("Bacterial vaginosis", [
      H("Not an infection so much as a shift in flora: loss of hydrogen peroxide-producing lactobacilli lets Gardnerella and anaerobes overgrow. Diagnosis uses Amsel criteria - thin gray homogeneous discharge, vaginal pH above 4.5, clue cells on wet mount, and a positive whiff (amine) test when KOH is added."),
      P("There is little inflammation, so 'vaginosis' rather than 'vaginitis' - white cells are scarce, in contrast to trichomoniasis. It is associated with preterm labor in pregnancy, so symptomatic pregnant patients are treated."),
    ]),
    S("Whipple disease and HACEK", [
      H("Whipple disease, from Tropheryma whipplei, causes malabsorption with diarrhea and weight loss, migratory polyarthralgia, cardiac and neurologic involvement, and lymphadenopathy, classically in an older white man. Biopsy shows PAS-positive, diastase-resistant foamy macrophages distending the lamina propria. Mnemonic: Foamy Whipped cream in a CAN - Cardiac, Arthralgias, Neurologic."),
      P("The HACEK organisms - Haemophilus species, Aggregatibacter, Cardiobacterium hominis, Eikenella corrodens, Kingella kingae - are fastidious oral Gram-negatives causing subacute endocarditis, historically 'culture-negative' because they grow slowly. Modern automated blood culture systems usually recover them within five days. Kingella is a notable cause of septic arthritis and osteomyelitis in toddlers."),
    ]),
  ]),
]
