"""Encyclopedia: DNA viruses, RNA viruses, HIV, and hepatitis viruses."""
from ecore import E, S, P, H

ENTRIES = [
E("herpesviruses", "Herpesviruses (HSV, VZV, EBV, CMV, HHV-6/8)", "DNA Viruses",
  "Eight enveloped double-stranded DNA viruses united by one property: after primary infection they never leave.",
  aka=["HSV", "herpes simplex", "VZV", "varicella", "shingles", "EBV", "mononucleosis", "CMV", "HHV-8", "Kaposi"],
  keywords=["latency", "Tzanck", "Cowdry", "owl eye", "Downey cells", "heterophile", "acyclovir", "ganciclovir"],
  treatment="HSV/VZV: acyclovir, valacyclovir, famciclovir. CMV: ganciclovir/valganciclovir, foscarnet, cidofovir. EBV, HHV-6, HHV-8: supportive or treat the underlying immunosuppression.",
  quick=[("Genome", "Linear double-stranded DNA, enveloped, icosahedral"),
         ("Replication", "In the nucleus; envelope from nuclear membrane"),
         ("Defining trait", "Lifelong latency with reactivation"),
         ("HSV latency", "HSV-1 trigeminal ganglion; HSV-2 sacral ganglia"),
         ("EBV latency", "B lymphocytes (enters via CD21)"),
         ("Histology", "Multinucleated giant cells with intranuclear inclusions")],
  images=[("herpes-labialis.jpg", "Herpes labialis: grouped vesicles on an erythematous base."),
          ("tzanck.jpg", "Tzanck smear: multinucleated giant cells with molded nuclei."),
          ("varicella.jpg", "Varicella: lesions in several stages at once - 'dew drops on a rose petal'."),
          ("zoster.jpg", "Herpes zoster in a single dermatome."),
          ("hutchinson.jpg", "Hutchinson sign: vesicles on the nasal tip predict ocular involvement."),
          ("cmv-owl.jpg", "CMV: 'owl eye' intranuclear inclusion."),
          ("kaposi.jpg", "Kaposi sarcoma from HHV-8.")],
  sections=[
    S("Herpes simplex", [
      H("HSV-1 travels up sensory axons to the trigeminal ganglion and HSV-2 to the sacral ganglia, where the genome persists as a circular episome expressing only latency-associated transcripts. Reactivation follows stress, fever, ultraviolet light, menstruation, or immunosuppression. Neither virus integrates into host DNA."),
      H("HSV-1 encephalitis characteristically affects the temporal lobes, producing fever, personality change, olfactory hallucinations, and seizures. CSF shows a lymphocytic pleocytosis, often with red cells from hemorrhagic necrosis. PCR is diagnostic, but intravenous acyclovir is started empirically because delay costs brain."),
      H("Neonatal HSV takes three forms: skin-eye-mouth (best prognosis), CNS, and disseminated disease (both with high mortality). Risk is highest with primary maternal infection near delivery, when little maternal antibody has crossed the placenta; cesarean delivery before prolonged rupture reduces transmission."),
      P("Acyclovir is selectively toxic because viral thymidine kinase performs the first phosphorylation; host kinases then complete it, and the triphosphate inhibits viral DNA polymerase and terminates the chain. Resistance arises from loss of thymidine kinase, so resistant isolates are treated with foscarnet or cidofovir, which act on the polymerase directly and need no activation."),
    ]),
    S("Varicella-zoster", [
      H("Primary infection is chickenpox: a generalized pruritic rash in which macules, papules, vesicles, and crusts coexist because lesions appear in successive crops. Smallpox, by contrast, was synchronous and centrifugal with palm and sole involvement."),
      H("The virus persists in dorsal root and cranial nerve ganglia; reactivation produces zoster in a single dermatome. Antivirals started within 72 hours shorten the eruption and reduce postherpetic neuralgia. The recombinant zoster vaccine is recommended from age 50."),
      P("Hutchinson sign - vesicles on the nasal tip - indicates nasociliary (V1) involvement and predicts ocular disease, requiring urgent ophthalmologic referral. Ramsay Hunt syndrome is geniculate ganglion zoster with facial palsy, ear canal vesicles, and hearing or vestibular changes."),
    ]),
    S("Epstein-Barr virus", [
      H("EBV enters B cells through CD21 (CR2). Infectious mononucleosis presents with fever, exudative pharyngitis, posterior cervical lymphadenopathy, splenomegaly, and fatigue. The atypical lymphocytes ('Downey cells') are reactive CD8 T cells, not infected B cells."),
      H("The monospot detects heterophile antibodies produced by polyclonal B-cell activation, which agglutinate horse or sheep erythrocytes. It can be negative in the first week and in young children, where EBV-specific serology is used instead."),
      H("Splenic rupture is the feared complication, so contact sports are avoided for at least three weeks and until splenomegaly resolves. Giving amoxicillin or ampicillin causes a florid morbilliform rash - not a true penicillin allergy."),
      P("EBV is associated with Burkitt lymphoma (t(8;14) MYC translocation, 'starry sky' histology), nasopharyngeal carcinoma (especially in southern China), Hodgkin lymphoma, CNS lymphoma in AIDS, oral hairy leukoplakia, and post-transplant lymphoproliferative disorder - which is managed first by reducing immunosuppression, because the problem is loss of T-cell control over EBV-transformed B cells."),
    ]),
    S("CMV, HHV-6 and HHV-8", [
      H("CMV is the most common congenital infection and the leading infectious cause of sensorineural hearing loss. Congenital disease shows microcephaly with periventricular calcifications, hearing loss, and a petechial 'blueberry muffin' rash - distinguished from toxoplasmosis, which gives diffuse calcifications, hydrocephalus, and chorioretinitis."),
      H("In AIDS with CD4 below 50, CMV causes retinitis with a 'pizza pie' fundus of hemorrhage and exudate, plus esophagitis and colitis. Histology shows 'owl eye' intranuclear inclusions. Acyclovir does not work because CMV lacks the necessary kinase; ganciclovir (marrow suppression) or foscarnet (nephrotoxicity with electrolyte wasting) is used."),
      H("HHV-6 causes roseola infantum: three to five days of high fever, then a rose-colored maculopapular rash appearing as the fever breaks. It is a common cause of febrile seizures. HHV-8 causes Kaposi sarcoma, primary effusion lymphoma, and multicentric Castleman disease."),
    ]),
  ]),

E("hpv-polyoma-pox", "HPV, Parvovirus, Polyomaviruses & Poxviruses", "DNA Viruses",
  "The remaining DNA viruses: an oncogenic papillomavirus, a single-stranded parvovirus, two polyomaviruses of the immunosuppressed, and the poxviruses.",
  aka=["HPV", "human papillomavirus", "parvovirus B19", "JC virus", "BK virus", "molluscum", "smallpox"],
  keywords=["koilocyte", "E6", "E7", "slapped cheek", "aplastic crisis", "PML", "hydrops fetalis"],
  treatment="HPV: prevention by vaccination; lesion-directed treatment. Parvovirus: supportive (IVIG if chronic in immunocompromised). PML: restore immunity. Molluscum: self-limited.",
  quick=[("HPV", "Circular dsDNA, naked; E6 degrades p53, E7 inhibits Rb"),
         ("Parvovirus B19", "The only single-stranded DNA virus; naked"),
         ("JC virus", "PML - demyelination in severe immunosuppression"),
         ("BK virus", "Kidney transplant nephropathy; hemorrhagic cystitis"),
         ("Poxvirus", "Largest virus; replicates in the CYTOPLASM")],
  images=[("koilocytes.jpg", "Koilocytes: perinuclear halos with wrinkled hyperchromatic nuclei."),
          ("fifth.jpg", "Erythema infectiosum: the 'slapped cheek' rash of parvovirus B19."),
          ("molluscum.jpg", "Molluscum contagiosum: umbilicated dome-shaped papules."),
          ("smallpox.jpg", "Smallpox - lesions all at the same stage.")],
  sections=[
    S("Human papillomavirus", [
      H("E6 targets p53 for degradation and E7 binds and inactivates Rb, releasing E2F. Losing both the apoptotic and the cell-cycle checkpoint is what makes high-risk types (16 and 18) oncogenic, causing cervical, anal, vulvar, penile, and oropharyngeal carcinoma. Types 6 and 11 cause condyloma acuminatum and laryngeal papillomatosis."),
      H("Koilocytes - squamous cells with a large clear perinuclear halo and a wrinkled hyperchromatic nucleus - are the cytopathic hallmark on cervical cytology."),
      P("The vaccine is a virus-like particle vaccine made of L1 capsid protein and contains no viral DNA. It is prophylactic only: it prevents new infection but does not clear established infection or treat existing lesions, which is why it is given at 11-12 years, before exposure."),
    ]),
    S("Parvovirus B19", [
      H("B19 binds the P blood group antigen (globoside) on erythroid progenitors and arrests their maturation, producing giant pronormoblasts. In people with normal red cell survival this causes only a transient dip; where survival is already shortened, as in sickle cell disease or hereditary spherocytosis, it precipitates aplastic crisis."),
      H("In children it causes erythema infectiosum (fifth disease): a 'slapped cheek' facial rash followed by a lacy reticular rash on the limbs. In adults, especially women, it more often causes a symmetric polyarthropathy that mimics rheumatoid arthritis. Patients are contagious before the rash appears, so isolation afterwards is of little value."),
      P("In pregnancy, infection of fetal erythroid precursors causes severe anemia, high-output failure, and hydrops fetalis. In the immunocompromised it causes chronic pure red cell aplasia, treated with IVIG."),
    ]),
    S("Polyomaviruses and poxviruses", [
      H("JC virus reactivates in severe immunosuppression and infects oligodendrocytes, causing progressive multifocal leukoencephalopathy - asymmetric non-enhancing white matter lesions with progressive deficits. Natalizumab, rituximab, and advanced HIV are the classic settings. BK virus reactivates after kidney transplant, causing nephropathy and graft loss, and hemorrhagic cystitis after marrow transplant."),
      H("Poxviruses are unique among DNA viruses in replicating entirely in the cytoplasm, so they must carry their own DNA-dependent RNA polymerase in the virion. Molluscum contagiosum produces umbilicated dome-shaped papules that resolve spontaneously in healthy children; extensive facial lesions in an adult suggest HIV."),
    ]),
  ]),

E("influenza", "Influenza Viruses", "RNA Viruses",
  "A segmented negative-sense RNA virus whose segmentation is the whole story: drift causes epidemics, shift causes pandemics.",
  aka=["flu", "influenza A", "influenza B"],
  keywords=["antigenic drift", "antigenic shift", "reassortment", "hemagglutinin", "neuraminidase", "oseltamivir", "Reye"],
  treatment="Oseltamivir or baloxavir, best within 48 hours. Annual inactivated vaccine for everyone 6 months and older.",
  quick=[("Genome", "8 segments of negative-sense single-stranded RNA, enveloped"),
         ("HA", "Hemagglutinin - binds sialic acid, mediates entry"),
         ("NA", "Neuraminidase - cleaves sialic acid to release progeny"),
         ("Drift", "Point mutations - seasonal epidemics"),
         ("Shift", "Reassortment of whole segments - pandemics, influenza A only")],
  images=[("fig-flu-shift.jpg", "Antigenic shift: reassortment of genome segments during co-infection.")],
  sections=[
    S("Drift versus shift", [
      H("Antigenic drift is the gradual accumulation of point mutations in hemagglutinin and neuraminidase, caused by an RNA polymerase with no proofreading. It produces seasonal epidemics and is why the vaccine is reformulated annually."),
      H("Antigenic shift is reassortment: when two different influenza A strains infect one cell, the eight segments are repackaged, producing a virus with a hemagglutinin the population has never seen. This is possible only because the genome is segmented, occurs only in influenza A (which has avian and swine reservoirs), and is what causes pandemics."),
      P("Pigs are a classic 'mixing vessel' because their respiratory epithelium carries both the alpha-2,6 sialic acid receptors preferred by human strains and the alpha-2,3 receptors preferred by avian strains, allowing co-infection and reassortment."),
    ]),
    S("Antivirals, vaccines, and complications", [
      H("Oseltamivir and zanamivir inhibit neuraminidase, so progeny virions remain tethered to sialic acid on the cell surface and cannot spread. Baloxavir inhibits the cap-dependent endonuclease of the viral polymerase and is given as a single dose. Amantadine blocked the M2 ion channel but is obsolete because of resistance."),
      H("The injectable vaccine is inactivated and safe in pregnancy and immunosuppression; the intranasal vaccine is live attenuated and is not. Because immunity wanes and strains drift, annual vaccination is required."),
      P("The major complication is secondary bacterial pneumonia - S. pneumoniae most commonly, and S. aureus for the severe necrotizing form - because influenza denudes respiratory epithelium and impairs neutrophil function. Aspirin in children with influenza or varicella risks Reye syndrome, an encephalopathy with hepatic microvesicular steatosis."),
    ]),
  ]),

E("paramyxo", "Measles, Mumps, RSV & Parainfluenza", "RNA Viruses",
  "The paramyxoviruses plus measles: non-segmented negative-sense RNA viruses of childhood, three of them vaccine-preventable.",
  aka=["measles", "rubeola", "mumps", "RSV", "croup", "bronchiolitis", "parainfluenza"],
  keywords=["Koplik spots", "SSPE", "orchitis", "parotitis", "steeple sign", "palivizumab", "Warthin-Finkeldey"],
  treatment="All supportive. Measles: vitamin A reduces mortality. Croup: dexamethasone, plus nebulized epinephrine if stridor at rest. RSV prophylaxis: palivizumab or nirsevimab for high-risk infants.",
  quick=[("Genome", "Non-segmented negative-sense single-stranded RNA, enveloped"),
         ("Measles", "Cough, coryza, conjunctivitis, Koplik spots, then rash"),
         ("Mumps", "Parotitis, orchitis, aseptic meningitis, pancreatitis"),
         ("RSV", "Bronchiolitis - wheezing in infants under 2"),
         ("Parainfluenza", "Croup - barking cough, steeple sign")],
  images=[("koplik.jpg", "Koplik spots: gray-white buccal lesions preceding the measles rash."),
          ("measles-rash.jpg", "Measles: a confluent maculopapular rash spreading downward from the hairline."),
          ("mumps.jpg", "Mumps parotitis - bilateral, non-suppurative swelling.")],
  sections=[
    S("Measles", [
      H("Prodrome of the three Cs - cough, coryza, conjunctivitis - with high fever, then Koplik spots (gray-white buccal papules with a red halo), which are pathognomonic and precede the rash by a day or two. The rash begins at the hairline and spreads downward, becoming confluent."),
      H("Complications are otitis media (most common), pneumonia (most common cause of death), and encephalitis. Subacute sclerosing panencephalitis is a fatal progressive dementia and myoclonus appearing 7-10 years after infection, caused by a persistent defective virus."),
      P("Measles infects lymphocytes through CD150 and depletes pre-existing memory B and T cells - 'immune amnesia' - leaving heightened susceptibility to other infections for months to years. This is one of the strongest arguments for vaccination beyond preventing measles itself. Vitamin A reduces mortality in children."),
      P("It is among the most contagious infections known, with airborne transmission and a basic reproduction number of 12-18, which is why herd immunity requires very high vaccine coverage. The vaccine is live attenuated, so it is contraindicated in pregnancy and severe immunosuppression."),
    ]),
    S("Mumps, RSV and parainfluenza", [
      H("Mumps causes bilateral non-suppurative parotitis. Post-pubertal orchitis can impair fertility but rarely causes sterility; other complications are aseptic meningitis, pancreatitis, and sensorineural hearing loss. Mnemonic for mumps: Parotitis, Orchitis, aseptic Meningitis."),
      H("RSV is the leading cause of bronchiolitis and pneumonia in infants: wheezing, tachypnea, and hyperinflation in a child under two. It forms multinucleated giant cells (syncytia) through its F protein - the target of palivizumab and nirsevimab, the monoclonal antibodies used for prophylaxis in high-risk infants."),
      H("Parainfluenza causes croup (laryngotracheobronchitis): a barking seal-like cough, inspiratory stridor, and hoarseness from subglottic narrowing, with the 'steeple sign' on a frontal neck radiograph. Treatment is dexamethasone, with nebulized epinephrine if there is stridor at rest."),
    ]),
  ]),

E("picorna-calici", "Enteroviruses, Rhinovirus, Norovirus & Rotavirus", "RNA Viruses",
  "The gut and airway RNA viruses: polio and coxsackie, the common cold, and the two great causes of gastroenteritis.",
  aka=["poliovirus", "coxsackievirus", "rhinovirus", "norovirus", "rotavirus", "echovirus"],
  keywords=["hand-foot-mouth", "herpangina", "myocarditis", "aseptic meningitis", "cruise ship", "NSP4"],
  treatment="All supportive. Prevention: polio and rotavirus vaccines; norovirus control needs soap-and-water handwashing and bleach.",
  quick=[("Picornaviruses", "Naked, positive-sense ssRNA (polio, coxsackie, echo, rhino, HAV)"),
         ("Rhinovirus", "Acid-labile, prefers 33°C - upper airway only"),
         ("Norovirus", "Naked calicivirus - resists alcohol gel"),
         ("Rotavirus", "Naked, segmented double-stranded RNA; NSP4 enterotoxin")],
  images=[("hfmd.jpg", "Hand-foot-and-mouth disease from coxsackievirus A16."),
          ("rotavirus-em.jpg", "Rotavirus particles with their wheel-like outline.")],
  sections=[
    S("Enteroviruses", [
      H("Poliovirus enters by the fecal-oral route, replicates in gut lymphoid tissue, and in a minority of cases reaches anterior horn cells, destroying lower motor neurons. The result is asymmetric flaccid paralysis with absent reflexes and fully intact sensation - the contrast with Guillain-Barre, which is symmetric, ascending, and demyelinating."),
      P("Oral polio vaccine is live attenuated and produces strong intestinal IgA that interrupts transmission, but it can revert to neurovirulence and is contraindicated in immunodeficiency. Inactivated vaccine is safe and produces IgG but less mucosal immunity, so it protects the individual while permitting some gut replication."),
      H("Coxsackie A causes herpangina (posterior oral vesicles and ulcers) and hand-foot-and-mouth disease. Coxsackie B causes myocarditis and pericarditis, and pleurodynia (Bornholm disease, 'devil's grip'). Enteroviruses collectively are the most common cause of aseptic meningitis."),
    ]),
    S("Rhinovirus", [
      H("Rhinovirus grows best at about 33°C and is acid-labile, so it cannot survive gastric passage - which is precisely why, unlike the other picornaviruses, it causes only upper respiratory disease. It binds ICAM-1 on respiratory epithelium, and with more than 100 serotypes immunity is type-specific, so there is no vaccine."),
    ]),
    S("Gastroenteritis viruses", [
      H("Norovirus causes explosive outbreaks on cruise ships, in schools, and in nursing homes. It is non-enveloped and therefore resistant to alcohol hand gel, so control requires soap-and-water handwashing and bleach disinfection. Its infectious dose is tiny and shedding continues after symptoms resolve."),
      H("Rotavirus is the classic cause of severe infant gastroenteritis in winter. It destroys small bowel villous tips, causing osmotic diarrhea, and its NSP4 protein acts as a viral enterotoxin driving secretion. The vaccine is live and oral, carries a small increase in intussusception risk, and is avoided in infants with prior intussusception or SCID."),
    ]),
  ]),

E("arbo-other-rna", "Arboviruses, Rabies, Prions & Other RNA Viruses", "RNA Viruses",
  "Mosquito- and tick-borne viruses, the rhabdovirus of rabies, filoviruses, and the proteinaceous outlier.",
  aka=["dengue", "yellow fever", "Zika", "chikungunya", "West Nile", "rabies", "Ebola", "prion", "HTLV"],
  keywords=["breakbone fever", "antibody-dependent enhancement", "Negri bodies", "microcephaly", "Creutzfeldt-Jakob"],
  treatment="Supportive. Rabies post-exposure prophylaxis: wound washing, immune globulin infiltrated into the wound, and vaccine - effective only before symptoms.",
  quick=[("Flaviviruses", "Dengue, yellow fever, Zika, West Nile - Aedes or Culex"),
         ("Dengue severity", "Antibody-dependent enhancement on second infection"),
         ("Rabies", "Rhabdovirus; retrograde axonal transport; Negri bodies"),
         ("Prions", "PrPc alpha-helix converts to PrPsc beta-sheet"),
         ("HTLV-1", "Adult T-cell leukemia/lymphoma; tropical spastic paraparesis")],
  images=[("negri.jpg", "Negri bodies: eosinophilic cytoplasmic inclusions in neurons."),
          ("ebola-em.jpg", "Ebola virion - the filamentous filovirus."),
          ("blueberry.jpg", "'Blueberry muffin' rash of congenital infection.")],
  sections=[
    S("Arboviruses", [
      H("Dengue causes high fever, severe retro-orbital and musculoskeletal pain ('breakbone fever'), and thrombocytopenia. Severe dengue arises through antibody-dependent enhancement: non-neutralizing antibody from a previous serotype binds a new serotype and promotes Fc receptor-mediated uptake into monocytes, raising viral load and cytokine release, producing plasma leakage, hemorrhage, and shock."),
      H("Yellow fever causes hepatic necrosis with jaundice and hematemesis ('black vomit') and has a highly effective live attenuated vaccine. Chikungunya causes prominent and often prolonged polyarthralgia. Zika is transmitted sexually and vertically as well as by mosquito, and causes congenital microcephaly with intracranial calcifications; Guillain-Barre is a recognized adult complication."),
      P("West Nile virus is spread by Culex mosquitoes with birds as the reservoir and causes encephalitis with a characteristic flaccid paralysis in a minority of patients."),
    ]),
    S("Rabies and filoviruses", [
      H("Rabies virus travels by retrograde axonal transport from the bite site to the CNS, which is why the incubation period depends on how far the bite is from the brain and why the virus is not found in blood. Negri bodies are eosinophilic cytoplasmic inclusions in neurons, classically in Purkinje cells and hippocampus."),
      H("Once encephalitic symptoms begin - agitation, hydrophobia, hypersalivation - the disease is nearly always fatal. Post-exposure prophylaxis works only beforehand and consists of wound washing, rabies immune globulin infiltrated around the wound, and vaccine. Bat exposure warrants prophylaxis even without a visible bite, because bat bites can go unnoticed."),
      P("Ebola and Marburg are filoviruses causing viral hemorrhagic fever with high mortality, transmitted by direct contact with body fluids; healthcare and burial practices drive outbreaks."),
    ]),
    S("Prions and HTLV", [
      H("Prion disease results from conversion of normal alpha-helical PrPc into beta-sheet-rich PrPsc, which is protease-resistant, aggregates, and templates further misfolding - a self-propagating conformational change with no nucleic acid involved. Creutzfeldt-Jakob disease causes rapidly progressive dementia with startle myoclonus and periodic sharp waves on EEG, with spongiform change on histology."),
      P("Prions resist standard autoclaving, formalin, and routine disinfection, which is why contaminated neurosurgical instruments have transmitted disease. Variant CJD followed exposure to bovine spongiform encephalopathy, and kuru followed ritual cannibalism."),
      P("HTLV-1 is a retrovirus endemic in Japan and the Caribbean causing adult T-cell leukemia/lymphoma - with lytic bone lesions and hypercalcemia - and HTLV-1-associated myelopathy (tropical spastic paraparesis)."),
    ]),
  ]),

E("hiv", "HIV & Antiretroviral Therapy", "RNA Viruses",
  "A retrovirus that destroys the CD4 cell, with a drug target at almost every step of its life cycle.",
  aka=["human immunodeficiency virus", "AIDS", "ART", "HAART"],
  keywords=["CD4", "viral load", "gp120", "CCR5", "reverse transcriptase", "integrase", "protease", "PrEP", "IRIS"],
  treatment="Two NRTIs plus an integrase strand transfer inhibitor is standard first-line (e.g. bictegravir/emtricitabine/tenofovir alafenamide). Start regardless of CD4 count.",
  quick=[("Genome", "Two copies of positive-sense ssRNA, enveloped retrovirus"),
         ("Entry", "gp120 binds CD4 plus CCR5 (early) or CXCR4 (late); gp41 fuses"),
         ("Screening", "4th-generation antigen/antibody test, then differentiation assay"),
         ("Acute infection", "HIV RNA - antibody tests are negative in the window period"),
         ("Suffixes", "-gravir integrase, -navir protease, -virine NNRTI, -viroc CCR5")],
  images=[("fig-hiv-cycle.jpg", "The HIV replication cycle, with the step each drug class blocks.")],
  sections=[
    S("Life cycle and drug targets", [
      H("gp120 binds CD4, changes shape, and then engages a chemokine co-receptor - CCR5 on macrophages and memory T cells early in infection, CXCR4 later. gp41 then drives membrane fusion. Homozygous CCR5-delta32 deletion confers near-complete resistance to R5-tropic strains."),
      P("Reverse transcriptase copies the RNA genome into DNA with no proofreading, which is the source of the enormous mutation rate and of resistance. Integrase splices the provirus into host DNA, creating the latent reservoir that prevents cure. Protease cleaves the Gag-Pol polyprotein during budding; without it, released virions remain immature and non-infectious."),
      H("Drug classes map onto these steps: NRTIs and NNRTIs block reverse transcriptase, integrase inhibitors block integration, protease inhibitors block maturation, maraviroc blocks CCR5 (requiring a tropism assay first), and enfuvirtide blocks gp41-mediated fusion."),
    ]),
    S("Diagnosis and monitoring", [
      H("A reactive fourth-generation antigen/antibody screen with a negative antibody differentiation assay suggests acute infection, when p24 antigen is present before antibody. HIV RNA testing resolves it. Recognizing acute infection matters because viral load and transmissibility are extremely high."),
      H("Acute retroviral syndrome resembles mononucleosis - fever, pharyngitis, diffuse lymphadenopathy, rash - with mucocutaneous ulcers as a useful distinguishing clue. CD4 count stages disease and predicts opportunistic infection; viral load measures treatment response."),
    ]),
    S("Opportunistic infections by CD4 count", [
      H("Below 200: Pneumocystis pneumonia - begin TMP-SMX prophylaxis at this threshold. Below 100: toxoplasmosis and cryptococcal disease. Below 50: CMV retinitis and disseminated MAC. Tuberculosis and bacterial pneumonia occur at any CD4 count."),
      P("Immune reconstitution inflammatory syndrome occurs weeks to months after starting therapy at a low CD4 count, as recovering immunity mounts an inflammatory response against residual antigen. Cultures are negative because this is inflammation, not uncontrolled infection; antiretrovirals are usually continued, with steroids in severe cases. Cryptococcal meningitis is the exception where antiretroviral therapy is deliberately delayed a few weeks."),
    ]),
    S("Drug toxicities and prevention", [
      H("Abacavir causes a potentially fatal hypersensitivity reaction tied to HLA-B*57:01, so genotyping is mandatory before use. Zidovudine causes marrow suppression; tenofovir disoproxil causes proximal tubular injury and reduced bone density. Protease inhibitors cause metabolic syndrome, lipodystrophy, and many CYP interactions."),
      H("Perinatal transmission falls to about 1% with maternal antiretroviral therapy, scheduled cesarean delivery if the viral load exceeds 1,000 copies/mL near term, intrapartum zidovudine, infant prophylaxis, and formula feeding where it is safe."),
      P("Pre-exposure prophylaxis with tenofovir-emtricitabine (or long-acting cabotegravir) is highly effective in people at substantial risk. Post-exposure prophylaxis is a three-drug regimen started within 72 hours and continued 28 days. An undetectable viral load on treatment means the virus is not sexually transmitted."),
    ]),
  ]),

E("hepatitis", "Hepatitis Viruses A through E", "Hepatitis Viruses",
  "Five unrelated viruses grouped by the organ they damage - separated by route, chronicity, and serology.",
  aka=["HAV", "HBV", "HCV", "HDV", "HEV", "hepatitis"],
  keywords=["HBsAg", "anti-HBc", "window period", "cirrhosis", "hepatocellular carcinoma", "ground glass", "cryoglobulinemia"],
  treatment="HBV: tenofovir or entecavir when indicated. HCV: direct-acting antivirals cure >95%. HAV/HEV: supportive. HDV: treat the HBV; pegylated interferon or bulevirtide.",
  quick=[("Fecal-oral", "A and E (vowels come from the bowels)"),
         ("Bloodborne", "B, C, D"),
         ("Chronic", "B (5% of adults, 90% of neonates), C (~75%), D"),
         ("Vaccine", "A and B (and therefore D)"),
         ("Cancer risk", "B (even without cirrhosis) and C (via cirrhosis)")],
  images=[("ground-glass.jpg", "'Ground glass' hepatocytes in chronic hepatitis B.")],
  sections=[
    S("Hepatitis B serology - the central skill", [
      H("HBsAg means active infection, acute or chronic. Anti-HBs means immunity, from vaccination or resolved infection. Anti-HBc means natural infection has occurred at some point - the vaccine contains only surface antigen, so it never produces core antibody."),
      H("So: anti-HBs alone = vaccinated. Anti-HBs plus anti-HBc = resolved infection with immunity. HBsAg plus anti-HBc = current infection (IgM anti-HBc if acute, IgG if chronic). The window period is the interval when HBsAg has disappeared but anti-HBs has not yet appeared, and IgM anti-HBc is the only positive marker."),
      H("HBeAg indicates active replication and high infectivity, including high perinatal transmission risk; seroconversion to anti-HBe usually accompanies falling viral load. Precore mutants replicate actively while remaining HBeAg-negative, so HBV DNA is measured alongside serology."),
    ]),
    S("Hepatitis B biology", [
      P("HBV is a DNA virus that uses reverse transcriptase: it transcribes its partially double-stranded circular DNA into a pregenomic RNA, which is reverse transcribed back into DNA inside the capsid. That is why nucleoside analogs such as tenofovir and entecavir work against it, and why HIV drugs and HBV drugs overlap."),
      H("HBV DNA can integrate into the host genome, and the X protein disrupts p53 and transcriptional control. This is why hepatitis B can cause hepatocellular carcinoma without passing through cirrhosis first, unlike hepatitis C, where cancer essentially requires cirrhosis."),
      P("Chronicity depends on the age at infection - a paradox explained by immune maturity. Perinatal infection becomes chronic in about 90% of cases because the immature immune system tolerates the virus; adult infection becomes chronic in under 5% because a vigorous response clears it (and that vigorous response is what makes the adult symptomatic). Extrahepatic disease includes polyarteritis nodosa and membranous nephropathy."),
    ]),
    S("Hepatitis C, D, A and E", [
      H("HCV has an RNA-dependent RNA polymerase without proofreading, so hypervariable envelope regions generate quasispecies that escape neutralizing antibody. This explains both the high chronicity rate and the absence of a vaccine. Direct-acting antivirals now cure over 95%: -previr (NS3/4A protease), -asvir (NS5A), -buvir (NS5B polymerase)."),
      P("Mixed cryoglobulinemia is the classic extrahepatic manifestation of HCV: immune complexes of IgM rheumatoid factor and IgG deposit in small vessels, causing palpable purpura, arthralgia, neuropathy, and membranoproliferative glomerulonephritis with low complement. Treating the virus treats the vasculitis."),
      H("HDV is a defective virus that requires HBsAg as its envelope, so it infects only people with hepatitis B - and hepatitis B vaccination prevents it. Simultaneous coinfection usually resolves with the HBV; superinfection of an established chronic carrier causes a severe flare and accelerated cirrhosis."),
      H("HAV and HEV are enterically transmitted and never become chronic in healthy hosts. HEV carries mortality up to 20% in the third trimester of pregnancy and has a swine reservoir; chronic HEV occurs only with immunosuppression. HAV post-exposure prophylaxis within two weeks uses vaccine for healthy people aged 12 months to 40 years and immune globulin for infants, adults over 40, and the immunocompromised."),
    ]),
  ]),
]
