"""Encyclopedia: fungi, protozoa, and helminths."""
from ecore import E, S, P, H

ENTRIES = [
E("candida", "Candida Species", "Fungi",
  "A commensal yeast that becomes pathogenic when either of two defenses fails - T cells at the mucosa, neutrophils in the bloodstream.",
  aka=["Candida albicans", "thrush", "candidiasis", "C. glabrata", "C. auris"],
  keywords=["germ tube", "pseudohyphae", "esophagitis", "candidemia", "diaper rash", "vulvovaginitis"],
  treatment="Thrush: nystatin or clotrimazole. Esophagitis: oral fluconazole. Candidemia: an echinocandin, plus removal of central lines and a dilated eye examination.",
  quick=[("Morphology", "Budding yeast with pseudohyphae; true hyphae in tissue"),
         ("Germ tube", "Positive in C. albicans (serum, 37°C, 3 h)"),
         ("Agar", "Chlamydospores on cornmeal agar"),
         ("Resistance", "C. glabrata and C. krusei often fluconazole-resistant"),
         ("C. auris", "Multidrug-resistant, persists on surfaces, outbreak-prone")],
  images=[("thrush.jpg", "Oral thrush: white plaques that scrape off leaving an erythematous base."),
          ("candida-gram.jpg", "Budding yeast with pseudohyphae."),
          ("germ-tube.jpg", "Positive germ tube test identifying C. albicans.")],
  sections=[
    S("Two defenses, two diseases", [
      H("T cells control Candida at mucosal surfaces, so T-cell defects - HIV, corticosteroids, chronic mucocutaneous candidiasis (IL-17 pathway and STAT1 defects) - produce thrush, esophagitis, and vulvovaginitis but not invasive disease."),
      H("Neutrophils prevent tissue invasion and bloodstream spread, so neutropenia, central venous catheters, broad-spectrum antibiotics, total parenteral nutrition, and abdominal surgery produce candidemia and disseminated disease with hepatosplenic and retinal lesions."),
      P("This division is one of the cleanest illustrations in microbiology that the host determines the syndrome. The same organism causes a trivial white plaque in one patient and fatal fungemia in another, purely as a function of which arm of immunity is missing."),
    ]),
    S("Clinical points", [
      H("Oral thrush produces white plaques that scrape off leaving an erythematous base - the contrast with oral hairy leukoplakia (EBV), which does not scrape off. Esophageal candidiasis causes odynophagia and is an AIDS-defining illness, treated empirically with systemic fluconazole; endoscopy is reserved for non-responders, to look for CMV or HSV."),
      P("Candidemia requires source control: central lines are removed, and every patient has a dilated ophthalmologic examination because endophthalmitis changes both drug choice and duration. Species identification matters because C. glabrata and C. krusei are frequently fluconazole-resistant, and C. auris is resistant to multiple classes and spreads within hospitals."),
    ]),
  ]),

E("aspergillus-mucor", "Aspergillus & Mucormycosis", "Fungi",
  "Two angioinvasive molds distinguished by branching angle, septation, and the host who gets them.",
  aka=["Aspergillus fumigatus", "ABPA", "aspergilloma", "Rhizopus", "Mucor", "zygomycosis"],
  keywords=["halo sign", "air crescent", "fungus ball", "black eschar", "ketoacidosis", "septate", "45 degrees"],
  treatment="Invasive aspergillosis: voriconazole (or isavuconazole). ABPA: corticosteroids plus itraconazole. Mucormycosis: urgent surgical debridement plus liposomal amphotericin B and correction of the acidosis.",
  quick=[("Aspergillus", "Septate hyphae branching at acute (45°) angles"),
         ("Mucorales", "Broad, ribbon-like, NON-septate, wide-angle (90°) branching"),
         ("Aspergillus host", "Neutropenia, transplant, chronic steroids"),
         ("Mucor host", "Diabetic ketoacidosis, deferoxamine, neutropenia"),
         ("Marker", "Serum and lavage galactomannan for Aspergillus")],
  images=[("aspergillus.jpg", "Aspergillus: septate hyphae branching at acute angles."),
          ("halo-sign.jpg", "CT halo sign - infarcted nodule surrounded by hemorrhage."),
          ("mucor.jpg", "Mucormycosis: broad non-septate hyphae with wide-angle branching.")],
  sections=[
    S("Aspergillus - three diseases by host", [
      H("Allergic bronchopulmonary aspergillosis occurs in asthma and cystic fibrosis: a hypersensitivity reaction with wheezing, very high IgE, eosinophilia, positive Aspergillus skin test, and central bronchiectasis. It is treated with corticosteroids plus itraconazole, not with an antifungal alone."),
      H("Aspergilloma is a fungus ball colonizing a pre-existing cavity, classically an old tuberculous cavity, presenting with hemoptysis. It moves with position on imaging and produces the air-crescent sign. It is colonization, not invasion."),
      H("Invasive aspergillosis occurs in prolonged neutropenia or transplantation. The organism invades blood vessels, causing infarction and hemorrhage - the CT halo sign is an infarcted nodule with a rim of hemorrhage. Treatment is voriconazole; galactomannan and beta-D-glucan assays aid diagnosis."),
    ]),
    S("Mucormycosis", [
      H("Ketoacidosis both lowers pH and reduces iron binding by transferrin, and Rhizopus possesses a ketone reductase that lets it thrive in that environment - which is why diabetic ketoacidosis is the classic setting. Deferoxamine therapy, which delivers iron to the fungus, is another."),
      H("Rhinocerebral disease begins in the sinuses with facial pain and a black necrotic eschar on the palate or turbinates, then invades the orbit and brain, producing proptosis and cranial nerve palsies. Because the fungus invades vessels and causes thrombosis, antifungals cannot reach the dead tissue - urgent wide surgical debridement is essential, alongside liposomal amphotericin B."),
    ]),
  ]),

E("crypto-pcp", "Cryptococcus & Pneumocystis", "Fungi",
  "The two defining fungal opportunists of advanced HIV: one an encapsulated yeast causing meningitis, one an unculturable organism causing pneumonia.",
  aka=["Cryptococcus neoformans", "Pneumocystis jirovecii", "PCP", "PJP"],
  keywords=["India ink", "cryptococcal antigen", "pigeon droppings", "ground glass", "LDH", "silver stain"],
  treatment="Cryptococcal meningitis: amphotericin B plus flucytosine, then fluconazole, with serial lumbar punctures. PCP: TMP-SMX, adding steroids if PaO2 <70 mm Hg or A-a gradient >35.",
  quick=[("Cryptococcus", "Encapsulated yeast, narrow-based budding, urease+"),
         ("Source", "Pigeon droppings and soil; C. gattii in eucalyptus"),
         ("Best test", "Cryptococcal antigen (CrAg) in serum or CSF"),
         ("Pneumocystis", "Cannot be cultured; silver or immunofluorescent stain"),
         ("PCP prophylaxis", "TMP-SMX when CD4 <200")],
  images=[("crypto-ink.jpg", "India ink: the capsule excludes ink, leaving a clear halo."),
          ("crypto-mucicarmine.jpg", "Mucicarmine stains the cryptococcal capsule red."),
          ("pcp-gms.jpg", "Silver stain showing the crushed ping-pong ball cysts of Pneumocystis.")],
  sections=[
    S("Cryptococcus", [
      H("The polysaccharide capsule is the key virulence factor: it blocks phagocytosis and complement, and its shed antigen is what the highly sensitive cryptococcal antigen test detects. India ink shows the capsule as a negative image - a clear halo the ink cannot penetrate."),
      H("Disease is a subacute meningoencephalitis with headache and few meningeal signs, because the inflammatory response is muted. What kills patients is raised intracranial pressure from capsular polysaccharide obstructing CSF outflow, so serial therapeutic lumbar punctures are as important as the antifungals."),
      P("Antiretroviral therapy is deliberately delayed by several weeks after starting antifungal treatment, because starting it early increases IRIS-related mortality. Corticosteroids worsen outcomes and are not used. Cryptococcal antigen screening is recommended for patients with CD4 counts below 100."),
    ]),
    S("Pneumocystis jirovecii", [
      H("Formerly classified as a protozoan, now known to be a fungus - but it lacks ergosterol, which is why azoles and amphotericin do not work and TMP-SMX does. It cannot be cultured, so diagnosis relies on staining induced sputum or bronchoalveolar lavage, or on PCR."),
      H("Presentation is subacute exertional dyspnea, a dry cough, and hypoxia out of proportion to examination findings, with diffuse bilateral ground-glass opacities and a raised LDH. Corticosteroids are added when the PaO2 is below 70 mm Hg or the A-a gradient exceeds 35, because killing the organisms triggers inflammation that worsens hypoxemia."),
      P("Prophylaxis with TMP-SMX begins at a CD4 count below 200 and also protects against toxoplasmosis. Alternatives for sulfa allergy are atovaquone, dapsone (check G6PD), or inhaled pentamidine."),
    ]),
  ]),

E("dimorphic", "Dimorphic Fungi", "Fungi",
  "Mold in the cold, yeast in the heat: four endemic fungi identified by geography plus tissue morphology.",
  aka=["Histoplasma", "Blastomyces", "Coccidioides", "Paracoccidioides", "valley fever"],
  keywords=["Ohio river valley", "bat droppings", "spherule", "broad-based budding", "captain's wheel", "erythema nodosum"],
  treatment="Mild disease may need none. Moderate: itraconazole (fluconazole for Coccidioides, lifelong for its meningitis). Severe or disseminated: amphotericin B, then an azole.",
  quick=[("Histoplasma", "Ohio/Mississippi valleys; bird and bat droppings; yeast INSIDE macrophages"),
         ("Blastomyces", "Eastern US, Great Lakes; broad-BASED budding, thick wall"),
         ("Coccidioides", "Southwest US; SPHERULE packed with endospores"),
         ("Paracoccidioides", "Latin America; 'captain's wheel' multiple budding"),
         ("Rule", "All are mold at 25°C and yeast at 37°C (except Coccidioides: spherule)")],
  images=[("histo-mac.jpg", "Histoplasma: small yeast filling macrophages."),
          ("blasto.jpg", "Blastomyces: broad-based budding with a thick refractile wall."),
          ("cocci-spherule.jpg", "Coccidioides spherule packed with endospores."),
          ("paracocci.jpg", "Paracoccidioides: the 'captain's wheel' of multiple buds.")],
  sections=[
    S("The shared pattern", [
      H("All four are dimorphic: a mold with hyphae in the environment at 25°C, and a yeast (or, for Coccidioides, a spherule) in tissue at 37°C. Infection follows inhalation of spores, and the primary illness is a self-limited pneumonia that is frequently mistaken for community-acquired pneumonia or tuberculosis."),
      P("Containment, as with tuberculosis, depends on cell-mediated immunity and granuloma formation. That is why dissemination occurs in HIV, transplant recipients, and patients on TNF inhibitors, and why histoplasmosis and tuberculosis are both screened for before starting those drugs."),
    ]),
    S("The four organisms", [
      H("Histoplasma capsulatum: Ohio and Mississippi river valleys, associated with bird and bat droppings and cave exploration. Tissue form is small oval yeast within macrophages. Disseminated disease causes fever, pancytopenia, hepatosplenomegaly, and oral ulcers; the urine antigen test is sensitive."),
      H("Blastomyces dermatitidis: eastern United States and Great Lakes region. Broad-based budding yeast with a thick doubly refractile wall. It disseminates to skin, producing verrucous lesions that mimic squamous cell carcinoma, and to bone."),
      H("Coccidioides immitis: southwestern United States deserts, with increased risk after earthquakes and dust storms. Forms a spherule packed with endospores. Primary infection ('valley fever') may cause erythema nodosum and arthralgia - 'desert rheumatism' - which paradoxically indicates a good immune response. Dissemination risk is higher in pregnancy and in people of Filipino and African ancestry; meningitis requires lifelong fluconazole."),
      P("Paracoccidioides brasiliensis: Latin America, with a yeast showing multiple buds around a mother cell - the 'captain's wheel' or 'pilot's wheel'. It affects adult men far more often than women, apparently because estrogen inhibits the mold-to-yeast transition."),
    ]),
  ]),

E("superficial-fungi", "Dermatophytes, Malassezia & Sporothrix", "Fungi",
  "Skin and subcutaneous fungi: ringworm, tinea versicolor, and the rose gardener's ascending nodules.",
  aka=["tinea", "ringworm", "Trichophyton", "tinea versicolor", "sporotrichosis"],
  keywords=["KOH", "spaghetti and meatballs", "Wood lamp", "hypopigmentation", "lymphocutaneous", "griseofulvin"],
  treatment="Tinea corporis/pedis: topical azole or terbinafine. Tinea capitis and onychomycosis need oral terbinafine or itraconazole. Tinea versicolor: topical selenium sulfide or ketoconazole. Sporotrichosis: itraconazole for months.",
  quick=[("Dermatophytes", "Trichophyton, Microsporum, Epidermophyton; KOH shows septate hyphae"),
         ("Malassezia", "Lipophilic yeast; 'spaghetti and meatballs' on KOH"),
         ("Tinea capitis", "Requires ORAL therapy - topicals cannot reach the follicle"),
         ("Sporothrix", "Dimorphic; thorn or sphagnum moss inoculation")],
  images=[("tinea-corporis.jpg", "Tinea corporis: an annular scaly plaque with an active advancing border."),
          ("malassezia.jpg", "'Spaghetti and meatballs': short hyphae with clusters of yeast."),
          ("onychomycosis.jpg", "Onychomycosis - thickened, discolored, dystrophic nail."),
          ("sporotrichosis.jpg", "Sporotrichosis: nodules ascending along lymphatics.")],
  sections=[
    S("Dermatophytes and Malassezia", [
      H("Dermatophytes digest keratin and infect skin, hair, and nails, producing annular scaly plaques with central clearing and an active advancing border. KOH shows septate branching hyphae. Tinea capitis and onychomycosis require oral therapy, because topical agents cannot reach the hair follicle or nail bed."),
      H("Malassezia furfur causes tinea versicolor: hypo- or hyperpigmented scaly macules on the trunk, most visible after sun exposure. It degrades skin lipids into azelaic acid, which inhibits tyrosinase in melanocytes - the mechanism of the hypopigmentation. KOH shows short curved hyphae with round yeast, the 'spaghetti and meatballs' pattern. It also causes seborrheic dermatitis and, in neonates on intravenous lipid emulsions, catheter-related fungemia."),
      P("Griseofulvin, which binds microtubules and is deposited in keratin, is effective for dermatophytes but not for Malassezia. Terbinafine inhibits squalene epoxidase and is preferred for onychomycosis."),
    ]),
    S("Sporothrix", [
      H("Sporotrichosis follows inoculation by a thorn, splinter, or sphagnum moss - the 'rose gardener's disease'. A nodule at the site is followed by a chain of nodules ascending along the lymphatics (nodular lymphangitis). Treatment is itraconazole for three to six months; potassium iodide is a traditional alternative."),
      P("A similar ascending, sporotrichoid pattern is produced by Mycobacterium marinum, Nocardia brasiliensis, and Leishmania, which is a useful differential to carry when the history involves water, soil, or travel."),
    ]),
  ]),

E("intestinal-protozoa", "Giardia, Entamoeba & Cryptosporidium", "Protozoa",
  "The three intestinal protozoa: one causes fatty malabsorptive diarrhea, one invades and reaches the liver, one is chlorine-resistant.",
  aka=["giardiasis", "amebiasis", "Entamoeba histolytica", "Cryptosporidium", "Cyclospora"],
  keywords=["steatorrhea", "campers", "flask-shaped ulcer", "anchovy paste", "acid-fast oocyst", "IgA deficiency"],
  treatment="Giardia: metronidazole or tinidazole. E. histolytica: metronidazole followed by a luminal agent (paromomycin). Cryptosporidium: restore immunity; nitazoxanide as adjunct.",
  quick=[("Giardia", "Pear-shaped trophozoite, two nuclei, 'falling leaf' motility"),
         ("Entamoeba", "Trophozoite with ingested RBCs; cyst with up to 4 nuclei"),
         ("Cryptosporidium", "Acid-fast oocysts; resists chlorination"),
         ("Diagnosis", "Stool antigen/PCR has largely replaced O&P microscopy")],
  images=[("giardia.jpg", "Giardia trophozoite with its paired nuclei and 'owl face' appearance."),
          ("entamoeba.jpg", "Entamoeba histolytica trophozoite containing ingested red cells."),
          ("crypto-af.jpg", "Acid-fast Cryptosporidium oocysts in stool."),
          ("fig-giardia-cycle.jpg", "Giardia life cycle: cysts ingested from contaminated water excyst in the duodenum.")],
  sections=[
    S("Giardia lamblia", [
      H("Acquired from contaminated streams (campers, hikers), daycare centers, and travel. It attaches to the duodenal brush border with a ventral sucking disc without invading, causing fat malabsorption: bulky, greasy, foul-smelling stools, bloating, and weight loss."),
      H("Recurrent or chronic giardiasis is a classic presentation of selective IgA deficiency, because secretory IgA normally blocks attachment. Such patients may also have anaphylaxis to blood products containing IgA."),
    ]),
    S("Entamoeba histolytica", [
      H("Trophozoites containing ingested red blood cells distinguish pathogenic E. histolytica from non-pathogenic amoebae. It invades colonic mucosa, producing flask-shaped ulcers - narrow-necked and broad-based because the organism spreads laterally once it reaches the submucosa - with bloody diarrhea and tenesmus."),
      H("It reaches the liver via the portal vein, producing a right-lobe abscess with 'anchovy paste' contents that are usually sterile of organisms in the center. Serology is positive; aspiration is not routinely needed. Treatment is metronidazole for invasive disease followed by a luminal agent such as paromomycin to eradicate cysts and prevent relapse."),
    ]),
    S("Cryptosporidium", [
      H("The thick-walled oocyst resists standard chlorination, which is why it causes swimming pool and municipal water outbreaks. In healthy hosts the illness is self-limited watery diarrhea; with CD4 counts below 100 it causes severe chronic diarrhea and wasting, and the definitive treatment is restoring immunity with antiretroviral therapy."),
      P("Oocysts are detected by modified acid-fast stain or, more often now, by stool antigen or multiplex PCR. Cyclospora and Cystoisospora are related acid-fast coccidia; Cyclospora has been linked to imported fresh produce and both respond to TMP-SMX."),
    ]),
  ]),

E("malaria-babesia", "Plasmodium & Babesia", "Protozoa",
  "Red cell parasites: five malaria species with different relapse and severity profiles, and a tick-borne look-alike.",
  aka=["malaria", "P. falciparum", "P. vivax", "babesiosis"],
  keywords=["hypnozoite", "primaquine", "G6PD", "Duffy", "sickle trait", "Maltese cross", "cerebral malaria"],
  treatment="Uncomplicated falciparum: artemisinin-based combination therapy. Severe: IV artesunate. Vivax/ovale: chloroquine plus primaquine or tafenoquine after G6PD testing. Babesia: atovaquone plus azithromycin.",
  quick=[("Vector", "Female Anopheles mosquito (malaria); Ixodes tick (Babesia)"),
         ("Relapse", "P. vivax and P. ovale form liver hypnozoites"),
         ("Severity", "P. falciparum - invades RBCs of all ages, cytoadheres"),
         ("Babesia clue", "Maltese cross tetrad, no pigment, asplenic patient"),
         ("Prophylaxis", "Atovaquone-proguanil, doxycycline, or mefloquine")],
  images=[("pf-rings.jpg", "P. falciparum: delicate ring forms, often multiple per cell."),
          ("pf-gametocyte.jpg", "The banana-shaped gametocyte of P. falciparum."),
          ("pvivax.jpg", "P. vivax: enlarged red cell with Schuffner dots."),
          ("babesia.jpg", "Babesia: the Maltese cross tetrad."),
          ("fig-malaria-cycle.jpg", "Malaria life cycle: sporozoites to liver, merozoites to red cells.")],
  sections=[
    S("Life cycle and relapse", [
      H("Sporozoites injected by the mosquito travel to hepatocytes and mature into merozoites, which invade red cells and cycle through ring, trophozoite, and schizont stages. Red cell rupture causes the paroxysms of fever, chills, and rigors, and the periodicity (48 or 72 hours) reflects the synchrony of that cycle."),
      H("P. vivax and P. ovale form dormant hepatic hypnozoites that cause true relapse weeks to months later. Radical cure requires primaquine or tafenoquine, which must be preceded by G6PD testing because both cause severe hemolysis in deficiency. P. falciparum and P. malariae have no liver stage."),
    ]),
    S("Why falciparum is dangerous", [
      H("P. falciparum invades red cells of every age, so parasitemia can become very high, and it expresses PfEMP1 knobs that bind endothelium. The resulting sequestration in cerebral and placental microvasculature causes cerebral malaria, severe anemia, hypoglycemia, acidosis, and adverse pregnancy outcomes."),
      P("Smear clues to falciparum are high parasitemia, multiple delicate rings per cell, rings at the cell margin ('appliqué' forms), banana-shaped gametocytes, and the absence of enlarged cells or Schuffner dots. Species identification matters because it determines whether artesunate and possible exchange transfusion are needed, and whether primaquine is required."),
    ]),
    S("Host protective polymorphisms and Babesia", [
      H("P. vivax uses the Duffy antigen to enter red cells, so Duffy-negative people, common in West Africa, are largely resistant to it. Sickle cell trait, thalassemia, and G6PD deficiency give partial protection against severe P. falciparum, which is why these alleles persist at high frequency in endemic regions - a textbook example of balancing selection."),
      H("Babesia microti is transmitted by Ixodes ticks in the northeastern and upper midwestern United States, causing fever and hemolytic anemia that is severe in asplenic and elderly patients. The Maltese cross tetrad is characteristic but uncommon, and unlike malaria there is no hemozoin pigment. Co-infection with Lyme disease is common because they share a vector."),
    ]),
  ]),

E("tissue-protozoa", "Toxoplasma, Trypanosomes, Leishmania & Free-Living Amoebae", "Protozoa",
  "Tissue and blood protozoa, each tied to a specific vector, exposure, or immune defect.",
  aka=["Toxoplasma gondii", "Chagas disease", "sleeping sickness", "leishmaniasis", "Naegleria", "Acanthamoeba", "Trichomonas"],
  keywords=["cat litter", "ring-enhancing", "reduviid", "megacolon", "tsetse", "kala-azar", "cribriform plate"],
  treatment="Toxoplasmosis: pyrimethamine, sulfadiazine, leucovorin. Chagas: benznidazole or nifurtimox. Leishmaniasis: liposomal amphotericin B. Trichomonas: metronidazole for patient and partners.",
  quick=[("Toxoplasma", "Cats are definitive host; also undercooked meat"),
         ("T. cruzi", "Reduviid 'kissing' bug; Latin America"),
         ("T. brucei", "Tsetse fly; Africa; antigenic variation (VSG)"),
         ("Leishmania", "Sandfly; amastigotes inside macrophages"),
         ("Naegleria", "Warm fresh water, via cribriform plate; nearly always fatal")],
  images=[("toxo-cyst.jpg", "Toxoplasma tissue cyst packed with bradyzoites."),
          ("tcruzi.jpg", "Trypanosoma cruzi trypomastigote on a blood film."),
          ("romana.jpg", "Romana sign: unilateral periorbital swelling in acute Chagas disease."),
          ("tbrucei.jpg", "Trypanosoma brucei among red cells."),
          ("leish-amast.jpg", "Leishmania amastigotes within a macrophage."),
          ("naegleria.jpg", "Naegleria fowleri trophozoite."),
          ("trich.jpg", "Trichomonas vaginalis - motile flagellate on wet mount.")],
  sections=[
    S("Toxoplasma gondii", [
      H("Cats are the definitive host; humans acquire it from oocysts in cat litter or soil, or from bradyzoite cysts in undercooked meat. Primary infection in immunocompetent adults is usually asymptomatic or a mononucleosis-like illness, after which tissue cysts persist for life in brain and muscle."),
      H("In AIDS with CD4 below 100, reactivation causes multiple ring-enhancing lesions, characteristically in the basal ganglia. Management is empiric pyrimethamine-sulfadiazine with clinical and radiographic reassessment in two weeks; failure to improve prompts biopsy to exclude primary CNS lymphoma, which is typically solitary, periventricular, and EBV-positive on CSF PCR."),
      H("Congenital toxoplasmosis produces the classic triad of chorioretinitis, hydrocephalus, and diffuse intracranial calcifications - contrasting with CMV, which causes periventricular calcifications and microcephaly. Pregnant women are advised to avoid changing cat litter and to cook meat thoroughly."),
    ]),
    S("Trypanosomes and Leishmania", [
      H("Trypanosoma cruzi (Chagas disease) is transmitted by the reduviid bug, which defecates while feeding; the parasite is rubbed into the bite or conjunctiva, producing Romana sign. Chronic disease destroys myenteric plexus ganglion cells, causing megaesophagus and megacolon, and damages myocardium, causing dilated cardiomyopathy with apical aneurysm and conduction disease."),
      H("Trypanosoma brucei (African sleeping sickness) is transmitted by the tsetse fly and evades immunity by switching its variant surface glycoprotein, producing recurrent parasitemia. Winterbottom sign is posterior cervical adenopathy. CNS involvement causes daytime somnolence and reversed sleep-wake cycles, and determines which drugs are used, since early-stage drugs do not cross into the brain."),
      P("Leishmania is transmitted by sandflies and lives as amastigotes inside macrophages. Cutaneous disease produces a chronic ulcer with raised edges; visceral disease (kala-azar, L. donovani) produces fever, massive splenomegaly, pancytopenia, and hypergammaglobulinemia, and is fatal untreated."),
    ]),
    S("Free-living amoebae and Trichomonas", [
      H("Naegleria fowleri enters through the cribriform plate after warm freshwater swimming or nasal irrigation with untreated water, causing fulminant primary amoebic meningoencephalitis that is almost uniformly fatal within a week. Motile trophozoites may be seen in CSF."),
      P("Acanthamoeba and Balamuthia cause a slower granulomatous amoebic encephalitis in immunocompromised hosts; Acanthamoeba also causes keratitis in contact lens wearers who use tap water or poor hygiene."),
      H("Trichomonas vaginalis causes a frothy yellow-green malodorous discharge with a 'strawberry cervix' and a vaginal pH above 4.5; motile flagellates are seen on saline wet mount. It is sexually transmitted, so partners are treated even though men are usually asymptomatic."),
    ]),
  ]),

E("nematodes", "Nematodes (Roundworms)", "Helminths",
  "Intestinal and tissue roundworms, grouped by how they get in: swallowed eggs, skin-penetrating larvae, or an insect bite.",
  aka=["Ascaris", "pinworm", "Enterobius", "hookworm", "Strongyloides", "Trichinella", "Toxocara", "Onchocerca", "Wuchereria"],
  keywords=["eosinophilia", "Loeffler", "tape test", "autoinfection", "hyperinfection", "river blindness", "elephantiasis"],
  treatment="Most intestinal nematodes: albendazole or mebendazole. Strongyloides: ivermectin. Onchocerca: ivermectin (plus doxycycline for Wolbachia). Wuchereria: diethylcarbamazine.",
  quick=[("Ingested eggs", "Ascaris, Enterobius, Trichuris"),
         ("Skin penetration", "Hookworm (Necator, Ancylostoma), Strongyloides"),
         ("Ingested larvae", "Trichinella (undercooked pork/bear)"),
         ("Insect bite", "Onchocerca (blackfly), Wuchereria (mosquito), Loa loa (deer fly)"),
         ("Eosinophilia", "Tissue-invasive helminths only - not luminal tapeworms or protozoa")],
  images=[("ascaris.jpg", "Adult Ascaris lumbricoides."),
          ("enterobius.jpg", "Enterobius egg - flattened on one side."),
          ("strongy.jpg", "Strongyloides rhabditiform larva in stool."),
          ("larva-migrans.jpg", "Cutaneous larva migrans: the serpiginous track of an animal hookworm."),
          ("trichinella-muscle.jpg", "Trichinella larvae encysted in skeletal muscle."),
          ("wuchereria.jpg", "Sheathed microfilaria of Wuchereria bancrofti."),
          ("elephantiasis.jpg", "Lymphatic filariasis with elephantiasis."),
          ("loa.jpg", "Loa loa crossing the conjunctiva.")],
  sections=[
    S("Intestinal nematodes", [
      H("Enterobius vermicularis (pinworm) causes nocturnal perianal itching in children. Eggs are deposited on perianal skin, so the adhesive tape test in the morning is diagnostic while stool examination is usually negative. Treat the child and household contacts, and repeat in two weeks."),
      H("Ascaris lumbricoides is acquired from ingested eggs in contaminated soil. Larvae migrate through the lungs, producing Loeffler syndrome - transient pulmonary infiltrates with eosinophilia, cough, and wheeze - before being swallowed. Heavy adult burdens cause intestinal or biliary obstruction."),
      H("Hookworms (Necator americanus, Ancylostoma duodenale) penetrate skin from soil, migrate through the lungs, and attach to small bowel mucosa with cutting plates, feeding on blood. The consequence is iron deficiency anemia with eosinophilia. Animal hookworms that cannot complete the cycle in humans cause cutaneous larva migrans, a creeping serpiginous track."),
      H("Strongyloides stercoralis is unique in completing autoinfection: larvae mature within the host and reinvade through the bowel wall or perianal skin, so infection persists for decades. Corticosteroids convert this into hyperinfection with disseminated larvae and polymicrobial Gram-negative bacteremia - which is why screening before immunosuppression matters."),
    ]),
    S("Tissue nematodes", [
      H("Trichinella spiralis comes from undercooked pork or bear meat. Larvae mature in the intestine, and newborn larvae disseminate to encyst in striated muscle, preferring the diaphragm, extraocular, and masseter muscles. The classic picture is fever, periorbital edema, myalgia, marked eosinophilia, and a raised creatine kinase."),
      H("Onchocerca volvulus is transmitted by blackflies breeding in fast-flowing rivers - hence river blindness. Adults live in subcutaneous nodules and release microfilariae that migrate through skin and eye, causing intense itching and progressive keratitis. Treatment is ivermectin; diethylcarbamazine is avoided because it triggers a severe Mazzotti reaction."),
      H("Wuchereria bancrofti is transmitted by mosquitoes and lodges in lymphatics, causing lymphatic obstruction and, after years, elephantiasis. Microfilariae are nocturnally periodic, so blood is drawn at night to match the vector's biting time."),
      P("Filarial worms depend on Wolbachia endosymbionts for fertility and survival, so doxycycline sterilizes and slowly kills adult worms - an elegant example of treating a parasite by killing its bacterium. Toxocara causes visceral larva migrans in children who ingest soil contaminated with dog or cat feces, with marked eosinophilia and hepatomegaly; ocular involvement can mimic retinoblastoma."),
    ]),
  ]),

E("cestodes-trematodes", "Cestodes & Trematodes (Tapeworms & Flukes)", "Helminths",
  "Flatworms defined by their intermediate host: the food you ate tells you which worm you have.",
  aka=["Taenia", "cysticercosis", "Echinococcus", "Diphyllobothrium", "Schistosoma", "Clonorchis", "Paragonimus"],
  keywords=["neurocysticercosis", "hydatid cyst", "B12 deficiency", "swimmer's itch", "portal hypertension", "bladder cancer"],
  treatment="Praziquantel for most tapeworms and flukes. Neurocysticercosis: albendazole with steroids and antiepileptics. Echinococcus: albendazole plus careful surgery or PAIR. Fasciola: triclabendazole.",
  quick=[("Taenia solium", "Pork: cysticerci = tapeworm; EGGS = cysticercosis"),
         ("Taenia saginata", "Beef: intestinal tapeworm only"),
         ("Echinococcus", "Dog feces; sheep intermediate; hydatid cyst"),
         ("Diphyllobothrium", "Raw freshwater fish; B12 deficiency"),
         ("Schistosoma", "Snail intermediate; skin penetration in fresh water")],
  images=[("tsolium-scolex.jpg", "Taenia solium scolex with its crown of hooks."),
          ("ncc-ct.jpg", "Neurocysticercosis: multiple cysts, some calcified."),
          ("hydatid.jpg", "Hydatid cyst with daughter cysts."),
          ("dlatum.jpg", "Diphyllobothrium latum proglottids."),
          ("schisto-mansoni.jpg", "S. mansoni egg with its lateral spine."),
          ("schisto-haem.jpg", "S. haematobium egg with its terminal spine."),
          ("clonorchis-egg.jpg", "Operculated Clonorchis egg.")],
  sections=[
    S("Tapeworms", [
      H("Taenia solium produces two entirely different diseases. Eating undercooked pork containing cysticerci gives an adult intestinal tapeworm. Eating the eggs, usually by fecal-oral spread from a human carrier, gives cysticercosis, with cysts in brain and muscle. Neurocysticercosis is a leading cause of adult-onset seizures in endemic regions."),
      H("Echinococcus granulosus comes from dog feces, with sheep as intermediate hosts; humans develop hydatid cysts, usually in the liver, with daughter cysts and eggshell calcification. The cyst fluid is highly antigenic, so spillage can cause anaphylaxis and seed new cysts - which is why simple aspiration is hazardous and the PAIR technique or careful surgery under albendazole cover is used."),
      H("Diphyllobothrium latum comes from raw or undercooked freshwater fish and competes for vitamin B12 in the ileum, producing a megaloblastic anemia that can be accompanied by subacute combined degeneration. Taenia saginata, from beef, causes only a benign intestinal infection."),
    ]),
    S("Flukes", [
      H("Schistosomes penetrate intact skin during freshwater exposure (snails are the intermediate host). S. haematobium lives in the vesical plexus, causing hematuria, obstructive uropathy, and squamous cell carcinoma of the bladder. S. mansoni and S. japonicum live in mesenteric veins; eggs embolize to the liver causing periportal 'pipestem' fibrosis with portal hypertension and preserved hepatocyte function."),
      P("The distinction between pipestem fibrosis and cirrhosis matters: portal hypertension develops with variceal bleeding, but synthetic function is preserved, so these patients do not become jaundiced or coagulopathic the way cirrhotics do. Swimmer's itch is a self-limited dermatitis from avian schistosome cercariae that cannot mature in humans."),
      H("Clonorchis sinensis and Opisthorchis come from raw freshwater fish, live in bile ducts, and cause chronic cholangitis, biliary obstruction, and cholangiocarcinoma. Paragonimus westermani comes from undercooked crab or crayfish and causes chronic cough with hemoptysis that mimics tuberculosis. Fasciola hepatica comes from watercress and needs triclabendazole rather than praziquantel."),
    ]),
  ]),
]
