from qcore import Q
from tables import *
TAG_GPC = "Gram+ Cocci"
TAG_GPR = "Gram+ Rods & Branching"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_GPC, "Gram stain: color logic",
  "A sputum Gram stain shows round purple organisms in clusters. Which statement explains the purple color?",
  ["A thick peptidoglycan layer retains the crystal violet-iodine complex",
   "A thin peptidoglycan layer retains the crystal violet-iodine complex",
   "An outer membrane traps the safranin counterstain tightly",
   "Mycolic acids in the wall resist decolorization by acid-alcohol",
   "The absence of a cell wall allows the dye to enter the cytoplasm"],
  "Gram-positive organisms have a thick peptidoglycan layer that traps the crystal violet-iodine complex when alcohol is applied, so they stay purple. Gram-negative organisms have a thin peptidoglycan layer and a lipid-rich outer membrane that is dissolved by alcohol, so they lose the complex and pick up the pink safranin counterstain.",
  difficulty="easy",
  why={"A thin peptidoglycan layer": "That is the Gram-negative wall, which decolorizes and turns pink.",
       "An outer membrane traps": "The outer membrane is a Gram-negative feature and is dissolved by alcohol.",
       "Mycolic acids in the wall": "Mycolic acids cause acid-fastness in mycobacteria, a different stain.",
       "The absence of a cell wall": "Organisms without a wall, such as Mycoplasma, do not stain at all."}),

Q(TAG_GPC, "Impetigo: organisms",
  "A 5-year-old has honey-colored crusted lesions around the nose and mouth without fever. Which pair of organisms most commonly causes this?",
  ["Staphylococcus aureus and Streptococcus pyogenes",
   "Streptococcus pneumoniae and Haemophilus influenzae",
   "Pseudomonas aeruginosa and Escherichia coli",
   "Corynebacterium diphtheriae and Listeria species",
   "Clostridium perfringens and Bacteroides fragilis"],
  "Non-bullous impetigo is a superficial skin infection with honey-colored crusts, caused by S. aureus and S. pyogenes. Localized disease is treated with topical mupirocin; widespread disease needs oral therapy. Streptococcal impetigo can be followed by post-streptococcal glomerulonephritis, but not by rheumatic fever.",
  difficulty="easy",
  why={"Streptococcus pneumoniae and Haemophilus": "These cause respiratory mucosal infections such as otitis and pneumonia.",
       "Pseudomonas aeruginosa and Escherichia": "These are Gram-negative rods causing wound, urinary, and hospital infections.",
       "Corynebacterium diphtheriae and Listeria": "Diphtheria affects the pharynx, and Listeria causes invasive food-borne disease.",
       "Clostridium perfringens and Bacteroides": "These anaerobes cause deep wound and intra-abdominal infections."},
  table=STREP),

Q(TAG_GPC, "Cellulitis vs abscess",
  "A 40-year-old has a warm, tender, spreading area of erythema on the calf with no fluctuance and no drainage. Which management step is most appropriate?",
  ["Oral cephalexin aimed at streptococci and MSSA",
   "Incision and drainage without any antibiotic therapy",
   "Oral fluconazole aimed at cutaneous fungal infection",
   "Topical mupirocin applied to the affected skin",
   "Oral metronidazole aimed at anaerobic organisms"],
  "Non-purulent cellulitis is usually streptococcal, so a beta-lactam such as cephalexin is appropriate. Purulent infection (abscess, drainage) suggests S. aureus, including community MRSA, and is treated with incision and drainage plus TMP-SMX or doxycycline if antibiotics are needed. Without fluctuance there is nothing to drain.",
  difficulty="easy",
  why={"Incision and drainage without any antibiotic": "There is no abscess to drain in non-purulent cellulitis.",
       "Oral fluconazole": "Fungal skin infection causes scaly annular lesions, not spreading tender erythema.",
       "Topical mupirocin": "Topical therapy does not penetrate deep enough for cellulitis.",
       "Oral metronidazole": "Anaerobes are not the usual cause of simple cellulitis."}),

Q(TAG_GPC, "Pneumococcal vaccine timing",
  "A healthy 68-year-old man has never received a pneumococcal vaccine. Which statement about pneumococcal vaccination is correct?",
  ["A single dose of a conjugate vaccine is recommended at this age",
   "Vaccination is advised only for people who have had pneumonia",
   "The polysaccharide vaccine works better than conjugate in infants",
   "Vaccination should be deferred until the patient turns eighty",
   "Vaccination is contraindicated in anyone older than sixty-five"],
  "Routine pneumococcal vaccination is recommended for all adults at 50 years and older, and for younger adults with risk conditions (asplenia, immunosuppression, chronic heart, lung, liver, or kidney disease, diabetes, CSF leak, cochlear implant). Current schedules use a single dose of a conjugate vaccine (PCV20 or PCV21), or PCV15 followed by PPSV23.",
  difficulty="easy",
  why={"Vaccination is advised only for people who have had pneumonia": "It is preventive and given before any infection occurs.",
       "The polysaccharide vaccine works better than conjugate in infants": "Polysaccharide vaccines respond poorly in children under two.",
       "Vaccination should be deferred until the patient turns eighty": "Delay leaves years of avoidable risk.",
       "Vaccination is contraindicated in anyone older than sixty-five": "Older adults are among the highest-priority groups."},
  table=VACCINES),

Q(TAG_GPR, "Tetanus booster interval",
  "A healthy 30-year-old woman with a fully documented childhood vaccination series and a Tdap at age 20 asks how often she needs tetanus boosters. What is the correct answer?",
  ["A tetanus-diphtheria booster every ten years",
   "A tetanus-diphtheria booster every single year",
   "No further boosters are needed after childhood doses",
   "A booster only when she sustains a dirty wound",
   "A booster every two years for the rest of her life"],
  "After the primary series, a Td (or Tdap) booster is recommended every 10 years. Tdap is also given once in adulthood and in every pregnancy (27-36 weeks) to protect newborns from pertussis. For a dirty wound, a booster is given if more than 5 years have passed.",
  difficulty="easy",
  why={"A tetanus-diphtheria booster every single year": "Annual boosting is unnecessary and causes local reactions.",
       "No further boosters are needed after childhood doses": "Antitoxin levels fall over time, so boosters are required.",
       "A booster only when she sustains a dirty wound": "Routine boosting keeps protection between injuries.",
       "A booster every two years for the rest of her life": "That interval is far shorter than needed."}),

Q(TAG_GPC, "Catalase test interpretation",
  "Hydrogen peroxide is added to colonies from a blood agar plate, and vigorous bubbling occurs. What does this indicate?",
  ["The organism makes catalase, breaking down the reagent",
   "The organism makes coagulase, which converts fibrinogen",
   "The organism makes urease, which splits urea to ammonia",
   "The organism makes oxidase, which transfers electrons",
   "The organism makes hyaluronidase, which spreads infection"],
  "Catalase converts hydrogen peroxide into water and oxygen, producing visible bubbles. Among Gram-positive cocci, staphylococci and Micrococcus are catalase-positive, while streptococci and enterococci are catalase-negative. This is the first branch point in identifying Gram-positive cocci.",
  difficulty="easy",
  why={"The organism makes coagulase": "Coagulase is tested with plasma and produces a clot, not bubbles.",
       "The organism makes urease": "Urease is detected by a pH change on urea medium.",
       "The organism makes oxidase": "Oxidase testing uses a reagent that turns purple, not peroxide.",
       "The organism makes hyaluronidase": "Hyaluronidase is a virulence factor and is not tested this way."},
  table=GPC_ALGORITHM),

# ---------------- medium ----------------
Q(TAG_GPC, "Toxic shock: staph vs strep",
  "Two patients have fever, hypotension, and multiorgan failure. Patient A has a diffuse macular rash, a recently packed nasal cavity, and negative blood cultures. Patient B has severe leg pain with necrotic skin and blood cultures growing chains of Gram-positive cocci. Which statement best contrasts these illnesses?",
  ["Staphylococcal toxic shock is usually culture-negative, while streptococcal disease is usually bacteremic",
   "Staphylococcal toxic shock is usually bacteremic, while streptococcal disease is culture-negative",
   "Both syndromes are caused by endotoxin from the bacterial outer membrane",
   "Neither syndrome involves T-cell activation or cytokine release",
   "Both syndromes require the organism to invade the bloodstream first"],
  "Staphylococcal toxic shock syndrome is driven by TSST-1 made at a colonized site (tampon, nasal packing, wound), so blood cultures are usually negative. Streptococcal toxic shock syndrome usually follows invasive infection such as necrotizing fasciitis, and blood cultures are often positive. Both are superantigen-mediated. Treatment includes source control, fluids, and clindamycin to shut off toxin production.",
  why={"Staphylococcal toxic shock is usually bacteremic": "The relationship is reversed in this option.",
       "Both syndromes are caused by endotoxin": "Endotoxin is a Gram-negative molecule; these are Gram-positive superantigens.",
       "Neither syndrome involves T-cell activation": "Superantigens activate large numbers of T cells at once.",
       "Both syndromes require the organism to invade": "Staphylococcal disease is toxin-mediated from a local site."},
  table=TOXINS),

Q(TAG_GPC, "Group B strep in adults",
  "A 62-year-old man with poorly controlled diabetes has a chronic foot ulcer and now has fever with cellulitis. Wound culture grows a beta-hemolytic, catalase-negative, bacitracin-resistant, CAMP-positive organism. Which statement is correct?",
  ["Group B strep also causes skin, soft tissue, and bone infection in diabetics",
   "Group B strep is found only in pregnant women and their newborn infants",
   "Group B strep is typically resistant to penicillin and needs vancomycin",
   "Group B strep is an obligate anaerobe that requires metronidazole therapy",
   "Group B strep is identified by its sensitivity to the optochin disk"],
  "Group B strep is best known for neonatal disease, but in adults it causes skin and soft tissue infection, osteomyelitis, bacteremia, and endocarditis, particularly in diabetics and older adults. It remains susceptible to penicillin, which is first-line therapy.",
  why={"Group B strep is found only in pregnant women": "It colonizes and infects adults of both sexes.",
       "Group B strep is typically resistant to penicillin": "Penicillin remains the drug of choice.",
       "Group B strep is an obligate anaerobe": "It is a facultative organism that grows aerobically.",
       "Group B strep is identified by its sensitivity to the optochin disk": "Optochin identifies pneumococcus among alpha-hemolytic strep."},
  table=STREP),

Q(TAG_GPC, "Enterococcus vs Streptococcus bovis group",
  "Blood cultures from a patient with endocarditis grow a catalase-negative, bile esculin-positive Gram-positive coccus that does not grow in 6.5% sodium chloride. What should be done next?",
  ["Arrange colonoscopy to look for a colonic neoplasm",
   "Arrange urologic evaluation for prostatic enlargement",
   "Begin antifungal therapy for suspected fungal endocarditis",
   "Begin isoniazid therapy for suspected tuberculous infection",
   "Arrange dental extraction of all remaining carious teeth"],
  "Bile esculin positivity indicates a group D organism. Growth in 6.5% NaCl separates Enterococcus (salt-tolerant) from S. gallolyticus, formerly S. bovis (not salt-tolerant). S. gallolyticus bacteremia or endocarditis is strongly linked to colorectal neoplasia and requires colonoscopy.",
  why={"Arrange urologic evaluation": "Genitourinary sources are linked to enterococcal infection, which grows in 6.5% salt.",
       "Begin antifungal therapy": "The organism is a Gram-positive coccus, not a fungus.",
       "Begin isoniazid therapy": "Mycobacteria do not grow in routine blood cultures this way.",
       "Arrange dental extraction": "Dental sources suggest viridans streptococci, which are bile esculin-negative."},
  table=STREP),

Q(TAG_GPR, "Anthrax: gastrointestinal form",
  "After a funeral feast where meat from a sick cow was eaten, several people develop fever, severe abdominal pain, bloody diarrhea, and ascites. Some have oropharyngeal ulcers and neck swelling. Which organism is most likely?",
  ["Bacillus anthracis",
   "Bacillus cereus",
   "Clostridium botulinum",
   "Listeria monocytogenes",
   "Yersinia enterocolitica"],
  "Gastrointestinal anthrax follows ingestion of spores in undercooked meat from infected animals. Spores germinate in the intestinal or oropharyngeal mucosa, causing ulcers, marked edema, hemorrhagic lymphadenitis, bloody diarrhea, and ascites. Mortality is high without prompt therapy. Cutaneous anthrax remains the most common form worldwide.",
  why={"Bacillus cereus": "B. cereus causes brief vomiting or diarrheal illness without ulcers or ascites.",
       "Clostridium botulinum": "Botulism causes descending paralysis without bloody diarrhea.",
       "Listeria monocytogenes": "Listeria causes febrile gastroenteritis, meningitis, or pregnancy loss.",
       "Yersinia enterocolitica": "Yersinia causes pseudoappendicitis with mesenteric adenitis."},
  table=GPR),

Q(TAG_GPR, "Listeria: CSF findings",
  "A 74-year-old man on chronic prednisone has fever, headache, and confusion. CSF shows 400 white cells with a mix of neutrophils and lymphocytes, protein 120 mg/dL, and glucose 35 mg/dL. Gram stain shows scattered small Gram-positive rods. Which antibiotic must be included?",
  ["Ampicillin",
   "Ceftriaxone",
   "Aztreonam",
   "Metronidazole",
   "Azithromycin"],
  "Listeria meningitis occurs in neonates, adults over 50, pregnant women, and immunosuppressed patients. CSF can show a mixed or lymphocyte-predominant pleocytosis, and Gram stain is often negative or shows few small Gram-positive rods. Listeria is intrinsically resistant to cephalosporins, so ampicillin (often with gentamicin) is required.",
  why={"Ceftriaxone": "All cephalosporins lack activity against Listeria.",
       "Aztreonam": "Aztreonam covers only aerobic Gram-negative rods.",
       "Metronidazole": "Metronidazole covers anaerobes.",
       "Azithromycin": "Macrolides are not reliable for CNS listeriosis."},
  table=MENINGITIS_AGE),

Q(TAG_GPR, "Clostridioides difficile: severe disease",
  "A 76-year-old woman has profuse diarrhea, a white cell count of 28,000/microliter, creatinine of 2.4 mg/dL, and hypotension. Stool PCR is positive for C. difficile toxin genes. Which regimen is most appropriate?",
  ["Oral vancomycin plus intravenous metronidazole",
   "Oral metronidazole given as a single agent",
   "Intravenous vancomycin given as a single agent",
   "Oral fidaxomicin plus loperamide for symptom relief",
   "Intravenous ceftriaxone plus oral rifaximin therapy"],
  "Fulminant C. difficile infection (hypotension, shock, ileus, megacolon) is treated with high-dose oral vancomycin plus IV metronidazole, with rectal vancomycin added if ileus is present. Surgical consultation is needed for colectomy in refractory disease. Non-severe first episodes are treated with oral fidaxomicin or vancomycin.",
  why={"Oral metronidazole given as a single agent": "Monotherapy with metronidazole is inadequate for severe disease.",
       "Intravenous vancomycin given as a single agent": "IV vancomycin does not reach the colonic lumen.",
       "Oral fidaxomicin plus loperamide": "Antimotility agents risk toxic megacolon.",
       "Intravenous ceftriaxone plus oral rifaximin": "Ceftriaxone worsens the disease by further disrupting flora."},
  table=CLOSTRIDIA),

Q(TAG_GPC, "Rheumatic fever: Jones criteria",
  "A 9-year-old girl has fever, a new mitral murmur, and migratory arthritis three weeks after pharyngitis. Which additional finding would count as a major criterion for acute rheumatic fever?",
  ["Erythema marginatum on the trunk",
   "An elevated C-reactive protein level",
   "A prolonged PR interval on the ECG",
   "Arthralgia without objective swelling",
   "A fever of 39 degrees Celsius"],
  "Major Jones criteria are carditis, polyarthritis, chorea, subcutaneous nodules, and erythema marginatum (JONES: Joints, heart, Nodules, Erythema marginatum, Sydenham chorea). Minor criteria include fever, arthralgia, elevated acute-phase reactants, and a prolonged PR interval. Diagnosis needs evidence of preceding strep infection plus two major or one major and two minor criteria.",
  why={"An elevated C-reactive protein level": "Acute-phase reactants are minor criteria.",
       "A prolonged PR interval on the ECG": "First-degree block is a minor criterion.",
       "Arthralgia without objective swelling": "Arthralgia alone is minor; true arthritis is major.",
       "A fever of 39 degrees Celsius": "Fever is a minor criterion."},
  table=GAS_SEQUELAE),

Q(TAG_GPC, "Prosthetic valve endocarditis timing",
  "A patient develops endocarditis two months after aortic valve replacement. Which organism is the most likely cause of early prosthetic valve endocarditis?",
  ["Staphylococcus epidermidis",
   "Streptococcus sanguinis",
   "Streptococcus gallolyticus",
   "Haemophilus parainfluenzae",
   "Enterococcus faecalis"],
  "Early prosthetic valve endocarditis (within about a year of surgery) is usually caused by organisms introduced at operation, most often coagulase-negative staphylococci such as S. epidermidis, followed by S. aureus. Late prosthetic valve endocarditis resembles native valve disease, with viridans streptococci and enterococci. Treatment usually requires vancomycin plus rifampin and gentamicin, and often valve replacement.",
  why={"Streptococcus sanguinis": "Viridans strep cause late prosthetic and native valve disease after dental procedures.",
       "Streptococcus gallolyticus": "That organism suggests colonic neoplasia and causes late disease.",
       "Haemophilus parainfluenzae": "HACEK organisms cause subacute, culture-negative native valve disease.",
       "Enterococcus faecalis": "Enterococci follow genitourinary procedures and cause late disease."},
  table=STAPH),

# ---------------- hard ----------------
Q(TAG_GPC, "Vancomycin-intermediate S. aureus",
  "A patient with MRSA bacteremia remains febrile after ten days of vancomycin with therapeutic levels. The isolate now has a vancomycin MIC of 8 micrograms/mL, and its cell wall appears thickened on electron microscopy. What best explains this finding?",
  ["A dense, overbuilt cell wall traps vancomycin before it reaches its target",
   "The organism acquired the vanA gene cluster from an enterococcus",
   "The organism began producing a vancomycin-hydrolyzing enzyme",
   "The organism lost the penicillin-binding protein that vancomycin blocks",
   "An efflux pump now actively exports vancomycin from the cytoplasm"],
  "Vancomycin-intermediate S. aureus (VISA) arises from stepwise changes producing a thickened cell wall with excess free D-Ala-D-Ala targets. These decoys trap vancomycin in the outer wall layers so it never reaches the membrane, where peptidoglycan synthesis occurs. True vancomycin resistance (VRSA, MIC 16 or higher) is rare and results from acquiring the vanA cluster from enterococci.",
  difficulty="hard",
  why={"The organism acquired the vanA gene cluster": "vanA produces high-level resistance (VRSA), not the intermediate phenotype with a thick wall.",
       "The organism began producing a vancomycin-hydrolyzing enzyme": "No clinically important enzyme degrades vancomycin.",
       "The organism lost the penicillin-binding protein": "Vancomycin binds the peptide substrate, not a PBP.",
       "An efflux pump now actively exports vancomycin": "Efflux is not a recognized mechanism for this glycopeptide."},
  table=RESISTANCE),

Q(TAG_GPC, "Clindamycin resistance: D-test",
  "A community MRSA isolate is reported as erythromycin-resistant and clindamycin-susceptible. On disk diffusion, the clindamycin zone is flattened on the side facing the erythromycin disk. What does this indicate?",
  ["Inducible clindamycin resistance, so clindamycin should be avoided",
   "Laboratory contamination, so the culture must simply be repeated",
   "Synergy between the two drugs, so both should be given together",
   "Efflux-only resistance, so clindamycin remains a reliable choice",
   "Beta-lactamase production, so a beta-lactam inhibitor is needed"],
  "A positive D-test shows inducible macrolide-lincosamide-streptogramin (MLSb) resistance from an erm gene. Erythromycin induces methylation of 23S rRNA, which also blocks clindamycin binding. The isolate may appear susceptible in broth but can fail during treatment, so clindamycin should be avoided. Alternatives include TMP-SMX, doxycycline, or linezolid.",
  difficulty="hard",
  why={"Laboratory contamination": "The flattened zone is a reproducible, meaningful phenotype.",
       "Synergy between the two drugs": "The flattening shows antagonistic induction, not synergy.",
       "Efflux-only resistance": "Efflux (msrA) affects macrolides alone and gives no D-shape.",
       "Beta-lactamase production": "Beta-lactamase does not affect clindamycin."},
  table=RESISTANCE),

Q(TAG_GPR, "Diphtheria: Elek test",
  "A throat isolate is identified as Corynebacterium diphtheriae. Before deciding on antitoxin, the laboratory performs an immunodiffusion assay in which a strip impregnated with antitoxin is placed on agar and the isolate is streaked at right angles. What does a precipitin line indicate?",
  ["The isolate produces diphtheria toxin",
   "The isolate is resistant to erythromycin",
   "The isolate carries a capsule antigen",
   "The isolate ferments glucose and maltose",
   "The isolate is susceptible to penicillin"],
  "The Elek test detects toxin production by immunoprecipitation between secreted toxin and antitoxin in agar. Only strains lysogenized by the beta-phage carrying the tox gene make toxin and cause disease. PCR for the tox gene is also used. Antitoxin is given as soon as toxigenic diphtheria is suspected clinically, without waiting for confirmation.",
  difficulty="hard",
  why={"The isolate is resistant to erythromycin": "Susceptibility is tested by separate disk or broth methods.",
       "The isolate carries a capsule antigen": "Capsule detection uses the quellung reaction or agglutination.",
       "The isolate ferments glucose and maltose": "Fermentation is read from biochemical media, not immunodiffusion.",
       "The isolate is susceptible to penicillin": "This assay measures toxin, not drug susceptibility."},
  table=GPR),

Q(TAG_GPR, "Nocardia vs Actinomyces: microbiology",
  "Two patients have chronic suppurative infections with branching, filamentous Gram-positive organisms. Isolate 1 grows only anaerobically and is not acid-fast. Isolate 2 grows aerobically and is acid-fast with a modified stain. Which statement correctly pairs the isolates with therapy?",
  ["Isolate 1 is Actinomyces treated with penicillin; isolate 2 is Nocardia treated with TMP-SMX",
   "Isolate 1 is Nocardia treated with penicillin; isolate 2 is Actinomyces treated with TMP-SMX",
   "Both isolates are Actinomyces and both respond to high-dose penicillin therapy",
   "Both isolates are Nocardia and both respond to trimethoprim-sulfamethoxazole",
   "Isolate 1 is Actinomyces treated with isoniazid; isolate 2 is Nocardia treated with penicillin"],
  "Actinomyces israelii is an anaerobic, non-acid-fast component of normal oral and genital flora that causes cervicofacial, thoracic, abdominal, and pelvic disease with sulfur granules and sinus tracts; it is treated with prolonged penicillin. Nocardia is an aerobic soil organism that is weakly acid-fast and causes pneumonia, brain abscess, and skin disease in immunocompromised hosts; it is treated with TMP-SMX. Mnemonic SNAP: Sulfonamides for Nocardia, Actinomyces gets Penicillin.",
  difficulty="hard",
  why={"Isolate 1 is Nocardia treated with penicillin": "The organisms and drugs are swapped.",
       "Both isolates are Actinomyces": "Aerobic growth and acid-fastness exclude Actinomyces for isolate 2.",
       "Both isolates are Nocardia": "Anaerobic growth without acid-fastness excludes Nocardia for isolate 1.",
       "Isolate 1 is Actinomyces treated with isoniazid": "Isoniazid treats mycobacteria, not Actinomyces."},
  table=GPR),

Q(TAG_GPC, "Streptococcal pharyngitis: testing strategy",
  "A 7-year-old has fever, tonsillar exudate, tender anterior cervical nodes, and no cough. A rapid antigen detection test for group A strep is negative. What is the most appropriate next step?",
  ["Send a throat culture, because rapid tests miss some cases in children",
   "Start amoxicillin immediately and ignore the negative rapid test result",
   "Reassure the family that no further testing or treatment is needed",
   "Order antistreptolysin O titers to confirm the acute infection now",
   "Start azithromycin empirically to cover atypical bacterial causes"],
  "Rapid antigen tests are highly specific but less sensitive than culture. In children and adolescents, in whom untreated infection carries a risk of rheumatic fever, a negative rapid test with a suggestive presentation should be confirmed by throat culture. ASO titers rise late and are used for post-streptococcal complications, not acute diagnosis.",
  difficulty="hard",
  why={"Start amoxicillin immediately and ignore": "Treating without confirmation causes unnecessary antibiotic use.",
       "Reassure the family that no further testing": "A negative rapid test does not exclude infection in a child.",
       "Order antistreptolysin O titers": "ASO reflects past infection and is not useful acutely.",
       "Start azithromycin empirically": "Atypical organisms are not the concern, and macrolide resistance is rising."},
  table=GAS_SEQUELAE),
]
