from qcore import Q
from tables import *
TAG_RESP = "Gram− Cocci & Respiratory Rods"
TAG_ENT = "Enteric Gram− Rods"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_RESP, "Oxidase test",
  "A non-lactose-fermenting Gram-negative rod from a burn wound turns oxidase reagent deep purple within seconds. Which organism does this support?",
  ["Pseudomonas aeruginosa",
   "Escherichia coli",
   "Klebsiella pneumoniae",
   "Shigella sonnei",
   "Proteus mirabilis"],
  "Oxidase detects cytochrome c oxidase. Pseudomonas, Neisseria, Vibrio, Campylobacter, and Helicobacter are oxidase-positive. All Enterobacterales (E. coli, Klebsiella, Shigella, Salmonella, Proteus) are oxidase-negative, so a positive test on a non-fermenter strongly suggests Pseudomonas.",
  difficulty="easy",
  why={"Escherichia coli": "E. coli is oxidase-negative and ferments lactose.",
       "Klebsiella pneumoniae": "Klebsiella is oxidase-negative and forms mucoid lactose-fermenting colonies.",
       "Shigella sonnei": "Shigella is oxidase-negative and causes dysentery, not burn infection.",
       "Proteus mirabilis": "Proteus is oxidase-negative and swarms across agar."},
  table=LACTOSE),

Q(TAG_ENT, "Traveler's diarrhea prevention",
  "A healthy traveler asks how to avoid diarrhea on a two-week trip to a resource-limited region. Which advice is most appropriate?",
  ["Drink bottled or boiled water and avoid raw salads and ice",
   "Take daily ciprofloxacin for the entire duration of the trip",
   "Take daily loperamide starting before leaving on the trip",
   "Receive a cholera vaccine to prevent all bacterial diarrhea",
   "Avoid all cooked foods and eat only uncooked fresh produce"],
  "Food and water precautions are the mainstay: drink sealed or boiled beverages, avoid ice, and eat food that is steaming hot or peeled by the traveler. Routine antibiotic prophylaxis is not recommended because of resistance and adverse effects, though self-treatment with azithromycin or rifaximin can be provided. ETEC is the most common cause.",
  difficulty="easy",
  why={"Take daily ciprofloxacin": "Routine prophylaxis promotes resistance and carries side effects.",
       "Take daily loperamide": "Loperamide treats symptoms and does not prevent infection.",
       "Receive a cholera vaccine": "The cholera vaccine gives limited, partial protection and does not cover other causes.",
       "Avoid all cooked foods": "Raw produce carries the highest risk; cooked food is safer."},
  table=DIARRHEA),

Q(TAG_RESP, "Otitis media: first-line therapy",
  "A 2-year-old has fever, ear pain, and a bulging erythematous tympanic membrane. He has had no antibiotics recently and has no allergies. Which treatment is first-line?",
  ["High-dose amoxicillin",
   "Oral vancomycin",
   "Intravenous ceftriaxone",
   "Oral ciprofloxacin",
   "Oral metronidazole"],
  "High-dose amoxicillin is first-line for acute otitis media, covering S. pneumoniae including many penicillin-intermediate strains. Amoxicillin-clavulanate is used after recent antibiotics, with concurrent conjunctivitis, or on treatment failure, because it covers beta-lactamase-producing H. influenzae and Moraxella.",
  difficulty="easy",
  why={"Oral vancomycin": "Oral vancomycin is not absorbed and acts only in the gut lumen.",
       "Intravenous ceftriaxone": "IV therapy is reserved for vomiting or treatment failure.",
       "Oral ciprofloxacin": "Fluoroquinolones are avoided in children and do not cover pneumococcus well.",
       "Oral metronidazole": "Metronidazole covers anaerobes, which do not cause this infection."},
  table=HAEMOPHILUS_BORD_LEG),

Q(TAG_ENT, "Uncomplicated cystitis therapy",
  "A healthy 25-year-old non-pregnant woman has three days of dysuria and urinary frequency without fever or flank pain. Which is an appropriate first-line treatment?",
  ["Nitrofurantoin for five days",
   "Ceftriaxone given intravenously",
   "Oral vancomycin for seven days",
   "Metronidazole given as a single dose",
   "Azithromycin given as a single dose"],
  "First-line options for uncomplicated cystitis are nitrofurantoin for 5 days, TMP-SMX for 3 days where resistance is below about 20%, or single-dose fosfomycin. Fluoroquinolones are reserved because of adverse effects and resistance. E. coli causes most cases, followed by S. saprophyticus in young women.",
  difficulty="easy",
  why={"Ceftriaxone given intravenously": "IV therapy is for pyelonephritis or systemic illness.",
       "Oral vancomycin for seven days": "Oral vancomycin is not absorbed and lacks Gram-negative activity.",
       "Metronidazole given as a single dose": "Metronidazole covers anaerobes and trichomonads.",
       "Azithromycin given as a single dose": "Azithromycin does not reach useful urinary concentrations."}),

Q(TAG_ENT, "Rehydration in cholera",
  "In a cholera outbreak, oral rehydration solution containing sodium and glucose is used. Why does adding glucose improve fluid absorption despite ongoing toxin activity?",
  ["Sodium-glucose cotransport in enterocytes remains intact",
   "Glucose directly neutralizes cholera toxin within the gut lumen",
   "Glucose blocks adenylyl cyclase inside intestinal cells",
   "Glucose kills Vibrio cholerae organisms in the intestine",
   "Glucose closes the CFTR chloride channel on enterocytes"],
  "Cholera toxin raises cAMP and drives chloride and water secretion through CFTR, but it does not damage enterocytes or the SGLT1 sodium-glucose cotransporter. Coupling sodium to glucose absorption pulls water back across the epithelium. Oral rehydration solution is one of the most effective public health interventions in medicine.",
  difficulty="easy",
  why={"Glucose directly neutralizes cholera toxin": "Glucose has no effect on the toxin itself.",
       "Glucose blocks adenylyl cyclase": "The enzyme stays activated; absorption simply continues in parallel.",
       "Glucose kills Vibrio cholerae organisms": "Glucose is not antimicrobial.",
       "Glucose closes the CFTR chloride channel": "CFTR remains open; sodium-coupled uptake offsets the loss."},
  table=VIBRIO),

# ---------------- medium ----------------
Q(TAG_RESP, "Meningococcemia without meningitis",
  "A 19-year-old has 12 hours of fever, myalgias, and rapidly spreading purpura with hypotension, but no headache or neck stiffness. Lumbar puncture is normal. Which statement best explains this presentation?",
  ["Meningococcemia can cause shock and purpura without meningitis",
   "Meningococcemia always produces neutrophilic meningitis first",
   "Purpura in this setting indicates an autoimmune vasculitis",
   "Normal CSF rules out invasive meningococcal infection entirely",
   "Shock in this setting is caused by a secreted A-B exotoxin"],
  "Invasive meningococcal disease can present as meningitis, meningococcemia, or both. Fulminant meningococcemia with purpura fulminans and shock may occur with normal CSF, and it carries the highest mortality. Treat immediately with ceftriaxone, without waiting for lumbar puncture, and give close contacts prophylaxis.",
  why={"Meningococcemia always produces neutrophilic meningitis first": "Bloodstream disease can occur without meningeal involvement.",
       "Purpura in this setting indicates an autoimmune vasculitis": "The purpura reflects endotoxin-driven DIC and microthrombi.",
       "Normal CSF rules out invasive meningococcal infection": "Blood cultures may be positive despite normal CSF.",
       "Shock in this setting is caused by a secreted A-B exotoxin": "Lipooligosaccharide endotoxin drives the cytokine storm."},
  table=NEISSERIA),

Q(TAG_RESP, "Epiglottitis in a vaccinated child",
  "A 6-year-old fully vaccinated child has acute fever, drooling, and stridor. Lateral neck radiograph shows a swollen epiglottis. Which statement about the likely cause is correct?",
  ["Other organisms such as streptococci and S. aureus now predominate",
   "Haemophilus influenzae type b remains the usual cause despite vaccination",
   "The Hib conjugate vaccine also protects against these other organisms",
   "Epiglottitis in vaccinated children is almost always viral in origin",
   "Blood cultures are contraindicated because they delay airway control"],
  "Since Hib vaccination, epiglottitis has become rare and now more often involves group A streptococci, S. pneumoniae, S. aureus, and nontypeable H. influenzae, with a shift toward older children and adults. Management is unchanged: secure the airway first in a controlled setting, then obtain cultures and give ceftriaxone (plus MRSA coverage if indicated).",
  why={"Haemophilus influenzae type b remains the usual cause": "Hib disease is now uncommon in vaccinated children.",
       "The Hib conjugate vaccine also protects against these other organisms": "It targets only the type b capsule.",
       "Epiglottitis in vaccinated children is almost always viral": "It remains a bacterial infection; croup is the viral mimic.",
       "Blood cultures are contraindicated": "Cultures are obtained after the airway is secured."},
  table=HAEMOPHILUS_BORD_LEG),

Q(TAG_ENT, "Asymptomatic bacteriuria",
  "A 68-year-old woman in a nursing home has no urinary symptoms. A routine urine culture grows 100,000 CFU/mL of E. coli. She is afebrile and feels well. What is the best management?",
  ["No antibiotic treatment is indicated",
   "A seven-day course of oral ciprofloxacin",
   "A three-day course of oral nitrofurantoin",
   "A single intravenous dose of ceftriaxone",
   "Long-term daily antibiotic suppression"],
  "Asymptomatic bacteriuria should not be treated in most adults, including older and institutionalized patients and those with diabetes or catheters, because treatment causes adverse effects and resistance without benefit. The exceptions are pregnancy and before urologic procedures with expected mucosal bleeding.",
  why={"A seven-day course of oral ciprofloxacin": "Treatment provides no benefit and risks C. difficile and resistance.",
       "A three-day course of oral nitrofurantoin": "Even a short course is unnecessary without symptoms.",
       "A single intravenous dose of ceftriaxone": "IV therapy is not warranted for a colonized, well patient.",
       "Long-term daily antibiotic suppression": "Suppression selects resistant organisms without improving outcomes."}),

Q(TAG_ENT, "Pyelonephritis management",
  "A 30-year-old woman has fever of 39 degrees Celsius, flank pain, nausea, and pyuria. She is vomiting and cannot keep fluids down. Which management is most appropriate?",
  ["Admit for intravenous ceftriaxone and fluids",
   "Discharge with oral nitrofurantoin for seven days",
   "Discharge with oral fosfomycin as a single dose",
   "Admit for intravenous vancomycin and fluids",
   "Discharge with oral metronidazole for ten days"],
  "Acute pyelonephritis with vomiting or systemic toxicity requires admission and IV therapy, typically ceftriaxone or a fluoroquinolone, adjusted by culture. Nitrofurantoin and fosfomycin concentrate in urine but do not reach adequate tissue levels, so they cannot treat kidney parenchymal infection. Imaging is considered if there is no improvement in 48-72 hours.",
  why={"Discharge with oral nitrofurantoin": "Nitrofurantoin does not achieve renal tissue levels.",
       "Discharge with oral fosfomycin": "Fosfomycin is for uncomplicated cystitis only.",
       "Admit for intravenous vancomycin": "Vancomycin lacks Gram-negative coverage.",
       "Discharge with oral metronidazole": "Metronidazole does not cover urinary Gram-negative rods."}),

Q(TAG_ENT, "Hemolytic uremic syndrome: management",
  "A 4-year-old with bloody diarrhea develops pallor, petechiae, and oliguria. Labs show anemia with schistocytes, platelets of 35,000/microliter, and creatinine of 2.8 mg/dL. Stool culture grows sorbitol-negative E. coli. Which step is most appropriate?",
  ["Supportive care with careful fluid and electrolyte management",
   "Intravenous ciprofloxacin to eradicate the organism quickly",
   "Oral azithromycin to shorten the duration of the diarrhea",
   "Loperamide to reduce stool frequency and fluid losses",
   "Platelet transfusion to correct the thrombocytopenia"],
  "Shiga toxin-producing E. coli HUS is managed supportively with fluids, electrolyte correction, and dialysis when needed. Antibiotics may increase toxin release and the risk of HUS, and antimotility agents prolong toxin exposure. Platelet transfusion is avoided unless there is bleeding or a procedure is planned, since it can worsen microthrombi. Eculizumab is used in atypical (complement-mediated) HUS.",
  why={"Intravenous ciprofloxacin to eradicate the organism": "Antibiotics can increase Shiga toxin release and worsen HUS.",
       "Oral azithromycin to shorten the duration": "Antibiotic benefit is unproven and potentially harmful here.",
       "Loperamide to reduce stool frequency": "Slowing transit increases toxin absorption.",
       "Platelet transfusion to correct the thrombocytopenia": "Transfusion can fuel microvascular thrombosis."},
  table=ECOLI),

Q(TAG_RESP, "Pseudomonas in cystic fibrosis",
  "A 16-year-old with cystic fibrosis has chronic Pseudomonas colonization. Sputum isolates are mucoid and grow in dense aggregates that resist antibiotics. Which bacterial product explains this phenotype?",
  ["Alginate, which forms a protective biofilm matrix",
   "Pyocyanin, which generates damaging oxygen radicals",
   "Exotoxin A, which halts host protein synthesis",
   "Lipid A, which triggers systemic cytokine release",
   "Elastase, which degrades structural connective tissue"],
  "Chronic airway Pseudomonas converts to a mucoid phenotype that overproduces alginate, an exopolysaccharide forming biofilm. Biofilm slows antibiotic penetration, shelters slow-growing cells, and prevents phagocyte clearance, so infection becomes impossible to eradicate. Management uses inhaled tobramycin or aztreonam, airway clearance, and CFTR modulators.",
  why={"Pyocyanin, which generates damaging oxygen radicals": "Pyocyanin causes oxidative injury but does not create the mucoid aggregates.",
       "Exotoxin A, which halts host protein synthesis": "Exotoxin A kills cells but does not build a matrix.",
       "Lipid A, which triggers systemic cytokine release": "Endotoxin drives inflammation and sepsis physiology.",
       "Elastase, which degrades structural connective tissue": "Elastase damages tissue but does not form biofilm."},
  table=ANTI_PSEUDOMONAL),

Q(TAG_ENT, "Spontaneous bacterial peritonitis",
  "A man with alcoholic cirrhosis and ascites has fever and abdominal pain. Ascitic fluid shows 600 neutrophils per microliter, and culture grows E. coli. Which statement about management is correct?",
  ["Give cefotaxime, and add albumin to reduce renal failure",
   "Give oral vancomycin, which concentrates in the peritoneum",
   "Perform urgent laparotomy to find a perforated viscus",
   "Withhold antibiotics until repeat paracentesis confirms growth",
   "Give metronidazole alone, since anaerobes predominate here"],
  "Spontaneous bacterial peritonitis is diagnosed when ascitic neutrophils exceed 250 per microliter. It is usually monomicrobial with enteric Gram-negative rods or streptococci. Treat with a third-generation cephalosporin, and add IV albumin, which lowers the risk of hepatorenal syndrome and death. Polymicrobial growth with very high protein suggests secondary peritonitis from perforation.",
  why={"Give oral vancomycin, which concentrates in the peritoneum": "Oral vancomycin stays in the gut lumen.",
       "Perform urgent laparotomy": "Surgery is for secondary peritonitis, which is typically polymicrobial.",
       "Withhold antibiotics until repeat paracentesis": "Delay increases mortality; the cell count is already diagnostic.",
       "Give metronidazole alone": "Anaerobes are rarely the cause of spontaneous peritonitis."}),

# ---------------- hard ----------------
Q(TAG_ENT, "Carbapenem resistance: NDM vs KPC",
  "A carbapenem-resistant Klebsiella isolate remains resistant when ceftazidime-avibactam is tested but is susceptible to aztreonam-avibactam. Which enzyme is most likely present?",
  ["A metallo-beta-lactamase such as NDM",
   "A serine carbapenemase such as KPC",
   "An extended-spectrum beta-lactamase such as CTX-M",
   "A chromosomal AmpC beta-lactamase",
   "An altered penicillin-binding protein"],
  "Metallo-beta-lactamases (NDM, VIM, IMP) use zinc and are not inhibited by avibactam, so ceftazidime-avibactam fails. They cannot hydrolyze aztreonam, but strains usually co-produce ESBLs that can, which is why aztreonam combined with avibactam works. KPC is a serine enzyme inhibited by avibactam, vaborbactam, and relebactam.",
  difficulty="hard",
  why={"A serine carbapenemase such as KPC": "KPC is inhibited by avibactam, so ceftazidime-avibactam would work.",
       "An extended-spectrum beta-lactamase such as CTX-M": "ESBLs do not confer carbapenem resistance.",
       "A chromosomal AmpC beta-lactamase": "AmpC alone rarely causes carbapenem resistance.",
       "An altered penicillin-binding protein": "PBP changes are the resistance route in Gram-positive organisms."},
  table=RESISTANCE),

Q(TAG_ENT, "Typhoid fever: culture timing",
  "A traveler returning from South Asia has one week of rising fever and abdominal pain. Which specimen has the highest yield in the first week of typhoid fever?",
  ["Blood culture",
   "Stool culture",
   "Urine culture",
   "Sputum culture",
   "Throat culture"],
  "S. Typhi causes bacteremia early, so blood cultures have the best yield in week 1 (bone marrow culture is even more sensitive and remains positive after antibiotics). The organism reaches the gut through bile later, so stool cultures become positive in weeks 2-3. Widal serology is unreliable.",
  difficulty="hard",
  why={"Stool culture": "Stool yield rises only in the second and third weeks.",
       "Urine culture": "Urine yield is low and also occurs later in illness.",
       "Sputum culture": "The respiratory tract is not a site of S. Typhi replication.",
       "Throat culture": "There is no pharyngeal phase in typhoid fever."},
  table=SALM_SHIG),

Q(TAG_RESP, "Bordetella: lymphocytosis mechanism",
  "An infant with pertussis has a white cell count of 45,000/microliter with 85% lymphocytes. Which mechanism explains this finding?",
  ["Pertussis toxin blocks lymphocyte entry into lymph nodes",
   "Pertussis toxin stimulates lymphocyte production in marrow",
   "Tracheal cytotoxin lyses circulating neutrophils directly",
   "Filamentous hemagglutinin binds and retains lymphocytes",
   "Endotoxin drives a leukemoid reaction with lymphoblasts"],
  "Pertussis toxin ADP-ribosylates Gi proteins, including those coupling chemokine receptors that normally direct lymphocytes out of blood into lymphoid tissue. Lymphocytes therefore accumulate in the circulation. Marked leukocytosis with lymphocytosis in young infants predicts severe disease, pulmonary hypertension, and death, and may prompt exchange transfusion.",
  difficulty="hard",
  why={"Pertussis toxin stimulates lymphocyte production in marrow": "The cells are redistributed, not newly produced.",
       "Tracheal cytotoxin lyses circulating neutrophils": "Tracheal cytotoxin damages ciliated airway epithelium.",
       "Filamentous hemagglutinin binds and retains lymphocytes": "FHA is an adhesin for respiratory epithelium.",
       "Endotoxin drives a leukemoid reaction with lymphoblasts": "The cells are mature lymphocytes, not blasts."},
  table=TOXINS),

Q(TAG_ENT, "Proteus: urine microscopy",
  "A patient with recurrent urinary infections has urine pH of 8.2 and coffin-lid-shaped crystals on microscopy. Which additional finding is most likely?",
  ["A large branching calculus filling the renal pelvis",
   "Calcium oxalate stones shaped like envelopes",
   "Uric acid stones in persistently acidic urine",
   "Cystine stones with a hexagonal crystal shape",
   "No stone formation despite the alkaline urine"],
  "Urease-producing organisms, chiefly Proteus and also Klebsiella and S. saprophyticus, split urea into ammonia, raising urine pH. Magnesium ammonium phosphate (struvite) precipitates as coffin-lid crystals and builds staghorn calculi that fill the collecting system and harbor bacteria. Cure requires stone removal plus antibiotics.",
  difficulty="hard",
  why={"Calcium oxalate stones shaped like envelopes": "Oxalate stones form in normal or acidic urine and are unrelated to urease.",
       "Uric acid stones in persistently acidic urine": "Uric acid stones need acidic urine, the opposite of this.",
       "Cystine stones with a hexagonal crystal shape": "Cystinuria is an inherited transport defect, not infection-related.",
       "No stone formation despite the alkaline urine": "Alkaline urine with these crystals leads to struvite stones."},
  table=UREASE),

Q(TAG_RESP, "Neisseria: complement and eculizumab",
  "A patient with paroxysmal nocturnal hemoglobinuria is about to start eculizumab. Which intervention is most important before the first dose?",
  ["Meningococcal vaccination, because the drug blocks C5",
   "Pneumococcal vaccination, because the drug impairs B cells",
   "Tuberculin testing, because the drug reactivates latent TB",
   "Hepatitis B screening, because the drug reactivates the virus",
   "Antifungal prophylaxis, because the drug causes neutropenia"],
  "Eculizumab and ravulizumab bind C5 and prevent the membrane attack complex from forming. Because MAC is the main defense against Neisseria, these drugs greatly increase the risk of meningococcal disease. Patients need meningococcal vaccination (ACWY and B) at least two weeks before starting, plus antibiotic prophylaxis when vaccination is delayed.",
  difficulty="hard",
  why={"Pneumococcal vaccination, because the drug impairs B cells": "The drug does not affect B cells, and pneumococcus is cleared largely by opsonization.",
       "Tuberculin testing, because the drug reactivates latent TB": "TB reactivation is a concern with TNF inhibitors.",
       "Hepatitis B screening, because the drug reactivates the virus": "HBV reactivation follows rituximab and other B-cell therapies.",
       "Antifungal prophylaxis, because the drug causes neutropenia": "Eculizumab does not cause neutropenia."},
  table=IMMUNODEF),
]
