from qcore import Q
from tables import *
TAG_ZOO = "Zoonotic Bacteria"
TAG_SPI = "Spirochetes"
TAG_RIC = "Rickettsiae & Chlamydiae"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_SPI, "Tick removal and Lyme prophylaxis",
  "A hiker in Connecticut removes an engorged Ixodes tick that has been attached for about 40 hours. He has no rash or symptoms. Which action is most appropriate?",
  ["A single 200 mg dose of doxycycline within 72 hours",
   "A 21-day course of oral doxycycline started today",
   "Lyme serology today, with treatment only if positive",
   "Intravenous ceftriaxone given as a single dose now",
   "No action, since prophylaxis is never recommended"],
  "A single 200 mg dose of doxycycline can be offered when an identified Ixodes tick has been attached at least 36 hours, removal was within 72 hours, and local infection rates are high. Serology is useless this early because antibodies take weeks. A full treatment course is reserved for actual disease such as erythema migrans.",
  difficulty="easy",
  why={"A 21-day course of oral doxycycline": "A full course is treatment for established disease, not prophylaxis.",
       "Lyme serology today": "Antibodies take 2-6 weeks to appear, so early testing misleads.",
       "Intravenous ceftriaxone given as a single dose": "IV therapy is reserved for carditis, meningitis, or refractory arthritis.",
       "No action, since prophylaxis is never recommended": "Prophylaxis is recommended when these specific criteria are met."},
  table=LYME_STAGES),

Q(TAG_ZOO, "Rabbit exposure",
  "A hunter develops fever and a painful ulcer with swollen regional nodes after skinning wild rabbits. Which organism should the laboratory be warned about?",
  ["Francisella tularensis",
   "Bartonella henselae",
   "Pasteurella multocida",
   "Salmonella enterica",
   "Leptospira interrogans"],
  "Francisella tularensis is among the most infectious bacteria known, with an infectious dose as low as 10 organisms, and it causes laboratory-acquired infections through aerosols. Suspected specimens require BSL-3 handling, so the laboratory must be notified. Treat with an aminoglycoside.",
  difficulty="easy",
  why={"Bartonella henselae": "Cat scratch disease follows kitten exposure and is not a major lab hazard.",
       "Pasteurella multocida": "Pasteurella follows cat or dog bites and grows readily and safely.",
       "Salmonella enterica": "Salmonella comes from food and reptiles and is handled at BSL-2.",
       "Leptospira interrogans": "Leptospira comes from contaminated water rather than rabbit carcasses."},
  table=ZOONOSES),

Q(TAG_RIC, "Doxycycline in children",
  "A 5-year-old in Oklahoma has fever, headache, and a petechial rash spreading from the wrists after a tick bite. The parents ask whether doxycycline will stain the child's teeth. What is the best response?",
  ["Short courses do not appreciably stain teeth and are recommended",
   "Doxycycline is contraindicated below the age of eight years",
   "Chloramphenicol is preferred in children despite its toxicity",
   "Amoxicillin is an equally effective alternative in this illness",
   "Treatment should be delayed until serology confirms the diagnosis"],
  "Doxycycline is the treatment of choice for suspected Rocky Mountain spotted fever at any age. Short courses do not cause clinically significant dental staining, and delay markedly increases mortality. Therapy is started on clinical suspicion because confirmatory serology becomes positive only after 7-10 days.",
  difficulty="easy",
  why={"Doxycycline is contraindicated below the age of eight": "That older teaching has been revised for this life-threatening infection.",
       "Chloramphenicol is preferred in children": "Chloramphenicol is less effective and carries marrow toxicity.",
       "Amoxicillin is an equally effective alternative": "Beta-lactams have no activity against rickettsiae.",
       "Treatment should be delayed until serology confirms": "Waiting for serology costs lives."},
  table=TICKBORNE),

Q(TAG_SPI, "Syphilis in pregnancy with penicillin allergy",
  "A pregnant woman with a documented IgE-mediated penicillin allergy has newly diagnosed secondary syphilis. Which management is correct?",
  ["Desensitize to penicillin, then treat with penicillin",
   "Treat with doxycycline for fourteen days instead",
   "Treat with azithromycin as a single oral dose",
   "Defer treatment until after she has delivered",
   "Treat with intramuscular ceftriaxone for ten days"],
  "Penicillin is the only regimen proven to treat both the mother and the fetus, so penicillin-allergic pregnant women undergo desensitization and then receive benzathine penicillin G. Doxycycline is contraindicated in pregnancy, azithromycin resistance is widespread, and deferring treatment risks congenital syphilis, stillbirth, and neonatal death.",
  difficulty="easy",
  why={"Treat with doxycycline for fourteen days": "Tetracyclines are contraindicated in pregnancy.",
       "Treat with azithromycin as a single oral dose": "Macrolide-resistant T. pallidum is common and it does not reliably treat the fetus.",
       "Defer treatment until after she has delivered": "Delay allows transplacental infection and fetal loss.",
       "Treat with intramuscular ceftriaxone for ten days": "Ceftriaxone data are limited and it is not the standard in pregnancy."},
  table=SYPHILIS_STAGES),

# ---------------- medium ----------------
Q(TAG_SPI, "Post-treatment Lyme symptoms",
  "A patient treated with appropriate doxycycline for erythema migrans two months ago still has fatigue and aching. Repeat Lyme serology remains positive. What is the most appropriate management?",
  ["Symptomatic care, since antibody titers persist after cure",
   "A prolonged course of intravenous ceftriaxone for months",
   "Repeat oral doxycycline courses until serology turns negative",
   "Long-term combination antibiotics for chronic Lyme infection",
   "Immediate testing for co-infection with Rickettsia rickettsii"],
  "Antibodies persist for years after successful treatment, so serology cannot be used as a test of cure. Lingering fatigue and musculoskeletal pain after treatment (post-treatment Lyme disease syndrome) does not respond to further antibiotics, and prolonged IV therapy causes line infections and other harm. Evaluate for co-infection with Babesia or Anaplasma if fever or cytopenias are present.",
  why={"A prolonged course of intravenous ceftriaxone": "Trials show no benefit and significant harm from prolonged IV therapy.",
       "Repeat oral doxycycline courses until serology turns negative": "Serology is not a marker of cure.",
       "Long-term combination antibiotics": "There is no evidence of persistent infection after standard treatment.",
       "Immediate testing for co-infection with Rickettsia rickettsii": "RMSF is transmitted by Dermacentor, not Ixodes."},
  table=LYME_STAGES),

Q(TAG_ZOO, "Q fever: acute vs chronic",
  "A slaughterhouse worker had an acute febrile pneumonia with hepatitis a year ago that resolved without specific therapy. He now has months of fatigue, weight loss, and a new aortic murmur with negative blood cultures. Which test best establishes the diagnosis?",
  ["Coxiella phase I IgG antibody titers",
   "Repeat blood cultures held for two weeks",
   "Brucella agglutination antibody testing",
   "Tuberculin skin testing with control antigens",
   "Serum galactomannan antigen measurement"],
  "Acute Q fever produces high phase II antibodies, while chronic infection such as endocarditis produces high phase I IgG titers. Coxiella does not grow in routine blood cultures, so it is a classic cause of culture-negative endocarditis. Chronic disease is treated with prolonged doxycycline plus hydroxychloroquine, often for 18 months or longer.",
  why={"Repeat blood cultures held for two weeks": "Coxiella is an obligate intracellular organism that will not grow.",
       "Brucella agglutination antibody testing": "Brucella is a reasonable mimic but does not fit the earlier pneumonia with hepatitis.",
       "Tuberculin skin testing": "TB does not typically cause culture-negative endocarditis.",
       "Serum galactomannan antigen measurement": "Galactomannan detects invasive aspergillosis."},
  table=ZOONOSES),

Q(TAG_RIC, "Chlamydia screening",
  "Which patient should be screened annually for chlamydial infection even without symptoms?",
  ["A sexually active 21-year-old woman",
   "A sexually active 40-year-old woman in a monogamous relationship",
   "A 30-year-old man with one long-term female partner",
   "A 60-year-old woman who is not sexually active",
   "A 16-year-old girl who has never been sexually active"],
  "Annual chlamydia screening is recommended for all sexually active women under 25, and for older women with risk factors such as new or multiple partners. Most infections are asymptomatic, and untreated infection causes PID, tubal infertility, and ectopic pregnancy. Screening uses nucleic acid amplification testing.",
  why={"A sexually active 40-year-old woman in a monogamous relationship": "Screening over 25 is based on risk factors, which are absent here.",
       "A 30-year-old man with one long-term female partner": "Routine screening of low-risk men is not recommended.",
       "A 60-year-old woman who is not sexually active": "There is no exposure risk.",
       "A 16-year-old girl who has never been sexually active": "Screening applies to sexually active patients."},
  table=CHLAMYDIA_SEROVARS),

Q(TAG_ZOO, "Brucellosis relapse",
  "A patient treated for brucellosis with a six-week regimen develops recurrent fever and back pain four months later. Blood cultures again grow Brucella. Which factor most likely explains the relapse?",
  ["The organism survives inside macrophages, so short courses fail",
   "The organism acquired a plasmid encoding doxycycline resistance",
   "The organism formed spores that resisted the antibiotic course",
   "The organism switched its capsular antigen to escape antibodies",
   "The organism produced beta-lactamase that degraded the drugs"],
  "Brucella is a facultative intracellular organism that persists inside macrophages of the reticuloendothelial system, where many antibiotics penetrate poorly. Relapse rates are high with short or single-drug therapy, so treatment uses doxycycline combined with rifampin or an aminoglycoside for at least six weeks, and longer for spondylitis or endocarditis. Relapse usually reflects inadequate therapy rather than acquired resistance.",
  why={"The organism acquired a plasmid encoding doxycycline resistance": "Acquired resistance in Brucella is rare.",
       "The organism formed spores": "Brucella does not form spores.",
       "The organism switched its capsular antigen": "Antigenic variation is not a Brucella mechanism.",
       "The organism produced beta-lactamase": "The regimen does not rely on beta-lactams."},
  table=ZOONOSES),

Q(TAG_RIC, "Psittacosis vs Q fever",
  "Two patients have atypical pneumonia with headache and relative bradycardia. Patient A keeps parrots; patient B works with sheep during lambing. Which statement correctly distinguishes them?",
  ["Both are treated with doxycycline, but only Coxiella causes endocarditis",
   "Both are treated with penicillin, since both have a peptidoglycan wall",
   "Only Chlamydia psittaci requires an arthropod vector for transmission",
   "Only Coxiella burnetii is transmitted from person to person by droplets",
   "Both organisms grow readily on standard blood agar within 48 hours"],
  "Chlamydia psittaci (birds) and Coxiella burnetii (livestock birth products) both cause atypical pneumonia and both respond to doxycycline. Coxiella is the one that classically causes chronic culture-negative endocarditis and is notable for an extremely low infectious dose by aerosol. Neither organism grows on standard media, and beta-lactams are ineffective.",
  why={"Both are treated with penicillin": "Neither organism responds to beta-lactams.",
       "Only Chlamydia psittaci requires an arthropod vector": "Psittacosis is acquired by inhaling dried bird droppings.",
       "Only Coxiella burnetii is transmitted from person to person": "Person-to-person spread essentially does not occur.",
       "Both organisms grow readily on standard blood agar": "Both are obligate intracellular organisms."},
  table=ATYPICAL_PNA),

Q(TAG_SPI, "Neurosyphilis: CSF findings",
  "A man with untreated syphilis has progressive memory loss and personality change. CSF shows lymphocytic pleocytosis, elevated protein, and a reactive VDRL. Which statement about testing is correct?",
  ["A reactive CSF VDRL is specific but not sensitive for neurosyphilis",
   "A reactive CSF VDRL is sensitive but not specific for neurosyphilis",
   "A non-reactive CSF VDRL definitively excludes neurosyphilis",
   "Serum RPR titers correlate directly with CSF inflammation",
   "CSF FTA-ABS is highly specific and confirms the diagnosis"],
  "CSF VDRL is highly specific, so a reactive result in a patient with syphilis confirms neurosyphilis, but it is insensitive and a negative result does not exclude it. CSF FTA-ABS is sensitive but not specific, so a negative result helps exclude disease while a positive one does not confirm it. Neurosyphilis requires IV aqueous penicillin G.",
  why={"A reactive CSF VDRL is sensitive but not specific": "The properties are reversed in this option.",
       "A non-reactive CSF VDRL definitively excludes neurosyphilis": "Sensitivity is limited, so disease can still be present.",
       "Serum RPR titers correlate directly with CSF inflammation": "Serum titers do not reliably reflect CNS involvement.",
       "CSF FTA-ABS is highly specific and confirms the diagnosis": "CSF FTA-ABS is sensitive but not specific."},
  table=SYPH_TESTS),

# ---------------- hard ----------------
Q(TAG_SPI, "Lyme carditis vs Chagas",
  "A 30-year-old man from Connecticut has new complete heart block, and a 45-year-old woman from rural Bolivia has heart block with an apical aneurysm. Which statement correctly contrasts the cardiac disease?",
  ["Lyme carditis usually resolves with antibiotics; Chagas damage is permanent",
   "Lyme carditis causes permanent fibrosis; Chagas carditis fully reverses",
   "Both conditions require immediate permanent pacemaker implantation",
   "Both conditions respond promptly to a single course of doxycycline",
   "Neither condition involves the cardiac conduction system directly"],
  "Lyme carditis causes AV block that typically resolves with antibiotics, so temporary pacing may be needed but permanent pacemakers are usually avoided. Chagas cardiomyopathy reflects destruction of autonomic ganglia and myocardial fibrosis, which is irreversible and often needs a pacemaker or defibrillator; benznidazole does not reverse established damage.",
  difficulty="hard",
  why={"Lyme carditis causes permanent fibrosis; Chagas carditis fully reverses": "The two are reversed here.",
       "Both conditions require immediate permanent pacemaker": "Lyme block usually resolves, so permanent pacing is avoided.",
       "Both conditions respond promptly to a single course of doxycycline": "Doxycycline has no activity against T. cruzi.",
       "Neither condition involves the cardiac conduction system": "Both classically involve conduction tissue."},
  table=TICKBORNE),

Q(TAG_RIC, "Rickettsial rash timing",
  "A patient with suspected Rocky Mountain spotted fever has had three days of fever and headache but no rash. Which statement is most accurate?",
  ["Up to 15 percent of patients never develop a rash at all",
   "A rash is present at onset in nearly every infected patient",
   "Absence of a rash on day three excludes the diagnosis",
   "Rash always begins on the trunk and spreads to the limbs",
   "Rash appears only after antibiotics are started for the illness"],
  "The rash of RMSF typically appears on days 3-5, starting at the wrists and ankles and spreading centrally to include palms and soles. A substantial minority, especially older adults and those with darker skin, never develop a recognized rash ('spotless' fever). Because mortality rises sharply after day 5, doxycycline is started on clinical suspicion alone.",
  difficulty="hard",
  why={"A rash is present at onset in nearly every infected patient": "Fever and headache usually precede the rash by several days.",
       "Absence of a rash on day three excludes the diagnosis": "The rash often has not yet appeared, and some cases never develop one.",
       "Rash always begins on the trunk": "Centrifugal spread from wrists and ankles is typical; truncal onset suggests typhus.",
       "Rash appears only after antibiotics are started": "The rash is part of the natural course of illness."},
  table=RICKETTSIAE),

Q(TAG_ZOO, "Plague: bioterrorism preparedness",
  "A public health team plans for a possible aerosolized Yersinia pestis release. Which statement about pneumonic plague is correct?",
  ["Untreated pneumonic plague is nearly always fatal within days",
   "Pneumonic plague responds well to oral penicillin prophylaxis",
   "Buboes are the dominant finding in aerosol-acquired disease",
   "Person-to-person spread requires a flea vector to occur",
   "A widely available licensed vaccine prevents pneumonic plague"],
  "Primary pneumonic plague follows inhalation, has an incubation of 1-6 days, and is almost uniformly fatal without antibiotics started within about 24 hours of symptom onset. It spreads person to person by respiratory droplets, so patients need droplet precautions and contacts need doxycycline or ciprofloxacin prophylaxis. Buboes are typical of flea-borne bubonic disease, not inhalational exposure.",
  difficulty="hard",
  why={"Pneumonic plague responds well to oral penicillin prophylaxis": "Beta-lactams are not the recommended agents for plague.",
       "Buboes are the dominant finding in aerosol-acquired disease": "Inhalation produces pneumonia without prominent buboes.",
       "Person-to-person spread requires a flea vector": "Respiratory droplets transmit pneumonic plague directly.",
       "A widely available licensed vaccine prevents pneumonic plague": "No widely licensed plague vaccine is available in the US."},
  table=ZOONOSES),

Q(TAG_SPI, "Congenital syphilis evaluation",
  "A newborn has a nonreactive RPR, but the mother was treated for syphilis only two weeks before delivery. The infant appears well. What is the most appropriate approach?",
  ["Evaluate and treat the infant, since maternal treatment was inadequate",
   "Discharge without treatment because the infant's RPR is nonreactive",
   "Repeat the infant's RPR at one year and treat only if it rises",
   "Treat the mother again and observe the infant without testing",
   "Give the infant a single oral dose of azithromycin before discharge"],
  "Maternal treatment is considered adequate only if appropriate penicillin was given more than 4 weeks before delivery with an appropriate titer response. Treatment within 30 days of delivery, non-penicillin regimens, or an inadequate titer drop all mandate full infant evaluation (CSF analysis, long bone films, CBC) and treatment with penicillin. A nonreactive neonatal RPR does not exclude infection.",
  difficulty="hard",
  why={"Discharge without treatment because the infant's RPR is nonreactive": "Neonatal serology can be negative in early or late-acquired infection.",
       "Repeat the infant's RPR at one year": "Waiting allows irreversible bone, eye, and neurologic damage.",
       "Treat the mother again and observe the infant without testing": "The infant needs its own evaluation and treatment.",
       "Give the infant a single oral dose of azithromycin": "Penicillin is the only adequate treatment for congenital syphilis."},
  table=TORCH),
]
