from qcore import Q
from tables import *
TAG_MYC = "Mycobacteria"
TAG_ABX = "Antibacterial Drugs"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_MYC, "TB transmission precautions",
  "A patient with cough, night sweats, and an upper lobe cavity is admitted. Which isolation precaution is required?",
  ["Airborne precautions with a negative-pressure room",
   "Droplet precautions with a surgical mask for staff",
   "Contact precautions with gowns and gloves only",
   "Standard precautions, since tuberculosis is not contagious",
   "Protective isolation to shield the patient from others"],
  "M. tuberculosis spreads by droplet nuclei that stay suspended in air for hours, so airborne precautions with a negative-pressure room and fit-tested N95 respirators are required. Droplet precautions suffice for influenza, pertussis, and meningococcus, which travel in larger droplets that fall quickly.",
  difficulty="easy",
  why={"Droplet precautions with a surgical mask": "Surgical masks do not filter droplet nuclei.",
       "Contact precautions with gowns and gloves only": "Contact precautions address surface and skin transmission.",
       "Standard precautions, since tuberculosis is not contagious": "Pulmonary TB with a cavity is highly contagious.",
       "Protective isolation to shield the patient": "Protective isolation is for neutropenic patients."}),

Q(TAG_ABX, "Allergy history: rash vs anaphylaxis",
  "A patient reports that amoxicillin caused a mild non-itchy rash in childhood, without swelling or breathing difficulty. He now needs treatment for a streptococcal infection. What is the most appropriate approach?",
  ["A cephalosporin or penicillin can usually be given safely",
   "All beta-lactams must be avoided for the rest of his life",
   "Vancomycin should replace beta-lactams in every situation",
   "He requires desensitization before any antibiotic is given",
   "Aztreonam is the only safe option for this type of history"],
  "Most reported penicillin allergies are not IgE-mediated, and childhood rashes often reflect a viral exanthem or an aminopenicillin rash. Unnecessary avoidance leads to broader, more toxic, and less effective therapy. A careful history, and allergy testing when needed, allows most patients to receive beta-lactams; cross-reactivity with modern cephalosporins is low.",
  difficulty="easy",
  why={"All beta-lactams must be avoided": "A benign childhood rash does not warrant lifelong avoidance.",
       "Vancomycin should replace beta-lactams in every situation": "Vancomycin is less effective for streptococci and drives resistance.",
       "He requires desensitization before any antibiotic": "Desensitization is reserved for true IgE-mediated allergy with no alternative.",
       "Aztreonam is the only safe option": "Aztreonam has no Gram-positive activity."}),

Q(TAG_ABX, "Antibiotics and oral contraceptives",
  "A woman taking a combined oral contraceptive is prescribed rifampin for latent tuberculosis. Which counseling point is most important?",
  ["Rifampin induces CYP enzymes and can cause contraceptive failure",
   "Rifampin inhibits CYP enzymes and raises hormone levels sharply",
   "Rifampin has no interaction with any hormonal contraception",
   "Rifampin only interacts with progestin-only contraceptive pills",
   "Rifampin blocks absorption of hormones from the intestine"],
  "Rifampin is a potent inducer of CYP3A4 and other enzymes, accelerating metabolism of estrogens and progestins and reducing contraceptive efficacy. Patients should use an additional or alternative method during therapy and for about a month afterward. Rifampin also lowers levels of warfarin, protease inhibitors, and many other drugs, and turns secretions orange.",
  difficulty="easy",
  why={"Rifampin inhibits CYP enzymes": "Rifampin induces rather than inhibits these enzymes.",
       "Rifampin has no interaction": "The interaction is clinically important.",
       "Rifampin only interacts with progestin-only contraceptive": "It affects both estrogen and progestin components.",
       "Rifampin blocks absorption of hormones": "The mechanism is accelerated metabolism, not malabsorption."},
  table=TB_DRUGS),

Q(TAG_ABX, "Culture before antibiotics",
  "A patient with suspected bacterial endocarditis is hemodynamically stable. Why should blood cultures be drawn before antibiotics are started?",
  ["Prior antibiotics commonly make blood cultures negative",
   "Antibiotics cause blood cultures to show false-positive growth",
   "Cultures drawn afterward always grow resistant organisms only",
   "Drawing cultures first shortens the total duration of therapy",
   "Blood cultures cannot be interpreted once fever has resolved"],
  "Even a single antibiotic dose can sterilize the blood enough to prevent growth, and prior antibiotic exposure is the most common cause of culture-negative endocarditis. In stable patients, at least three sets from separate sites are drawn before therapy. In septic shock or meningitis, antibiotics are given immediately after cultures are drawn without delay.",
  difficulty="easy",
  why={"Antibiotics cause blood cultures to show false-positive growth": "Antibiotics suppress growth rather than create it.",
       "Cultures drawn afterward always grow resistant organisms only": "They usually grow nothing at all.",
       "Drawing cultures first shortens the total duration of therapy": "The benefit is identifying the organism, not shortening therapy.",
       "Blood cultures cannot be interpreted once fever has resolved": "Bacteremia in endocarditis is continuous, not fever-dependent."}),

# ---------------- medium ----------------
Q(TAG_MYC, "IGRA vs tuberculin skin test",
  "A nurse who received BCG as a child needs testing for latent tuberculosis. Which statement favors an interferon-gamma release assay?",
  ["IGRA uses antigens absent from BCG, so prior vaccination does not interfere",
   "IGRA distinguishes latent infection from active tuberculosis disease",
   "IGRA remains reliable in the first weeks after recent exposure",
   "IGRA requires a second visit for the result to be read properly",
   "IGRA is preferred in children under two years of age"],
  "IGRAs measure interferon-gamma release to ESAT-6 and CFP-10, antigens absent from BCG and most nontuberculous mycobacteria, so BCG does not cause false positives. They need only one visit. Like the skin test, an IGRA cannot separate latent infection from active disease, and neither test is reliable during the window before immune conversion.",
  why={"IGRA distinguishes latent infection from active tuberculosis": "Neither test makes that distinction.",
       "IGRA remains reliable in the first weeks after recent exposure": "Both tests take 8-10 weeks to convert.",
       "IGRA requires a second visit": "That is the skin test, which must be read at 48-72 hours.",
       "IGRA is preferred in children under two": "Skin testing is generally preferred in very young children."},
  table=TST),

Q(TAG_MYC, "Directly observed therapy",
  "A patient with smear-positive pulmonary tuberculosis has missed several clinic appointments. Which intervention most reduces the risk of acquired drug resistance?",
  ["Directly observed therapy for the full treatment course",
   "Adding a fifth drug to the standard four-drug regimen",
   "Shortening therapy to two months to improve adherence",
   "Switching to intermittent isoniazid monotherapy at home",
   "Rechecking sputum smears weekly without other changes"],
  "Acquired resistance develops when drug exposure is irregular, allowing resistant mutants to be selected. Directly observed therapy, in person or by video, is the most effective way to ensure adherence and prevent resistance. Adding drugs, shortening courses, or using monotherapy all worsen the problem.",
  why={"Adding a fifth drug": "More drugs do not help if doses are missed and add toxicity.",
       "Shortening therapy to two months": "Two months of therapy leaves viable organisms and causes relapse.",
       "Switching to intermittent isoniazid monotherapy": "Monotherapy reliably selects resistant organisms.",
       "Rechecking sputum smears weekly": "Monitoring detects failure but does not prevent it."},
  table=TB_DRUGS),

Q(TAG_MYC, "Multidrug-resistant tuberculosis",
  "An isolate from a patient with tuberculosis is resistant to both isoniazid and rifampin. Which term describes this pattern, and what is a key consequence?",
  ["Multidrug-resistant TB, which requires longer regimens with newer agents",
   "Extensively drug-resistant TB, which cannot be treated at all",
   "Mono-resistant TB, which responds to standard four-drug therapy",
   "Latent tuberculosis infection, which needs only one drug",
   "Nontuberculous mycobacterial disease, which needs a macrolide"],
  "Resistance to at least isoniazid and rifampin defines MDR-TB. Treatment uses longer regimens built around bedaquiline, linezolid, and fluoroquinolones, guided by susceptibility testing. Additional resistance to a fluoroquinolone plus another key group A drug defines pre-XDR or XDR-TB, which is harder to treat but not untreatable. Rapid molecular tests detect rifampin resistance within hours.",
  why={"Extensively drug-resistant TB, which cannot be treated at all": "XDR requires additional resistance, and newer regimens do cure many patients.",
       "Mono-resistant TB, which responds to standard four-drug": "Resistance to two key drugs is not mono-resistance.",
       "Latent tuberculosis infection": "This patient has an isolate from active disease.",
       "Nontuberculous mycobacterial disease": "The organism is M. tuberculosis."},
  table=TB_DRUGS),

Q(TAG_ABX, "Vancomycin trough monitoring",
  "A patient on vancomycin for MRSA bacteremia has a rising creatinine. Which statement about vancomycin monitoring is correct?",
  ["Dosing is guided by AUC or trough levels to limit nephrotoxicity",
   "Peak levels are the main determinant of clinical efficacy",
   "Levels need not be monitored because toxicity is unrelated to dose",
   "Concurrent piperacillin-tazobactam lowers the risk of kidney injury",
   "Vancomycin nephrotoxicity is always permanent and irreversible"],
  "Vancomycin exposure is monitored by AUC-guided dosing (preferred) or trough levels, because higher exposure increases acute kidney injury. Risk rises with prolonged therapy, high doses, and concurrent nephrotoxins; the combination with piperacillin-tazobactam is associated with more kidney injury than vancomycin with cefepime or meropenem. Injury is usually reversible when the drug is adjusted or stopped.",
  why={"Peak levels are the main determinant of clinical efficacy": "Efficacy tracks with AUC relative to MIC, not peak.",
       "Levels need not be monitored": "Toxicity is clearly exposure-related.",
       "Concurrent piperacillin-tazobactam lowers the risk": "That combination increases the risk of kidney injury.",
       "Vancomycin nephrotoxicity is always permanent": "It usually improves after adjustment or discontinuation."},
  table=ABX_TOX),

Q(TAG_ABX, "Antibiotic de-escalation",
  "A patient admitted with pneumonia was started on vancomycin and piperacillin-tazobactam. Cultures now grow pan-susceptible Streptococcus pneumoniae, and he is improving. What is the best next step?",
  ["Narrow therapy to a beta-lactam such as ceftriaxone",
   "Continue both drugs for the full treatment course",
   "Add azithromycin to broaden coverage even further",
   "Stop all antibiotics immediately since he is improving",
   "Switch to oral vancomycin to complete the course"],
  "De-escalation to the narrowest effective agent once culture results are known reduces C. difficile infection, resistance, and drug toxicity without worsening outcomes. It is a core principle of antimicrobial stewardship. Stopping entirely before an adequate course risks relapse, and oral vancomycin is not absorbed.",
  why={"Continue both drugs for the full treatment course": "Unnecessary broad coverage causes harm and resistance.",
       "Add azithromycin to broaden coverage": "Broadening is the opposite of what culture data support.",
       "Stop all antibiotics immediately": "An adequate course is still required.",
       "Switch to oral vancomycin": "Oral vancomycin is not absorbed and cannot treat pneumonia."}),

Q(TAG_ABX, "Aminoglycoside once-daily dosing",
  "Why is gentamicin often given as a single large daily dose rather than divided doses?",
  ["Killing is concentration-dependent and a post-antibiotic effect persists",
   "Killing is time-dependent, so continuous high levels are required",
   "Once-daily dosing raises trough levels and improves tissue uptake",
   "Once-daily dosing allows the drug to work against anaerobes as well",
   "Divided dosing causes more ototoxicity because peaks are higher"],
  "Aminoglycosides kill in proportion to peak concentration and continue to suppress growth after levels fall (post-antibiotic effect). Extended-interval dosing achieves high peaks for efficacy while allowing troughs to fall, which reduces the saturable uptake into renal tubular cells and cochlear hair cells that drives toxicity. Beta-lactams, in contrast, are time-dependent.",
  why={"Killing is time-dependent": "That describes beta-lactams, which benefit from frequent or prolonged infusion.",
       "Once-daily dosing raises trough levels": "It lowers troughs, which is what reduces toxicity.",
       "Once-daily dosing allows the drug to work against anaerobes": "Anaerobes resist aminoglycosides because uptake requires oxygen.",
       "Divided dosing causes more ototoxicity because peaks are higher": "Divided dosing gives lower peaks but higher troughs."},
  table=PROTEIN_SYNTH),

# ---------------- hard ----------------
Q(TAG_ABX, "Beta-lactam infusion strategy",
  "An ICU patient with Pseudomonas pneumonia is switched from intermittent piperacillin-tazobactam to an extended four-hour infusion. What is the pharmacologic rationale?",
  ["It increases the time that free drug stays above the MIC",
   "It raises the peak concentration achieved after each dose",
   "It produces a longer post-antibiotic effect against the organism",
   "It converts the drug from bacteriostatic to bactericidal activity",
   "It reduces protein binding and thereby increases free drug"],
  "Beta-lactams kill in a time-dependent way, so efficacy correlates with the fraction of the dosing interval during which free drug concentration exceeds the MIC. Prolonged or continuous infusion increases that time, which matters most for organisms with high MICs such as Pseudomonas. Beta-lactams have minimal post-antibiotic effect against Gram-negative rods.",
  difficulty="hard",
  why={"It raises the peak concentration achieved": "Extended infusion lowers the peak while extending exposure.",
       "It produces a longer post-antibiotic effect": "Beta-lactams have little post-antibiotic effect against Gram-negatives.",
       "It converts the drug from bacteriostatic to bactericidal": "Beta-lactams are already bactericidal.",
       "It reduces protein binding": "Infusion rate does not alter protein binding."}),

Q(TAG_ABX, "Inoculum effect and the Eagle phenomenon",
  "In severe streptococcal necrotizing infection, penicillin can fail despite full susceptibility in vitro. Which mechanism best explains this, and what is the practical response?",
  ["Stationary-phase organisms downregulate PBPs; add clindamycin",
   "The organism acquires beta-lactamase in tissue; add clavulanate",
   "Penicillin cannot penetrate fascia; switch to intravenous vancomycin",
   "The organism develops altered PBP2a in tissue; switch to ceftaroline",
   "Penicillin is inactivated by low tissue pH; give sodium bicarbonate"],
  "At very high bacterial densities, organisms enter stationary phase and reduce expression of penicillin-binding proteins, so beta-lactams lose effect. This is the Eagle effect, or inoculum effect. Clindamycin works regardless of growth phase and also suppresses toxin and M-protein synthesis, so it is added to penicillin in severe streptococcal infection along with surgical debridement.",
  difficulty="hard",
  why={"The organism acquires beta-lactamase in tissue": "Group A strep does not produce beta-lactamase.",
       "Penicillin cannot penetrate fascia": "Poor perfusion of necrotic tissue matters, but the key mechanism is growth phase.",
       "The organism develops altered PBP2a in tissue": "PBP2a is a staphylococcal mechanism and is not acquired during an infection.",
       "Penicillin is inactivated by low tissue pH": "Tissue pH is not the explanation for this phenomenon."}),

Q(TAG_ABX, "Sulfonamide and G6PD deficiency",
  "A man of Mediterranean descent develops fatigue, jaundice, and dark urine three days after starting TMP-SMX. Blood smear shows bite cells and Heinz bodies. Which statement about further testing is correct?",
  ["G6PD levels can be falsely normal during acute hemolysis",
   "G6PD levels are highest during an acute hemolytic episode",
   "A normal G6PD level during hemolysis definitively excludes the deficiency",
   "Heinz bodies indicate an autoimmune hemolytic process instead",
   "The reaction is an IgE-mediated allergy to the sulfonamide"],
  "In G6PD deficiency, the oldest, most deficient red cells are destroyed first, leaving younger cells and reticulocytes with relatively higher enzyme activity. Testing during or soon after acute hemolysis can therefore be falsely normal, and should be repeated several weeks later. Oxidant drugs include sulfonamides, dapsone, primaquine, nitrofurantoin, and rasburicase.",
  difficulty="hard",
  why={"G6PD levels are highest during an acute hemolytic episode": "Levels appear higher than baseline but are not truly elevated; the point is that testing is unreliable then.",
       "A normal G6PD level during hemolysis definitively excludes": "A normal result during hemolysis does not exclude the deficiency.",
       "Heinz bodies indicate an autoimmune hemolytic process": "Heinz bodies reflect oxidized denatured hemoglobin.",
       "The reaction is an IgE-mediated allergy": "This is oxidative hemolysis, not an allergic reaction."},
  table=ABX_TOX),

Q(TAG_MYC, "Mycobacterium abscessus",
  "A patient develops painful nodules at injection sites weeks after cosmetic mesotherapy at an unlicensed clinic. Cultures grow a rapidly growing, acid-fast organism resistant to standard antituberculous drugs. Which organism is most likely?",
  ["Mycobacterium abscessus",
   "Mycobacterium tuberculosis",
   "Mycobacterium leprae",
   "Mycobacterium avium complex",
   "Mycobacterium marinum"],
  "Rapidly growing mycobacteria (M. abscessus, M. fortuitum, M. chelonae) grow within a week and cause skin and soft tissue infection after injections, cosmetic procedures, surgery, or tattooing, often from contaminated water or solutions. They resist standard antituberculous drugs, and treatment requires prolonged combinations such as a macrolide with amikacin plus other agents, guided by susceptibility testing.",
  difficulty="hard",
  why={"Mycobacterium tuberculosis": "M. tuberculosis grows slowly over weeks and responds to RIPE therapy.",
       "Mycobacterium leprae": "M. leprae cannot be cultured and causes anesthetic skin lesions.",
       "Mycobacterium avium complex": "MAC is slow-growing and typically causes lung or disseminated disease.",
       "Mycobacterium marinum": "M. marinum follows water exposure to broken skin and grows slowly at lower temperatures."}),
]
