from qcore import Q
from tables import *
TAG_HERP = "Herpesviruses"
TAG_DNA = "DNA Viruses (Non-Herpes)"
TAG_RNA = "RNA Viruses"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_RNA, "Influenza vaccine timing",
  "A healthy 35-year-old asks when to get the influenza vaccine. Which statement is correct?",
  ["Annual vaccination is recommended for everyone six months and older",
   "Vaccination is recommended only for adults older than sixty-five",
   "One vaccination in adulthood provides lifelong protection",
   "Vaccination should be avoided by health care workers",
   "Vaccination is recommended only after an outbreak begins"],
  "Annual influenza vaccination is recommended for everyone 6 months and older, ideally by the end of October. Yearly doses are needed because antigenic drift changes circulating strains and because vaccine-induced immunity wanes. The injectable vaccine is inactivated and safe in pregnancy and immunosuppression; the intranasal vaccine is live and is not.",
  difficulty="easy",
  why={"Vaccination is recommended only for adults older than sixty-five": "Older adults are high-risk but everyone is included.",
       "One vaccination in adulthood provides lifelong protection": "Drift and waning immunity require yearly doses.",
       "Vaccination should be avoided by health care workers": "Health care workers are a priority group.",
       "Vaccination is recommended only after an outbreak begins": "Vaccination takes about two weeks to take effect."},
  table=VACCINES),

Q(TAG_HERP, "Cold sore transmission",
  "A mother with an active cold sore asks how to avoid infecting her newborn. Which advice is most appropriate?",
  ["Avoid kissing the baby and wash hands before handling her",
   "Stop breastfeeding until the cold sore has fully healed",
   "Take oral acyclovir, which fully prevents any transmission",
   "No precautions are needed since oral herpes is harmless",
   "Keep the infant isolated in a negative-pressure room"],
  "HSV-1 spreads by direct contact with lesions or saliva. Neonatal herpes can be devastating, so a parent with an active cold sore should avoid kissing the baby, cover the lesion, and wash hands carefully. Breastfeeding is safe unless there is a lesion on the breast. Antivirals shorten the outbreak but do not eliminate shedding.",
  difficulty="easy",
  why={"Stop breastfeeding until the cold sore has fully healed": "Breastfeeding is safe unless a lesion is on the breast.",
       "Take oral acyclovir, which fully prevents any transmission": "Antivirals reduce but do not eliminate shedding.",
       "No precautions are needed since oral herpes is harmless": "Neonatal HSV can be fatal.",
       "Keep the infant isolated in a negative-pressure room": "HSV is not airborne."},
  table=HERPES),

Q(TAG_DNA, "HPV vaccine counseling",
  "The parents of an 11-year-old ask why the HPV vaccine is given before any sexual activity. What is the best explanation?",
  ["The vaccine prevents infection but does not clear existing infection",
   "The vaccine works only in children younger than twelve years",
   "The vaccine treats existing warts and precancerous lesions",
   "The vaccine protects against all sexually transmitted infections",
   "The vaccine contains live virus that is unsafe in adolescents"],
  "HPV vaccine is prophylactic: it produces neutralizing antibody against L1 capsid proteins and prevents new infection, but it does not treat or clear infection already present. Vaccinating at 11-12 years, before exposure, maximizes benefit, and two doses suffice when started before 15. It is a virus-like particle vaccine containing no viral DNA.",
  difficulty="easy",
  why={"The vaccine works only in children younger than twelve": "It is effective through age 26 and may be considered to 45.",
       "The vaccine treats existing warts and precancerous lesions": "It has no therapeutic effect on established lesions.",
       "The vaccine protects against all sexually transmitted infections": "It covers only specific HPV types.",
       "The vaccine contains live virus": "It contains virus-like particles with no viral genome."},
  table=VACCINES),

Q(TAG_RNA, "Rabies: bat exposure",
  "A family finds a bat in the bedroom where their toddler was sleeping. The child has no visible bite. What is the most appropriate action?",
  ["Give rabies post-exposure prophylaxis, since bat bites can go unnoticed",
   "Observe the child for thirty days and treat only if symptoms appear",
   "Give the rabies vaccine alone without rabies immune globulin",
   "Test the child's blood for rabies antibodies before deciding",
   "Do nothing, because rabies requires a clearly visible wound"],
  "Bat teeth are tiny and bites may leave no visible mark, so post-exposure prophylaxis is recommended when a bat is found in a room with a sleeping person, an unattended child, or anyone unable to report contact. Prophylaxis is both immune globulin and vaccine. Once symptoms appear, rabies is nearly always fatal, so waiting is not an option.",
  difficulty="easy",
  why={"Observe the child for thirty days": "Prophylaxis must begin before symptoms, which are almost uniformly fatal.",
       "Give the rabies vaccine alone": "Unvaccinated people need immune globulin as well.",
       "Test the child's blood for rabies antibodies": "Antibody testing does not exclude incubating infection.",
       "Do nothing, because rabies requires a clearly visible wound": "Bat bites are often invisible."}),

Q(TAG_RNA, "Norovirus infection control",
  "During a norovirus outbreak on a hospital ward, which measure is most effective at limiting spread?",
  ["Soap-and-water handwashing with bleach-based surface cleaning",
   "Alcohol-based hand rub used after every patient contact",
   "Airborne precautions with N95 respirators for all staff",
   "Prophylactic oral antibiotics for exposed staff members",
   "Routine stool cultures for every patient on the ward"],
  "Norovirus is a naked virus that resists alcohol and survives on surfaces, so soap-and-water handwashing and bleach-based (or other sporicidal-grade) disinfection are key, along with contact precautions and excluding ill staff. It is not airborne, antibiotics do not work against viruses, and mass screening does not stop transmission.",
  difficulty="easy",
  why={"Alcohol-based hand rub": "Alcohol is unreliable against non-enveloped viruses.",
       "Airborne precautions with N95 respirators": "Spread is fecal-oral and by contaminated surfaces.",
       "Prophylactic oral antibiotics": "Antibiotics have no antiviral effect.",
       "Routine stool cultures for every patient": "Testing does not itself interrupt transmission."},
  table=DIARRHEA),

# ---------------- medium ----------------
Q(TAG_HERP, "EBV and amoxicillin rash",
  "A 19-year-old with sore throat and fatigue is given amoxicillin and develops a widespread maculopapular rash. Monospot is positive. Which statement is correct?",
  ["The rash does not indicate a true penicillin allergy",
   "The rash confirms an IgE-mediated penicillin allergy",
   "The rash indicates progression to Stevens-Johnson syndrome",
   "The rash means the patient has streptococcal scarlet fever",
   "The rash requires lifelong avoidance of all beta-lactams"],
  "Ampicillin and amoxicillin cause a non-allergic maculopapular rash in most patients with EBV mononucleosis, probably through transient immune activation. It does not predict future reactions, so beta-lactams can be used later. Mononucleosis is managed supportively, with avoidance of contact sports for at least 3-4 weeks because of splenic rupture risk.",
  why={"The rash confirms an IgE-mediated penicillin allergy": "This rash is delayed and non-allergic.",
       "The rash indicates progression to Stevens-Johnson syndrome": "SJS involves mucosal erosions and skin detachment.",
       "The rash means the patient has streptococcal scarlet fever": "Scarlet fever produces a sandpaper rash with strawberry tongue.",
       "The rash requires lifelong avoidance of all beta-lactams": "Unnecessary avoidance leads to worse antibiotic choices later."},
  table=HERPES),

Q(TAG_HERP, "CMV in transplant recipients",
  "A CMV-seronegative patient receives a kidney from a CMV-seropositive donor. Which statement about risk and prevention is correct?",
  ["This mismatch carries the highest risk and warrants valganciclovir prophylaxis",
   "This combination carries the lowest risk of CMV disease after transplant",
   "CMV disease occurs only when the recipient is seropositive beforehand",
   "Acyclovir is the preferred agent for preventing CMV in transplantation",
   "Prophylaxis is unnecessary because CMV disease is always mild"],
  "The highest-risk combination is a seropositive donor with a seronegative recipient (D+/R-), because the recipient has no pre-existing immunity to a virus delivered with the graft. Prevention uses valganciclovir prophylaxis or preemptive therapy guided by viral load monitoring. Acyclovir is not reliably active against CMV, which lacks thymidine kinase.",
  why={"This combination carries the lowest risk": "D+/R- is the highest-risk combination.",
       "CMV disease occurs only when the recipient is seropositive": "Primary infection from the donor organ is the classic scenario.",
       "Acyclovir is the preferred agent": "CMV lacks thymidine kinase, so acyclovir is ineffective.",
       "Prophylaxis is unnecessary because CMV disease is always mild": "CMV causes pneumonitis, colitis, and graft loss."},
  table=HERPES_DRUGS),

Q(TAG_DNA, "BK virus in kidney transplant",
  "A kidney transplant recipient on tacrolimus and mycophenolate has a rising creatinine. Biopsy shows tubular injury with intranuclear inclusions, and plasma BK viral load is high. What is the mainstay of treatment?",
  ["Reducing immunosuppression to restore cellular immunity",
   "High-dose valganciclovir for at least six weeks",
   "Intravenous acyclovir followed by oral suppression",
   "Immediate graft removal to prevent viral dissemination",
   "High-dose corticosteroids to reduce tubular inflammation"],
  "BK polyomavirus nephropathy is managed primarily by carefully reducing immunosuppression so that cellular immunity can control the virus, while balancing the risk of rejection. No antiviral is clearly effective, though cidofovir, leflunomide, and IVIG are sometimes tried. BK also causes hemorrhagic cystitis after hematopoietic stem cell transplant.",
  why={"High-dose valganciclovir": "Valganciclovir targets CMV and is not effective for BK virus.",
       "Intravenous acyclovir": "Acyclovir has no activity against polyomaviruses.",
       "Immediate graft removal": "Graft loss is what reducing immunosuppression aims to prevent.",
       "High-dose corticosteroids": "More immunosuppression worsens viral replication."},
  table=DNA_VIRUSES),

Q(TAG_RNA, "Measles exposure in a clinic",
  "An unvaccinated 3-year-old with measles sat in a waiting room. Which exposed contact should receive immune globulin rather than vaccine?",
  ["A 4-month-old infant exposed in the same waiting room",
   "A healthy 10-year-old with two documented MMR doses",
   "A 30-year-old with documented measles immunity by titer",
   "A healthy 2-year-old with one prior MMR dose already given",
   "A 25-year-old health care worker with two MMR doses"],
  "Susceptible contacts can receive MMR within 72 hours, but immune globulin (within 6 days) is used for those who cannot receive live vaccine or are at high risk: infants under 12 months, pregnant women without evidence of immunity, and severely immunocompromised patients. Already-immune contacts need nothing.",
  why={"A healthy 10-year-old with two documented MMR doses": "Two documented doses indicate presumptive immunity.",
       "A 30-year-old with documented measles immunity by titer": "Serologic immunity means no intervention is needed.",
       "A healthy 2-year-old with one prior MMR dose": "This child can simply receive the second vaccine dose.",
       "A 25-year-old health care worker with two MMR doses": "Two doses meet immunity requirements."},
  table=VACCINES),

Q(TAG_RNA, "Hepatitis A post-exposure",
  "A restaurant worker is diagnosed with hepatitis A. A healthy 30-year-old coworker was exposed five days ago and has never been vaccinated. What is recommended?",
  ["Hepatitis A vaccine, which works well for post-exposure prophylaxis",
   "Immune globulin only, since vaccine is ineffective after exposure",
   "No intervention, because hepatitis A is not contagious to adults",
   "A course of oral ribavirin to prevent clinical hepatitis",
   "Hepatitis B immune globulin plus the hepatitis B vaccine series"],
  "For healthy people aged 12 months to 40 years, hepatitis A vaccine alone is preferred for post-exposure prophylaxis within 2 weeks, and it also provides lasting protection. Immune globulin is preferred for infants under 12 months, adults over 40 (may be given with vaccine), immunocompromised patients, and those with chronic liver disease.",
  why={"Immune globulin only, since vaccine is ineffective": "Vaccine is effective post-exposure in healthy young adults.",
       "No intervention, because hepatitis A is not contagious to adults": "HAV spreads readily by the fecal-oral route.",
       "A course of oral ribavirin": "Ribavirin is not used for hepatitis A.",
       "Hepatitis B immune globulin plus the hepatitis B vaccine": "That regimen addresses hepatitis B exposure."},
  table=HEPATITIS),

Q(TAG_RNA, "Chikungunya vs dengue",
  "A traveler returning from the Caribbean has fever and severe joint pain that persists for months after the fever resolves. Platelets and hematocrit were normal throughout. Which infection is most likely?",
  ["Chikungunya virus infection",
   "Dengue virus infection",
   "Zika virus infection",
   "Yellow fever virus infection",
   "West Nile virus infection"],
  "Chikungunya (a togavirus spread by Aedes) causes abrupt fever with severe, often symmetric polyarthralgia that can persist for months, without the thrombocytopenia and plasma leakage of dengue. Dengue causes breakbone pain with thrombocytopenia and hemoconcentration; Zika is usually mild with rash and conjunctivitis but risks congenital infection.",
  why={"Dengue virus infection": "Dengue causes thrombocytopenia and hemoconcentration, absent here.",
       "Zika virus infection": "Zika causes mild rash and conjunctivitis without prolonged arthritis.",
       "Yellow fever virus infection": "Yellow fever causes jaundice and hemorrhage.",
       "West Nile virus infection": "West Nile causes neuroinvasive disease in older adults."},
  table=ARBO),

# ---------------- hard ----------------
Q(TAG_HERP, "Acyclovir-resistant HSV",
  "A patient with advanced HIV has progressive perianal ulcers despite two weeks of high-dose acyclovir. Culture grows HSV-2. Which mechanism and treatment are most likely appropriate?",
  ["Thymidine kinase mutation; treat with foscarnet",
   "DNA polymerase mutation; treat with oral valacyclovir",
   "Acquired beta-lactamase; treat with amoxicillin-clavulanate",
   "Loss of the viral envelope; treat with interferon alfa",
   "Ribonucleotide reductase deficiency; treat with ribavirin"],
  "Most acyclovir resistance in HSV results from mutations in viral thymidine kinase, so the drug is never phosphorylated. Foscarnet and cidofovir inhibit viral DNA polymerase directly and need no viral kinase, so they remain effective. Valacyclovir and famciclovir share acyclovir's requirement for thymidine kinase and will also fail.",
  difficulty="hard",
  why={"DNA polymerase mutation; treat with oral valacyclovir": "Valacyclovir is a prodrug of acyclovir and would also fail.",
       "Acquired beta-lactamase": "Beta-lactamase is a bacterial enzyme irrelevant to viruses.",
       "Loss of the viral envelope": "Envelope loss would render the virus non-infectious.",
       "Ribonucleotide reductase deficiency; treat with ribavirin": "Ribavirin is not used for HSV."},
  table=HERPES_DRUGS),

Q(TAG_RNA, "Influenza antivirals: mechanism comparison",
  "A hospitalized patient with influenza receives baloxavir instead of oseltamivir. How do these drugs differ?",
  ["Baloxavir blocks cap-dependent endonuclease; oseltamivir blocks neuraminidase",
   "Baloxavir blocks neuraminidase; oseltamivir blocks the M2 ion channel",
   "Baloxavir blocks hemagglutinin binding; oseltamivir blocks viral uncoating",
   "Both drugs inhibit the viral RNA-dependent RNA polymerase directly",
   "Both drugs prevent viral entry by blocking sialic acid receptors"],
  "Baloxavir inhibits the cap-dependent endonuclease of the viral polymerase complex, blocking transcription, and is given as a single oral dose. Oseltamivir and zanamivir inhibit neuraminidase, preventing release of new virions from infected cells. M2 inhibitors such as amantadine are no longer used because of widespread resistance.",
  difficulty="hard",
  why={"Baloxavir blocks neuraminidase; oseltamivir blocks the M2 ion channel": "The mechanisms are misassigned.",
       "Baloxavir blocks hemagglutinin binding": "Neither drug blocks hemagglutinin.",
       "Both drugs inhibit the viral RNA-dependent RNA polymerase directly": "Oseltamivir does not target the polymerase.",
       "Both drugs prevent viral entry": "Both act after entry."}),

Q(TAG_DNA, "Parvovirus B19 in the immunocompromised",
  "A patient on rituximab has persistent severe anemia with a reticulocyte count near zero, normal platelets, and normal white cells. Bone marrow shows giant pronormoblasts. Which test is most likely to establish the diagnosis?",
  ["Parvovirus B19 DNA by PCR in serum",
   "Parvovirus B19 IgM antibody testing",
   "Direct antiglobulin (Coombs) testing",
   "Hemoglobin electrophoresis analysis",
   "Serum vitamin B12 and folate levels"],
  "Parvovirus B19 lyses erythroid precursors, producing pure red cell aplasia with giant pronormoblasts. In patients who cannot mount an antibody response, such as those on rituximab or with HIV, infection persists and serology is unreliable, so PCR for viral DNA is the diagnostic test. Treatment is IVIG, which supplies neutralizing antibody, plus reducing immunosuppression.",
  difficulty="hard",
  why={"Parvovirus B19 IgM antibody testing": "Antibody responses are unreliable in B-cell-depleted patients.",
       "Direct antiglobulin (Coombs) testing": "Coombs testing detects immune hemolysis, which would raise reticulocytes.",
       "Hemoglobin electrophoresis analysis": "Electrophoresis diagnoses hemoglobinopathies, not aplasia.",
       "Serum vitamin B12 and folate levels": "Deficiency causes megaloblastic changes across all cell lines."},
  table=DNA_VIRUSES),

Q(TAG_RNA, "SSPE pathogenesis",
  "A 12-year-old who had measles in infancy develops progressive cognitive decline, myoclonic jerks, and seizures. EEG shows periodic complexes, and CSF has high measles antibody titers. Which statement explains this illness?",
  ["Defective measles virus persists in the CNS for years before disease",
   "Reinfection with a new measles strain causes acute encephalitis",
   "The measles vaccine strain reverts and invades the nervous system",
   "Antibodies against myelin cross-react after measles infection",
   "Prion protein misfolds after measles-induced immune activation"],
  "Subacute sclerosing panencephalitis develops years after measles, usually when infection occurred before age 2. Virus with defective matrix (M) protein persists in neurons and spreads cell to cell, escaping antibody. It causes relentless neurologic decline and is fatal. Risk is essentially eliminated by measles vaccination, and SSPE is not caused by the vaccine strain.",
  difficulty="hard",
  why={"Reinfection with a new measles strain causes acute encephalitis": "Acute post-measles encephalitis occurs within days to weeks, not years.",
       "The measles vaccine strain reverts": "SSPE follows wild-type infection, and vaccination prevents it.",
       "Antibodies against myelin cross-react": "That describes acute disseminated encephalomyelitis.",
       "Prion protein misfolds": "Prion disease is unrelated to measles."},
  table=PARAMYXO),

Q(TAG_RNA, "Poliovirus vaccine strategy",
  "A country with ongoing wild poliovirus transmission is deciding between oral and inactivated vaccine for an outbreak response. Which statement is correct?",
  ["Oral vaccine induces intestinal IgA and interrupts fecal-oral spread",
   "Inactivated vaccine induces stronger intestinal IgA than oral vaccine",
   "Oral vaccine cannot be used in outbreaks because it is not protective",
   "Inactivated vaccine can revert and cause vaccine-derived poliovirus",
   "Neither vaccine reduces transmission once an outbreak has begun"],
  "Oral polio vaccine replicates in the gut and induces mucosal IgA, which blocks intestinal replication and interrupts community transmission, so it is preferred for outbreak control. Its drawback is rare reversion to vaccine-associated paralytic polio and circulating vaccine-derived poliovirus. Inactivated vaccine gives excellent systemic protection against paralysis but weaker mucosal immunity, and it cannot revert.",
  difficulty="hard",
  why={"Inactivated vaccine induces stronger intestinal IgA": "IPV produces mainly serum IgG with limited mucosal immunity.",
       "Oral vaccine cannot be used in outbreaks": "OPV is the mainstay of outbreak response.",
       "Inactivated vaccine can revert": "IPV contains killed virus and cannot revert.",
       "Neither vaccine reduces transmission": "OPV clearly reduces transmission."},
  table=VACCINES),
]
