from qcore import Q
from tables import *
TAG_HIV = "HIV & Antiretrovirals"
TAG_HEP = "Hepatitis Viruses"
TAG_FUN = "Fungi & Antifungals"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_HIV, "HIV screening recommendation",
  "A healthy 30-year-old man has a routine visit and reports no specific risk factors. What is the recommended approach to HIV testing?",
  ["Screen at least once, since universal HIV screening is advised for all adults",
   "Screen only patients who report high-risk sexual behavior",
   "Screen only if the patient has symptoms suggesting infection",
   "Screen only patients who inject drugs or have had transfusions",
   "Defer screening because his risk factors are clearly absent"],
  "Routine one-time HIV screening is recommended for everyone aged 15-65 regardless of stated risk, because risk-based screening misses many infections and diagnosis is often delayed. People with ongoing risk are tested at least annually. Opt-out screening increases diagnosis rates and reduces stigma.",
  difficulty="easy",
  why={"Screen only patients who report high-risk sexual behavior": "Risk-based screening misses a substantial share of infections.",
       "Screen only if the patient has symptoms": "Most infections are asymptomatic for years.",
       "Screen only patients who inject drugs or have had transfusions": "Sexual transmission accounts for most cases.",
       "Defer screening because his risk factors are clearly absent": "Reported risk factors are unreliable."}),

Q(TAG_HEP, "Hepatitis B vaccination of adults",
  "A 45-year-old with type 2 diabetes has never received hepatitis B vaccine. Which statement is correct?",
  ["Vaccination is now recommended for all adults under sixty",
   "Vaccination is recommended only for health care workers",
   "Vaccination is contraindicated in patients with diabetes",
   "Vaccination is needed only after a documented exposure occurs",
   "Vaccination provides protection for only about one year"],
  "Universal hepatitis B vaccination is recommended for all adults aged 19-59, and for those 60 and older with risk factors. Diabetes is itself a risk factor. The vaccine is recombinant HBsAg, produces anti-HBs without anti-HBc, and gives long-lasting protection through immunologic memory.",
  difficulty="easy",
  why={"Vaccination is recommended only for health care workers": "Recommendations now cover all younger adults.",
       "Vaccination is contraindicated in patients with diabetes": "Diabetes increases risk and is an indication.",
       "Vaccination is needed only after a documented exposure": "Pre-exposure vaccination is the goal.",
       "Vaccination provides protection for only about one year": "Protection is long-lasting."},
  table=HBV_SEROLOGY),

Q(TAG_FUN, "Oral candidiasis risk factors",
  "Which factor most predisposes an otherwise healthy adult to oral candidiasis?",
  ["Using an inhaled corticosteroid without rinsing the mouth",
   "Drinking several cups of coffee every day",
   "Brushing the teeth twice each day with fluoride",
   "Taking a daily multivitamin supplement regularly",
   "Exercising vigorously several times per week"],
  "Inhaled corticosteroids deposit in the oropharynx and cause local immunosuppression, so patients are told to rinse and spit after use. Other common predisposing factors are recent antibiotics, dentures, xerostomia, diabetes, and systemic immunosuppression. Unexplained thrush in an adult should prompt HIV testing.",
  difficulty="easy",
  why={"Drinking several cups of coffee every day": "Coffee does not predispose to candidiasis.",
       "Brushing the teeth twice each day": "Good oral hygiene reduces risk.",
       "Taking a daily multivitamin supplement": "Vitamins do not cause thrush.",
       "Exercising vigorously several times per week": "Exercise is unrelated to oral candidiasis."},
  table=OPP_FUNGI),

Q(TAG_FUN, "Tinea capitis treatment",
  "A 6-year-old has a scaly patch of scalp with broken hairs and an enlarged occipital lymph node. KOH shows septate hyphae. What is the appropriate treatment?",
  ["Oral griseofulvin or terbinafine for several weeks",
   "Topical ketoconazole cream applied twice daily",
   "Oral cephalexin aimed at staphylococcal infection",
   "Topical corticosteroid ointment applied to the patch",
   "Selenium sulfide shampoo used as the sole treatment"],
  "Tinea capitis requires systemic therapy because topical agents do not penetrate the hair shaft. Griseofulvin or terbinafine is given for several weeks. Antifungal shampoo reduces spore shedding to contacts but cannot cure infection. A kerion is an inflammatory boggy mass that still reflects fungal infection, not bacterial abscess.",
  difficulty="easy",
  why={"Topical ketoconazole cream": "Topicals cannot reach fungus inside the hair shaft.",
       "Oral cephalexin": "This is a fungal, not bacterial, infection.",
       "Topical corticosteroid ointment": "Steroids alone worsen and mask fungal infection.",
       "Selenium sulfide shampoo used as the sole treatment": "Shampoo is adjunctive only."},
  table=ANTIFUNGALS),

# ---------------- medium ----------------
Q(TAG_HIV, "When to start antiretroviral therapy",
  "A newly diagnosed patient has a CD4 count of 620 cells/microliter and feels well. When should antiretroviral therapy begin?",
  ["As soon as possible, regardless of the CD4 count",
   "Only after the CD4 count falls below 500 cells per microliter",
   "Only after the CD4 count falls below 200 cells per microliter",
   "Only when an opportunistic infection has developed",
   "Only if the plasma viral load exceeds 100,000 copies"],
  "ART is recommended for everyone with HIV regardless of CD4 count, ideally started rapidly, sometimes on the day of diagnosis. Early treatment reduces mortality, AIDS and non-AIDS complications, and transmission (undetectable equals untransmittable). The main exception is delaying ART several weeks in cryptococcal meningitis to reduce IRIS.",
  why={"Only after the CD4 count falls below 500": "CD4-based thresholds are obsolete.",
       "Only after the CD4 count falls below 200": "Waiting allows irreversible immune damage.",
       "Only when an opportunistic infection has developed": "Treatment aims to prevent opportunistic infection.",
       "Only if the plasma viral load exceeds 100,000 copies": "Viral load does not determine eligibility."},
  table=HIV_DRUGS),

Q(TAG_HIV, "Cryptococcal antigen screening",
  "A patient presents with a CD4 count of 60 cells/microliter and no neurologic symptoms. Serum cryptococcal antigen is positive. What is the next step?",
  ["Lumbar puncture to check for occult meningitis",
   "Start antiretroviral therapy immediately without further testing",
   "Repeat the antigen test in three months to confirm",
   "Begin empiric treatment for Pneumocystis pneumonia",
   "Start fluconazole and begin antiretroviral therapy the same day"],
  "A positive serum cryptococcal antigen with advanced HIV requires lumbar puncture, because a substantial proportion have meningitis even without symptoms. If CSF is positive, induction therapy with amphotericin B plus flucytosine is started and ART is delayed 4-6 weeks to reduce the risk of IRIS. Isolated antigenemia with negative CSF is treated with fluconazole.",
  why={"Start antiretroviral therapy immediately without further testing": "Starting ART before excluding meningitis risks severe IRIS.",
       "Repeat the antigen test in three months": "Delay allows meningitis to progress.",
       "Begin empiric treatment for Pneumocystis pneumonia": "The antigen result points to Cryptococcus.",
       "Start fluconazole and begin antiretroviral therapy the same day": "CSF status must be known first."},
  table=HIV_OI),

Q(TAG_HEP, "Hepatitis B reactivation",
  "A patient with resolved hepatitis B (HBsAg negative, anti-HBc positive, anti-HBs positive) is about to start rituximab for lymphoma. What is recommended?",
  ["Antiviral prophylaxis with entecavir or tenofovir during therapy",
   "No intervention, because resolved infection cannot reactivate",
   "Hepatitis B vaccination given during the rituximab course",
   "Interferon therapy started before the first rituximab dose",
   "Monitoring liver enzymes alone without antiviral prophylaxis"],
  "HBV persists as cccDNA in hepatocytes even after apparent resolution, so B-cell-depleting therapy such as rituximab can cause reactivation with severe hepatitis and death. Patients with any anti-HBc positivity should receive prophylaxis with entecavir or tenofovir, continued for at least 12 months after completing immunosuppression.",
  why={"No intervention, because resolved infection cannot reactivate": "cccDNA persists and reactivation is well documented.",
       "Hepatitis B vaccination given during the rituximab course": "B-cell depletion prevents a vaccine response.",
       "Interferon therapy started before the first rituximab dose": "Interferon is not used for prophylaxis.",
       "Monitoring liver enzymes alone": "Monitoring detects reactivation only after damage occurs."},
  table=HEPATITIS),

Q(TAG_HEP, "Hepatitis C in pregnancy",
  "A pregnant woman is found to have chronic hepatitis C. Which statement about management is correct?",
  ["Direct-acting antivirals are usually deferred until after delivery",
   "Cesarean delivery is recommended to prevent transmission",
   "Breastfeeding is contraindicated because of viral transmission",
   "Ribavirin should be started immediately to reduce viral load",
   "Transmission to the infant occurs in the majority of pregnancies"],
  "Vertical HCV transmission occurs in roughly 5-6% of pregnancies and is higher with HIV co-infection or high viral load. Cesarean delivery is not recommended, and breastfeeding is safe unless nipples are cracked and bleeding. Direct-acting antivirals are generally deferred until after pregnancy pending more safety data; ribavirin is teratogenic and contraindicated. Infants are tested after 18 months or by HCV RNA earlier.",
  why={"Cesarean delivery is recommended": "Cesarean delivery does not reduce HCV transmission.",
       "Breastfeeding is contraindicated": "Breastfeeding is considered safe in hepatitis C.",
       "Ribavirin should be started immediately": "Ribavirin is a known teratogen.",
       "Transmission to the infant occurs in the majority": "Transmission occurs in a small minority."},
  table=HEPATITIS),

Q(TAG_FUN, "Candidemia: source control",
  "A patient with candidemia is started on micafungin. Blood cultures remain positive after three days. A central venous catheter remains in place. What is the most important next step?",
  ["Remove the indwelling vascular device",
   "Add fluconazole to the echinocandin therapy",
   "Increase the micafungin dose substantially",
   "Change to oral nystatin suspension therapy",
   "Continue current therapy without any changes"],
  "Candida forms biofilm on intravascular catheters, which shelters it from antifungals, so catheter removal is central to treatment and improves survival. Persistent candidemia also requires evaluation for endocarditis, endophthalmitis, and other metastatic foci, with dilated ophthalmologic examination for all patients. Antifungal therapy continues for 14 days after the first negative culture.",
  why={"Add fluconazole to the echinocandin therapy": "Combination therapy does not overcome an infected device.",
       "Increase the micafungin dose substantially": "Higher doses do not penetrate biofilm adequately.",
       "Change to oral nystatin suspension": "Nystatin is not absorbed and cannot treat bloodstream infection.",
       "Continue current therapy without any changes": "Persistent candidemia demands source control."},
  table=OPP_FUNGI),

Q(TAG_FUN, "Histoplasmosis and TNF inhibitors",
  "A patient in Ohio on infliximab for rheumatoid arthritis develops fever, weight loss, and diffuse pulmonary infiltrates with pancytopenia. Which infection is most likely?",
  ["Disseminated histoplasmosis",
   "Invasive aspergillosis of the lung",
   "Pneumocystis jirovecii pneumonia",
   "Cryptococcal meningitis with lung involvement",
   "Coccidioidomycosis acquired in the Midwest"],
  "TNF-alpha maintains granulomas, so TNF inhibitors predispose to reactivation of granulomatous infections: tuberculosis, histoplasmosis, blastomycosis, coccidioidomycosis, and listeriosis. In the Ohio and Mississippi River valleys, disseminated histoplasmosis with fever, cytopenias, and hepatosplenomegaly is classic. Urine and serum Histoplasma antigen testing is the fastest diagnostic approach.",
  why={"Invasive aspergillosis of the lung": "Aspergillosis occurs mainly with prolonged neutropenia.",
       "Pneumocystis jirovecii pneumonia": "Pneumocystis is more associated with steroids and T-cell depletion, and does not cause pancytopenia.",
       "Cryptococcal meningitis with lung involvement": "Cryptococcus typically presents with headache and meningeal signs.",
       "Coccidioidomycosis acquired in the Midwest": "Coccidioides is endemic in the southwestern deserts."},
  table=DIMORPHIC),

# ---------------- hard ----------------
Q(TAG_HIV, "Virologic failure workup",
  "A patient on dolutegravir, tenofovir, and emtricitabine has a viral load that rose from undetectable to 8,000 copies/mL. Which step comes first?",
  ["Assess adherence and drug interactions before changing therapy",
   "Switch immediately to a protease inhibitor-based regimen",
   "Add a fourth antiretroviral drug to the current regimen",
   "Stop all antiretroviral therapy and observe the viral load",
   "Repeat the CD4 count and continue the regimen unchanged"],
  "Most virologic failure reflects poor adherence or drug interactions (antacids and polyvalent cations with integrase inhibitors, rifampin, and others) rather than resistance. Assess adherence and interactions, then obtain genotypic resistance testing while the patient is still on therapy, because resistant virus becomes undetectable once the drug pressure is removed.",
  difficulty="hard",
  why={"Switch immediately to a protease inhibitor-based regimen": "Switching without understanding the cause repeats the failure.",
       "Add a fourth antiretroviral drug": "Adding a single active drug risks sequential resistance.",
       "Stop all antiretroviral therapy and observe": "Stopping allows disease progression and loses resistance data.",
       "Repeat the CD4 count and continue the regimen": "Ignoring rising viral load allows resistance to accumulate."},
  table=HIV_DRUGS),

Q(TAG_HEP, "Hepatitis D diagnosis",
  "A patient with chronic hepatitis B has worsening liver function. HBsAg is positive and HBV DNA is low, yet transaminases are markedly elevated. Which test should be sent next?",
  ["Hepatitis D antibody with confirmatory HDV RNA",
   "Hepatitis A IgM antibody testing",
   "Hepatitis E IgM antibody testing",
   "Repeat HBV DNA in three months",
   "Alpha-fetoprotein tumor marker measurement"],
  "Hepatitis D requires HBsAg to assemble, and it suppresses HBV replication, so a patient with active liver injury, positive HBsAg, and disproportionately low HBV DNA should be tested for HDV. All HBsAg-positive patients should be screened at least once. Delta co-infection accelerates progression to cirrhosis; bulevirtide, an entry inhibitor, is used where available.",
  difficulty="hard",
  why={"Hepatitis A IgM antibody testing": "Hepatitis A causes acute self-limited illness, not this chronic pattern.",
       "Hepatitis E IgM antibody testing": "Hepatitis E is considered mainly with travel or immunosuppression.",
       "Repeat HBV DNA in three months": "Delay misses an important treatable co-infection.",
       "Alpha-fetoprotein tumor marker measurement": "AFP screens for hepatocellular carcinoma, not this pattern of injury."},
  table=HEPATITIS),

Q(TAG_FUN, "Aspergillus galactomannan interpretation",
  "A neutropenic patient has a positive serum galactomannan. Which factor most limits the interpretation of this result?",
  ["Concurrent mold-active antifungal therapy lowers sensitivity",
   "Neutropenia itself makes the test uninterpretable in all cases",
   "The test detects only Candida species and not molds",
   "Results are valid only when obtained from cerebrospinal fluid",
   "A positive result definitively confirms invasive aspergillosis"],
  "Galactomannan is a cell wall polysaccharide released during hyphal growth. Its sensitivity falls sharply in patients already receiving mold-active prophylaxis, and false positives occur with some beta-lactams, other fungi, and dietary sources. It performs best in neutropenic hematology patients; bronchoalveolar lavage galactomannan adds sensitivity. It supports but does not by itself confirm the diagnosis.",
  difficulty="hard",
  why={"Neutropenia itself makes the test uninterpretable": "Neutropenic patients are where the test performs best.",
       "The test detects only Candida species": "Galactomannan is an Aspergillus cell wall antigen.",
       "Results are valid only when obtained from cerebrospinal fluid": "Serum and BAL are the usual specimens.",
       "A positive result definitively confirms invasive aspergillosis": "False positives occur, so it is supportive evidence."},
  table=OPP_FUNGI),

Q(TAG_FUN, "Antifungal spectrum gaps",
  "A patient with candidemia due to Candida krusei is being treated. Which agent is intrinsically unreliable against this species?",
  ["Fluconazole",
   "Micafungin",
   "Caspofungin",
   "Amphotericin B",
   "Voriconazole"],
  "Candida krusei is intrinsically resistant to fluconazole, and C. glabrata often has reduced azole susceptibility. Echinocandins are the preferred empiric therapy for candidemia, particularly when a non-albicans species is suspected. Candida auris is frequently multidrug-resistant and requires susceptibility-directed therapy and strict infection control.",
  difficulty="hard",
  why={"Micafungin": "Echinocandins remain active against C. krusei.",
       "Caspofungin": "Echinocandins are the preferred treatment for this species.",
       "Amphotericin B": "Amphotericin retains activity against C. krusei.",
       "Voriconazole": "Voriconazole usually remains active despite fluconazole resistance."},
  table=ANTIFUNGALS),
]
