from qcore import Q
from tables import *
TAG_PRO = "Protozoa"
TAG_HEL = "Helminths"
TAG_SYS = "Infections by System & Vaccines"
TAG_LAB = "Bacterial Structure, Genetics & Lab"
QUESTIONS = [
# ---------------- easy ----------------
Q(TAG_PRO, "Malaria prophylaxis choice",
  "A traveler is going to a chloroquine-resistant malaria region for two weeks. Which prophylaxis regimen is appropriate?",
  ["Atovaquone-proguanil taken daily during and after travel",
   "Chloroquine taken weekly during and after the trip",
   "Primaquine taken only after returning home",
   "Azithromycin taken daily throughout the trip",
   "No prophylaxis if insect repellent is used correctly"],
  "For chloroquine-resistant areas, options are atovaquone-proguanil, doxycycline, or mefloquine. Atovaquone-proguanil is started 1-2 days before travel and continued 7 days after leaving. Chemoprophylaxis is combined with bite prevention: repellent, permethrin-treated clothing, and bed nets. Chloroquine is used only where the parasite remains susceptible.",
  difficulty="easy",
  why={"Chloroquine taken weekly": "Chloroquine fails in resistant regions.",
       "Primaquine taken only after returning home": "Primaquine targets liver hypnozoites and is not routine prophylaxis.",
       "Azithromycin taken daily": "Azithromycin is not an effective antimalarial.",
       "No prophylaxis if insect repellent is used": "Repellent alone is insufficient in high-risk areas."},
  table=MALARIA),

Q(TAG_PRO, "Toxoplasmosis prevention in pregnancy",
  "A pregnant woman asks how to avoid toxoplasmosis. Which set of precautions is most appropriate?",
  ["Cook meat thoroughly, wash produce, and avoid changing cat litter",
   "Avoid all contact with cats and give away any household pets",
   "Avoid swimming pools and any recreational fresh water",
   "Take prophylactic pyrimethamine for the entire pregnancy",
   "Avoid all dairy products throughout the whole pregnancy"],
  "Toxoplasma is acquired from tissue cysts in undercooked meat and from oocysts in cat feces or contaminated soil and produce. Cooking meat thoroughly, washing produce, gardening with gloves, and delegating litter box duty are effective. Cats need not be removed, since indoor cats fed commercial food pose little risk and shedding is brief.",
  difficulty="easy",
  why={"Avoid all contact with cats and give away any household pets": "Removing cats is unnecessary and not recommended.",
       "Avoid swimming pools and any recreational fresh water": "That advice relates to Cryptosporidium and Naegleria.",
       "Take prophylactic pyrimethamine": "Pyrimethamine is teratogenic and not used preventively.",
       "Avoid all dairy products": "Unpasteurized dairy matters for Listeria and Brucella."},
  table=TORCH),

Q(TAG_HEL, "Pinworm household management",
  "A child is diagnosed with pinworm. Which additional measure reduces reinfection?",
  ["Wash bedding and clothing and keep fingernails trimmed short",
   "Boil all drinking water used by the household members",
   "Avoid undercooked pork for the next several months",
   "Keep the child home from school for two full weeks",
   "Treat household pets with the same anthelmintic drug"],
  "Pinworm eggs survive on bedding, clothing, and surfaces and are transmitted by hand-to-mouth contact and fomites, with frequent autoinfection from scratching. Laundering bedding and nightclothes, trimming nails, handwashing, and morning bathing reduce reinfection. Treatment is repeated in 2 weeks, and household members are treated together.",
  difficulty="easy",
  why={"Boil all drinking water": "Pinworm is not waterborne.",
       "Avoid undercooked pork": "Pork transmits Taenia solium and Trichinella.",
       "Keep the child home from school for two full weeks": "Exclusion is unnecessary once treatment begins.",
       "Treat household pets": "Humans are the only host for Enterobius."},
  table=NEMATODES),

Q(TAG_SYS, "Hand hygiene",
  "Which single measure most reduces transmission of health care-associated infections?",
  ["Hand hygiene performed before and after patient contact",
   "Routine surveillance cultures from all admitted patients",
   "Prophylactic antibiotics for patients with indwelling lines",
   "Weekly environmental cleaning of all patient rooms",
   "Restricting visitors from entering any patient rooms"],
  "Hand hygiene is the single most effective measure for preventing health care-associated infection. Alcohol-based rub is preferred for most situations, while soap and water is required for C. difficile, norovirus, and visibly soiled hands. Other core measures are catheter and line bundles, appropriate precautions, and antimicrobial stewardship.",
  difficulty="easy",
  why={"Routine surveillance cultures from all admitted patients": "Surveillance identifies colonization but does not by itself prevent spread.",
       "Prophylactic antibiotics for patients with indwelling lines": "Prophylaxis promotes resistance without preventing line infection.",
       "Weekly environmental cleaning": "Cleaning matters but is less effective than hand hygiene between contacts.",
       "Restricting visitors from entering any patient rooms": "Visitor restriction has limited effect on transmission."}),

Q(TAG_LAB, "Blood culture contamination",
  "One of four blood culture bottles grows coagulase-negative staphylococci after four days in a patient with no devices. Which interpretation is most appropriate?",
  ["Likely contamination introduced during venipuncture",
   "Definite bacteremia requiring six weeks of therapy",
   "Proof of endocarditis requiring surgical valve replacement",
   "Evidence of an infected prosthetic device somewhere",
   "A laboratory error that invalidates all four bottles"],
  "Contamination is suggested when only one of several bottles grows a skin organism, growth appears late, and the patient lacks devices or clinical signs. True infection is suggested by multiple positive sets, rapid growth, indwelling hardware, and persistent bacteremia. Careful skin antisepsis and adequate blood volume reduce contamination.",
  difficulty="easy",
  why={"Definite bacteremia requiring six weeks of therapy": "A single bottle with a skin organism usually reflects contamination.",
       "Proof of endocarditis requiring surgical valve replacement": "Endocarditis requires persistent bacteremia and imaging evidence.",
       "Evidence of an infected prosthetic device": "The patient has no device.",
       "A laboratory error that invalidates all four bottles": "The other bottles remain interpretable."},
  table=STAPH),

# ---------------- medium ----------------
Q(TAG_PRO, "Amebic vs pyogenic liver abscess",
  "A man returning from Mexico has fever and right upper quadrant pain. Ultrasound shows a single right lobe liver lesion. Which finding would most favor an amebic rather than pyogenic abscess?",
  ["Positive Entamoeba serology with a single lesion in a young man",
   "Multiple abscesses with growth of enteric organisms on culture",
   "Biliary obstruction with cholangitis on imaging studies",
   "Aspirated material containing abundant neutrophils and bacteria",
   "Recent colonic surgery with an anastomotic leak identified"],
  "Amebic liver abscess is usually a single right lobe lesion in a younger man with travel to an endemic area; serology is positive and aspirate is sterile 'anchovy paste' with few cells. Pyogenic abscesses are often multiple, follow biliary or portal sources, grow enteric organisms, and require drainage. Amebic abscess responds to metronidazole plus a luminal agent.",
  why={"Multiple abscesses with growth of enteric organisms": "That pattern indicates pyogenic infection.",
       "Biliary obstruction with cholangitis": "Biliary disease is the classic source of pyogenic abscess.",
       "Aspirated material containing abundant neutrophils and bacteria": "Amebic aspirate is typically acellular and sterile.",
       "Recent colonic surgery with an anastomotic leak": "That suggests a pyogenic, portal-source abscess."},
  table=INTESTINAL_PROTOZOA),

Q(TAG_HEL, "Strongyloides screening before steroids",
  "A patient from El Salvador is about to start high-dose prednisone for an autoimmune disease. Eosinophilia is noted. Which action is most important?",
  ["Screen for Strongyloides and treat before starting steroids",
   "Start steroids and monitor for symptoms of hyperinfection",
   "Give empiric praziquantel to cover intestinal parasites",
   "Order stool ova and parasite exams after steroids begin",
   "Treat empirically with metronidazole for possible giardiasis"],
  "Strongyloides can persist for decades through autoinfection, and corticosteroids precipitate hyperinfection with disseminated larvae and Gram-negative sepsis, which carries very high mortality. Patients from endemic areas, especially with eosinophilia, should be screened with serology and treated with ivermectin before immunosuppression. Stool examination alone is insensitive.",
  why={"Start steroids and monitor for symptoms": "Hyperinfection is often fatal once established.",
       "Give empiric praziquantel": "Praziquantel treats flukes and tapeworms, not Strongyloides.",
       "Order stool ova and parasite exams after steroids begin": "Testing must precede immunosuppression, and stool testing is insensitive.",
       "Treat empirically with metronidazole": "Metronidazole has no activity against Strongyloides."},
  table=NEMATODES),

Q(TAG_PRO, "Malaria: species identification importance",
  "A returning traveler has fever and a parasitemia of 1%. Why does species identification change management?",
  ["Falciparum can rapidly worsen, and vivax needs liver-stage therapy",
   "Only falciparum requires any antimalarial treatment at all",
   "Only vivax can cause cerebral malaria and severe anemia",
   "Species identification affects prognosis but never treatment",
   "All species are treated identically with chloroquine alone"],
  "Identifying the species matters because P. falciparum can deteriorate within hours, may require IV artesunate, and demands close monitoring, while P. vivax and P. ovale form hypnozoites that need primaquine or tafenoquine after G6PD testing to prevent relapse. Mixed infections occur, and parasitemia should be followed during therapy.",
  why={"Only falciparum requires any antimalarial treatment": "All species require treatment.",
       "Only vivax can cause cerebral malaria": "Cerebral malaria is a falciparum complication.",
       "Species identification affects prognosis but never treatment": "It directly changes drug choice and monitoring.",
       "All species are treated identically with chloroquine alone": "Resistance patterns and liver stages differ."},
  table=MALARIA),

Q(TAG_SYS, "Sepsis: first hour management",
  "A patient with suspected sepsis has a lactate of 4.2 mmol/L and hypotension. Which bundle of actions should occur within the first hour?",
  ["Cultures, broad antibiotics, fluids, and lactate measurement",
   "Imaging first, with antibiotics withheld until a source is found",
   "Vasopressors first, with fluids withheld to avoid overload",
   "Antibiotics withheld until culture results are available",
   "Corticosteroids given first, before antibiotics or fluids"],
  "Sepsis bundles call for measuring lactate, obtaining blood cultures before antibiotics, giving broad-spectrum antibiotics, and starting 30 mL/kg crystalloid for hypotension or lactate of 4 or more, with vasopressors if hypotension persists. Every hour of delay in effective antibiotics increases mortality in septic shock. Source identification and control follow promptly.",
  why={"Imaging first, with antibiotics withheld": "Delaying antibiotics for imaging increases mortality.",
       "Vasopressors first, with fluids withheld": "Fluid resuscitation precedes or accompanies vasopressors.",
       "Antibiotics withheld until culture results": "Cultures take days; empiric therapy cannot wait.",
       "Corticosteroids given first": "Steroids are considered only for refractory shock."}),

Q(TAG_SYS, "Febrile neutropenia",
  "A patient with acute leukemia has an absolute neutrophil count of 200/microliter and a temperature of 38.5 degrees Celsius. What is the most appropriate initial management?",
  ["Immediate empiric antipseudomonal beta-lactam therapy",
   "Observation with antibiotics only if cultures turn positive",
   "Oral amoxicillin after outpatient evaluation and discharge",
   "Antifungal therapy alone, since bacteria are rarely involved",
   "Granulocyte transfusion as the primary initial intervention"],
  "Fever in a neutropenic patient is a medical emergency. Empiric antipseudomonal therapy such as cefepime, piperacillin-tazobactam, or meropenem should begin within an hour of presentation after cultures. Vancomycin is added for suspected line infection, skin infection, or hemodynamic instability. Persistent fever after 4-7 days prompts empiric antifungal therapy.",
  why={"Observation with antibiotics only if cultures turn positive": "Waiting for cultures risks rapid deterioration.",
       "Oral amoxicillin after outpatient evaluation": "Amoxicillin lacks Pseudomonas coverage; only selected low-risk patients are managed as outpatients.",
       "Antifungal therapy alone": "Bacterial infection predominates early.",
       "Granulocyte transfusion as the primary initial intervention": "Granulocyte transfusion is rarely used and never first-line."},
  table=IMMUNODEF),

Q(TAG_LAB, "Minimum inhibitory concentration",
  "A susceptibility report lists an MIC of 2 micrograms/mL with an interpretation of susceptible. What does the MIC represent?",
  ["The lowest drug concentration that prevents visible growth",
   "The lowest drug concentration that kills all organisms present",
   "The peak drug concentration achieved in a patient's serum",
   "The concentration at which resistance mutations first appear",
   "The dose in milligrams required to treat this infection"],
  "MIC is the lowest concentration preventing visible growth in vitro. Susceptible or resistant categories depend on MIC together with achievable drug concentrations at the site of infection, so MICs cannot be compared directly between different drugs. The minimum bactericidal concentration (MBC) is the lowest concentration that kills the inoculum.",
  why={"The lowest drug concentration that kills all organisms": "That defines the MBC, not the MIC.",
       "The peak drug concentration achieved in a patient's serum": "Serum peak is a pharmacokinetic measure in the patient.",
       "The concentration at which resistance mutations first appear": "That is the mutant prevention concentration.",
       "The dose in milligrams required to treat this infection": "MIC is a concentration, not a dose."}),

# ---------------- hard ----------------
Q(TAG_PRO, "Severe malaria: exchange and artesunate",
  "A patient with falciparum malaria has 15% parasitemia, confusion, and acute kidney injury. Which statement about management is correct?",
  ["Intravenous artesunate is first-line, and delayed hemolysis can follow",
   "Oral artemether-lumefantrine is adequate for this parasitemia",
   "Chloroquine should be given because it acts fastest in severe disease",
   "Exchange transfusion is now proven to reduce mortality in all cases",
   "Corticosteroids improve outcomes in cerebral malaria significantly"],
  "IV artesunate is first-line for severe malaria and reduces mortality compared with quinine. Post-artesunate delayed hemolysis can occur 1-3 weeks later, so hemoglobin is monitored after discharge. Exchange transfusion is no longer routinely recommended, and corticosteroids worsen outcomes in cerebral malaria. Oral therapy follows once the patient can take it.",
  difficulty="hard",
  why={"Oral artemether-lumefantrine is adequate": "Severe disease requires parenteral therapy.",
       "Chloroquine should be given": "Falciparum is widely chloroquine-resistant.",
       "Exchange transfusion is now proven to reduce mortality": "Evidence has not supported routine exchange transfusion.",
       "Corticosteroids improve outcomes in cerebral malaria": "Trials showed steroids prolong coma and increase complications."},
  table=MALARIA),

Q(TAG_HEL, "Eosinophilia workup in a traveler",
  "A traveler returning from Southeast Asia has eosinophilia of 2,400/microliter and no symptoms. Which statement about evaluation is correct?",
  ["Serology plus stool studies are needed, since stool alone often misses infection",
   "A single stool ova and parasite examination reliably excludes helminths",
   "Eosinophilia this high is almost always caused by protozoal infection",
   "Empiric albendazole should be given before any diagnostic testing",
   "Eosinophilia in travelers is nearly always an allergic drug reaction"],
  "Tissue-invasive helminths cause eosinophilia, while protozoa generally do not. A single stool examination is insensitive because shedding is intermittent and some parasites (Strongyloides, schistosomes early on, filariae, Trichinella) are poorly detected in stool, so serology is added and stool studies are repeated. Other causes include drugs, atopy, and hypereosinophilic syndromes.",
  difficulty="hard",
  why={"A single stool ova and parasite examination reliably excludes helminths": "Sensitivity is poor with one specimen.",
       "Eosinophilia this high is almost always caused by protozoal infection": "Protozoa typically do not cause eosinophilia.",
       "Empiric albendazole should be given before any diagnostic testing": "Empiric therapy can be dangerous, as in heavy Loa loa infection.",
       "Eosinophilia in travelers is nearly always an allergic drug reaction": "Parasitic infection must be excluded first."},
  table=NEMATODES),

Q(TAG_SYS, "Post-transplant infection timeline",
  "A solid organ transplant recipient develops infection one month after surgery. Which type of infection is most likely at this stage?",
  ["Surgical site, catheter, and hospital-acquired bacterial infection",
   "Opportunistic infection such as CMV or Pneumocystis pneumonia",
   "Community-acquired pneumonia from respiratory viruses only",
   "Late Epstein-Barr virus lymphoproliferative disease",
   "Chronic hepatitis C infection acquired from the donor organ"],
  "The post-transplant timeline is useful: in the first month, infections are mostly surgical, catheter-related, and nosocomial, similar to any postoperative patient. From 1-6 months, when immunosuppression is heaviest, opportunistic infections such as CMV, Pneumocystis, Aspergillus, and reactivated TB predominate. After 6 months, community-acquired infections and late opportunistic disease including PTLD are more common.",
  difficulty="hard",
  why={"Opportunistic infection such as CMV or Pneumocystis": "Those cluster in the 1-6 month window.",
       "Community-acquired pneumonia from respiratory viruses only": "Community pathogens dominate after 6 months.",
       "Late Epstein-Barr virus lymphoproliferative disease": "PTLD typically appears later.",
       "Chronic hepatitis C infection acquired from the donor organ": "Donor-derived hepatitis presents over a longer course."},
  table=IMMUNODEF),

Q(TAG_LAB, "Antibiogram interpretation",
  "A hospital antibiogram shows that 82% of E. coli isolates are susceptible to ciprofloxacin. How should this information be used?",
  ["To guide empiric therapy before individual susceptibilities return",
   "To confirm that a specific patient's isolate is susceptible",
   "To determine the correct antibiotic dose for each patient",
   "To establish which organism is causing a given infection",
   "To decide how long each patient's therapy should continue"],
  "An antibiogram summarizes local susceptibility patterns and is used to choose empiric therapy before culture results return. It cannot predict an individual isolate's susceptibility, identify the organism, or set dose and duration. Antibiograms also track resistance trends and support stewardship decisions.",
  difficulty="hard",
  why={"To confirm that a specific patient's isolate is susceptible": "Only individual testing can do that.",
       "To determine the correct antibiotic dose": "Dosing depends on the patient, site, and drug pharmacology.",
       "To establish which organism is causing a given infection": "Antibiograms assume the organism is already known.",
       "To decide how long each patient's therapy should continue": "Duration is determined by syndrome and response."}),

Q(TAG_SYS, "Necrotizing fasciitis recognition",
  "A patient has severe leg pain out of proportion to findings, rapidly advancing erythema, and systemic toxicity. Laboratory studies show marked leukocytosis and a rising creatine kinase. What is the most important next step?",
  ["Urgent surgical exploration, since imaging should not delay it",
   "MRI of the leg before any surgical consultation is obtained",
   "Observation on intravenous antibiotics for twenty-four hours",
   "Ultrasound-guided aspiration with outpatient follow-up",
   "Compression bandaging with elevation of the affected limb"],
  "Necrotizing soft tissue infection is a surgical emergency, and survival depends on early, aggressive debridement. Pain out of proportion, rapid progression, systemic toxicity, bullae, crepitus, or skin anesthesia should prompt immediate surgical consultation; imaging must not delay operation. Broad-spectrum antibiotics including clindamycin are given, but debridement is the definitive treatment.",
  difficulty="hard",
  why={"MRI of the leg before any surgical consultation": "Imaging delays the operation that determines survival.",
       "Observation on intravenous antibiotics for twenty-four hours": "Antibiotics alone cannot penetrate necrotic, avascular tissue.",
       "Ultrasound-guided aspiration with outpatient follow-up": "Outpatient management of this condition is unsafe.",
       "Compression bandaging with elevation": "Compression does not address the underlying necrosis."}),
]
