"""Staphylococci in depth: S. aureus virulence, syndromes, lab, and treatment; coagulase-negative species."""
from qcore import Q
from tables import *
TAG_GPC = "Gram+ Cocci"
TAG_ABX = "Antibacterial Drugs"
QUESTIONS = [
# ---------------- S. aureus: identification ----------------
Q(TAG_GPC, "S. aureus: coagulase & clumping factor",
  "Colonies from a wound culture are catalase-positive Gram-positive cocci in clusters. A tube of rabbit plasma inoculated with the organism forms a clot within four hours. Which enzyme does this test detect?",
  ["An enzyme that converts fibrinogen to fibrin",
   "An enzyme that splits hydrogen peroxide into oxygen",
   "An enzyme that hydrolyzes urea into ammonia",
   "An enzyme that degrades hyaluronic acid in tissue",
   "An enzyme that converts plasminogen to plasmin"],
  "Coagulase (free coagulase detected in the tube test, and bound clumping factor detected on a slide) converts fibrinogen to fibrin. It is the classic marker that separates S. aureus from the coagulase-negative staphylococci. The fibrin coat is thought to shield the organism from phagocytosis and helps wall off abscesses.",
  difficulty="easy",
  why={"An enzyme that splits hydrogen peroxide": "That is catalase, which all staphylococci make, so it cannot separate the species.",
       "An enzyme that hydrolyzes urea": "Urease is positive in S. saprophyticus and Proteus but is not detected with plasma.",
       "An enzyme that degrades hyaluronic acid": "Hyaluronidase is a spreading factor and has no clotting effect.",
       "An enzyme that converts plasminogen": "That is staphylokinase or streptokinase, which dissolves clots rather than forming them."},
  table=STAPH),

Q(TAG_GPC, "S. aureus: mannitol salt agar",
  "A nasal swab is plated on a medium containing 7.5% sodium chloride and a sugar with a pH indicator. Yellow colonies grow surrounded by yellow medium. Which organism is most likely?",
  ["Staphylococcus aureus",
   "Staphylococcus epidermidis",
   "Streptococcus pyogenes",
   "Enterococcus faecalis",
   "Micrococcus luteus"],
  "Mannitol salt agar is selective (high salt inhibits most organisms except staphylococci) and differential (mannitol fermentation acidifies the medium and turns the phenol red indicator yellow). S. aureus ferments mannitol; S. epidermidis grows but leaves the medium pink-red. It is commonly used to screen nasal swabs for carriage.",
  difficulty="easy",
  why={"Staphylococcus epidermidis": "It tolerates salt but does not ferment mannitol, so the medium stays red.",
       "Streptococcus pyogenes": "Streptococci are inhibited by 7.5% salt.",
       "Enterococcus faecalis": "Enterococci tolerate 6.5% salt but are not the organism this medium is designed to detect, and they usually fail to grow well at 7.5%.",
       "Micrococcus luteus": "Micrococcus grows as yellow-pigmented colonies but does not ferment mannitol."},
  table=STAPH),

Q(TAG_GPC, "S. aureus: golden pigment",
  "The characteristic golden color of S. aureus colonies comes from staphyloxanthin. What is the main survival advantage of this pigment?",
  ["It protects the cell against oxidant killing by neutrophils",
   "It binds the Fc region of antibodies and blocks opsonization",
   "It lyses red cells and gives beta-hemolysis on blood agar",
   "It degrades DNA in neutrophil extracellular traps",
   "It anchors the organism to fibronectin on host tissue"],
  "Staphyloxanthin is a carotenoid antioxidant that quenches reactive oxygen species. Mutants without the pigment are killed more readily by neutrophil oxidative burst. This pairs with catalase, which destroys hydrogen peroxide, as the organism's defense against phagocyte killing.",
  difficulty="hard",
  why={"It binds the Fc region": "Fc binding is the function of protein A.",
       "It lyses red cells": "Hemolysis is caused by alpha toxin and other hemolysins.",
       "It degrades DNA": "Nuclease (thermonuclease) degrades NETs.",
       "It anchors the organism to fibronectin": "Fibronectin-binding proteins are surface adhesins, not pigments."}),

# ---------------- S. aureus: virulence factors ----------------
Q(TAG_GPC, "S. aureus: Panton-Valentine leukocidin",
  "A previously healthy 19-year-old wrestler develops multiple recurrent furuncles, then a severe necrotizing pneumonia with hemoptysis after influenza. The isolate is methicillin-resistant and carries the lukS-lukF genes. What does this toxin do?",
  ["Forms pores that lyse neutrophils and macrophages",
   "Cleaves desmoglein 1 in the superficial epidermis",
   "Crosslinks MHC class II with T-cell receptors",
   "ADP-ribosylates elongation factor 2 in host cells",
   "Cleaves SNARE proteins at the neuromuscular junction"],
  "Panton-Valentine leukocidin is a two-component pore-forming toxin that kills leukocytes. It is strongly associated with community-acquired MRSA (the USA300 lineage), recurrent skin abscesses, and necrotizing pneumonia after influenza. Toxin-suppressing agents such as clindamycin or linezolid are often added in severe disease.",
  why={"Cleaves desmoglein 1": "That is exfoliative toxin, which causes scalded skin syndrome.",
       "Crosslinks MHC class II": "That is the superantigen mechanism of TSST-1 and enterotoxins.",
       "ADP-ribosylates elongation factor 2": "That is diphtheria toxin and Pseudomonas exotoxin A.",
       "Cleaves SNARE proteins": "That is botulinum and tetanus toxin."},
  table=TOXINS),

Q(TAG_GPC, "S. aureus: alpha toxin",
  "Which S. aureus toxin is a heptameric pore former that binds ADAM10 on epithelial and endothelial cells and is the main cause of beta-hemolysis on blood agar?",
  ["Alpha-hemolysin",
   "Exfoliative toxin A",
   "Enterotoxin B",
   "Toxic shock syndrome toxin",
   "Staphylokinase"],
  "Alpha toxin (alpha-hemolysin) assembles into a heptameric pore after binding its receptor ADAM10. It damages epithelium, endothelium, platelets, and red cells, contributing to pneumonia, skin necrosis, and hemolysis on blood agar.",
  difficulty="hard",
  why={"Exfoliative toxin A": "This is a serine protease targeting desmoglein 1, not a pore.",
       "Enterotoxin B": "Enterotoxins are superantigens that cause vomiting.",
       "Toxic shock syndrome toxin": "TSST-1 is a superantigen, not a membrane pore.",
       "Staphylokinase": "Staphylokinase activates plasminogen and does not lyse cells."},
  table=TOXINS),

Q(TAG_GPC, "S. aureus: protein A & opsonization",
  "An investigator deletes the spa gene from S. aureus and finds the mutant is phagocytosed far more efficiently by neutrophils in the presence of immune serum. What did the deleted protein normally do?",
  ["Bound IgG by its Fc region in the wrong orientation",
   "Cleaved IgA at the hinge region on mucosal surfaces",
   "Degraded complement C5a to block neutrophil chemotaxis",
   "Formed a polysaccharide capsule of hyaluronic acid",
   "Inactivated hydrogen peroxide inside the phagosome"],
  "Protein A is a cell wall protein that binds the Fc portion of IgG. Antibodies are held upside down, so their Fc cannot engage neutrophil Fc receptors or activate complement efficiently. The result is impaired opsonization and phagocytosis.",
  why={"Cleaved IgA at the hinge": "IgA protease is made by Neisseria, H. influenzae, and pneumococcus.",
       "Degraded complement C5a": "C5a peptidase is a virulence factor of S. pyogenes.",
       "Formed a polysaccharide capsule of hyaluronic": "A hyaluronic acid capsule belongs to S. pyogenes.",
       "Inactivated hydrogen peroxide": "That is catalase, encoded by a different gene."},
  table=STAPH),

Q(TAG_GPC, "S. aureus: enterotoxin heat stability",
  "Eleven guests at a picnic develop severe vomiting and abdominal cramps about three hours after eating a cream-filled pastry that had been left out in the sun. Reheating the pastry would not have prevented illness. Why not?",
  ["The preformed toxin survives heat that kills the bacteria",
   "The spores survive boiling and germinate in the intestine",
   "The organism grows best at refrigerator temperatures",
   "The toxin forms only after the food has been eaten",
   "The organism invades the gut wall before heating matters"],
  "Staphylococcal enterotoxins are preformed in food held at room temperature and are heat-stable, so cooking kills the organisms but not the toxin. Illness begins 1-6 hours after ingestion with vomiting and cramps and resolves within a day. The toxin acts as a superantigen and on the vagus/emetic center.",
  difficulty="easy",
  why={"The spores survive boiling": "S. aureus does not form spores; that describes Bacillus and Clostridium.",
       "The organism grows best at refrigerator": "Cold growth is typical of Listeria and Yersinia.",
       "The toxin forms only after the food": "In-gut toxin production gives a longer incubation, as with C. perfringens.",
       "The organism invades the gut wall": "This is an intoxication with no invasion."},
  table=DIARRHEA),

Q(TAG_GPC, "S. aureus: exfoliative toxin target",
  "A 3-year-old has fever, diffuse tender erythema, and large flaccid bullae that slough with gentle pressure. The oral mucosa is spared. Biopsy shows a split in the granular layer. Which host protein is the toxin's target?",
  ["Desmoglein 1",
   "Desmoglein 3",
   "Type XVII collagen",
   "Type VII collagen",
   "Keratin 14"],
  "Exfoliative toxins A and B are serine proteases that cleave desmoglein 1, which holds keratinocytes together in the superficial epidermis (stratum granulosum). Mucosa is spared because it relies on desmoglein 3. The toxin is produced at a distant focus, so the bullae are usually culture-negative. The same target is attacked by autoantibodies in pemphigus foliaceus.",
  why={"Desmoglein 3": "Desmoglein 3 is targeted in pemphigus vulgaris, which involves mucosa.",
       "Type XVII collagen": "BP180 is the target in bullous pemphigoid, a subepidermal split.",
       "Type VII collagen": "Anchoring fibril collagen is affected in epidermolysis bullosa acquisita.",
       "Keratin 14": "Keratin mutations cause epidermolysis bullosa simplex."}),

# ---------------- S. aureus: clinical syndromes ----------------
Q(TAG_GPC, "S. aureus: post-influenza pneumonia",
  "A 45-year-old woman recovering from influenza develops high fever, rigors, and hypoxia. Chest CT shows multiple thick-walled cavities. Sputum shows Gram-positive cocci in clusters. Which organism is most likely?",
  ["Staphylococcus aureus",
   "Streptococcus pneumoniae",
   "Streptococcus pyogenes",
   "Enterococcus faecalis",
   "Streptococcus agalactiae"],
  "Influenza damages respiratory epithelium and impairs neutrophil function, predisposing to secondary bacterial pneumonia. S. aureus, including PVL-positive MRSA, causes a necrotizing, cavitary pneumonia after influenza. Pneumococcus remains the most common secondary pathogen overall but forms lancet-shaped diplococci, not clusters.",
  difficulty="easy",
  why={"Streptococcus pneumoniae": "Pneumococci are lancet-shaped diplococci, and cavitation is uncommon.",
       "Streptococcus pyogenes": "Group A strep grows in chains, although it can also follow influenza.",
       "Enterococcus faecalis": "Enterococci rarely cause pneumonia.",
       "Streptococcus agalactiae": "Group B strep grows in chains and mainly affects neonates and diabetics."}),

Q(TAG_GPC, "S. aureus: septic arthritis in adults",
  "A 70-year-old man with rheumatoid arthritis and a prosthesis-free knee has an acutely hot, swollen knee. Synovial fluid shows 85,000 white cells/µL with 95% neutrophils and no crystals. Which organism is the most common cause in this setting?",
  ["Staphylococcus aureus",
   "Neisseria gonorrhoeae",
   "Pseudomonas aeruginosa",
   "Salmonella species",
   "Borrelia burgdorferi"],
  "S. aureus is the most common cause of non-gonococcal septic arthritis, and rheumatoid arthritis is a major risk factor. Gonococcal arthritis mainly affects young sexually active adults and often has tenosynovitis and pustular skin lesions. Treatment is joint drainage plus antibiotics covering S. aureus.",
  difficulty="easy",
  why={"Neisseria gonorrhoeae": "Gonococcal arthritis is typical of young sexually active adults.",
       "Pseudomonas aeruginosa": "Pseudomonas joint infection is linked to injection drug use and puncture wounds.",
       "Salmonella species": "Salmonella causes osteomyelitis in sickle cell disease.",
       "Borrelia burgdorferi": "Lyme arthritis gives a large effusion with lower cell counts and a slower onset."}),

Q(TAG_GPC, "S. aureus: vertebral osteomyelitis & epidural abscess",
  "A 52-year-old man who injects drugs has two weeks of worsening back pain and fever, and now has leg weakness and urinary retention. MRI shows discitis with an epidural collection. Which organism is most likely, and what is the priority?",
  ["S. aureus; urgent surgical decompression and antibiotics",
   "M. tuberculosis; four-drug therapy before any surgery",
   "E. coli; oral ciprofloxacin and outpatient follow-up",
   "Brucella; doxycycline with rifampin for six weeks",
   "Candida; fluconazole alone with repeat imaging in a month"],
  "S. aureus causes most cases of hematogenous vertebral osteomyelitis and spinal epidural abscess, particularly in people who inject drugs. New neurologic deficits indicate cord compression and require urgent decompression along with intravenous antibiotics covering MRSA.",
  difficulty="medium",
  why={"M. tuberculosis": "Pott disease is more indolent and does not explain an acute bacterial abscess.",
       "E. coli; oral ciprofloxacin": "Gram-negative spinal infection occurs after urinary sources and still requires IV therapy.",
       "Brucella; doxycycline": "Brucellar spondylitis follows animal or dairy exposure.",
       "Candida; fluconazole": "Fungal discitis is rare and still needs decompression with cord compression."}),

Q(TAG_GPC, "S. aureus: bacteremia workup",
  "A 60-year-old man has two of two blood cultures growing methicillin-susceptible S. aureus. The source appears to be a peripheral IV line that has been removed. Which next step is essential?",
  ["Echocardiography to look for endocarditis",
   "Repeat cultures only if a fever recurs",
   "Discharge on two weeks of oral amoxicillin",
   "Treat as a skin contaminant and observe",
   "Start oral metronidazole for anaerobes"],
  "S. aureus in the blood is never dismissed as a contaminant. Management includes source removal, repeat blood cultures until clearance, echocardiography (transthoracic, often transesophageal) to exclude endocarditis, and intravenous anti-staphylococcal therapy, usually cefazolin or nafcillin for MSSA, for at least 14 days.",
  why={"Repeat cultures only if a fever recurs": "Clearance must be documented with repeat cultures regardless of symptoms.",
       "Discharge on two weeks of oral amoxicillin": "Amoxicillin is destroyed by staphylococcal penicillinase.",
       "Treat as a skin contaminant": "S. aureus bacteremia is always treated as real.",
       "Start oral metronidazole": "Metronidazole has no activity against S. aureus."}),

Q(TAG_ABX, "MSSA bacteremia: drug choice",
  "Blood cultures from a patient with S. aureus bacteremia show susceptibility to oxacillin. The patient has no drug allergies and was started empirically on vancomycin. What is the best change?",
  ["Switch to cefazolin",
   "Continue vancomycin alone",
   "Switch to oral linezolid",
   "Add gentamicin for synergy",
   "Switch to ceftazidime"],
  "For methicillin-susceptible S. aureus, anti-staphylococcal beta-lactams (cefazolin, nafcillin, oxacillin) clear bacteremia faster and lower mortality compared with vancomycin. Vancomycin is reserved for MRSA or serious beta-lactam allergy. Adding gentamicin increases kidney injury without improving outcomes.",
  why={"Continue vancomycin alone": "Vancomycin is inferior to beta-lactams for MSSA.",
       "Switch to oral linezolid": "Linezolid is bacteriostatic and not first-line for bacteremia.",
       "Add gentamicin for synergy": "Gentamicin adds nephrotoxicity without benefit in native-valve disease.",
       "Switch to ceftazidime": "Ceftazidime has weak Gram-positive activity."},
  table=CEPHS),

Q(TAG_ABX, "Daptomycin: failure in pneumonia",
  "A patient with MRSA bacteremia improves on daptomycin, but then develops MRSA pneumonia while still on the drug. Why is daptomycin a poor choice for pneumonia?",
  ["It is inactivated by pulmonary surfactant",
   "It cannot cross cell membranes to reach bacteria",
   "It is excreted unchanged into the bile",
   "It only acts on Gram-negative organisms",
   "It antagonizes the effect of vancomycin"],
  "Daptomycin is a lipopeptide that inserts into Gram-positive membranes, causing depolarization. Surfactant binds and inactivates it, so it fails in pneumonia. It is used for MRSA bacteremia and right-sided endocarditis, and its main adverse effect is myopathy with elevated CK.",
  why={"It cannot cross cell membranes": "It acts on the bacterial membrane directly.",
       "It is excreted unchanged into the bile": "Daptomycin is renally cleared.",
       "It only acts on Gram-negative": "It acts only on Gram-positive organisms.",
       "It antagonizes the effect of vancomycin": "There is no such antagonism, and pneumonia failure has a different cause."}),

Q(TAG_ABX, "MRSA: oral options for skin infection",
  "A 25-year-old has a drained abscess on the thigh and surrounding cellulitis. Culture grows MRSA. Which oral agent is appropriate?",
  ["Doxycycline",
   "Amoxicillin-clavulanate",
   "Cephalexin",
   "Dicloxacillin",
   "Penicillin V"],
  "Community MRSA skin infections are usually susceptible to doxycycline, TMP-SMX, and often clindamycin. Linezolid is another option. All beta-lactams except ceftaroline fail against MRSA because PBP2a has low affinity for them.",
  difficulty="easy",
  why={"Amoxicillin-clavulanate": "Clavulanate blocks penicillinase but not PBP2a-mediated resistance.",
       "Cephalexin": "First-generation cephalosporins do not bind PBP2a.",
       "Dicloxacillin": "Dicloxacillin is inactive against methicillin-resistant strains by definition.",
       "Penicillin V": "Nearly all S. aureus make penicillinase."},
  table=CELL_WALL),

Q(TAG_ABX, "Ceftaroline: MRSA activity",
  "Which cephalosporin binds PBP2a and is therefore active against methicillin-resistant S. aureus?",
  ["Ceftaroline",
   "Ceftriaxone",
   "Cefoperazone",
   "Cefazolin",
   "Cefoxitin"],
  "Ceftaroline is sometimes called a fifth-generation cephalosporin. It has high affinity for PBP2a and treats MRSA skin infections and community pneumonia. It keeps broad Gram-negative activity but does not cover Pseudomonas.",
  difficulty="easy",
  why={"Ceftriaxone": "Third-generation cephalosporins do not bind PBP2a.",
       "Cefoperazone": "This third-generation agent covers some Pseudomonas but not MRSA.",
       "Cefazolin": "Cefazolin treats MSSA, not MRSA.",
       "Cefoxitin": "Cefoxitin is used in the lab to detect mecA-mediated resistance, not to treat it."},
  table=CEPHS),

Q(TAG_GPC, "MRSA: laboratory detection",
  "A microbiology lab uses a cefoxitin disk rather than an oxacillin disk to predict methicillin resistance in S. aureus. What does resistance to cefoxitin indicate?",
  ["Presence of mecA, which encodes PBP2a",
   "Presence of blaZ, which encodes penicillinase",
   "Presence of vanA, which alters the wall terminus",
   "Presence of erm, which methylates the ribosome",
   "Presence of a thickened wall that traps drug"],
  "Cefoxitin is a strong inducer of mecA expression and gives a clearer result than oxacillin. Resistance predicts mecA, carried on the SCCmec element, which encodes PBP2a. PCR for mecA or detection of PBP2a by latex agglutination confirms MRSA.",
  difficulty="hard",
  why={"Presence of blaZ": "Penicillinase affects penicillin but not cefoxitin or oxacillin.",
       "Presence of vanA": "vanA causes vancomycin resistance.",
       "Presence of erm": "erm causes macrolide and inducible clindamycin resistance.",
       "Presence of a thickened wall": "A thick wall is the mechanism of VISA."},
  table=RESISTANCE),

Q(TAG_GPC, "S. aureus: decolonization",
  "A patient has had five recurrent MRSA skin abscesses over a year despite appropriate drainage. Nasal swab is positive for MRSA. Which measure reduces recurrences?",
  ["Intranasal mupirocin and chlorhexidine bathing",
   "Long-term daily oral vancomycin for six months",
   "Monthly intramuscular benzathine penicillin",
   "A single dose of oral fluconazole at each relapse",
   "Routine avoidance of all skin contact"],
  "Up to a third of people carry S. aureus in the anterior nares, which serves as a reservoir for recurrent infection. Decolonization uses intranasal mupirocin twice daily for five days plus chlorhexidine washes, along with hygiene measures and not sharing towels or razors.",
  why={"Long-term daily oral vancomycin": "Oral vancomycin is not absorbed and does not reach the nares or skin.",
       "Monthly intramuscular benzathine penicillin": "This prevents rheumatic fever recurrence, not MRSA.",
       "A single dose of oral fluconazole": "Fluconazole is an antifungal.",
       "Routine avoidance of all skin contact": "This is impractical and not recommended."}),

Q(TAG_GPC, "S. aureus: pyomyositis",
  "A 12-year-old boy in a tropical country develops fever and a firm, painful thigh after minor trauma. MRI shows an abscess within the quadriceps muscle. Which organism is most likely?",
  ["Staphylococcus aureus",
   "Clostridium perfringens",
   "Streptococcus pneumoniae",
   "Enterococcus faecium",
   "Staphylococcus epidermidis"],
  "Pyomyositis is a primary bacterial abscess of skeletal muscle, historically called tropical pyomyositis. S. aureus causes about 90% of cases. Risk factors include muscle trauma, HIV, and diabetes. Treatment is drainage plus anti-staphylococcal antibiotics.",
  difficulty="medium",
  why={"Clostridium perfringens": "Gas gangrene causes rapid myonecrosis with crepitus and shock, not a focal abscess.",
       "Streptococcus pneumoniae": "Pneumococcus rarely infects muscle.",
       "Enterococcus faecium": "Enterococci cause urinary, biliary, and endovascular infections.",
       "Staphylococcus epidermidis": "It infects devices, not normal muscle."}),

Q(TAG_GPC, "S. aureus: hyper-IgE syndrome",
  "A 9-year-old has recurrent cold staphylococcal skin abscesses without warmth or redness, recurrent pneumonia with pneumatoceles, retained primary teeth, eczema, and an IgE of 4,000 IU/mL. Which defect explains the susceptibility?",
  ["STAT3 mutation impairing Th17 differentiation",
   "NADPH oxidase deficiency impairing oxidative burst",
   "CD18 deficiency impairing neutrophil adhesion",
   "LYST mutation impairing phagolysosome fusion",
   "Terminal complement deficiency impairing lysis"],
  "Autosomal dominant hyper-IgE (Job) syndrome results from STAT3 mutations. Th17 cells fail to develop, so IL-17-driven neutrophil recruitment is poor and abscesses are 'cold.' The mnemonic FATED covers coarse Facies, cold Abscesses, retained baby Teeth, high IgE, and Dermatologic eczema.",
  difficulty="hard",
  why={"NADPH oxidase deficiency": "Chronic granulomatous disease causes catalase-positive infections with granulomas, not high IgE with retained teeth.",
       "CD18 deficiency": "Leukocyte adhesion deficiency causes delayed cord separation and no pus.",
       "LYST mutation": "Chediak-Higashi syndrome has albinism, neuropathy, and giant granules.",
       "Terminal complement deficiency": "C5-C9 deficiency predisposes to Neisseria."},
  table=IMMUNODEF),

Q(TAG_GPC, "S. aureus: prosthetic joint timing",
  "Six years after a hip replacement, a 74-year-old woman develops sudden fever and a painful hip two weeks after an episode of cellulitis. Which organism most likely seeded the joint?",
  ["Staphylococcus aureus",
   "Cutibacterium acnes",
   "Staphylococcus epidermidis",
   "Corynebacterium striatum",
   "Mycobacterium fortuitum"],
  "Late acute prosthetic joint infection arises from hematogenous seeding of the prosthesis years after surgery, often from skin, urinary, or dental sources. S. aureus is the typical organism and causes abrupt symptoms. Early and delayed infections after surgery are more often coagulase-negative staphylococci or Cutibacterium, which produce indolent pain.",
  difficulty="medium",
  why={"Cutibacterium acnes": "It causes indolent infection, especially of shoulder prostheses, introduced at surgery.",
       "Staphylococcus epidermidis": "It is typically introduced at surgery and causes slow, low-grade infection.",
       "Corynebacterium striatum": "A skin diphtheroid, occasionally a device pathogen, not a typical bacteremic seeder.",
       "Mycobacterium fortuitum": "Rapidly growing mycobacteria cause rare surgical site infections."}),

# ---------------- coagulase-negative staphylococci ----------------
Q(TAG_GPC, "S. epidermidis: novobiocin",
  "Two coagulase-negative staphylococci are isolated: one from the blood of a patient with a ventriculoperitoneal shunt, and one from the urine of a sexually active 20-year-old woman. Which test separates them?",
  ["Novobiocin susceptibility",
   "Optochin disk susceptibility",
   "Bacitracin susceptibility",
   "Bile solubility",
   "Hippurate hydrolysis"],
  "Among coagulase-negative staphylococci, S. epidermidis is novobiocin-sensitive and S. saprophyticus is novobiocin-resistant. Mnemonic: 'On the staph retreat, there's NO StRESS' - Novobiocin: Saprophyticus Resistant, Epidermidis Sensitive.",
  difficulty="easy",
  why={"Optochin disk susceptibility": "Optochin separates pneumococcus from viridans streptococci.",
       "Bacitracin susceptibility": "Bacitracin separates group A from group B streptococci.",
       "Bile solubility": "Bile solubility identifies pneumococcus.",
       "Hippurate hydrolysis": "Hippurate hydrolysis identifies group B streptococci."},
  table=GPC_ALGORITHM),

Q(TAG_GPC, "S. epidermidis: device infection pathogenesis",
  "A patient with a central venous catheter has persistent low-grade bacteremia with S. epidermidis despite vancomycin. Why is this infection hard to clear without removing the device?",
  ["Bacteria in a polysaccharide biofilm resist drugs and phagocytes",
   "The organism hides inside macrophages where vancomycin cannot reach it",
   "The organism has a thick capsule of poly-D-glutamate that blocks complement",
   "The organism produces a superantigen that suppresses antibody formation",
   "The organism switches its surface pili through gene conversion"],
  "S. epidermidis colonizes plastic by producing a biofilm of polysaccharide intercellular adhesin. Bacteria in biofilm grow slowly, are shielded from antibiotics and neutrophils, and repeatedly shed into the blood. Cure usually requires removing the device.",
  why={"The organism hides inside macrophages": "It is an extracellular organism.",
       "The organism has a thick capsule of poly-D-glutamate": "A poly-D-glutamate capsule is unique to B. anthracis.",
       "The organism produces a superantigen": "S. epidermidis is not a superantigen producer.",
       "The organism switches its surface pili": "Pilus gene conversion is a Neisseria gonorrhoeae mechanism."}),

Q(TAG_GPC, "S. epidermidis: single positive culture",
  "In an otherwise stable outpatient without any implanted devices, one of four blood culture bottles grows coagulase-negative staphylococci after 3 days. What is the most likely explanation?",
  ["Contamination from skin during venipuncture",
   "Early infective endocarditis of a native valve",
   "Seeding from an occult vertebral osteomyelitis",
   "Bacteremia from an undiagnosed urinary infection",
   "Reactivation of a latent intracellular infection"],
  "Coagulase-negative staphylococci are the most common blood culture contaminants. One positive bottle out of several, with long time to positivity, in a patient without prosthetic material strongly suggests contamination from skin flora. True infection is supported by multiple positive sets with the same organism and a device or prosthetic valve.",
  difficulty="easy",
  why={"Early infective endocarditis": "Native-valve endocarditis would produce continuous bacteremia with multiple positive sets.",
       "Seeding from an occult vertebral": "S. aureus, not CoNS, causes hematogenous osteomyelitis.",
       "Bacteremia from an undiagnosed urinary": "Urinary sources yield Gram-negative rods.",
       "Reactivation of a latent intracellular": "Staphylococci do not establish latency."}),

Q(TAG_GPC, "S. saprophyticus: adhesion & urease",
  "A 22-year-old woman has dysuria and frequency. Urine culture grows a catalase-positive, coagulase-negative Gram-positive coccus that is urease-positive and novobiocin-resistant. Which statement about this organism is correct?",
  ["It is the second most common cause of cystitis in young women",
   "It is the leading cause of catheter-associated bacteremia in ICUs",
   "It typically causes pyelonephritis in elderly catheterized men",
   "It is usually a contaminant from vaginal flora",
   "It is identified by its sensitivity to optochin"],
  "Staphylococcus saprophyticus is second only to E. coli as a cause of uncomplicated cystitis in young sexually active women. It adheres to uroepithelium and makes urease. Nitrofurantoin or TMP-SMX usually works. Nitrite is often negative because Gram-positive organisms do not reduce nitrate.",
  difficulty="easy",
  why={"It is the leading cause of catheter": "That is S. epidermidis.",
       "It typically causes pyelonephritis in elderly": "Its classic host is young women with cystitis.",
       "It is usually a contaminant": "It is a true pathogen in the urine at significant counts.",
       "It is identified by its sensitivity to optochin": "Optochin is used for pneumococcus."},
  table=STAPH),

Q(TAG_GPC, "S. lugdunensis: aggressive CoNS",
  "A blood culture grows a coagulase-negative staphylococcus that is PYR-positive and ornithine decarboxylase-positive. The patient has a destructive aortic valve infection with a perivalvular abscess. Which species is this?",
  ["Staphylococcus lugdunensis",
   "Staphylococcus saprophyticus",
   "Staphylococcus hominis",
   "Staphylococcus capitis",
   "Staphylococcus haemolyticus"],
  "S. lugdunensis is coagulase-negative but behaves like S. aureus, causing aggressive native-valve endocarditis with abscesses, as well as skin and bone infection. It is identified by PYR and ornithine decarboxylase positivity, and it should never be dismissed as a contaminant.",
  difficulty="hard",
  why={"Staphylococcus saprophyticus": "This is a urinary pathogen and is novobiocin-resistant.",
       "Staphylococcus hominis": "It is a low-virulence skin commensal and a common contaminant.",
       "Staphylococcus capitis": "It is a scalp commensal that occasionally infects devices.",
       "Staphylococcus haemolyticus": "It is a multidrug-resistant commensal, typically of line infections."}),

Q(TAG_GPC, "Staph vs strep: catalase branch logic",
  "A blood culture grows Gram-positive cocci in clusters that are catalase-negative. Which conclusion is most appropriate?",
  ["A streptococcus-like organism is the most likely identity",
   "The organism is S. aureus that has lost its catalase gene",
   "The organism must be an anaerobic coccus from the gut flora",
   "The organism is a coagulase-negative staphylococcus",
   "The organism is Micrococcus and should be discarded"],
  "Staphylococci are catalase-positive, so a catalase-negative Gram-positive coccus is best treated as a streptococcus-like organism (for example Aerococcus or Gemella, which can appear in clusters or tetrads) until identified. Gram stain arrangement can be misleading in broth. MALDI-TOF resolves the identity.",
  difficulty="hard",
  why={"The organism is S. aureus that has lost": "Catalase-negative S. aureus is exceedingly rare.",
       "The organism must be an anaerobic coccus": "Aerobic blood culture growth argues against an obligate anaerobe.",
       "The organism is a coagulase-negative": "All staphylococci, coagulase-positive or not, are catalase-positive.",
       "The organism is Micrococcus": "Micrococcus is catalase-positive."},
  table=GPC_ALGORITHM),

# ---------------- toxins, same concept from other angles ----------------
Q(TAG_GPC, "TSST-1: mechanism from the immunology side",
  "In staphylococcal toxic shock syndrome, a single toxin activates up to 20% of the body's T cells. Which feature explains this?",
  ["It binds MHC II outside the groove and the TCR V-beta region",
   "It is processed into peptides presented in the MHC II groove",
   "It binds CD14 and TLR4 on monocytes as lipopolysaccharide does",
   "It cross-links IgE on mast cells and triggers degranulation",
   "It is presented on MHC I after cytosolic proteasome cleavage"],
  "Superantigens bypass normal antigen processing. They bridge the outside of the MHC class II molecule and the variable beta region of the T-cell receptor, activating every T cell with a matching V-beta family. The resulting massive IL-2, IFN-gamma, and TNF release causes fever, rash, and shock.",
  why={"It is processed into peptides": "Conventional antigens activate only a tiny fraction of T cells.",
       "It binds CD14 and TLR4": "That is the endotoxin pathway of Gram-negative organisms.",
       "It cross-links IgE": "This describes type I hypersensitivity.",
       "It is presented on MHC I": "MHC I presentation drives CD8 cells and is antigen-specific."},
  table=TOXINS),

Q(TAG_GPC, "Toxic shock: diagnosis and desquamation",
  "A 17-year-old has fever of 40°C, hypotension, a diffuse sunburn-like rash, vomiting, and myalgia with elevated CK, during menstruation. Which finding is expected one to two weeks later if she survives?",
  ["Desquamation of the palms and soles",
   "Honey-crusted plaques on the face",
   "Grouped vesicles in a single dermatome",
   "Painless genital chancre with firm edges",
   "Scaly annular plaques with central clearing"],
  "Staphylococcal toxic shock produces fever, hypotension, an erythroderma rash, and involvement of three or more organ systems. Desquamation, especially of the palms and soles, follows in one to two weeks. Management is removal of the source (tampon or packing), fluids, and an anti-staphylococcal drug plus clindamycin.",
  difficulty="easy",
  why={"Honey-crusted plaques": "These describe impetigo.",
       "Grouped vesicles in a single dermatome": "These describe herpes zoster.",
       "Painless genital chancre": "This describes primary syphilis.",
       "Scaly annular plaques": "These describe tinea corporis."},
  table=TOXINS),

Q(TAG_ABX, "Clindamycin in toxin-mediated disease",
  "Why is clindamycin added to a beta-lactam when treating staphylococcal toxic shock syndrome?",
  ["It halts toxin synthesis at the ribosome in any growth phase",
   "It binds and neutralizes circulating toxin in the bloodstream",
   "It kills the organism faster than the beta-lactam alone can",
   "It prevents the organism from forming heat-resistant spores",
   "It enhances beta-lactam entry through the outer membrane"],
  "Clindamycin binds the 50S subunit and halts synthesis of toxins such as TSST-1 and streptococcal pyrogenic exotoxins. Unlike beta-lactams, it works in stationary-phase organisms, which is when high inocula produce most toxin. It does not neutralize toxin that is already circulating; IVIG is sometimes given for that purpose.",
  why={"It binds and neutralizes circulating toxin": "Neutralization is the role of IVIG, not clindamycin.",
       "It kills the organism faster": "Clindamycin is mainly bacteriostatic.",
       "It prevents the organism from forming": "Staphylococci do not form spores.",
       "It enhances beta-lactam entry": "Staphylococci have no outer membrane."},
  table=PROTEIN_SYNTH),

# ---------------- epidemiology / prevention ----------------
Q(TAG_GPC, "S. aureus: surgical site prevention",
  "Before cardiac surgery, patients are screened for nasal S. aureus carriage and decolonized if positive. What is the reason?",
  ["Carriers are at higher risk of infection with their own strain",
   "Carriers are more likely to develop a drug allergy after surgery",
   "Carriage indicates an underlying immune deficiency to treat first",
   "Carriage makes cefazolin prophylaxis contraindicated",
   "Carriers transmit the organism by the airborne route"],
  "Most S. aureus surgical site infections come from the patient's own nasal flora. Preoperative mupirocin and chlorhexidine reduce postoperative S. aureus infection in carriers. Staphylococci spread mainly by contact, especially on hands, not through the air.",
  why={"Carriers are more likely to develop a drug allergy": "Carriage has no effect on drug allergy.",
       "Carriage indicates an underlying immune": "About 30% of healthy people are carriers.",
       "Carriage makes cefazolin prophylaxis contraindicated": "Cefazolin remains standard prophylaxis.",
       "Carriers transmit the organism by the airborne": "Transmission is mainly by contact."}),

Q(TAG_GPC, "S. aureus: food poisoning vs B. cereus",
  "Two outbreaks cause vomiting within 1-6 hours of eating. Outbreak 1 follows ham salad prepared by a cook with a paronychia. Outbreak 2 follows fried rice kept warm overnight. Which feature do the causative toxins share?",
  ["Both are preformed in food and heat-stable",
   "Both are produced after ingestion in the ileum",
   "Both are released only when spores germinate in the gut",
   "Both act by cleaving 60S ribosomal RNA",
   "Both require invasion of colonic epithelial cells"],
  "Staphylococcal enterotoxin (from food handlers) and B. cereus cereulide (emetic toxin, from rice) are both preformed and heat-stable, which is why both cause rapid-onset vomiting. B. cereus also has a diarrheal form from a heat-labile toxin made in the gut, with an 8-16 hour incubation.",
  difficulty="medium",
  why={"Both are produced after ingestion": "Toxin production in the gut gives a longer incubation.",
       "Both are released only when spores": "S. aureus does not form spores.",
       "Both act by cleaving 60S": "That is the mechanism of Shiga and Shiga-like toxin.",
       "Both require invasion": "Neither organism invades in these syndromes."},
  table=DIARRHEA),

Q(TAG_ABX, "Vancomycin: resistance in S. aureus",
  "A patient has persistent MRSA bacteremia with a vancomycin MIC of 4 µg/mL. The isolate has a markedly thickened cell wall but lacks vanA. What is the mechanism of reduced susceptibility?",
  ["Excess D-Ala-D-Ala residues in the wall trap the drug as decoys",
   "A plasmid-encoded enzyme hydrolyzes the glycopeptide structure of vancomycin",
   "The organism substitutes D-Ala-D-Lac for the terminal peptide residues",
   "An efflux pump removes vancomycin from the cytoplasm of the organism",
   "A methylase alters the 23S ribosomal RNA binding site of vancomycin"],
  "Vancomycin-intermediate S. aureus (VISA) accumulates a thickened wall rich in free D-Ala-D-Ala termini that act as decoys and bind vancomycin before it reaches the membrane-level synthesis sites. Full resistance (VRSA) requires acquiring vanA from enterococci, which replaces the terminus with D-Ala-D-Lac.",
  difficulty="hard",
  why={"A plasmid-encoded enzyme hydrolyzes": "Vancomycin is not inactivated enzymatically.",
       "The organism substitutes D-Ala-D-Lac": "That is vanA-mediated full resistance, which this isolate lacks.",
       "An efflux pump removes vancomycin": "Vancomycin acts outside the cytoplasm.",
       "A methylase alters the 23S": "Methylation affects macrolides and clindamycin; vancomycin does not bind ribosomes."},
  table=RESISTANCE),
]
