"""Streptococci and enterococci in depth: groups A and B, pneumococcus, viridans, S. gallolyticus, enterococci."""
from qcore import Q
from tables import *
TAG_GPC = "Gram+ Cocci"
TAG_ABX = "Antibacterial Drugs"
QUESTIONS = [
# ---------------- Group A strep ----------------
Q(TAG_GPC, "S. pyogenes: PYR and bacitracin",
  "A throat swab grows small colonies with a wide zone of complete clearing on sheep blood agar. The organism is catalase-negative. Which pair of results identifies it as group A?",
  ["Bacitracin-sensitive and PYR-positive",
   "Bacitracin-resistant and CAMP-positive",
   "Optochin-sensitive and bile-soluble",
   "Novobiocin-resistant and urease-positive",
   "Bile esculin-positive and salt-tolerant"],
  "Among beta-hemolytic streptococci, group A (S. pyogenes) is bacitracin-sensitive and PYR-positive, while group B is bacitracin-resistant, CAMP-positive, and hippurate-positive. Rapid antigen tests detect the group A carbohydrate directly from the throat.",
  difficulty="easy",
  why={"Bacitracin-resistant and CAMP": "These identify group B strep.",
       "Optochin-sensitive": "These identify pneumococcus, an alpha-hemolytic organism.",
       "Novobiocin-resistant": "These identify S. saprophyticus, a catalase-positive staphylococcus.",
       "Bile esculin-positive": "These identify enterococci."},
  table=GPC_ALGORITHM),

Q(TAG_GPC, "S. pyogenes: Centor and testing",
  "A 9-year-old has fever of 39°C, tonsillar exudates, tender anterior cervical nodes, and no cough. A rapid antigen test is negative. What is the next step?",
  ["Send a throat culture before deciding on treatment",
   "Treat with amoxicillin regardless of any testing",
   "Reassure the family; the negative test excludes it",
   "Order an antistreptolysin O titer from the blood",
   "Obtain a monospot test and treat as viral illness"],
  "Rapid antigen tests are highly specific but only about 85% sensitive. In children and adolescents a negative rapid test is backed up by a throat culture, because missing group A strep risks acute rheumatic fever. In adults, backup culture is usually unnecessary because rheumatic fever is rare.",
  why={"Treat with amoxicillin regardless": "Empiric treatment without confirmation leads to overuse of antibiotics.",
       "Reassure the family": "A negative rapid test in a child can be a false negative.",
       "Order an antistreptolysin O": "ASO rises weeks after infection and does not diagnose acute pharyngitis.",
       "Obtain a monospot test": "Mono is possible, but a strep culture is still needed first."},
  table=STREP),

Q(TAG_GPC, "S. pyogenes: M protein function",
  "Which function of group A streptococcal M protein makes it the organism's main defense against phagocytosis?",
  ["It binds factor H and blocks alternative complement",
   "It binds the Fc region of IgG in reverse orientation",
   "It cleaves IgA at its hinge on mucosal surfaces",
   "It lyses red cells by forming an oxygen-labile pore",
   "It dissolves fibrin clots by activating plasminogen"],
  "M protein recruits factor H and C4b-binding protein to the bacterial surface. This degrades C3b and prevents opsonization. Antibody against a specific M type is protective, but there are more than 200 emm types, so immunity is type-specific and reinfection is common.",
  difficulty="hard",
  why={"It binds the Fc region": "That is protein A of S. aureus.",
       "It cleaves IgA": "IgA protease belongs to Neisseria, Haemophilus, and pneumococcus.",
       "It lyses red cells": "That is streptolysin O.",
       "It dissolves fibrin clots": "That is streptokinase."},
  table=STREP),

Q(TAG_GPC, "S. pyogenes: streptolysin S vs O",
  "Group A strep produces two hemolysins. One is oxygen-labile and immunogenic; the other is oxygen-stable and non-immunogenic. Which statement is correct?",
  ["Streptolysin S is oxygen-stable and non-immunogenic",
   "Streptolysin S raises ASO titers after throat infection",
   "Streptolysin O is oxygen-stable and non-immunogenic",
   "Streptolysin O is responsible for the scarlet fever rash",
   "Streptolysin S is the target of the anti-DNase B test"],
  "Streptolysin O is oxygen-labile (hemolysis is best seen in stabs below the agar surface) and immunogenic, so it produces ASO antibodies. Streptolysin S is oxygen-stable, non-immunogenic, and produces the surface beta-hemolysis. The scarlet fever rash comes from pyrogenic exotoxins.",
  difficulty="hard",
  why={"Streptolysin S raises ASO": "ASO titers are antibodies to streptolysin O.",
       "Streptolysin O is oxygen-stable": "Streptolysin O is oxygen-labile and strongly immunogenic.",
       "Streptolysin O is responsible for the scarlet": "The rash is caused by pyrogenic exotoxins SpeA and SpeC.",
       "Streptolysin S is the target": "Anti-DNase B targets streptococcal DNase."},
  table=STREP),

Q(TAG_GPC, "S. pyogenes: anti-DNase B after skin infection",
  "Three weeks after impetigo, a 7-year-old has cola-colored urine and periorbital edema. His ASO titer is normal. Which test best documents a recent streptococcal infection?",
  ["Anti-DNase B antibody",
   "Blood culture on sheep agar",
   "Throat rapid antigen test",
   "Heterophile antibody test",
   "Anti-hyaluronidase IgE level"],
  "ASO rises reliably after pharyngitis but often stays low after skin infection, because skin lipids bind and inactivate streptolysin O. Anti-DNase B rises after both throat and skin infection, making it the better test for glomerulonephritis following impetigo. Complement C3 is also low.",
  why={"Blood culture": "Post-streptococcal glomerulonephritis is immune-mediated and cultures are negative.",
       "Throat rapid antigen": "The infection was of the skin and has already resolved.",
       "Heterophile antibody": "This detects EBV infection.",
       "Anti-hyaluronidase IgE": "No IgE-based strep test is used clinically."},
  table=GAS_SEQUELAE),

Q(TAG_GPC, "S. pyogenes: PSGN histology",
  "A child with post-streptococcal glomerulonephritis has a kidney biopsy. Which pattern of immune deposits is expected on electron microscopy?",
  ["Subepithelial humps",
   "Subendothelial wire loops",
   "Linear deposits along the GBM",
   "Mesangial IgA deposits only",
   "Effacement of podocytes alone"],
  "Post-streptococcal glomerulonephritis is a type III hypersensitivity: immune complexes form and deposit in the subepithelial space as 'humps', with granular 'lumpy-bumpy' IgG and C3 on immunofluorescence. It follows specific nephritogenic strains after either pharyngitis or skin infection, and children usually recover fully.",
  why={"Subendothelial wire loops": "These are characteristic of lupus nephritis.",
       "Linear deposits along the GBM": "Linear IgG is anti-GBM disease (Goodpasture).",
       "Mesangial IgA": "IgA nephropathy follows mucosal infection within days, not weeks.",
       "Effacement of podocytes alone": "This is minimal change disease."},
  table=GAS_SEQUELAE),

Q(TAG_GPC, "S. pyogenes: rheumatic fever pathogenesis",
  "A 12-year-old develops migratory polyarthritis, a new mitral regurgitation murmur, and subcutaneous nodules three weeks after an untreated sore throat. What is the mechanism of the cardiac injury?",
  ["Antibodies to M protein cross-react with myosin",
   "Bacteria seed the mitral valve and form vegetations",
   "Pyrogenic exotoxin directly kills cardiac myocytes",
   "Immune complexes deposit in the coronary arteries",
   "Streptolysin O forms pores in the valve endothelium"],
  "Acute rheumatic fever is a type II hypersensitivity driven by molecular mimicry: antibodies and T cells raised against M protein cross-react with myosin and valve proteins. Aschoff bodies with Anitschkow cells are seen in the myocardium. It follows pharyngitis only, never skin infection, and treating the pharyngitis within nine days prevents it.",
  why={"Bacteria seed the mitral valve": "Blood cultures are sterile in rheumatic fever; that describes endocarditis.",
       "Pyrogenic exotoxin directly kills": "Exotoxins cause scarlet fever and toxic shock, not carditis.",
       "Immune complexes deposit": "That is type III disease, the mechanism of PSGN.",
       "Streptolysin O forms pores": "Cardiac injury is immune-mediated, not direct toxin damage."},
  table=GAS_SEQUELAE),

Q(TAG_GPC, "Rheumatic fever: secondary prophylaxis",
  "A 14-year-old has had acute rheumatic fever with carditis and residual mitral regurgitation. Which long-term measure prevents recurrence?",
  ["Intramuscular benzathine penicillin G every four weeks",
   "A single dose of amoxicillin before dental procedures",
   "Daily oral aspirin continued for the rest of her life",
   "Oral rifampin twice daily for household close contacts",
   "Tonsillectomy followed by no further antibiotic therapy"],
  "Recurrent group A strep infection can reactivate rheumatic fever and worsen valve damage. Secondary prophylaxis with benzathine penicillin G every 3-4 weeks continues for 10 years or until age 21 (longer with residual valve disease). Oral penicillin V twice daily is an alternative.",
  why={"A single dose of amoxicillin before dental": "That is endocarditis prophylaxis, not prevention of rheumatic fever.",
       "Daily oral aspirin": "Aspirin treats arthritis in the acute attack.",
       "Oral rifampin twice daily": "Rifampin prophylaxis is used for meningococcal contacts.",
       "Tonsillectomy": "Tonsillectomy does not replace antibiotic prophylaxis."},
  table=GAS_SEQUELAE),

Q(TAG_GPC, "S. pyogenes: scarlet fever toxin",
  "A 6-year-old with pharyngitis has a sandpaper-like rash that starts on the neck and spreads, sparing the area around the mouth, with a strawberry tongue and accentuation in skin folds. What produces the rash?",
  ["Pyrogenic exotoxins encoded by a lysogenic phage",
   "Immune complexes against the M protein of the strain",
   "Direct bacterial invasion of the dermal capillaries",
   "Streptolysin O released from bacteria in the throat",
   "Lipoteichoic acid binding to TLR2 in the dermis"],
  "Streptococcal pyrogenic exotoxins (SpeA, SpeC) are superantigens encoded by bacteriophage genes. They cause the diffuse sandpaper rash, circumoral pallor, Pastia lines in skin folds, and a strawberry tongue, followed by desquamation. Scarlet fever is treated like any strep pharyngitis.",
  difficulty="easy",
  why={"Immune complexes against the M protein": "Immune complexes cause PSGN, not the rash.",
       "Direct bacterial invasion": "Scarlet fever is toxin-mediated; the skin is not infected.",
       "Streptolysin O released": "Streptolysin O is a hemolysin and does not cause rash.",
       "Lipoteichoic acid binding": "This triggers inflammation but not the scarlet fever exanthem."},
  table=GAS_SEQUELAE),

Q(TAG_GPC, "S. pyogenes: spreading factors",
  "Group A strep causes rapidly spreading cellulitis and necrotizing fasciitis. Which pair of enzymes most directly promotes its spread through tissue planes?",
  ["Hyaluronidase and streptokinase",
   "Coagulase and clumping factor",
   "Urease and phospholipase C",
   "Catalase and superoxide dismutase",
   "Neuraminidase and IgA protease"],
  "Hyaluronidase breaks down connective tissue ground substance, streptokinase activates plasminogen to dissolve fibrin barriers, and DNase (streptodornase) thins pus. Together they explain the spreading nature of streptococcal infection, in contrast to the walled-off abscesses of S. aureus.",
  why={"Coagulase and clumping factor": "These S. aureus factors wall infection off, the opposite of spreading.",
       "Urease and phospholipase C": "Urease belongs to Proteus and H. pylori; phospholipase C is C. perfringens alpha toxin.",
       "Catalase and superoxide dismutase": "Streptococci are catalase-negative.",
       "Neuraminidase and IgA protease": "These are pneumococcal and influenza-associated factors."},
  table=STREP),

Q(TAG_GPC, "Necrotizing fasciitis: clinical clue",
  "A 50-year-old with a minor leg abrasion has pain far out of proportion to the mild erythema, rapidly rising lactate, and hypotension. Which finding at surgery confirms the diagnosis?",
  ["Gray necrotic fascia that peels easily off muscle",
   "A localized collection of pus with a fibrous capsule",
   "Normal fascia with inflammation only of the dermis",
   "Well-defined raised borders at the edge of erythema",
   "Lymphatic streaking toward the regional lymph nodes"],
  "Necrotizing fasciitis spreads along the fascia faster than the overlying skin changes, so pain out of proportion is the key early sign. At surgery the fascia is gray and necrotic, 'dishwater' fluid is present, and tissue separates easily with a finger (a positive finger test). Management is emergent debridement, broad-spectrum antibiotics, and clindamycin.",
  why={"A localized collection of pus": "That describes an abscess, which is typically staphylococcal.",
       "Normal fascia with inflammation": "That describes cellulitis.",
       "Well-defined raised borders": "Raised sharply demarcated borders describe erysipelas.",
       "Lymphatic streaking": "Lymphangitis can accompany cellulitis but does not define fasciitis."}),

Q(TAG_GPC, "S. pyogenes: penicillin susceptibility",
  "Why is penicillin still reliably effective against group A streptococci after decades of use, while S. aureus became resistant?",
  ["GAS has never acquired beta-lactamase or altered PBPs",
   "GAS lacks a cell wall target for other drug classes",
   "GAS is intracellular where penicillin concentrates",
   "GAS has an outer membrane that excludes most drugs",
   "GAS is killed faster at high bacterial inocula"],
  "No clinical group A streptococcal isolate resistant to penicillin has been documented. It lacks beta-lactamases and has not acquired low-affinity PBPs. Macrolide resistance does occur, so macrolides are not first-line. At very high inocula penicillin works less well (the Eagle effect), which is one reason clindamycin is added in invasive disease.",
  why={"GAS lacks a cell wall target": "GAS has a typical Gram-positive wall.",
       "GAS is intracellular": "GAS is mainly extracellular.",
       "GAS has an outer membrane": "Outer membranes are a Gram-negative feature.",
       "GAS is killed faster at high": "The opposite is true: the Eagle effect reduces killing at high inocula."}),

Q(TAG_GPC, "PANDAS / Sydenham chorea",
  "A 10-year-old girl develops involuntary, purposeless jerking movements of her face and arms and emotional lability. She had an untreated sore throat four months ago. Which structure is targeted?",
  ["Basal ganglia neurons, by cross-reacting antibodies",
   "Motor end plates, by antibodies to acetylcholine receptors",
   "Anterior horn cells, by direct viral invasion",
   "Myelin sheaths, by antibodies to gangliosides",
   "Cerebellar Purkinje cells, by circulating toxins"],
  "Sydenham chorea is a major Jones criterion and may appear months after pharyngitis, often as the only manifestation. Antibodies to streptococcal antigens cross-react with basal ganglia neurons. It usually resolves over months, but secondary penicillin prophylaxis is still required.",
  difficulty="medium",
  why={"Motor end plates": "That is myasthenia gravis.",
       "Anterior horn cells": "That is poliovirus.",
       "Myelin sheaths": "Anti-ganglioside antibodies occur in Guillain-Barré after Campylobacter.",
       "Cerebellar Purkinje cells": "Paraneoplastic cerebellar degeneration targets Purkinje cells."},
  table=GAS_SEQUELAE),

# ---------------- Group B strep ----------------
Q(TAG_GPC, "S. agalactiae: CAMP test",
  "A beta-hemolytic, catalase-negative coccus from a neonate's blood is streaked perpendicular to S. aureus on blood agar and produces an arrowhead zone of enhanced hemolysis. What does this identify?",
  ["Group B streptococcus",
   "Group A streptococcus",
   "Enterococcus faecalis",
   "Listeria monocytogenes",
   "Viridans streptococcus"],
  "The CAMP factor of group B strep acts together with S. aureus beta-hemolysin to create an arrowhead of enhanced hemolysis. Group B strep is also bacitracin-resistant and hippurate-positive. Listeria can also be CAMP-positive, but it is a Gram-positive rod with tumbling motility.",
  difficulty="easy",
  why={"Group A streptococcus": "Group A is CAMP-negative and bacitracin-sensitive.",
       "Enterococcus faecalis": "Enterococci are usually non-hemolytic and bile esculin-positive.",
       "Listeria monocytogenes": "Listeria is a rod, although it can give a positive CAMP reaction.",
       "Viridans streptococcus": "Viridans strep is alpha-hemolytic."},
  table=STREP),

Q(TAG_GPC, "S. agalactiae: early vs late onset",
  "A 5-week-old infant presents with fever, irritability, and a bulging fontanelle. CSF grows group B strep. The mother's intrapartum antibiotics were given appropriately. Which statement explains this presentation?",
  ["Maternal prophylaxis prevents early-onset disease but not late-onset",
   "Late-onset disease is usually pneumonia acquired during vaginal delivery",
   "The infant must have been infected by a contaminated blood transfusion",
   "Group B strep meningitis occurs only in the first 24 hours of life",
   "Maternal antibiotics cause late disease by selecting resistant flora"],
  "Early-onset GBS disease (days 0-6) is acquired during delivery and presents as sepsis and pneumonia; it is prevented by intrapartum penicillin. Late-onset disease (1 week to 3 months) is often acquired after birth, more often presents as meningitis, and is not prevented by intrapartum prophylaxis.",
  why={"Late-onset disease is usually pneumonia": "Pneumonia and sepsis are typical of early-onset disease.",
       "The infant must have been infected": "Late-onset GBS is acquired from the mother, community, or hospital, not typically transfusion.",
       "Group B strep meningitis occurs only": "Meningitis is actually more common in late-onset disease.",
       "Maternal antibiotics cause late disease": "Penicillin resistance in GBS is not a recognized problem."},
  table=MENINGITIS_AGE),

Q(TAG_GPC, "S. agalactiae: capsule and neonatal risk",
  "Why are infants born before 34 weeks at greater risk of invasive group B strep disease than term infants of colonized mothers?",
  ["Less maternal IgG against the capsule has crossed the placenta",
   "Preterm infants lack the receptors that bind GBS to epithelium",
   "Preterm infants make more complement, which feeds GBS growth",
   "Preterm delivery is always by cesarean, bypassing colonization",
   "Preterm infants have higher IgA levels in their respiratory tract"],
  "Protective anti-capsular IgG crosses the placenta mainly in the third trimester. Preterm infants receive less of it, so the sialic acid-rich polysaccharide capsule of GBS protects the organism from complement-mediated opsonization more effectively. Prematurity, prolonged rupture of membranes, and intrapartum fever are all risk factors.",
  difficulty="hard",
  why={"Preterm infants lack the receptors": "Preterm infants are more, not less, susceptible to adherence.",
       "Preterm infants make more complement": "Neonates, especially preterm infants, have lower complement levels.",
       "Preterm delivery is always by cesarean": "Many preterm deliveries are vaginal.",
       "Preterm infants have higher IgA": "Neonatal IgA levels are low regardless of gestation."}),

Q(TAG_GPC, "S. agalactiae: intrapartum drug choice",
  "A woman at 36 weeks has a positive rectovaginal GBS culture. She reports a remote childhood rash with amoxicillin but no hives, swelling, or anaphylaxis. Which intrapartum regimen is preferred?",
  ["Intravenous cefazolin during labor",
   "Oral azithromycin at the onset of labor",
   "Intravenous vancomycin during labor",
   "No prophylaxis, since she is allergic",
   "Oral cephalexin started immediately"],
  "Penicillin or ampicillin is first choice. For a low-risk penicillin allergy (no anaphylaxis, angioedema, or urticaria), cefazolin is preferred because it reaches high amniotic levels. Clindamycin (if susceptible) or vancomycin is used for high-risk allergies. Prophylaxis must be intravenous and given at least four hours before delivery.",
  difficulty="hard",
  why={"Oral azithromycin": "Oral agents and macrolides are not adequate intrapartum prophylaxis.",
       "Intravenous vancomycin": "Vancomycin is reserved for high-risk allergy with clindamycin-resistant strains.",
       "No prophylaxis, since she is allergic": "Alternatives exist, and omitting prophylaxis raises neonatal risk.",
       "Oral cephalexin started immediately": "Antepartum oral treatment does not prevent colonization at delivery."}),

# ---------------- pneumococcus ----------------
Q(TAG_GPC, "S. pneumoniae: bile solubility and optochin",
  "An alpha-hemolytic, catalase-negative diplococcus from sputum dissolves when sodium deoxycholate is added. What does this confirm, and which other test agrees?",
  ["Pneumococcus; it is also optochin-sensitive",
   "Viridans strep; it is also optochin-resistant",
   "Enterococcus; it also grows in 6.5% salt",
   "Group B strep; it is also hippurate-positive",
   "Group A strep; it is also PYR-positive"],
  "Bile (deoxycholate) activates pneumococcal autolysin, which lyses the cells. Pneumococci are also optochin-sensitive and show umbilicated, 'draughtsman' colonies. Viridans streptococci are bile-insoluble and optochin-resistant.",
  difficulty="easy",
  why={"Viridans strep": "Viridans strep is bile-insoluble.",
       "Enterococcus": "Enterococci are bile-tolerant, not bile-soluble.",
       "Group B strep": "Group B strep is beta-hemolytic.",
       "Group A strep": "Group A strep is beta-hemolytic."},
  table=GPC_ALGORITHM),

Q(TAG_GPC, "S. pneumoniae: quellung reaction",
  "Adding type-specific antiserum to a pneumococcal isolate makes the capsule appear swollen and sharply outlined under the microscope. What is this test used for?",
  ["Identifying the capsular serotype",
   "Measuring penicillin resistance",
   "Detecting the pneumolysin toxin",
   "Quantifying bacterial viability",
   "Confirming beta-lactamase activity"],
  "The quellung (Neufeld) reaction uses anticapsular antibody to identify the capsular type. Pneumococcus has about 100 serotypes, and vaccines target the most invasive ones. The capsule is the main virulence factor because it blocks phagocytosis.",
  why={"Measuring penicillin resistance": "Resistance is measured with MIC testing.",
       "Detecting the pneumolysin toxin": "Pneumolysin is not detected by capsular swelling.",
       "Quantifying bacterial viability": "Viability is measured by colony counts.",
       "Confirming beta-lactamase activity": "Pneumococci resist penicillin by altered PBPs, not beta-lactamase."}),

Q(TAG_GPC, "S. pneumoniae: conjugate vaccine immunology",
  "Why does a pneumococcal conjugate vaccine protect infants when the plain polysaccharide vaccine does not?",
  ["Protein carriers recruit helper T cells to drive class switching and memory",
   "Polysaccharides are digested in the infant gut before they reach lymph nodes",
   "Conjugation removes the capsule so antibodies bind the cell wall instead",
   "Infants lack B cells, so the conjugate activates CD8 T cells for killing",
   "The conjugate contains live attenuated bacteria that colonize the pharynx"],
  "Pure polysaccharides are T-independent antigens: they give weak IgM responses without memory, and children under two respond poorly. Linking the polysaccharide to a protein carrier (such as CRM197, a diphtheria toxoid variant) lets helper T cells recognize carrier peptides and help polysaccharide-specific B cells class-switch to IgG and form memory cells.",
  why={"Polysaccharides are digested": "Vaccines are injected, not swallowed.",
       "Conjugation removes the capsule": "Protection is directed at the capsule itself.",
       "Infants lack B cells": "Infants have B cells; their marginal zone response to T-independent antigens is immature.",
       "The conjugate contains live": "Conjugate vaccines are subunit vaccines, not live."},
  table=VACCINES),

Q(TAG_GPC, "S. pneumoniae: meningitis empiric therapy",
  "A 40-year-old has fever, neck stiffness, and confusion. CSF Gram stain shows Gram-positive diplococci. Which regimen is started, along with dexamethasone?",
  ["Vancomycin plus ceftriaxone",
   "Ampicillin plus gentamicin",
   "Penicillin G alone",
   "Ceftriaxone plus azithromycin",
   "Meropenem plus metronidazole"],
  "Pneumococci resist penicillin through altered penicillin-binding proteins, and some are also less susceptible to ceftriaxone. Empiric meningitis treatment therefore combines vancomycin and ceftriaxone until susceptibilities are known. Dexamethasone given before or with the first dose reduces hearing loss and death in pneumococcal meningitis.",
  why={"Ampicillin plus gentamicin": "This is neonatal or Listeria-directed coverage.",
       "Penicillin G alone": "Resistance is too common to rely on penicillin before susceptibility results.",
       "Ceftriaxone plus azithromycin": "This covers community pneumonia, not resistant meningitis.",
       "Meropenem plus metronidazole": "This is not standard empiric meningitis therapy."},
  table=MENINGITIS_AGE),

Q(TAG_GPC, "S. pneumoniae: penicillin resistance mechanism",
  "A pneumococcal isolate has a penicillin MIC of 4 µg/mL. It produces no beta-lactamase. What is the resistance mechanism, and how did the organism acquire it?",
  ["Mosaic PBP genes acquired by natural transformation",
   "A plasmid beta-lactamase acquired by conjugation",
   "Loss of an outer membrane porin by point mutation",
   "An efflux pump acquired by phage transduction",
   "A methylated ribosome acquired from a transposon"],
  "Pneumococci are naturally competent and take up DNA from related streptococci. Recombination creates mosaic PBP genes that encode low-affinity binding proteins. Beta-lactamase inhibitors do not help because no beta-lactamase is involved.",
  difficulty="hard",
  why={"A plasmid beta-lactamase": "Pneumococci do not produce beta-lactamases.",
       "Loss of an outer membrane porin": "Pneumococci have no outer membrane.",
       "An efflux pump acquired by phage": "Efflux causes macrolide (mef) resistance, not beta-lactam resistance.",
       "A methylated ribosome": "Ribosome methylation (erm) affects macrolides and clindamycin."},
  table=GENETICS),

Q(TAG_GPC, "S. pneumoniae: host risk after splenectomy",
  "A 30-year-old man who had a splenectomy after trauma develops fever and within 12 hours is in shock with purpura and DIC. Which organism is the most common cause?",
  ["Streptococcus pneumoniae",
   "Staphylococcus epidermidis",
   "Enterococcus faecalis",
   "Streptococcus mutans",
   "Streptococcus agalactiae"],
  "Overwhelming post-splenectomy infection is most often caused by pneumococcus, followed by H. influenzae type b and meningococcus. The spleen removes opsonized encapsulated bacteria and produces IgM against polysaccharides. Asplenic patients should receive pneumococcal, meningococcal, and Hib vaccines and carry standby antibiotics.",
  difficulty="easy",
  why={"Staphylococcus epidermidis": "It is not encapsulated in the relevant sense and causes device infections.",
       "Enterococcus faecalis": "Enterococci are not a typical cause of post-splenectomy sepsis.",
       "Streptococcus mutans": "S. mutans causes dental caries and endocarditis.",
       "Streptococcus agalactiae": "GBS affects neonates and older diabetics."},
  table=IMMUNODEF),

Q(TAG_GPC, "S. pneumoniae: urinary antigen",
  "A 72-year-old with community-acquired pneumonia received antibiotics before sputum could be collected. Which test can still identify pneumococcus as the cause?",
  ["Urinary antigen for C-polysaccharide",
   "Cold agglutinin titer in the serum",
   "Acid-fast stain of expectorated sputum",
   "Urinary antigen for Legionella serogroup 1",
   "Heterophile antibody on a blood sample"],
  "The pneumococcal urinary antigen test detects C-polysaccharide and remains positive for days to weeks after antibiotics are started. It is useful when cultures are compromised. The Legionella urinary antigen detects serogroup 1 only.",
  why={"Cold agglutinin titer": "Cold agglutinins suggest Mycoplasma.",
       "Acid-fast stain": "Acid-fast stains detect mycobacteria.",
       "Urinary antigen for Legionella": "This detects Legionella, not pneumococcus.",
       "Heterophile antibody": "This detects EBV."},
  table=ATYPICAL_PNA),

# ---------------- viridans strep & friends ----------------
Q(TAG_GPC, "Viridans strep: dextran and valve adherence",
  "A 45-year-old with mitral valve prolapse has low-grade fevers and weight loss for six weeks after a dental extraction. Blood cultures grow alpha-hemolytic, optochin-resistant cocci. Which property lets this organism adhere to damaged valves?",
  ["Dextran synthesized from sucrose",
   "Protein A binding immunoglobulin",
   "A poly-D-glutamate capsule",
   "Coagulase coating the bacterial surface",
   "Lipoteichoic acid-binding TLR4"],
  "Viridans streptococci such as S. sanguinis and S. mutans make dextrans from sucrose, which let them stick to fibrin-platelet aggregates on damaged valves. They cause subacute endocarditis, typically after dental work, with a slower course than S. aureus. Penicillin or ceftriaxone is standard therapy.",
  why={"Protein A binding immunoglobulin": "Protein A belongs to S. aureus.",
       "A poly-D-glutamate capsule": "This is the capsule of B. anthracis.",
       "Coagulase coating": "Coagulase belongs to S. aureus.",
       "Lipoteichoic acid-binding TLR4": "Lipoteichoic acid signals through TLR2, and it is not an adhesin for valves."},
  table=STREP),

Q(TAG_GPC, "S. anginosus group: abscesses",
  "A 58-year-old has a brain abscess and a separate liver abscess. Aspirates grow small colonies with a caramel odor that are Gram-positive cocci in chains, catalase-negative, and optochin-resistant. Which organism is most likely?",
  ["Streptococcus intermedius",
   "Streptococcus pneumoniae",
   "Streptococcus pyogenes",
   "Streptococcus gallolyticus",
   "Streptococcus agalactiae"],
  "S. intermedius belongs to the S. anginosus (milleri) group - S. anginosus, S. intermedius, and S. constellatus - is a viridans subgroup with a strong tendency to form abscesses in the brain, liver, lungs, and pleura. Cultures often smell of butterscotch or caramel.",
  difficulty="hard",
  why={"Streptococcus pneumoniae": "Pneumococcus is optochin-sensitive and rarely causes liver abscess.",
       "Streptococcus pyogenes": "GAS is beta-hemolytic and spreads rather than forming abscesses.",
       "Streptococcus gallolyticus": "It is linked to colon cancer and endocarditis, not multifocal abscesses.",
       "Streptococcus agalactiae": "GBS is beta-hemolytic and hippurate-positive."},
  table=STREP),

Q(TAG_GPC, "S. gallolyticus: colonoscopy",
  "A 67-year-old man has endocarditis. Blood cultures grow a non-enterococcal group D streptococcus that grows on bile esculin but not in 6.5% salt. Which test should follow his valve workup?",
  ["Colonoscopy",
   "Bronchoscopy",
   "Upper endoscopy",
   "Bone marrow biopsy",
   "Renal ultrasound"],
  "Streptococcus gallolyticus (formerly S. bovis biotype I) bacteremia and endocarditis are strongly associated with colorectal adenomas and carcinoma, so colonoscopy is indicated. It is separated from enterococci by its failure to grow in 6.5% NaCl.",
  difficulty="easy",
  why={"Bronchoscopy": "The association is with colon, not lung, neoplasia.",
       "Upper endoscopy": "Gastric cancer is not the recognized association.",
       "Bone marrow biopsy": "No hematologic malignancy is linked to this organism.",
       "Renal ultrasound": "It is not a urinary pathogen."},
  table=STREP),

Q(TAG_GPC, "Nutritionally variant streptococci",
  "A patient with culture-negative endocarditis has Gram-positive cocci seen in blood culture broth that grow on blood agar only as tiny satellite colonies around a streak of S. aureus. Which organism is most likely?",
  ["Abiotrophia or Granulicatella",
   "Haemophilus influenzae type b",
   "Streptococcus gallolyticus",
   "Enterococcus faecalis",
   "Aerococcus urinae"],
  "Abiotrophia and Granulicatella, the nutritionally variant streptococci, need pyridoxal (vitamin B6) and grow only as satellites near S. aureus or on supplemented media. They cause about 5% of streptococcal endocarditis and are treated like enterococci because relapse is common.",
  difficulty="hard",
  why={"Haemophilus influenzae": "H. influenzae also satellites near S. aureus but is a Gram-negative coccobacillus.",
       "Streptococcus gallolyticus": "It grows readily on standard media.",
       "Enterococcus faecalis": "Enterococci grow readily on standard media.",
       "Aerococcus urinae": "It grows on blood agar without supplementation."}),

# ---------------- enterococci ----------------
Q(TAG_GPC, "Enterococcus: salt and bile growth",
  "A catalase-negative Gram-positive coccus from urine grows in 6.5% NaCl and hydrolyzes esculin in the presence of bile. Which organism is this?",
  ["Enterococcus faecalis",
   "Streptococcus gallolyticus",
   "Streptococcus agalactiae",
   "Staphylococcus saprophyticus",
   "Streptococcus mitis"],
  "Enterococci are hardy: they grow in 6.5% salt, 40% bile, and a wide range of temperatures. Both enterococci and S. gallolyticus are bile esculin-positive, but only enterococci grow in 6.5% salt. Enterococci are also PYR-positive.",
  difficulty="easy",
  why={"Streptococcus gallolyticus": "It is bile esculin-positive but does not grow in 6.5% salt.",
       "Streptococcus agalactiae": "GBS is beta-hemolytic and CAMP-positive.",
       "Staphylococcus saprophyticus": "It is catalase-positive.",
       "Streptococcus mitis": "Viridans strep does not grow in bile or high salt."},
  table=GPC_ALGORITHM),

Q(TAG_GPC, "Enterococcus: intrinsic cephalosporin resistance",
  "A patient on ceftriaxone for pneumonia develops a urinary infection with a Gram-positive coccus that grew through the antibiotic. Why are enterococci intrinsically resistant to cephalosporins?",
  ["Their PBPs bind cephalosporins with low affinity",
   "They produce an extended-spectrum beta-lactamase from a plasmid",
   "Their outer membrane porins exclude cephalosporins",
   "They lack peptidoglycan in the wall",
   "They pump cephalosporins out with efflux systems"],
  "Enterococci carry low-affinity PBPs (such as PBP5) that cephalosporins bind poorly. Cephalosporin use therefore selects for enterococcal superinfection. Mnemonic: LAME organisms are not covered by cephalosporins - Listeria, Atypicals, MRSA (except ceftaroline), and Enterococci.",
  why={"They produce an extended-spectrum": "ESBLs are a Gram-negative mechanism.",
       "Their outer membrane porins": "Enterococci have no outer membrane.",
       "They lack peptidoglycan": "Enterococci have a thick peptidoglycan wall.",
       "They pump cephalosporins out": "Efflux is not the main mechanism of intrinsic cephalosporin resistance."},
  table=CEPHS),

Q(TAG_ABX, "E. faecalis endocarditis: double beta-lactam",
  "A 78-year-old with chronic kidney disease has E. faecalis native valve endocarditis that is ampicillin-susceptible with high-level gentamicin resistance. Which regimen is preferred?",
  ["Ampicillin plus ceftriaxone",
   "Ampicillin plus gentamicin",
   "Ceftriaxone alone",
   "Vancomycin plus rifampin",
   "Nafcillin plus gentamicin"],
  "Ampicillin plus ceftriaxone works synergistically because the two drugs saturate different PBPs. It avoids aminoglycoside nephrotoxicity and still works when there is high-level aminoglycoside resistance. Ceftriaxone alone is inactive against enterococci.",
  difficulty="hard",
  why={"Ampicillin plus gentamicin": "High-level gentamicin resistance abolishes synergy, and the drug is nephrotoxic.",
       "Ceftriaxone alone": "Enterococci are intrinsically resistant to cephalosporins.",
       "Vancomycin plus rifampin": "Vancomycin is inferior when the organism is ampicillin-susceptible.",
       "Nafcillin plus gentamicin": "Nafcillin has poor activity against enterococci."}),

Q(TAG_GPC, "E. faecium vs E. faecalis",
  "Which statement correctly contrasts the two main enterococcal species?",
  ["E. faecium is more often ampicillin- and vancomycin-resistant",
   "E. faecalis is more often ampicillin- and vancomycin-resistant",
   "E. faecium is catalase-positive and E. faecalis is negative",
   "E. faecalis is beta-hemolytic and E. faecium is alpha",
   "E. faecium is found only in the environment, not the gut"],
  "E. faecalis causes most enterococcal infections and is usually ampicillin-susceptible. E. faecium causes fewer infections but accounts for most vancomycin-resistant (VRE) and ampicillin-resistant isolates. VRE infections are treated with linezolid or daptomycin.",
  why={"E. faecalis is more often": "The reverse is true.",
       "E. faecium is catalase-positive": "Both are catalase-negative.",
       "E. faecalis is beta-hemolytic": "Most enterococci are gamma-hemolytic.",
       "E. faecium is found only": "Both species colonize the gut."},
  table=RESISTANCE),

Q(TAG_ABX, "VRE: drug choice for bacteremia",
  "A liver transplant recipient has bacteremia with E. faecium resistant to both ampicillin and vancomycin. Which drug is appropriate?",
  ["Daptomycin",
   "Ceftaroline",
   "Aztreonam",
   "Cefazolin",
   "Polymyxin B"],
  "Options for VRE are daptomycin (preferred for bacteremia, often at high dose) and linezolid. Tigecycline has low blood levels. Ceftaroline and other cephalosporins are inactive against enterococci.",
  why={"Ceftaroline": "Ceftaroline is active against MRSA but not enterococci.",
       "Aztreonam": "Aztreonam acts only on Gram-negative organisms.",
       "Cefazolin": "Enterococci are intrinsically cephalosporin-resistant.",
       "Polymyxin B": "Polymyxins act only on Gram-negative outer membranes."},
  table=RESISTANCE),
]
