"""Gram-positive rods and branching bacteria in depth: Listeria, Corynebacterium, Bacillus, Clostridia, Actinomyces, Nocardia."""
from qcore import Q
from tables import *
TAG_GPR = "Gram+ Rods & Branching"
TAG_ABX = "Antibacterial Drugs"
QUESTIONS = [
# ---------------- Listeria ----------------
Q(TAG_GPR, "Listeria: tumbling motility and cold growth",
  "A Gram-positive rod from a neonate's blood shows end-over-end tumbling motility in a wet mount at room temperature and an umbrella pattern in semisolid agar. It also grows at 4°C. Which organism is this?",
  ["Listeria monocytogenes",
   "Bacillus cereus",
   "Corynebacterium jeikeium",
   "Erysipelothrix rhusiopathiae",
   "Clostridium perfringens"],
  "Listeria is a facultative intracellular Gram-positive rod that is motile at room temperature (tumbling, umbrella pattern) but not at 37°C. It grows in the cold, which lets it multiply in refrigerated foods such as deli meats, soft cheeses, and smoked fish. It is catalase-positive and shows narrow beta-hemolysis.",
  difficulty="easy",
  why={"Bacillus cereus": "B. cereus is a large spore-forming rod and does not grow at 4°C.",
       "Corynebacterium jeikeium": "Corynebacteria are non-motile club-shaped rods.",
       "Erysipelothrix rhusiopathiae": "Erysipelothrix is non-motile and infects handlers of fish and meat.",
       "Clostridium perfringens": "C. perfringens is an anaerobic, non-motile, boxcar-shaped rod."},
  table=GPR),

Q(TAG_GPR, "Listeria: listeriolysin O",
  "After being phagocytosed by a macrophage, Listeria escapes into the cytoplasm. Which factor is required for this escape?",
  ["Listeriolysin O",
   "ActA surface protein",
   "Internalin A",
   "Protein A of S. aureus",
   "Streptolysin S"],
  "Listeriolysin O is a cholesterol-dependent pore-forming toxin that ruptures the phagosome membrane. In the cytoplasm, ActA recruits host Arp2/3 to polymerize actin 'rockets' that propel the bacterium into neighboring cells. Internalin binds E-cadherin to trigger uptake into intestinal and placental cells.",
  why={"ActA surface protein": "ActA drives actin-based motility after the organism reaches the cytoplasm.",
       "Internalin A": "Internalin mediates entry into epithelial cells through E-cadherin.",
       "Protein A of S. aureus": "Protein A binds the Fc region of IgG.",
       "Streptolysin S": "Streptolysin S is a group A streptococcal hemolysin."},
  table=GPR),

Q(TAG_GPR, "Listeria: cell-mediated immunity",
  "Why are patients taking high-dose glucocorticoids or TNF inhibitors at particular risk of Listeria meningitis?",
  ["Clearance needs T cells to activate infected macrophages",
   "Clearance needs complement to lyse the bacteria directly",
   "Clearance needs IgA secreted into the intestinal lumen",
   "Clearance needs eosinophils to release major basic protein",
   "Clearance needs antibody to neutralize a secreted exotoxin"],
  "Listeria lives inside macrophages and spreads directly from cell to cell, so antibody and complement contribute little. Control requires IFN-gamma from Th1 and CD8 cells to activate macrophages. Risk groups include pregnancy, neonates, the elderly, and anyone with impaired cell-mediated immunity.",
  why={"Clearance needs complement": "Complement defects predispose to Neisseria, not Listeria.",
       "Clearance needs IgA": "IgA deficiency does not predispose to listeriosis.",
       "Clearance needs eosinophils": "Eosinophils are directed against helminths.",
       "Clearance needs antibody": "Listeria disease is not driven by a circulating exotoxin."},
  table=IMMUNODEF),

Q(TAG_GPR, "Listeria: pregnancy presentation",
  "A 28-year-old woman at 30 weeks' gestation who ate soft cheese made from unpasteurized milk develops fever and myalgias. Blood cultures grow a Gram-positive rod. What is the major risk?",
  ["Transplacental spread causing fetal loss or preterm sepsis",
   "Acute liver failure caused by a toxin made in the mother's gut",
   "Ascending paralysis caused by antibodies to peripheral myelin",
   "Fetal hydrops caused by arrest of red cell production",
   "Congenital cataracts with a patent ductus arteriosus"],
  "Pregnant women have a much higher risk of listeriosis, and the maternal illness is usually mild. The organism crosses the placenta and can cause miscarriage, stillbirth, preterm labor, or granulomatosis infantiseptica with disseminated microabscesses. Treatment is ampicillin, often with gentamicin.",
  why={"Acute liver failure caused by a toxin": "Hepatic failure from a gut toxin is not a feature of listeriosis.",
       "Ascending paralysis": "Guillain-Barré syndrome follows Campylobacter infection.",
       "Fetal hydrops": "Hydrops fetalis is caused by parvovirus B19.",
       "Congenital cataracts": "These are features of congenital rubella."},
  table=TORCH),

Q(TAG_ABX, "Listeria: cephalosporin gap",
  "A 70-year-old on chemotherapy has meningitis with a Gram-positive rod on CSF Gram stain. He is receiving vancomycin and ceftriaxone. Which drug must be added?",
  ["Ampicillin",
   "Gentamicin alone",
   "Cefepime",
   "Aztreonam",
   "Metronidazole"],
  "Listeria is intrinsically resistant to all cephalosporins, so empiric meningitis therapy in adults over 50, neonates, and immunocompromised patients adds ampicillin. TMP-SMX is the alternative in penicillin allergy. Gentamicin may be added for synergy but is never used alone.",
  difficulty="easy",
  why={"Gentamicin alone": "Aminoglycosides penetrate CSF poorly and are only synergistic.",
       "Cefepime": "Listeria resists every cephalosporin.",
       "Aztreonam": "Aztreonam acts only against Gram-negative organisms.",
       "Metronidazole": "Metronidazole covers anaerobes, and Listeria is facultative."},
  table=MENINGITIS_AGE),

# ---------------- Corynebacterium ----------------
Q(TAG_GPR, "C. diphtheriae: microscopy and media",
  "A throat swab from an unvaccinated child with a gray pharyngeal membrane is stained with methylene blue. Which appearance is expected?",
  ["Club-shaped rods in angular clusters with granules",
   "Chains of spherical cocci surrounded by a clear capsule",
   "Large boxcar-shaped rods with central pale endospores",
   "Branching filaments that fragment into short rods",
   "Curved rods with a single flagellum at one pole"],
  "C. diphtheriae is a club-shaped Gram-positive rod arranged in angular 'Chinese letter' clusters, with metachromatic Babes-Ernst granules of polyphosphate. It grows on Loeffler medium and forms black colonies on cystine-tellurite agar.",
  difficulty="easy",
  why={"Chains of spherical cocci": "This describes streptococci.",
       "Large boxcar-shaped rods": "Boxcar rods with spores describe Bacillus and Clostridium.",
       "Branching filaments": "Branching filaments describe Actinomyces and Nocardia.",
       "Curved rods with a single flagellum": "This describes Vibrio or Campylobacter."},
  table=GPR),

Q(TAG_GPR, "Diphtheria toxin: mechanism",
  "Diphtheria toxin has an A and a B fragment. What does the A fragment do once inside the cell?",
  ["ADP-ribosylates elongation factor 2",
   "ADP-ribosylates the Gs alpha subunit",
   "ADP-ribosylates the Gi alpha subunit",
   "Cleaves 28S ribosomal RNA at one adenine",
   "Blocks release of glycine from interneurons"],
  "Fragment B binds the heparin-binding EGF-like receptor and delivers fragment A, which ADP-ribosylates elongation factor 2 and shuts down host protein synthesis. Local necrosis produces the pseudomembrane, and absorbed toxin causes myocarditis and neuritis. Pseudomonas exotoxin A shares this mechanism.",
  why={"ADP-ribosylates the Gs alpha": "That is cholera toxin and pertussis-related cAMP toxins.",
       "ADP-ribosylates the Gi alpha": "That is pertussis toxin.",
       "Cleaves 28S ribosomal RNA": "That is Shiga and Shiga-like toxin.",
       "Blocks release of glycine": "That is tetanospasmin."},
  table=TOXINS),

Q(TAG_GPR, "Diphtheria: airway and antitoxin timing",
  "A child has a firmly adherent gray membrane over the tonsils that bleeds when scraped, a 'bull neck' from cervical edema, and stridor. What is the most important immediate intervention?",
  ["Give equine antitoxin before culture results return",
   "Give erythromycin and wait for the culture to confirm",
   "Scrape the membrane off to relieve airway obstruction",
   "Give a dose of diphtheria toxoid vaccine immediately",
   "Give corticosteroids alone to reduce cervical edema"],
  "Antitoxin neutralizes only circulating toxin, not toxin already bound to cells, so it is given on clinical suspicion without waiting for confirmation. Antibiotics (erythromycin or penicillin) stop toxin production and transmission but do not replace antitoxin. Airway protection and cardiac monitoring are essential, and the membrane is never scraped because it bleeds and can obstruct.",
  why={"Give erythromycin and wait": "Delay allows more toxin to bind irreversibly.",
       "Scrape the membrane off": "Scraping causes bleeding and can worsen obstruction.",
       "Give a dose of diphtheria toxoid": "Active immunization is too slow for acute disease, though it is needed in convalescence.",
       "Give corticosteroids alone": "Steroids do not neutralize toxin."},
  table=TOXINS),

Q(TAG_GPR, "Diphtheria: carrier vs disease",
  "Which feature determines whether a C. diphtheriae isolate can cause the classic disease?",
  ["Carriage of a lysogenic phage bearing the tox gene",
   "Presence of a capsule made of poly-D-glutamic acid",
   "Ability to grow anaerobically in deep tissue",
   "Ability to ferment mannitol on selective agar",
   "Presence of a type III secretion apparatus"],
  "The tox gene is carried by a lysogenic corynebacteriophage, so only phage-infected strains are toxigenic. Toxin production is repressed by iron through the DtxR regulator and rises when iron is low. The Elek test detects toxin production.",
  why={"Presence of a capsule made of poly-D-glutamic": "That capsule belongs to B. anthracis.",
       "Ability to grow anaerobically": "C. diphtheriae is a facultative anaerobe, and this is not what distinguishes toxigenic strains.",
       "Ability to ferment mannitol": "Mannitol fermentation identifies S. aureus.",
       "Presence of a type III secretion": "Diphtheria toxin is secreted and does not use a type III injectisome."},
  table=GENETICS),

Q(TAG_GPR, "Corynebacterium: non-diphtheriae species",
  "Blood cultures from a neutropenic patient with a tunneled catheter grow a multidrug-resistant, lipophilic Gram-positive rod identified as Corynebacterium jeikeium. What is the appropriate treatment?",
  ["Vancomycin and catheter removal",
   "Penicillin G alone through the catheter",
   "Oral erythromycin as an outpatient",
   "No therapy, since this is skin flora",
   "Metronidazole with catheter retention"],
  "C. jeikeium and other non-diphtherial corynebacteria (diphtheroids) are usually contaminants, but in neutropenic patients with indwelling lines they cause true bacteremia. They are typically resistant to beta-lactams, so vancomycin is the drug of choice, along with line removal.",
  difficulty="hard",
  why={"Penicillin G alone": "These organisms are usually beta-lactam resistant.",
       "Oral erythromycin as an outpatient": "Macrolide resistance is common and the patient needs IV therapy.",
       "No therapy, since this is skin flora": "In a neutropenic patient with a line this is treated as real.",
       "Metronidazole with catheter retention": "Metronidazole has no aerobic Gram-positive activity."}),

Q(TAG_GPR, "Corynebacterium minutissimum: erythrasma",
  "A 55-year-old obese man has well-demarcated red-brown patches in the groin that fluoresce coral-red under a Wood lamp. KOH preparation shows no fungal elements. Which organism is responsible?",
  ["Corynebacterium minutissimum",
   "Trichophyton rubrum, a dermatophyte",
   "Malassezia furfur",
   "Candida albicans",
   "Staphylococcus aureus"],
  "Erythrasma is a superficial infection of skin folds caused by Corynebacterium minutissimum, producing coral-red fluorescence from porphyrins. It mimics tinea cruris but has no fungal hyphae on KOH. Treatment is topical or oral erythromycin or clindamycin.",
  difficulty="hard",
  why={"Trichophyton rubrum, a dermatophyte": "Tinea cruris shows hyphae on KOH and does not fluoresce coral-red.",
       "Malassezia furfur": "Tinea versicolor shows spaghetti-and-meatballs yeast and hyphae.",
       "Candida albicans": "Candidal intertrigo has satellite pustules and shows pseudohyphae.",
       "Staphylococcus aureus": "Staphylococcal skin infection is pustular or crusted."}),

# ---------------- Bacillus ----------------
Q(TAG_GPR, "B. anthracis: capsule and spores",
  "Which combination of features distinguishes Bacillus anthracis from other Bacillus species?",
  ["A poly-D-glutamate capsule and non-motility",
   "A polysaccharide capsule and swarming motility",
   "A lipid A-rich outer membrane and motility",
   "Mycolic acid in the wall and acid-fastness",
   "A sialic acid capsule and cold growth"],
  "B. anthracis is the only Bacillus species with a poly-D-glutamate capsule, and it is non-motile, unlike B. cereus and B. subtilis. The capsule resists phagocytosis and is poorly immunogenic because it is not made of sugars. Spores allow survival in soil for decades.",
  why={"A polysaccharide capsule and swarming": "Its capsule is a polypeptide and the organism is non-motile.",
       "A lipid A-rich outer membrane": "Outer membranes and lipid A belong to Gram-negative organisms.",
       "Mycolic acid in the wall": "Mycolic acids are found in mycobacteria and Nocardia.",
       "A sialic acid capsule and cold growth": "Sialic acid capsules occur in group B strep and E. coli K1."},
  table=GPR),

Q(TAG_GPR, "Anthrax toxins: edema and lethal factor",
  "Anthrax produces a tripartite toxin. Protective antigen delivers two enzymes into the cell. What does each enzyme do?",
  ["One is an adenylyl cyclase; the other cleaves MAP kinase kinase",
   "One is a protease of SNARE proteins; the other blocks Gi signaling",
   "One ADP-ribosylates EF-2; the other cleaves ribosomal RNA",
   "One methylates 23S rRNA; the other phosphorylates CFTR",
   "One activates guanylate cyclase; the other blocks Gs signaling"],
  "Protective antigen forms the pore. Edema factor is a calmodulin-dependent adenylyl cyclase that raises cAMP and causes massive edema. Lethal factor is a zinc metalloprotease that cleaves MAP kinase kinases, killing cells and driving shock. The vaccine targets protective antigen.",
  difficulty="hard",
  why={"One is a protease of SNARE proteins": "SNARE cleavage describes botulinum and tetanus toxins.",
       "One ADP-ribosylates EF-2": "That describes diphtheria toxin and Shiga toxin.",
       "One methylates 23S rRNA": "Ribosomal methylation is an antibiotic resistance mechanism.",
       "One activates guanylate cyclase": "Guanylate cyclase activation describes heat-stable E. coli toxin."},
  table=TOXINS),

Q(TAG_GPR, "Anthrax: cutaneous lesion evolution",
  "A sheep farmer develops a painless papule on the forearm that becomes a vesicle, then ulcerates with a black center and marked surrounding swelling. Which statement about this lesion is correct?",
  ["A lack of pain helps separate it from other skin ulcers",
   "It is exquisitely tender, unlike a staphylococcal boil",
   "It should be surgically excised to prevent dissemination",
   "It heals only after intravenous immunoglobulin is given",
   "It appears months after the exposure to infected animals"],
  "Cutaneous anthrax begins one to seven days after spores enter broken skin and forms a painless ulcer with a black eschar and prominent non-pitting edema from edema toxin. Painlessness is a key clue. Treatment is ciprofloxacin or doxycycline; excision is avoided because it may promote spread.",
  difficulty="medium",
  why={"It is exquisitely tender": "The anthrax eschar is characteristically painless.",
       "It should be surgically excised": "Excision is discouraged and antibiotics are the mainstay.",
       "It heals only after intravenous immunoglobulin": "Antitoxin is reserved for systemic disease, not routine cutaneous cases.",
       "It appears months after the exposure": "Incubation is days, not months."}),

Q(TAG_GPR, "Inhalational anthrax: imaging",
  "A worker at a wool processing plant has two days of fever and malaise, then abrupt respiratory failure and shock. Which chest imaging finding is most characteristic?",
  ["Widened mediastinum with pleural effusions",
   "Upper lobe cavity with surrounding nodules",
   "Diffuse miliary nodules throughout both lungs",
   "A single dense lobar consolidation with air bronchograms",
   "Bilateral hilar calcifications with egg-shell pattern"],
  "Inhaled spores are carried by macrophages to mediastinal lymph nodes, causing hemorrhagic mediastinitis with a widened mediastinum and bloody pleural effusions. There is no true pneumonia. Hemorrhagic meningitis may follow. Treatment combines ciprofloxacin, a protein synthesis inhibitor, and antitoxin.",
  why={"Upper lobe cavity": "Cavitation suggests tuberculosis or S. aureus.",
       "Diffuse miliary nodules": "Miliary nodules suggest disseminated tuberculosis.",
       "A single dense lobar consolidation": "Lobar consolidation suggests pneumococcus.",
       "Bilateral hilar calcifications": "Egg-shell calcification suggests silicosis."}),

Q(TAG_GPR, "B. cereus: two syndromes",
  "Two groups of diners become ill after a buffet. Group 1 vomited within two hours of eating fried rice. Group 2 had watery diarrhea 12 hours after eating meat and vegetables. Which explanation fits both?",
  ["One toxin is preformed in food; the other is made in the gut",
   "Both illnesses come from toxin preformed in the food before cooking",
   "Both illnesses require the organism to invade the intestinal wall",
   "One illness is bacterial and the other is a viral co-infection",
   "One toxin blocks Gi signaling; the other blocks Gs signaling"],
  "B. cereus makes two distinct toxins. Cereulide is preformed in food, heat-stable, and causes vomiting within one to six hours, classically from reheated rice. The heat-labile enterotoxin is produced in the small bowel and causes watery diarrhea after 8 to 16 hours. Both are self-limited and treated with fluids.",
  why={"Both illnesses come from toxin preformed": "The diarrheal form depends on toxin made in the gut.",
       "Both illnesses require the organism to invade": "Neither syndrome is invasive.",
       "One illness is bacterial and the other is a viral": "Both syndromes come from the same organism.",
       "One toxin blocks Gi signaling": "G-protein modification describes pertussis and cholera toxins."},
  table=DIARRHEA),

Q(TAG_GPR, "B. cereus: keratitis and line infection",
  "Besides food poisoning, which other presentations should prompt consideration of Bacillus cereus?",
  ["Contact lens keratitis and catheter-related bacteremia",
   "Cavitary pneumonia and endocarditis of the aortic valve",
   "Pelvic inflammatory disease with perihepatitis",
   "Chronic prostatitis in older diabetic men",
   "Cervical lymphadenitis in young children"],
  "B. cereus also causes severe keratitis, especially in contact lens wearers and after eye trauma, and it causes catheter-related bacteremia in immunocompromised patients. Spores resist disinfection, which explains its role in hospital and ocular infections.",
  difficulty="hard",
  why={"Cavitary pneumonia and endocarditis": "These suggest S. aureus.",
       "Pelvic inflammatory disease": "PID with perihepatitis suggests chlamydia or gonorrhea.",
       "Chronic prostatitis": "Chronic prostatitis is usually caused by Gram-negative rods.",
       "Cervical lymphadenitis in young children": "This suggests nontuberculous mycobacteria or S. aureus."}),

# ---------------- Clostridia ----------------
Q(TAG_GPR, "C. tetani: toxin transport",
  "Tetanospasmin is produced in a contaminated wound but causes rigidity throughout the body. How does it reach the central nervous system?",
  ["Retrograde axonal transport up motor neurons",
   "Passive diffusion across the blood-brain barrier",
   "Transport inside infected circulating macrophages",
   "Spread along the cerebrospinal fluid from the wound",
   "Direct invasion of the spinal cord by the bacteria"],
  "Tetanospasmin binds motor nerve terminals and travels by retrograde axonal transport to the spinal cord, where it moves into inhibitory interneurons. There it cleaves synaptobrevin (a SNARE protein), blocking release of glycine and GABA, so motor neurons fire unopposed. The bacteria stay at the wound.",
  why={"Passive diffusion across the blood-brain barrier": "The toxin is too large and uses axonal transport instead.",
       "Transport inside infected circulating macrophages": "The organism is not intracellular.",
       "Spread along the cerebrospinal fluid": "CSF spread is not the route.",
       "Direct invasion of the spinal cord": "C. tetani remains localized in the wound."},
  table=TOXINS),

Q(TAG_GPR, "Tetanus: clinical signs",
  "A 60-year-old gardener with no vaccination records has trouble opening his mouth, a fixed grimace, and painful arching of the back with a stiff abdomen. Which set of findings fits this illness?",
  ["Trismus and risus sardonicus with a clear sensorium",
   "Descending weakness with dilated pupils and dry mouth",
   "Flaccid paralysis with loss of deep tendon reflexes",
   "Fever with nuchal rigidity and neutrophils in the CSF",
   "Ascending symmetric weakness with high CSF protein"],
  "Tetanus causes trismus (lockjaw), risus sardonicus, opisthotonos, and autonomic instability, with intact sensation and consciousness. Treatment includes wound debridement, metronidazole, tetanus immune globulin, benzodiazepines, and later active immunization, because the disease does not produce immunity.",
  difficulty="easy",
  why={"Descending weakness with dilated pupils": "This describes botulism.",
       "Flaccid paralysis with loss of deep tendon": "Tetanus causes rigidity, not flaccid weakness.",
       "Fever with nuchal rigidity": "That pattern indicates bacterial meningitis.",
       "Ascending symmetric weakness": "That describes Guillain-Barré syndrome."},
  table=CLOSTRIDIA),

Q(TAG_GPR, "Botulinum toxin: same target, opposite effect",
  "Botulinum and tetanus toxins both cleave SNARE proteins, yet one causes flaccid paralysis and the other rigidity. What explains the difference?",
  ["Botulinum acts at the neuromuscular junction; tetanus at interneurons",
   "Botulinum acts at inhibitory interneurons; tetanus at the neuromuscular junction",
   "Botulinum blocks sodium channels while tetanus blocks calcium channels",
   "Botulinum is an endotoxin while tetanus is a secreted exotoxin",
   "Botulinum destroys motor neurons while tetanus destroys sensory neurons"],
  "Both are zinc proteases that cleave SNARE proteins and block vesicle fusion. Botulinum toxin blocks acetylcholine release at the neuromuscular junction and at autonomic synapses, giving flaccid paralysis with dry mouth and dilated pupils. Tetanospasmin blocks inhibitory glycine and GABA release in the spinal cord, giving rigidity and spasms.",
  why={"Botulinum acts at inhibitory interneurons": "The two sites are reversed in this option.",
       "Botulinum blocks sodium channels": "Neither toxin blocks ion channels.",
       "Botulinum is an endotoxin": "Both are exotoxins; these organisms are Gram-positive.",
       "Botulinum destroys motor neurons": "Neither toxin destroys neurons."},
  table=TOXINS),

Q(TAG_GPR, "Infant botulism: source and treatment",
  "A 4-month-old has poor feeding, a weak cry, constipation, and loss of head control. Which combination of source and treatment is correct?",
  ["Ingested spores germinating in the colon; human antitoxin",
   "Preformed toxin in home-canned food; equine-derived antitoxin",
   "A contaminated umbilical stump; penicillin with metronidazole",
   "Ingested spores in honey; aminoglycoside therapy with fluids",
   "Toxin in unpasteurized milk; intravenous immunoglobulin alone"],
  "Infants lack a protective gut microbiome, so ingested spores (classically from honey) germinate and produce toxin in the colon. Treatment is human-derived botulism immune globulin (BabyBIG), not equine antitoxin. Aminoglycosides are avoided because they worsen neuromuscular blockade.",
  why={"Preformed toxin in home-canned food": "Preformed toxin in canned goods causes adult food-borne botulism.",
       "A contaminated umbilical stump": "That describes neonatal tetanus.",
       "Ingested spores in honey; aminoglycoside": "The source is right but aminoglycosides worsen the paralysis.",
       "Toxin in unpasteurized milk": "Unpasteurized milk is linked to Listeria, Brucella, and Campylobacter."},
  table=CLOSTRIDIA),

Q(TAG_GPR, "C. perfringens: alpha toxin",
  "A crush injury to the thigh becomes swollen with crepitus, and the skin has a bronze discoloration with a thin brown discharge. What is the enzymatic action of the responsible toxin?",
  ["A lecithinase that hydrolyzes cell phospholipids",
   "A protease that cleaves desmoglein in the epidermis",
   "A pore-forming protein that binds cholesterol only",
   "A nuclease that degrades host cell DNA in tissue",
   "A superantigen that bridges MHC II and the TCR"],
  "Alpha toxin is a phospholipase C (lecithinase) that destroys cell membranes, causing myonecrosis, hemolysis, and platelet destruction. Gas in tissue comes from fermentation. The Nagler reaction on egg yolk agar demonstrates lecithinase. Management is urgent debridement plus penicillin and clindamycin.",
  why={"A protease that cleaves desmoglein": "That is staphylococcal exfoliative toxin.",
       "A pore-forming protein that binds cholesterol": "That describes listeriolysin O and streptolysin O.",
       "A nuclease that degrades host cell DNA": "DNases thin pus but do not cause myonecrosis.",
       "A superantigen that bridges MHC II": "Superantigens cause toxic shock, not gas gangrene."},
  table=CLOSTRIDIA),

Q(TAG_GPR, "C. perfringens: food poisoning timing",
  "Twenty attendees at a banquet develop watery diarrhea and cramps about 12 hours after eating beef stew that was held on a warm steam table. Vomiting is rare. Which mechanism fits?",
  ["Enterotoxin released as the organisms sporulate in the gut",
   "Preformed heat-stable toxin acting on the vagal emetic center",
   "Invasion of colonic mucosa with bloody inflammatory diarrhea",
   "Cytotoxin that inhibits protein synthesis in the colonic wall",
   "Persistent activation of adenylyl cyclase by an AB5 toxin"],
  "C. perfringens type A food poisoning follows ingestion of large numbers of vegetative cells in meat or gravy. The enterotoxin is released as the organisms sporulate in the small intestine, giving watery diarrhea and cramps at 8-16 hours with little vomiting, resolving within 24 hours.",
  difficulty="medium",
  why={"Preformed heat-stable toxin acting on the vagal": "That mechanism gives vomiting in one to six hours.",
       "Invasion of colonic mucosa": "There is no invasion or blood in the stool.",
       "Cytotoxin that inhibits protein synthesis": "That describes Shiga toxin.",
       "Persistent activation of adenylyl cyclase": "That describes cholera toxin."},
  table=DIARRHEA),

Q(TAG_GPR, "C. difficile: toxins A and B",
  "A patient on clindamycin develops profuse watery diarrhea. Colonoscopy shows yellow-white plaques. Which action explains the mucosal damage?",
  ["Glucosylation of Rho GTPases disrupting the cytoskeleton",
   "ADP-ribosylation of elongation factor 2 halting translation",
   "Cleavage of an adenine from 28S ribosomal RNA",
   "Permanent activation of Gs raising intracellular cAMP",
   "Inactivation of Gi increasing intracellular cAMP"],
  "Toxins A (enterotoxin) and B (cytotoxin) glucosylate Rho-family GTPases, so actin filaments collapse and tight junctions fail. Cells round up and die, producing the pseudomembranes of fibrin, mucin, and neutrophils. Diagnosis uses NAAT for toxin genes or an EIA for toxin with GDH.",
  why={"ADP-ribosylation of elongation factor 2": "That is diphtheria toxin.",
       "Cleavage of an adenine from 28S": "That is Shiga toxin.",
       "Permanent activation of Gs": "That is cholera toxin.",
       "Inactivation of Gi": "That is pertussis toxin."},
  table=TOXINS),

Q(TAG_GPR, "C. difficile: severe disease management",
  "A 78-year-old has C. difficile colitis with a white count of 22,000/µL, creatinine 1.8 times baseline, and marked abdominal distension. Which approach is correct?",
  ["Oral vancomycin, adding intravenous metronidazole for ileus",
   "Oral metronidazole alone, reserving vancomycin for relapse",
   "Intravenous vancomycin, which concentrates in the colonic lumen",
   "Loperamide to slow transit and reduce fluid losses quickly",
   "Fecal microbiota transplantation as initial therapy for all cases"],
  "Oral vancomycin (or fidaxomicin) is first-line for C. difficile, including severe disease, because it is not absorbed and reaches high colonic levels. With ileus or fulminant disease, IV metronidazole is added and vancomycin may be given per rectum. Antimotility agents risk ileus and toxic megacolon. FMT is used for recurrent disease.",
  difficulty="medium",
  why={"Oral metronidazole alone": "Metronidazole is now second-line and inferior in severe disease.",
       "Intravenous vancomycin": "IV vancomycin does not reach the colonic lumen.",
       "Loperamide to slow transit": "Antimotility drugs can precipitate toxic megacolon.",
       "Fecal microbiota transplantation as initial": "FMT is reserved for recurrent infection."}),

Q(TAG_GPR, "C. difficile: recurrence prevention",
  "A patient has had three episodes of C. difficile colitis in six months, each responding to oral vancomycin. Which option best reduces further recurrence?",
  ["Fecal microbiota transplantation",
   "A six-month course of oral metronidazole",
   "Daily oral probiotics as sole therapy",
   "Intravenous immunoglobulin every month",
   "Routine screening of household contacts"],
  "Recurrent C. difficile reflects persistent disruption of the gut microbiome. Fecal microbiota transplantation cures about 85-90% of multiply recurrent cases. Other options include a tapered vancomycin course, fidaxomicin, and bezlotoxumab, a monoclonal antibody against toxin B.",
  why={"A six-month course of oral metronidazole": "Prolonged metronidazole risks neuropathy and does not restore flora.",
       "Daily oral probiotics as sole therapy": "Probiotics alone do not reliably prevent recurrence.",
       "Intravenous immunoglobulin every month": "IVIG is not standard; bezlotoxumab targets toxin B specifically.",
       "Routine screening of household contacts": "Asymptomatic carriers are not screened or treated."}),

# ---------------- Actinomyces & Nocardia ----------------
Q(TAG_GPR, "Actinomyces vs Nocardia: oxygen and stain",
  "Two branching filamentous organisms are isolated. Isolate 1 is a strict anaerobe and is not acid-fast. Isolate 2 is aerobic and partially acid-fast. Which pair of identifications is correct?",
  ["Isolate 1 Actinomyces; isolate 2 Nocardia",
   "Isolate 1 Nocardia; isolate 2 Actinomyces",
   "Isolate 1 Mycobacterium; isolate 2 Actinomyces",
   "Isolate 1 Streptomyces; isolate 2 Mycobacterium",
   "Isolate 1 Nocardia; isolate 2 Streptomyces"],
  "Actinomyces is an anaerobic, non-acid-fast branching rod that is normal oral flora and causes cervicofacial infection with draining sinus tracts and sulfur granules. Nocardia is an aerobic, partially acid-fast soil organism causing pulmonary and brain disease in immunocompromised hosts. Treatment differs: penicillin for Actinomyces, TMP-SMX for Nocardia.",
  difficulty="easy",
  why={"Isolate 1 Nocardia; isolate 2 Actinomyces": "The oxygen requirements are reversed here.",
       "Isolate 1 Mycobacterium": "Mycobacteria are strongly acid-fast and do not branch prominently.",
       "Isolate 1 Streptomyces": "Streptomyces is an aerobic soil organism.",
       "Isolate 1 Nocardia; isolate 2 Streptomyces": "Nocardia is aerobic, not anaerobic."},
  table=GPR),

Q(TAG_GPR, "Actinomyces: sulfur granules",
  "A 45-year-old man has a firm swelling along the jaw after a dental extraction, with a sinus tract draining pus that contains yellow granules. What are these granules?",
  ["Aggregates of filaments with inflammatory cells",
   "Collections of elemental sulfur made by the bacteria",
   "Calcified remnants of degenerating bone fragments",
   "Clusters of eosinophils around a parasitic larva",
   "Fungal spherules packed with mature endospores"],
  "Sulfur granules are macroscopic colonies of Actinomyces filaments with surrounding neutrophils and debris; the name reflects their yellow color, not sulfur content. Cervicofacial actinomycosis follows dental procedures or poor dentition and crosses tissue planes, forming sinus tracts. Treatment is prolonged penicillin.",
  why={"Collections of elemental sulfur": "No sulfur is present; the color is the only similarity.",
       "Calcified remnants of degenerating bone": "These granules are bacterial colonies, not bone.",
       "Clusters of eosinophils": "Eosinophilic granulomas indicate parasitic disease.",
       "Fungal spherules packed with mature endospores": "Spherules indicate Coccidioides."},
  table=GPR),

Q(TAG_GPR, "Nocardia: pulmonary and CNS disease",
  "A renal transplant recipient on tacrolimus has three weeks of cough and a cavitary upper lobe lesion. Sputum shows beaded, branching, weakly acid-fast rods. Which additional evaluation is essential?",
  ["Brain imaging to look for abscesses",
   "Bone marrow biopsy to look for granulomas",
   "Echocardiography to look for vegetations",
   "Colonoscopy to look for mucosal ulcers",
   "Nerve conduction studies of the limbs"],
  "Nocardia disseminates from the lung to the brain in up to a third of immunocompromised patients, often without neurologic symptoms, so brain imaging is standard. Treatment is high-dose TMP-SMX, often with a carbapenem or amikacin in severe disease, for six months or longer.",
  why={"Bone marrow biopsy": "Marrow involvement is not typical.",
       "Echocardiography": "Endocarditis is a rare manifestation.",
       "Colonoscopy": "Gut involvement is uncommon.",
       "Nerve conduction studies": "Peripheral nerve disease is not a feature of nocardiosis."},
  table=GPR),

Q(TAG_GPR, "Nocardia: mycetoma after soil injury",
  "A farmer steps on a thorn and months later has a chronically draining, swollen foot with sinus tracts and grains in the discharge. Which organism group should be considered along with fungi?",
  ["Aerobic actinomycetes such as Nocardia",
   "Anaerobic cocci such as Peptostreptococcus",
   "Spirochetes such as Treponema pallidum",
   "Rickettsiae transmitted by mite bites",
   "Mycoplasma species lacking a cell wall"],
  "Mycetoma is a chronic granulomatous infection of the foot. Actinomycetoma is caused by aerobic actinomycetes (Nocardia, Actinomadura, Streptomyces) and responds to TMP-SMX-based therapy; eumycetoma is caused by fungi such as Madurella and needs antifungals with surgery. Distinguishing them changes treatment entirely.",
  difficulty="hard",
  why={"Anaerobic cocci such as Peptostreptococcus": "These cause abscesses, not grain-forming mycetoma.",
       "Spirochetes such as Treponema pallidum": "Syphilis does not produce grains or mycetoma.",
       "Rickettsiae transmitted by mite bites": "Rickettsiae cause acute febrile illness with rash.",
       "Mycoplasma species lacking a cell wall": "Mycoplasma causes respiratory and urogenital disease."}),

Q(TAG_GPR, "Erysipelothrix: fish handler",
  "A fishmonger has a spreading violaceous plaque with a raised border on the hand after a puncture from a fish spine. Culture grows a thin, non-motile, catalase-negative, H2S-producing Gram-positive rod. What is the organism and treatment?",
  ["Erysipelothrix rhusiopathiae; penicillin",
   "Listeria monocytogenes; ampicillin and gentamicin",
   "Streptococcus iniae; vancomycin",
   "Mycobacterium marinum; clarithromycin",
   "Vibrio vulnificus; doxycycline"],
  "Erysipelothrix rhusiopathiae causes erysipeloid, a violaceous cellulitis of the hand in fish, meat, and poultry handlers. It is catalase-negative, produces H2S on triple sugar iron agar, and is notably resistant to vancomycin. Penicillin is the drug of choice.",
  difficulty="hard",
  why={"Listeria monocytogenes; ampicillin and gentamicin": "Listeria is catalase-positive and motile and causes invasive disease.",
       "Streptococcus iniae; vancomycin": "S. iniae infects fish handlers but is a coccus in chains.",
       "Mycobacterium marinum; clarithromycin": "M. marinum causes indolent nodules in a sporotrichoid pattern.",
       "Vibrio vulnificus; doxycycline": "V. vulnificus is a Gram-negative rod that causes hemorrhagic bullae."}),

Q(TAG_GPR, "Cutibacterium acnes: shoulder prosthesis",
  "Eleven months after shoulder replacement, a patient has persistent pain without fever. Cultures held for 14 days grow an anaerobic, catalase-positive Gram-positive rod. Which organism is this?",
  ["Cutibacterium acnes",
   "Actinomyces israelii",
   "Clostridium perfringens",
   "Bacillus subtilis",
   "Lactobacillus species"],
  "Cutibacterium (formerly Propionibacterium) acnes lives in sebaceous follicles, is dense on the shoulder, and causes indolent prosthetic joint infection that needs prolonged anaerobic culture to detect. It also contributes to acne and can infect CSF shunts. It is catalase-positive, unlike Actinomyces.",
  difficulty="hard",
  why={"Actinomyces israelii": "Actinomyces is catalase-negative and forms sinus tracts.",
       "Clostridium perfringens": "C. perfringens forms spores and causes acute myonecrosis.",
       "Bacillus subtilis": "B. subtilis is an aerobic spore former and usually a contaminant.",
       "Lactobacillus species": "Lactobacilli are rarely pathogenic outside endocarditis in compromised hosts."}),

Q(TAG_GPR, "Spore structure and sterilization",
  "Which feature of bacterial endospores explains why they survive boiling at 100°C and require an autoclave at 121°C?",
  ["A dehydrated core held by calcium dipicolinate",
   "A thick outer membrane rich in lipid A and porins",
   "A polysaccharide capsule that excludes hot water",
   "A mycolic acid layer that repels aqueous solutions",
   "An efflux system that expels heat-shock products"],
  "Spores have a dehydrated core containing calcium dipicolinate and small acid-soluble proteins that protect DNA, plus a keratin-like coat and cortex. They resist heat, drying, radiation, and many disinfectants. Autoclaving at 121°C for 15 minutes, or ethylene oxide, is needed; alcohol hand gel does not kill C. difficile spores.",
  difficulty="medium",
  why={"A thick outer membrane rich in lipid A": "Spore formers are Gram-positive and have no outer membrane.",
       "A polysaccharide capsule that excludes": "Capsules do not confer heat resistance.",
       "A mycolic acid layer": "Mycolic acids explain acid-fastness in mycobacteria.",
       "An efflux system that expels": "Efflux pumps affect drug resistance, not heat survival."},
  table=GENETICS),
]
