"""Gram-negative organisms in depth: Neisseria, Haemophilus, Bordetella, Legionella, Pseudomonas, enterics, Vibrio, Campylobacter, H. pylori, anaerobes."""
from qcore import Q
from tables import *
TAG_GNC = "Gram− Cocci & Respiratory Rods"
TAG_ENT = "Enteric Gram− Rods"
TAG_ABX = "Antibacterial Drugs"
QUESTIONS = [
# ---------------- Neisseria ----------------
Q(TAG_GNC, "Neisseria: maltose fermentation",
  "Two oxidase-positive Gram-negative diplococci are isolated. Both ferment glucose; only one ferments maltose. Which identification follows?",
  ["The maltose fermenter is N. meningitidis",
   "The maltose fermenter is N. gonorrhoeae",
   "The maltose fermenter is Moraxella catarrhalis",
   "Neither organism can ferment any sugar",
   "Both organisms ferment maltose equally well"],
  "Meningococci ferment maltose and glucose; gonococci ferment glucose only. Mnemonic: MeninGococci ferment Maltose and Glucose, Gonococci ferment Glucose. Moraxella catarrhalis ferments neither and is also oxidase-positive.",
  difficulty="easy",
  why={"The maltose fermenter is N. gonorrhoeae": "Gonococci do not ferment maltose.",
       "The maltose fermenter is Moraxella catarrhalis": "Moraxella is asaccharolytic.",
       "Neither organism can ferment any sugar": "Both ferment glucose.",
       "Both organisms ferment maltose equally well": "Only the meningococcus ferments maltose."},
  table=NEISSERIA),

Q(TAG_GNC, "N. gonorrhoeae: why no lasting immunity",
  "A 24-year-old man has his third episode of gonococcal urethritis in two years. Which property of the organism best explains repeated infection?",
  ["Pilin gene rearrangement alters its surface antigens",
   "A polysaccharide capsule blocks all antibody binding",
   "The organism hides within neurons between episodes",
   "The organism integrates its DNA into the host genome",
   "Antibody to its endotoxin core is always protective"],
  "Gonococci vary pilin and Opa proteins by recombination among silent gene copies, so antibody from one infection does not protect against the next. They also make IgA protease. There is no gonococcal vaccine, unlike the meningococcus, which has a capsule that can be targeted.",
  why={"A polysaccharide capsule blocks all antibody": "Gonococci are not encapsulated; that is the meningococcus.",
       "The organism hides within neurons": "Neuronal latency is a herpesvirus property.",
       "The organism integrates its DNA": "Integration into host DNA is a retroviral property.",
       "Antibody to its endotoxin core": "Anti-LOS antibody does not prevent reinfection."},
  table=NEISSERIA),

Q(TAG_GNC, "Gonorrhea: current treatment",
  "A 26-year-old woman has purulent cervicitis and a positive nucleic acid amplification test for N. gonorrhoeae. Chlamydia testing is negative. What is the recommended treatment?",
  ["A single intramuscular dose of ceftriaxone",
   "A single oral dose of ciprofloxacin",
   "A seven-day course of oral penicillin V",
   "A single oral dose of cefixime with azithromycin",
   "A fourteen-day course of oral doxycycline"],
  "Current guidance is a single intramuscular dose of ceftriaxone (500 mg, or 1 g if 150 kg or more) for uncomplicated gonorrhea. Doxycycline is added only when chlamydia is not excluded. Fluoroquinolone resistance is widespread, and penicillins are no longer used.",
  difficulty="easy",
  why={"A single oral dose of ciprofloxacin": "Quinolone resistance is too common.",
       "A seven-day course of oral penicillin V": "Penicillinase-producing strains are widespread.",
       "A single oral dose of cefixime with azithromycin": "Oral cefixime is a backup option only when ceftriaxone is unavailable.",
       "A fourteen-day course of oral doxycycline": "Doxycycline treats chlamydia, not gonorrhea."},
  table=NEISSERIA),

Q(TAG_GNC, "Gonococcal arthritis vs septic arthritis",
  "A 22-year-old woman has fever, migratory joint pains, tenosynovitis of the wrist, and a few pustules on the extremities. Aspirate of the knee grows nothing. Which explanation fits?",
  ["Disseminated gonococcal infection often has sterile joint fluid",
   "Disseminated gonococcal infection always yields positive joint cultures",
   "The negative culture rules out any bacterial cause of arthritis",
   "The findings indicate crystal-induced rather than infectious arthritis",
   "The findings represent reactive arthritis after enteric infection"],
  "Disseminated gonococcal infection has two patterns. The arthritis-dermatitis form has fever, tenosynovitis, migratory polyarthralgia, and pustular lesions, with frequently negative joint and blood cultures; NAAT of genital, rectal, or throat sites is the best diagnostic test. The purulent form is a true septic monoarthritis with positive fluid cultures.",
  why={"Disseminated gonococcal infection always yields": "Cultures are often negative in the arthritis-dermatitis form.",
       "The negative culture rules out": "Culture is insensitive here, so NAAT at mucosal sites is used.",
       "The findings indicate crystal-induced": "Crystal disease does not cause pustules or tenosynovitis with fever.",
       "The findings represent reactive arthritis": "Reactive arthritis follows enteric or chlamydial infection and is not pustular."},
  table=NEISSERIA),

Q(TAG_GNC, "N. meningitidis: carriage to invasion",
  "A college dormitory resident becomes ill with meningococcemia, while several roommates carry the organism without illness. Which factor most determines progression to invasive disease?",
  ["Absence of bactericidal antibody to that capsule",
   "Presence of a mutation in the bacterial pilin gene",
   "Absence of a functional spleen in every case",
   "Presence of high titers of secretory IgA in saliva",
   "Absence of nasal ciliary function from smoking alone"],
  "Nasopharyngeal carriage is common, especially in adolescents and crowded settings, and usually leads to protective antibody. Invasive disease occurs when a susceptible person without bactericidal anticapsular antibody acquires a virulent strain. Complement deficiency, asplenia, eculizumab, smoking, and viral infection all increase risk.",
  why={"Presence of a mutation in the bacterial pilin": "Pilin variation aids colonization but does not determine invasion.",
       "Absence of a functional spleen in every case": "Asplenia raises risk but most cases occur in people with spleens.",
       "Presence of high titers of secretory IgA": "The organism cleaves IgA, and mucosal IgA does not prevent bacteremia.",
       "Absence of nasal ciliary function from smoking": "Smoking is a risk factor but not the main determinant."},
  table=NEISSERIA),

Q(TAG_GNC, "Meningococcal vaccines: serogroup coverage",
  "A 16-year-old received a quadrivalent conjugate meningococcal vaccine at 11 years of age. Which additional vaccine is recommended, and why?",
  ["A serogroup B vaccine, which the quadrivalent does not cover",
   "A repeat quadrivalent dose, since serogroup B is included in it",
   "A pneumococcal conjugate vaccine, which covers serogroup B",
   "A Haemophilus influenzae type b vaccine for cross-protection",
   "No further vaccine, since one dose provides lifelong immunity"],
  "MenACWY conjugate vaccines cover serogroups A, C, W, and Y. Serogroup B has a capsule resembling human neural tissue, so its vaccines are protein-based (MenB-4C, MenB-FHbp) and are given separately, typically at 16-23 years. A MenACWY booster at 16 is also recommended.",
  why={"A repeat quadrivalent dose, since serogroup B is included": "Serogroup B is not in the quadrivalent vaccine.",
       "A pneumococcal conjugate vaccine": "Pneumococcal vaccines do not cover meningococci.",
       "A Haemophilus influenzae type b vaccine": "Hib vaccine gives no meningococcal protection.",
       "No further vaccine, since one dose": "Protection wanes, and serogroup B is still uncovered."},
  table=VACCINES),

Q(TAG_GNC, "Meningococcal prophylaxis: agents",
  "A nurse performed mouth-to-mouth resuscitation on a patient later found to have meningococcal meningitis. Which prophylactic option is appropriate?",
  ["A single oral dose of ciprofloxacin",
   "A single oral dose of amoxicillin",
   "A ten-day course of oral penicillin V",
   "A single intravenous dose of vancomycin",
   "Observation alone, since risk is negligible"],
  "Close contacts (household members, childcare contacts, anyone exposed to oral secretions) receive prophylaxis with rifampin, ciprofloxacin, or ceftriaxone. Casual contacts do not. Ceftriaxone is preferred in pregnancy. Prophylaxis eradicates nasopharyngeal carriage, which penicillin does not do reliably.",
  difficulty="easy",
  why={"A single oral dose of amoxicillin": "Amoxicillin does not eradicate carriage.",
       "A ten-day course of oral penicillin V": "Penicillin treats disease but does not clear the nasopharynx.",
       "A single intravenous dose of vancomycin": "Vancomycin has no Gram-negative activity.",
       "Observation alone": "Exposure to oral secretions is a clear indication for prophylaxis."},
  table=NEISSERIA),

# ---------------- Haemophilus ----------------
Q(TAG_GNC, "H. influenzae: factors X and V",
  "A Gram-negative coccobacillus grows on chocolate agar but not on sheep blood agar, and it grows on blood agar only in satellite colonies beside S. aureus. Which nutrients does it require?",
  ["Hemin and NAD",
   "Cysteine and iron",
   "Pyridoxal and L-cysteine",
   "Mevalonate and biotin",
   "Charcoal and yeast extract"],
  "H. influenzae needs factor X (hemin) and factor V (NAD). Sheep blood agar contains NADases, so the organism grows only near S. aureus colonies that release NAD by lysing red cells (satellite phenomenon). Chocolate agar is heated blood agar, which releases both factors.",
  difficulty="easy",
  why={"Cysteine and iron": "Cysteine and iron are required by Legionella and Francisella.",
       "Pyridoxal and L-cysteine": "Pyridoxal is needed by nutritionally variant streptococci.",
       "Mevalonate and biotin": "These are not standard growth factor requirements in the clinical lab.",
       "Charcoal and yeast extract": "These are ingredients of media for Legionella and Bordetella."},
  table=HAEMOPHILUS_BORD_LEG),

Q(TAG_GNC, "Hib vaccine: effect on disease pattern",
  "Since routine Hib conjugate vaccination began, which change in H. influenzae disease has occurred?",
  ["Nontypeable strains now cause most disease",
   "Type b strains now cause most adult meningitis",
   "The organism no longer causes any human disease",
   "Type f strains now cause most childhood epiglottitis",
   "Disease has shifted entirely to immunized children"],
  "Conjugate vaccination nearly eliminated invasive type b disease, including meningitis and epiglottitis in children. Most remaining disease is from nontypeable (unencapsulated) strains causing otitis media, sinusitis, conjunctivitis, and exacerbations of COPD. The vaccine targets the polyribosylribitol phosphate capsule, so it does not prevent nontypeable disease.",
  why={"Type b strains now cause most adult meningitis": "Adult meningitis is mainly pneumococcal and meningococcal.",
       "The organism no longer causes any human disease": "Nontypeable strains remain common pathogens.",
       "Type f strains now cause most childhood epiglottitis": "Epiglottitis is now rare and more often from other organisms.",
       "Disease has shifted entirely to immunized children": "Vaccinated children are largely protected against type b."},
  table=VACCINES),

Q(TAG_GNC, "Epiglottitis: airway priority",
  "An unimmunized 4-year-old is drooling, leaning forward, and has a muffled voice with high fever and stridor. What is the first priority?",
  ["Secure the airway in a controlled setting",
   "Obtain a lateral neck radiograph immediately",
   "Examine the throat with a tongue depressor",
   "Start oral amoxicillin and observe at home",
   "Give nebulized racemic epinephrine and discharge"],
  "Epiglottitis is an airway emergency. The child is kept calm and taken to the operating room for controlled intubation; pharyngeal examination can precipitate complete obstruction. After the airway is secured, ceftriaxone is given, and rifampin prophylaxis is offered to unimmunized close contacts.",
  difficulty="easy",
  why={"Obtain a lateral neck radiograph": "Imaging delays airway control, although a thumbprint sign may be seen.",
       "Examine the throat with a tongue depressor": "This can trigger laryngospasm and complete obstruction.",
       "Start oral amoxicillin and observe at home": "This is a life-threatening infection needing hospital care.",
       "Give nebulized racemic epinephrine and discharge": "That is croup management, a different illness."}),

Q(TAG_GNC, "H. ducreyi: painful ulcer",
  "A man has a painful genital ulcer with ragged undermined edges and tender suppurative inguinal nodes. Gram stain shows Gram-negative rods in a 'school of fish' pattern. What is the organism and treatment?",
  ["Haemophilus ducreyi; azithromycin",
   "Treponema pallidum; penicillin G",
   "Klebsiella granulomatis; doxycycline",
   "Herpes simplex virus; valacyclovir",
   "Chlamydia trachomatis L1-L3; doxycycline"],
  "Chancroid from H. ducreyi causes a painful ulcer with a soft base and tender, often suppurative buboes. Mnemonic: 'do cry' for painful H. ducreyi. Treatment is a single dose of azithromycin or ceftriaxone. Syphilitic chancres are painless with firm borders.",
  difficulty="medium",
  why={"Treponema pallidum; penicillin G": "The syphilitic chancre is painless with indurated edges.",
       "Klebsiella granulomatis; doxycycline": "Granuloma inguinale causes beefy-red painless ulcers with Donovan bodies.",
       "Herpes simplex virus; valacyclovir": "HSV causes shallow grouped vesicles and ulcers, not deep undermined ulcers.",
       "Chlamydia trachomatis L1-L3; doxycycline": "Lymphogranuloma venereum has a small painless ulcer with painful nodes."},
  table=GENITAL_ULCERS),

# ---------------- Bordetella ----------------
Q(TAG_GNC, "Pertussis: toxin actions",
  "Pertussis toxin ADP-ribosylates the inhibitory alpha subunit of a G protein. What is the consequence inside the host cell?",
  ["Adenylyl cyclase is disinhibited and cAMP rises",
   "Adenylyl cyclase is inhibited and cAMP falls sharply",
   "Guanylate cyclase is activated and cGMP rises",
   "Protein synthesis halts at the elongation step",
   "Chloride channels close and secretion decreases"],
  "Pertussis toxin inactivates Gi, so adenylyl cyclase is no longer restrained and cAMP rises. This impairs neutrophil chemotaxis and causes lymphocytosis. The organism also makes adenylate cyclase toxin, tracheal cytotoxin (which destroys ciliated cells), and filamentous hemagglutinin.",
  why={"Adenylyl cyclase is inhibited and cAMP falls": "Blocking the inhibitory subunit raises cAMP rather than lowering it.",
       "Guanylate cyclase is activated": "Guanylate cyclase activation describes heat-stable E. coli toxin.",
       "Protein synthesis halts": "That describes diphtheria and Shiga toxins.",
       "Chloride channels close": "Cholera toxin opens chloride channels; pertussis does not act this way."},
  table=TOXINS),

Q(TAG_GNC, "Pertussis: stage-dependent treatment benefit",
  "A 6-year-old has had three weeks of paroxysmal coughing fits with post-tussive vomiting. Which statement about azithromycin is correct?",
  ["It reduces transmission but will not shorten this cough",
   "It shortens the cough substantially at any disease stage",
   "It is contraindicated in children of this age group",
   "It works only if given with a course of corticosteroids",
   "It eradicates the organism and prevents all complications"],
  "Pertussis has catarrhal, paroxysmal, and convalescent stages. Antibiotics help symptoms only if given in the catarrhal stage; later the cough is driven by damage already done to ciliated epithelium. Treatment is still given to reduce transmission, and close contacts receive prophylaxis.",
  why={"It shortens the cough substantially at any disease stage": "By the paroxysmal stage, symptom benefit is minimal.",
       "It is contraindicated in children": "Macrolides are the treatment of choice at this age.",
       "It works only if given with a course of corticosteroids": "Steroids are not standard therapy.",
       "It eradicates the organism and prevents all complications": "Eradication does not reverse established epithelial injury."},
  table=HAEMOPHILUS_BORD_LEG),

Q(TAG_GNC, "Pertussis: infant presentation",
  "A 6-week-old has episodes of breath-holding and turning blue while feeding, without much coughing. His white count is 30,000/µL with 80% lymphocytes. Which diagnosis fits best?",
  ["Pertussis, which often presents as apnea in infants",
   "Acute lymphoblastic leukemia with airway compression",
   "Respiratory syncytial virus with typical wheezing",
   "Foreign body aspiration into the right main bronchus",
   "Congenital laryngomalacia with inspiratory stridor"],
  "Young infants with pertussis often have apnea, cyanosis, or gagging rather than the classic whoop, and marked lymphocytosis is a clue. They are at highest risk of death. Prevention depends on maternal Tdap at 27-36 weeks and cocooning of close contacts.",
  why={"Acute lymphoblastic leukemia": "Leukemia would usually show blasts and other cytopenias.",
       "Respiratory syncytial virus": "RSV gives wheezing and crackles and does not cause this lymphocytosis.",
       "Foreign body aspiration": "Aspiration causes focal findings and does not raise the lymphocyte count.",
       "Congenital laryngomalacia": "Laryngomalacia causes stridor without fever or leukocytosis."},
  table=HAEMOPHILUS_BORD_LEG),

# ---------------- Legionella ----------------
Q(TAG_GNC, "Legionella: staining and culture",
  "A smoker with pneumonia, diarrhea, confusion, and a sodium of 128 mEq/L has a sputum sample with many neutrophils but no organisms on Gram stain. Which laboratory approach identifies the cause?",
  ["Culture on charcoal yeast extract with added cysteine",
   "Culture on chocolate agar in five percent carbon dioxide",
   "Culture on Thayer-Martin medium with antibiotics added",
   "Culture on MacConkey agar to assess lactose fermentation",
   "Culture on Lowenstein-Jensen medium for several weeks"],
  "Legionella stains poorly with Gram stain because of its branched-chain fatty acids, and it needs buffered charcoal yeast extract agar with iron and cysteine. Urinary antigen detects serogroup 1 rapidly. Clues include hyponatremia, diarrhea, confusion, and transaminitis in a smoker.",
  why={"Culture on chocolate agar": "Chocolate agar is used for Haemophilus and Neisseria.",
       "Culture on Thayer-Martin medium": "Thayer-Martin is selective for Neisseria.",
       "Culture on MacConkey agar": "MacConkey selects for Gram-negative enterics.",
       "Culture on Lowenstein-Jensen medium": "This medium is used for mycobacteria."},
  table=MEDIA),

Q(TAG_GNC, "Legionella: intracellular survival",
  "How does Legionella pneumophila survive within alveolar macrophages?",
  ["It blocks fusion of the phagosome with lysosomes",
   "It escapes into the cytoplasm using a pore-forming toxin",
   "It neutralizes the phagosome by producing urease",
   "It survives by forming a thick waxy mycolic acid coat",
   "It replicates inside the nucleus alongside host DNA"],
  "Legionella uses a Dot/Icm type IV secretion system to remodel its vacuole and prevent phagosome-lysosome fusion, replicating inside a rough ER-derived compartment. This is why treatment needs drugs that penetrate cells, such as azithromycin or levofloxacin, rather than beta-lactams.",
  difficulty="hard",
  why={"It escapes into the cytoplasm using a pore-forming": "Cytoplasmic escape describes Listeria and Shigella.",
       "It neutralizes the phagosome by producing urease": "Urease-based survival is a feature of H. pylori in acid.",
       "It survives by forming a thick waxy mycolic acid coat": "Mycolic acids belong to mycobacteria.",
       "It replicates inside the nucleus": "No bacterium replicates in the nucleus."},
  table=HAEMOPHILUS_BORD_LEG),

Q(TAG_GNC, "Pontiac fever vs Legionnaires disease",
  "Several hotel guests develop chills, headache, and myalgia without pneumonia after using a whirlpool spa; all recover in a few days without treatment. Which statement is correct?",
  ["This is Pontiac fever, a self-limited form of the infection",
   "This is Legionnaires disease with a mild pneumonia on imaging",
   "This represents a different organism unrelated to Legionella",
   "This requires four weeks of levofloxacin for every guest",
   "This indicates that the spa water was free of Legionella"],
  "Pontiac fever is a self-limited flu-like illness from Legionella exposure without pneumonia, resolving in two to five days without antibiotics. Legionnaires disease is the pneumonic form and requires a macrolide or fluoroquinolone. Both follow aerosol exposure from water systems; there is no person-to-person spread.",
  difficulty="medium",
  why={"This is Legionnaires disease with a mild pneumonia": "No pneumonia is present in this scenario.",
       "This represents a different organism": "Both syndromes come from Legionella.",
       "This requires four weeks of levofloxacin": "Pontiac fever resolves without antibiotics.",
       "This indicates that the spa water was free": "Aerosolized spa water is a classic source."},
  table=HAEMOPHILUS_BORD_LEG),

# ---------------- Pseudomonas ----------------
Q(TAG_GNC, "Pseudomonas: aerobic metabolism and lab clues",
  "An organism from a burn wound is an oxidase-positive, non-lactose-fermenting Gram-negative rod that grows as blue-green colonies with a grape-like odor. Which metabolic description fits?",
  ["An obligate aerobe that does not ferment glucose",
   "A facultative anaerobe that ferments lactose rapidly",
   "An obligate anaerobe killed by ambient oxygen",
   "A microaerophile needing added carbon dioxide",
   "An aerotolerant organism lacking catalase entirely"],
  "Pseudomonas aeruginosa is an obligate aerobe (it can use nitrate for anaerobic respiration) that does not ferment sugars, so it is a non-lactose fermenter on MacConkey agar and oxidase-positive. Pyocyanin and pyoverdin give the blue-green color, and it smells of grapes or corn tortillas.",
  difficulty="easy",
  why={"A facultative anaerobe that ferments lactose": "That describes E. coli and Klebsiella.",
       "An obligate anaerobe killed by ambient oxygen": "That describes Bacteroides and Clostridium.",
       "A microaerophile needing added carbon dioxide": "That describes Campylobacter and Neisseria growth conditions.",
       "An aerotolerant organism lacking catalase": "Pseudomonas is catalase-positive."},
  table=ANTI_PSEUDOMONAL),

Q(TAG_GNC, "Pseudomonas: alginate in cystic fibrosis",
  "Sputum from an adolescent with cystic fibrosis grows mucoid Pseudomonas colonies. Which property does this mucoid phenotype reflect, and what does it mean clinically?",
  ["An alginate biofilm that makes eradication difficult",
   "A poly-D-glutamate capsule that resists complement lysis",
   "A lipopolysaccharide O antigen that blocks phagocytosis",
   "An efflux pump that expels all classes of antibiotic",
   "A plasmid carrying carbapenemase and colistin resistance"],
  "Chronic airway infection selects mucoid strains that overproduce alginate, forming biofilm. Biofilm bacteria grow slowly and tolerate antibiotics and phagocytes, so chronic infection is suppressed with inhaled tobramycin or aztreonam rather than cured. Chronic Pseudomonas infection predicts faster decline in lung function.",
  why={"A poly-D-glutamate capsule": "That capsule is unique to B. anthracis.",
       "A lipopolysaccharide O antigen": "O antigen variation does not produce mucoid colonies.",
       "An efflux pump that expels all classes": "Efflux contributes to resistance but is not what makes colonies mucoid.",
       "A plasmid carrying carbapenemase": "Mucoid appearance is not a marker of carbapenemase."},
  table=ANTI_PSEUDOMONAL),

Q(TAG_GNC, "Pseudomonas: malignant otitis externa",
  "A 72-year-old man with diabetes has severe ear pain, drainage, and granulation tissue at the bone-cartilage junction of the ear canal, with a facial droop. Which organism and site of extension should be assumed?",
  ["Pseudomonas spreading to the skull base",
   "S. pneumoniae spreading to the mastoid air cells",
   "Candida spreading along the tympanic membrane",
   "Aspergillus spreading into the middle ear cavity",
   "M. tuberculosis spreading to cervical nodes"],
  "Malignant (necrotizing) otitis externa is a Pseudomonas osteomyelitis of the skull base, typically in older diabetics, with cranial nerve palsies as a warning sign. It needs imaging and prolonged systemic anti-pseudomonal therapy such as ciprofloxacin, not topical drops alone.",
  difficulty="medium",
  why={"S. pneumoniae spreading to the mastoid": "Pneumococcus causes otitis media and mastoiditis, not this necrotizing canal disease.",
       "Candida spreading along the tympanic membrane": "Fungal otitis externa is usually superficial.",
       "Aspergillus spreading into the middle ear": "Aspergillus otomycosis is rarely invasive except in severe immunosuppression.",
       "M. tuberculosis spreading to cervical nodes": "Tuberculous otitis is rare and painless with chronic drainage."},
  table=ANTI_PSEUDOMONAL),

Q(TAG_GNC, "Pseudomonas: puncture wound osteomyelitis",
  "A teenager steps on a nail through the sole of a sneaker and develops osteomyelitis of the foot. Which organism is classically implicated besides S. aureus?",
  ["Pseudomonas aeruginosa",
   "Salmonella species, as in sickle cell",
   "Bartonella henselae",
   "Pasteurella multocida",
   "Eikenella corrodens"],
  "Puncture wounds through footwear are classically associated with Pseudomonas osteomyelitis, likely from moist sneaker linings, although S. aureus remains most common overall. Salmonella osteomyelitis is associated with sickle cell disease, and Pasteurella with animal bites.",
  difficulty="easy",
  why={"Salmonella species": "Salmonella bone infection is linked to sickle cell disease.",
       "Bartonella henselae": "Bartonella causes cat scratch lymphadenitis.",
       "Pasteurella multocida": "Pasteurella follows cat and dog bites.",
       "Eikenella corrodens": "Eikenella follows human bites and fist-to-mouth injuries."}),

Q(TAG_ABX, "Anti-pseudomonal coverage: identifying the gap",
  "A patient with febrile neutropenia is started on an antibiotic that must cover Pseudomonas. Which agent lacks such coverage?",
  ["Ertapenem",
   "Meropenem",
   "Cefepime",
   "Piperacillin-tazobactam",
   "Ceftazidime"],
  "Ertapenem is the one carbapenem without Pseudomonas or Acinetobacter activity, which is why it is not used for febrile neutropenia. Anti-pseudomonal options include piperacillin-tazobactam, cefepime, ceftazidime, meropenem, imipenem, aztreonam, ciprofloxacin, and aminoglycosides.",
  why={"Meropenem": "Meropenem is reliably anti-pseudomonal.",
       "Cefepime": "Cefepime is a standard anti-pseudomonal cephalosporin.",
       "Piperacillin-tazobactam": "This combination is anti-pseudomonal.",
       "Ceftazidime": "Ceftazidime is anti-pseudomonal, with weaker Gram-positive activity."},
  table=ANTI_PSEUDOMONAL),

# ---------------- enterics ----------------
Q(TAG_ENT, "E. coli: UPEC adhesins",
  "Which bacterial structure allows uropathogenic E. coli to ascend from the bladder to the kidney?",
  ["P fimbriae binding to uroepithelial glycolipids",
   "Type III secretion injecting effector proteins",
   "A urease that alkalinizes the urine directly",
   "Peritrichous flagella that resist urine flow alone",
   "Shiga toxin that damages renal tubular cells"],
  "Type 1 fimbriae mediate bladder colonization, and P fimbriae (pap genes) bind the P blood group antigen on uroepithelium, permitting ascent to the kidney and pyelonephritis. Other UPEC factors include hemolysin, aerobactin for iron capture, and capsule.",
  difficulty="hard",
  why={"Type III secretion injecting effector proteins": "Type III secretion is used by enteropathogenic strains, Shigella, and Salmonella.",
       "A urease that alkalinizes the urine": "Urease belongs to Proteus, Klebsiella, and Staphylococcus saprophyticus.",
       "Peritrichous flagella that resist urine flow": "Motility contributes but is not the key adhesin.",
       "Shiga toxin that damages renal tubular cells": "Shiga toxin acts on endothelium in HUS, not in ascending infection."},
  table=ECOLI),

Q(TAG_ENT, "E. coli: toxin pair in traveler's diarrhea",
  "A traveler has several days of watery diarrhea without fever or blood. The isolate produces a heat-labile and a heat-stable toxin. What are their targets?",
  ["One raises cAMP and the other raises cGMP",
   "One raises cAMP and the other blocks protein synthesis",
   "One cleaves ribosomal RNA and the other forms pores",
   "One inactivates Gi and the other inactivates Gs",
   "One glucosylates Rho and the other cleaves SNAREs"],
  "Enterotoxigenic E. coli makes a labile toxin that activates adenylyl cyclase (raising cAMP, like cholera toxin) and a stable toxin that activates guanylate cyclase (raising cGMP). Both drive chloride and water secretion without invasion, so there is no fever or blood. Mnemonic: labile like Air (adenylate), stable like Ground (guanylate).",
  why={"One raises cAMP and the other blocks protein synthesis": "Protein synthesis inhibition describes Shiga toxin.",
       "One cleaves ribosomal RNA and the other forms pores": "Neither ETEC toxin acts this way.",
       "One inactivates Gi and the other inactivates Gs": "Gi inactivation describes pertussis toxin.",
       "One glucosylates Rho and the other cleaves SNAREs": "These describe C. difficile and botulinum toxins."},
  table=ECOLI),

Q(TAG_ENT, "EHEC: antibiotic avoidance",
  "A 5-year-old has bloody diarrhea after eating undercooked ground beef. Stool is positive for Shiga toxin and a sorbitol-negative E. coli. Why are antibiotics avoided?",
  ["Killing the organism releases more toxin and raises HUS risk",
   "Antibiotics cause the organism to become invasive in the colon",
   "Antibiotics select for vancomycin resistance in gut flora",
   "Antibiotics prevent the immune response needed for clearance",
   "Antibiotics reduce toxin binding without changing outcomes"],
  "Antibiotics (and antimotility agents) increase the risk of hemolytic uremic syndrome in Shiga toxin-producing E. coli infection, probably by increasing toxin release during bacterial lysis. Management is supportive with careful IV hydration, monitoring the hemoglobin, platelet count, and creatinine.",
  why={"Antibiotics cause the organism to become invasive": "EHEC remains non-invasive throughout.",
       "Antibiotics select for vancomycin resistance": "That concern is unrelated to this decision.",
       "Antibiotics prevent the immune response": "Immune suppression is not the mechanism of harm here.",
       "Antibiotics reduce toxin binding without changing outcomes": "They actually worsen outcomes rather than being neutral."},
  table=ECOLI),

Q(TAG_ENT, "Klebsiella: currant jelly sputum",
  "An alcohol-dependent man has a right upper lobe cavitary pneumonia with thick, blood-tinged sputum. Culture grows a lactose-fermenting, non-motile, urease-positive Gram-negative rod with a large capsule. Which organism is this?",
  ["Klebsiella pneumoniae",
   "Escherichia coli",
   "Proteus mirabilis",
   "Serratia marcescens",
   "Enterobacter aerogenes"],
  "Klebsiella is a heavily encapsulated, non-motile lactose fermenter that causes aspiration pneumonia in alcohol-dependent and diabetic patients, often with cavitation and thick 'currant jelly' sputum. It also causes UTIs and, in hypervirulent strains, liver abscess with metastatic spread.",
  difficulty="easy",
  why={"Escherichia coli": "E. coli is motile and rarely cavitates the lung.",
       "Proteus mirabilis": "Proteus swarms, smells of burnt chocolate, and is not a lung pathogen.",
       "Serratia marcescens": "Serratia produces red pigment and is a hospital pathogen.",
       "Enterobacter aerogenes": "Enterobacter is motile and mainly a hospital pathogen."},
  table=LACTOSE),

Q(TAG_ENT, "Proteus: urease and stones",
  "A woman with recurrent urinary infections has a large branching renal stone and urine pH of 8.2. Which mechanism links the organism to the stone?",
  ["Urease raises urine pH, precipitating struvite",
   "Hemolysin damages tubules, releasing calcium",
   "Nitrate reduction acidifies urine, forming urate",
   "Biofilm traps oxalate crystals on the urothelium",
   "Capsule binds cystine, which then crystallizes"],
  "Proteus urease splits urea into ammonia and carbon dioxide, raising urine pH. Alkaline urine precipitates magnesium ammonium phosphate (struvite), which forms staghorn calculi that harbor bacteria. Cure requires removing the stone as well as treating the infection. Other urease producers include Klebsiella, S. saprophyticus, and Ureaplasma.",
  why={"Hemolysin damages tubules": "Calcium stones are metabolic and not driven by hemolysin.",
       "Nitrate reduction acidifies urine": "Proteus alkalinizes rather than acidifies urine.",
       "Biofilm traps oxalate crystals": "Oxalate stones are not infection-related.",
       "Capsule binds cystine": "Cystine stones result from an inherited transport defect."},
  table=UREASE),

Q(TAG_ENT, "Salmonella vs Shigella: invasion route",
  "Both Salmonella and Shigella invade the colon, yet only one regularly causes bacteremia. Which statement explains the difference?",
  ["Salmonella survives in macrophages and enters the blood",
   "Shigella survives in macrophages and reaches the bloodstream",
   "Shigella lacks any mechanism for epithelial invasion",
   "Salmonella is non-invasive and acts only through toxin",
   "Both organisms are equally likely to cause bacteremia"],
  "Salmonella invades through M cells, survives inside macrophages, and can disseminate, causing bacteremia and osteomyelitis. Shigella invades epithelium through M cells, escapes into the cytoplasm, and spreads cell to cell but kills macrophages by apoptosis and rarely enters the blood. Shigella also has a much lower infectious dose.",
  why={"Shigella survives in macrophages and reaches the bloodstream": "Shigella triggers macrophage death instead of surviving inside them.",
       "Shigella lacks any mechanism for epithelial invasion": "Shigella is highly invasive of epithelium.",
       "Salmonella is non-invasive": "Salmonella is invasive.",
       "Both organisms are equally likely": "Bacteremia is far more common with Salmonella."},
  table=SALM_SHIG),

Q(TAG_ENT, "Salmonella: acid and antacid risk",
  "Which factor most increases susceptibility to non-typhoidal Salmonella gastroenteritis?",
  ["Proton pump inhibitor use",
   "Daily aspirin therapy",
   "A high-fiber vegetarian diet",
   "Recent influenza vaccination",
   "Chronic beta-blocker therapy"],
  "Salmonella has a relatively high infectious dose and is acid-sensitive, so reduced gastric acidity from proton pump inhibitors, antacids, or gastrectomy lowers the dose needed. Sickle cell disease, asplenia, HIV, and extremes of age raise the risk of invasive disease.",
  difficulty="medium",
  why={"Daily aspirin therapy": "Aspirin does not raise gastric pH enough to matter.",
       "A high-fiber vegetarian diet": "Diet fiber is not a recognized risk factor.",
       "Recent influenza vaccination": "Vaccination does not predispose to enteric infection.",
       "Chronic beta-blocker therapy": "Beta-blockers have no effect on gastric acid."},
  table=SALM_SHIG),

Q(TAG_ENT, "Shigella: toxin and complication",
  "A child in a daycare outbreak has fever, tenesmus, and scant bloody stools, then develops a seizure. Which statements about this organism are correct?",
  ["It makes Shiga toxin and has a very low infectious dose",
   "It makes Shiga toxin and requires a very high inoculum",
   "It makes cholera-like toxin and is spread only by water",
   "It is non-invasive and produces watery stools exclusively",
   "It is spread only by undercooked beef and never person to person"],
  "Shigella needs as few as 10-100 organisms, so person-to-person spread in daycares and households is common. S. dysenteriae type 1 produces Shiga toxin, which inhibits protein synthesis by cleaving 28S rRNA and can cause HUS. Seizures occur in young children, often with fever.",
  why={"It makes Shiga toxin and requires a very high inoculum": "The infectious dose is remarkably low.",
       "It makes cholera-like toxin": "Cholera-like enterotoxin describes Vibrio and ETEC.",
       "It is non-invasive": "Shigella invades colonic epithelium and causes dysentery.",
       "It is spread only by undercooked beef": "Beef is the EHEC vehicle; Shigella spreads person to person."},
  table=SALM_SHIG),

Q(TAG_ENT, "Vibrio cholerae: rehydration physiology",
  "A patient with cholera has profuse rice-water stools. Why does oral rehydration solution with glucose work despite ongoing chloride secretion?",
  ["Sodium-glucose cotransport is intact and pulls water in",
   "Glucose blocks cholera toxin binding to the GM1 receptor",
   "Glucose inhibits adenylyl cyclase inside the enterocyte",
   "Glucose kills the organism by fermentative acidification",
   "Glucose stimulates gastric acid, which neutralizes toxin"],
  "Cholera toxin causes secretion through CFTR but leaves the SGLT1 sodium-glucose cotransporter working. Glucose-coupled sodium absorption pulls water back across the mucosa, which is why oral rehydration solution saves lives without stopping the diarrhea. Severe cases also get doxycycline or azithromycin, which shortens shedding.",
  why={"Glucose blocks cholera toxin binding": "Glucose has no effect on toxin binding.",
       "Glucose inhibits adenylyl cyclase": "cAMP remains elevated during treatment.",
       "Glucose kills the organism": "Oral rehydration does not kill Vibrio.",
       "Glucose stimulates gastric acid": "Gastric acid plays no role in the effect."},
  table=VIBRIO),

Q(TAG_ENT, "Campylobacter: growth conditions",
  "A teenager has fever, cramping abdominal pain, and bloody diarrhea after handling raw chicken. The comma-shaped organism grows at 42°C in a microaerophilic atmosphere. Which organism is this?",
  ["Campylobacter jejuni",
   "Vibrio parahaemolyticus",
   "Yersinia enterocolitica",
   "Shigella sonnei",
   "Aeromonas hydrophila"],
  "C. jejuni is a curved, comma- or S-shaped Gram-negative rod that is oxidase-positive and grows best at 42°C in reduced oxygen on Skirrow medium. Poultry is the main source. It is the most common bacterial cause of diarrhea in many countries and precedes Guillain-Barré syndrome and reactive arthritis.",
  difficulty="easy",
  why={"Vibrio parahaemolyticus": "This follows shellfish and grows on TCBS agar with salt.",
       "Yersinia enterocolitica": "Yersinia grows in the cold and mimics appendicitis.",
       "Shigella sonnei": "Shigella is a straight, non-motile rod.",
       "Aeromonas hydrophila": "Aeromonas is linked to fresh water and is not thermophilic."},
  table=DIARRHEA),

Q(TAG_ENT, "H. pylori: urease-based tests",
  "Which diagnostic tests for H. pylori depend on the organism's urease, and what must be stopped before testing?",
  ["Breath and stool-independent urea tests; hold PPIs first",
   "Serologic antibody tests; hold all antibiotics for a month",
   "Stool antigen tests; hold antacids for twenty-four hours",
   "Biopsy silver stain; hold anticoagulants for three days",
   "Complement fixation tests; hold proton pump inhibitors"],
  "The urea breath test and rapid urease test on biopsy both detect urease, which H. pylori uses to neutralize acid. Proton pump inhibitors, bismuth, and antibiotics suppress the organism and cause false negatives, so PPIs are stopped one to two weeks before testing. Serology cannot distinguish current from past infection.",
  difficulty="medium",
  why={"Serologic antibody tests": "Serology does not measure urease and cannot confirm eradication.",
       "Stool antigen tests": "Stool antigen detects bacterial protein rather than urease activity.",
       "Biopsy silver stain": "Staining visualizes organisms without using urease.",
       "Complement fixation tests": "Complement fixation is not used for H. pylori."},
  table=UREASE),

Q(TAG_ENT, "H. pylori: ulcer site and mechanism",
  "How does H. pylori lead to duodenal ulceration?",
  ["Antral infection raises gastrin and the duodenal acid load",
   "Body infection destroys parietal cells and lowers acid production",
   "It secretes an enterotoxin that raises duodenal cAMP levels",
   "It invades the duodenal wall and causes direct necrosis",
   "It blocks bicarbonate secretion from the exocrine pancreas"],
  "Antral-predominant infection reduces somatostatin from D cells, so gastrin and acid output rise and the duodenum receives an excess acid load, producing duodenal ulcers. Body-predominant infection causes atrophic gastritis, lower acid, and greater risk of gastric ulcer and adenocarcinoma. CagA and VacA increase virulence.",
  difficulty="hard",
  why={"Body infection destroys parietal cells and lowers acid production": "That pattern lowers acid and is linked to gastric cancer rather than duodenal ulcer.",
       "It secretes an enterotoxin that raises duodenal cAMP": "H. pylori does not act through a cAMP enterotoxin.",
       "It invades the duodenal wall": "It remains in the mucus layer and does not invade deeply.",
       "It blocks bicarbonate secretion from the exocrine pancreas": "Pancreatic secretion is not the mechanism."},
  table=UREASE),

Q(TAG_ENT, "Bacteroides fragilis: intrinsic resistance",
  "An intra-abdominal abscess after colon surgery grows an obligate anaerobe with no lipopolysaccharide-driven endotoxin activity typical of enterics. Which regimen is appropriate?",
  ["Metronidazole with a cephalosporin",
   "Penicillin G with gentamicin synergy",
   "Aztreonam with vancomycin",
   "Cephalexin with azithromycin",
   "Nitrofurantoin with doxycycline"],
  "Bacteroides fragilis is the most common anaerobe in intra-abdominal infection. It produces beta-lactamase and resists penicillin and aminoglycosides, which need oxygen for uptake. Effective options include metronidazole, carbapenems, piperacillin-tazobactam, and cefoxitin, combined with aerobic Gram-negative coverage.",
  why={"Penicillin G with gentamicin synergy": "Both fail: the organism makes beta-lactamase and aminoglycosides need oxygen.",
       "Aztreonam with vancomycin": "Neither drug covers anaerobic Gram-negative rods.",
       "Cephalexin with azithromycin": "Neither reliably covers B. fragilis.",
       "Nitrofurantoin with doxycycline": "Nitrofurantoin is limited to the urinary tract."},
  table=ABX_TOX),

Q(TAG_ENT, "Yersinia enterocolitica: mimics and iron",
  "A child with beta-thalassemia on transfusions and chelation develops fever, right lower quadrant pain, and diarrhea. Which organism should be suspected, and why is he at risk?",
  ["Yersinia enterocolitica, which thrives on excess iron",
   "Shigella flexneri, which needs a very small inoculum",
   "Clostridioides difficile, which follows antibiotic use",
   "Vibrio vulnificus, which follows raw oyster ingestion",
   "Campylobacter jejuni, which follows poultry exposure"],
  "Yersinia uses siderophores and multiplies readily in iron-replete hosts, so iron overload from transfusions and deferoxamine therapy raises the risk. It causes pseudoappendicitis with mesenteric adenitis, and it grows in the cold, so refrigerated milk and pork are vehicles. Reactive arthritis may follow.",
  difficulty="hard",
  why={"Shigella flexneri": "Shigella causes dysentery without a link to iron overload.",
       "Clostridioides difficile": "No antibiotic exposure is described here.",
       "Vibrio vulnificus": "V. vulnificus risk rises with iron overload but causes sepsis with bullae after oysters.",
       "Campylobacter jejuni": "Campylobacter is not associated with iron overload."},
  table=DIARRHEA),

Q(TAG_ENT, "Enterics: lactose fermentation logic",
  "On MacConkey agar, which set of organisms produces pink colonies?",
  ["E. coli, Klebsiella, Enterobacter, Citrobacter",
   "Salmonella, Shigella, Proteus, Yersinia, Pseudomonas",
   "Pseudomonas, Salmonella, E. coli, Shigella, Proteus",
   "Klebsiella, Shigella, Serratia, Yersinia, Salmonella",
   "Proteus, Enterobacter, Pseudomonas, Shigella, Yersinia"],
  "Lactose fermenters turn MacConkey agar pink: E. coli, Klebsiella, Enterobacter, Citrobacter, and Serratia (Serratia slowly). Mnemonic: 'lactose is KEE' for Klebsiella, E. coli, Enterobacter as the fast fermenters. Non-fermenters (colorless) include Salmonella, Shigella, Proteus, Yersinia, and Pseudomonas.",
  difficulty="easy",
  why={"Salmonella, Shigella, Proteus, Yersinia, Pseudomonas": "These are all non-fermenters.",
       "Pseudomonas, Salmonella, E. coli, Shigella, Proteus": "Only E. coli in this list ferments lactose.",
       "Klebsiella, Shigella, Serratia, Yersinia, Salmonella": "Shigella, Yersinia, and Salmonella do not ferment lactose.",
       "Proteus, Enterobacter, Pseudomonas, Shigella, Yersinia": "Only Enterobacter here ferments lactose."},
  table=LACTOSE),
]
