"""Mycobacteria, spirochetes, rickettsiae, chlamydiae, and zoonoses in depth."""
from qcore import Q
from tables import *
TAG_MYCO = "Mycobacteria"
TAG_SPIRO = "Spirochetes"
TAG_RICK = "Rickettsiae & Chlamydiae"
TAG_ZOO = "Zoonotic Bacteria"
TAG_ABX = "Antibacterial Drugs"
QUESTIONS = [
# ---------------- tuberculosis ----------------
Q(TAG_MYCO, "TB: cord factor",
  "Which mycobacterial cell wall component causes serpentine cord formation in culture and activates macrophages to release TNF-alpha, contributing to caseating granulomas?",
  ["Trehalose dimycolate",
   "Mycolic acid alone",
   "Arabinogalactan polymer",
   "Lipoarabinomannan",
   "Sulfatide lipids"],
  "Cord factor (trehalose 6,6'-dimycolate) makes the organism grow in serpentine cords, inhibits phagosome maturation, and induces TNF-alpha release that drives granuloma formation and the weight loss of tuberculosis. Sulfatides also block phagosome-lysosome fusion.",
  difficulty="hard",
  why={"Mycolic acid alone": "Mycolic acids confer acid-fastness but do not by themselves cause cording.",
       "Arabinogalactan polymer": "Arabinogalactan is a structural polysaccharide and is the target of ethambutol.",
       "Lipoarabinomannan": "LAM modulates immune signaling and is used in a urine antigen test.",
       "Sulfatide lipids": "Sulfatides block phagolysosome fusion but do not cause cording."},
  table=TB_DRUGS),

Q(TAG_MYCO, "TB: granuloma cell types",
  "A lymph node biopsy from a patient with tuberculosis shows granulomas. Which cell and cytokine pair is central to keeping this infection contained?",
  ["Macrophages driven by interferon-gamma",
   "Neutrophils activated by interleukin-8",
   "Eosinophils activated by interleukin-5",
   "Mast cells activated by interleukin-4",
   "B cells activated by interleukin-21"],
  "CD4 Th1 cells release IFN-gamma, which activates macrophages to form epithelioid cells, Langhans giant cells, and granulomas. Blocking TNF-alpha or losing CD4 cells breaks containment, which is why TNF inhibitors and HIV reactivate latent tuberculosis, and why the IGRA measures IFN-gamma release.",
  difficulty="easy",
  why={"Neutrophils activated by interleukin-8": "Neutrophils dominate acute pyogenic infection, not granulomas.",
       "Eosinophils activated by interleukin-5": "Eosinophils respond to helminths.",
       "Mast cells activated by interleukin-4": "Mast cells mediate allergy.",
       "B cells activated by interleukin-21": "Antibody plays little role in containing tuberculosis."},
  table=IMMUNODEF),

Q(TAG_MYCO, "TB: Ghon complex vs reactivation site",
  "Why does primary tuberculosis typically involve the lower lobes while reactivation disease favors the apices?",
  ["Apices have higher oxygen tension and poorer drainage",
   "Apices receive far more blood flow than the lung bases do",
   "Lower lobes have thicker pleura that blocks reactivation",
   "Lower lobes lack alveolar macrophages for the organism",
   "Apices are cooler, which slows bacterial multiplication"],
  "Inhaled droplets deposit where ventilation is greatest, the lower lobes, producing the Ghon focus with hilar adenopathy (Ghon complex). Reactivation favors the apices, where the ventilation-perfusion ratio gives the highest oxygen tension, favoring this obligate aerobe, and lymphatic clearance is poorer.",
  difficulty="medium",
  why={"Apices receive far more blood flow": "Perfusion is actually lowest at the apices when upright.",
       "Lower lobes have thicker pleura": "Pleural thickness does not determine reactivation site.",
       "Lower lobes lack alveolar macrophages": "Macrophages are present throughout the lung.",
       "Apices are cooler, which slows bacterial": "Cooler temperature favors M. marinum and leprosy, not apical TB."}),

Q(TAG_MYCO, "TB: acid-fast alternatives",
  "A patient's sputum is processed for mycobacteria. Which method most quickly identifies an isolate that will not respond to rifampin?",
  ["Nucleic acid amplification with rpoB probes",
   "Ziehl-Neelsen staining of a concentrated sputum smear",
   "Auramine-rhodamine fluorescent staining of sputum",
   "Solid culture on Lowenstein-Jensen slants for weeks",
   "Tuberculin skin testing with intradermal PPD"],
  "Molecular tests (for example Xpert MTB/RIF) detect M. tuberculosis DNA and rpoB mutations conferring rifampin resistance within hours. Smears are quick but insensitive and do not give susceptibility. Culture remains the reference standard but takes weeks, and the skin test cannot distinguish infection from disease.",
  why={"Ziehl-Neelsen staining of a concentrated sputum smear": "Smear microscopy gives no resistance information.",
       "Auramine-rhodamine fluorescent staining": "Fluorescent staining is more sensitive than ZN but still gives no susceptibility data.",
       "Solid culture on Lowenstein-Jensen slants": "Solid culture takes three to eight weeks.",
       "Tuberculin skin testing": "The skin test detects prior sensitization, not resistance."},
  table=STAINS),

Q(TAG_MYCO, "Isoniazid: mechanism and activation",
  "Isoniazid requires bacterial activation before it can act. Which sequence is correct?",
  ["KatG activates it, then it blocks mycolic acid synthesis",
   "KatG activates it, then it blocks arabinogalactan synthesis",
   "Pyrazinamidase activates it, then it disrupts membranes",
   "It needs no activation and blocks RNA polymerase directly",
   "It is activated in the liver and blocks DNA gyrase"],
  "Isoniazid is a prodrug activated by mycobacterial catalase-peroxidase (KatG); the active form inhibits InhA, an enoyl reductase in mycolic acid synthesis. Resistance arises from katG or inhA mutations. Adverse effects include hepatitis, peripheral neuropathy from pyridoxine depletion, and drug-induced lupus.",
  why={"KatG activates it, then it blocks arabinogalactan": "Arabinogalactan synthesis is inhibited by ethambutol.",
       "Pyrazinamidase activates it": "Pyrazinamidase activates pyrazinamide.",
       "It needs no activation and blocks RNA polymerase": "RNA polymerase is the rifampin target.",
       "It is activated in the liver and blocks DNA gyrase": "Gyrase is the fluoroquinolone target."},
  table=TB_DRUGS),

Q(TAG_MYCO, "Rifampin: induction consequences",
  "A woman on combined oral contraceptives and warfarin is started on rifampin for tuberculosis. What is the expected consequence?",
  ["Both drugs become less effective from enzyme induction",
   "Both drugs become more potent from enzyme inhibition",
   "The contraceptive fails while warfarin needs a lower dose",
   "Warfarin fails while the contraceptive becomes stronger",
   "Neither drug is affected because rifampin is renally cleared"],
  "Rifampin is a potent inducer of cytochrome P450, especially CYP3A4, so it accelerates metabolism of oral contraceptives, warfarin, protease inhibitors, and many other drugs. It also causes orange discoloration of urine, sweat, and tears, and can cause hepatotoxicity. Rifabutin induces less and is preferred with antiretroviral therapy.",
  difficulty="easy",
  why={"Both drugs become more potent from enzyme inhibition": "Rifampin induces rather than inhibits P450.",
       "The contraceptive fails while warfarin needs a lower dose": "Warfarin requirements rise, not fall.",
       "Warfarin fails while the contraceptive becomes stronger": "Both are made less effective.",
       "Neither drug is affected": "Rifampin is a classic inducer with many interactions."},
  table=TB_DRUGS),

Q(TAG_MYCO, "Ethambutol and pyrazinamide: adverse effects",
  "A patient on four-drug tuberculosis therapy reports difficulty distinguishing red from green, and his uric acid is elevated with a painful great toe. Which drugs explain these two problems?",
  ["Ethambutol for the eyes and pyrazinamide for the gout",
   "Pyrazinamide for the vision and ethambutol for the gout",
   "Isoniazid for the vision and rifampin for the gout",
   "Rifampin for the vision and isoniazid for the gout",
   "Streptomycin for the vision and ethambutol for the gout"],
  "Ethambutol inhibits arabinosyl transferase and causes dose-dependent optic neuritis with red-green color blindness. Pyrazinamide reduces uric acid excretion and can precipitate gout; it also causes hepatotoxicity. Isoniazid causes neuropathy and hepatitis, rifampin causes orange fluids, and streptomycin causes vestibular and auditory toxicity.",
  difficulty="easy",
  why={"Pyrazinamide for the vision and ethambutol for the gout": "The two adverse effects are swapped.",
       "Isoniazid for the vision and rifampin for the gout": "Isoniazid causes peripheral neuropathy rather than optic neuritis.",
       "Rifampin for the vision and isoniazid for the gout": "Neither drug causes these effects.",
       "Streptomycin for the vision and ethambutol for the gout": "Streptomycin is ototoxic, not a cause of optic neuritis."},
  table=TB_DRUGS),

Q(TAG_MYCO, "Isoniazid: pyridoxine and neuropathy",
  "Why is pyridoxine given with isoniazid, especially in pregnancy, alcohol use disorder, and malnutrition?",
  ["Isoniazid depletes vitamin B6, causing peripheral neuropathy",
   "Isoniazid depletes vitamin B12, causing subacute degeneration",
   "Isoniazid blocks folate absorption, causing megaloblastosis",
   "Isoniazid chelates calcium, causing tetany and paresthesias",
   "Isoniazid blocks thiamine use, causing Wernicke syndrome"],
  "Isoniazid forms hydrazones with pyridoxal phosphate and increases its excretion, so B6 becomes deficient and a sensory peripheral neuropathy develops. Pyridoxine 25-50 mg daily prevents this. Massive isoniazid overdose causes refractory seizures treated with high-dose pyridoxine.",
  difficulty="easy",
  why={"Isoniazid depletes vitamin B12": "B12 deficiency is unrelated to isoniazid.",
       "Isoniazid blocks folate absorption": "Folate antagonism is a feature of TMP-SMX and phenytoin.",
       "Isoniazid chelates calcium": "Isoniazid does not chelate calcium.",
       "Isoniazid blocks thiamine use": "Thiamine deficiency relates to alcohol use itself."},
  table=TB_DRUGS),

Q(TAG_MYCO, "Latent TB: regimen options",
  "A healthy 32-year-old nurse has a positive IGRA, a normal chest radiograph, and no symptoms. Which treatment options are appropriate?",
  ["Rifampin for four months, or isoniazid with rifapentine weekly",
   "Four-drug therapy with isoniazid, rifampin, pyrazinamide, ethambutol",
   "No treatment, because latent infection cannot be treated",
   "A single dose of azithromycin repeated every month",
   "Bacille Calmette-Guerin vaccination instead of any drug"],
  "Latent tuberculosis is treated to prevent reactivation. Preferred short regimens are rifampin daily for four months, isoniazid plus rifapentine weekly for 12 doses, or isoniazid plus rifampin daily for three months. Isoniazid alone for six to nine months remains an alternative. Four-drug therapy is for active disease.",
  why={"Four-drug therapy with isoniazid, rifampin, pyrazinamide": "Four drugs are reserved for active disease.",
       "No treatment, because latent infection cannot": "Treating latent infection is standard and prevents reactivation.",
       "A single dose of azithromycin": "Azithromycin does not treat M. tuberculosis.",
       "Bacille Calmette-Guerin vaccination instead": "BCG is not used to treat latent infection."},
  table=TB_DRUGS),

Q(TAG_MYCO, "TB skin test: false negatives",
  "A patient with miliary tuberculosis and advanced AIDS has a tuberculin skin test with no induration. What explains this?",
  ["Anergy from impaired cell-mediated immunity",
   "Prior BCG vaccination blunting the reaction",
   "An error, since the test is always positive in disease",
   "Recent exposure within the last two years only",
   "A booster effect from repeated annual testing"],
  "The tuberculin test depends on a type IV hypersensitivity response, so it is falsely negative with severe immunosuppression, overwhelming disease, malnutrition, recent viral infection, and in the first 2-8 weeks after exposure. An IGRA avoids BCG cross-reactivity but can also be affected by immunosuppression.",
  difficulty="medium",
  why={"Prior BCG vaccination blunting": "BCG causes false positives, not negatives.",
       "An error, since the test is always positive": "Severe disease commonly produces a negative result.",
       "Recent exposure within the last two years": "This patient has active disease, so the window period is not the issue.",
       "A booster effect from repeated annual testing": "Boosting increases reactions rather than suppressing them."},
  table=TST),

Q(TAG_MYCO, "MAC prophylaxis and treatment",
  "A patient with AIDS and a CD4 count of 30 cells/µL has fever, weight loss, diarrhea, and anemia, with blood cultures growing Mycobacterium avium complex. Which regimen treats this?",
  ["Azithromycin, ethambutol, and rifabutin together",
   "Isoniazid with rifampin for nine months total",
   "Dapsone with rifampin and clofazimine daily",
   "TMP-SMX at treatment dose for three weeks",
   "Amphotericin B followed by oral fluconazole"],
  "Disseminated MAC occurs when the CD4 count falls below 50 and causes fever, weight loss, diarrhea, and elevated alkaline phosphatase. Treatment is a macrolide plus ethambutol, often with rifabutin. Antiretroviral therapy is essential and can precipitate IRIS.",
  why={"Isoniazid with rifampin for nine months": "MAC is not reliably susceptible to isoniazid.",
       "Dapsone with rifampin and clofazimine daily": "That regimen treats leprosy.",
       "TMP-SMX at treatment dose": "TMP-SMX treats Pneumocystis and Nocardia.",
       "Amphotericin B followed by oral fluconazole": "That treats cryptococcal disease."},
  table=HIV_OI),

Q(TAG_MYCO, "M. scrofulaceum vs TB lymphadenitis",
  "A 3-year-old has a firm, painless, slowly enlarging submandibular node with violaceous overlying skin, no fever, and a normal chest radiograph. Which management is best?",
  ["Surgical excision of the node",
   "Four-drug antituberculous therapy",
   "Incision and drainage with packing",
   "Observation without any intervention",
   "Intravenous ceftriaxone for two weeks"],
  "Nontuberculous mycobacterial lymphadenitis in young children is usually caused by M. avium complex or M. scrofulaceum. Complete surgical excision is both diagnostic and curative; incision and drainage risks a chronic draining sinus tract. Systemic symptoms and abnormal imaging would point to tuberculosis instead.",
  difficulty="hard",
  why={"Four-drug antituberculous therapy": "Tuberculous adenitis usually has systemic signs or lung findings.",
       "Incision and drainage with packing": "This often leads to a chronically draining fistula.",
       "Observation without any intervention": "Untreated nodes may rupture and scar.",
       "Intravenous ceftriaxone": "Beta-lactams do not treat mycobacteria."}),

Q(TAG_MYCO, "Leprosy: nerve involvement",
  "A patient from an endemic area has thickened peripheral nerves and loss of sensation on the cool areas of skin, with preserved sensation in the warm axillae and groin. What explains this distribution?",
  ["The organism prefers cooler temperatures",
   "The organism spreads along arterial walls",
   "Warm areas have denser lymphatic drainage",
   "Cool areas have fewer Schwann cells present",
   "The organism requires high tissue oxygen levels"],
  "M. leprae grows best at 27-30°C, so it targets skin, superficial nerves, the nose, testes, and earlobes while sparing warm areas. It invades Schwann cells, causing sensory loss, then trauma and deformity. It cannot be cultured on artificial media and is grown in armadillos or mouse footpads.",
  difficulty="medium",
  why={"The organism spreads along arterial walls": "It spreads within nerves rather than along arteries.",
       "Warm areas have denser lymphatic drainage": "Lymphatic density does not explain the pattern.",
       "Cool areas have fewer Schwann cells": "Schwann cell density is not the determining factor.",
       "The organism requires high tissue oxygen": "Temperature, not oxygen, determines the distribution."},
  table=LEPROSY),

Q(TAG_MYCO, "Leprosy: lepromatous vs tuberculoid",
  "Two patients have leprosy. Patient A has a few well-defined anesthetic plaques with rare bacilli on biopsy. Patient B has diffuse nodular skin thickening with numerous bacilli. Which immunologic contrast is correct?",
  ["Patient A has a strong Th1 response; patient B a Th2 response",
   "Patient A has a strong Th2 response; patient B a Th1 response",
   "Both patients have identical cell-mediated immune responses",
   "Patient A lacks antibody entirely while patient B lacks T cells",
   "Patient B has the stronger cell-mediated response of the two"],
  "Tuberculoid leprosy reflects a strong Th1 response that limits the organism: few lesions, few bacilli, marked nerve damage, and a positive lepromin test. Lepromatous leprosy reflects a Th2-skewed response with poor macrophage activation: diffuse disease, abundant bacilli, and leonine facies. Tuberculoid disease is treated with dapsone and rifampin, and lepromatous disease adds clofazimine.",
  why={"Patient A has a strong Th2 response": "The two responses are reversed in this option.",
       "Both patients have identical cell-mediated": "The spectrum is defined by differing T-cell responses.",
       "Patient A lacks antibody entirely": "Antibody is present in both; the difference is T-cell polarization.",
       "Patient B has the stronger cell-mediated response": "Lepromatous disease reflects the weaker cellular response."},
  table=LEPROSY),

# ---------------- spirochetes ----------------
Q(TAG_SPIRO, "Syphilis: treponemal vs nontreponemal tests",
  "A man given benzathine penicillin for syphilis two years ago now has a reactive treponemal antibody test with a nonreactive RPR. How should this be interpreted?",
  ["Prior infection, since treponemal tests remain positive",
   "Active untreated infection requiring immediate therapy",
   "A false positive treponemal test in a healthy person",
   "Early primary infection before antibody develops fully",
   "Laboratory error, since both tests should always agree"],
  "Treponemal tests (FTA-ABS, TP-PA, EIA) usually remain reactive for life, while nontreponemal titers (RPR, VDRL) fall after successful treatment and are used to monitor response. A fourfold titer drop indicates cure. A reactive treponemal test with a nonreactive RPR usually means previously treated infection.",
  difficulty="medium",
  why={"Active untreated infection requiring immediate": "Active infection would usually have a reactive RPR.",
       "A false positive treponemal test": "False positive treponemal tests are uncommon and the history fits treated disease.",
       "Early primary infection before antibody": "In very early disease the treponemal test may be the first to turn positive, but the history of treatment fits better.",
       "Laboratory error, since both tests should always agree": "Discordance is expected after treatment."},
  table=SYPH_TESTS),

Q(TAG_SPIRO, "Syphilis: prozone phenomenon",
  "A pregnant woman with widespread condyloma lata has a nonreactive RPR, but dilution of the serum produces a strongly reactive result. What explains the initial result?",
  ["Excess antibody prevented visible lattice formation",
   "Antibody was absent until the sample was diluted",
   "The dilution removed an interfering anticoagulant",
   "Complement in the undiluted serum lysed the antigen",
   "Heat during handling destroyed the original antibody"],
  "In the prozone phenomenon, very high antibody concentrations block cross-linking of antigen particles, so the undiluted sample appears nonreactive. Diluting the serum restores lattice formation and reveals the true titer. It matters most in secondary syphilis and pregnancy, where titers are highest.",
  difficulty="hard",
  why={"Antibody was absent until the sample was diluted": "Dilution cannot create antibody.",
       "The dilution removed an interfering anticoagulant": "Anticoagulants do not cause this effect.",
       "Complement in the undiluted serum lysed the antigen": "Complement is not involved in the RPR reaction.",
       "Heat during handling destroyed the original antibody": "Heat inactivation would not be reversed by dilution."},
  table=SYPH_TESTS),

Q(TAG_SPIRO, "Syphilis: biologic false positive RPR",
  "A woman with systemic lupus erythematosus and antiphospholipid antibodies has a reactive RPR but a nonreactive treponemal test. What is the interpretation?",
  ["A false positive RPR from cross-reacting cardiolipin antibody",
   "Untreated latent syphilis that needs three weekly injections",
   "Successfully treated early syphilis from years earlier",
   "Active neurosyphilis requiring a lumbar puncture today",
   "A false negative treponemal test caused by the prozone effect"],
  "Nontreponemal tests detect antibody to cardiolipin, so they can be falsely reactive in lupus, antiphospholipid syndrome, pregnancy, viral infections, tuberculosis, malaria, injection drug use, and advanced age. A nonreactive treponemal test rules out syphilis in this setting.",
  why={"Untreated latent syphilis that needs three weekly": "A nonreactive treponemal test argues against true infection.",
       "Successfully treated early syphilis": "Treated syphilis leaves the treponemal test reactive.",
       "Active neurosyphilis requiring a lumbar puncture": "There is no evidence of treponemal infection.",
       "A false negative treponemal test caused by the prozone": "The prozone affects nontreponemal titers, not treponemal tests."},
  table=SYPH_TESTS),

Q(TAG_SPIRO, "Syphilis: dark-field and PCR",
  "Why is Treponema pallidum not identified in the routine microbiology laboratory?",
  ["It cannot be grown in vitro and is too slender to see",
   "It grows only at 42°C in a microaerophilic atmosphere",
   "It requires charcoal yeast extract agar with added iron",
   "It lives only within host macrophages and never outside them",
   "It forms spores that resist all standard staining methods"],
  "T. pallidum cannot be cultured on artificial media and is too slender to be seen with Gram stain. Dark-field microscopy of lesion exudate, direct fluorescent antibody testing, or PCR can demonstrate it, and silver stains show it in tissue. Diagnosis is usually serologic.",
  difficulty="medium",
  why={"It grows only at 42°C": "Those are Campylobacter growth conditions.",
       "It requires charcoal yeast extract agar": "That medium is for Legionella.",
       "It lives only within host macrophages and never outside them": "It is an extracellular organism.",
       "It forms spores": "Spirochetes do not form spores."},
  table=STAINS),

Q(TAG_SPIRO, "Lyme disease: stage-specific treatment",
  "A 40-year-old has an expanding annular rash with central clearing after a hike in Connecticut. Serology is negative. What is the best management?",
  ["Treat with doxycycline now on clinical grounds",
   "Await convalescent serology before any treatment",
   "Treat with intravenous ceftriaxone for four weeks",
   "Treat with a single dose of azithromycin only",
   "Reassure and observe, since serology is negative"],
  "Erythema migrans is a clinical diagnosis; serology is often negative in the first weeks because antibody has not yet developed. Early disease is treated with oral doxycycline (or amoxicillin or cefuroxime). Intravenous ceftriaxone is reserved for meningitis, high-grade carditis, or refractory arthritis.",
  difficulty="easy",
  why={"Await convalescent serology before any treatment": "Delay risks progression, and treatment should not wait.",
       "Treat with intravenous ceftriaxone for four weeks": "IV therapy is for neurologic or cardiac involvement.",
       "Treat with a single dose of azithromycin": "Macrolides are second-line and require a full course.",
       "Reassure and observe": "Early serology is insensitive and does not exclude Lyme disease."},
  table=LYME_STAGES),

Q(TAG_SPIRO, "Lyme: two-tier testing logic",
  "Why is Lyme serology performed as a two-step algorithm rather than a single test?",
  ["A sensitive screen is confirmed by a specific second test",
   "A specific screen is confirmed by a more sensitive second test",
   "The first test detects IgM and the second detects only antigen",
   "The first test measures spirochete DNA and the second culture",
   "The two tests detect different Borrelia species separately"],
  "The first step is a sensitive EIA; reactive or equivocal samples go to a more specific second test, historically an immunoblot and now often a second EIA. This limits false positives from cross-reacting antibodies. Neither test distinguishes active from past infection, so testing is reserved for patients with compatible illness.",
  difficulty="medium",
  why={"A specific screen is confirmed by a more sensitive": "The order of sensitivity and specificity is reversed.",
       "The first test detects IgM and the second detects only antigen": "Both steps detect antibody.",
       "The first test measures spirochete DNA": "PCR is not part of routine serologic testing.",
       "The two tests detect different Borrelia species": "Both target B. burgdorferi antigens."},
  table=LYME_STAGES),

Q(TAG_SPIRO, "Lyme carditis: conduction block",
  "A 25-year-old with a recent tick bite has light-headedness. ECG shows complete heart block with a narrow QRS. What is the expected course with treatment?",
  ["Conduction usually recovers, so pacing is rarely permanent",
   "Conduction rarely recovers, so a permanent pacemaker is required",
   "The block will progress to ventricular tachycardia in most cases",
   "The block indicates chronic Chagas disease rather than Lyme",
   "The block requires immediate cardiac transplantation evaluation"],
  "Lyme carditis typically causes AV block at the level of the AV node, which resolves with intravenous ceftriaxone; temporary pacing may be needed, but permanent pacemakers are rarely required. Chagas disease, by contrast, causes irreversible conduction disease and apical aneurysms.",
  difficulty="hard",
  why={"Conduction rarely recovers, so a permanent pacemaker": "Lyme block is usually reversible.",
       "The block will progress to ventricular tachycardia": "Ventricular arrhythmias are not the typical course.",
       "The block indicates chronic Chagas disease": "The tick bite and acute course point to Lyme disease.",
       "The block requires immediate cardiac transplantation": "Transplantation is not indicated for reversible block."},
  table=LYME_STAGES),

Q(TAG_SPIRO, "Leptospirosis: exposure and phases",
  "A triathlete who swam in a freshwater lake develops fever, severe myalgias, conjunctival suffusion without discharge, and then jaundice with kidney injury. Which statement about this illness is correct?",
  ["The organism is shed in animal urine and enters broken skin",
   "The organism is transmitted only by the bite of an infected rodent",
   "The organism is acquired by inhaling aerosols from birth fluids",
   "The organism is spread person to person by respiratory droplets",
   "The organism requires a tick vector to complete its life cycle"],
  "Leptospira is shed in the urine of rats, dogs, and livestock and penetrates skin abrasions or mucous membranes during freshwater exposure. Conjunctival suffusion is a useful clue. Severe disease (Weil disease) brings jaundice, kidney failure, and hemorrhage. Treatment is doxycycline or penicillin.",
  difficulty="medium",
  why={"The organism is transmitted only by the bite": "Bites are not the usual route; contaminated water is.",
       "The organism is acquired by inhaling aerosols from birth fluids": "That route describes Coxiella burnetii.",
       "The organism is spread person to person": "Person-to-person spread does not occur.",
       "The organism requires a tick vector": "Ticks transmit Borrelia, not Leptospira."},
  table=ZOONOSES),

Q(TAG_SPIRO, "Relapsing fever: antigenic variation",
  "A patient has repeated episodes of high fever lasting three days, separated by afebrile intervals of about a week. Blood smears during fever show spirochetes. What explains the relapses?",
  ["Variable surface antigen switching evades new antibody",
   "The organism hides in hepatocytes between febrile episodes",
   "Reinfection occurs from repeated bites by the same vector",
   "The spirochete forms spores that later germinate in blood",
   "Immune complexes deposit and cause periodic fevers"],
  "Borrelia recurrentis and related species rearrange variable major protein genes, so each antibody response clears one antigenic variant and a new one emerges, producing recurring fevers. Louse-borne disease is epidemic and has fewer relapses; tick-borne disease is endemic with more relapses. Treatment can trigger a Jarisch-Herxheimer reaction.",
  difficulty="hard",
  why={"The organism hides in hepatocytes": "Hepatic latency describes Plasmodium vivax hypnozoites.",
       "Reinfection occurs from repeated bites": "Relapses occur without new exposure.",
       "The spirochete forms spores": "Spirochetes do not form spores.",
       "Immune complexes deposit and cause periodic fevers": "Relapses follow antigenic switching with recurrent spirochetemia."},
  table=TICKBORNE),

# ---------------- rickettsiae & chlamydiae ----------------
Q(TAG_RICK, "Rickettsia: energy parasitism",
  "Why must Rickettsia species be grown in cell culture rather than on agar?",
  ["They are obligate intracellular users of host metabolites",
   "They lack any cell wall and are destroyed by agar surfaces",
   "They require an anaerobic atmosphere unavailable in culture",
   "They grow only inside erythrocytes that agar cannot supply",
   "They divide only at temperatures above forty-five degrees"],
  "Rickettsiae are obligate intracellular Gram-negative organisms that rely on host CoA and NAD, so they cannot be cultured on cell-free media. They replicate in endothelium, producing a vasculitis with rash, and are diagnosed serologically or by PCR. Doxycycline is treatment for all rickettsial disease.",
  difficulty="easy",
  why={"They lack any cell wall": "Lacking a cell wall describes Mycoplasma.",
       "They require an anaerobic atmosphere": "Oxygen requirement is not the barrier to culture.",
       "They grow only inside erythrocytes": "Red cell parasitism describes Babesia and Plasmodium.",
       "They divide only at temperatures above forty-five": "They grow at human body temperature."},
  table=RICKETTSIAE),

Q(TAG_RICK, "RMSF vs typhus: rash direction",
  "Two patients have fever, headache, and rash. In patient A the rash began on the wrists and ankles and spread inward, including the palms. In patient B it began on the trunk and spread outward, sparing palms and soles. Which pair of diagnoses fits?",
  ["A has Rocky Mountain spotted fever; B has typhus",
   "A has typhus; B has Rocky Mountain spotted fever",
   "Both patients have Rocky Mountain spotted fever",
   "A has ehrlichiosis; B has Rocky Mountain spotted fever",
   "A has Lyme disease; B has Q fever with a rash"],
  "Rocky Mountain spotted fever starts peripherally and moves centrally, involving the palms and soles, and follows Dermacentor tick exposure. Typhus starts centrally and spreads outward, sparing palms and soles. Both are treated with doxycycline, given empirically because serology is often negative early.",
  difficulty="easy",
  why={"A has typhus; B has Rocky Mountain spotted fever": "The two rash patterns are reversed.",
       "Both patients have Rocky Mountain spotted fever": "The rash directions differ, so the diagnoses differ.",
       "A has ehrlichiosis": "Ehrlichiosis usually has no rash in adults.",
       "A has Lyme disease": "Lyme produces a single expanding annular lesion, and Q fever rarely has a rash."},
  table=RICKETTSIAE),

Q(TAG_RICK, "Ehrlichia vs Anaplasma: inclusions",
  "A patient in the southeastern United States has fever, headache, leukopenia, thrombocytopenia, and elevated transaminases after a tick bite, with no rash. The smear shows intracytoplasmic inclusions in monocytes. Which organism is this?",
  ["Ehrlichia chaffeensis",
   "Anaplasma phagocytophilum",
   "Rickettsia rickettsii",
   "Babesia microti",
   "Borrelia burgdorferi"],
  "Ehrlichia chaffeensis infects monocytes (morulae in monocytes) and is spread by Amblyomma; Anaplasma phagocytophilum infects granulocytes and is spread by Ixodes, so it can coexist with Lyme disease and babesiosis. Both cause fever with cytopenias and transaminitis and are treated with doxycycline.",
  difficulty="medium",
  why={"Anaplasma phagocytophilum": "Anaplasma forms morulae in granulocytes and is Ixodes-borne.",
       "Rickettsia rickettsii": "R. rickettsii infects endothelium and usually produces a rash.",
       "Babesia microti": "Babesia parasitizes red cells and causes hemolysis.",
       "Borrelia burgdorferi": "Borrelia is a spirochete without intracellular inclusions."},
  table=TICKBORNE),

Q(TAG_RICK, "Chlamydia: elementary vs reticulate body",
  "Which statement correctly describes the two forms in the chlamydial developmental cycle?",
  ["The elementary body infects; the reticulate body replicates",
   "The elementary body replicates; the reticulate body is infectious",
   "Both forms are infectious and metabolically identical",
   "The elementary body divides only inside the host nucleus",
   "The reticulate body survives for long periods outside cells"],
  "The elementary body is the small, dense, infectious form that enters cells; inside, it becomes the larger reticulate body, which divides by binary fission using host ATP. New elementary bodies are released to infect other cells. Chlamydia lacks muramic acid in its wall, which is one reason beta-lactams are ineffective.",
  difficulty="easy",
  why={"The elementary body replicates": "The two roles are reversed here.",
       "Both forms are infectious and metabolically identical": "Only the elementary body is infectious.",
       "The elementary body divides only inside the host nucleus": "Replication occurs in a cytoplasmic inclusion.",
       "The reticulate body survives for long periods outside cells": "The reticulate body is fragile and intracellular."},
  table=CHLAMYDIA_SEROVARS),

Q(TAG_RICK, "Chlamydia: serovar and syndrome matching",
  "A traveler has a small painless genital ulcer followed by large, tender, matted inguinal nodes that begin to drain. Which chlamydial serovars cause this?",
  ["L1 through L3",
   "A through C",
   "D through K",
   "Serovar J only",
   "Serovars M and N"],
  "Lymphogranuloma venereum is caused by C. trachomatis L1-L3 and produces a transient painless ulcer followed by painful suppurative lymphadenopathy (buboes) and sometimes proctitis. Serovars A-C cause trachoma; D-K cause urethritis, cervicitis, PID, and neonatal disease. Treatment is doxycycline for three weeks.",
  difficulty="medium",
  why={"A through C": "These cause trachoma, a chronic conjunctival infection.",
       "D through K": "These cause genital and neonatal infections without buboes.",
       "Serovar J only": "Serovar J belongs to the urogenital group.",
       "Serovars M and N": "No such serovars are recognized."},
  table=CHLAMYDIA_SEROVARS),

Q(TAG_RICK, "Trachoma: mechanism of blindness",
  "How does repeated ocular C. trachomatis infection lead to blindness?",
  ["Conjunctival scarring turns the lashes inward onto the cornea",
   "The organism invades the optic nerve and destroys the axons",
   "Immune complexes deposit in the retina and detach it",
   "The lens becomes opacified by direct bacterial invasion",
   "Intraocular pressure rises and damages the optic disc"],
  "Repeated infection in childhood scars the conjunctiva, causing entropion and trichiasis; inturned lashes abrade the cornea, leading to opacification. The SAFE strategy is Surgery, Azithromycin, Facial cleanliness, and Environmental improvement. Mass azithromycin distribution is the pharmacologic core.",
  difficulty="medium",
  why={"The organism invades the optic nerve": "Optic nerve invasion does not occur.",
       "Immune complexes deposit in the retina": "Retinal detachment is not the mechanism.",
       "The lens becomes opacified": "Cataract is unrelated to trachoma.",
       "Intraocular pressure rises": "Glaucoma is not the mechanism of trachomatous blindness."},
  table=CHLAMYDIA_SEROVARS),

Q(TAG_RICK, "Coxiella: exposure and no vector",
  "A veterinarian who assisted with sheep births develops a prolonged fever with pneumonia and hepatitis. Which statement about this organism is correct?",
  ["It is inhaled as spore-like particles without a vector",
   "It is transmitted by a tick bite like other rickettsiae",
   "It is acquired by drinking water contaminated with urine",
   "It is transmitted by the bite of an infected sandfly",
   "It requires direct inoculation through a needle stick"],
  "Coxiella burnetii forms a spore-like form and is inhaled from aerosols of placental tissue, birth fluids, urine, and dust from cattle, sheep, and goats, with no arthropod vector needed. Acute Q fever causes pneumonia and hepatitis; chronic disease causes culture-negative endocarditis. It usually causes no rash.",
  difficulty="medium",
  why={"It is transmitted by a tick bite": "Ticks maintain it in animals, but human disease follows inhalation.",
       "It is acquired by drinking water contaminated with urine": "That describes leptospirosis.",
       "It is transmitted by the bite of an infected sandfly": "Sandflies transmit Leishmania and Bartonella bacilliformis.",
       "It requires direct inoculation through a needle stick": "Aerosol inhalation is the usual route."},
  table=ZOONOSES),

# ---------------- zoonoses ----------------
Q(TAG_ZOO, "Brucella: exposure and lab hazard",
  "A worker at a goat dairy in the Mediterranean has weeks of undulating fever, night sweats, and back pain. Which additional measure is essential when blood cultures are drawn?",
  ["Notify the laboratory so a biosafety cabinet is used",
   "Request rapid room-temperature incubation of the bottles",
   "Ask the lab to add lysostaphin to the culture medium",
   "Request anaerobic bottles only, since it is anaerobic",
   "Send the sample for dark-field microscopy immediately"],
  "Brucella is a major cause of laboratory-acquired infection, so the laboratory must be warned to handle cultures in a biosafety cabinet. It is a facultative intracellular Gram-negative coccobacillus acquired from unpasteurized dairy or animal contact, causing undulant fever, sacroiliitis, and spondylitis. Treatment is doxycycline plus rifampin or streptomycin for six weeks.",
  difficulty="medium",
  why={"Request rapid room-temperature incubation": "Brucella needs standard incubation and may take days to grow.",
       "Ask the lab to add lysostaphin": "Lysostaphin is used for staphylococci in research settings.",
       "Request anaerobic bottles only": "Brucella is aerobic.",
       "Send the sample for dark-field microscopy": "Dark-field microscopy is used for spirochetes."},
  table=ZOONOSES),

Q(TAG_ZOO, "Francisella: infectious dose and syndromes",
  "A hunter who skinned rabbits develops an ulcer on the hand with tender regional adenopathy. Which statement about this organism is correct?",
  ["A very small inoculum suffices, so it is a bioterror concern",
   "A very large inoculum is required, which limits its transmissibility",
   "It is spread person to person by the respiratory droplet route",
   "It grows readily on MacConkey agar as a lactose fermenter",
   "It is treated with amoxicillin-clavulanate for two weeks"],
  "Francisella tularensis needs as few as 10 organisms and is classified as a tier 1 select agent. Exposures include rabbits, ticks and deer flies, contaminated water, and aerosols from mowing over carcasses. Ulceroglandular disease is most common; treatment is streptomycin, gentamicin, or doxycycline. It needs cysteine-enriched media.",
  difficulty="medium",
  why={"A very large inoculum is required": "The infectious dose is extremely low.",
       "It is spread person to person": "Person-to-person spread does not occur.",
       "It grows readily on MacConkey agar": "It is fastidious and needs cysteine-supplemented media.",
       "It is treated with amoxicillin-clavulanate": "Beta-lactams are ineffective against tularemia."},
  table=ZOONOSES),

Q(TAG_ZOO, "Bartonella: immune status determines lesion",
  "Two patients are infected with Bartonella henselae after cat exposure. One has tender regional lymphadenopathy with granulomas; the other, with AIDS, has friable vascular skin nodules. What explains the difference?",
  ["Intact cell-mediated immunity contains the organism instead",
   "The two patients are infected with different Bartonella species",
   "The vascular lesions are a coinfection with Kaposi sarcoma virus",
   "The organism makes a toxin only in patients with normal T cells",
   "The immunocompetent patient has the higher burden of organisms"],
  "With intact cell-mediated immunity, B. henselae causes cat scratch disease with stellate necrotizing granulomas. With advanced HIV, the response shifts to vasoproliferation, producing bacillary angiomatosis, which mimics Kaposi sarcoma but resolves with erythromycin or doxycycline. Tissue shows organisms on Warthin-Starry silver stain.",
  difficulty="hard",
  why={"The two patients are infected with different": "The same species causes both presentations.",
       "The vascular lesions are a coinfection with Kaposi": "Bacillary angiomatosis is bacterial and responds to antibiotics.",
       "The organism makes a toxin only in patients": "No such toxin explains the difference.",
       "The immunocompetent patient has the higher burden of organisms": "Burden is much higher in the immunocompromised patient."},
  table=ZOONOSES),

Q(TAG_ZOO, "Pasteurella vs Bartonella after a cat",
  "A woman is bitten by her cat and 18 hours later has rapidly spreading cellulitis with purulent drainage. Which organism and treatment fit best?",
  ["Pasteurella multocida; amoxicillin-clavulanate",
   "Bartonella henselae; a course of azithromycin",
   "Capnocytophaga canimorsus; ceftriaxone",
   "Eikenella corrodens; ampicillin-sulbactam",
   "Staphylococcus aureus; oral cephalexin"],
  "Pasteurella multocida causes cellulitis within 24 hours of a cat or dog bite and may extend to tenosynovitis or osteomyelitis. Amoxicillin-clavulanate covers Pasteurella along with staphylococci, streptococci, and oral anaerobes; cephalexin alone misses Pasteurella. Cat scratch disease develops over weeks as regional adenopathy.",
  difficulty="easy",
  why={"Bartonella henselae; a course of azithromycin": "Bartonella causes subacute lymphadenopathy, not rapid cellulitis.",
       "Capnocytophaga canimorsus; ceftriaxone": "Capnocytophaga causes sepsis in asplenic patients after dog bites.",
       "Eikenella corrodens; ampicillin-sulbactam": "Eikenella follows human bites.",
       "Staphylococcus aureus; oral cephalexin": "The timing points to Pasteurella, and cephalexin does not cover it."},
  table=ZOONOSES),

Q(TAG_ZOO, "Yersinia pestis: virulence and forms",
  "A patient in the southwestern United States has fever and an exquisitely tender, swollen inguinal node after camping where prairie dogs were dying. Which statement is correct?",
  ["Untreated bubonic disease may become pneumonic plague",
   "Bubonic disease never spreads to the lungs in any patient",
   "The organism is spread mainly by person-to-person contact",
   "Treatment is a beta-lactam such as ampicillin-sulbactam",
   "The bubo should be excised promptly to prevent spread"],
  "Fleas from rodents transmit Y. pestis, producing a bubo. Untreated infection can progress to secondary pneumonic plague, which then spreads person to person by droplets and requires airborne precautions. Treatment is an aminoglycoside, fluoroquinolone, or doxycycline. The organism shows bipolar 'safety pin' staining.",
  difficulty="medium",
  why={"Bubonic disease never spreads to the lungs": "Secondary pneumonic plague is a recognized complication.",
       "The organism is spread mainly by person-to-person": "Flea bites cause most cases; droplet spread occurs only with pneumonic disease.",
       "Treatment is a beta-lactam": "Beta-lactams are not used for plague.",
       "The bubo should be excised promptly": "Aspiration may be done for diagnosis, but excision is not therapy."},
  table=ZOONOSES),
]
