"""Herpesviruses and other DNA viruses in depth."""
from qcore import Q
from tables import *
TAG_HERP = "Herpesviruses"
TAG_DNA = "DNA Viruses (Non-Herpes)"
QUESTIONS = [
# ---------------- HSV ----------------
Q(TAG_HERP, "HSV: latency site by serotype",
  "Which pairing of herpes simplex serotype and latency site is correct?",
  ["HSV-1 in the trigeminal ganglion; HSV-2 in sacral ganglia",
   "HSV-1 in sacral ganglia; HSV-2 in the trigeminal ganglion",
   "Both serotypes remain latent in regional lymph nodes",
   "Both serotypes remain latent within circulating B cells",
   "Both serotypes integrate into the host cell chromosome"],
  "HSV-1 travels up sensory axons to the trigeminal ganglion, and HSV-2 to the sacral ganglia, where the genome persists as a circular episome expressing latency-associated transcripts. Reactivation follows stress, fever, sunlight, or immunosuppression. Neither virus integrates into host DNA.",
  difficulty="easy",
  why={"HSV-1 in sacral ganglia": "The two latency sites are reversed.",
       "Both serotypes remain latent in regional lymph nodes": "Lymphoid latency describes EBV.",
       "Both serotypes remain latent within circulating B cells": "B-cell latency is characteristic of EBV.",
       "Both serotypes integrate into the host cell chromosome": "Integration is a retroviral and HPV feature."},
  table=HERPES),

Q(TAG_HERP, "HSV encephalitis: lobe and CSF",
  "A previously healthy 30-year-old has fever, confusion, and olfactory hallucinations with a focal seizure. Which combination of findings is expected?",
  ["Temporal lobe changes with lymphocytes and red cells in CSF",
   "Frontal lobe changes with a neutrophilic CSF and low glucose",
   "Cerebellar changes with eosinophils in the spinal fluid",
   "Basal ganglia changes with a completely normal spinal fluid",
   "Periventricular changes with a very high CSF protein alone"],
  "HSV-1 encephalitis characteristically affects the temporal lobes, producing personality change, olfactory hallucinations, and seizures. CSF shows lymphocytic pleocytosis, often with red blood cells from hemorrhagic necrosis, and elevated protein with normal glucose. PCR is diagnostic, and intravenous acyclovir must be started empirically.",
  why={"Frontal lobe changes with a neutrophilic CSF": "Neutrophils with low glucose indicate bacterial meningitis.",
       "Cerebellar changes with eosinophils": "Eosinophilic CSF suggests parasitic infection.",
       "Basal ganglia changes with a completely normal spinal fluid": "CSF is abnormal in HSV encephalitis.",
       "Periventricular changes with a very high CSF protein": "This pattern does not describe HSV encephalitis."},
  table=CSF),

Q(TAG_HERP, "Acyclovir: selectivity and resistance",
  "Acyclovir is far more toxic to infected cells than to uninfected cells. Which mechanism explains this, and how does resistance arise?",
  ["Viral thymidine kinase activates it; resistance follows its loss",
   "Viral protease activates it; resistance follows a protease mutation",
   "Host kinases activate it; resistance follows a host mutation",
   "It needs no activation; resistance follows increased efflux",
   "Viral integrase activates it; resistance follows integrase change"],
  "Acyclovir is monophosphorylated by viral thymidine kinase, then converted by host kinases to the triphosphate, which inhibits viral DNA polymerase and causes chain termination. Thymidine kinase-deficient mutants are resistant, and such isolates are treated with foscarnet or cidofovir, which act directly on the polymerase.",
  why={"Viral protease activates it": "Acyclovir is not protease-dependent.",
       "Host kinases activate it; resistance follows a host mutation": "The first step needs the viral kinase, which is why it is selective.",
       "It needs no activation": "Acyclovir is a prodrug requiring phosphorylation.",
       "Viral integrase activates it": "Herpesviruses do not use integrase."},
  table=HERPES_DRUGS),

Q(TAG_HERP, "Neonatal HSV: three patterns",
  "A 10-day-old infant born vaginally to a mother with unrecognized genital herpes has lethargy and seizures. Which statement about neonatal HSV is correct?",
  ["Disseminated and CNS disease carry the worst outcomes",
   "Skin, eye, and mouth disease carries the highest mortality",
   "Cesarean delivery after rupture never reduces transmission",
   "Transmission risk is highest with recurrent maternal disease",
   "Acyclovir is withheld until CSF PCR results are available"],
  "Neonatal HSV presents as skin-eye-mouth disease, CNS disease, or disseminated disease; the latter two carry high mortality and morbidity, so high-dose intravenous acyclovir is started empirically. Risk is highest with primary maternal infection near delivery, when there is little maternal antibody, and cesarean delivery before prolonged rupture lowers risk.",
  why={"Skin, eye, and mouth disease carries the highest mortality": "That form has the best prognosis with treatment.",
       "Cesarean delivery after rupture never reduces transmission": "Cesarean delivery does reduce risk, especially before prolonged rupture.",
       "Transmission risk is highest with recurrent maternal disease": "Primary maternal infection carries much greater risk.",
       "Acyclovir is withheld until CSF PCR results": "Treatment begins immediately on suspicion."},
  table=TORCH),

Q(TAG_HERP, "VZV: shingles and postherpetic pain",
  "A 70-year-old has a painful vesicular rash in one thoracic dermatome. Which intervention reduces the risk of postherpetic neuralgia?",
  ["Antiviral therapy started within 72 hours of onset",
   "Topical antibiotic ointment applied to the vesicles",
   "Oral prednisone alone without any antiviral drug",
   "Delay of antivirals until the vesicles have crusted",
   "Immediate varicella vaccination during the eruption"],
  "Starting valacyclovir, famciclovir, or acyclovir within 72 hours of rash onset shortens the eruption and reduces the risk and duration of postherpetic neuralgia. The recombinant zoster vaccine prevents zoster and is recommended at 50 years and older, but vaccination is not given during acute disease.",
  difficulty="easy",
  why={"Topical antibiotic ointment": "Antibacterial ointment does not affect the virus or the neuralgia.",
       "Oral prednisone alone": "Steroids may help acute pain but do not replace antivirals.",
       "Delay of antivirals until the vesicles have crusted": "The benefit is lost after roughly 72 hours.",
       "Immediate varicella vaccination during the eruption": "Vaccination is a preventive measure, not a treatment."},
  table=HERPES_DRUGS),

Q(TAG_HERP, "VZV: Ramsay Hunt and ophthalmic zoster",
  "A patient with zoster has vesicles on the tip of the nose along with eye pain and redness. Which nerve branch involvement does the nasal tip indicate, and why does it matter?",
  ["Nasociliary branch, which signals risk to the eye",
   "Facial nerve, which signals risk of hearing loss",
   "Glossopharyngeal nerve, which signals swallowing risk",
   "Mandibular branch, which signals risk to the teeth",
   "Vagus nerve, which signals risk of vocal cord palsy"],
  "Hutchinson sign, vesicles on the nasal tip, indicates involvement of the nasociliary branch of V1 and predicts ocular involvement, so urgent ophthalmology referral and systemic antivirals are required. Ramsay Hunt syndrome is zoster of the geniculate ganglion with facial palsy, ear vesicles, and hearing changes.",
  difficulty="medium",
  why={"Facial nerve, which signals risk of hearing loss": "That describes Ramsay Hunt syndrome with ear canal vesicles.",
       "Glossopharyngeal nerve": "The nasal tip is not supplied by cranial nerve IX.",
       "Mandibular branch, which signals risk to the teeth": "V3 supplies the lower face, not the nasal tip.",
       "Vagus nerve, which signals risk of vocal cord palsy": "The vagus does not supply the nasal tip."},
  table=HERPES),

Q(TAG_HERP, "EBV: heterophile antibody basis",
  "The monospot test detects antibodies that agglutinate horse or sheep erythrocytes. Why are such antibodies produced during infectious mononucleosis?",
  ["Polyclonal B-cell activation makes many antibodies",
   "The virus expresses a protein identical to an animal antigen",
   "Infected T cells release antibody after viral transformation",
   "Complement fragments bind red cells and cause agglutination",
   "The antibodies are directed against a viral capsid protein"],
  "EBV infects B cells through CD21 and drives polyclonal activation, so antibodies are made against many antigens including unrelated animal red cell antigens (heterophile antibodies). The test can be negative in the first week and in young children, in whom EBV-specific serology is used instead. Atypical lymphocytes are reactive CD8 T cells.",
  difficulty="hard",
  why={"The virus expresses a protein identical to an animal antigen": "Mimicry of an animal antigen is not the mechanism.",
       "Infected T cells release antibody": "EBV infects B cells, and T cells do not make antibody.",
       "Complement fragments bind red cells": "Complement is not the basis of the test.",
       "The antibodies are directed against a viral capsid protein": "Capsid antibodies are measured by specific EBV serology, not the monospot."},
  table=HERPES),

Q(TAG_HERP, "EBV: splenic rupture counseling",
  "A 19-year-old football player has infectious mononucleosis with tender splenomegaly. Which advice is most important?",
  ["Avoid contact sports for at least three weeks",
   "Begin oral acyclovir to shorten the illness",
   "Take a course of amoxicillin to prevent bacterial superinfection",
   "Resume full contact play once the fever resolves",
   "Undergo elective splenectomy to prevent rupture"],
  "Splenic rupture is the feared complication of mononucleosis, so contact and collision sports are avoided for at least three weeks and until splenomegaly resolves. Antivirals do not alter the course. Corticosteroids are reserved for airway compromise from tonsillar hypertrophy.",
  difficulty="easy",
  why={"Begin oral acyclovir to shorten the illness": "Acyclovir reduces shedding but not clinical illness.",
       "Take a course of amoxicillin": "Amoxicillin risks a morbilliform rash and has no benefit.",
       "Resume full contact play once the fever resolves": "Splenomegaly outlasts the fever.",
       "Undergo elective splenectomy": "Splenectomy is never indicated for this purpose."},
  table=HERPES),

Q(TAG_HERP, "EBV: oral hairy leukoplakia",
  "A man with untreated HIV has white corrugated plaques along the lateral tongue that cannot be scraped off. Which cause is most likely?",
  ["Epstein-Barr virus",
   "Candida albicans",
   "Human papillomavirus",
   "Herpes simplex virus",
   "Kaposi sarcoma herpesvirus"],
  "Oral hairy leukoplakia is an EBV-driven epithelial proliferation on the lateral tongue that does not scrape off, unlike candidal thrush. It signals advanced immunosuppression and improves with antiretroviral therapy. Kaposi sarcoma from HHV-8 produces violaceous palatal or gingival plaques instead.",
  difficulty="medium",
  why={"Candida albicans": "Thrush is a white plaque that scrapes off, leaving erythema.",
       "Human papillomavirus": "HPV causes oral warts and oropharyngeal carcinoma.",
       "Herpes simplex virus": "HSV causes painful ulcers rather than corrugated plaques.",
       "Kaposi sarcoma herpesvirus": "HHV-8 lesions are violaceous vascular plaques."},
  table=HIV_OI),

Q(TAG_HERP, "EBV: post-transplant lymphoproliferative disease",
  "Six months after a kidney transplant, a patient on tacrolimus and mycophenolate has fever, adenopathy, and a rising EBV viral load with a nodal B-cell proliferation. Which initial step is appropriate?",
  ["Reduce immunosuppression and monitor the graft",
   "Increase immunosuppression to control inflammation",
   "Start acyclovir monotherapy at high oral doses",
   "Begin antituberculous therapy empirically today",
   "Proceed directly to allograft removal surgery"],
  "Post-transplant lymphoproliferative disorder arises when immunosuppression removes T-cell control of EBV-transformed B cells. First-line management is reducing immunosuppression, often with rituximab; chemotherapy is used for aggressive disease. Antivirals do not treat established proliferation, because the transformed cells are in latency.",
  difficulty="hard",
  why={"Increase immunosuppression to control inflammation": "More immunosuppression worsens the proliferation.",
       "Start acyclovir monotherapy at high oral doses": "Acyclovir acts on replicating virus, not latently infected transformed cells.",
       "Begin antituberculous therapy empirically today": "The biopsy shows a B-cell proliferation, not granulomas.",
       "Proceed directly to allograft removal": "Graft removal is not the initial treatment."},
  table=HERPES),

Q(TAG_HERP, "CMV: owl eye inclusions and retinitis",
  "A patient with AIDS and a CD4 count of 30 cells/µL reports floaters and painless vision loss. Funduscopy shows perivascular hemorrhages with yellow-white exudates. Which treatment is indicated?",
  ["Ganciclovir or valganciclovir",
   "Acyclovir at standard doses",
   "Amphotericin B with flucytosine",
   "Pyrimethamine with sulfadiazine",
   "TMP-SMX at treatment dosing"],
  "CMV retinitis produces a 'pizza pie' fundus with hemorrhage and exudates and occurs when the CD4 count drops below 50. Treatment is ganciclovir, valganciclovir, or foscarnet, along with antiretroviral therapy. CMV has low affinity for the thymidine kinase that acyclovir requires, so acyclovir is ineffective.",
  difficulty="medium",
  why={"Acyclovir at standard doses": "CMV lacks the kinase needed to activate acyclovir efficiently.",
       "Amphotericin B with flucytosine": "That combination treats cryptococcal meningitis.",
       "Pyrimethamine with sulfadiazine": "That treats toxoplasmic encephalitis.",
       "TMP-SMX at treatment dosing": "That treats Pneumocystis pneumonia."},
  table=HIV_OI),

Q(TAG_HERP, "Ganciclovir vs foscarnet toxicity",
  "A transplant recipient with CMV viremia develops severe neutropenia on valganciclovir, and therapy is switched to foscarnet. Which toxicity must now be monitored?",
  ["Nephrotoxicity with electrolyte wasting",
   "Severe bone marrow suppression once again",
   "Irreversible optic nerve inflammation",
   "Pulmonary fibrosis with a restrictive defect",
   "Hemorrhagic cystitis from drug metabolites"],
  "Ganciclovir causes dose-limiting neutropenia and thrombocytopenia. Foscarnet, a pyrophosphate analog that inhibits viral DNA polymerase without needing phosphorylation, causes nephrotoxicity with hypocalcemia, hypomagnesemia, and hypokalemia, and can cause seizures. Cidofovir is also nephrotoxic and is given with probenecid and hydration.",
  difficulty="hard",
  why={"Severe bone marrow suppression once again": "Marrow suppression is the ganciclovir problem being avoided.",
       "Irreversible optic nerve inflammation": "Optic neuritis is an ethambutol effect.",
       "Pulmonary fibrosis with a restrictive defect": "Pulmonary fibrosis is caused by bleomycin and amiodarone.",
       "Hemorrhagic cystitis from drug metabolites": "That is caused by cyclophosphamide and BK virus."},
  table=HERPES_DRUGS),

Q(TAG_HERP, "CMV: congenital findings",
  "A newborn has microcephaly, periventricular calcifications, sensorineural hearing loss, and a petechial rash. Which infection fits best?",
  ["Cytomegalovirus",
   "Toxoplasma gondii",
   "Rubella virus",
   "Treponema pallidum",
   "Parvovirus B19"],
  "Congenital CMV is the most common congenital infection and the leading infectious cause of sensorineural hearing loss. Periventricular calcifications and microcephaly distinguish it from congenital toxoplasmosis, which causes diffuse intracranial calcifications, chorioretinitis, and hydrocephalus. Valganciclovir improves hearing outcomes in symptomatic infants.",
  difficulty="easy",
  why={"Toxoplasma gondii": "Toxoplasmosis causes scattered calcifications with hydrocephalus and chorioretinitis.",
       "Rubella virus": "Congenital rubella causes cataracts, cardiac defects, and deafness.",
       "Treponema pallidum": "Congenital syphilis causes snuffles, bone lesions, and a desquamating rash.",
       "Parvovirus B19": "Parvovirus causes hydrops fetalis from aplastic anemia."},
  table=TORCH),

Q(TAG_HERP, "HHV-6 and HHV-8: distinguishing disease",
  "Which pairing of human herpesvirus and disease is correct?",
  ["HHV-6 with roseola infantum; HHV-8 with Kaposi sarcoma",
   "HHV-6 with Kaposi sarcoma; HHV-8 with roseola infantum",
   "HHV-6 with Burkitt lymphoma; HHV-8 with oral hairy leukoplakia",
   "HHV-6 with hand-foot-and-mouth disease; HHV-8 with shingles",
   "HHV-6 with congenital deafness; HHV-8 with infant hydrops"],
  "HHV-6 causes roseola (exanthem subitum): high fever for three to five days, then a rose-colored maculopapular rash as the fever breaks, and it is a common cause of febrile seizures. HHV-8 causes Kaposi sarcoma, primary effusion lymphoma, and multicentric Castleman disease.",
  difficulty="easy",
  why={"HHV-6 with Kaposi sarcoma": "The two associations are reversed.",
       "HHV-6 with Burkitt lymphoma": "Burkitt lymphoma and hairy leukoplakia are EBV-associated.",
       "HHV-6 with hand-foot-and-mouth disease": "That illness is caused by coxsackievirus A16.",
       "HHV-6 with congenital deafness": "Congenital deafness is linked to CMV and rubella."},
  table=HERPES),

Q(TAG_HERP, "Herpesvirus structure and drug targets",
  "All herpesviruses share which structural features?",
  ["Double-stranded linear DNA, enveloped and icosahedral",
   "Single-stranded RNA with an envelope and a helical nucleocapsid",
   "Double-stranded circular DNA with no envelope at all",
   "Single-stranded DNA with a naked icosahedral capsid only",
   "Segmented double-stranded RNA with a double capsid shell"],
  "Herpesviruses are enveloped, icosahedral, double-stranded linear DNA viruses that replicate in the nucleus and acquire their envelope from nuclear and Golgi membranes. The envelope explains sensitivity to drying and detergents and the need for close contact, and all establish latency.",
  difficulty="easy",
  why={"Single-stranded RNA with an envelope and a helical": "That describes paramyxoviruses and rhabdoviruses.",
       "Double-stranded circular DNA with no envelope": "That describes papillomaviruses and polyomaviruses.",
       "Single-stranded DNA with a naked icosahedral capsid": "That describes parvovirus B19.",
       "Segmented double-stranded RNA with a double capsid": "That describes rotavirus."},
  table=DNA_VIRUSES),

# ---------------- other DNA viruses ----------------
Q(TAG_DNA, "HPV: E6 and E7 targets",
  "High-risk HPV types drive cervical carcinogenesis through two early proteins. Which host proteins do they inactivate?",
  ["E6 degrades p53 and E7 inhibits Rb",
   "E6 inhibits Rb and E7 degrades p53",
   "Both proteins inactivate the BRCA1 repair pathway",
   "Both proteins activate the RAS signaling cascade",
   "E6 blocks APC and E7 blocks mismatch repair"],
  "E6 targets p53 for ubiquitin-mediated degradation, and E7 binds Rb and releases E2F, so the cell loses both apoptotic and cell-cycle checkpoints. Types 16 and 18 account for most cervical cancers, along with anal, vulvar, penile, and oropharyngeal cancers. Types 6 and 11 cause condyloma acuminatum.",
  difficulty="easy",
  why={"E6 inhibits Rb and E7 degrades p53": "The two targets are reversed.",
       "Both proteins inactivate the BRCA1 repair pathway": "BRCA1 is not the HPV target.",
       "Both proteins activate the RAS signaling cascade": "RAS activation is not the HPV mechanism.",
       "E6 blocks APC and E7 blocks mismatch repair": "These pathways relate to colorectal cancer."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "HPV: koilocytes",
  "A cervical cytology specimen shows enlarged squamous cells with wrinkled hyperchromatic nuclei surrounded by a clear perinuclear halo. What does this finding indicate?",
  ["Cytopathic change from human papillomavirus",
   "Intranuclear inclusions typical of cytomegalovirus",
   "Multinucleated giant cells typical of herpes simplex",
   "Intracytoplasmic inclusions typical of chlamydia",
   "Pseudohyphae with budding yeast typical of candida"],
  "Koilocytes are the hallmark cytopathic effect of HPV infection. They reflect productive viral replication in maturing squamous cells. Screening combines cytology and high-risk HPV DNA testing, and vaccination prevents infection with the covered types.",
  difficulty="medium",
  why={"Intranuclear inclusions typical of cytomegalovirus": "CMV produces large owl-eye inclusions.",
       "Multinucleated giant cells typical of herpes simplex": "HSV gives multinucleated cells with intranuclear inclusions on a Tzanck smear.",
       "Intracytoplasmic inclusions typical of chlamydia": "Chlamydial inclusions are seen in conjunctival scrapings.",
       "Pseudohyphae with budding yeast typical of candida": "Candida shows fungal forms, not koilocytes."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Parvovirus B19: receptor and hematology",
  "Parvovirus B19 causes transient aplastic crisis in sickle cell disease. Which mechanism explains this?",
  ["It infects erythroid progenitors through the P antigen",
   "It infects mature erythrocytes and lyses them directly",
   "It suppresses the marrow by triggering antibody to platelets",
   "It infects megakaryocytes and halts platelet production",
   "It causes splenic sequestration of circulating red cells"],
  "B19 binds the P blood group antigen (globoside) on erythroid precursors and halts their maturation, producing giant pronormoblasts. In people with normal red cell survival this causes only a brief dip, but with shortened survival, as in sickle cell disease, hemoglobin falls sharply. In pregnancy it causes hydrops fetalis.",
  difficulty="medium",
  why={"It infects mature erythrocytes and lyses them": "Mature red cells lack the nucleus needed for viral replication.",
       "It suppresses the marrow by triggering antibody to platelets": "Immune thrombocytopenia is a different process.",
       "It infects megakaryocytes": "The target is the erythroid lineage.",
       "It causes splenic sequestration": "Sequestration crisis is a separate complication of sickle cell disease."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Parvovirus B19: adult arthropathy",
  "A 34-year-old teacher develops symmetric joint pain in the hands and knees and a lacy rash on the arms; her child recently had a bright red rash across both cheeks. Which statement is correct?",
  ["Adults often have arthropathy, children a cheek eruption",
   "Adults and children both present with the slapped cheek rash",
   "Joint symptoms indicate that antibiotics should be started",
   "The illness is contagious once the rash has already appeared",
   "The virus is a double-stranded RNA virus spread in stool"],
  "In children, B19 causes erythema infectiosum with slapped-cheek rash and a lacy reticular rash. Adults, particularly women, more often have symmetric polyarthropathy that can mimic rheumatoid arthritis. Patients are contagious before the rash appears, so isolation after the rash offers little benefit. B19 is a single-stranded DNA virus.",
  difficulty="medium",
  why={"Adults and children both present with the slapped cheek": "Facial rash is typical of children, not adults.",
       "Joint symptoms indicate that antibiotics should be started": "This is a viral illness and needs no antibiotics.",
       "The illness is contagious once the rash has already appeared": "Contagiousness precedes the rash.",
       "The virus is a double-stranded RNA virus": "B19 is a single-stranded DNA virus."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Smallpox vs chickenpox lesion synchrony",
  "Which feature best distinguishes the rash of smallpox from that of varicella?",
  ["Lesions all at one stage, heaviest on the face and limbs",
   "Lesions at several different stages, heaviest on the trunk",
   "Lesions confined to a single dermatome with severe pain",
   "Lesions sparing the palms and the soles in every case",
   "Lesions appearing only after the fever has fully resolved"],
  "Smallpox lesions appear in a single synchronous crop with centrifugal distribution, involving palms and soles, and are deep-seated. Varicella lesions come in successive crops, so macules, papules, vesicles, and crusts coexist, and they are centripetal, sparing palms and soles. Smallpox was declared eradicated in 1980.",
  difficulty="medium",
  why={"Lesions at several different stages": "That pattern describes varicella.",
       "Lesions confined to a single dermatome": "Dermatomal grouping describes zoster.",
       "Lesions sparing the palms and the soles": "Smallpox characteristically involves palms and soles.",
       "Lesions appearing only after the fever has fully resolved": "Fever precedes and accompanies the rash in both."},
  table=RASHES),

Q(TAG_DNA, "Adenovirus: syndromes and setting",
  "Outbreaks of pharyngoconjunctival fever in a swim club, keratoconjunctivitis in a clinic, and hemorrhagic cystitis in a transplant unit. Which virus links these?",
  ["Adenovirus",
   "Coxsackievirus A",
   "Rhinovirus",
   "Norovirus",
   "Parainfluenza virus"],
  "Adenovirus is a non-enveloped double-stranded DNA virus causing pharyngoconjunctival fever, epidemic keratoconjunctivitis, febrile pharyngitis, gastroenteritis, and hemorrhagic cystitis, plus outbreaks of pneumonia in military recruits. Its lack of an envelope makes it resistant to drying and chlorine, favoring pool and fomite spread.",
  difficulty="easy",
  why={"Coxsackievirus A": "Coxsackie A causes herpangina and hand-foot-and-mouth disease.",
       "Rhinovirus": "Rhinovirus causes the common cold without conjunctivitis outbreaks of this kind.",
       "Norovirus": "Norovirus causes outbreaks of vomiting and diarrhea.",
       "Parainfluenza virus": "Parainfluenza causes croup."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Polyomaviruses: JC vs BK",
  "Which pairing of polyomavirus and clinical setting is correct?",
  ["JC virus with demyelination in AIDS; BK with graft nephropathy",
   "JC virus with graft nephropathy; BK virus with demyelination in AIDS",
   "Both viruses cause hemorrhagic cystitis only after transplant",
   "Both viruses cause progressive dementia in immunocompetent adults",
   "JC virus with oral hairy leukoplakia; BK virus with retinitis"],
  "JC virus reactivates in severe immunosuppression and infects oligodendrocytes, causing progressive multifocal leukoencephalopathy with asymmetric white matter lesions and no enhancement; natalizumab and rituximab also raise the risk. BK virus reactivates after kidney transplant, causing nephropathy and graft dysfunction, and causes hemorrhagic cystitis after marrow transplant.",
  difficulty="medium",
  why={"JC virus with graft nephropathy": "The two associations are reversed.",
       "Both viruses cause hemorrhagic cystitis only after transplant": "JC virus targets the central nervous system.",
       "Both viruses cause progressive dementia in immunocompetent": "Disease occurs in immunosuppressed hosts.",
       "JC virus with oral hairy leukoplakia": "Hairy leukoplakia is EBV-driven and retinitis is usually CMV."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Molluscum contagiosum: management",
  "A 6-year-old has several small dome-shaped papules with central umbilication on the trunk. What is the natural history and management?",
  ["They usually resolve on their own over months",
   "They require systemic acyclovir for several weeks",
   "They indicate underlying immune deficiency in most children",
   "They must be excised widely because of malignant potential",
   "They respond only to a course of oral antifungal therapy"],
  "Molluscum contagiosum is a poxvirus infection spread by skin contact and fomites. In healthy children lesions resolve spontaneously over months to a couple of years; cryotherapy or curettage speeds clearance. Extensive facial lesions in an adult suggest HIV infection.",
  difficulty="easy",
  why={"They require systemic acyclovir": "Acyclovir has no activity against poxviruses.",
       "They indicate underlying immune deficiency in most children": "Most affected children are immunologically normal.",
       "They must be excised widely": "These lesions are benign.",
       "They respond only to a course of oral antifungal": "Antifungals have no role."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Naked vs enveloped DNA viruses",
  "Which set contains only non-enveloped DNA viruses?",
  ["Adenovirus, papillomavirus, polyomavirus, parvovirus",
   "Herpesvirus, poxvirus, hepadnavirus, and adenovirus",
   "Papillomavirus, herpesvirus, parvovirus, and poxvirus",
   "Poxvirus, adenovirus, hepadnavirus, and polyomavirus",
   "Parvovirus, herpesvirus, polyomavirus, hepadnavirus"],
  "Among DNA viruses, only the herpesviruses, poxviruses, and hepadnaviruses (HBV) are enveloped; adenoviruses, papillomaviruses, polyomaviruses, and parvoviruses are naked. Naked viruses resist drying, detergents, acid, and bile, which is why they spread by fomites and the fecal-oral route.",
  difficulty="medium",
  why={"Herpesvirus, poxvirus, hepadnavirus, and adenovirus": "The first three are all enveloped.",
       "Papillomavirus, herpesvirus, parvovirus, and poxvirus": "Herpesviruses and poxviruses are enveloped.",
       "Poxvirus, adenovirus, hepadnavirus, and polyomavirus": "Poxvirus and hepadnavirus are enveloped.",
       "Parvovirus, herpesvirus, polyomavirus, hepadnavirus": "Herpesvirus and hepadnavirus are enveloped."},
  table=DNA_VIRUSES),

Q(TAG_DNA, "Poxvirus: cytoplasmic replication",
  "Poxviruses are unique among DNA viruses in replicating entirely in the cytoplasm. What does this require the virus to carry?",
  ["Its own DNA-dependent RNA polymerase",
   "A reverse transcriptase to copy its genome",
   "An integrase to insert DNA into the host genome",
   "A neuraminidase to release progeny virions",
   "A host histone complex to package its DNA"],
  "Because poxviruses never enter the nucleus, they must encode their own DNA-dependent RNA polymerase and transcription machinery, which they carry in the virion. They are large, complex, enveloped viruses, and vaccinia is used as the smallpox and mpox vaccine platform.",
  difficulty="hard",
  why={"A reverse transcriptase to copy its genome": "Reverse transcriptase is used by retroviruses and HBV.",
       "An integrase to insert DNA": "Poxviruses do not integrate.",
       "A neuraminidase to release progeny": "Neuraminidase is an influenza protein.",
       "A host histone complex": "Poxviruses do not depend on host histones for packaging."},
  table=DNA_VIRUSES),
]
