"""RNA viruses, HIV, and hepatitis viruses in depth."""
from qcore import Q
from tables import *
TAG_RNA = "RNA Viruses"
TAG_HIV = "HIV & Antiretrovirals"
TAG_HEP = "Hepatitis Viruses"
QUESTIONS = [
# ---------------- picornaviruses & enteric ----------------
Q(TAG_RNA, "Poliovirus: anterior horn cells",
  "An unvaccinated traveler develops fever and headache, then asymmetric flaccid weakness of one leg with absent reflexes and intact sensation. Which structure is damaged?",
  ["Anterior horn motor neurons",
   "Dorsal root sensory ganglia",
   "Peripheral nerve myelin sheaths",
   "The neuromuscular junction receptors",
   "Posterior columns of the spinal cord"],
  "Poliovirus enters by the fecal-oral route, replicates in the gut and lymphoid tissue, and in a small fraction of cases reaches anterior horn cells, destroying lower motor neurons. This gives asymmetric flaccid paralysis with preserved sensation. Guillain-Barré, by contrast, is symmetric, ascending, and demyelinating.",
  difficulty="easy",
  why={"Dorsal root sensory ganglia": "Sensation is intact in poliomyelitis.",
       "Peripheral nerve myelin sheaths": "Demyelination causes symmetric ascending weakness.",
       "The neuromuscular junction receptors": "Junction disease causes fatigable weakness without reflex loss early.",
       "Posterior columns of the spinal cord": "Posterior column disease causes sensory ataxia."}),

Q(TAG_RNA, "Polio vaccines: OPV vs IPV tradeoff",
  "Why do many countries use inactivated polio vaccine rather than oral polio vaccine, despite the oral vaccine producing better mucosal immunity?",
  ["The oral vaccine can revert and cause paralytic disease",
   "The oral vaccine fails to produce any serum antibody",
   "The inactivated vaccine also prevents all virus shedding",
   "The oral vaccine cannot be given to children under five",
   "The inactivated vaccine provides immunity after one dose"],
  "Live attenuated oral vaccine gives strong intestinal IgA and interrupts transmission, but it can revert to neurovirulence, causing vaccine-associated paralytic polio, and it is contraindicated in immunodeficiency. Inactivated vaccine is safe and produces IgG but less mucosal immunity, so it protects the individual while allowing some gut replication.",
  why={"The oral vaccine fails to produce any serum antibody": "It produces both serum and mucosal antibody.",
       "The inactivated vaccine also prevents all virus shedding": "IPV gives less mucosal protection, so shedding can occur.",
       "The oral vaccine cannot be given to children under five": "Its usual recipients are young children.",
       "The inactivated vaccine provides immunity after one dose": "IPV requires a multi-dose series."},
  table=VACCINES),

Q(TAG_RNA, "Coxsackie B: myocarditis",
  "A 20-year-old has chest pain and dyspnea two weeks after a flu-like illness. Troponin is elevated, ECG shows diffuse ST changes, and the ejection fraction is 35% with normal coronary arteries. Which virus is the classic cause?",
  ["Coxsackievirus B",
   "Rhinovirus",
   "Rotavirus",
   "Norovirus",
   "Hepatitis A virus"],
  "Coxsackie B is the classic cause of viral myocarditis and pericarditis, and it also causes pleurodynia (Bornholm disease) and aseptic meningitis. Coxsackie A causes herpangina and hand-foot-and-mouth disease. Both are non-enveloped, positive-sense single-stranded RNA enteroviruses spread by the fecal-oral route.",
  difficulty="easy",
  why={"Rhinovirus": "Rhinovirus is limited to the upper airway by its temperature preference.",
       "Rotavirus": "Rotavirus causes infant gastroenteritis.",
       "Norovirus": "Norovirus causes outbreaks of vomiting and diarrhea.",
       "Hepatitis A virus": "HAV is an enterovirus-like picornavirus but targets the liver."},
  table=RNA_FAMILIES),

Q(TAG_RNA, "Rhinovirus: temperature and acid lability",
  "Why does rhinovirus cause only upper respiratory disease and not enteric infection, unlike other picornaviruses?",
  ["It prefers 33°C and is inactivated by stomach acid",
   "It prefers 37°C and is resistant to stomach acid",
   "It has an envelope that stomach bile dissolves",
   "It requires a receptor found only in the alveoli",
   "It replicates only inside lymphoid germinal centers"],
  "Rhinovirus grows best at the cooler temperature of the nasal passages (about 33°C) and is acid-labile, so it cannot survive gastric passage. It binds ICAM-1 on respiratory epithelium. With over 100 serotypes, immunity is type-specific and reinfection is common, which is why there is no vaccine.",
  difficulty="medium",
  why={"It prefers 37°C and is resistant to stomach acid": "Those properties describe the enteroviruses.",
       "It has an envelope that stomach bile dissolves": "Picornaviruses are non-enveloped.",
       "It requires a receptor found only in the alveoli": "ICAM-1 is widely expressed on upper airway cells.",
       "It replicates only inside lymphoid germinal centers": "Replication occurs in respiratory epithelium."},
  table=RNA_FAMILIES),

Q(TAG_RNA, "Norovirus: outbreak control",
  "An outbreak of vomiting and diarrhea sweeps through a cruise ship. Alcohol hand gel dispensers are everywhere. Which measure is most effective?",
  ["Handwashing with soap and water plus bleach wipes",
   "Increasing the use of alcohol-based hand sanitizer",
   "Prophylactic azithromycin for all passengers aboard",
   "Restricting only the passengers who report symptoms",
   "Switching to a bottled water supply for the ship"],
  "Norovirus is non-enveloped and resists alcohol, so soap-and-water handwashing and bleach-based surface disinfection are needed. Its very low infectious dose, environmental stability, and prolonged shedding make outbreaks explosive. Asymptomatic and recovering people still shed, so isolating only symptomatic passengers is insufficient.",
  difficulty="easy",
  why={"Increasing the use of alcohol-based hand sanitizer": "Alcohol is relatively ineffective against non-enveloped viruses.",
       "Prophylactic azithromycin for all passengers": "Antibiotics do not affect viruses.",
       "Restricting only the passengers who report symptoms": "Shedding continues after symptoms resolve.",
       "Switching to a bottled water supply": "Spread is mainly person-to-person and via surfaces."},
  table=DIARRHEA),

Q(TAG_RNA, "Rotavirus: mechanism and vaccine caution",
  "A 9-month-old has profuse watery diarrhea in winter. Which statement about the responsible virus and its vaccine is correct?",
  ["NSP4 acts as an enterotoxin; the vaccine is live and oral",
   "NSP4 acts as an enterotoxin; the vaccine is inactivated",
   "The virus invades the colon; the vaccine is given by injection",
   "The virus is a naked DNA virus; the vaccine uses capsid protein",
   "The virus destroys colonocytes; the vaccine is contraindicated in all infants"],
  "Rotavirus is a naked, segmented double-stranded RNA virus that destroys small bowel villous tips, causing osmotic diarrhea, and its NSP4 protein acts as a viral enterotoxin driving secretion. The vaccine is live attenuated and oral; it is associated with a small increase in intussusception risk and is avoided in infants with a history of intussusception or SCID.",
  why={"NSP4 acts as an enterotoxin; the vaccine is inactivated": "The rotavirus vaccine is live attenuated.",
       "The virus invades the colon": "It infects the small intestine.",
       "The virus is a naked DNA virus": "Rotavirus is a double-stranded RNA virus.",
       "The virus destroys colonocytes": "The vaccine is routinely given to healthy infants."},
  table=VACCINES),

# ---------------- influenza & paramyxo ----------------
Q(TAG_RNA, "Influenza: drift vs shift consequences",
  "Which statement correctly contrasts antigenic drift and antigenic shift in influenza?",
  ["Drift causes seasonal epidemics; shift can cause pandemics",
   "Drift can cause pandemics; shift causes seasonal epidemics",
   "Both result from reassortment of segmented genomes",
   "Both result from point mutations during replication",
   "Drift occurs only in influenza B and shift only in influenza A"],
  "Drift is the gradual accumulation of point mutations in hemagglutinin and neuraminidase, producing seasonal epidemics and requiring annual vaccine updates. Shift is reassortment of whole genome segments between human and animal strains, creating a novel subtype against which populations have no immunity, which can cause a pandemic. Only influenza A undergoes shift.",
  difficulty="easy",
  why={"Drift can cause pandemics; shift causes seasonal": "The two are reversed.",
       "Both result from reassortment": "Drift is mutation, not reassortment.",
       "Both result from point mutations": "Shift requires segment exchange.",
       "Drift occurs only in influenza B": "Both A and B drift; only A shifts."},
  table=RNA_FAMILIES),

Q(TAG_RNA, "Oseltamivir vs baloxavir mechanisms",
  "Which pairing of influenza antiviral and target is correct?",
  ["Oseltamivir blocks neuraminidase; baloxavir blocks endonuclease",
   "Oseltamivir blocks endonuclease; baloxavir blocks neuraminidase",
   "Both drugs block the viral hemagglutinin attachment step",
   "Both drugs block the M2 ion channel used for uncoating",
   "Oseltamivir blocks reverse transcriptase; baloxavir blocks protease"],
  "Oseltamivir and zanamivir inhibit neuraminidase, so progeny virions cannot be released from the cell surface. Baloxavir inhibits the cap-dependent endonuclease of the viral polymerase complex and is given as a single dose. Amantadine blocked the M2 channel but is no longer used because of widespread resistance.",
  why={"Oseltamivir blocks endonuclease": "The targets are reversed.",
       "Both drugs block the viral hemagglutinin": "Neither agent targets hemagglutinin.",
       "Both drugs block the M2 ion channel": "That was the adamantane mechanism.",
       "Oseltamivir blocks reverse transcriptase": "Influenza does not use reverse transcriptase."},
  table=RNA_FAMILIES),

Q(TAG_RNA, "Measles: immune amnesia and complications",
  "A child recovering from measles develops a bacterial pneumonia. Which mechanism links measles to increased infection risk afterward?",
  ["Depletion of memory lymphocytes for months to years",
   "Permanent destruction of bone marrow stem cell lines",
   "Autoantibody formation against neutrophil granules",
   "Complement consumption that lasts several years",
   "Loss of mucosal IgA production for the rest of life"],
  "Measles infects lymphocytes through CD150 and depletes pre-existing memory B and T cells, leaving a period of heightened susceptibility to other infections for months to years. The most common cause of death is secondary pneumonia. Vitamin A reduces mortality. Subacute sclerosing panencephalitis appears years later.",
  difficulty="hard",
  why={"Permanent destruction of bone marrow stem cell lines": "Marrow stem cells are not destroyed.",
       "Autoantibody formation against neutrophil granules": "ANCA formation is unrelated to measles.",
       "Complement consumption that lasts several years": "Complement is not persistently consumed.",
       "Loss of mucosal IgA production for the rest of life": "IgA production recovers."},
  table=PARAMYXO),

Q(TAG_RNA, "Measles: Koplik spots and prodrome",
  "Which finding appears before the measles exanthem and is most specific for the diagnosis?",
  ["Gray-white buccal lesions with a red halo",
   "Posterior auricular and occipital adenopathy",
   "Strawberry tongue with circumoral pallor",
   "Tender vesicles on the palms and soles",
   "Bilateral parotid gland swelling and pain"],
  "Koplik spots are small gray-white papules on the buccal mucosa that appear one to two days before the rash and are pathognomonic. The prodrome is the three Cs: cough, coryza, and conjunctivitis, with high fever. The rash begins at the hairline and spreads downward, becoming confluent.",
  difficulty="easy",
  why={"Posterior auricular and occipital adenopathy": "That is characteristic of rubella.",
       "Strawberry tongue with circumoral pallor": "That describes scarlet fever.",
       "Tender vesicles on the palms and soles": "That describes hand-foot-and-mouth disease.",
       "Bilateral parotid gland swelling and pain": "That describes mumps."},
  table=RASHES),

Q(TAG_RNA, "Mumps: complications by age",
  "An unvaccinated 19-year-old has bilateral parotid swelling followed by testicular pain and swelling. Which statement is correct?",
  ["Orchitis is more common after puberty and can impair fertility",
   "Orchitis is more common before puberty and always causes sterility",
   "Parotitis in mumps is usually unilateral and suppurative",
   "Aseptic meningitis never occurs with this infection",
   "Antiviral therapy shortens the course substantially"],
  "Mumps causes parotitis (typically bilateral and non-suppurative), and post-pubertal males may develop orchitis, which can reduce fertility but rarely causes sterility. Other complications are aseptic meningitis, pancreatitis, and sensorineural hearing loss. Care is supportive; the MMR vaccine prevents it.",
  difficulty="medium",
  why={"Orchitis is more common before puberty and always causes sterility": "Orchitis is a post-pubertal problem and sterility is rare.",
       "Parotitis in mumps is usually unilateral and suppurative": "It is usually bilateral and non-suppurative; suppuration suggests bacterial parotitis.",
       "Aseptic meningitis never occurs": "Aseptic meningitis is a recognized complication.",
       "Antiviral therapy shortens the course substantially": "No antiviral is effective."},
  table=PARAMYXO),

Q(TAG_RNA, "RSV: prophylaxis for high-risk infants",
  "A 2-month-old born at 29 weeks with chronic lung disease is entering RSV season. Which preventive option is appropriate?",
  ["A monoclonal antibody against the F protein",
   "A live attenuated intranasal RSV vaccine now",
   "A course of oral ribavirin through the season",
   "Monthly intravenous immunoglobulin infusions",
   "Prophylactic azithromycin during winter months"],
  "Monoclonal antibodies against the fusion (F) protein, palivizumab monthly or nirsevimab as a single dose, provide passive protection for high-risk infants. Maternal RSV vaccination is another route to infant protection. There is no live attenuated infant RSV vaccine in routine use, and ribavirin is reserved for rare severe cases.",
  difficulty="medium",
  why={"A live attenuated intranasal RSV vaccine now": "No such vaccine is used routinely in infants.",
       "A course of oral ribavirin": "Ribavirin is not used for prophylaxis.",
       "Monthly intravenous immunoglobulin infusions": "Nonspecific IVIG is not the standard approach.",
       "Prophylactic azithromycin": "Antibiotics do not prevent a viral infection."},
  table=PARAMYXO),

Q(TAG_RNA, "Croup vs bronchiolitis vs epiglottitis",
  "A 2-year-old has a barking cough, inspiratory stridor, and hoarseness that worsen at night, with a normal appetite and no drooling. Which condition and treatment fit?",
  ["Croup; dexamethasone, with epinephrine if severe",
   "Bronchiolitis; nebulized albuterol and antibiotics",
   "Epiglottitis; immediate intubation and ceftriaxone",
   "Bacterial tracheitis; vancomycin with bronchoscopy",
   "Foreign body; rigid bronchoscopy for its removal"],
  "Croup (laryngotracheobronchitis), usually from parainfluenza virus, causes subglottic narrowing with a barking cough and stridor, and the 'steeple sign' on radiograph. Treatment is dexamethasone, plus nebulized epinephrine for stridor at rest. Epiglottitis produces drooling and a toxic appearance; bronchiolitis produces wheezing in infants.",
  difficulty="easy",
  why={"Bronchiolitis; nebulized albuterol and antibiotics": "Bronchiolitis causes wheezing in younger infants and is managed supportively.",
       "Epiglottitis; immediate intubation": "Epiglottitis presents with drooling and a muffled voice.",
       "Bacterial tracheitis; vancomycin": "Tracheitis causes a toxic appearance with purulent secretions.",
       "Foreign body; rigid bronchoscopy for its removal": "Aspiration gives sudden onset with focal findings."},
  table=PARAMYXO),

Q(TAG_RNA, "Rabies: Negri bodies and progression",
  "A man bitten by a dog abroad presents two months later with agitation, hypersalivation, and pain on attempting to drink. Which statement is correct?",
  ["Once symptoms begin, the disease is nearly always fatal",
   "Post-exposure prophylaxis remains effective at this stage",
   "The virus travels through the bloodstream to the brain",
   "The illness resolves spontaneously in most patients",
   "Diagnosis requires a positive blood culture for the virus"],
  "Rabies virus travels by retrograde axonal transport from the bite site to the CNS, which is why the incubation period varies with bite location. Once encephalitic symptoms appear, survival is exceptional. Prophylaxis works only before symptoms: wound washing, rabies immune globulin into the wound, and vaccine. Negri bodies are cytoplasmic inclusions in neurons.",
  difficulty="easy",
  why={"Post-exposure prophylaxis remains effective at this stage": "Prophylaxis must precede symptom onset.",
       "The virus travels through the bloodstream": "Spread is neural, not hematogenous.",
       "The illness resolves spontaneously in most patients": "Untreated symptomatic rabies is nearly uniformly fatal.",
       "Diagnosis requires a positive blood culture": "The virus is not detected by blood culture."},
  table=RNA_FAMILIES),

Q(TAG_RNA, "Arbovirus: dengue severe disease mechanism",
  "A traveler who had dengue two years ago returns from another trip with high fever, then develops plasma leakage with hemoptysis and a falling platelet count. Which mechanism explains the severity of the second infection?",
  ["Antibody to the first serotype enhances uptake of the second",
   "Antibody to the first serotype neutralizes all four serotypes",
   "The second infection is caused by a bacterial superinfection",
   "The virus integrates into host DNA and reactivates later",
   "Cross-reactive antibody destroys platelets by direct lysis"],
  "Antibody-dependent enhancement occurs when non-neutralizing antibody from a prior dengue serotype binds a new serotype and promotes Fc receptor-mediated uptake into monocytes, raising viral load and cytokine release. Severe dengue features plasma leakage, hemorrhage, and shock. This is why dengue vaccination strategy depends on prior infection status.",
  difficulty="hard",
  why={"Antibody to the first serotype neutralizes all four": "Cross-protection is incomplete and transient.",
       "The second infection is caused by a bacterial superinfection": "Severe dengue is a viral and immune phenomenon.",
       "The virus integrates into host DNA": "Flaviviruses do not integrate.",
       "Cross-reactive antibody destroys platelets by direct lysis": "Thrombocytopenia is multifactorial, not simple antibody lysis."},
  table=ARBO),

Q(TAG_RNA, "Yellow fever vs dengue vs chikungunya",
  "Three travelers return from the same region. One has jaundice with black vomit, one has severe joint pains lasting months, and one has retro-orbital pain with a falling platelet count. Which set of diagnoses fits?",
  ["Yellow fever, chikungunya, dengue",
   "Dengue, yellow fever, chikungunya",
   "Chikungunya, dengue, yellow fever",
   "Yellow fever, dengue, chikungunya",
   "Chikungunya, yellow fever, dengue"],
  "Yellow fever causes hepatic necrosis with jaundice and hematemesis (black vomit) and has a live attenuated vaccine. Chikungunya causes prominent, often prolonged polyarthralgia. Dengue causes retro-orbital pain, myalgia, thrombocytopenia, and, in severe cases, plasma leakage. All three are transmitted by Aedes mosquitoes.",
  difficulty="medium",
  why={"Dengue, yellow fever, chikungunya": "The order does not match the described features.",
       "Chikungunya, dengue, yellow fever": "The jaundice case is yellow fever, not chikungunya.",
       "Yellow fever, dengue, chikungunya": "Prolonged arthralgia points to chikungunya, not dengue.",
       "Chikungunya, yellow fever, dengue": "The first patient has hepatic disease typical of yellow fever."},
  table=ARBO),

Q(TAG_RNA, "Zika: congenital and sexual transmission",
  "Which features distinguish Zika virus from other flaviviruses in a pregnant traveler?",
  ["Fetal microcephaly and transmission through semen",
   "Fetal hydrops and transmission by blood transfusion only",
   "Congenital cataracts and transmission by breast milk only",
   "Fetal limb hypoplasia and transmission by the fecal-oral route",
   "Neonatal hepatitis and transmission by contaminated water"],
  "Zika is transmitted by Aedes mosquitoes but also sexually and vertically, and it can persist in semen for months. Congenital Zika syndrome includes microcephaly, intracranial calcifications, and eye abnormalities. Guillain-Barré syndrome is a recognized complication in adults. Pregnant travelers avoid endemic areas.",
  difficulty="medium",
  why={"Fetal hydrops and transmission by blood transfusion only": "Hydrops is a parvovirus B19 feature.",
       "Congenital cataracts and transmission by breast milk only": "Cataracts point to congenital rubella.",
       "Fetal limb hypoplasia and transmission by the fecal-oral route": "Limb hypoplasia follows congenital varicella.",
       "Neonatal hepatitis and transmission by contaminated water": "This pattern does not describe Zika."},
  table=ARBO),

Q(TAG_RNA, "Segmented genomes: which viruses",
  "Which group of viruses has segmented genomes, permitting reassortment?",
  ["Bunyaviruses, orthomyxoviruses, arenaviruses, reoviruses",
   "Paramyxoviruses, rhabdoviruses, coronaviruses, flaviviruses",
   "Picornaviruses, caliciviruses, togaviruses, retroviruses",
   "Herpesviruses, adenoviruses, poxviruses, parvoviruses",
   "Coronaviruses, filoviruses, hepeviruses, astroviruses"],
  "Mnemonic BOAR: Bunyaviruses, Orthomyxoviruses, Arenaviruses, and Reoviruses have segmented genomes, so co-infection can produce reassortment, the basis of influenza antigenic shift. Non-segmented RNA viruses change only through mutation and recombination.",
  difficulty="medium",
  why={"Paramyxoviruses, rhabdoviruses, coronaviruses, flaviviruses": "These all have non-segmented genomes.",
       "Picornaviruses, caliciviruses, togaviruses, retroviruses": "These are non-segmented, although retroviruses are diploid.",
       "Herpesviruses, adenoviruses, poxviruses, parvoviruses": "These are DNA viruses without segments.",
       "Coronaviruses, filoviruses, hepeviruses, astroviruses": "All are non-segmented."},
  table=RNA_FAMILIES),

Q(TAG_RNA, "Prions: mechanism of disease",
  "A 62-year-old has rapidly progressive dementia, startle myoclonus, and periodic sharp waves on EEG, dying within eight months. What is the molecular basis?",
  ["A misfolded beta-sheet protein templating others",
   "A defective virus that requires a helper to replicate",
   "A circular RNA that silences host gene expression",
   "A retrovirus integrating into neuronal chromosomes",
   "An autoantibody directed against neuronal receptors"],
  "Prion diseases result from conversion of normal alpha-helical PrPc into beta-sheet-rich PrPsc, which is protease-resistant, aggregates, and templates further misfolding. Creutzfeldt-Jakob disease is usually sporadic; variant CJD follows exposure to bovine material, and kuru followed ritual cannibalism. Prions resist standard autoclaving and formalin.",
  difficulty="medium",
  why={"A defective virus that requires a helper": "That describes hepatitis D virus.",
       "A circular RNA that silences host gene expression": "Viroids of that kind infect plants.",
       "A retrovirus integrating into neuronal chromosomes": "No nucleic acid is involved in prion transmission.",
       "An autoantibody directed against neuronal receptors": "That describes autoimmune encephalitis."}),

# ---------------- HIV ----------------
Q(TAG_HIV, "HIV: diagnostic algorithm",
  "A patient has a fourth-generation HIV antigen/antibody test that is reactive, and the supplemental antibody differentiation assay is negative. What is the next step?",
  ["Perform an HIV RNA test to detect acute infection",
   "Report the result as a false positive and stop testing",
   "Repeat the same screening test in six months",
   "Start antiretroviral therapy without further testing",
   "Order a CD4 count to establish the diagnosis"],
  "A reactive antigen/antibody screen with a negative antibody differentiation assay suggests acute infection, when p24 antigen is present before antibodies develop. HIV RNA testing resolves this: a positive RNA confirms acute infection. CD4 counts stage disease but never diagnose it.",
  difficulty="medium",
  why={"Report the result as a false positive and stop testing": "Acute infection must be excluded first.",
       "Repeat the same screening test in six months": "Delay would miss highly infectious acute infection.",
       "Start antiretroviral therapy without further testing": "Confirmation precedes treatment.",
       "Order a CD4 count to establish the diagnosis": "CD4 counts do not diagnose HIV."},
  table=HIV_DRUGS),

Q(TAG_HIV, "HIV: acute retroviral syndrome",
  "A 25-year-old has fever, sore throat, diffuse adenopathy, a maculopapular rash, and oral ulcers two weeks after a new sexual partner. A rapid antibody test is negative. Which test confirms the suspected diagnosis?",
  ["Plasma HIV RNA quantification",
   "Western blot for HIV antibodies",
   "Heterophile antibody agglutination",
   "CD4 to CD8 ratio measurement",
   "Rapid plasma reagin titer testing"],
  "Acute HIV infection mimics mononucleosis, with mucocutaneous ulcers being a useful clue. Antibody tests may still be negative during the window period, so HIV RNA (or a p24 antigen-containing assay) is required. Recognizing acute infection matters because viral load and transmissibility are very high.",
  difficulty="medium",
  why={"Western blot for HIV antibodies": "Antibody testing is negative during the window period.",
       "Heterophile antibody agglutination": "This tests for EBV, which is the mimic to exclude.",
       "CD4 to CD8 ratio measurement": "The ratio is nonspecific and not diagnostic.",
       "Rapid plasma reagin titer testing": "RPR screens for syphilis."},
  table=HIV_DRUGS),

Q(TAG_HIV, "HIV: NRTI toxicities",
  "Which pairing of nucleoside reverse transcriptase inhibitor and characteristic adverse effect is correct?",
  ["Zidovudine with marrow suppression; tenofovir with renal harm",
   "Zidovudine with renal injury; tenofovir with marrow suppression",
   "Abacavir with optic neuritis; lamivudine with pancreatitis",
   "Emtricitabine with cardiomyopathy; abacavir with deafness",
   "Tenofovir with red-green color blindness; lamivudine with gout"],
  "Zidovudine causes anemia, neutropenia, and myopathy. Tenofovir disoproxil causes proximal tubular injury with Fanconi syndrome and reduced bone density; the alafenamide prodrug is gentler. Abacavir can cause a severe hypersensitivity reaction tied to HLA-B*57:01, which is screened for before use. Lamivudine and emtricitabine are well tolerated.",
  difficulty="medium",
  why={"Zidovudine with renal injury": "The toxicities are reversed.",
       "Abacavir with optic neuritis": "Abacavir causes hypersensitivity, and optic neuritis is an ethambutol effect.",
       "Emtricitabine with cardiomyopathy": "Neither association is correct.",
       "Tenofovir with red-green color blindness": "Color vision loss is caused by ethambutol."},
  table=HIV_DRUGS),

Q(TAG_HIV, "HIV: abacavir hypersensitivity screening",
  "Before starting abacavir, which test must be performed?",
  ["HLA-B allele genotyping before the first dose",
   "Glucose-6-phosphate dehydrogenase assay",
   "Thiopurine methyltransferase activity",
   "CYP2C19 loss-of-function genotyping",
   "Serum tryptase baseline measurement"],
  "Abacavir hypersensitivity presents with fever, rash, and gastrointestinal and respiratory symptoms and can be fatal on re-challenge. It is strongly associated with HLA-B*57:01, so genotyping before use is mandatory and the drug is avoided in carriers.",
  difficulty="easy",
  why={"Glucose-6-phosphate dehydrogenase assay": "G6PD testing relates to dapsone, primaquine, and sulfonamides.",
       "Thiopurine methyltransferase activity": "TPMT testing precedes azathioprine and mercaptopurine.",
       "CYP2C19 loss-of-function genotyping": "That genotype affects clopidogrel and voriconazole.",
       "Serum tryptase baseline measurement": "Tryptase assesses mast cell disorders."},
  table=HIV_DRUGS),

Q(TAG_HIV, "HIV: integrase inhibitor suffix logic",
  "A regimen contains bictegravir, emtricitabine, and tenofovir alafenamide. Which drug classes are represented?",
  ["An integrase inhibitor with two nucleoside analogs",
   "A protease inhibitor with two nucleoside analogs",
   "Two integrase inhibitors with one protease inhibitor",
   "A fusion inhibitor with two non-nucleoside analogs",
   "A CCR5 antagonist with two integrase inhibitors"],
  "Drug name suffixes give the class: -gravir for integrase strand transfer inhibitors, -navir for protease inhibitors, -virine for NNRTIs, and -viroc for CCR5 antagonists. Integrase inhibitor-based regimens with two NRTIs are first-line because of potency, tolerability, and few interactions.",
  difficulty="easy",
  why={"A protease inhibitor with two nucleoside analogs": "Protease inhibitor names end in -navir.",
       "Two integrase inhibitors with one protease inhibitor": "Only one integrase inhibitor is present.",
       "A fusion inhibitor with two non-nucleoside analogs": "Enfuvirtide is the fusion inhibitor, and no NNRTI is present.",
       "A CCR5 antagonist with two integrase inhibitors": "Maraviroc is the CCR5 antagonist and is not in this regimen."},
  table=HIV_DRUGS),

Q(TAG_HIV, "HIV: maraviroc and tropism testing",
  "Why must a tropism assay be performed before prescribing maraviroc?",
  ["It works only against strains that use the CCR5 co-receptor",
   "It works only against strains resistant to integrase inhibitors",
   "It requires confirmation that the CD4 count exceeds 500 cells",
   "It must be matched to the viral subtype found in the patient",
   "It is effective only when the viral load is below detection"],
  "Maraviroc blocks the CCR5 co-receptor, so it has no activity against CXCR4-tropic (X4) or dual-tropic virus. A tropism assay identifies patients whose virus is exclusively R5-tropic. The CCR5-delta32 homozygous genotype confers natural resistance to R5 strains.",
  difficulty="hard",
  why={"It works only against strains resistant to integrase inhibitors": "Its activity is unrelated to integrase resistance.",
       "It requires confirmation that the CD4 count exceeds 500": "CD4 count does not determine eligibility.",
       "It must be matched to the viral subtype": "Subtype is not the determinant; co-receptor use is.",
       "It is effective only when the viral load is below detection": "It is used to reduce viral load."},
  table=HIV_DRUGS),

Q(TAG_HIV, "HIV: opportunistic infection thresholds",
  "Which pairing of CD4 count threshold and characteristic opportunistic infection is correct?",
  ["Below 200 for Pneumocystis; below 50 for CMV retinitis",
   "Below 50 for Pneumocystis; below 200 for CMV retinitis",
   "Below 500 for cryptococcal meningitis; below 400 for MAC",
   "Below 350 for toxoplasmosis; below 300 for CMV retinitis",
   "Below 100 for oral candidiasis; below 50 for tuberculosis"],
  "Pneumocystis pneumonia becomes a risk below 200 cells/µL, which is also when prophylaxis with TMP-SMX begins. Toxoplasmosis and cryptococcal disease cluster below 100, and CMV retinitis and disseminated MAC appear below 50. Tuberculosis can occur at any CD4 count.",
  difficulty="easy",
  why={"Below 50 for Pneumocystis": "The thresholds are reversed.",
       "Below 500 for cryptococcal meningitis": "Cryptococcal disease occurs at much lower counts.",
       "Below 350 for toxoplasmosis": "Toxoplasmic encephalitis occurs below about 100.",
       "Below 100 for oral candidiasis": "Thrush occurs at higher counts, and tuberculosis occurs at any count."},
  table=HIV_OI),

Q(TAG_HIV, "HIV: IRIS recognition",
  "Two weeks after starting antiretroviral therapy with a CD4 count of 40, a patient with treated cryptococcal meningitis develops worsening headache with a higher CSF white count but negative cultures. What is happening?",
  ["Immune reconstitution inflammatory syndrome",
   "Antiretroviral drug failure with resistance",
   "A second bacterial meningitis superinfection",
   "Direct neurotoxicity of the antiretroviral drugs",
   "Relapse from inadequate antifungal dosing"],
  "IRIS occurs as recovering immunity mounts an inflammatory response against residual antigen from a treated or subclinical infection, typically within weeks to months of starting therapy at a low CD4 count. Cultures are negative because this is inflammation, not uncontrolled infection. Antiretrovirals are usually continued, with steroids in severe cases.",
  difficulty="medium",
  why={"Antiretroviral drug failure with resistance": "Failure would show a rising viral load rather than sterile inflammation.",
       "A second bacterial meningitis superinfection": "Cultures are negative and the timing fits IRIS.",
       "Direct neurotoxicity of the antiretroviral drugs": "This pattern is not a recognized drug toxicity.",
       "Relapse from inadequate antifungal dosing": "Relapse would typically yield positive cultures."},
  table=HIV_OI),

Q(TAG_HIV, "HIV: perinatal prevention steps",
  "A pregnant woman newly diagnosed with HIV has a viral load of 40,000 copies/mL at 36 weeks. Which measures reduce transmission to the infant?",
  ["Antiretrovirals now, cesarean delivery, and infant prophylaxis",
   "Antiretrovirals only after delivery, with breastfeeding encouraged",
   "Vaginal delivery regardless of viral load, with no infant therapy",
   "A single dose of nevirapine at delivery as the only intervention",
   "Deferring all therapy until the infant's testing is completed"],
  "Perinatal transmission is reduced by maternal antiretroviral therapy to suppress viral load, scheduled cesarean delivery when the viral load exceeds 1,000 copies/mL near term, intrapartum zidovudine, infant postexposure prophylaxis, and avoidance of breastfeeding where formula is safe. Combined, these lower transmission to about 1%.",
  difficulty="medium",
  why={"Antiretrovirals only after delivery": "Suppression before and during delivery is essential.",
       "Vaginal delivery regardless of viral load": "Cesarean delivery is recommended with high viral loads.",
       "A single dose of nevirapine at delivery": "Single-dose strategies are inferior and risk resistance.",
       "Deferring all therapy until the infant's testing": "Prevention must occur before and at delivery."},
  table=HIV_DRUGS),

# ---------------- hepatitis ----------------
Q(TAG_HEP, "HBV serologic patterns: acute vs chronic vs vaccinated",
  "A patient has a positive surface antibody and a positive core antibody, with negative surface antigen. How is this interpreted?",
  ["Resolved prior infection with immunity",
   "Successful vaccination without infection",
   "Active chronic infection with high infectivity",
   "The window period of acute infection",
   "Chronic infection in the inactive carrier state"],
  "Anti-HBs indicates immunity; anti-HBc indicates that natural infection occurred, since the vaccine contains only surface antigen. Both positive with a negative HBsAg means resolved infection. Vaccination gives anti-HBs alone. The window period has anti-HBc (IgM) with neither antigen nor surface antibody detectable.",
  difficulty="easy",
  why={"Successful vaccination without infection": "Vaccination does not produce core antibody.",
       "Active chronic infection with high infectivity": "Chronic infection has persistent surface antigen.",
       "The window period of acute infection": "In the window period, surface antibody has not yet appeared.",
       "Chronic infection in the inactive carrier state": "Carriers remain surface antigen-positive."},
  table=HBV_SEROLOGY),

Q(TAG_HEP, "HBV: e antigen meaning",
  "A patient with chronic hepatitis B has a positive e antigen and an HBV DNA level above 10 million IU/mL. What does the e antigen indicate?",
  ["Active viral replication and high infectivity",
   "Resolution of infection with developing immunity",
   "A vaccine response rather than natural infection",
   "Coinfection with hepatitis D virus specifically",
   "Immunity to reinfection with other genotypes"],
  "HBeAg is a marker of active replication and high infectivity, including high risk of perinatal transmission. Seroconversion to anti-HBe usually accompanies falling viral loads. Precore mutants can replicate actively while HBeAg-negative, so viral load is measured alongside serology.",
  difficulty="medium",
  why={"Resolution of infection with developing immunity": "That is signaled by anti-HBs and anti-HBe.",
       "A vaccine response rather than natural infection": "The vaccine contains surface antigen only.",
       "Coinfection with hepatitis D virus": "HDV requires separate antibody or RNA testing.",
       "Immunity to reinfection with other genotypes": "HBeAg is not a marker of immunity."},
  table=HBV_SEROLOGY),

Q(TAG_HEP, "HBV: reverse transcriptase and integration",
  "Hepatitis B is a DNA virus, yet it uses reverse transcriptase. Where does this step fit in its replication?",
  ["A pregenomic RNA is copied back into DNA",
   "Genomic DNA is copied directly into new DNA",
   "Viral RNA is integrated by an integrase enzyme",
   "Host mRNA is reverse transcribed into a provirus",
   "The genome is translated directly into structural proteins"],
  "HBV transcribes its partially double-stranded circular DNA into a pregenomic RNA, which is reverse transcribed back into DNA inside the capsid. This explains why nucleoside analogs such as tenofovir and entecavir are effective and why HBV shares risk of resistance with HIV drugs. HBV DNA can also integrate, contributing to hepatocellular carcinoma even without cirrhosis.",
  difficulty="hard",
  why={"Genomic DNA is copied directly into new DNA": "An RNA intermediate is obligatory.",
       "Viral RNA is integrated by an integrase enzyme": "HBV has no integrase; integration is incidental.",
       "Host mRNA is reverse transcribed into a provirus": "The template is viral pregenomic RNA.",
       "The genome is translated directly into structural proteins": "DNA is not translated directly."},
  table=HEPATITIS),

Q(TAG_HEP, "HBV: who needs treatment",
  "Which chronic hepatitis B patient most clearly needs antiviral therapy?",
  ["One with cirrhosis and detectable HBV DNA",
   "One with normal enzymes and undetectable DNA",
   "One who is anti-HBs positive after vaccination",
   "One with isolated anti-HBc and no other markers",
   "One with resolved infection and normal imaging"],
  "Treatment is indicated for cirrhosis with any detectable HBV DNA, and for active hepatitis with elevated ALT and high viral load. Entecavir and tenofovir are first-line. Inactive carriers with normal enzymes and low DNA are monitored. All chronic patients need hepatocellular carcinoma surveillance.",
  difficulty="medium",
  why={"One with normal enzymes and undetectable DNA": "This is the inactive carrier state, which is monitored.",
       "One who is anti-HBs positive after vaccination": "This person is immune, not infected.",
       "One with isolated anti-HBc and no other markers": "This usually reflects remote resolved infection.",
       "One with resolved infection and normal imaging": "Resolved infection needs no antiviral therapy."},
  table=HEPATITIS),

Q(TAG_HEP, "HDV: coinfection vs superinfection",
  "Which statement contrasts hepatitis D coinfection with superinfection?",
  ["Superinfection of a chronic carrier causes more severe disease",
   "Coinfection with hepatitis B causes more severe chronic disease",
   "Superinfection occurs only in people vaccinated against hepatitis B",
   "Coinfection requires no hepatitis B surface antigen at all",
   "Both patterns resolve spontaneously without any sequelae"],
  "HDV is a defective virus that needs HBsAg as its envelope, so it infects only people with hepatitis B. Simultaneous coinfection usually resolves as the HBV does; superinfection of an established chronic carrier causes severe acute exacerbation and accelerated progression to cirrhosis. Hepatitis B vaccination prevents both.",
  difficulty="medium",
  why={"Coinfection with hepatitis B causes more severe chronic disease": "Coinfection typically follows the course of the acute HBV infection.",
       "Superinfection occurs only in people vaccinated": "Vaccination prevents HDV by preventing HBV.",
       "Coinfection requires no hepatitis B surface antigen": "HDV depends on HBsAg entirely.",
       "Both patterns resolve spontaneously without any sequelae": "Superinfection frequently leads to cirrhosis."},
  table=HEPATITIS),

Q(TAG_HEP, "HEV: pregnancy mortality and zoonosis",
  "Which feature distinguishes hepatitis E from hepatitis A?",
  ["High mortality in pregnancy and a swine reservoir",
   "High mortality in children and a rodent reservoir",
   "Chronic infection in all healthy hosts after exposure",
   "Transmission by sexual contact and shared needles",
   "Availability of a routine vaccine in most countries"],
  "Both HAV and HEV are enterically transmitted and usually self-limited, but HEV carries mortality up to 20% in the third trimester of pregnancy and has zoonotic reservoirs, particularly pigs and deer. Chronic HEV occurs in organ transplant recipients. A vaccine exists but is not widely available; HAV has a widely used vaccine.",
  difficulty="medium",
  why={"High mortality in children and a rodent reservoir": "The risk group is pregnant women, and pigs are the reservoir.",
       "Chronic infection in all healthy hosts": "Chronic infection occurs only with immunosuppression.",
       "Transmission by sexual contact and shared needles": "Those are bloodborne routes for HBV and HCV.",
       "Availability of a routine vaccine in most countries": "The HEV vaccine is not widely available."},
  table=HEPATITIS),

Q(TAG_HEP, "HCV: why no vaccine",
  "Which property of hepatitis C virus most explains the absence of an effective vaccine?",
  ["High mutation rate producing many envelope variants",
   "Integration of viral DNA into the host chromosome",
   "Latency in dorsal root ganglia between recurrences",
   "Lack of any envelope protein to target with antibody",
   "Replication exclusively inside bile duct epithelium"],
  "HCV has no proofreading in its RNA-dependent RNA polymerase, so hypervariable envelope regions change constantly, producing quasispecies that escape neutralizing antibody. This is also why most infections become chronic. Direct-acting antivirals now cure over 95%, targeting NS3/4A protease (-previr), NS5A (-asvir), and NS5B polymerase (-buvir).",
  difficulty="medium",
  why={"Integration of viral DNA into the host chromosome": "HCV does not integrate.",
       "Latency in dorsal root ganglia": "Ganglionic latency is a herpesvirus property.",
       "Lack of any envelope protein": "HCV is enveloped with E1 and E2 glycoproteins.",
       "Replication exclusively inside bile duct epithelium": "It replicates in hepatocytes."},
  table=HCV_DAA),

Q(TAG_HEP, "HCV: extrahepatic manifestations",
  "A patient with chronic hepatitis C has palpable purpura, arthralgia, neuropathy, and glomerulonephritis, with low complement and a positive rheumatoid factor. Which mechanism explains this?",
  ["Cryoglobulin immune complexes deposit in small vessels",
   "Direct viral invasion of vascular endothelial cells",
   "Antibody directed against the glomerular basement membrane",
   "Granulomatous inflammation of medium-sized arteries",
   "IgA deposition in the mesangium after mucosal infection"],
  "Mixed cryoglobulinemia is the classic extrahepatic manifestation of HCV: immune complexes containing IgM rheumatoid factor and IgG precipitate in the cold and deposit in small vessels, producing purpura, arthralgia, neuropathy, and membranoproliferative glomerulonephritis. Treating the virus treats the vasculitis. HCV is also linked to porphyria cutanea tarda and lichen planus.",
  difficulty="hard",
  why={"Direct viral invasion of vascular endothelial cells": "The vasculitis is immune complex-mediated.",
       "Antibody directed against the glomerular basement membrane": "That describes anti-GBM disease.",
       "Granulomatous inflammation of medium-sized arteries": "That describes polyarteritis or granulomatous vasculitis.",
       "IgA deposition in the mesangium": "That describes IgA nephropathy."},
  table=HEPATITIS),

Q(TAG_HEP, "Hepatitis A: post-exposure options",
  "A 45-year-old healthy man ate at a restaurant where a food handler has confirmed hepatitis A ten days ago. Which post-exposure measure is preferred?",
  ["Hepatitis A vaccine given as a single dose",
   "Hepatitis A immune globulin used alone always",
   "A course of oral ribavirin for two weeks",
   "Hepatitis B immune globulin plus vaccine",
   "No intervention, since exposure was by food"],
  "Post-exposure prophylaxis within two weeks prevents or attenuates hepatitis A. For healthy people aged 12 months to 40 years, vaccine alone is preferred; immune globulin is favored for infants under 12 months, adults over 40, immunocompromised patients, and those with chronic liver disease. HAV causes no chronic infection.",
  difficulty="medium",
  why={"Hepatitis A immune globulin used alone always": "Immune globulin is reserved for specific groups.",
       "A course of oral ribavirin": "Ribavirin has no role in hepatitis A.",
       "Hepatitis B immune globulin plus vaccine": "That is hepatitis B exposure management.",
       "No intervention, since exposure was by food": "Foodborne exposure is exactly the indication."},
  table=HEPATITIS),
]
