"""Fungi, antifungals, protozoa, and helminths in depth."""
from qcore import Q
from tables import *
TAG_FUNGI = "Fungi & Antifungals"
TAG_PROT = "Protozoa"
TAG_HELM = "Helminths"
QUESTIONS = [
# ---------------- fungi ----------------
Q(TAG_FUNGI, "Candida: germ tube test",
  "A yeast from a blood culture forms true germ tubes within three hours in serum at 37°C. Which species is identified?",
  ["Candida albicans",
   "Candida glabrata",
   "Candida krusei",
   "Cryptococcus neoformans",
   "Malassezia furfur"],
  "C. albicans forms germ tubes in serum and produces chlamydospores on cornmeal agar, distinguishing it from other Candida species. This matters because C. glabrata and C. krusei are often fluconazole-resistant, so species identification guides therapy.",
  difficulty="easy",
  why={"Candida glabrata": "C. glabrata is germ tube-negative and often fluconazole-resistant.",
       "Candida krusei": "C. krusei is germ tube-negative and intrinsically fluconazole-resistant.",
       "Cryptococcus neoformans": "Cryptococcus is an encapsulated yeast that does not form germ tubes.",
       "Malassezia furfur": "Malassezia requires lipid-supplemented media to grow."},
  table=OPP_FUNGI),

Q(TAG_FUNGI, "Candida: host defense layers",
  "Which pairing of immune defect and candidal syndrome is correct?",
  ["T-cell defects with mucosal disease; neutropenia with dissemination",
   "T-cell defects with dissemination; neutropenia with mucocutaneous disease",
   "Complement deficiency with thrush; asplenia with candidemia",
   "IgA deficiency with candidemia; T-cell defects with onychomycosis",
   "Neutropenia with thrush only; B-cell defects with deep organ disease"],
  "T cells control Candida at mucosal surfaces, so HIV, steroid use, and chronic mucocutaneous candidiasis produce thrush and esophagitis. Neutrophils prevent tissue invasion and bloodstream spread, so neutropenia, central lines, and broad-spectrum antibiotics lead to candidemia and disseminated disease with retinal and hepatosplenic lesions.",
  difficulty="medium",
  why={"T-cell defects with dissemination": "The two defenses are reversed.",
       "Complement deficiency with thrush": "Complement defects predispose to Neisseria.",
       "IgA deficiency with candidemia": "IgA deficiency causes sinopulmonary and gastrointestinal infections.",
       "Neutropenia with thrush only": "Neutropenia carries a risk of invasive disease, not just thrush."},
  table=IMMUNODEF),

Q(TAG_FUNGI, "Candida esophagitis vs oral thrush in HIV",
  "A man with HIV and a CD4 count of 90 has odynophagia and white plaques on the tongue. What is the appropriate next step?",
  ["Empiric fluconazole, with endoscopy if no response",
   "Immediate endoscopy with biopsy before any therapy",
   "Topical nystatin swish and swallow as sole therapy",
   "Intravenous amphotericin B for two weeks minimum",
   "Acyclovir, since ulcers in HIV are usually herpetic"],
  "Esophageal candidiasis is an AIDS-defining illness and is treated empirically with systemic fluconazole; endoscopy is reserved for patients who do not improve, to look for CMV or HSV esophagitis. Topical agents treat thrush but do not reach the esophagus adequately.",
  difficulty="medium",
  why={"Immediate endoscopy with biopsy before any therapy": "Empiric therapy is standard first, with endoscopy for failures.",
       "Topical nystatin swish and swallow as sole therapy": "Topical therapy does not treat esophageal disease.",
       "Intravenous amphotericin B for two weeks": "Amphotericin is excessive for uncomplicated esophagitis.",
       "Acyclovir, since ulcers in HIV are usually herpetic": "The plaques and clinical picture point to Candida."},
  table=HIV_OI),

Q(TAG_FUNGI, "Aspergillus: three syndromes by host",
  "Three patients have Aspergillus-related illness: an asthmatic with wheezing and high IgE, a man with an old tuberculous cavity and hemoptysis, and a neutropenic patient with a halo sign on chest CT. Which set of diagnoses fits?",
  ["ABPA, aspergilloma, invasive aspergillosis",
   "Aspergilloma, ABPA, invasive aspergillosis",
   "Invasive aspergillosis, ABPA, aspergilloma",
   "ABPA, invasive aspergillosis, aspergilloma",
   "Aspergilloma, invasive aspergillosis, ABPA"],
  "ABPA is a hypersensitivity reaction in asthma or cystic fibrosis with high IgE, eosinophilia, and central bronchiectasis, treated with steroids plus itraconazole. Aspergilloma is a fungus ball colonizing a pre-existing cavity, causing hemoptysis. Invasive aspergillosis occurs in neutropenia, with angioinvasion producing halo and air-crescent signs, treated with voriconazole.",
  difficulty="medium",
  why={"Aspergilloma, ABPA, invasive aspergillosis": "The first two are swapped.",
       "Invasive aspergillosis, ABPA, aspergilloma": "The order does not match the three hosts described.",
       "ABPA, invasive aspergillosis, aspergilloma": "The last two are swapped.",
       "Aspergilloma, invasive aspergillosis, ABPA": "The asthmatic patient has ABPA, not aspergilloma."},
  table=OPP_FUNGI),

Q(TAG_FUNGI, "Mucormycosis: risk and angioinvasion",
  "A patient in diabetic ketoacidosis has facial pain, a black eschar on the palate, and cranial nerve palsies. Biopsy shows broad ribbon-like hyphae with wide-angle branching. Which factor explains the predisposition?",
  ["Acidosis and high glucose free iron for fungal growth",
   "Neutrophilia that walls the fungus into the sinuses",
   "High insulin levels that directly promote fungal growth",
   "An absent spleen that fails to clear fungal spores",
   "Complement deficiency preventing fungal opsonization"],
  "Ketoacidosis lowers pH and reduces iron binding by transferrin, and Rhizopus has a ketone reductase that lets it thrive in this environment. It invades blood vessels, causing thrombosis and necrosis, spreading from sinuses to orbit and brain. Treatment is urgent surgical debridement plus amphotericin B and correction of the acidosis.",
  difficulty="hard",
  why={"Neutrophilia that walls the fungus": "Neutrophil dysfunction, not neutrophilia, is the problem.",
       "High insulin levels that directly promote fungal growth": "Insulin deficiency, not excess, characterizes DKA.",
       "An absent spleen that fails to clear fungal spores": "Asplenia predisposes to encapsulated bacteria.",
       "Complement deficiency preventing fungal opsonization": "Complement defects predispose to Neisseria."},
  table=OPP_FUNGI),

Q(TAG_FUNGI, "Cryptococcus: capsule and India ink",
  "A patient with AIDS has a subacute headache. CSF opening pressure is 34 cm H2O, and India ink shows round yeast with a wide clear halo. Which additional management step is essential?",
  ["Serial lumbar punctures to draw off fluid",
   "Immediate high-dose corticosteroid therapy",
   "Prompt initiation of antiretroviral therapy",
   "A ventriculoperitoneal shunt within 24 hours",
   "Empiric antituberculous therapy while awaiting cultures"],
  "Cryptococcal meningitis kills mainly through raised intracranial pressure, so repeated therapeutic lumbar punctures are essential alongside amphotericin B with flucytosine, then fluconazole. Antiretroviral therapy is deliberately delayed by a few weeks to reduce IRIS. The capsule excludes ink particles, giving the halo, and the cryptococcal antigen test is highly sensitive.",
  difficulty="hard",
  why={"Immediate high-dose corticosteroid therapy": "Steroids worsen outcomes in cryptococcal meningitis.",
       "Prompt initiation of antiretroviral therapy": "Early antiretrovirals increase IRIS-related mortality here.",
       "A ventriculoperitoneal shunt within 24 hours": "Shunting is reserved for pressure refractory to punctures.",
       "Empiric antituberculous therapy": "The India ink finding establishes the diagnosis."},
  table=OPP_FUNGI),

Q(TAG_FUNGI, "Dimorphic fungi: geography and morphology",
  "Which pairing of dimorphic fungus, region, and tissue form is correct?",
  ["Histoplasma; Ohio valley; yeast inside macrophages",
   "Histoplasma; southwestern desert; spherules with endospores",
   "Coccidioides; Mississippi valley; broad-based budding yeast",
   "Blastomyces; southwestern desert; yeast inside macrophages",
   "Paracoccidioides; Ohio valley; spherules with endospores"],
  "Histoplasma is found in the Ohio and Mississippi river valleys, in bird and bat droppings, and appears as small yeast within macrophages. Coccidioides is found in the southwestern United States and forms spherules filled with endospores. Blastomyces is found in the eastern United States and forms broad-based budding yeast. Paracoccidioides, from Latin America, forms a captain's wheel.",
  difficulty="easy",
  why={"Histoplasma; southwestern desert; spherules": "Spherules and the desert describe Coccidioides.",
       "Coccidioides; Mississippi valley; broad-based budding": "Broad-based budding describes Blastomyces.",
       "Blastomyces; southwestern desert; yeast inside macrophages": "Intracellular yeast describes Histoplasma.",
       "Paracoccidioides; Ohio valley; spherules": "Paracoccidioides is Latin American and forms a captain's wheel."},
  table=DIMORPHIC),

Q(TAG_FUNGI, "Coccidioides: erythema nodosum and dissemination risk",
  "A construction worker in Arizona develops fever, cough, arthralgia, and tender red shin nodules. Which statement about his illness is correct?",
  ["The skin nodules reflect a good immune response, not dissemination",
   "The skin nodules indicate fungal invasion of the subcutaneous fat",
   "Dissemination risk is highest in young healthy nonpregnant adults",
   "The illness always requires amphotericin B, even when mild",
   "The illness is transmitted person to person by respiratory droplets"],
  "Primary coccidioidomycosis ('valley fever') may cause erythema nodosum and erythema multiforme, which reflect vigorous cell-mediated immunity and a favorable prognosis. Dissemination risk is higher in pregnancy, immunosuppression, and in people of Filipino and African ancestry. Mild disease is often observed; fluconazole is used for more severe or disseminated illness, and meningitis requires lifelong fluconazole.",
  difficulty="hard",
  why={"The skin nodules indicate fungal invasion of the subcutaneous fat": "Erythema nodosum is a reactive panniculitis without organisms.",
       "Dissemination risk is highest in young healthy nonpregnant adults": "Risk is highest in pregnancy and immunosuppression.",
       "The illness always requires amphotericin B": "Mild disease is frequently managed without antifungals.",
       "The illness is transmitted person to person": "Infection follows inhalation of arthroconidia from soil."},
  table=DIMORPHIC),

Q(TAG_FUNGI, "Histoplasma: reactivation with TNF inhibitors",
  "A man in Missouri on infliximab for rheumatoid arthritis develops fever, weight loss, pancytopenia, and hepatosplenomegaly. Bone marrow shows small intracellular yeast. Which statement is correct?",
  ["TNF is needed to maintain granulomas that contain this fungus",
   "TNF inhibitors block neutrophil migration into infected tissue",
   "The infection reflects a new inoculation from air conditioning",
   "The finding indicates a hematologic malignancy rather than infection",
   "Reactivation occurs only in patients who also have diabetes"],
  "TNF-alpha maintains granuloma integrity, so TNF inhibitors allow reactivation of latent Histoplasma and tuberculosis. Disseminated histoplasmosis presents with fever, cytopenias, hepatosplenomegaly, and oral ulcers. The urine antigen test is sensitive, and treatment is amphotericin B followed by itraconazole. Screening before starting these drugs is standard.",
  difficulty="medium",
  why={"TNF inhibitors block neutrophil migration": "The key effect is on granuloma maintenance by macrophages and T cells.",
       "The infection reflects a new inoculation from air conditioning": "This is reactivation of latent infection in an endemic area.",
       "The finding indicates a hematologic malignancy": "Intracellular yeast establish the infectious diagnosis.",
       "Reactivation occurs only in patients who also have diabetes": "Diabetes is not required for reactivation."},
  table=DIMORPHIC),

Q(TAG_FUNGI, "Pneumocystis: diagnosis and steroid indication",
  "A man with AIDS has exertional dyspnea, diffuse ground-glass opacities, LDH of 600 U/L, and a room-air PaO2 of 62 mm Hg. Which treatment plan is correct?",
  ["TMP-SMX with adjunctive corticosteroids",
   "TMP-SMX alone, avoiding steroids entirely",
   "Fluconazole with adjunctive corticosteroids",
   "Azithromycin with ethambutol and rifabutin",
   "Amphotericin B with oral flucytosine added"],
  "Pneumocystis jirovecii pneumonia is treated with TMP-SMX. Corticosteroids are added when the PaO2 is below 70 mm Hg or the A-a gradient exceeds 35 mm Hg, because dying organisms trigger inflammation that worsens hypoxemia. Diagnosis uses induced sputum or lavage with silver or immunofluorescent staining, since the organism cannot be cultured.",
  difficulty="medium",
  why={"TMP-SMX alone, avoiding steroids entirely": "Steroids reduce mortality in moderate to severe disease.",
       "Fluconazole with adjunctive corticosteroids": "Pneumocystis lacks ergosterol and does not respond to azoles.",
       "Azithromycin with ethambutol and rifabutin": "That regimen treats disseminated MAC.",
       "Amphotericin B with oral flucytosine": "That combination treats cryptococcal disease."},
  table=HIV_OI),

Q(TAG_FUNGI, "Antifungal targets: matching",
  "Which pairing of antifungal class and molecular target is correct?",
  ["Azoles inhibit 14-alpha-demethylase; echinocandins block glucan synthase",
   "Azoles bind ergosterol directly; echinocandins inhibit squalene epoxidase",
   "Amphotericin blocks glucan synthase; flucytosine binds ergosterol",
   "Terbinafine inhibits 14-alpha-demethylase; griseofulvin blocks glucan",
   "Flucytosine inhibits glucan synthase; echinocandins block DNA synthesis"],
  "Azoles inhibit lanosterol 14-alpha-demethylase, reducing ergosterol synthesis. Echinocandins (caspofungin, micafungin) inhibit beta-1,3-glucan synthase in the wall. Amphotericin B binds ergosterol and forms membrane pores. Flucytosine is converted to 5-fluorouracil, disrupting nucleic acid synthesis. Terbinafine inhibits squalene epoxidase, and griseofulvin disrupts microtubules.",
  difficulty="easy",
  why={"Azoles bind ergosterol directly": "Direct ergosterol binding is the amphotericin mechanism.",
       "Amphotericin blocks glucan synthase": "Glucan synthase is the echinocandin target.",
       "Terbinafine inhibits 14-alpha-demethylase": "Terbinafine acts on squalene epoxidase.",
       "Flucytosine inhibits glucan synthase": "Flucytosine interferes with nucleic acid synthesis."},
  table=ANTIFUNGALS),

Q(TAG_FUNGI, "Amphotericin B: toxicity management",
  "A patient on conventional amphotericin B develops a creatinine rise, potassium of 3.0 mEq/L, and magnesium of 1.2 mg/dL. Which interventions address these problems?",
  ["Saline loading, electrolyte repletion, a lipid formulation",
   "Fluid restriction, potassium binders, and dose escalation",
   "Adding flucytosine to allow a higher amphotericin dose",
   "Switching to oral fluconazole regardless of the organism",
   "Adding probenecid to reduce renal tubular drug uptake"],
  "Amphotericin causes dose-dependent nephrotoxicity with distal tubular potassium and magnesium wasting, plus infusion-related fevers and rigors. Sodium loading before infusion, aggressive electrolyte repletion, and liposomal formulations reduce renal injury. Probenecid is used with cidofovir, not amphotericin.",
  difficulty="medium",
  why={"Fluid restriction, potassium binders, and dose escalation": "This would worsen both the kidney injury and the hypokalemia.",
       "Adding flucytosine to allow a higher amphotericin dose": "Flucytosine allows a shorter course but adds marrow toxicity.",
       "Switching to oral fluconazole regardless of the organism": "Many organisms treated with amphotericin are azole-resistant.",
       "Adding probenecid": "Probenecid is a cidofovir adjunct."},
  table=ANTIFUNGALS),

Q(TAG_FUNGI, "Azole interactions and selectivity",
  "A transplant recipient on tacrolimus is started on voriconazole and develops tremor with a high tacrolimus level. What explains this?",
  ["Azoles inhibit CYP3A4 and slow tacrolimus metabolism",
   "Azoles induce CYP3A4 and speed tacrolimus metabolism",
   "Azoles displace tacrolimus from renal tubular transporters",
   "Azoles increase tacrolimus absorption by altering gut flora",
   "Azoles inhibit P-glycoprotein export from hepatocytes only"],
  "Azoles inhibit CYP3A4, raising levels of calcineurin inhibitors, warfarin, statins, and many other drugs, so doses must be reduced and levels monitored. Voriconazole also causes transient visual disturbances, photosensitivity, and periostitis with long use. Itraconazole has negative inotropic effects and is avoided in heart failure.",
  difficulty="medium",
  why={"Azoles induce CYP3A4": "Azoles inhibit rather than induce this enzyme.",
       "Azoles displace tacrolimus from renal tubular transporters": "Renal transport is not the mechanism.",
       "Azoles increase tacrolimus absorption by altering gut flora": "Flora changes do not account for this interaction.",
       "Azoles inhibit P-glycoprotein export from hepatocytes only": "CYP3A4 inhibition is the principal mechanism."},
  table=ANTIFUNGALS),

Q(TAG_FUNGI, "Sporothrix: rose gardener",
  "A gardener pricked by a thorn develops a nodule at the site, followed by a chain of nodules ascending the arm along lymphatics. Which treatment is preferred?",
  ["Itraconazole for several months",
   "Oral fluconazole for a single week",
   "Intravenous caspofungin therapy",
   "Topical terbinafine cream daily",
   "Oral doxycycline for two weeks"],
  "Sporotrichosis is a subcutaneous mycosis caused by a dimorphic fungus inoculated by thorns or sphagnum moss, producing ascending nodular lymphangitis. Itraconazole for three to six months is first-line; potassium iodide is a traditional alternative. Amphotericin is reserved for disseminated or pulmonary disease.",
  difficulty="medium",
  why={"Oral fluconazole for a single week": "Fluconazole is less effective and the course would be far too short.",
       "Intravenous caspofungin therapy": "Echinocandins are not active against Sporothrix.",
       "Topical terbinafine cream daily": "Topical therapy cannot reach subcutaneous and lymphatic disease.",
       "Oral doxycycline for two weeks": "Antibacterials do not treat a fungal infection."},
  table=DIMORPHIC),

Q(TAG_FUNGI, "Dermatophytes vs Malassezia",
  "A teenager has hypopigmented scaly macules on the upper back that fluoresce yellow-green and show short hyphae with round yeast on KOH. Which organism and treatment fit?",
  ["Malassezia furfur; topical selenium sulfide",
   "Trichophyton rubrum; topical selenium sulfide",
   "Malassezia furfur; oral griseofulvin for weeks",
   "Epidermophyton floccosum; topical nystatin",
   "Candida albicans; oral terbinafine for months"],
  "Tinea versicolor is caused by Malassezia, a lipophilic yeast; KOH shows the 'spaghetti and meatballs' pattern. It degrades lipids into acids that inhibit melanocytes, causing hypopigmentation that is most visible after sun exposure. Treatment is topical selenium sulfide, ketoconazole, or an oral azole for extensive disease. Griseofulvin does not work against it.",
  difficulty="medium",
  why={"Trichophyton rubrum; topical selenium sulfide": "Dermatophytes show branching septate hyphae without yeast forms.",
       "Malassezia furfur; oral griseofulvin": "Griseofulvin is ineffective against Malassezia.",
       "Epidermophyton floccosum; topical nystatin": "Nystatin treats Candida, not dermatophytes.",
       "Candida albicans; oral terbinafine": "Candida produces pseudohyphae and causes moist intertrigo."},
  table=ANTIFUNGALS),

# ---------------- protozoa ----------------
Q(TAG_PROT, "Giardia: IgA deficiency link",
  "A patient with recurrent giardiasis, sinopulmonary infections, and an anaphylactic reaction to a blood transfusion most likely has which underlying condition?",
  ["Selective IgA deficiency",
   "Chronic granulomatous disease",
   "Terminal complement deficiency",
   "Severe combined immunodeficiency",
   "Hereditary angioedema from C1 inhibitor loss"],
  "Secretory IgA blocks Giardia attachment to the duodenal brush border, so IgA deficiency leads to recurrent or chronic giardiasis along with sinopulmonary infections. Anti-IgA antibodies can cause anaphylaxis with blood products, so washed cellular products are used. Treatment of giardiasis is metronidazole or tinidazole.",
  difficulty="medium",
  why={"Chronic granulomatous disease": "CGD causes catalase-positive bacterial and fungal infections.",
       "Terminal complement deficiency": "That predisposes to Neisseria infections.",
       "Severe combined immunodeficiency": "SCID presents in infancy with severe infections of all types.",
       "Hereditary angioedema from C1 inhibitor loss": "That causes swelling attacks, not infections."},
  table=INTESTINAL_PROTOZOA),

Q(TAG_PROT, "Entamoeba: trophozoite finding",
  "A traveler has bloody diarrhea with tenesmus. Stool microscopy shows trophozoites containing ingested red blood cells. Which statement about management is correct?",
  ["Treat with metronidazole, then a luminal agent",
   "Treat with metronidazole alone and no follow-up",
   "Treat with a luminal agent alone, such as paromomycin",
   "Treat with vancomycin, since colitis is bacterial",
   "No treatment is needed, since infection self-resolves"],
  "Erythrophagocytosis distinguishes E. histolytica from non-pathogenic amoebae. Invasive disease is treated with metronidazole or tinidazole to kill trophozoites in tissue, followed by a luminal agent (paromomycin or iodoquinol) to eradicate cysts and prevent relapse and ongoing transmission. Flask-shaped colonic ulcers are characteristic.",
  difficulty="medium",
  why={"Treat with metronidazole alone and no follow-up": "Without a luminal agent, cysts persist and relapse occurs.",
       "Treat with a luminal agent alone": "Luminal agents do not reach invasive tissue trophozoites.",
       "Treat with vancomycin": "Vancomycin treats C. difficile, not amoebiasis.",
       "No treatment is needed": "Invasive amoebiasis can progress to liver abscess and perforation."},
  table=INTESTINAL_PROTOZOA),

Q(TAG_PROT, "Cryptosporidium: chlorine resistance",
  "An outbreak of watery diarrhea affects swimmers at a chlorinated public pool. Acid-fast oocysts are seen in stool. Which property explains the outbreak setting?",
  ["A thick-walled oocyst resists standard chlorination",
   "A lipid envelope protects the organism from chlorine",
   "The parasite multiplies within the pool filtration system",
   "The parasite survives only in warm untreated fresh water",
   "The parasite forms heat-resistant endospores in water"],
  "Cryptosporidium oocysts are highly chlorine-resistant, so pool outbreaks are common and filtration or UV treatment is needed. In healthy hosts the illness is self-limited; with CD4 counts below 100 it causes severe chronic diarrhea, treated primarily by restoring immunity, with nitazoxanide as an adjunct.",
  difficulty="medium",
  why={"A lipid envelope protects the organism": "The oocyst wall is not a lipid envelope.",
       "The parasite multiplies within the pool filtration system": "It does not multiply outside a host.",
       "The parasite survives only in warm untreated fresh water": "It survives in treated water as well.",
       "The parasite forms heat-resistant endospores": "Endospores are a bacterial structure."},
  table=INTESTINAL_PROTOZOA),

Q(TAG_PROT, "Toxoplasma: ring lesions vs lymphoma",
  "A patient with AIDS and a CD4 count of 60 has headache and MRI showing multiple ring-enhancing lesions in the basal ganglia. Toxoplasma serology is positive. What is the appropriate approach?",
  ["Empiric pyrimethamine and sulfadiazine, with imaging in two weeks",
   "Immediate brain biopsy before starting any antimicrobial therapy",
   "Whole-brain radiation for presumed central nervous system lymphoma",
   "Empiric amphotericin B for presumed cryptococcal disease",
   "Observation alone while the CD4 count recovers on therapy"],
  "Multiple ring-enhancing lesions with positive serology at a low CD4 count are treated empirically with pyrimethamine, sulfadiazine, and leucovorin. Clinical and radiographic improvement within two weeks confirms the diagnosis; failure to improve prompts biopsy to look for primary CNS lymphoma, which is typically a single periventricular lesion and EBV-positive on CSF PCR.",
  difficulty="medium",
  why={"Immediate brain biopsy before starting any antimicrobial": "Biopsy is reserved for patients who fail empiric therapy.",
       "Whole-brain radiation for presumed central nervous system lymphoma": "Lymphoma usually produces a solitary lesion and needs tissue confirmation.",
       "Empiric amphotericin B": "Cryptococcal disease causes meningitis rather than multiple ring lesions.",
       "Observation alone": "Untreated toxoplasmic encephalitis progresses rapidly."},
  table=HIV_OI),

Q(TAG_PROT, "Malaria: species and relapse",
  "A traveler returns from Papua New Guinea and has malaria. Which species require additional therapy to prevent relapse, and with which drug?",
  ["P. vivax and P. ovale; primaquine after G6PD testing",
   "P. falciparum and P. malariae; primaquine after G6PD testing",
   "P. vivax and P. falciparum; doxycycline for four weeks",
   "P. ovale and P. knowlesi; chloroquine for eight weeks",
   "All species relapse; artemether-lumefantrine is sufficient"],
  "P. vivax and P. ovale form dormant hepatic hypnozoites that cause true relapse weeks to months later, so radical cure requires primaquine or tafenoquine after testing for G6PD deficiency to avoid hemolysis. P. falciparum and P. malariae have no liver stage, although P. malariae can persist in blood for years.",
  difficulty="medium",
  why={"P. falciparum and P. malariae; primaquine": "Neither species forms hypnozoites.",
       "P. vivax and P. falciparum; doxycycline": "P. falciparum does not relapse, and doxycycline does not clear hypnozoites.",
       "P. ovale and P. knowlesi; chloroquine": "P. knowlesi has no hypnozoites, and chloroquine does not kill them.",
       "All species relapse": "Only vivax and ovale have a dormant liver stage."},
  table=MALARIA),

Q(TAG_PROT, "P. falciparum: severe disease mechanism",
  "Why does P. falciparum cause cerebral malaria and higher parasitemia than the other species?",
  ["It invades red cells of all ages and makes them cytoadhere",
   "It invades only reticulocytes but multiplies far more quickly",
   "It produces an exotoxin that crosses the blood-brain barrier",
   "It survives inside neurons and destroys them from within",
   "It causes antibodies that attack the cerebral endothelium"],
  "P. falciparum invades erythrocytes of every age, so parasitemia can be very high, and it expresses PfEMP1 knobs that bind endothelium, sequestering infected cells in cerebral and placental microvasculature. This causes cerebral malaria, severe anemia, hypoglycemia, and acidosis. P. vivax and P. ovale prefer reticulocytes, and P. malariae prefers older cells.",
  difficulty="hard",
  why={"It invades only reticulocytes but multiplies far more quickly": "Reticulocyte restriction describes vivax and ovale.",
       "It produces an exotoxin that crosses the blood-brain barrier": "Sequestration, not an exotoxin, causes cerebral disease.",
       "It survives inside neurons": "The parasite is confined to red cells and hepatocytes.",
       "It causes antibodies that attack the cerebral endothelium": "The mechanism is mechanical and inflammatory, not autoimmune."},
  table=MALARIA),

Q(TAG_PROT, "Malaria: protective host polymorphisms",
  "Which pairing of red cell variant and the malaria species it protects against is correct?",
  ["Duffy-negative red cells with resistance to P. vivax",
   "Duffy-negative red cells with resistance to P. falciparum",
   "Sickle cell trait with complete resistance to P. vivax",
   "Hereditary spherocytosis with resistance to all species",
   "G6PD deficiency with increased risk of severe falciparum"],
  "P. vivax uses the Duffy antigen to enter red cells, so Duffy-negative individuals, common in West Africa, are largely resistant to it. Sickle cell trait, thalassemia, and G6PD deficiency give partial protection against severe P. falciparum, which is why they persist at high frequency in endemic regions.",
  difficulty="hard",
  why={"Duffy-negative red cells with resistance to P. falciparum": "Duffy is the vivax receptor.",
       "Sickle cell trait with complete resistance to P. vivax": "Sickle trait gives partial protection against falciparum.",
       "Hereditary spherocytosis with resistance to all species": "Spherocytosis is not a recognized protective polymorphism here.",
       "G6PD deficiency with increased risk of severe falciparum": "G6PD deficiency is protective rather than harmful in this context."},
  table=MALARIA),

Q(TAG_PROT, "Babesia: asplenia and smear",
  "An asplenic man from Nantucket has fever, hemolytic anemia, and a blood smear showing small intraerythrocytic rings and a rare tetrad. Which treatment is standard?",
  ["Atovaquone with azithromycin",
   "Chloroquine with primaquine",
   "Doxycycline with rifampin",
   "TMP-SMX with leucovorin",
   "Amphotericin B with flucytosine"],
  "Babesia microti is transmitted by Ixodes ticks and causes severe disease in asplenic and elderly patients. The Maltese cross tetrad is characteristic but uncommon; there is no pigment, unlike malaria. Treatment is atovaquone plus azithromycin, or clindamycin plus quinine for severe disease, with exchange transfusion for very high parasitemia. Co-infection with Lyme disease is common.",
  difficulty="medium",
  why={"Chloroquine with primaquine": "Antimalarials of this type do not treat babesiosis.",
       "Doxycycline with rifampin": "Doxycycline treats other tick-borne infections but not Babesia.",
       "TMP-SMX with leucovorin": "That combination treats Pneumocystis.",
       "Amphotericin B with flucytosine": "That combination treats cryptococcal disease."},
  table=BLOOD_TISSUE_PROTOZOA),

Q(TAG_PROT, "Chagas: vector and chronic disease",
  "A man who lived in rural Bolivia has progressive dysphagia and constipation, with a dilated esophagus and colon on imaging, plus an enlarged heart. Which mechanism explains the gastrointestinal findings?",
  ["Destruction of myenteric plexus ganglion cells",
   "Fibrosis of the esophageal muscularis from toxin",
   "Autoantibodies directed against smooth muscle actin",
   "Obstruction of the lumen by adult worms in the gut",
   "Ischemic injury from small vessel thrombosis"],
  "Trypanosoma cruzi, spread by the reduviid 'kissing' bug, destroys autonomic ganglion cells in the myenteric plexus, producing megaesophagus and megacolon, and damages the myocardium, causing dilated cardiomyopathy with apical aneurysms and conduction disease. Acute disease may show Romana sign. Benznidazole and nifurtimox treat acute infection.",
  difficulty="medium",
  why={"Fibrosis of the esophageal muscularis from toxin": "No toxin-mediated fibrosis explains this syndrome.",
       "Autoantibodies directed against smooth muscle actin": "Autoimmunity contributes but ganglion cell loss is the key lesion.",
       "Obstruction of the lumen by adult worms": "T. cruzi is a protozoan, not a helminth.",
       "Ischemic injury from small vessel thrombosis": "Thrombotic ischemia is not the mechanism."},
  table=BLOOD_TISSUE_PROTOZOA),

Q(TAG_PROT, "African trypanosomiasis: stage determines drug",
  "A patient from Uganda has fever, posterior cervical lymphadenopathy, and daytime somnolence with reversed sleep-wake cycles. Why is it essential to examine the cerebrospinal fluid?",
  ["CNS involvement requires drugs that reach the brain",
   "CSF culture is the only way to grow the organism",
   "CSF glucose determines whether antibiotics will work",
   "CSF findings distinguish the two vector species involved",
   "CSF pressure predicts the risk of permanent blindness"],
  "Staging determines therapy: early hemolymphatic disease is treated with suramin (T. b. rhodesiense) or pentamidine (T. b. gambiense), while CNS involvement requires drugs that penetrate the brain, such as melarsoprol or eflornithine, or newer fexinidazole. Winterbottom sign is posterior cervical adenopathy, and the vector is the tsetse fly.",
  difficulty="hard",
  why={"CSF culture is the only way to grow the organism": "Diagnosis uses microscopy of blood, nodes, or CSF.",
       "CSF glucose determines whether antibiotics will work": "This is a parasitic, not bacterial, infection.",
       "CSF findings distinguish the two vector species": "Geography and clinical course distinguish the subspecies.",
       "CSF pressure predicts the risk of permanent blindness": "Blindness is a feature of onchocerciasis."},
  table=BLOOD_TISSUE_PROTOZOA),

Q(TAG_PROT, "Naegleria vs Acanthamoeba",
  "Two patients have amoebic central nervous system disease. Patient A swam in a warm freshwater lake and died within a week of fulminant meningoencephalitis. Patient B, immunosuppressed, had a slowly progressive encephalitis over weeks. Which pairing is correct?",
  ["A is Naegleria fowleri; B is Acanthamoeba",
   "A is Acanthamoeba; B is Naegleria fowleri",
   "Both patients are infected with Naegleria fowleri",
   "A is Entamoeba histolytica; B is Naegleria fowleri",
   "A is Acanthamoeba; B is Balamuthia in a healthy host"],
  "Naegleria enters through the cribriform plate after warm freshwater exposure and causes rapidly fatal primary amoebic meningoencephalitis; motile trophozoites may be seen in CSF, and amphotericin B with miltefosine is attempted. Acanthamoeba and Balamuthia cause granulomatous amoebic encephalitis in immunocompromised hosts over weeks, and Acanthamoeba also causes contact lens-associated keratitis.",
  difficulty="medium",
  why={"A is Acanthamoeba; B is Naegleria fowleri": "The two courses are reversed.",
       "Both patients are infected with Naegleria fowleri": "The subacute course in the second patient fits a different organism.",
       "A is Entamoeba histolytica": "E. histolytica causes colitis and liver abscess.",
       "A is Acanthamoeba; B is Balamuthia in a healthy host": "The acute freshwater case is Naegleria."},
  table=BLOOD_TISSUE_PROTOZOA),

# ---------------- helminths ----------------
Q(TAG_HELM, "Strongyloides: autoinfection cycle",
  "Why can Strongyloides infection persist for decades after a person leaves an endemic area?",
  ["Larvae reinfect the host through the bowel or perianal skin",
   "Eggs remain dormant in the liver for many years at a time",
   "Adult worms encyst in skeletal muscle and later reactivate",
   "The parasite integrates its DNA into intestinal epithelium",
   "Cysts survive in the gallbladder and periodically hatch"],
  "Strongyloides is unique among nematodes in completing autoinfection: rhabditiform larvae mature into infective filariform larvae within the host and reinvade through the intestinal wall or perianal skin. Corticosteroids convert this to hyperinfection with disseminated larvae and Gram-negative bacteremia, so screening before immunosuppression is essential.",
  difficulty="medium",
  why={"Eggs remain dormant in the liver": "Hepatic dormancy describes Plasmodium hypnozoites.",
       "Adult worms encyst in skeletal muscle": "Muscle encystment describes Trichinella.",
       "The parasite integrates its DNA": "Helminths do not integrate into host DNA.",
       "Cysts survive in the gallbladder": "Chronic biliary carriage describes Salmonella Typhi."},
  table=NEMATODES),

Q(TAG_HELM, "Ascaris: Loeffler syndrome",
  "A child in a rural area has cough, wheezing, transient pulmonary infiltrates, and eosinophilia, followed weeks later by passing a large worm. Which explains the pulmonary phase?",
  ["Larvae migrate through alveoli before being swallowed",
   "Adult worms lodge in the pulmonary arteries and die there",
   "Eggs embolize to the lungs and provoke granulomas",
   "The infection triggers asthma without any lung invasion",
   "Larvae enter the lungs through inhaled contaminated dust"],
  "Ascaris, hookworm, and Strongyloides larvae all migrate through the lungs, ascend the airway, and are swallowed, producing transient eosinophilic infiltrates known as Loeffler syndrome. Adults live in the small intestine, and heavy burdens cause obstruction or biliary disease. Treatment is albendazole or mebendazole.",
  difficulty="medium",
  why={"Adult worms lodge in the pulmonary arteries": "Adults remain in the intestine.",
       "Eggs embolize to the lungs and provoke granulomas": "Egg embolization to lungs occurs in schistosomiasis.",
       "The infection triggers asthma without any lung invasion": "Larval migration through the lung is the mechanism.",
       "Larvae enter the lungs through inhaled contaminated dust": "Infection follows ingestion of eggs."},
  table=NEMATODES),

Q(TAG_HELM, "Hookworm: anemia mechanism",
  "A farmer who walks barefoot has iron deficiency anemia and eosinophilia. Which mechanism causes the anemia?",
  ["Worms attach to the mucosa and feed on blood",
   "Worms consume dietary vitamin B12 in the ileum",
   "Worms destroy red cells directly in the bloodstream",
   "Worms block iron absorption by coating the duodenum",
   "Worms trigger antibodies that lyse red cell precursors"],
  "Necator americanus and Ancylostoma duodenale penetrate skin, migrate through lungs, and attach to the small bowel mucosa with cutting plates or teeth, causing chronic blood loss and iron deficiency. Treatment is albendazole plus iron. Diphyllobothrium latum, a tapeworm, is the one that consumes B12.",
  difficulty="easy",
  why={"Worms consume dietary vitamin B12": "B12 consumption describes the fish tapeworm.",
       "Worms destroy red cells directly in the bloodstream": "Hookworms do not enter the bloodstream as adults.",
       "Worms block iron absorption by coating the duodenum": "The anemia comes from blood loss, not malabsorption.",
       "Worms trigger antibodies that lyse red cell precursors": "There is no autoimmune mechanism here."},
  table=NEMATODES),

Q(TAG_HELM, "Enterobius: diagnosis and treatment",
  "A 6-year-old has nocturnal perianal itching. Which diagnostic method and treatment approach is correct?",
  ["Adhesive tape test; treat the child and household contacts",
   "Stool ova and parasite exam; treat only the affected child",
   "Blood eosinophil count; treat with a single course of steroids",
   "Serologic antibody testing; treat with praziquantel once",
   "Duodenal aspirate; treat with a two-week metronidazole course"],
  "Pinworm eggs are deposited on perianal skin, so the cellophane tape test applied in the morning is diagnostic while stool examination is usually negative. Treatment is albendazole, mebendazole, or pyrantel pamoate, repeated in two weeks, and household members are treated because reinfection is common. Bedding and clothes are washed.",
  difficulty="easy",
  why={"Stool ova and parasite exam; treat only the affected child": "Eggs are rarely found in stool and household spread is common.",
       "Blood eosinophil count": "Pinworm does not usually cause eosinophilia and steroids are not treatment.",
       "Serologic antibody testing; treat with praziquantel": "Praziquantel treats flukes and tapeworms.",
       "Duodenal aspirate": "That approach targets Giardia."},
  table=NEMATODES),

Q(TAG_HELM, "Trichinella: muscle and clinical clue",
  "A man develops fever, periorbital edema, and severe myalgia with marked eosinophilia after eating undercooked bear meat. Which statement is correct?",
  ["Larvae encyst in striated muscle after intestinal invasion",
   "Adult worms migrate into muscle and die there in cysts",
   "Eggs deposited in muscle hatch and cause inflammation",
   "The organism infects only the intestinal lumen without invasion",
   "Muscle damage results from an antibody against sarcomeres"],
  "Trichinella spiralis larvae are released from ingested meat, mature in the intestine, and newborn larvae disseminate to encyst in striated muscle, preferring the diaphragm, extraocular, and masseter muscles. Periorbital edema, myalgia, eosinophilia, and elevated CK are the classic picture. Treatment is albendazole with steroids for severe disease.",
  difficulty="medium",
  why={"Adult worms migrate into muscle and die there": "Adults remain in the intestine; larvae migrate.",
       "Eggs deposited in muscle hatch": "Trichinella females release live larvae rather than eggs into tissue.",
       "The organism infects only the intestinal lumen": "Tissue invasion is what produces the syndrome.",
       "Muscle damage results from an antibody against sarcomeres": "Damage is caused by larval invasion."},
  table=NEMATODES),

Q(TAG_HELM, "Filariasis: Wolbachia and doxycycline",
  "Why is doxycycline used in the treatment of onchocerciasis and lymphatic filariasis?",
  ["It kills endosymbiotic bacteria the worms need to survive",
   "It kills the microfilariae directly within the bloodstream",
   "It blocks the inflammatory reaction to dying microfilariae",
   "It prevents the mosquito vector from transmitting larvae",
   "It reverses lymphatic fibrosis that has already developed"],
  "Filarial worms depend on Wolbachia endosymbionts for fertility and survival, so doxycycline sterilizes and kills adult worms over weeks. Ivermectin kills microfilariae in onchocerciasis, and diethylcarbamazine is used in lymphatic filariasis but is avoided in onchocerciasis because of the severe Mazzotti reaction.",
  difficulty="hard",
  why={"It kills the microfilariae directly": "Ivermectin, not doxycycline, is the microfilaricide.",
       "It blocks the inflammatory reaction": "Steroids, not doxycycline, blunt that reaction.",
       "It prevents the mosquito vector from transmitting": "Doxycycline does not act on the vector.",
       "It reverses lymphatic fibrosis": "Established elephantiasis is not reversed by drugs."},
  table=NEMATODES),

Q(TAG_HELM, "Onchocerca: river blindness and vector",
  "A man from West Africa has intensely itchy skin nodules and progressive vision loss. Slit-lamp examination shows microfilariae in the anterior chamber. Which vector transmits this parasite?",
  ["The blackfly, which breeds in swift rivers",
   "The tsetse fly, which transmits it in dry savanna",
   "The Anopheles mosquito, which bites at night",
   "The reduviid bug, which defecates while feeding",
   "The Ixodes tick, which attaches for many hours"],
  "Onchocerca volvulus is transmitted by Simulium blackflies breeding in fast-flowing rivers, which is why the disease is called river blindness. Adults live in subcutaneous nodules and release microfilariae that migrate through skin and eye. Ivermectin given periodically is the mainstay, with doxycycline targeting Wolbachia.",
  difficulty="medium",
  why={"The tsetse fly": "Tsetse flies transmit African trypanosomiasis.",
       "The Anopheles mosquito": "Anopheles transmits malaria and Wuchereria.",
       "The reduviid bug": "The reduviid bug transmits Chagas disease.",
       "The Ixodes tick": "Ixodes transmits Lyme disease, babesiosis, and anaplasmosis."},
  table=NEMATODES),

Q(TAG_HELM, "Taenia solium: two very different diseases",
  "Which statement correctly distinguishes the two forms of Taenia solium infection?",
  ["Undercooked pork gives intestinal worms; eggs give tissue cysts",
   "Eating undercooked pork gives cysts; eating eggs gives intestinal worms",
   "Both routes produce only an intestinal tapeworm infection",
   "Both routes produce only cysts within the brain and muscle",
   "Eating beef gives cysts and eating pork gives intestinal worms"],
  "Ingesting cysticerci in undercooked pork produces an adult intestinal tapeworm (taeniasis), treated with praziquantel. Ingesting eggs, usually by the fecal-oral route from a human carrier, produces cysticercosis, with cysts in brain and muscle. Neurocysticercosis is a leading cause of adult-onset seizures in endemic regions, and treatment adds albendazole with steroids and antiepileptics.",
  difficulty="medium",
  why={"Eating undercooked pork gives cysts; eating eggs gives intestinal worms": "The two routes are reversed.",
       "Both routes produce only an intestinal tapeworm": "Egg ingestion produces tissue cysts.",
       "Both routes produce only cysts": "Cysticerci in pork produce an intestinal tapeworm.",
       "Eating beef gives cysts": "Taenia saginata from beef causes only intestinal infection."},
  table=CESTODES_TREMATODES),

Q(TAG_HELM, "Echinococcus: why not to aspirate",
  "A shepherd has a large hepatic liver lesion with internal daughter loculations and eggshell calcification. Why is simple percutaneous aspiration hazardous?",
  ["Spillage can cause anaphylaxis and seed new cysts",
   "The cyst contains bacteria that cause peritonitis",
   "Aspiration invariably leads to uncontrollable bleeding",
   "The needle tract allows adult worms to escape the liver",
   "Aspiration converts the cyst into a malignant lesion"],
  "Hydatid cyst fluid is highly antigenic, so leakage can cause anaphylaxis, and spilled protoscolices seed new cysts. Management is albendazole with careful surgery or the PAIR technique (puncture, aspiration, injection of a scolicidal agent, reaspiration) under cover. Dogs are definitive hosts and sheep intermediate hosts.",
  difficulty="medium",
  why={"The cyst contains bacteria that cause peritonitis": "Hydatid cysts are not primarily bacterial.",
       "Aspiration invariably leads to uncontrollable bleeding": "Bleeding is not the principal hazard.",
       "The needle tract allows adult worms to escape": "Adults live in the dog intestine, not the human cyst.",
       "Aspiration converts the cyst into a malignant lesion": "Hydatid cysts do not become malignant."},
  table=CESTODES_TREMATODES),

Q(TAG_HELM, "Schistosoma: species and organ",
  "Which pairing of schistosome species and clinical consequence is correct?",
  ["S. haematobium with bladder cancer; S. mansoni with liver fibrosis",
   "S. haematobium with portal fibrosis; S. mansoni with bladder cancer",
   "Both species cause squamous cell carcinoma of the bladder",
   "Both species cause only intestinal ulceration without fibrosis",
   "S. japonicum with bladder cancer; S. mansoni with lung cysts"],
  "S. haematobium lives in the vesical venous plexus, causing hematuria, obstructive uropathy, and squamous cell carcinoma of the bladder. S. mansoni and S. japonicum live in mesenteric veins; eggs embolize to the liver, causing periportal 'pipestem' fibrosis with portal hypertension and preserved hepatocyte function. Praziquantel treats all species; snails are the intermediate host.",
  difficulty="medium",
  why={"S. haematobium with portal fibrosis": "The two associations are reversed.",
       "Both species cause squamous cell carcinoma of the bladder": "Only S. haematobium is linked to bladder cancer.",
       "Both species cause only intestinal ulceration": "Hepatic and urinary disease are the major consequences.",
       "S. japonicum with bladder cancer": "S. japonicum affects the mesenteric circulation and liver."},
  table=CESTODES_TREMATODES),

Q(TAG_HELM, "Liver flukes and cholangiocarcinoma",
  "A man from Southeast Asia who regularly ate raw freshwater fish develops biliary obstruction and is found to have cholangiocarcinoma. Which parasite is implicated?",
  ["Clonorchis sinensis",
   "Paragonimus westermani",
   "Fasciola hepatica",
   "Schistosoma haematobium",
   "Diphyllobothrium latum"],
  "Clonorchis sinensis and Opisthorchis are acquired from raw or undercooked freshwater fish, inhabit bile ducts, and cause chronic cholangitis, biliary obstruction, and cholangiocarcinoma. Paragonimus, from crabs and crayfish, causes lung disease mimicking tuberculosis. Fasciola comes from watercress and also involves the biliary tree. Praziquantel treats these flukes, except Fasciola, which needs triclabendazole.",
  difficulty="medium",
  why={"Paragonimus westermani": "Paragonimus causes chronic cough with hemoptysis from lung involvement.",
       "Fasciola hepatica": "Fasciola causes biliary disease but is not strongly linked to cholangiocarcinoma.",
       "Schistosoma haematobium": "That species is linked to bladder cancer.",
       "Diphyllobothrium latum": "The fish tapeworm causes B12 deficiency."},
  table=CESTODES_TREMATODES),

Q(TAG_HELM, "Anthelmintic mechanisms",
  "Which pairing of anthelmintic drug and mechanism is correct?",
  ["Albendazole blocks microtubules; ivermectin opens chloride channels",
   "Albendazole opens chloride channels; ivermectin blocks microtubules",
   "Praziquantel blocks folate synthesis; albendazole opens sodium channels",
   "Ivermectin inhibits protein synthesis; praziquantel blocks microtubules",
   "Pyrantel blocks microtubules; albendazole depolarizes the worm"],
  "Benzimidazoles (albendazole, mebendazole) bind beta-tubulin and block microtubule polymerization and glucose uptake. Ivermectin opens glutamate-gated chloride channels, paralyzing the parasite; it spares humans because these channels are absent and the blood-brain barrier excludes the drug. Praziquantel increases calcium permeability, causing spastic paralysis. Pyrantel is a depolarizing neuromuscular blocker.",
  difficulty="medium",
  why={"Albendazole opens chloride channels": "The two mechanisms are reversed.",
       "Praziquantel blocks folate synthesis": "Folate synthesis inhibition describes antibacterial sulfonamides.",
       "Ivermectin inhibits protein synthesis": "Ivermectin acts on ion channels.",
       "Pyrantel blocks microtubules": "Pyrantel acts at the neuromuscular junction."},
  table=ANTHELMINTICS),

Q(TAG_HELM, "Eosinophilia: which parasites",
  "A returning traveler has marked eosinophilia. Which category of parasite most reliably causes this?",
  ["Tissue-invasive helminths",
   "Intestinal protozoa such as Giardia",
   "Blood protozoa such as Plasmodium",
   "Intracellular bacteria such as Rickettsia",
   "Luminal tapeworms confined to the gut"],
  "Eosinophilia is characteristic of helminths that invade tissue, including Strongyloides, hookworm, Ascaris during migration, Toxocara, Trichinella, filariae, and schistosomes. Protozoa, including Giardia and Plasmodium, do not typically cause eosinophilia, and adult tapeworms confined to the lumen cause little or none.",
  difficulty="easy",
  why={"Intestinal protozoa such as Giardia": "Giardia typically causes no eosinophilia.",
       "Blood protozoa such as Plasmodium": "Malaria does not characteristically raise eosinophils.",
       "Intracellular bacteria such as Rickettsia": "Rickettsial illness does not cause eosinophilia.",
       "Luminal tapeworms confined to the gut": "Luminal worms provoke little eosinophil response."},
  table=NEMATODES),
]
