"""Intracellular and atypical bacteria in depth: Chlamydia/Chlamydophila, Gardnerella/Tropheryma/HACEK,
Mycoplasma/Ureaplasma, and Rickettsia/Ehrlichia/Anaplasma/Coxiella, from several angles: lab identification,
virulence mechanism, clinical vignette, treatment, and epidemiology."""
from qcore import Q
from tables import *
TAG_RC = "Rickettsiae & Chlamydiae"
TAG_MOB = "Mycoplasma & Other Bacteria"

QUESTIONS = [
# ================= Chlamydia & Chlamydophila =================
Q(TAG_RC, "Chlamydia trachomatis: inclusion body culture",
  "A research lab inoculates McCoy cell monolayers with an endocervical specimen and examines the cells 48 hours later with iodine stain. Compact, glycogen-rich cytoplasmic inclusions are seen adjacent to the nucleus. What does this technique detect?",
  ["Growth of the organism inside a cultured eukaryotic cell line",
   "Direct binding of a fluorescent antibody to a swab smear",
   "Amplification of a conserved ribosomal DNA sequence",
   "Formation of a visible precipitin ring in agar gel",
   "A color change from fermentation of a carbohydrate substrate"],
  "Chlamydia trachomatis cannot be grown on artificial media because it is an obligate intracellular organism, so cell culture (historically McCoy or HeLa cells) was the reference method; the intracytoplasmic inclusion contains glycogen and stains with iodine. Cell culture is slow and insensitive compared with nucleic acid amplification testing, which has replaced it for routine diagnosis and is now the clinical standard.",
  difficulty="medium",
  why={"Direct binding of a fluorescent antibody": "Direct fluorescent antibody staining is a separate, faster method applied straight to a smear, not to cultured monolayers.",
       "Amplification of a conserved ribosomal": "That describes nucleic acid amplification testing, which does not require live cell culture.",
       "Formation of a visible precipitin ring": "Precipitin rings are used in older serologic assays, not in monolayer culture.",
       "A color change from fermentation": "Chlamydia has no fermentative metabolism to detect this way."}),

Q(TAG_RC, "Chlamydia trachomatis: reactive arthritis",
  "A 24-year-old man has conjunctivitis, asymmetric oligoarthritis of the knee and ankle, and dysuria beginning three weeks after unprotected intercourse. Urine NAAT is positive for a genital pathogen. Which mechanism best explains his joint findings?",
  ["An HLA-B27-associated autoimmune reaction triggered by the infection",
   "Direct bacterial invasion and destructive infection of the synovium",
   "Deposition of monosodium urate crystals within the joint space",
   "Hematogenous seeding of the joint by circulating organisms",
   "A type I hypersensitivity reaction to genital mucosal antigens"],
  "Reactive arthritis follows genitourinary Chlamydia trachomatis or enteric infection in genetically predisposed (often HLA-B27-positive) patients, producing the classic triad of conjunctivitis, urethritis, and asymmetric oligoarthritis roughly two to four weeks later. Joint fluid is sterile because the process is immune-mediated rather than an infection of the synovium itself.",
  difficulty="medium",
  why={"Direct bacterial invasion and destructive": "Synovial cultures are sterile in reactive arthritis, unlike septic arthritis.",
       "Deposition of monosodium urate": "Urate crystals cause gout, an unrelated and non-infectious process.",
       "Hematogenous seeding of the joint": "This describes septic arthritis, which would grow an organism from joint fluid.",
       "A type I hypersensitivity reaction": "Immediate hypersensitivity produces wheal-and-flare or anaphylaxis, not a delayed oligoarthritis."}),

Q(TAG_RC, "Chlamydia trachomatis: epididymitis",
  "A sexually active 27-year-old man has unilateral scrotal pain and swelling over two days, with relief of pain on elevation of the testicle. Urinalysis shows pyuria without hematuria. Which organism is the most likely cause in this age group?",
  ["Chlamydia trachomatis",
   "Escherichia coli",
   "Mumps virus",
   "Pseudomonas aeruginosa",
   "Mycobacterium tuberculosis"],
  "In sexually active men under 35, epididymitis is usually caused by Chlamydia trachomatis or Neisseria gonorrhoeae ascending from the urethra; relief of pain with testicular elevation (a positive Prehn sign) favors epididymitis over torsion. In older men and children, coliforms such as E. coli from urinary tract infection are more common.",
  difficulty="easy",
  why={"Escherichia coli": "Coliform epididymitis is typical of older men with bladder outlet obstruction or recent instrumentation.",
       "Mumps virus": "Mumps causes orchitis, usually with parotitis, rather than isolated epididymitis.",
       "Pseudomonas aeruginosa": "Pseudomonas is an unusual cause of epididymitis, seen mainly after urinary instrumentation.",
       "Mycobacterium tuberculosis": "Tuberculous epididymitis develops indolently over weeks in the setting of known TB exposure."}),

Q(TAG_RC, "Chlamydia: neonatal conjunctivitis timing",
  "An infant develops mild watery eye discharge with eyelid swelling on day 9 of life. A Gram stain of the discharge shows no organisms and few neutrophils. Which pathogen fits this timeline best, and how does it differ from the other classic cause of neonatal conjunctivitis?",
  ["Chlamydia trachomatis, which presents later than gonococcal disease",
   "Neisseria gonorrhoeae, which presents later than chlamydial disease",
   "Herpes simplex virus, which always appears within the first day",
   "Pseudomonas aeruginosa, which is unrelated to the birth canal",
   "Staphylococcus aureus, acquired from nursery equipment"],
  "Gonococcal ophthalmia neonatorum is a hyperacute, purulent conjunctivitis appearing within two to five days of birth, while chlamydial conjunctivitis is milder and appears later, around five to fourteen days, often without organisms visible on Gram stain since it is intracellular. Both are acquired from an infected birth canal and require systemic, not just topical, antibiotics.",
  difficulty="medium",
  why={"Neisseria gonorrhoeae, which presents later": "Gonococcal conjunctivitis is the earlier, hyperacute, purulent presentation, not the later one.",
       "Herpes simplex virus, which always appears": "Neonatal HSV keratoconjunctivitis can appear across the first two weeks and is not confined to day one.",
       "Pseudomonas aeruginosa, which is unrelated": "Pseudomonas conjunctivitis is a nosocomial concern, not tied to vaginal delivery.",
       "Staphylococcus aureus, acquired from nursery": "Staphylococcal conjunctivitis is not the classic organism linked to a specific birth-canal timeline."}),

Q(TAG_RC, "Chlamydia trachomatis: dual therapy rationale",
  "A 21-year-old woman tests positive for Chlamydia trachomatis by NAAT. Testing for Neisseria gonorrhoeae from the same specimen is still pending. Why do current guidelines no longer recommend treating every chlamydia diagnosis empirically for gonorrhea as well?",
  ["Gonorrhea results are now reliable enough to guide targeted treatment",
   "Chlamydia has become the more antibiotic-resistant of the two organisms",
   "Coinfection with gonorrhea has become extremely rare in adults",
   "Ceftriaxone is now considered unsafe to give without confirmed infection",
   "Doxycycline alone reliably cures both organisms at the same time"],
  "Older guidance treated every chlamydia diagnosis presumptively for gonorrhea because gonorrhea testing was less reliable; with widely available, highly sensitive NAAT for both organisms, treatment can now be targeted to confirmed results rather than given empirically, reducing unnecessary ceftriaxone use and antibiotic pressure.",
  difficulty="hard",
  why={"Chlamydia has become the more antibiotic-resistant": "Chlamydia trachomatis has not developed significant resistance to first-line doxycycline or azithromycin.",
       "Coinfection with gonorrhea has become extremely rare": "Coinfection remains common enough that testing, not empiric coverage, is the recommended strategy.",
       "Ceftriaxone is now considered unsafe": "Ceftriaxone safety is unchanged; the shift is about avoiding unnecessary use, not danger.",
       "Doxycycline alone reliably cures both organisms": "Doxycycline has no reliable activity against Neisseria gonorrhoeae."}),

Q(TAG_RC, "Chlamydia trachomatis: treatment in pregnancy",
  "A 26-year-old woman at 22 weeks of gestation has a positive chlamydia NAAT. Which regimen is preferred over the usual first-line agent, and why?",
  ["Azithromycin, because doxycycline affects fetal bone and tooth development",
   "Doxycycline, because it clears the organism faster than any alternative",
   "Ceftriaxone, because it is the only agent proven safe in pregnancy",
   "Erythromycin estolate, because it has fewer gastrointestinal side effects",
   "Metronidazole, because it treats both chlamydia and vaginal flora"],
  "Doxycycline is avoided in pregnancy because tetracyclines bind developing bone and teeth and can cause enamel discoloration, so a single dose of azithromycin is the preferred treatment for chlamydia during pregnancy, with a test of cure recommended afterward.",
  difficulty="easy",
  why={"Doxycycline, because it clears the organism faster": "Doxycycline is avoided in pregnancy specifically because of fetal risk, not chosen for speed.",
       "Ceftriaxone, because it is the only agent": "Ceftriaxone treats gonorrhea, not chlamydia, and is not the pregnancy-preferred chlamydia agent.",
       "Erythromycin estolate, because it has fewer": "Erythromycin estolate is specifically avoided in pregnancy due to hepatotoxicity risk.",
       "Metronidazole, because it treats both chlamydia": "Metronidazole has no activity against Chlamydia trachomatis."}),

Q(TAG_RC, "Chlamydia trachomatis: specimen sensitivity",
  "A clinic wants to maximize detection of Chlamydia trachomatis in asymptomatic women being screened during a routine visit. Which specimen type gives the highest sensitivity on nucleic acid amplification testing?",
  ["A self-collected or clinician-collected vaginal swab",
   "A first-void urine sample collected after voiding twice",
   "An endocervical swab placed in bacterial transport broth",
   "A blood sample tested for organism-specific IgM antibody",
   "A rectal swab regardless of the site of exposure"],
  "Vaginal swabs, whether self- or clinician-collected, yield the highest NAAT sensitivity for chlamydia in women, equal to or better than endocervical swabs, and are more sensitive than urine, which performs better in men than in women. Serology is not used to diagnose acute urogenital infection.",
  difficulty="medium",
  why={"A first-void urine sample collected after voiding": "Urine testing has somewhat lower sensitivity than a vaginal swab in women and requires first-void, not post-void, collection.",
       "An endocervical swab placed in bacterial transport": "Endocervical swabs work but are not more sensitive than vaginal swabs and require a speculum exam.",
       "A blood sample tested for organism-specific IgM": "Serology reflects past exposure and is not used to diagnose current urogenital infection.",
       "A rectal swab regardless of the site of exposure": "Rectal swabs are appropriate only when rectal exposure or symptoms are present, not as a general screening specimen."}),

Q(TAG_RC, "Chlamydophila pneumoniae: biphasic illness",
  "A 19-year-old college student develops hoarseness and sore throat that improve over a week, followed by a slowly worsening dry cough, low-grade fever, and patchy infiltrates on chest x-ray. Several dormmates have had a similar illness. Which organism best fits this two-stage course?",
  ["Chlamydophila pneumoniae",
   "Chlamydia psittaci",
   "Coxiella burnetii",
   "Legionella pneumophila",
   "Streptococcus pneumoniae"],
  "Chlamydophila (Chlamydia) pneumoniae classically causes a biphasic illness in young adults living in close quarters: pharyngitis or laryngitis first, followed one to two weeks later by a mild, slowly progressive atypical pneumonia. It spreads person to person by respiratory droplets, unlike the animal-exposure organisms in this group.",
  difficulty="medium",
  why={"Chlamydia psittaci": "Psittacosis follows bird exposure rather than dormmate contact and lacks the classic two-stage pharyngitis-then-pneumonia course.",
       "Coxiella burnetii": "Q fever follows exposure to parturient livestock, not person-to-person spread among students.",
       "Legionella pneumophila": "Legionella is linked to contaminated water sources, not close-quarters person-to-person spread.",
       "Streptococcus pneumoniae": "Pneumococcal pneumonia presents acutely with high fever and lobar consolidation, not a gradual biphasic course."}),

Q(TAG_RC, "Chlamydia: virulence and phagolysosome evasion",
  "After a Chlamydia trachomatis elementary body is endocytosed by a genital epithelial cell, the organism survives and converts into its replicating form inside a membrane-bound vacuole. What allows this vacuole to avoid destruction?",
  ["Secreted inclusion membrane proteins block fusion with lysosomes",
   "A thick outer capsule shields the vacuole from acidification",
   "Released catalase neutralizes lysosomal reactive oxygen species",
   "The organism escapes into the cytoplasm before lysosomes arrive",
   "Host actin polymerization walls off the lysosome permanently"],
  "Chlamydia uses a type III secretion system to insert bacterial (Inc) proteins into the inclusion membrane, which modifies vesicle trafficking so the inclusion does not fuse with lysosomes, letting the reticulate body replicate safely inside the cell until it converts back to infectious elementary bodies.",
  difficulty="hard",
  why={"A thick outer capsule shields the vacuole": "Chlamydia lacks a polysaccharide capsule of this kind.",
       "Released catalase neutralizes lysosomal": "Catalase-based oxidant defense is a staphylococcal strategy, not the chlamydial inclusion mechanism.",
       "The organism escapes into the cytoplasm": "Chlamydia remains within its membrane-bound inclusion throughout its replicative cycle.",
       "Host actin polymerization walls off the lysosome": "Actin-based motility mechanisms are used by organisms such as Listeria and Shigella, not by Chlamydia."}),

Q(TAG_RC, "Psittacosis: occupational exposure beyond parrots",
  "Several workers at a turkey processing plant develop fever, headache, dry cough, and relative bradycardia over the same week. None owns a pet bird. Which organism should be suspected, and what is the source?",
  ["Chlamydia psittaci, from inhaling dust contaminated by poultry droppings",
   "Coxiella burnetii, from inhaling dust from poultry bedding straw",
   "Histoplasma capsulatum, from inhaling spores in accumulated droppings",
   "Francisella tularensis, from handling infected rabbit carcasses",
   "Yersinia pestis, from flea bites acquired near rodent burrows"],
  "Psittacosis is not limited to parrots; poultry workers, especially in turkey processing, are a well-recognized occupational risk group because Chlamydia psittaci is shed in the droppings and secretions of many bird species and inhaled as dried aerosolized particles.",
  difficulty="medium",
  why={"Coxiella burnetii, from inhaling dust from poultry bedding": "Q fever is linked to parturient sheep, goats, and cattle, not poultry bedding.",
       "Histoplasma capsulatum, from inhaling spores": "Histoplasmosis follows exposure to bird or bat droppings in soil, and causes a fungal pneumonia rather than this bacterial syndrome.",
       "Francisella tularensis, from handling infected rabbit": "Tularemia follows contact with rabbits or ticks, not poultry processing.",
       "Yersinia pestis, from flea bites acquired": "Plague requires flea exposure near rodents, unrelated to a poultry plant."}),

Q(TAG_RC, "Lymphogranuloma venereum: proctitis mimicking IBD",
  "A 33-year-old man who has sex with men has months of rectal pain, tenesmus, and bloody mucoid discharge. Colonoscopy shows friable rectal mucosa with ulceration, initially read as inflammatory bowel disease. Which test should be added before starting immunosuppressive therapy?",
  ["A mucosal nucleic acid amplification test for Chlamydia trachomatis",
   "Serum antinuclear antibody and rheumatoid factor panel",
   "Fecal calprotectin level to confirm mucosal inflammation",
   "Colonic biopsy stained specifically for iron deposition",
   "Serum tissue transglutaminase antibody for gluten sensitivity"],
  "Lymphogranuloma venereum (LGV, C. trachomatis serovars L1-L3) can cause a chronic proctocolitis in men who have sex with men that closely mimics inflammatory bowel disease on endoscopy and biopsy; a targeted NAAT identifies the treatable infection and prevents inappropriate immunosuppression, since LGV proctitis responds to a three-week course of doxycycline.",
  difficulty="hard",
  why={"Serum antinuclear antibody and rheumatoid": "These autoimmune markers do not distinguish LGV from IBD and would not identify the infection.",
       "Fecal calprotectin level to confirm mucosal": "Calprotectin confirms inflammation is present but does not identify its infectious cause.",
       "Colonic biopsy stained specifically for iron": "Iron staining is used to evaluate hemochromatosis or iron overload, not infectious proctitis.",
       "Serum tissue transglutaminase antibody for gluten": "This test screens for celiac disease, unrelated to proctitis in this setting."}),

Q(TAG_RC, "Chlamydia trachomatis: rescreening after treatment",
  "A 20-year-old woman completes a full course of doxycycline for chlamydial cervicitis and reports taking every dose. Three months later, routine guidelines call for repeat testing even though she feels well. What is the main reason for this rescreening?",
  ["High rates of reinfection from an untreated or new partner",
   "Frequent emergence of doxycycline-resistant strains locally",
   "The need to rule out a new coexisting fungal vaginitis",
   "Poor absorption of doxycycline in most young adult women",
   "A requirement to confirm resolution of pelvic ultrasound findings"],
  "Because reinfection rates after chlamydia treatment are high, largely from an untreated partner or a new partner, guidelines recommend rescreening around three months after treatment regardless of symptoms, rather than performing a test of cure immediately after therapy, which can give a false positive from residual dead organisms.",
  difficulty="medium",
  why={"Frequent emergence of doxycycline-resistant": "Doxycycline resistance in Chlamydia trachomatis is not a recognized clinical problem driving this recommendation.",
       "The need to rule out a new coexisting fungal": "Routine rescreening targets chlamydial reinfection specifically, not incidental fungal infection.",
       "Poor absorption of doxycycline in most young": "Doxycycline absorption is not impaired in this population, and this is not the basis for the guideline.",
       "A requirement to confirm resolution of pelvic": "Rescreening is done by NAAT for the organism, not by repeat pelvic imaging."}),

# ================= Gardnerella, Tropheryma & Other Bacteria =================
Q(TAG_MOB, "Gardnerella vaginalis: Amsel criteria",
  "A 29-year-old woman has a thin, gray vaginal discharge. Testing shows a vaginal pH of 5.2, a fishy odor when potassium hydroxide is added, and epithelial cells with borders obscured by adherent coccobacilli. Only three of the four standard criteria are met. Which additional finding would complete the diagnosis?",
  ["Absence of pain, itching, or overt inflammation on examination",
   "Motile, flagellated organisms seen on the wet mount preparation",
   "A cervix that bleeds easily on contact with a swab",
   "Numerous white blood cells surrounding vaginal epithelial cells",
   "A strawberry-like appearance of the cervical surface"],
  "The Amsel criteria for bacterial vaginosis require three of four findings: thin homogeneous discharge, vaginal pH above 4.5, a positive whiff test, and clue cells; here the fourth criterion is the notable lack of accompanying inflammation, since bacterial vaginosis is a shift in flora rather than a true inflammatory infection, distinguishing it from trichomoniasis.",
  difficulty="medium",
  why={"Motile, flagellated organisms seen on the wet mount": "Motile flagellates on wet mount indicate Trichomonas vaginalis, not bacterial vaginosis.",
       "A cervix that bleeds easily on contact": "A friable, easily bleeding cervix suggests cervicitis from chlamydia or gonorrhea, not bacterial vaginosis.",
       "Numerous white blood cells surrounding vaginal": "Bacterial vaginosis is characterized by a paucity of white blood cells, unlike trichomoniasis or candidiasis.",
       "A strawberry-like appearance of the cervical": "A strawberry cervix is a classic sign of trichomonal infection."}),

Q(TAG_MOB, "Gardnerella vaginalis: recurrence management",
  "A 34-year-old woman has her fourth episode of bacterial vaginosis this year, each initially responding to oral metronidazole before symptoms return within two months. Her male partner has no symptoms. What is the most appropriate next step?",
  ["Consider a longer suppressive or maintenance antimicrobial regimen for her",
   "Treat her male partner empirically with the same oral antibiotic",
   "Switch to a single injection of intramuscular benzathine penicillin",
   "Begin daily oral fluconazole to prevent recurrent yeast overgrowth",
   "Recommend permanent discontinuation of any vaginal hygiene products alone"],
  "Recurrent bacterial vaginosis is managed by extending or repeating first-line therapy (oral or vaginal metronidazole or clindamycin) and, for frequent recurrence, using a longer maintenance course; treating male partners has not been shown to reduce recurrence, since bacterial vaginosis reflects a disturbed vaginal ecosystem rather than a classic sexually transmitted infection passed back and forth.",
  difficulty="medium",
  why={"Treat her male partner empirically with the same": "Partner treatment does not reduce recurrence rates in bacterial vaginosis and is not recommended.",
       "Switch to a single injection of intramuscular": "Benzathine penicillin has no role in bacterial vaginosis and does not target the causative anaerobes.",
       "Begin daily oral fluconazole to prevent recurrent": "Fluconazole is an antifungal and would not address bacterial, non-fungal overgrowth.",
       "Recommend permanent discontinuation of any vaginal hygiene": "While douching is a risk factor, stopping it alone does not reliably resolve established recurrent disease."}),

Q(TAG_MOB, "Gardnerella vaginalis: pregnancy complication",
  "A 30-year-old woman at 16 weeks of gestation is found to have bacterial vaginosis on routine screening. Which pregnancy complication is this condition most strongly associated with?",
  ["Preterm labor and premature rupture of membranes",
   "Congenital malformation of the neural tube",
   "Gestational diabetes requiring insulin therapy",
   "Placenta previa diagnosed on later ultrasound",
   "Fetal growth restriction from placental infarction"],
  "Bacterial vaginosis is associated with an increased risk of preterm labor, premature rupture of membranes, and postpartum endometritis, thought to relate to ascending anaerobic organisms and inflammatory mediators reaching the amniotic membranes; treatment is generally reserved for symptomatic women.",
  difficulty="easy",
  why={"Congenital malformation of the neural tube": "Neural tube defects relate to folate status and certain medications, not vaginal flora disturbance.",
       "Gestational diabetes requiring insulin therapy": "Gestational diabetes is a metabolic condition unrelated to vaginal bacterial overgrowth.",
       "Placenta previa diagnosed on later ultrasound": "Placenta previa is an anatomic placental location issue, not linked to bacterial vaginosis.",
       "Fetal growth restriction from placental infarction": "Placental infarction relates to vascular disease, not the ascending anaerobic flora of bacterial vaginosis."}),

Q(TAG_MOB, "Gardnerella vaginalis: not a classic STI",
  "A patient newly diagnosed with bacterial vaginosis asks whether her new partner needs to be tested or treated and whether she acquired this from him. What is the most accurate response?",
  ["It reflects a disturbed vaginal flora and is not managed as a classic STI",
   "It is an obligate sexually transmitted infection requiring partner therapy",
   "It can only be acquired through unprotected anal intercourse",
   "It is transmitted exclusively through shared personal hygiene items",
   "It requires contact tracing identical to that used for chlamydia"],
  "Bacterial vaginosis results from an overgrowth of Gardnerella and anaerobes replacing protective lactobacilli; while new or multiple sexual partners are a risk factor, it is not treated as a classic sexually transmitted infection, and routine partner testing or treatment is not recommended because it does not reduce recurrence.",
  difficulty="easy",
  why={"It is an obligate sexually transmitted infection": "It is not classified or managed as an obligate STI requiring partner treatment.",
       "It can only be acquired through unprotected anal": "Bacterial vaginosis is not restricted to a single specific sexual practice.",
       "It is transmitted exclusively through shared personal": "Fomite transmission through hygiene items is not an established mechanism.",
       "It requires contact tracing identical to that used": "Formal contact tracing protocols are used for reportable STIs, not for bacterial vaginosis."}),

Q(TAG_MOB, "Gardnerella vaginalis vs Trichomonas: wet mount differential",
  "Two women have vaginal discharge and a vaginal pH of 5.0. Wet mount from the first shows epithelial cells stippled with adherent coccobacilli and no motile organisms; the second shows pear-shaped organisms actively swimming with flagella. Which statement correctly distinguishes the two conditions?",
  ["The first shows epithelial cells studded with bacteria, and the second shows motile parasites",
   "The first shows motile parasites, and the second shows epithelial cells studded with bacteria",
   "Both conditions arise from overgrowth of the same anaerobic bacterial species",
   "Neither of these two conditions raises the vaginal pH above the normal acidic range",
   "The first responds only to a topical antifungal, while the second needs oral metronidazole"],
  "Bacterial vaginosis produces clue cells (epithelial cells studded with adherent bacteria) with a raised pH but little inflammation, while trichomoniasis shows the motile flagellated protozoan on wet mount along with a strawberry cervix and a brisk neutrophilic response; both happen to raise vaginal pH but arise from entirely different organisms.",
  difficulty="medium",
  why={"The first shows motile parasites, and the second": "This reverses the findings: clue cells belong to bacterial vaginosis, motile organisms to trichomoniasis.",
       "Both conditions arise from overgrowth of the same": "Trichomoniasis is caused by a flagellated protozoan, not the anaerobic bacteria implicated in bacterial vaginosis.",
       "Neither of these two conditions raises the vaginal": "Both bacterial vaginosis and trichomoniasis characteristically raise vaginal pH above 4.5.",
       "The first responds only to a topical antifungal": "Bacterial vaginosis is treated with metronidazole or clindamycin, not an antifungal."}),

Q(TAG_MOB, "Tropheryma whipplei: arthralgia predates malabsorption",
  "A 58-year-old man has had migratory large-joint arthralgias for six years before now developing chronic diarrhea, weight loss, and abdominal pain. Which statement about this pattern is correct?",
  ["Joint symptoms commonly precede the intestinal disease by a long interval",
   "Joint symptoms always occur after the diarrhea has already resolved",
   "Arthralgia in this disease indicates a coexisting autoimmune arthritis",
   "The arthralgia represents metastatic spread of the intestinal infection",
   "Joint involvement excludes the diagnosis of this intestinal disease"],
  "Whipple disease often begins with intermittent, migratory arthralgias or arthritis of large joints that can precede the gastrointestinal symptoms of malabsorption, weight loss, and diarrhea by several years, which can delay recognition of the underlying Tropheryma whipplei infection.",
  difficulty="hard",
  why={"Joint symptoms always occur after the diarrhea": "The typical sequence is the reverse, with joint symptoms preceding gut disease.",
       "Arthralgia in this disease indicates a coexisting": "The arthralgia is a direct manifestation of the same infection, not a separate autoimmune process.",
       "The arthralgia represents metastatic spread of the": "Bacteria are not described as metastasizing; the joint symptoms reflect the systemic nature of this infection.",
       "Joint involvement excludes the diagnosis of this": "Joint involvement is a classic and expected feature, not an excluding one."}),

Q(TAG_MOB, "Tropheryma whipplei: neurologic involvement",
  "A 62-year-old man with known Whipple disease develops rhythmic, slow contractions of the jaw muscles that occur synchronously with slow, pendular eye movements. Which term describes this finding, and what does its presence indicate?",
  ["Oculomasticatory myorhythmia, signaling brain involvement",
   "Opsoclonus-myoclonus, signaling a paraneoplastic process",
   "Nystagmus, signaling a peripheral vestibular disorder",
   "Blepharospasm, signaling a primary movement disorder",
   "Tardive dyskinesia, signaling prior antipsychotic exposure"],
  "Oculomasticatory myorhythmia is a virtually pathognomonic finding of central nervous system Whipple disease, consisting of synchronized rhythmic movements of eye convergence and jaw muscles; its presence signals neurologic involvement, which requires a treatment regimen that adequately penetrates the CNS.",
  difficulty="hard",
  why={"Opsoclonus-myoclonus, signaling a paraneoplastic": "Opsoclonus-myoclonus is a distinct paraneoplastic or postinfectious syndrome unrelated to Whipple disease.",
       "Nystagmus, signaling a peripheral vestibular": "Isolated nystagmus reflects vestibular pathway dysfunction, not this specific synchronized jaw-eye movement.",
       "Blepharospasm, signaling a primary movement": "Blepharospasm is involuntary eyelid closure without the jaw component described here.",
       "Tardive dyskinesia, signaling prior antipsychotic": "Tardive dyskinesia follows chronic dopamine receptor blockade, unrelated to this infection."}),

Q(TAG_MOB, "Tropheryma whipplei: PCR diagnosis",
  "A patient with suspected Whipple disease has a small bowel biopsy that is inconclusive. Which additional test can confirm active infection and help assess for disseminated or central nervous system disease?",
  ["Polymerase chain reaction for Tropheryma whipplei DNA",
   "Serum antibody titer against Tropheryma whipplei antigen",
   "Fecal fat quantification over a 72-hour collection",
   "Small bowel manometry to assess motility patterns",
   "Serum tissue transglutaminase antibody testing"],
  "PCR for Tropheryma whipplei DNA can be performed on blood, cerebrospinal fluid, or other tissue and is useful both to confirm the diagnosis when biopsy is equivocal and to screen for disseminated or CNS disease, which changes the required duration and choice of antibiotic therapy.",
  difficulty="medium",
  why={"Serum antibody titer against Tropheryma whipplei": "Serologic antibody testing is not a standard, validated diagnostic approach for this organism.",
       "Fecal fat quantification over a 72-hour": "Fecal fat testing documents malabsorption in general but does not identify the causative organism.",
       "Small bowel manometry to assess motility": "Manometry evaluates motor function of the gut and does not detect infection.",
       "Serum tissue transglutaminase antibody testing": "This tests for celiac disease, a different cause of malabsorption."}),

Q(TAG_MOB, "Tropheryma whipplei: treatment to prevent CNS relapse",
  "A patient recently diagnosed with Whipple disease is treated with a two-week course of intravenous ceftriaxone. Which additional step is essential to prevent relapse?",
  ["Continuing oral trimethoprim-sulfamethoxazole for at least one year",
   "Repeating the ceftriaxone course every three months indefinitely",
   "Adding a short course of oral corticosteroids after the antibiotic",
   "Switching to topical antibiotics applied directly to the small bowel",
   "Stopping therapy once diarrhea and weight loss have resolved"],
  "After initial induction therapy with an agent that crosses the blood-brain barrier, such as ceftriaxone, prolonged oral trimethoprim-sulfamethoxazole for about a year is given to prevent relapse, particularly central nervous system relapse, which can occur even after apparent clinical cure of the intestinal disease.",
  difficulty="medium",
  why={"Repeating the ceftriaxone course every three months": "Intermittent repeat dosing is not the standard regimen; a prolonged continuous oral agent is used instead.",
       "Adding a short course of oral corticosteroids": "Corticosteroids have no established role in standard Whipple disease treatment.",
       "Switching to topical antibiotics applied directly": "Topical intestinal antibiotics are not a recognized treatment approach for this systemic infection.",
       "Stopping therapy once diarrhea and weight loss": "Stopping early based on symptom resolution risks relapse, especially in the central nervous system."}),

Q(TAG_MOB, "Tropheryma whipplei vs Mycobacterium avium complex",
  "Small bowel biopsies from two different patients both show the lamina propria distended by foamy macrophages that stain positive with periodic acid-Schiff. One patient has HIV with a very low CD4 count; the other is an immunocompetent older man with arthralgias. Which additional stain distinguishes the two conditions?",
  ["Acid-fast stain, positive only in the immunocompromised patient's specimen",
   "Gram stain, positive only in the immunocompetent patient's specimen",
   "Silver stain, positive only in the immunocompromised patient's specimen",
   "Congo red stain, positive only in the immunocompetent patient's specimen",
   "India ink preparation, positive only in the immunocompetent patient's specimen"],
  "Both Mycobacterium avium complex in advanced HIV and Tropheryma whipplei can fill the lamina propria with PAS-positive foamy macrophages, but MAC organisms are acid-fast while Tropheryma whipplei is not, so an acid-fast stain distinguishes disseminated MAC infection from Whipple disease.",
  difficulty="hard",
  why={"Gram stain, positive only in the immunocompetent": "Gram stain does not reliably differentiate these two intracellular organisms within macrophages.",
       "Silver stain, positive only in the immunocompromised": "Silver stains are used for fungi and Legionella, not to separate these two conditions.",
       "Congo red stain, positive only in the immunocompetent": "Congo red identifies amyloid deposits, unrelated to either organism.",
       "India ink preparation, positive only in the immunocompetent": "India ink is used to visualize the capsule of Cryptococcus, not these organisms."}),

Q(TAG_MOB, "HACEK group: Aggregatibacter and dental disease",
  "A 45-year-old man with poor dentition and a bicuspid aortic valve develops a six-week illness with low-grade fever, fatigue, and a new murmur. Blood cultures eventually grow a slow-growing, fastidious Gram-negative organism after extended incubation. Which feature of this organism explains the delay in culture positivity?",
  ["It requires an increased carbon dioxide atmosphere and grows very slowly",
   "It only grows inside living host cells and cannot be cultured on media at all",
   "It lacks a cell wall, so standard blood culture bottles cannot detect it",
   "It is destroyed by the anticoagulant added to blood culture bottles",
   "It requires a strictly anaerobic atmosphere with no oxygen exposure"],
  "HACEK organisms, including Aggregatibacter, are fastidious oral Gram-negative rods that grow slowly and often need an enriched, carbon dioxide-enhanced atmosphere with extended incubation; modern continuous-monitoring blood culture systems usually detect them within about five days, but they were historically a classic cause of apparently culture-negative endocarditis.",
  difficulty="medium",
  why={"It only grows inside living host cells and cannot": "HACEK organisms are extracellular and do grow on artificial media, unlike obligate intracellular bacteria.",
       "It lacks a cell wall, so standard blood culture": "HACEK organisms are Gram-negative rods with a normal cell wall and outer membrane.",
       "It is destroyed by the anticoagulant added to blood": "Standard blood culture anticoagulants do not inactivate these organisms.",
       "It requires a strictly anaerobic atmosphere with no": "HACEK organisms generally prefer increased carbon dioxide rather than a strictly anaerobic environment."}),

Q(TAG_MOB, "HACEK group: Cardiobacterium hominis",
  "A 60-year-old man with a bicuspid aortic valve and chronic periodontal disease has subacute fever and a new diastolic murmur over several weeks. Blood cultures grow a slow-growing, pleomorphic Gram-negative rod that is part of normal oral and upper respiratory flora. Which organism is this?",
  ["Cardiobacterium hominis",
   "Bartonella henselae",
   "Coxiella burnetii",
   "Legionella pneumophila",
   "Mycoplasma pneumoniae"],
  "Cardiobacterium hominis is a fastidious, pleomorphic Gram-negative rod of the HACEK group found in normal oral flora; it causes subacute native-valve endocarditis, particularly in patients with underlying valve disease or poor dentition, with a course and epidemiology distinct from the other listed intracellular or vector-associated organisms.",
  difficulty="hard",
  why={"Bartonella henselae": "Bartonella causes cat-scratch disease and culture-negative endocarditis but is associated with cat exposure, not dental flora.",
       "Coxiella burnetii": "Coxiella causes Q fever endocarditis after livestock exposure, unrelated to oral flora.",
       "Legionella pneumophila": "Legionella causes pneumonia linked to water sources, not endocarditis from dental flora.",
       "Mycoplasma pneumoniae": "Mycoplasma causes atypical pneumonia and lacks a cell wall, unlike this Gram-negative rod."}),

Q(TAG_MOB, "HACEK group: Eikenella corrodens after a bite",
  "A 30-year-old man punches another person in the mouth and sustains a laceration over the knuckle from contact with teeth. Three days later the wound is swollen, tender, and draining pus. Culture grows a slow-growing, facultative Gram-negative rod that pits the surface of the agar. Which organism is this?",
  ["Eikenella corrodens",
   "Pasteurella multocida",
   "Capnocytophaga canimorsus",
   "Clostridium tetani",
   "Bacteroides fragilis"],
  "Eikenella corrodens is part of normal oral flora and a classic pathogen in clenched-fist ('fight bite') injuries, notable for its ability to pit or corrode the surface of agar media; treatment is with amoxicillin-clavulanate along with surgical exploration when indicated, since it is often part of a polymicrobial oral flora infection.",
  difficulty="medium",
  why={"Pasteurella multocida": "Pasteurella is the classic organism in cat and dog bites, not human bite wounds.",
       "Capnocytophaga canimorsus": "Capnocytophaga causes fulminant sepsis after dog bites, especially in asplenic patients, not human bites.",
       "Clostridium tetani": "Tetanus follows deep puncture wounds contaminated with soil or rust, and it does not pit agar.",
       "Bacteroides fragilis": "Bacteroides is an anaerobic gut organism associated with intra-abdominal infection, not agar pitting from oral flora."}),

Q(TAG_MOB, "Kingella kingae: pediatric septic arthritis",
  "A previously healthy 18-month-old attending daycare develops a limp and refuses to bear weight on one leg, with low-grade fever. Joint aspirate shows neutrophilic inflammation, but the standard aerobic culture remains negative at 48 hours. Which test would most likely identify the causative organism?",
  ["Polymerase chain reaction of the synovial fluid",
   "Acid-fast staining of the synovial fluid sediment",
   "Serum antistreptolysin O antibody titer",
   "Fungal culture of the synovial fluid on Sabouraud agar",
   "Cold agglutinin titer from a peripheral blood sample"],
  "Kingella kingae is a leading cause of septic arthritis and osteomyelitis in children between six months and four years old, often clustering in daycare outbreaks; it grows poorly on routine culture, so PCR of synovial fluid or blood culture bottle inoculation improves detection compared with standard plating.",
  difficulty="medium",
  why={"Acid-fast staining of the synovial fluid sediment": "Acid-fast stains identify mycobacteria, which are not the concern in this acute pediatric presentation.",
       "Serum antistreptolysin O antibody titer": "ASO titers assess prior group A streptococcal infection and its sequelae, not acute joint infection.",
       "Fungal culture of the synovial fluid on Sabouraud": "Fungal septic arthritis is rare in an otherwise healthy toddler and is not the leading consideration here.",
       "Cold agglutinin titer from a peripheral blood": "Cold agglutinins are associated with Mycoplasma pneumoniae infection, unrelated to joint disease."}),

Q(TAG_MOB, "HACEK endocarditis: first-line treatment",
  "A patient with confirmed native-valve endocarditis caused by a HACEK organism has no reported drug allergies. Which empiric antibiotic regimen is preferred while susceptibility results are pending?",
  ["Ceftriaxone given once daily intravenously",
   "Oral amoxicillin-clavulanate for six weeks",
   "Vancomycin combined with gentamicin",
   "Intravenous metronidazole for anaerobic coverage",
   "Oral trimethoprim-sulfamethoxazole for four weeks"],
  "Ceftriaxone is the preferred agent for HACEK endocarditis because these organisms are reliably susceptible and once-daily intravenous dosing is convenient for a prolonged treatment course, unlike the older ampicillin-gentamicin regimens that fell out of favor due to beta-lactamase production and aminoglycoside toxicity.",
  difficulty="easy",
  why={"Oral amoxicillin-clavulanate for six weeks": "Endocarditis from these organisms is treated with intravenous therapy, not an oral regimen.",
       "Vancomycin combined with gentamicin": "This combination targets Gram-positive organisms such as enterococci, not HACEK organisms.",
       "Intravenous metronidazole for anaerobic coverage": "Metronidazole targets anaerobes and has no reliable activity against HACEK organisms.",
       "Oral trimethoprim-sulfamethoxazole for four weeks": "This is not standard therapy for endocarditis caused by HACEK organisms."}),

# ================= Mycoplasma & Ureaplasma =================
Q(TAG_MOB, "Mycoplasma pneumoniae: cold agglutinin mechanism",
  "A 20-year-old with several days of dry cough and low-grade fever develops pallor and dark urine. Peripheral smear shows red cell agglutination that reverses on warming the sample. Which mechanism explains the anemia?",
  ["IgM antibodies against the I antigen fix complement at cold temperatures",
   "IgG antibodies against Rh antigens cause extravascular hemolysis at 37°C",
   "Direct bacterial invasion and lysis of circulating red blood cells",
   "Oxidative damage to hemoglobin from a drug metabolite in the plasma",
   "Mechanical shearing of red cells across an abnormal heart valve"],
  "Mycoplasma pneumoniae infection can induce IgM autoantibodies directed against the I antigen on red blood cells; these agglutinate cells and fix complement preferentially in cooler peripheral body temperatures, causing a cold agglutinin-mediated hemolytic anemia that improves as the underlying infection resolves.",
  difficulty="medium",
  why={"IgG antibodies against Rh antigens cause": "Warm IgG autoimmune hemolytic anemia against Rh antigens is a different process, unrelated to cold agglutinins.",
       "Direct bacterial invasion and lysis of circulating": "Mycoplasma does not invade or directly lyse red blood cells; the hemolysis is antibody-mediated.",
       "Oxidative damage to hemoglobin from a drug": "Oxidative hemolysis relates to G6PD deficiency and certain drugs, not this infection.",
       "Mechanical shearing of red cells across an abnormal": "Mechanical hemolysis occurs with damaged prosthetic valves or microangiopathy, not this infection."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: diagnostic testing",
  "A 24-year-old military recruit has a persistent dry cough and patchy infiltrates that seem more extensive on chest x-ray than the mild physical exam would suggest. A cold agglutinin titer is mildly elevated. Which test result would most specifically confirm active Mycoplasma pneumoniae infection?",
  ["A positive polymerase chain reaction from a respiratory specimen",
   "A cold agglutinin titer above 1:32 alone, without further testing",
   "Growth of the organism on routine blood agar within 24 hours",
   "A Gram stain of sputum showing small Gram-negative coccobacilli",
   "An elevated total white blood cell count with marked left shift"],
  "Cold agglutinins are an insensitive and nonspecific finding also seen with other infections and are not diagnostic alone; PCR of a respiratory specimen is the most specific and now preferred confirmatory test for Mycoplasma pneumoniae, since the organism does not grow on routine media and has no cell wall to visualize by Gram stain.",
  difficulty="medium",
  why={"A cold agglutinin titer above 1:32 alone, without": "Cold agglutinins can be elevated in other conditions and are not specific enough to confirm the diagnosis by themselves.",
       "Growth of the organism on routine blood agar": "Mycoplasma requires special cholesterol-supplemented media and grows far too slowly for a 24-hour result.",
       "A Gram stain of sputum showing small Gram-negative": "Mycoplasma lacks a cell wall entirely and cannot be visualized or classified by Gram stain.",
       "An elevated total white blood cell count with marked": "Atypical pneumonia from Mycoplasma classically shows a normal or only mildly elevated white count, and this finding is nonspecific."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: mucocutaneous complication",
  "A 16-year-old boy develops fever and cough, then several days later erosive lesions of the lips and oral mucosa with sparse target-like skin lesions on the extremities, but minimal skin detachment overall. Which process best explains this presentation?",
  ["A Mycoplasma-triggered eruption with mucosa-predominant involvement",
   "Direct bacterial invasion and infection of the oral mucosa itself",
   "An IgE-mediated drug reaction to a recently started antibiotic",
   "Autoimmune blistering disease with antibodies against desmoglein 3",
   "Viral reactivation causing grouped vesicles in a dermatomal band"],
  "Mycoplasma pneumoniae infection can trigger a mucocutaneous eruption with prominent, often severe mucositis (oral, ocular, and sometimes urogenital) but comparatively sparse and limited true skin lesions, a pattern now often distinguished from classic drug-induced Stevens-Johnson syndrome as Mycoplasma-induced rash and mucositis.",
  difficulty="hard",
  why={"Direct bacterial invasion and infection of the oral": "The mucocutaneous findings are immune-mediated reactions to the infection, not direct bacterial invasion of the mucosa.",
       "An IgE-mediated drug reaction to a recently started": "This vignette describes a reaction temporally tied to the infection itself, not a new medication.",
       "Autoimmune blistering disease with antibodies against": "Pemphigus vulgaris is a chronic autoimmune disease unrelated to a preceding respiratory infection.",
       "Viral reactivation causing grouped vesicles in a": "A dermatomal vesicular eruption describes herpes zoster, a different pattern from diffuse mucosal erosions."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: bullous myringitis",
  "A 15-year-old with several days of dry cough and headache develops sudden severe ear pain. Otoscopy shows fluid-filled vesicles on an erythematous, bulging tympanic membrane. Which organism is most strongly associated with this specific ear finding?",
  ["Mycoplasma pneumoniae",
   "Streptococcus pneumoniae",
   "Haemophilus influenzae",
   "Moraxella catarrhalis",
   "Pseudomonas aeruginosa"],
  "Bullous myringitis, painful vesicles or bullae on the tympanic membrane, is classically associated with Mycoplasma pneumoniae infection accompanying atypical pneumonia, distinguishing it from the more common bacterial causes of straightforward otitis media without bullae.",
  difficulty="medium",
  why={"Streptococcus pneumoniae": "Pneumococcus is a leading cause of typical otitis media but is not the organism classically tied to bullous vesicles on the eardrum.",
       "Haemophilus influenzae": "Haemophilus causes typical otitis media and sinusitis, not the specific bullous tympanic finding.",
       "Moraxella catarrhalis": "Moraxella causes otitis media and sinusitis in children without the classic bullous myringitis association.",
       "Pseudomonas aeruginosa": "Pseudomonas is linked to malignant otitis externa in diabetics, a different clinical picture entirely."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: clinical-radiographic dissociation",
  "A 22-year-old has a dry cough, headache, and low-grade fever for a week and still goes to work daily. Chest x-ray shows patchy bilateral interstitial infiltrates that appear more severe than his mild symptoms suggest. Which feature is most characteristic of this presentation?",
  ["The radiographic findings look worse than the clinical exam suggests",
   "The chest x-ray typically shows a single dense lobar consolidation",
   "The patient is usually too ill to continue daily activities",
   "Sputum is typically copious, purulent, and blood-streaked",
   "Symptoms characteristically begin abruptly with rigors and high fever"],
  "Mycoplasma pneumoniae causes 'walking pneumonia,' named because patients remain ambulatory and relatively well-appearing despite chest imaging that often looks more extensive than the mild clinical symptoms would predict, unlike the more toxic-appearing presentation of classic bacterial lobar pneumonia.",
  difficulty="easy",
  why={"The chest x-ray typically shows a single dense lobar": "A single dense lobar consolidation is more typical of pneumococcal pneumonia, not the patchy interstitial pattern of Mycoplasma.",
       "The patient is usually too ill to continue daily": "Patients with this illness are classically well enough to remain ambulatory, which gives the syndrome its name.",
       "Sputum is typically copious, purulent, and blood": "Mycoplasma pneumonia usually causes a dry, nonproductive cough rather than copious purulent sputum.",
       "Symptoms characteristically begin abruptly with rigors": "The onset is typically gradual over days, not abrupt with rigors as seen in classic bacterial pneumonia."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: beta-lactam ineffectiveness",
  "A patient with confirmed Mycoplasma pneumoniae infection is treated with amoxicillin and shows no clinical improvement after five days. What best explains this treatment failure?",
  ["The organism lacks a peptidoglycan cell wall, the drug's target structure",
   "The organism produces a beta-lactamase enzyme that inactivates amoxicillin",
   "The organism has altered penicillin-binding proteins with low drug affinity",
   "Amoxicillin is inactivated by pulmonary surfactant before reaching the organism",
   "The organism resides intracellularly where amoxicillin cannot penetrate at all"],
  "Mycoplasma species entirely lack a cell wall and therefore have no peptidoglycan target for beta-lactam antibiotics such as amoxicillin, making all beta-lactams inherently ineffective regardless of dose; effective agents instead target protein or nucleic acid synthesis, such as macrolides, tetracyclines, or fluoroquinolones.",
  difficulty="easy",
  why={"The organism produces a beta-lactamase enzyme that": "Beta-lactamase production is not the reason for resistance here; the organism simply has no wall target at all.",
       "The organism has altered penicillin-binding proteins": "Altered PBPs describe resistance mechanisms in organisms that still have a cell wall, unlike Mycoplasma.",
       "Amoxicillin is inactivated by pulmonary surfactant": "Surfactant inactivation describes a different drug's failure in pneumonia (daptomycin), not amoxicillin's mechanism here.",
       "The organism resides intracellularly where amoxicillin": "Mycoplasma is primarily an extracellular pathogen adherent to respiratory epithelium, not an intracellular one."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: adhesin and ciliary damage",
  "Mycoplasma pneumoniae attaches tightly to respiratory epithelial cells using a specialized terminal organelle before causing local tissue damage and a persistent cough. Which protein mediates this attachment?",
  ["P1 adhesin binding to sialylated receptors on epithelial cells",
   "Pilin subunits assembling into retractable type IV pili",
   "Filamentous hemagglutinin binding to ciliated epithelium",
   "Fimbrial adhesin binding to mannose residues on epithelial cells",
   "Flagellin monomers binding to Toll-like receptor 5"],
  "Mycoplasma pneumoniae uses its P1 adhesin, concentrated at a specialized terminal attachment organelle, to bind sialylated receptors on respiratory epithelial cells; this tight attachment allows the organism to damage cilia and epithelium locally, producing the prolonged, often severe cough characteristic of the infection despite minimal systemic toxicity.",
  difficulty="hard",
  why={"Pilin subunits assembling into retractable type IV": "Type IV pili and twitching motility are a mechanism used by organisms such as Neisseria and Pseudomonas, not Mycoplasma.",
       "Filamentous hemagglutinin binding to ciliated": "Filamentous hemagglutinin is the adhesin of Bordetella pertussis, not Mycoplasma pneumoniae.",
       "Fimbrial adhesin binding to mannose residues on": "Mannose-binding type 1 fimbriae are characteristic of uropathogenic E. coli, an unrelated organism.",
       "Flagellin monomers binding to Toll-like receptor 5": "Mycoplasma is nonmotile by flagella and does not use flagellin as its attachment mechanism."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: macrolide resistance",
  "A child in East Asia with confirmed Mycoplasma pneumoniae pneumonia continues to have high fever after five days of azithromycin. Testing reveals a ribosomal mutation conferring drug resistance. Which alternative agent is appropriate given the patient's age?",
  ["Doxycycline, despite the usual caution about young children",
   "Amoxicillin-clavulanate at a higher weight-based dose",
   "A prolonged second course of the same macrolide",
   "Intravenous vancomycin for broader Gram-positive coverage",
   "Oral metronidazole to cover resistant anaerobic organisms"],
  "Macrolide-resistant Mycoplasma pneumoniae, from ribosomal target mutations, has become common in parts of East Asia; when azithromycin fails, doxycycline (or a fluoroquinolone in older patients) is used despite the usual reluctance to give tetracyclines to young children, because the risk of prolonged untreated pneumonia is judged to outweigh the small risk of dental staining with a short course.",
  difficulty="hard",
  why={"Amoxicillin-clavulanate at a higher weight-based": "Mycoplasma has no cell wall, so beta-lactams including amoxicillin-clavulanate remain ineffective regardless of dose.",
       "A prolonged second course of the same macrolide": "Repeating the same class of drug does not overcome a ribosomal mutation causing macrolide resistance.",
       "Intravenous vancomycin for broader Gram-positive": "Vancomycin targets the cell wall, which Mycoplasma lacks, and has no activity against it.",
       "Oral metronidazole to cover resistant anaerobic": "Metronidazole targets anaerobic bacteria and protozoa, not Mycoplasma."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: post-infectious encephalitis",
  "Two weeks after a mild respiratory illness with dry cough, a 12-year-old develops confusion, ataxia, and new focal weakness. Respiratory PCR from the earlier illness had confirmed Mycoplasma pneumoniae. What is the most likely explanation for the current neurologic picture?",
  ["A postinfectious, immune-mediated encephalitis from molecular mimicry",
   "Direct hematogenous seeding of the brain by circulating bacteria",
   "A structural brain abscess forming at the site of bacterial invasion",
   "Reactivation of a latent neurotropic virus following recent stress",
   "A toxin-mediated descending paralysis identical to botulism"],
  "Mycoplasma pneumoniae is a recognized trigger of postinfectious encephalitis and other neurologic complications, thought to arise from an immune-mediated (para- or post-infectious) mechanism rather than direct bacterial invasion of the central nervous system, typically appearing one to three weeks after the respiratory illness.",
  difficulty="hard",
  why={"Direct hematogenous seeding of the brain by": "Mycoplasma central nervous system disease is generally attributed to immune mechanisms rather than direct organism invasion of brain tissue.",
       "A structural brain abscess forming at the site of": "This presentation describes a diffuse encephalitic picture, not a focal abscess from bacterial invasion.",
       "Reactivation of a latent neurotropic virus": "Mycoplasma is a bacterium and does not establish the kind of latency associated with neurotropic viruses.",
       "A toxin-mediated descending paralysis identical": "Botulism causes a descending flaccid paralysis without confusion, a very different clinical picture."}),

Q(TAG_MOB, "Mycoplasma vs Legionella: distinguishing atypical pneumonias",
  "Two patients present separately with atypical pneumonia. One has mild illness after living in a college dormitory; the other has severe pneumonia with confusion, diarrhea, and hyponatremia after a hotel stay with a recently serviced cooling tower. Which laboratory feature would help distinguish the second patient's likely infection?",
  ["A positive urinary antigen test for a specific serogroup",
   "A positive cold agglutinin titer confirming the diagnosis",
   "Growth of the organism on routine unsupplemented blood agar",
   "A Gram stain showing small pleomorphic coccobacilli directly",
   "An elevated rapid plasma reagin titer supporting the diagnosis"],
  "Legionella pneumophila, linked to exposures such as cooling towers and hotel water systems, often causes more severe pneumonia with extrapulmonary features like diarrhea, confusion, and hyponatremia, and is identified with a urinary antigen test for serogroup 1; Mycoplasma pneumoniae, by contrast, causes the milder dormitory-associated illness and cannot be confirmed this way.",
  difficulty="medium",
  why={"A positive cold agglutinin titer confirming the": "Cold agglutinins are associated with Mycoplasma, not Legionella, and are nonspecific even there.",
       "Growth of the organism on routine unsupplemented": "Legionella requires special buffered charcoal yeast extract media, not routine blood agar, and grows slowly.",
       "A Gram stain showing small pleomorphic coccobacilli": "Legionella stains poorly with Gram stain and is better visualized with silver stains or direct fluorescent antibody.",
       "An elevated rapid plasma reagin titer supporting": "RPR is a screening test for syphilis and is unrelated to either pneumonia."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: complement fixation vs PCR",
  "A hospital laboratory is deciding whether to continue using a complement fixation antibody assay or transition to a molecular assay for diagnosing acute Mycoplasma pneumoniae infection. Which limitation applies specifically to the antibody-based approach?",
  ["A significant rise in titer between paired serum samples may take weeks to appear",
   "The antibody assay cannot be performed on any specimen from a symptomatic patient",
   "The antibody assay requires the organism to be cultured before testing can begin",
   "The antibody assay detects an antigen that is also present in normal respiratory flora",
   "The antibody assay is falsely negative in nearly all patients with true infection"],
  "Paired acute and convalescent serology (such as complement fixation) requires a fourfold rise in antibody titer measured weeks apart, which delays diagnosis and is impractical for guiding acute treatment decisions, unlike PCR of a respiratory specimen, which can rapidly confirm infection during the acute illness itself.",
  difficulty="hard",
  why={"The antibody assay cannot be performed on any": "Serum can be drawn from a symptomatic patient; the limitation is the delay in obtaining a diagnostic titer rise, not an inability to sample.",
       "The antibody assay requires the organism to be": "Serologic antibody testing does not require culturing the organism first.",
       "The antibody assay detects an antigen that is also": "The limitation described relates to timing of the titer rise, not cross-reactivity with normal flora antigens.",
       "The antibody assay is falsely negative in nearly all": "Serology does eventually become positive in true infection; the issue is the delay, not a near-universal false negative."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: normal white blood cell count",
  "A 26-year-old with a gradually worsening dry cough and low-grade fever over ten days has a complete blood count showing a white blood cell count within the normal range. Which organism is this laboratory finding most consistent with?",
  ["Mycoplasma pneumoniae",
   "Streptococcus pneumoniae",
   "Staphylococcus aureus",
   "Klebsiella pneumoniae",
   "Haemophilus influenzae"],
  "Atypical pneumonia from Mycoplasma pneumoniae classically presents with a normal or only mildly elevated white blood cell count, in contrast to the marked leukocytosis with neutrophilia typically seen in classic bacterial pneumonias caused by pneumococcus, staphylococcus, or the enteric Gram-negative rods.",
  difficulty="easy",
  why={"Streptococcus pneumoniae": "Pneumococcal pneumonia typically produces a marked leukocytosis with neutrophilia, unlike this presentation.",
       "Staphylococcus aureus": "Staphylococcal pneumonia is usually severe and accompanied by a significant leukocytosis.",
       "Klebsiella pneumoniae": "Klebsiella pneumonia in its classic form causes marked leukocytosis along with a toxic clinical appearance.",
       "Haemophilus influenzae": "Haemophilus pneumonia, especially in patients with underlying lung disease, typically raises the white blood cell count."}),

Q(TAG_MOB, "Ureaplasma urealyticum: urethritis after chlamydia is excluded",
  "A 24-year-old man has recurrent dysuria and mucoid urethral discharge. Testing for Chlamydia trachomatis and Neisseria gonorrhoeae is negative. Which organism, identified by its ability to hydrolyze urea, should be considered as a cause of his nongonococcal urethritis?",
  ["Ureaplasma urealyticum",
   "Proteus mirabilis",
   "Trichomonas vaginalis",
   "Klebsiella granulomatis",
   "Haemophilus ducreyi"],
  "Ureaplasma urealyticum, like Mycoplasma, lacks a cell wall but is distinguished by its urease activity, which hydrolyzes urea; it is a recognized cause of nongonococcal, non-chlamydial urethritis and is treated with the same protein- or nucleic-acid-targeting antibiotics used for Mycoplasma, since beta-lactams are ineffective against it as well.",
  difficulty="medium",
  why={"Proteus mirabilis": "Proteus is also urease-positive but is a Gram-negative rod causing urinary tract infection with struvite stones, not this urethritis syndrome.",
       "Trichomonas vaginalis": "Trichomonas is a flagellated protozoan detected by motility on wet mount, not by urease activity.",
       "Klebsiella granulomatis": "Klebsiella granulomatis causes granuloma inguinale with genital ulceration, not a urease-based urethritis picture.",
       "Haemophilus ducreyi": "Haemophilus ducreyi causes chancroid, a painful genital ulcer, rather than nongonococcal urethritis."}),

Q(TAG_MOB, "Ureaplasma: neonatal pulmonary complication",
  "A very premature infant born after prolonged rupture of membranes and maternal genital colonization with Ureaplasma develops persistent respiratory distress and eventually chronic lung changes requiring prolonged oxygen support. Which condition is this organism most associated with contributing to in preterm infants?",
  ["Bronchopulmonary dysplasia and long-term lung disease of prematurity",
   "Congenital heart block from transplacental antibody transfer",
   "Necrotizing enterocolitis from ischemic bowel injury",
   "Congenital cataracts from first-trimester viral infection",
   "Sensorineural hearing loss from cochlear inflammation"],
  "Ureaplasma species can colonize the amniotic fluid and respiratory tract of very preterm infants and are associated with chorioamnionitis and an increased risk of bronchopulmonary dysplasia, contributing to chronic lung disease of prematurity beyond what prematurity alone would explain.",
  difficulty="hard",
  why={"Congenital heart block from transplacental antibody": "Congenital heart block is associated with maternal anti-Ro/SSA antibodies in autoimmune disease, not Ureaplasma.",
       "Necrotizing enterocolitis from ischemic bowel": "Necrotizing enterocolitis relates to prematurity and gut ischemia, not primarily to Ureaplasma colonization.",
       "Congenital cataracts from first-trimester viral": "Congenital cataracts are classically linked to first-trimester rubella infection, an unrelated organism.",
       "Sensorineural hearing loss from cochlear": "Congenital hearing loss is classically linked to cytomegalovirus infection, not Ureaplasma."}),

Q(TAG_MOB, "Mycoplasma genitalium: persistent urethritis",
  "A 29-year-old man completes a full course of doxycycline for chlamydial urethritis, but dysuria and discharge persist. Repeat testing for Chlamydia trachomatis and Neisseria gonorrhoeae is now negative. Which organism should be considered as a cause of his ongoing symptoms?",
  ["Mycoplasma genitalium",
   "Escherichia coli",
   "Candida albicans",
   "Gardnerella vaginalis",
   "Treponema pallidum"],
  "Mycoplasma genitalium is an increasingly recognized cause of persistent or recurrent nongonococcal urethritis after apparently adequate treatment for chlamydia, and it is not reliably covered by the standard doxycycline regimen used for other causes of urethritis.",
  difficulty="medium",
  why={"Escherichia coli": "E. coli more typically causes urinary tract infection or epididymitis in older men, not this pattern of persistent urethritis.",
       "Candida albicans": "Candidal balanitis causes penile irritation and a rash rather than the discharge-with-dysuria urethritis syndrome described.",
       "Gardnerella vaginalis": "Gardnerella is associated with vaginal flora disturbance in women, not male urethritis.",
       "Treponema pallidum": "Syphilis classically presents with a painless genital ulcer (chancre), not persistent urethral discharge."}),

Q(TAG_MOB, "Mycoplasma genitalium: resistance-guided therapy",
  "A man with confirmed Mycoplasma genitalium urethritis fails to improve after a standard azithromycin regimen, and testing reveals a macrolide-resistance mutation. Which antibiotic is the preferred next choice?",
  ["Moxifloxacin",
   "Amoxicillin",
   "Nitrofurantoin",
   "Trimethoprim-sulfamethoxazole",
   "Vancomycin"],
  "Macrolide resistance has become common in Mycoplasma genitalium, so resistance-guided therapy with moxifloxacin, a fluoroquinolone, is recommended when azithromycin fails or resistance is detected, since it targets DNA gyrase and topoisomerase rather than the ribosomal site affected by macrolide resistance mutations.",
  difficulty="hard",
  why={"Amoxicillin": "Mycoplasma genitalium lacks a cell wall, so beta-lactams such as amoxicillin have no activity regardless of resistance pattern.",
       "Nitrofurantoin": "Nitrofurantoin is used for uncomplicated urinary tract infection and has no established role for this organism.",
       "Trimethoprim-sulfamethoxazole": "This combination is not the recommended resistance-guided therapy for macrolide-resistant Mycoplasma genitalium.",
       "Vancomycin": "Vancomycin acts on cell wall synthesis, a target that does not exist in this organism."}),

# ================= Rickettsiae, Ehrlichia, Anaplasma & Coxiella =================
Q(TAG_RC, "RMSF: delayed treatment and complications",
  "A 9-year-old boy with fever, headache, and a petechial rash on the wrists and ankles is initially treated only with supportive fluids for a presumed viral illness. Four days later he develops digital gangrene, hypotension, and acute kidney injury. What does this course illustrate about this disease?",
  ["Delaying doxycycline until laboratory confirmation raises the risk of severe complications",
   "Antibiotics provide no mortality benefit once the rash has appeared on the extremities",
   "The organism becomes resistant to doxycycline after several days of untreated infection",
   "Gangrene in this disease indicates an unrelated, coincidental vascular disease process",
   "Kidney injury in this disease is always reversible regardless of treatment timing"],
  "Rocky Mountain spotted fever can progress rapidly from nonspecific symptoms to vasculitis-driven complications such as digital or limb gangrene, hypotension, and multiorgan injury; treatment with doxycycline should begin on clinical suspicion without waiting for confirmatory serology, because delay is directly linked to increased morbidity and mortality.",
  difficulty="medium",
  why={"Antibiotics provide no mortality benefit once the": "Doxycycline still reduces mortality even after rash onset; earlier treatment simply improves outcomes further.",
       "The organism becomes resistant to doxycycline after": "Rickettsia rickettsii does not develop doxycycline resistance over the course of untreated infection.",
       "Gangrene in this disease indicates an unrelated": "The gangrene results directly from rickettsial vasculitis and small vessel thrombosis, not a coincidental process.",
       "Kidney injury in this disease is always reversible": "Severe, delayed cases can cause lasting organ injury; outcomes are not uniformly reversible."}),

Q(TAG_RC, "RMSF vs meningococcemia: differential diagnosis",
  "A 16-year-old has fever, headache, and a petechial rash that began on the wrists and ankles four days ago, one week after a camping trip. Meningococcemia is also being considered. Which feature would most favor Rocky Mountain spotted fever over meningococcemia?",
  ["A rash that started at the distal extremities and spread toward the trunk",
   "The presence of fever accompanying the rash on examination",
   "Thrombocytopenia found on the complete blood count",
   "Hypotension developing over the following day",
   "A rash made up of petechiae rather than a solid erythematous patch"],
  "Rocky Mountain spotted fever classically produces a rash that starts on the wrists and ankles and spreads centrally to the trunk, whereas meningococcemia typically produces a petechial or purpuric rash that starts on the trunk and extremities more diffusely and can progress rapidly to purpura fulminans; the peripheral-to-central distribution is a helpful distinguishing clue alongside the tick exposure history.",
  difficulty="medium",
  why={"The presence of fever accompanying the rash on": "Fever accompanies the rash in both conditions and does not distinguish between them.",
       "Thrombocytopenia found on the complete blood count": "Thrombocytopenia can occur in both Rocky Mountain spotted fever and meningococcemia and is not specific.",
       "Hypotension developing over the following day": "Both diseases can progress to hypotension and shock, so this does not reliably distinguish them.",
       "A rash made up of petechiae rather than a solid": "Both conditions can present with petechial rashes, so morphology alone does not separate them."}),

Q(TAG_RC, "Weil-Felix reaction: historical serology",
  "Before modern serologic and molecular assays were available, clinicians used a test based on cross-reacting antibodies against certain Proteus antigens to support a diagnosis of rickettsial infection. Why has this test largely been abandoned?",
  ["It has poor sensitivity and specificity because the cross-reaction is nonspecific",
   "It requires a live rickettsial culture that is hazardous to prepare",
   "It cannot be performed using any commercially available laboratory reagents",
   "It gives a positive result only after the patient has already died",
   "It specifically detects only Coxiella burnetii and no other organism"],
  "The Weil-Felix reaction relies on the coincidental cross-reactivity between certain rickettsial antigens and Proteus OX strains, agglutinating Proteus with patient serum; it has largely been replaced by more sensitive and specific methods such as PCR and immunofluorescence assays because the cross-reaction is unreliable and nonspecific.",
  difficulty="hard",
  why={"It requires a live rickettsial culture that is": "The Weil-Felix test actually avoids handling live rickettsiae by using Proteus antigens instead.",
       "It cannot be performed using any commercially": "The test uses standard Proteus strains and reagents that are technically simple to obtain, not the reason it fell out of favor.",
       "It gives a positive result only after the patient": "The test can be positive in survivors during illness; timing after death is not the issue.",
       "It specifically detects only Coxiella burnetii and": "Coxiella burnetii classically does not produce a positive Weil-Felix reaction at all, unlike the other rickettsiae."}),

Q(TAG_RC, "RMSF without a rash",
  "A 6-year-old boy in a Rocky Mountain spotted fever-endemic area has three days of high fever, severe headache, and vomiting after a recent hiking trip, with no rash on repeated examination. Thrombocytopenia and hyponatremia are present. What is the most appropriate approach?",
  ["Start doxycycline empirically based on clinical suspicion alone",
   "Withhold antibiotics until a rash appears to confirm the diagnosis",
   "Order a Weil-Felix titer and wait for the result before treating",
   "Reassure the family, since a rash must always be present initially",
   "Treat instead with amoxicillin, which covers the likely alternative diagnosis"],
  "A substantial proportion of Rocky Mountain spotted fever cases, sometimes called 'spotless fever,' lack a rash for the first several days of illness or never develop one; because delayed treatment increases mortality, doxycycline should be started empirically based on the clinical picture, exposure history, and supportive labs such as thrombocytopenia and hyponatremia, without waiting for a rash or confirmatory testing.",
  difficulty="medium",
  why={"Withhold antibiotics until a rash appears to confirm": "Waiting for a rash that may never appear risks a dangerous treatment delay in a potentially fatal illness.",
       "Order a Weil-Felix titer and wait for the result": "Serologic confirmation takes time and is unreliable, so treatment should not be delayed pending this result.",
       "Reassure the family, since a rash must always be": "A rash is common but not universal, especially early in the illness, so its absence does not exclude the diagnosis.",
       "Treat instead with amoxicillin, which covers the": "Amoxicillin has no activity against Rickettsia and would not address the likely diagnosis."}),

Q(TAG_RC, "Anaplasma phagocytophilum: neutrophil morulae",
  "A 48-year-old man from Wisconsin has fever, headache, and myalgias one week after removing an engorged tick. He has no rash. Peripheral blood smear shows small, berry-like clusters of bacteria within the cytoplasm of neutrophils. Which organism and vector combination fits this finding?",
  ["Anaplasma phagocytophilum, transmitted by an Ixodes tick",
   "Ehrlichia chaffeensis, transmitted by the lone star tick",
   "Rickettsia rickettsii, transmitted by a Dermacentor tick",
   "Babesia microti, transmitted by an Ixodes tick",
   "Borrelia burgdorferi, transmitted by an Ixodes tick"],
  "Anaplasma phagocytophilum causes human granulocytic anaplasmosis and forms morulae within neutrophils, in contrast to Ehrlichia chaffeensis, which infects monocytes; both are tick-borne intracellular organisms treated with doxycycline, but Anaplasma is transmitted by Ixodes ticks, the same vector responsible for Lyme disease and babesiosis, allowing coinfection.",
  difficulty="hard",
  why={"Ehrlichia chaffeensis, transmitted by the lone star": "Ehrlichia chaffeensis forms morulae in monocytes and is transmitted by the lone star tick, not the pattern described here.",
       "Rickettsia rickettsii, transmitted by a Dermacentor": "Rickettsia rickettsii infects endothelial cells and does not form intracellular morulae within neutrophils.",
       "Babesia microti, transmitted by an Ixodes tick": "Babesia is a protozoan found within red blood cells as ring forms, not within neutrophils as morulae.",
       "Borrelia burgdorferi, transmitted by an Ixodes tick": "Borrelia is a spirochete seen on dark-field microscopy, not as intracellular clusters within neutrophils."}),

Q(TAG_RC, "Q fever: risk in pregnancy",
  "A pregnant sheep farmer is exposed to an aerosol from a ewe during an unattended lambing. Her serology later confirms acute Coxiella burnetii infection. Which pregnancy-related risk is of particular concern with this infection?",
  ["Placental infection with risk of miscarriage or preterm delivery",
   "Transplacental viral infection causing fetal limb hypoplasia",
   "Maternal infection causing isolated fetal deafness without other effects",
   "Fetal infection leading exclusively to a characteristic skin rash at birth",
   "Ascending infection causing an isolated postpartum urinary tract infection"],
  "Coxiella burnetii has a particular tropism for placental tissue, and infection during pregnancy carries an increased risk of miscarriage, preterm delivery, and low birth weight; because of this risk, pregnant women with acute or chronic Q fever are typically treated with a prolonged course of an antibiotic considered safer in pregnancy rather than doxycycline.",
  difficulty="hard",
  why={"Transplacental viral infection causing fetal limb": "Limb hypoplasia is a feature of congenital varicella infection, an unrelated viral disease.",
       "Maternal infection causing isolated fetal deafness": "Isolated congenital deafness without other effects is more classically linked to congenital cytomegalovirus infection.",
       "Fetal infection leading exclusively to a": "Congenital rash at birth is not the characteristic complication of maternal Q fever.",
       "Ascending infection causing an isolated postpartum": "Q fever's placental tropism causes pregnancy loss risk, not an isolated postpartum urinary infection."}),

Q(TAG_RC, "Q fever endocarditis: prolonged combination therapy",
  "A patient with a prosthetic heart valve is diagnosed with chronic Q fever endocarditis based on serology showing a very high phase I antibody titer. Which treatment regimen is used, and for how long?",
  ["Doxycycline plus hydroxychloroquine for at least eighteen months",
   "A single two-week course of intravenous ceftriaxone alone",
   "Oral azithromycin monotherapy continued for one full year",
   "Intravenous vancomycin plus gentamicin for six full weeks",
   "A two-week course of oral metronidazole with valve replacement"],
  "Chronic Q fever endocarditis requires prolonged combination therapy, typically doxycycline plus hydroxychloroquine, continued for at least eighteen months for a prosthetic valve; hydroxychloroquine raises intracellular pH within the phagolysosome, which restores doxycycline's bactericidal activity against this organism that would otherwise only be suppressed.",
  difficulty="hard",
  why={"A single two-week course of intravenous ceftriaxone": "A short ceftriaxone course is inadequate for this chronic, relapsing intracellular infection.",
       "Oral azithromycin monotherapy continued for one": "Monotherapy with a macrolide is not the standard regimen for chronic Q fever endocarditis.",
       "Intravenous vancomycin plus gentamicin for six": "This combination targets Gram-positive organisms such as enterococci, not Coxiella burnetii.",
       "A two-week course of oral metronidazole with valve": "Metronidazole has no activity against Coxiella burnetii, an obligate intracellular organism."}),

Q(TAG_RC, "Murine typhus: urban flea-borne reservoir",
  "A person living in a warm coastal city with a significant rat and opossum population develops fever, headache, and a mild maculopapular rash on the trunk. No tick exposure is reported. Which organism and reservoir combination is most likely?",
  ["Rickettsia typhi, maintained in an urban rodent flea cycle",
   "Rickettsia prowazekii, maintained in human body louse populations",
   "Rickettsia rickettsii, maintained in Dermacentor tick populations",
   "Orientia tsutsugamushi, maintained in trombiculid mite populations",
   "Coxiella burnetii, maintained in livestock birthing tissue"],
  "Murine (endemic) typhus is caused by Rickettsia typhi and is maintained in urban and suburban flea cycles involving rats and, in some regions, opossums, producing a generally milder illness than epidemic typhus, which instead circulates among humans through body lice, especially in crowded or unsanitary conditions.",
  difficulty="medium",
  why={"Rickettsia prowazekii, maintained in human body": "Epidemic typhus circulates through human body lice in crowded settings, not through an urban rodent-flea cycle.",
       "Rickettsia rickettsii, maintained in Dermacentor": "Rocky Mountain spotted fever is tick-borne, with a rash pattern and vector distinct from this flea-borne illness.",
       "Orientia tsutsugamushi, maintained in trombiculid": "Scrub typhus is transmitted by mite larvae (chiggers) in specific geographic regions, not through an urban rat-flea cycle.",
       "Coxiella burnetii, maintained in livestock birthing": "Q fever is acquired by inhaling aerosols from livestock birth products, unrelated to fleas or rodents."}),

Q(TAG_RC, "Ehrlichiosis: empiric treatment before confirmation",
  "A 50-year-old man from Missouri has fever, headache, and myalgias after a tick bite, with leukopenia, thrombocytopenia, and elevated transaminases on initial labs. Confirmatory serology will not be available for several days. What is the most appropriate immediate management?",
  ["Start doxycycline now, without waiting for the lab results",
   "Withhold antibiotics until serology confirms the specific organism",
   "Begin broad-spectrum antifungal therapy while awaiting results",
   "Order a bone marrow biopsy before deciding on any treatment",
   "Treat only if a rash develops over the following days"],
  "Ehrlichiosis and anaplasmosis are diagnosed clinically and treated empirically with doxycycline based on exposure history and compatible laboratory findings such as leukopenia, thrombocytopenia, and transaminitis, because waiting for serologic confirmation, which often requires paired acute and convalescent titers, would dangerously delay treatment of a potentially severe illness.",
  difficulty="medium",
  why={"Withhold antibiotics until serology confirms the": "Confirmatory serology can take days, and delaying treatment increases the risk of severe or fatal disease.",
       "Begin broad-spectrum antifungal therapy while": "There is no fungal component to this illness, so antifungal therapy would not address the underlying infection.",
       "Order a bone marrow biopsy before deciding on any": "A bone marrow biopsy is not part of the standard workup or a prerequisite for starting treatment.",
       "Treat only if a rash develops over the following": "Most patients with ehrlichiosis never develop a rash, so waiting for one would likely mean never treating."}),

Q(TAG_RC, "Tick-borne intracellular infections: lab pattern differential",
  "A patient with fever after a recent tick bite has leukopenia, thrombocytopenia, and mildly elevated liver transaminases, but no rash and no joint symptoms. A colleague suggests early Lyme disease as the cause. Why does this laboratory pattern argue against that diagnosis?",
  ["These values do not fit the typical picture of Borrelia burgdorferi infection",
   "Lyme disease always presents with markedly elevated white blood cell counts",
   "Lyme disease cannot occur without an erythema migrans rash at any point",
   "Lyme disease is transmitted by a tick species found only outside North America",
   "Lyme disease produces morulae visible within circulating white blood cells"],
  "Early localized Lyme disease from Borrelia burgdorferi does not typically cause the cytopenias and transaminitis seen in ehrlichiosis or anaplasmosis; this combination of leukopenia, thrombocytopenia, and elevated liver enzymes without a rash points instead toward a granulocytic or monocytic intracellular tick-borne infection, and coinfection should also be considered given the shared Ixodes vector.",
  difficulty="hard",
  why={"Lyme disease always presents with markedly elevated": "Lyme disease does not classically produce a marked leukocytosis, so this statement does not describe the actual pattern.",
       "Lyme disease cannot occur without an erythema": "A meaningful minority of Lyme disease cases lack a recognized erythema migrans rash, so its absence does not exclude Lyme disease itself.",
       "Lyme disease is transmitted by a tick species found": "Lyme disease in the United States is transmitted by Ixodes species found domestically, not exclusively abroad.",
       "Lyme disease produces morulae visible within": "Morulae within leukocytes are a feature of ehrlichiosis and anaplasmosis, not of Borrelia burgdorferi infection."}),

Q(TAG_MOB, "HACEK group: fastidious growth requirements",
  "Blood cultures from a patient with subacute native-valve endocarditis remain negative on the automated system at five days. The laboratory is asked to hold the bottles longer and incubate under increased carbon dioxide. Which organism group does this extended protocol target?",
  ["Slow-growing, capnophilic Gram-negative organisms of the oral flora",
   "Rapidly dividing Gram-positive cocci that clump under the microscope",
   "Obligate intracellular bacteria that cannot grow on artificial media",
   "Spore-forming anaerobes that require strictly oxygen-free conditions",
   "Cell-wall-deficient organisms that need cholesterol-enriched broth"],
  "The HACEK organisms (Haemophilus, Aggregatibacter, Cardiobacterium, Eikenella, Kingella) are fastidious, slow-growing, carbon-dioxide-loving Gram-negative oral commensals that were once the classic explanation for 'culture-negative' endocarditis before labs began routinely extending incubation and adding CO2.",
  difficulty="medium",
  why={"Rapidly dividing Gram-positive cocci": "That describes staphylococci or streptococci, which usually flag positive well within five days.",
       "Obligate intracellular bacteria that cannot grow": "Chlamydia and Rickettsia need cell culture or serology, not extended blood-culture incubation.",
       "Spore-forming anaerobes that require strictly": "Clostridium species are not the target of this particular incubation change.",
       "Cell-wall-deficient organisms that need cholesterol": "That describes Mycoplasma, which requires specialized broth, not simply longer incubation with CO2."}),

Q(TAG_MOB, "Mycoplasma pneumoniae: setting and age of outbreaks",
  "A cluster of mild pneumonia cases with persistent dry cough occurs among college students sharing a dormitory over several weeks. Symptoms in each case start gradually and spread slowly among close contacts. What feature of this organism best explains the slow, close-contact pattern of spread?",
  ["A long incubation period combined with inefficient, low-titer respiratory shedding",
   "A short incubation period with a single point-source contaminated food item",
   "An arthropod vector that requires an outdoor exposure to a specific habitat",
   "A high level of environmental resistance allowing spread through fomites alone",
   "A high aerosol infectivity requiring only brief passage through a shared hallway"],
  "Mycoplasma pneumoniae has a relatively long incubation period (roughly two to three weeks) and spreads inefficiently, requiring prolonged close contact rather than brief exposure, which is why outbreaks smolder slowly through households, military barracks, and college dormitories rather than exploding all at once.",
  difficulty="medium",
  why={"A short incubation period with a single point-source": "A single contaminated food source describes a norovirus or Salmonella outbreak pattern, not this gradual spread.",
       "An arthropod vector that requires an outdoor": "Mycoplasma pneumoniae spreads by respiratory droplets, not through an arthropod vector.",
       "A high level of environmental resistance allowing": "Mycoplasma lacks a cell wall and survives poorly outside a host, so fomite spread is not the mechanism.",
       "A high aerosol infectivity requiring only brief": "The opposite is true here; spread requires prolonged close contact, not brief passing exposure."}),

Q(TAG_MOB, "Ureaplasma: intrauterine infection and preterm labor",
  "Ureaplasma species are recovered from the amniotic fluid of a woman in preterm labor at 26 weeks with intact membranes and no fever. What is this organism's proposed role in this scenario?",
  ["Subclinical infection that provokes cytokine release and triggers early delivery",
   "Direct invasion of the fetal bloodstream causing fetal sepsis and demise",
   "Vertical transmission that produces a fetal skin rash and hepatosplenomegaly",
   "Ascending infection that is always accompanied by maternal fever and chills",
   "Colonization of amniotic fluid with no association with pregnancy outcome"],
  "Ureaplasma species can ascend into the amniotic cavity and cause subclinical chorioamnionitis, often without overt maternal fever, and the resulting inflammatory cytokine response is implicated as a trigger for preterm labor and, in the neonate, chronic lung disease.",
  difficulty="hard",
  why={"Direct invasion of the fetal bloodstream causing": "Fetal sepsis and demise are not the typical proposed mechanism; the effect is mediated through inflammation rather than fulminant fetal bacteremia.",
       "Vertical transmission that produces a fetal skin": "A rash with hepatosplenomegaly suggests congenital infections like syphilis or CMV, not Ureaplasma.",
       "Ascending infection that is always accompanied by": "Ureaplasma chorioamnionitis is often subclinical and can occur without maternal fever, unlike this option implies.",
       "Colonization of amniotic fluid with no association": "This contradicts the recognized link between Ureaplasma and preterm labor."}),
]
