"""Spirochetes (Borrelia, Leptospira, Treponema) and mycobacteria (TB, NTM, M. leprae)
in further depth, covering angles not used in n12_myco_spiro.py."""
from qcore import Q
from tables import *
TAG_SPIRO = "Spirochetes"
TAG_MYCO = "Mycobacteria"
TAG_ABX = "Antibacterial Drugs"

QUESTIONS = [
# ================= Borrelia (Lyme & relapsing fever) — 13 =================
Q(TAG_SPIRO, "Lyme disease: vector and life cycle",
  "A family physician wants to explain why Lyme disease is most often reported in early summer. Which statement about the vector best accounts for this pattern?",
  ["Nymphal ticks feed most heavily in late spring and summer",
   "Adult female ticks feed only during the autumn breeding season",
   "Larval ticks acquire and immediately transmit infection in spring",
   "Infected mosquitoes peak in abundance during the warmest months",
   "Reservoir deer shed the spirochete into pastures each summer"],
  "Ixodes nymphs, which are tiny and easily missed, feed heavily from late spring through summer and account for most human transmission because their small size lets them stay attached long enough to transmit Borrelia (which usually takes over 36 hours). Larvae acquire infection from the white-footed mouse reservoir but rarely transmit it themselves, since they feed once before molting.",
  difficulty="medium",
  why={"Adult female ticks feed only during the autumn": "Adults feed mainly in fall and spring and cause fewer cases than nymphs.",
       "Larval ticks acquire and immediately transmit": "Larvae acquire infection but generally transmit it after molting to the nymph stage, not immediately.",
       "Infected mosquitoes peak in abundance": "Lyme disease is not transmitted by mosquitoes.",
       "Reservoir deer shed the spirochete into pastures": "Deer support the adult tick stage but are not the reservoir for the spirochete itself."},
  table=TICKBORNE),

Q(TAG_SPIRO, "Lyme disease: attachment time and prophylaxis",
  "A hiker finds an engorged Ixodes tick that was attached for an estimated 60 hours, removed within 72 hours of the bite, in an area where local tick infection rates exceed 20%. Which management best fits current guidance?",
  ["A single dose of doxycycline given promptly",
   "A full 21-day course of amoxicillin started now",
   "Serologic testing today with treatment only if positive",
   "No intervention unless erythema migrans later appears",
   "Immediate intravenous ceftriaxone for possible carditis"],
  "A single 200 mg dose of doxycycline can be offered after an Ixodes bite when the tick was attached at least 36 hours, prophylaxis can start within 72 hours of removal, and local infection rates are high. Otherwise, watchful waiting for erythema migrans is preferred over testing or a full antibiotic course, since serology is insensitive early and most bites do not transmit infection.",
  difficulty="hard",
  why={"A full 21-day course of amoxicillin started now": "A full treatment course is reserved for documented infection, not prophylaxis after a bite.",
       "Serologic testing today with treatment only if positive": "Antibody has not yet developed this soon after exposure, so early serology is not useful.",
       "No intervention unless erythema migrans later appears": "This ignores criteria that support single-dose prophylaxis when attachment time and local rates are high enough.",
       "Immediate intravenous ceftriaxone for possible carditis": "There are no signs of disseminated disease, so IV therapy is unwarranted at this stage."}),

Q(TAG_SPIRO, "Lyme disease: multiple erythema migrans",
  "Three weeks after a tick bite on the thigh, a patient develops the expected local annular rash plus several smaller similar lesions scattered on the trunk and arms, along with fatigue and arthralgias. What does the appearance of the distant lesions indicate?",
  ["Hematogenous spread of spirochetes to other areas of skin",
   "A separate tick bite occurring at each new lesion site",
   "An IgE-mediated drug reaction to recent doxycycline",
   "Autoinoculation from scratching the original lesion",
   "An id reaction triggered by a concurrent fungal skin infection"],
  "Secondary or multiple erythema migrans lesions arise when Borrelia disseminates through the bloodstream from the primary bite site to distant skin, marking early disseminated disease rather than several separate exposures. Associated fatigue, arthralgia, and headache commonly accompany the rash at this stage.",
  difficulty="medium",
  why={"A separate tick bite occurring at each new lesion": "Multiple simultaneous new bites at scattered sites in this pattern is far less likely than hematogenous spread.",
       "An IgE-mediated drug reaction to recent doxycycline": "There is no mention of drug exposure preceding the rash, and the lesions match secondary Lyme lesions.",
       "Autoinoculation from scratching the original lesion": "Scratching would not reproduce annular lesions at distant untouched sites.",
       "An id reaction triggered by a concurrent fungal skin infection": "Nothing suggests a fungal infection is present to trigger such a reaction."}),

Q(TAG_SPIRO, "Lyme disease: facial nerve palsy",
  "A child from a Lyme-endemic area develops unilateral facial droop with inability to close one eye, three weeks after a summer spent outdoors, without other neurologic deficits. Which statement about this presentation is correct?",
  ["It usually resolves and does not need intravenous therapy alone",
   "It signals permanent nerve damage requiring surgical decompression",
   "It is a contraindication to any doxycycline-containing regimen",
   "It only ever occurs together with meningitis in the same patient",
   "It indicates concurrent babesiosis until proven otherwise"],
  "Isolated facial (seventh cranial nerve) palsy from early disseminated Lyme disease, especially in children, is generally treated with oral doxycycline or amoxicillin and resolves without permanent deficit; intravenous ceftriaxone is reserved for meningitis or other CNS involvement. It can occur alone, without concurrent meningitis.",
  why={"It signals permanent nerve damage requiring surgical": "Surgery has no role, and most cases recover fully with oral therapy.",
       "It is a contraindication to any doxycycline-containing": "Doxycycline is avoided mainly in young children with dental concerns, and even then alternatives exist, but it is not because of the palsy.",
       "It only ever occurs together with meningitis": "Facial palsy commonly occurs as an isolated finding without meningitis.",
       "It indicates concurrent babesiosis until proven otherwise": "Babesiosis is a separate coinfection risk from Ixodes bites but is not implied by facial palsy specifically."},
  table=LYME_STAGES),

Q(TAG_SPIRO, "Lyme arthritis: chronic knee involvement",
  "A patient with untreated Lyme disease from months earlier now has recurrent large-joint swelling, most often of one knee, with modest pain relative to the degree of swelling. Synovial fluid shows an inflammatory neutrophilic effusion but no organisms on Gram stain. Which test best confirms the diagnosis at this stage?",
  ["Serum IgG antibody testing against Borrelia antigens",
   "Synovial fluid Gram stain repeated after enrichment culture",
   "Blood smear examination for intraerythrocytic organisms",
   "Synovial biopsy for acid-fast bacilli and granulomas",
   "Peripheral blood culture incubated for six weeks"],
  "By the late arthritic stage, Borrelia is rarely recoverable from joint fluid by culture or stain, so diagnosis relies on IgG serology, which is reliably positive at this point (unlike early disease, when antibody may still be negative). PCR of synovial fluid is an alternative in some cases, but routine culture and stain are not useful.",
  difficulty="hard",
  why={"Synovial fluid Gram stain repeated after enrichment culture": "Borrelia is difficult to culture and is essentially never recovered from joint fluid.",
       "Blood smear examination for intraerythrocytic organisms": "That approach detects Babesia, not Borrelia, which does not live inside red cells.",
       "Synovial biopsy for acid-fast bacilli and granulomas": "Lyme arthritis does not show acid-fast organisms or caseating granulomas.",
       "Peripheral blood culture incubated for six weeks": "By the arthritic stage the organism is not circulating in blood in detectable numbers."},
  table=LYME_STAGES),

Q(TAG_SPIRO, "Lyme disease: post-treatment syndrome",
  "A patient completed an appropriate course of doxycycline for confirmed early Lyme disease six months ago and now reports persistent fatigue, diffuse myalgias, and difficulty concentrating, with a normal physical examination and no rash. What is the most appropriate next management step?",
  ["Supportive care, since prolonged antibiotics show no added benefit",
   "A second full course of intravenous ceftriaxone for six weeks",
   "Repeat treatment with oral doxycycline for a further two months",
   "Lifelong suppressive antibiotic therapy to prevent relapse",
   "Combination therapy with doxycycline plus intramuscular penicillin"],
  "Post-treatment Lyme disease syndrome describes lingering nonspecific symptoms after guideline-appropriate therapy; randomized trials show no benefit and added harm from prolonged or repeated antibiotic courses, so management is supportive and directed at symptoms rather than further antimicrobials.",
  difficulty="medium",
  why={"A second full course of intravenous ceftriaxone": "Repeat IV therapy has not shown benefit in trials and carries line-related risk.",
       "Repeat treatment with oral doxycycline for a further": "Extending oral therapy further has not been shown to help this syndrome.",
       "Lifelong suppressive antibiotic therapy to prevent relapse": "There is no evidence of ongoing infection to justify indefinite antibiotics.",
       "Combination therapy with doxycycline plus intramuscular": "There is no rationale for combining agents when the infection has already been treated."}),

Q(TAG_SPIRO, "Lyme disease: pregnancy considerations",
  "A pregnant woman at 20 weeks gestation develops a single annular expanding rash with central clearing after removing an engorged tick from her leg a week earlier. Which treatment is most appropriate?",
  ["Amoxicillin for the duration recommended in nonpregnant adults",
   "Doxycycline for the duration recommended in nonpregnant adults",
   "No antibiotic treatment until after delivery to avoid fetal risk",
   "Single-dose azithromycin, since it is safest throughout pregnancy",
   "Intravenous ceftriaxone regardless of the stage of disease"],
  "Early Lyme disease in pregnancy is treated the same as in nonpregnant adults, but with amoxicillin (or cefuroxime) rather than doxycycline, which is generally avoided due to effects on fetal bone and teeth. Untreated maternal Lyme disease is a preventable exposure, so treatment should not be withheld.",
  difficulty="medium",
  why={"Doxycycline for the duration recommended in nonpregnant": "Doxycycline is avoided in pregnancy because of fetal skeletal and dental effects.",
       "No antibiotic treatment until after delivery": "Delaying treatment is not recommended when an effective and safe alternative exists.",
       "Single-dose azithromycin, since it is safest throughout": "Azithromycin is a second-line option only when first-line drugs cannot be used, and single-dose regimens are not standard for erythema migrans.",
       "Intravenous ceftriaxone regardless of the stage of disease": "IV therapy is reserved for disseminated disease such as meningitis or carditis, not localized early infection."},
  table=LYME_STAGES),

Q(TAG_SPIRO, "Borrelia: outer surface protein vaccine strategy",
  "An investigational Lyme vaccine targets outer surface protein A (OspA) and is designed to work primarily while the spirochete is still within the tick rather than after it has entered the human host. What is the rationale for this strategy?",
  ["Antibody ingested with the blood meal kills the organism in the tick gut",
   "OspA is expressed only after the spirochete enters human skin",
   "The vaccine prevents attachment of the tick to human skin",
   "OspA antibodies cross the placenta to protect the fetus directly",
   "The vaccine sterilizes the local mouse reservoir population"],
  "Borrelia expresses OspA while resident in the tick midgut, then downregulates it and upregulates OspC upon feeding as it moves to the salivary glands and mammalian host. A vaccine targeting OspA works by having host antibody, ingested by the tick during its blood meal, neutralize the organism before it can complete this transition and infect the host.",
  difficulty="hard",
  why={"OspA is expressed only after the spirochete enters human skin": "OspA expression is actually downregulated after the tick begins feeding, the reverse of this statement.",
       "The vaccine prevents attachment of the tick to human skin": "The vaccine does not affect tick attachment; it acts on the spirochete itself.",
       "OspA antibodies cross the placenta to protect the fetus directly": "This is not the mechanism being described and is not the basis for the vaccine's design.",
       "The vaccine sterilizes the local mouse reservoir population": "The vaccine is designed for human protection, not reservoir control."}),

Q(TAG_SPIRO, "Relapsing fever: louse-borne vs tick-borne epidemiology",
  "Two outbreaks of relapsing fever are compared: one occurs among refugees in crowded, unhygienic conditions, and the other occurs in scattered campers in rural cabins. Which distinction correctly separates them?",
  ["Louse-borne disease is epidemic while tick-borne disease is endemic and sporadic",
   "Louse-borne disease is caused by a spirochete different from Borrelia",
   "Tick-borne disease requires no arthropod and is spread by direct contact",
   "Louse-borne disease has more relapses per patient than tick-borne disease",
   "Tick-borne disease occurs only in immunocompromised hosts"],
  "Louse-borne relapsing fever (Borrelia recurrentis) is transmitted among humans by the human body louse and causes explosive epidemics in crowded settings with poor hygiene, such as refugee camps or war. Tick-borne relapsing fever, caused by other Borrelia species, is maintained in a rodent-tick cycle and produces sporadic endemic cases, generally with more relapse episodes than the louse-borne form.",
  difficulty="medium",
  why={"Louse-borne disease is caused by a spirochete different from Borrelia": "Both forms are caused by Borrelia species; they differ in vector and species, not genus.",
       "Tick-borne disease requires no arthropod and is spread by direct contact": "Tick-borne disease still requires a soft tick (Ornithodoros) vector.",
       "Louse-borne disease has more relapses per patient than tick-borne disease": "Tick-borne disease typically causes more relapse episodes than louse-borne disease.",
       "Tick-borne disease occurs only in immunocompromised hosts": "Tick-borne relapsing fever affects immunocompetent people exposed to the rodent-tick cycle."},
  table=TICKBORNE),

Q(TAG_SPIRO, "Borrelia: dark-field blood smear during fever",
  "A patient with suspected relapsing fever has a temperature of 40°C and is having chills. A thin blood smear is examined under dark-field or Giemsa-stained light microscopy. What is the expected finding, and when should the sample ideally be drawn?",
  ["Visible spirochetes in blood, best drawn at the height of an attack",
   "Visible spirochetes in blood, best seen during the afebrile interval",
   "Intraerythrocytic ring forms, best seen at any time of day",
   "Intracytoplasmic morulae in monocytes, drawn during fever",
   "No organisms are ever visible on peripheral smear in this disease"],
  "Unlike most other spirochetes, Borrelia species causing relapsing fever circulate in high enough numbers during febrile episodes to be directly visualized on a peripheral blood smear, which is the classic bedside diagnostic method; smears are far less sensitive during afebrile intervals when spirochetemia clears.",
  difficulty="easy",
  why={"Visible spirochetes in blood, best seen during the afebrile interval": "Spirochete numbers actually fall during the afebrile interval, making smears less sensitive then.",
       "Intraerythrocytic ring forms, best seen at any time of day": "Ring forms inside red cells describe Plasmodium or Babesia, not Borrelia.",
       "Intracytoplasmic morulae in monocytes, drawn during fever": "Morulae in monocytes describe Ehrlichia, a different organism entirely.",
       "No organisms are ever visible on peripheral smear in this disease": "Relapsing fever is notable precisely because organisms are visible on smear, unlike Lyme disease."}),

Q(TAG_SPIRO, "Lyme disease: co-infection recognition",
  "A patient treated with doxycycline for erythema migrans continues to have high fevers and worsening fatigue after five days, and a peripheral smear shows intraerythrocytic ring and tetrad forms. Which additional pathogen transmitted by the same tick explains this?",
  ["Babesia microti",
   "Rickettsia rickettsii",
   "Ehrlichia chaffeensis",
   "Anaplasma phagocytophilum",
   "Coxiella burnetii"],
  "Ixodes scapularis transmits Borrelia burgdorferi, Babesia microti, and Anaplasma phagocytophilum, so patients can be co-infected. Persistent fever despite doxycycline (which does not reliably treat Babesia) with red cell ring forms and tetrads ('Maltese cross') points to babesiosis, which needs atovaquone-azithromycin or quinine-clindamycin.",
  difficulty="medium",
  why={"Rickettsia rickettsii": "Rocky Mountain spotted fever is transmitted by Dermacentor ticks, not Ixodes, and does not produce red cell ring forms.",
       "Ehrlichia chaffeensis": "Ehrlichia is spread by Amblyomma and infects monocytes rather than red cells, and it would respond to doxycycline.",
       "Anaplasma phagocytophilum": "Anaplasma does share the Ixodes vector but infects granulocytes with morulae, not red cells, and responds to doxycycline.",
       "Coxiella burnetii": "Q fever is acquired by inhalation from livestock, not a tick bite, and does not cause ring forms in red cells."},
  table=TICKBORNE),

Q(TAG_SPIRO, "Borrelia: cell wall structure and Gram stain",
  "Why is Borrelia burgdorferi difficult to visualize on a standard Gram stain of a skin biopsy from erythema migrans?",
  ["It is thin and best visualized with silver stains such as Warthin-Starry",
   "It lacks a cell wall entirely and cannot take up any stain",
   "It is an obligate intracellular organism confined to the cytoplasm",
   "It forms a thick capsule that excludes crystal violet dye",
   "It only stains with acid-fast methods used for mycobacteria"],
  "Like other spirochetes, Borrelia is a thin, tightly coiled Gram-negative organism that is difficult to see with standard Gram or routine H&E staining; it is far better demonstrated with silver impregnation stains such as Warthin-Starry, or by immunohistochemistry and PCR, rather than by culture from skin, which is insensitive.",
  difficulty="medium",
  why={"It lacks a cell wall entirely and cannot take up any stain": "Borrelia does have a true Gram-negative-type cell wall, unlike Mycoplasma, which truly lacks one.",
       "It is an obligate intracellular organism confined to the cytoplasm": "Borrelia is extracellular, unlike Rickettsia or Chlamydia.",
       "It forms a thick capsule that excludes crystal violet dye": "Borrelia is not notably encapsulated; its thinness, not a capsule, limits visibility.",
       "It only stains with acid-fast methods used for mycobacteria": "Acid-fast staining is used for mycobacteria and Nocardia, not spirochetes."},
  table=STAINS),

Q(TAG_SPIRO, "Lyme disease: antigenic variation of VlsE",
  "Chronic untreated Lyme disease can persist for months despite an active antibody response. Which Borrelia surface protein undergoes gene conversion that contributes to this immune evasion, and is also exploited as a sensitive serologic target?",
  ["VlsE, which continuously varies its exposed epitopes",
   "OspC, which is expressed identically throughout infection",
   "Flagellin, which is invariant across all Borrelia strains",
   "P66, which is shed extracellularly and neutralized rapidly",
   "DbpA, which binds decorin without any antigenic change"],
  "VlsE undergoes extensive segmental gene conversion at its central variable region, generating antigenic variants that let Borrelia partially evade a developing antibody response and contribute to persistence; despite this variation, a conserved invariable region (IR6/C6) of VlsE is used as a sensitive and specific antigen in modern Lyme serologic assays.",
  difficulty="hard",
  why={"OspC, which is expressed identically throughout infection": "OspC expression itself changes with the stage of infection and is not invariant.",
       "Flagellin, which is invariant across all Borrelia strains": "Flagellin is a conserved antigen used in some assays but does not undergo the variation described here.",
       "P66, which is shed extracellularly and neutralized rapidly": "P66 is a porin/adhesin and is not the classic example of this gene-conversion-driven variation.",
       "DbpA, which binds decorin without any antigenic change": "Decorin-binding protein A is an adhesin, not the antigen known for this variation mechanism."}),

# ================= Leptospira interrogans — 17 =================
Q(TAG_SPIRO, "Leptospira: darkfield morphology",
  "A reference laboratory examines an isolate by dark-field microscopy and describes a thin, tightly coiled organism with hooked ends. Which organism does this description match?",
  ["Leptospira interrogans",
   "Borrelia burgdorferi",
   "Treponema pallidum",
   "Campylobacter jejuni",
   "Legionella pneumophila"],
  "Leptospira is a thin spirochete distinguished from other spirochetes by its characteristic hooked ends, best appreciated on dark-field microscopy since it does not take up Gram stain well. It cannot be cultured on routine media and requires specialized semisolid media with long incubation.",
  difficulty="easy",
  why={"Borrelia burgdorferi": "Borrelia is a looser, larger coil without the characteristic hooked ends.",
       "Treponema pallidum": "Treponema has tight regular coils but lacks the hooked-end appearance.",
       "Campylobacter jejuni": "Campylobacter is a curved or comma-shaped Gram-negative rod, not a spirochete.",
       "Legionella pneumophila": "Legionella is a faintly staining Gram-negative rod, not a spirochete."},
  table=STAINS),

Q(TAG_SPIRO, "Leptospira: occupational exposure",
  "A sewer worker develops fever, severe calf pain, and conjunctival suffusion after wading through flooded tunnels. Which occupational group shares this same elevated risk?",
  ["Rice paddy farmers who wade barefoot through standing water",
   "Poultry processing plant workers handling raw chicken carcasses",
   "Underground coal miners exposed to rock dust",
   "Greenhouse workers exposed to Sporothrix-laden soil",
   "Textile workers exposed to contaminated wool and hides"],
  "Leptospirosis is an occupational hazard wherever people wade through water or soil contaminated with animal urine, including sewer workers, rice paddy farmers, veterinarians, and abattoir workers, all of whom have prolonged skin contact with rodent- or livestock-contaminated water.",
  difficulty="easy",
  why={"Poultry processing plant workers handling raw chicken carcasses": "This exposure is more associated with Campylobacter and Salmonella than Leptospira.",
       "Underground coal miners exposed to rock dust": "Rock dust exposure causes pneumoconiosis, not leptospirosis, unless mines are also flooded with contaminated water.",
       "Greenhouse workers exposed to Sporothrix-laden soil": "That exposure causes sporotrichosis, a fungal infection from thorn injuries.",
       "Textile workers exposed to contaminated wool and hides": "Wool and hide exposure is classically linked to inhalational anthrax."},
  table=ZOONOSES),

Q(TAG_SPIRO, "Leptospirosis: anicteric vs icteric phases",
  "A patient with leptospirosis has a biphasic illness: an initial week of fever, headache, and myalgia followed by a brief improvement, then recurrence of fever with meningismus. Which term describes this second phase in most patients?",
  ["The immune phase, marked by antibody-mediated organ involvement",
   "The leptospiremic phase, when organisms are cultured from blood",
   "The incubation phase, before any antibody has yet formed",
   "The convalescent phase, when all symptoms have fully resolved",
   "The carrier phase, when the organism localizes only to kidneys"],
  "Leptospirosis classically has a biphasic course: an early leptospiremic (septicemic) phase with organisms recoverable from blood, followed by a brief afebrile interval, then an immune phase driven by antibody formation, during which organisms clear from blood but may be found in urine, and aseptic meningitis or the more severe Weil syndrome can appear.",
  difficulty="medium",
  why={"The leptospiremic phase, when organisms are cultured from blood": "Blood cultures are positive in the first phase; by the second phase the organism has largely cleared from blood.",
       "The incubation phase, before any antibody has yet formed": "Incubation occurs before any symptoms begin, not between the two febrile phases.",
       "The convalescent phase, when all symptoms have fully resolved": "This phase is described by new symptoms, not resolution.",
       "The carrier phase, when the organism localizes only to kidneys": "Renal localization with urinary shedding can occur but does not exclude systemic immune-phase manifestations like meningitis."}),

Q(TAG_SPIRO, "Weil disease: bleeding diathesis",
  "A patient with severe leptospirosis develops jaundice, acute kidney injury, and diffuse petechiae with a falling platelet count and prolonged bleeding time. Which mechanism best explains the hemorrhagic tendency?",
  ["Direct endothelial and capillary injury by the organism",
   "Vitamin K malabsorption from cholestatic liver injury alone",
   "An autoimmune platelet destruction triggered by molecular mimicry",
   "Disseminated intravascular coagulation from a separate viral coinfection",
   "Warfarin-like inhibition of hepatic clotting factor synthesis"],
  "In Weil disease, Leptospira directly damages vascular endothelium and capillaries, producing widespread microvascular injury, thrombocytopenia, and a bleeding tendency (pulmonary hemorrhage is a leading cause of death) that is out of proportion to the degree of hepatic synthetic dysfunction seen with the jaundice.",
  difficulty="hard",
  why={"Vitamin K malabsorption from cholestatic liver injury alone": "While hepatic dysfunction contributes, it does not fully account for the vascular and platelet findings described.",
       "An autoimmune platelet destruction triggered by molecular mimicry": "Immune-mediated platelet destruction is not the established mechanism in leptospirosis.",
       "Disseminated intravascular coagulation from a separate viral coinfection": "No coinfection is described, and the bleeding relates directly to the leptospiral infection.",
       "Warfarin-like inhibition of hepatic clotting factor synthesis": "There is no warfarin exposure, and this mechanism is not how leptospirosis causes bleeding."}),

Q(TAG_SPIRO, "Leptospirosis: pulmonary hemorrhage syndrome",
  "In a region with a recent leptospirosis outbreak, several young patients rapidly develop hemoptysis and respiratory failure without the classic jaundice of Weil disease. What does this presentation represent?",
  ["Severe pulmonary hemorrhage syndrome, an anicteric but lethal form",
   "A separate unrelated viral hemorrhagic fever outbreak",
   "Evidence that these patients instead have hantavirus infection",
   "Proof that leptospirosis cannot cause disease without jaundice",
   "An allergic reaction to doxycycline given for prophylaxis"],
  "Severe pulmonary hemorrhage syndrome is an increasingly recognized, often anicteric form of severe leptospirosis, especially in outbreak settings, causing diffuse alveolar hemorrhage and high mortality even without the jaundice and renal failure of classic Weil disease. It underscores that leptospirosis can be severe and fatal without hepatic involvement.",
  difficulty="hard",
  why={"A separate unrelated viral hemorrhagic fever outbreak": "The scenario describes a recognized presentation of leptospirosis itself, not a separate viral illness.",
       "Evidence that these patients instead have hantavirus infection": "Hantavirus causes a different syndrome (pulmonary or renal) and is a distinct pathogen from Leptospira.",
       "Proof that leptospirosis cannot cause disease without jaundice": "This form specifically demonstrates that severe, even fatal, disease can occur without jaundice.",
       "An allergic reaction to doxycycline given for prophylaxis": "There is no mention of a drug reaction, and the presentation is a known leptospiral syndrome."}),

Q(TAG_SPIRO, "Leptospira: renal tubular localization",
  "After the systemic bloodstream phase of infection resolves, an infected animal reservoir continues to shed the organism in urine for extended periods, sometimes for life. Where does the organism persist to make this possible?",
  ["The proximal renal tubules, sheltered from the host immune response",
   "The hepatic bile canaliculi, protected within the biliary tree",
   "The choroid plexus, protected by the blood-brain barrier",
   "The corneal stroma, an immune-privileged avascular site",
   "The seminiferous tubules, protected by the blood-testis barrier"],
  "Leptospira persists and replicates in the proximal renal tubular epithelium of reservoir hosts such as rats, cattle, and dogs, a site relatively protected from the systemic antibody response, allowing chronic urinary shedding that maintains the organism in the environment and drives human exposure.",
  difficulty="medium",
  why={"The hepatic bile canaliculi, protected within the biliary tree": "Hepatic injury occurs during infection but the chronic reservoir site of shedding is renal, not biliary.",
       "The choroid plexus, protected by the blood-brain barrier": "The CNS can be involved in the immune phase, but chronic shedding into urine occurs from the kidney.",
       "The corneal stroma, an immune-privileged avascular site": "Conjunctival suffusion is a clinical sign, but the organism is not chronically harbored in the cornea.",
       "The seminiferous tubules, protected by the blood-testis barrier": "This is not the recognized reservoir site responsible for urinary shedding."},
  table=ZOONOSES),

Q(TAG_SPIRO, "Leptospirosis: diagnostic confirmation",
  "A clinician suspects leptospirosis in a patient with a compatible exposure history and biphasic fever. Local labs cannot perform the microscopic agglutination test. Which alternative is most useful for diagnosis in the first week of illness?",
  ["PCR of blood, which is most sensitive early in the leptospiremic phase",
   "Stool culture on selective enteric media for spirochetes",
   "A single convalescent IgG titer drawn at four weeks only",
   "Skin biopsy with silver stain of an unrelated area",
   "Peripheral blood smear examined under bright-field microscopy alone"],
  "PCR of blood (or urine later in illness) detects Leptospira DNA and is most useful in the first week, before an antibody response has developed and while organisms are still circulating; the microscopic agglutination test, the serologic reference standard, requires paired sera and specialized live-antigen panels. Routine culture is slow and insensitive.",
  difficulty="medium",
  why={"Stool culture on selective enteric media for spirochetes": "Leptospira is not recovered from stool and does not grow on routine enteric media.",
       "A single convalescent IgG titer drawn at four weeks only": "A single late titer does not aid early diagnosis and misses the acute window for treatment decisions.",
       "Skin biopsy with silver stain of an unrelated area": "There is no characteristic skin lesion to biopsy in leptospirosis.",
       "Peripheral blood smear examined under bright-field microscopy alone": "Leptospira is too thin to reliably visualize on routine bright-field smears; dark-field or specific stains are needed, and even then sensitivity is low."}),

Q(TAG_SPIRO, "Leptospira: outer membrane virulence factor",
  "Investigators studying Leptospira virulence find that a surface lipoprotein binds host fibronectin and laminin, promoting adherence to and invasion of endothelial and renal tubular cells. Which category of molecule is this most consistent with?",
  ["An adhesin mediating attachment to host extracellular matrix",
   "A superantigen that nonspecifically activates T lymphocytes",
   "An A-B exotoxin that ADP-ribosylates a host G protein",
   "A pore-forming hemolysin that lyses red blood cells directly",
   "An IgA protease that cleaves mucosal secretory antibody"],
  "Leptospiral surface proteins such as LigA/LigB and Lsa proteins act as adhesins that bind host extracellular matrix components (fibronectin, laminin, and others), mediating attachment and tissue invasion, which is a different virulence strategy from toxin-based mechanisms used by many other bacteria.",
  difficulty="hard",
  why={"A superantigen that nonspecifically activates T lymphocytes": "Superantigens are the mechanism of toxins like TSST-1, not the adhesion process described here.",
       "An A-B exotoxin that ADP-ribosylates a host G protein": "This describes toxins such as cholera or pertussis toxin, a different mechanism than the binding described.",
       "A pore-forming hemolysin that lyses red blood cells directly": "Leptospira does produce hemolysins, but the protein described is an adhesin, not a pore former.",
       "An IgA protease that cleaves mucosal secretory antibody": "IgA protease is a feature of organisms like Neisseria and Haemophilus, not the adhesion mechanism described."}),

Q(TAG_SPIRO, "Leptospirosis: antimicrobial choice by severity",
  "A patient with mild leptospirosis is being managed as an outpatient, while another with jaundice and rising creatinine is hospitalized. Which pairing of treatments is most appropriate?",
  ["Oral doxycycline for the mild case, intravenous penicillin for severe disease",
   "Oral metronidazole for the mild case, oral doxycycline for severe disease",
   "Intramuscular benzathine penicillin for both regardless of severity",
   "Oral fluoroquinolone for the mild case, oral azithromycin for severe disease",
   "No antibiotics for the mild case, only supportive care and dialysis for severe disease"],
  "Mild leptospirosis is treated with oral doxycycline (or amoxicillin), while severe disease, such as Weil syndrome, is treated with intravenous penicillin G or ceftriaxone, plus supportive care that may include dialysis for renal failure. A Jarisch-Herxheimer-like reaction can occur after starting antibiotics.",
  difficulty="medium",
  why={"Oral metronidazole for the mild case, oral doxycycline for severe": "Metronidazole has no activity against Leptospira, and severe disease needs intravenous, not oral, therapy.",
       "Intramuscular benzathine penicillin for both regardless of severity": "Benzathine penicillin gives prolonged low levels appropriate for syphilis, not the regimen used for leptospirosis of any severity.",
       "Oral fluoroquinolone for the mild case, oral azithromycin for severe": "These are not the standard first-line choices, and severe disease requires intravenous therapy.",
       "No antibiotics for the mild case, only supportive care and dialysis": "Antibiotics shorten the course even in mild disease and should not be withheld."}),

Q(TAG_SPIRO, "Leptospirosis: Jarisch-Herxheimer-like reaction",
  "Shortly after starting penicillin for severe leptospirosis, a patient develops transient fever, chills, and worsening hypotension. What does this reaction reflect?",
  ["Release of pathogen antigens as the spirochetes are rapidly killed",
   "An IgE-mediated anaphylactic reaction to the penicillin itself",
   "A new nosocomial bloodstream infection acquired in the hospital",
   "Progression of untreated disease unrelated to antibiotic therapy",
   "Cross-reactivity between penicillin and a leptospiral vaccine antigen"],
  "As with syphilis, rapid antibiotic-induced killing of leptospires can release pyrogenic products and trigger a transient Jarisch-Herxheimer-like reaction with fever, chills, and hypotension shortly after the first dose, which is self-limited and managed supportively rather than by stopping the antibiotic.",
  difficulty="medium",
  why={"An IgE-mediated anaphylactic reaction to the penicillin itself": "Anaphylaxis would typically include urticaria, angioedema, or bronchospasm rather than this classic pattern tied to treatment timing.",
       "A new nosocomial bloodstream infection acquired in the hospital": "The timing immediately after the first antibiotic dose points to a treatment-related reaction, not a new infection.",
       "Progression of untreated disease unrelated to antibiotic therapy": "The reaction is specifically linked temporally to starting antibiotics, arguing against unrelated progression.",
       "Cross-reactivity between penicillin and a leptospiral vaccine antigen": "No vaccine is mentioned, and this is not the mechanism of the reaction."}),

Q(TAG_SPIRO, "Leptospirosis: conjunctival suffusion vs conjunctivitis",
  "On examination, a patient with suspected leptospirosis has diffuse reddening of the conjunctivae without any discharge, itching, or exudate. How does this finding differ from typical infectious conjunctivitis?",
  ["Suffusion produces redness with no discharge, unlike ordinary conjunctivitis",
   "Suffusion is always accompanied by purulent discharge and crusting",
   "Suffusion indicates a herpetic dendritic corneal ulcer is present",
   "Suffusion is limited to one eye, while conjunctivitis is bilateral",
   "Suffusion resolves only with topical antibiotic eye drops"],
  "Conjunctival suffusion, a hallmark clinical clue in leptospirosis, is redness of the conjunctivae without the discharge, exudate, or itching typically seen in bacterial, viral, or allergic conjunctivitis, and it does not respond to topical antibiotics since it reflects vascular congestion rather than local infection.",
  difficulty="easy",
  why={"Suffusion is always accompanied by purulent discharge and crusting": "The defining feature of suffusion is the absence of discharge, the opposite of this statement.",
       "Suffusion indicates a herpetic dendritic corneal ulcer is present": "Suffusion is a conjunctival, not corneal, finding and does not imply herpetic disease.",
       "Suffusion is limited to one eye, while conjunctivitis is bilateral": "Suffusion in leptospirosis is typically bilateral, and laterality is not the distinguishing feature.",
       "Suffusion resolves only with topical antibiotic eye drops": "Topical antibiotics would not address suffusion, since there is no local bacterial infection of the eye."}),

Q(TAG_SPIRO, "Leptospira: serovar diversity and immunity",
  "Leptospira interrogans includes more than 200 antigenically distinct serovars, each associated with a different animal reservoir. What is the clinical implication of this diversity?",
  ["Immunity after infection with one serovar may not protect against another",
   "A single serologic test can detect antibody to all serovars equally well",
   "Only one serovar is capable of causing human disease at all",
   "Vaccination against one serovar eliminates risk from all others for life",
   "Serovar identity determines whether the organism is Gram-positive or negative"],
  "Because immunity to Leptospira is largely serovar-specific, infection or vaccination against one serovar does not reliably protect against others, which complicates both vaccine design (used mainly in animals and at-risk workers) and interpretation of serologic testing, since the microscopic agglutination test uses a locally relevant panel of serovars.",
  difficulty="medium",
  why={"A single serologic test can detect antibody to all serovars equally well": "Serologic testing requires a broad, regionally tailored panel because reactivity is serovar-specific.",
       "Only one serovar is capable of causing human disease at all": "Many different serovars, not just one, are capable of causing human leptospirosis.",
       "Vaccination against one serovar eliminates risk from all others for life": "Protection is serovar-specific and not lifelong or universal across serovars.",
       "Serovar identity determines whether the organism is Gram-positive or negative": "All Leptospira serovars share the same Gram-negative-type spirochete structure; serovar reflects surface antigen differences, not staining class."}),

Q(TAG_SPIRO, "Leptospirosis: differentiating from dengue",
  "A returning traveler from Southeast Asia has fever, myalgia, headache, and a mild bleeding tendency after wading through floodwater during a monsoon. Which additional finding would favor leptospirosis over dengue as the cause?",
  ["Conjunctival suffusion and prominent calf tenderness",
   "A positive tourniquet test with a diffuse petechial rash",
   "Marked leukopenia with a rising hematocrit on serial testing",
   "Retro-orbital pain with a biphasic saddleback fever curve",
   "Onset within days of a mosquito-dense urban environment"],
  "Conjunctival suffusion and severe calf or lumbar myalgia point more toward leptospirosis, which follows exposure to contaminated water rather than a mosquito bite, whereas dengue is suggested by a positive tourniquet test, marked leukopenia with hemoconcentration, retro-orbital pain, and a saddleback fever curve tied to an urban mosquito exposure.",
  difficulty="hard",
  why={"A positive tourniquet test with a diffuse petechial rash": "This finding is characteristic of dengue's capillary fragility, favoring dengue rather than leptospirosis.",
       "Marked leukopenia with a rising hematocrit on serial testing": "Leukopenia with hemoconcentration is typical of dengue, whereas leptospirosis more often shows a neutrophilic leukocytosis.",
       "Retro-orbital pain with a biphasic saddleback fever curve": "This classic dengue pattern would argue for dengue over leptospirosis.",
       "Onset within days of a mosquito-dense urban environment": "A mosquito-associated exposure history points toward dengue rather than the waterborne exposure of leptospirosis."},
  table=ZOONOSES),

Q(TAG_SPIRO, "Leptospira: doxycycline chemoprophylaxis",
  "Before a multi-day adventure race through flooded jungle terrain in an endemic region, participants are offered weekly oral doxycycline. What is the rationale for this practice?",
  ["Prophylactic dosing reduces the incidence of clinical leptospirosis",
   "Doxycycline prevents all tick bites throughout the entire event",
   "Doxycycline sterilizes floodwater sources used for drinking",
   "It eliminates the need for post-exposure wound cleaning",
   "It provides lifelong immunity against all Leptospira serovars"],
  "Weekly oral doxycycline has been shown in studies of high-risk short-term exposures, such as endurance races or military exercises through contaminated water, to reduce the incidence of clinical leptospirosis, functioning as chemoprophylaxis rather than as a vaccine or disinfectant.",
  difficulty="medium",
  why={"Doxycycline prevents all tick bites throughout the entire event": "Leptospirosis is acquired through water and skin contact, not tick bites, so this rationale does not apply.",
       "Doxycycline sterilizes floodwater sources used for drinking": "Oral prophylaxis acts systemically in the host, not on the environmental water source.",
       "It eliminates the need for post-exposure wound cleaning": "Basic wound care and avoiding contaminated water remain recommended alongside chemoprophylaxis.",
       "It provides lifelong immunity against all Leptospira serovars": "Chemoprophylaxis provides temporary risk reduction during exposure, not durable immunity."}),

Q(TAG_SPIRO, "Leptospirosis: aseptic meningitis phase",
  "During the second week of a biphasic febrile illness following freshwater exposure, a patient develops headache and neck stiffness. Cerebrospinal fluid shows a lymphocytic pleocytosis with normal glucose and mildly elevated protein. What does this represent?",
  ["Aseptic meningitis during the immune phase of leptospirosis",
   "Bacterial meningitis requiring empiric vancomycin and ceftriaxone",
   "Fungal meningitis requiring induction amphotericin B therapy",
   "Tuberculous meningitis requiring four-drug antituberculous therapy",
   "A subarachnoid hemorrhage from the associated bleeding diathesis"],
  "During the immune phase of leptospirosis, aseptic meningitis with a lymphocytic, normoglycorrhachic CSF profile is common and generally follows a benign course, distinguishing it from the neutrophilic, hypoglycorrhachic picture of bacterial meningitis or the profile expected in fungal or tuberculous meningitis.",
  difficulty="medium",
  why={"Bacterial meningitis requiring empiric vancomycin and ceftriaxone": "Bacterial meningitis would typically show a neutrophilic pleocytosis with low glucose, not this lymphocytic, normoglycorrhachic pattern.",
       "Fungal meningitis requiring induction amphotericin B therapy": "Fungal meningitis usually develops in an immunocompromised host over a more indolent course and is not suggested by this exposure history.",
       "Tuberculous meningitis requiring four-drug antituberculous therapy": "Tuberculous meningitis typically shows markedly low glucose and a more subacute time course than described here.",
       "A subarachnoid hemorrhage from the associated bleeding diathesis": "The CSF findings described reflect inflammation, not the presence of blood from a hemorrhage."},
  table=ZOONOSES),

Q(TAG_SPIRO, "Leptospira: comparison with Legionella exposure",
  "A patient presents with fever and myalgia after a weekend of freshwater kayaking. A colleague asks how to distinguish possible leptospirosis from Legionnaires disease acquired from a contaminated air conditioning system. Which feature favors leptospirosis?",
  ["Conjunctival suffusion and exposure to natural water rather than aerosols",
   "A urine antigen test positive for a soluble bacterial antigen",
   "Hyponatremia together with relative bradycardia on examination",
   "Gram stain of sputum showing faintly staining, thin rods in clusters",
   "Growth on charcoal yeast extract agar supplemented with cysteine and iron"],
  "Conjunctival suffusion and a water-based rather than aerosol-based exposure history point to leptospirosis. Legionella, in contrast, is acquired by inhaling aerosolized water from air conditioning systems or showers, is detected by a urinary antigen test, and grows only on charcoal yeast extract agar with iron and cysteine.",
  difficulty="medium",
  why={"A urine antigen test positive for a soluble bacterial antigen": "This test is used to diagnose Legionella, not Leptospira, so a positive result would favor Legionella instead.",
       "Hyponatremia together with relative bradycardia on examination": "Hyponatremia and relative bradycardia are classically associated with Legionella infection.",
       "Gram stain of sputum showing faintly staining, thin rods in clusters": "This description fits Legionella, which stains poorly with Gram stain, rather than the spirochete morphology of Leptospira.",
       "Growth on charcoal yeast extract agar supplemented with cysteine and iron": "This is the specific culture requirement for Legionella, not Leptospira, which needs its own specialized semisolid media."},
  table=ZOONOSES),

Q(TAG_SPIRO, "Leptospirosis: renal injury mechanism",
  "In a patient with acute kidney injury from leptospirosis, urinalysis shows mild proteinuria, pyuria, and granular casts, and the injury improves substantially with supportive care and antibiotics. What best characterizes the underlying renal lesion?",
  ["Reversible interstitial nephritis with tubular dysfunction",
   "Rapidly progressive glomerulonephritis with crescent formation",
   "Diffuse renal cortical necrosis with permanent nephron loss",
   "Papillary necrosis from long-standing analgesic overuse",
   "Renal artery thrombosis causing widespread cortical infarction"],
  "Leptospirosis-associated kidney injury results mainly from interstitial nephritis and tubular injury caused by direct bacterial invasion and toxin-mediated damage, which is typically reversible with supportive care (including dialysis when needed) and antimicrobial therapy, unlike glomerulonephritis or cortical necrosis, which more often leave lasting damage.",
  difficulty="hard",
  why={"Rapidly progressive glomerulonephritis with crescent formation": "Crescentic glomerulonephritis is not the typical renal lesion in leptospirosis and implies a different, often more destructive process.",
       "Diffuse renal cortical necrosis with permanent nephron loss": "Cortical necrosis causes permanent damage, whereas leptospiral nephropathy is usually reversible.",
       "Papillary necrosis from long-standing analgesic overuse": "There is no analgesic exposure described, and this is a distinct, unrelated cause of renal injury.",
       "Renal artery thrombosis causing widespread cortical infarction": "This describes a vascular occlusive process, not the interstitial and tubular injury seen in leptospirosis."}),

# ================= Treponema pallidum (syphilis) — 7 =================
Q(TAG_SPIRO, "Syphilis: secondary rash distribution",
  "A patient several weeks after an unnoticed genital sore develops a diffuse maculopapular rash that notably involves the palms and soles, along with generalized lymphadenopathy. Which additional finding would be most consistent with this stage?",
  ["Flat, broad, wart-like lesions in moist intertriginous areas",
   "A single indurated, painless ulcer with a clean base",
   "Destructive, rubbery necrotic lesions of the palate",
   "Chronic ataxia with loss of proprioception and vibration sense",
   "Argyll Robertson pupils that fail to react to light"],
  "Secondary syphilis, occurring weeks after the primary chancre heals, produces a widespread rash involving palms and soles, generalized lymphadenopathy, and condylomata lata, which are flat, moist, wart-like plaques teeming with spirochetes in intertriginous areas, distinct from the ulcerative chancre of primary disease or the destructive gummas and neurologic findings of tertiary disease.",
  difficulty="easy",
  why={"A single indurated, painless ulcer with a clean base": "This describes the primary chancre, an earlier stage than the one described here.",
       "Destructive, rubbery necrotic lesions of the palate": "Gummas are a tertiary-stage finding, occurring years after untreated infection.",
       "Chronic ataxia with loss of proprioception and vibration sense": "Tabes dorsalis is a late tertiary neurologic manifestation, not part of secondary disease.",
       "Argyll Robertson pupils that fail to react to light": "This pupillary finding is characteristic of neurosyphilis, a late complication, not secondary disease."},
  table=SYPHILIS_STAGES),

Q(TAG_SPIRO, "Neurosyphilis: general paresis",
  "A patient with untreated syphilis from many years earlier develops progressive personality change, memory loss, and delusions of grandeur, with cerebrospinal fluid showing a lymphocytic pleocytosis and elevated protein. Which tertiary manifestation does this represent?",
  ["General paresis from chronic parenchymal brain infection",
   "Meningovascular syphilis presenting as an acute embolic stroke",
   "Tabes dorsalis from posterior column and dorsal root involvement",
   "A gumma compressing the pituitary stalk directly",
   "Otosyphilis causing sudden bilateral sensorineural hearing loss"],
  "General paresis (dementia paralytica) is a late parenchymatous form of neurosyphilis resulting from chronic invasion of the brain parenchyma, producing progressive cognitive decline and personality change, sometimes with grandiose delusions, distinct from tabes dorsalis (posterior column and dorsal root degeneration causing sensory ataxia) and meningovascular disease (which causes stroke-like presentations from vasculitis).",
  difficulty="hard",
  why={"Meningovascular syphilis presenting as an acute embolic stroke": "That form results from vasculitis-related infarction with a more abrupt focal neurologic deficit, not chronic personality change.",
       "Tabes dorsalis from posterior column and dorsal root involvement": "Tabes dorsalis produces sensory ataxia and lightning pains rather than the dementia and personality change described here.",
       "A gumma compressing the pituitary stalk directly": "A pituitary gumma would cause localized endocrine or visual symptoms rather than progressive global dementia.",
       "Otosyphilis causing sudden bilateral sensorineural hearing loss": "This describes an auditory complication, not the cognitive and personality syndrome described."},
  table=SYPHILIS_STAGES),

Q(TAG_SPIRO, "Syphilis: congenital late stigmata",
  "An 8-year-old born to a mother with untreated syphilis during pregnancy is now found to have notched, peg-shaped upper incisors, a saddle-shaped nose deformity, and bilateral interstitial keratitis. What do these findings represent?",
  ["Late stigmata of congenital syphilis appearing after infancy",
   "Findings of early congenital syphilis present at birth",
   "An unrelated genetic syndrome affecting facial bone development",
   "Sequelae of untreated rubella infection during gestation",
   "A vitamin D deficiency disorder from dietary insufficiency"],
  "Late congenital syphilis stigmata, appearing after age 2, include Hutchinson teeth (notched, peg-shaped incisors), saddle nose, saber shins, and interstitial keratitis, reflecting scarring from earlier untreated infection, in contrast to early congenital syphilis, which presents in infancy with findings like snuffles, hepatosplenomegaly, and a desquamating rash.",
  difficulty="medium",
  why={"Findings of early congenital syphilis present at birth": "Early congenital syphilis manifests in infancy with different findings such as rhinitis and rash, not these structural stigmata that appear later.",
       "An unrelated genetic syndrome affecting facial bone development": "The clinical triad described is classically linked to congenital syphilis, not an unrelated genetic disorder.",
       "Sequelae of untreated rubella infection during gestation": "Congenital rubella causes a different pattern, including cardiac defects, cataracts, and deafness, not these specific stigmata.",
       "A vitamin D deficiency disorder from dietary insufficiency": "Rickets from vitamin D deficiency causes bone deformities but not the dental and keratitis findings described."},
  table=SYPHILIS_STAGES),

Q(TAG_SPIRO, "Syphilis: penicillin mechanism in a spirochete",
  "Benzathine penicillin G remains first-line therapy for syphilis at every stage. Why does Treponema pallidum remain reliably susceptible to penicillin, unlike many other bacteria that have developed resistance?",
  ["The organism has never acquired a way to evade the drug's action",
   "The organism produces its own penicillin-degrading enzyme at low levels only",
   "Its outer membrane pumps penicillin out before it can act",
   "It alters penicillin-binding proteins just enough to reduce, not eliminate, killing",
   "It exists mainly in a dormant spore form that resists cell wall agents"],
  "Despite decades of use, Treponema pallidum has not developed the beta-lactamase production, efflux pumps, or penicillin-binding protein alterations seen in many other bacteria, so penicillin remains uniformly effective, which is why it is preferred at every stage of syphilis, including in pregnancy where it is the only proven safe and effective option.",
  difficulty="medium",
  why={"The organism produces its own penicillin-degrading enzyme at low levels only": "No meaningful beta-lactamase activity has been demonstrated in this organism.",
       "Its outer membrane pumps penicillin out before it can act": "No clinically significant efflux-based resistance mechanism has been identified.",
       "It alters penicillin-binding proteins just enough to reduce, not eliminate, killing": "No PBP-based resistance mechanism reducing penicillin efficacy has been established in this organism.",
       "It exists mainly in a dormant spore form that resists cell wall agents": "Treponema pallidum, like other spirochetes, does not form spores."}),

Q(TAG_SPIRO, "Syphilis: doxycycline as an alternative regimen",
  "A patient with early syphilis has a documented severe penicillin allergy and is not pregnant. Which alternative regimen is appropriate?",
  ["Doxycycline for fourteen days with close serologic follow-up",
   "A single dose of oral metronidazole with no further therapy",
   "Topical mupirocin applied directly to the primary lesion",
   "Oral vancomycin for ten days to cover the spirochete",
   "A short course of trimethoprim-sulfamethoxazole for five days"],
  "For non-pregnant patients with a significant penicillin allergy, doxycycline for two weeks is an effective alternative for early syphilis, whereas in pregnancy, penicillin desensitization is required since alternatives are not considered reliably safe or effective for the fetus.",
  difficulty="medium",
  why={"A single dose of oral metronidazole with no further therapy": "Metronidazole is not active against Treponema pallidum.",
       "Topical mupirocin applied directly to the primary lesion": "Topical antibiotics do not treat a systemic spirochetal infection.",
       "Oral vancomycin for ten days to cover the spirochete": "Vancomycin is not used to treat syphilis and does not reliably penetrate to treat this organism.",
       "A short course of trimethoprim-sulfamethoxazole for five days": "This combination is not an established alternative regimen for syphilis."},
  table=SYPH_TESTS),

Q(TAG_SPIRO, "Syphilis: ocular and otic involvement",
  "A patient with HIV and a history of untreated syphilis develops blurred vision and is found to have posterior uveitis. Which statement about this complication is correct?",
  ["It can occur at any stage and warrants treatment as neurosyphilis",
   "It only occurs in the congenital form of the disease",
   "It is always painless and resolves without any treatment",
   "It indicates that the disease has been fully cured already",
   "It is unrelated to Treponema pallidum and needs no further workup"],
  "Ocular syphilis (including uveitis) and otosyphilis can occur at any stage of infection, are more common in patients with HIV, and are treated according to the neurosyphilis regimen (intravenous aqueous penicillin G) regardless of cerebrospinal fluid findings, since the eye and inner ear are considered extensions of the central nervous system for treatment purposes.",
  difficulty="hard",
  why={"It only occurs in the congenital form of the disease": "Ocular involvement occurs in acquired syphilis as well, not only the congenital form.",
       "It is always painless and resolves without any treatment": "Ocular syphilis requires treatment and can cause permanent vision loss if untreated.",
       "It indicates that the disease has been fully cured already": "This complication indicates active, undertreated disease rather than cure.",
       "It is unrelated to Treponema pallidum and needs no further workup": "Ocular syphilis is a direct complication of the infection and requires treatment, not dismissal."},
  table=SYPHILIS_STAGES),

Q(TAG_SPIRO, "Syphilis: HIV testing at diagnosis",
  "A young adult is newly diagnosed with primary syphilis after presenting with a painless genital ulcer. Beyond treating the chancre, what should be routinely offered given this diagnosis?",
  ["Testing for HIV and other sexually transmitted infections",
   "Immediate lumbar puncture regardless of any neurologic symptoms",
   "A chest radiograph to evaluate for pulmonary involvement",
   "Screening colonoscopy given a possible gastrointestinal association",
   "Liver biopsy to evaluate for early hepatic gumma formation"],
  "A new diagnosis of syphilis should prompt testing for HIV and other sexually transmitted infections, since genital ulcers facilitate HIV transmission and shared risk factors are common; routine lumbar puncture is reserved for patients with neurologic, ocular, or otic symptoms or treatment failure, not for uncomplicated primary disease.",
  difficulty="easy",
  why={"Immediate lumbar puncture regardless of any neurologic symptoms": "Lumbar puncture is reserved for those with neurologic, ocular, or otic signs, or other specific indications, not routinely for primary disease.",
       "A chest radiograph to evaluate for pulmonary involvement": "Syphilis does not typically involve the lungs, so this is not a routine part of the workup.",
       "Screening colonoscopy given a possible gastrointestinal association": "There is no established need for colonoscopy screening based on a syphilis diagnosis.",
       "Liver biopsy to evaluate for early hepatic gumma formation": "Gummas are a late tertiary finding and would not be an expected or indicated workup step at the time of primary diagnosis."},
  table=SYPHILIS_STAGES),

# ================= Mycobacterium tuberculosis — 1 =================
Q(TAG_MYCO, "TB: pleural effusion pathophysiology",
  "A patient with tuberculosis develops a unilateral pleural effusion. Thoracentesis shows an exudate with a lymphocyte predominance, low glucose, and a markedly elevated adenosine deaminase level, but the fluid smear and culture are both negative for acid-fast bacilli. What best explains the low yield of direct organism detection in this fluid?",
  ["A delayed hypersensitivity reaction to a small antigen load drives it",
   "The pleural space is sterile and the process is entirely noninfectious",
   "The organisms have already been cleared by prior antibiotic exposure",
   "The fluid represents a transudate from elevated pulmonary venous pressure",
   "The bacilli are present in large numbers but lack a demonstrable cell wall"],
  "Tuberculous pleural effusion typically results from a delayed-type hypersensitivity reaction to a relatively small number of mycobacterial antigens that rupture into the pleural space, so direct smear and culture of the fluid have low sensitivity; elevated adenosine deaminase and a lymphocytic exudate are used to support the diagnosis, with pleural biopsy offering higher yield than fluid alone.",
  difficulty="hard",
  why={"The pleural space is sterile and the process is entirely noninfectious": "The effusion is a genuine response to mycobacterial antigen, not an unrelated sterile process.",
       "The organisms have already been cleared by prior antibiotic exposure": "No antibiotic treatment is mentioned, and the low yield is an inherent feature of this pathophysiology, not a treatment effect.",
       "The fluid represents a transudate from elevated pulmonary venous pressure": "The fluid is described as an exudate, not a transudate from a hydrostatic cause.",
       "The bacilli are present in large numbers but lack a demonstrable cell wall": "Mycobacteria retain their characteristic mycolic-acid cell wall here; the low yield instead reflects a paucibacillary immune-mediated process."},
  table=TB_DRUGS),

# ================= Nontuberculous mycobacteria & M. leprae — 10 =================
Q(TAG_MYCO, "M. marinum: exposure and lesion morphology",
  "A home aquarium enthusiast develops a slowly enlarging nodule on the hand that progresses to a chain of similar nodules tracking up the forearm along the lymphatics, without significant fever. Which organism and exposure fit best?",
  ["Mycobacterium marinum from handling fish or their tank water",
   "Mycobacterium tuberculosis from an unrecognized household contact",
   "Mycobacterium leprae from contact with an armadillo",
   "Mycobacterium avium complex from inhaled aerosolized water",
   "Mycobacterium abscessus from a recent cosmetic tattoo"],
  "Mycobacterium marinum causes a sporotrichoid pattern of nodules along lymphatic channels after minor trauma during exposure to fish tanks, aquariums, or fish handling, growing best at the cooler temperature of the skin (around 30°C) rather than core body temperature, and is treated with a prolonged multidrug regimen such as clarithromycin plus ethambutol or rifampin.",
  difficulty="medium",
  why={"Mycobacterium tuberculosis from an unrecognized household contact": "TB does not typically produce this sporotrichoid lymphatic nodular pattern from skin inoculation.",
       "Mycobacterium leprae from contact with an armadillo": "Leprosy presents with anesthetic skin lesions and nerve involvement, not this lymphatic nodular chain, and lacks the aquarium exposure.",
       "Mycobacterium avium complex from inhaled aerosolized water": "MAC classically causes pulmonary or disseminated disease, not this localized cutaneous lymphatic pattern.",
       "Mycobacterium abscessus from a recent cosmetic tattoo": "While M. abscessus can cause skin infections after procedures, the aquarium exposure and sporotrichoid pattern specifically point to M. marinum."},
  table=STAINS),

Q(TAG_MYCO, "MAC: pulmonary disease in non-HIV hosts",
  "An older woman with bronchiectasis and no HIV risk factors has chronic cough and nodular infiltrates on chest CT, with repeated sputum cultures growing Mycobacterium avium complex. How does this presentation differ from disseminated MAC in AIDS?",
  ["It is a localized lung infection rather than a bloodstream illness",
   "It requires no treatment since MAC is never pathogenic outside AIDS",
   "It indicates the patient has undiagnosed advanced HIV infection",
   "It is treated with isoniazid, rifampin, and pyrazinamide only",
   "It always progresses rapidly to septic shock within days"],
  "MAC can cause chronic, indolent pulmonary disease in older patients with structural lung disease such as bronchiectasis, distinct from the disseminated, bloodstream form seen with advanced immunosuppression in AIDS; pulmonary MAC is treated with a macrolide, ethambutol, and rifampin, rather than a standard TB regimen, and requires prolonged therapy based on sputum conversion.",
  difficulty="medium",
  why={"It requires no treatment since MAC is never pathogenic outside AIDS": "Pulmonary MAC disease in structurally damaged lungs is a recognized indication for treatment even without HIV.",
       "It indicates the patient has undiagnosed advanced HIV infection": "Pulmonary MAC occurs independently of HIV status, particularly in older patients with bronchiectasis.",
       "It is treated with isoniazid, rifampin, and pyrazinamide only": "MAC is not reliably susceptible to standard first-line TB drugs and requires a macrolide-based regimen.",
       "It always progresses rapidly to septic shock within days": "Pulmonary MAC in this population typically follows an indolent, chronic course rather than rapid deterioration."},
  table=HIV_OI),

Q(TAG_MYCO, "Rapidly growing mycobacteria: surgical site infection",
  "Weeks after cosmetic liposuction, a patient develops draining nodules along the surgical incision sites that fail to respond to standard antistaphylococcal antibiotics, and cultures eventually grow an acid-fast organism within five days of incubation. Which group of organisms is most likely responsible?",
  ["Rapidly growing mycobacteria such as M. abscessus or M. fortuitum",
   "Mycobacterium tuberculosis reactivating at the surgical incision site",
   "Mycobacterium leprae introduced through the surgical wound",
   "Mycobacterium avium complex disseminated to the skin",
   "Mycobacterium marinum from contaminated operating room water"],
  "Rapidly growing mycobacteria (M. abscessus, M. fortuitum, M. chelonae) grow in culture within days rather than weeks, unlike M. tuberculosis, and are recognized causes of surgical site and cosmetic procedure-related infections (including liposuction, tattoos, and injections) that fail typical antistaphylococcal therapy and require prolonged multidrug regimens tailored to species and susceptibility.",
  difficulty="medium",
  why={"Mycobacterium tuberculosis reactivating at the surgical incision site": "M. tuberculosis grows slowly, typically taking weeks on culture, not days, and does not typically cause this procedure-associated pattern.",
       "Mycobacterium leprae introduced through the surgical wound": "M. leprae cannot be cultured on artificial media at all, ruling out this rapid culture growth.",
       "Mycobacterium avium complex disseminated to the skin": "MAC is a slow grower and more typically causes pulmonary or disseminated disease in immunocompromised hosts, not this rapid-growing wound pattern.",
       "Mycobacterium marinum from contaminated operating room water": "M. marinum is also a slower-growing species and is classically linked to aquatic exposure, not surgical wounds."}),

Q(TAG_MYCO, "Leprosy: transmission and susceptibility",
  "Most household contacts of a patient with lepromatous leprosy never develop clinical disease despite prolonged exposure. What best explains this observation?",
  ["Most exposed individuals mount an effective cell-mediated immune response",
   "The organism is not actually transmissible between humans at all",
   "Household contacts are protected entirely by prior BCG vaccination",
   "Transmission requires a deep puncture wound, which is uncommon",
   "The organism only infects individuals with an underlying immunodeficiency"],
  "Only a minority of people exposed to M. leprae, thought to be transmitted mainly via nasal droplets from lepromatous (multibacillary) patients, ever develop clinical leprosy, because most individuals mount an effective Th1 cell-mediated response that contains or clears the organism; genetic susceptibility and the strength of this cellular response largely determine who develops disease and along which end of the clinical spectrum.",
  difficulty="medium",
  why={"The organism is not actually transmissible between humans at all": "Person-to-person transmission, mainly via prolonged close respiratory contact, is well documented, even though most exposed people do not develop disease.",
       "Household contacts are protected entirely by prior BCG vaccination": "BCG offers only partial, inconsistent protection against leprosy and is not the primary explanation for low attack rates.",
       "Transmission requires a deep puncture wound, which is uncommon": "Nasal droplet transmission, not puncture wounds, is thought to be the main route.",
       "The organism only infects individuals with an underlying immunodeficiency": "Clinical leprosy occurs in immunocompetent people as well; susceptibility is a spectrum, not limited to overtly immunodeficient hosts."},
  table=LEPROSY),

Q(TAG_MYCO, "Leprosy: reversal reaction",
  "A patient with borderline leprosy started on multidrug therapy several weeks ago develops sudden painful swelling and erythema of existing skin lesions along with new tenderness of several peripheral nerves. What does this represent?",
  ["A type 1 reversal reaction with a shift toward greater cell-mediated immunity",
   "Erythema nodosum leprosum from immune complex deposition",
   "Treatment failure requiring a change to a different antibiotic regimen",
   "A new, unrelated bacterial superinfection of the skin lesions",
   "An IgE-mediated drug allergy to one of the leprosy medications"],
  "A type 1 (reversal) reaction occurs, often after starting treatment, when the immune response shifts toward a more Th1, cell-mediated pattern, causing inflammation and swelling of existing skin lesions and, importantly, acute neuritis that can cause permanent nerve damage if not promptly treated with corticosteroids; this differs from erythema nodosum leprosum, which involves immune complex-mediated systemic inflammation, more typical of lepromatous disease.",
  difficulty="hard",
  why={"Erythema nodosum leprosum from immune complex deposition": "ENL typically presents with new tender subcutaneous nodules and systemic symptoms, occurring mainly in lepromatous disease, rather than reactivation of existing plaques with neuritis in borderline disease.",
       "Treatment failure requiring a change to a different antibiotic regimen": "This immune reaction occurs despite effective treatment and does not itself indicate drug failure.",
       "A new, unrelated bacterial superinfection of the skin lesions": "The pattern described, including nerve tenderness, is characteristic of an immune reaction rather than a new bacterial infection.",
       "An IgE-mediated drug allergy to one of the leprosy medications": "This presentation with nerve involvement is a recognized immunologic reaction to the underlying disease process, not a drug hypersensitivity reaction."},
  table=LEPROSY),

Q(TAG_MYCO, "Leprosy: erythema nodosum leprosum",
  "A patient with lepromatous leprosy on treatment develops new crops of tender subcutaneous nodules, fever, and joint pain, with biopsy showing a neutrophilic infiltrate around blood vessels. What is the underlying mechanism of this reaction?",
  ["Immune complex deposition causing a type III hypersensitivity reaction",
   "A direct cytopathic effect of rapidly multiplying live bacilli",
   "A cell-mediated shift toward stronger Th1 granuloma formation",
   "An IgE-mediated mast cell degranulation reaction to therapy",
   "Reactivation of latent tuberculosis coinfection during treatment"],
  "Erythema nodosum leprosum, a type 2 reaction seen mainly in lepromatous (multibacillary) leprosy, results from immune complex deposition (a type III hypersensitivity reaction) as bacterial antigens are released during treatment, producing tender nodules, fever, neuritis, and systemic inflammation, and is managed with thalidomide or corticosteroids rather than by stopping antileprosy therapy.",
  difficulty="hard",
  why={"A direct cytopathic effect of rapidly multiplying live bacilli": "The reaction occurs during effective treatment, when bacillary killing, not multiplication, is occurring.",
       "A cell-mediated shift toward stronger Th1 granuloma formation": "That description fits a type 1 reversal reaction, which has a different histology and occurs more often in borderline disease.",
       "An IgE-mediated mast cell degranulation reaction to therapy": "The histology described (immune complex, neutrophilic, perivascular) does not match an IgE-mediated process.",
       "Reactivation of latent tuberculosis coinfection during treatment": "There is no indication of a separate tuberculous process; the findings are explained by the leprosy immune reaction itself."},
  table=LEPROSY),

Q(TAG_MYCO, "Leprosy: histoid variant and drug resistance",
  "A patient previously treated for lepromatous leprosy develops new, unusually firm, dome-shaped cutaneous nodules with a distinctive spindle-cell histology packed with bacilli. What does this variant suggest?",
  ["A histoid form that can signal irregular therapy or emerging resistance",
   "A benign, self-limited scar reaction unrelated to the original infection",
   "Definite proof of cure requiring no further evaluation",
   "A new, unrelated dermatofibroma occurring coincidentally",
   "A manifestation exclusively linked to HIV coinfection"],
  "Histoid leprosy is an uncommon variant that can arise in patients with irregular treatment, drug resistance, or relapse, presenting with firm nodules containing a characteristic spindle-cell pattern densely packed with acid-fast bacilli, and it warrants reassessment of adherence and drug susceptibility rather than being dismissed as benign.",
  difficulty="hard",
  why={"A benign, self-limited scar reaction unrelated to the original infection": "The lesion is bacillus-laden and reflects ongoing or resistant infection, not a benign unrelated scar.",
       "Definite proof of cure requiring no further evaluation": "New bacillus-rich nodules indicate the opposite of cure and warrant further workup.",
       "A new, unrelated dermatofibroma occurring coincidentally": "The histology and bacillary content described are specific to this leprosy variant, not an unrelated skin tumor.",
       "A manifestation exclusively linked to HIV coinfection": "Histoid leprosy is linked to treatment irregularity or resistance and is not exclusive to HIV coinfected patients."}),

Q(TAG_MYCO, "Leprosy: classification for treatment purposes",
  "The World Health Organization classifies leprosy into paucibacillary and multibacillary categories to guide treatment duration and drug combinations. Which feature is used to make this distinction in a resource-limited field setting?",
  ["The number of skin lesions and nerves involved on clinical examination",
   "The results of a whole-genome sequencing panel of the organism",
   "The patient's HIV status determined by rapid antibody testing",
   "The presence or absence of a family history of leprosy",
   "The patient's age at the time of the initial examination"],
  "In settings without ready access to skin smears, the WHO classifies leprosy as paucibacillary (five or fewer skin lesions, one nerve involved) or multibacillary (more than five lesions or more than one nerve, or a positive skin smear) based on simple clinical criteria, which determines whether a shorter two-drug or longer three-drug multidrug regimen is used.",
  difficulty="medium",
  why={"The results of a whole-genome sequencing panel of the organism": "Sequencing is not part of routine field classification and is not available in most treatment settings.",
       "The patient's HIV status determined by rapid antibody testing": "HIV status can influence management in some contexts but is not the basis for the paucibacillary/multibacillary classification.",
       "The presence or absence of a family history of leprosy": "Family history may reflect exposure risk but is not used to classify current disease severity for treatment.",
       "The patient's age at the time of the initial examination": "Age is not a criterion used in this clinical classification scheme."},
  table=LEPROSY),

Q(TAG_MYCO, "M. leprae: obligate intracellular growth requirement",
  "Researchers attempting to culture Mycobacterium leprae in the laboratory find that it fails to grow on any standard mycobacterial media, including Lowenstein-Jensen agar. Which approach has historically been used instead to propagate and study this organism?",
  ["Inoculation into the footpads of mice or into armadillos",
   "Growth in embryonated chicken eggs at forty degrees Celsius",
   "Culture in charcoal yeast extract agar with added cysteine",
   "Propagation in a standard mammalian cell line at thirty-seven degrees",
   "Co-culture with a helper mycobacterial species on solid agar"],
  "M. leprae has never been successfully cultured on artificial media; it can be grown in the footpads of mice, which limits bacillary load and mimics its natural cool-temperature tropism, and more robustly in nine-banded armadillos, whose lower core body temperature supports much higher bacillary yields for research and vaccine studies.",
  difficulty="medium",
  why={"Growth in embryonated chicken eggs at forty degrees Celsius": "Egg culture at that temperature is used for organisms like Rickettsia and some viruses, not M. leprae, which prefers cooler temperatures and does not grow this way.",
       "Culture in charcoal yeast extract agar with added cysteine": "That specialized medium is used for Legionella and does not support M. leprae growth.",
       "Propagation in a standard mammalian cell line at thirty-seven degrees": "Core body temperature is too warm for this organism's preferred growth range, and it is not reliably propagated in standard cell lines.",
       "Co-culture with a helper mycobacterial species on solid agar": "No such co-culture method has enabled artificial cultivation of M. leprae."},
  table=LEPROSY),

Q(TAG_MYCO, "Leprosy: dapsone adverse effect",
  "A patient started on dapsone as part of multidrug therapy for leprosy develops fatigue and is found to have hemolytic anemia with bite cells on peripheral smear. Which underlying condition predisposes to this adverse effect?",
  ["Glucose-6-phosphate dehydrogenase deficiency",
   "Hereditary spherocytosis from a membrane protein defect",
   "Sickle cell trait with occasional vaso-occlusive episodes",
   "Autoimmune warm antibody hemolytic anemia",
   "Paroxysmal nocturnal hemoglobinuria from complement dysregulation"],
  "Dapsone, an oxidant drug, can precipitate hemolytic anemia in patients with glucose-6-phosphate dehydrogenase deficiency, producing bite cells and Heinz bodies from oxidative damage to hemoglobin, similar to other oxidant drugs such as sulfonamides and primaquine; screening for G6PD deficiency is considered before starting dapsone in at-risk populations.",
  difficulty="medium",
  why={"Hereditary spherocytosis from a membrane protein defect": "Spherocytosis causes chronic hemolysis from a membrane defect and is not specifically triggered by dapsone's oxidant mechanism.",
       "Sickle cell trait with occasional vaso-occlusive episodes": "Sickle trait does not predispose to oxidant-drug hemolysis in the way described here.",
       "Autoimmune warm antibody hemolytic anemia": "This is an antibody-mediated process unrelated to the oxidant mechanism of dapsone-induced hemolysis.",
       "Paroxysmal nocturnal hemoglobinuria from complement dysregulation": "This condition involves complement-mediated hemolysis, a different mechanism than the oxidant stress caused by dapsone."},
  table=LEPROSY),
]
