"""Additional protozoa and helminth questions: Giardia/Entamoeba/Cryptosporidium/Cyclospora,
Plasmodium & Babesia, Toxoplasma/trypanosomes/Leishmania/free-living amoebae, cestodes &
trematodes, and a couple more nematode angles. Supplements n07_para_sys.py and
n15_fungi_para.py with new vignettes and angles rather than repeating them."""
from qcore import Q
TAG_PROT = "Protozoa"
TAG_HELM = "Helminths"

QUESTIONS = [
# ================= Giardia, Entamoeba, Cryptosporidium, Cyclospora =================
Q(TAG_PROT, "Giardia: trophozoite identification",
  "A stool wet mount from a hiker with foul-smelling, greasy diarrhea after a backcountry camping trip shows a pear-shaped organism with two nuclei and four pairs of flagella that appears to tumble as it moves. Which structure is this organism using to attach to the duodenal mucosa?",
  ["A ventral adhesive disc",
   "A cortical row of cilia",
   "A posterior sucker with hooks",
   "A flagellar pocket near the kinetoplast",
   "An oral groove lined with microtubules"],
  "Giardia lamblia trophozoites attach to duodenal enterocytes with a ventral sucking disc made of microtubules, without invading tissue. The classic wet mount shows a falling-leaf motility pattern. Cysts, not trophozoites, are the infective and environmentally resistant form.",
  difficulty="easy",
  why={"A cortical row of cilia": "Ciliary rows are a feature of Balantidium coli, not Giardia.",
       "A posterior sucker with hooks": "A hooked posterior sucker describes the scolex of tapeworms such as Taenia.",
       "A flagellar pocket near the kinetoplast": "A kinetoplast-associated flagellar pocket is a trypanosome feature.",
       "An oral groove lined with microtubules": "A ciliated oral groove is a feature of Balantidium, not Giardia."}),

Q(TAG_PROT, "Giardia: transmission and cyst form",
  "An outbreak of watery, non-bloody diarrhea occurs among people who drank untreated water from a mountain stream without boiling or filtering it first. Which form of the parasite in the water was responsible for establishing infection after ingestion?",
  ["A resistant quadrinucleate cyst",
   "A binucleate trophozoite",
   "An acid-fast sporulated oocyst",
   "A motile ciliated cyst",
   "An encapsulated microsporidian spore"],
  "Giardia cysts are quadrinucleate, environmentally resistant, and survive routine chlorination, so untreated surface water is a classic source. Filtration or boiling, rather than chlorine alone, reliably removes them. Excystation occurs in the duodenum after ingestion.",
  difficulty="easy",
  why={"A binucleate trophozoite": "Trophozoites do not survive well outside the host and are not the infectious form.",
       "An acid-fast sporulated oocyst": "A sporulated acid-fast oocyst describes Cryptosporidium or Cyclospora, not Giardia.",
       "A motile ciliated cyst": "Giardia cysts lack cilia, and motility belongs to the trophozoite stage.",
       "An encapsulated microsporidian spore": "Microsporidian spores belong to an unrelated, much smaller organism."}),

Q(TAG_PROT, "Giardia: mechanism of malabsorption",
  "A child with several weeks of greasy, foul-smelling stools and poor weight gain is found to have Giardia trophozoites on duodenal aspirate. Biopsy shows flattened villi with organisms adherent to the epithelium but no ulceration or tissue invasion. Which mechanism best accounts for the resulting fat malabsorption?",
  ["Attachment to the small bowel impairs local enzyme function",
   "Invasion destroys the colonic wall and causes bleeding",
   "A secreted toxin triggers massive chloride secretion",
   "Autoantibodies form against the intestinal lining",
   "Overgrowth of ileal bacteria deconjugates bile acids"],
  "Giardia causes malabsorption through mechanical attachment and diffuse mucosal injury with disaccharidase and enzyme deficiency, not tissue invasion or a classic enterotoxin. Symptoms improve after treatment with metronidazole or tinidazole once the mucosa recovers.",
  difficulty="medium",
  why={"Invasion destroys the colonic wall and causes bleeding": "Giardia does not invade tissue and mainly affects the small bowel, not the colon.",
       "A secreted toxin triggers massive chloride secretion": "No cholera-like enterotoxin has been identified in Giardia.",
       "Autoantibodies form against the intestinal lining": "No autoimmune mechanism is implicated in giardiasis.",
       "Overgrowth of ileal bacteria deconjugates bile acids": "This describes a separate mechanism of bacterial, not parasitic, malabsorption."}),

Q(TAG_PROT, "Giardia: diagnosis pearls",
  "A 30-year-old man has three weeks of bloating, flatulence, and greasy stools after returning from backpacking in Nepal. A single stool ova and parasite exam is negative. Which next step best increases the chance of detecting the causative organism?",
  ["Antigen testing or repeat sampling on separate days",
   "A single rectal biopsy taken during colonoscopy",
   "Blood cultures drawn during a febrile episode",
   "Serum antibody testing for amebic infection",
   "An abdominal CT scan with contrast enhancement"],
  "Giardia shedding is intermittent, so a single stool exam has limited sensitivity. Stool antigen enzyme immunoassay or repeat sampling over several days improves detection. Duodenal aspirate or string testing is reserved for cases that remain unconfirmed.",
  difficulty="easy",
  why={"A single rectal biopsy taken during colonoscopy": "Giardia lives in the duodenum and is not reliably found on random rectal biopsy.",
       "Blood cultures drawn during a febrile episode": "Giardiasis does not typically cause bacteremia or fever.",
       "Serum antibody testing for amebic infection": "That test targets a different organism and would not confirm giardiasis.",
       "An abdominal CT scan with contrast enhancement": "Imaging does not identify this luminal parasite."}),

Q(TAG_PROT, "Giardia: treatment in pregnancy",
  "A pregnant woman in her first trimester has confirmed giardiasis with persistent diarrhea and poor oral intake. Metronidazole is being considered. Which alternative is generally preferred earlier in pregnancy?",
  ["Paromomycin, a poorly absorbed luminal agent",
   "Tinidazole, given as a single high dose",
   "Chloroquine, dosed weekly until delivery",
   "Doxycycline, continued for two weeks",
   "Iodoquinol, used for six straight weeks"],
  "Paromomycin is a poorly absorbed aminoglycoside that acts within the gut lumen with minimal systemic exposure, making it a reasonable option in early pregnancy when metronidazole and tinidazole are often avoided. Symptomatic and supportive care is otherwise continued.",
  difficulty="medium",
  why={"Tinidazole, given as a single high dose": "Tinidazole is generally avoided in the first trimester along with metronidazole.",
       "Chloroquine, dosed weekly until delivery": "Chloroquine treats malaria and has no role in giardiasis.",
       "Doxycycline, continued for two weeks": "Tetracyclines are avoided in pregnancy due to fetal effects.",
       "Iodoquinol, used for six straight weeks": "Iodoquinol is not the preferred first choice in early pregnancy and carries its own toxicity concerns."}),

Q(TAG_PROT, "Giardia: differentiating giardiasis from amebiasis",
  "Two patients return from travel abroad with diarrhea of similar duration. One has bloating and greasy, non-bloody stools, while the other has tenesmus with blood and mucus in the stool. Which feature best distinguishes the first presentation as giardiasis rather than amebiasis?",
  ["Absence of blood or invasive mucosal disease",
   "Presence of trophozoites containing red blood cells",
   "Onset of fever with hepatic tenderness",
   "Detection of flask-shaped ulcers on colonoscopy",
   "Growth of erythrophagocytic organisms in culture"],
  "Giardiasis produces a non-inflammatory, malabsorptive diarrhea without invasion, while amebiasis causes dysentery from invasive colitis with erythrophagocytic trophozoites and flask-shaped ulcers. Fever and hepatic tenderness suggest possible extension to amebic liver abscess.",
  difficulty="medium",
  why={"Presence of trophozoites containing red blood cells": "Erythrophagocytosis is characteristic of invasive Entamoeba histolytica, not Giardia.",
       "Onset of fever with hepatic tenderness": "Hepatic involvement suggests amebic liver abscess rather than giardiasis.",
       "Detection of flask-shaped ulcers on colonoscopy": "Flask-shaped ulcers are the classic Entamoeba lesion, not seen in giardiasis.",
       "Growth of erythrophagocytic organisms in culture": "That finding points to Entamoeba histolytica."}),

Q(TAG_PROT, "Entamoeba histolytica: colonic ulcer pattern",
  "Colonoscopy in a patient with dysentery reveals discrete ulcers with narrow necks and broad undermined bases scattered through the colon, with relatively normal mucosa between lesions. Which organism produces this pattern?",
  ["Entamoeba histolytica",
   "Shigella flexneri",
   "Salmonella Typhi",
   "Clostridioides difficile",
   "Campylobacter jejuni"],
  "Entamoeba histolytica trophozoites burrow through the mucosa and undermine the submucosa, producing classic flask-shaped ulcers with narrow openings and wide bases, separated by relatively spared mucosa. This distinguishes amebic colitis from the diffuse bacterial colitides.",
  difficulty="medium",
  why={"Shigella flexneri": "Shigella produces diffuse mucosal inflammation and ulceration rather than discrete flask-shaped lesions.",
       "Salmonella Typhi": "Typhoid causes ileal Peyer patch ulceration, not this colonic flask pattern.",
       "Clostridioides difficile": "C. difficile causes pseudomembranous plaques, not undermined flask ulcers.",
       "Campylobacter jejuni": "Campylobacter causes diffuse colitis without the classic flask-shaped ulcer."}),

Q(TAG_PROT, "Entamoeba histolytica: serology in liver abscess",
  "A 40-year-old man from an endemic region has fever, right upper quadrant pain, and a single hypoechoic liver lesion on ultrasound. Aspirate, if obtained, would likely show reddish-brown material without organisms on direct smear. Which test most reliably confirms the diagnosis?",
  ["Serum antibody testing against Entamoeba antigens",
   "Gram stain of the aspirated fluid",
   "Blood cultures for enteric organisms",
   "Stool culture for invasive bacteria",
   "Aspirate culture on standard bacterial media"],
  "Amebic liver abscess aspirate is classically sterile 'anchovy paste' with few organisms visible on direct smear, so serum antibody testing is the most useful confirmatory test and is positive in the great majority of cases. Metronidazole plus a luminal agent is standard therapy.",
  difficulty="medium",
  why={"Gram stain of the aspirated fluid": "Amebic abscess fluid is typically sterile and acellular on direct staining.",
       "Blood cultures for enteric organisms": "Bacteremia is not expected with an amebic abscess.",
       "Stool culture for invasive bacteria": "Stool culture targets bacterial pathogens, not Entamoeba.",
       "Aspirate culture on standard bacterial media": "Entamoeba does not grow on routine bacterial culture media."}),

Q(TAG_PROT, "Entamoeba histolytica: dispar vs histolytica",
  "A routine stool ova and parasite exam in an asymptomatic food handler shows amebic cysts that are morphologically identical to Entamoeba histolytica. Which additional step is needed before recommending treatment?",
  ["Antigen or molecular testing to exclude E. dispar",
   "Empiric metronidazole regardless of species",
   "Repeat microscopy on the same specimen",
   "Colonoscopy to look for flask ulcers",
   "Antibody testing that reflects past exposure only"],
  "Entamoeba histolytica and the nonpathogenic Entamoeba dispar are morphologically indistinguishable by microscopy, so stool antigen detection or PCR is needed to confirm true pathogenic infection before committing an asymptomatic carrier to treatment.",
  difficulty="hard",
  why={"Empiric metronidazole regardless of species": "Treating without distinguishing species exposes a harmless carrier to unnecessary therapy.",
       "Repeat microscopy on the same specimen": "E. dispar and E. histolytica look identical under the microscope, so repeating it will not help.",
       "Colonoscopy to look for flask ulcers": "An asymptomatic carrier is unlikely to have invasive ulcers to find.",
       "Antibody testing that reflects past exposure only": "Antibody tests stay positive from prior infections and cannot confirm current species status."}),

Q(TAG_PROT, "Entamoeba histolytica: fulminant necrotizing colitis",
  "A malnourished young child in an endemic area develops sudden severe abdominal pain, distention, and free air on abdominal imaging after several days of dysentery. Which complication of amebic colitis has occurred?",
  ["Toxic megacolon with bowel perforation",
   "Development of an amebic brain abscess",
   "Progression to chronic ulcerative colitis",
   "Formation of a perianal fistula tract",
   "Spread to the lung causing empyema"],
  "Fulminant necrotizing amebic colitis can progress to toxic megacolon and perforation, a rare but highly lethal complication seen especially in young children and malnourished or immunosuppressed patients. It requires urgent surgical evaluation along with antiamebic therapy.",
  difficulty="hard",
  why={"Development of an amebic brain abscess": "Cerebral spread is a rare complication and does not explain free intraperitoneal air.",
       "Progression to chronic ulcerative colitis": "Ulcerative colitis is an unrelated autoimmune disease, not a complication of amebiasis.",
       "Formation of a perianal fistula tract": "A fistula does not explain acute distention with free air.",
       "Spread to the lung causing empyema": "Pleuropulmonary spread usually follows a liver abscess, not colitis directly."}),

Q(TAG_PROT, "Cryptosporidium: modified acid-fast stain",
  "A stool sample from a patient with watery diarrhea is examined using a modified acid-fast stain. Small red-pink spherical structures about 4 to 6 micrometers in diameter are seen against a blue-green background. Which organism is most consistent with this finding?",
  ["Cryptosporidium parvum",
   "Giardia lamblia",
   "Entamoeba histolytica",
   "Isospora belli",
   "Balantidium coli"],
  "Cryptosporidium oocysts are small, round, and stain variably acid-fast, appearing red-pink against the counterstain. Isospora oocysts are also acid-fast but larger and ellipsoidal. Diagnosis can also use antigen immunoassay, which is more sensitive than staining alone.",
  difficulty="easy",
  why={"Giardia lamblia": "Giardia trophozoites and cysts are not acid-fast and have a different morphology.",
       "Entamoeba histolytica": "Entamoeba cysts are not acid-fast and are typically larger with visible nuclei.",
       "Isospora belli": "Isospora oocysts are larger and ellipsoidal rather than small and spherical.",
       "Balantidium coli": "Balantidium is a large ciliated organism, not a small acid-fast oocyst."}),

Q(TAG_PROT, "Cryptosporidium: AIDS-associated diarrhea",
  "A man with AIDS and a CD4 count of 40 cells/microliter has three months of large-volume watery diarrhea and significant weight loss. Stool studies confirm Cryptosporidium. Which intervention most improves his long-term outcome?",
  ["Initiation of effective antiretroviral therapy",
   "A prolonged course of oral vancomycin",
   "High-dose intravenous corticosteroids",
   "Surgical resection of affected bowel",
   "Total parenteral nutrition given indefinitely"],
  "Chronic cryptosporidiosis in advanced HIV is driven by profound immune deficiency, and durable control requires immune reconstitution with antiretroviral therapy. Nitazoxanide provides modest benefit as an adjunct, but restoring CD4 counts is the key long-term intervention.",
  difficulty="medium",
  why={"A prolonged course of oral vancomycin": "Vancomycin targets bacteria such as C. difficile and has no effect on this parasite.",
       "High-dose intravenous corticosteroids": "Steroids would further impair immune control of the infection.",
       "Surgical resection of affected bowel": "The disease is diffuse and mucosal, not a surgical problem.",
       "Total parenteral nutrition given indefinitely": "Nutritional support helps symptoms but does not address the underlying immune deficiency."}),

Q(TAG_PROT, "Cryptosporidium: treatment approach",
  "A healthy 30-year-old immunocompetent adult develops profuse watery diarrhea after a farm visit, and Cryptosporidium oocysts are confirmed in stool. Symptoms have lasted five days. Which management approach is most appropriate?",
  ["Supportive rehydration alone for this mild illness",
   "Immediate intravenous amphotericin B therapy",
   "A prolonged course of oral metronidazole",
   "Emergency colonoscopy to assess mucosal damage",
   "Lifelong prophylactic nitazoxanide administration"],
  "In immunocompetent hosts, cryptosporidiosis is typically self-limited over one to two weeks, and supportive oral rehydration is sufficient. Nitazoxanide can shorten illness but is not required for a mild, resolving case, and is never given as lifelong prophylaxis in this population.",
  difficulty="easy",
  why={"Immediate intravenous amphotericin B therapy": "Amphotericin is an antifungal and has no role against this parasite.",
       "A prolonged course of oral metronidazole": "Metronidazole is not effective against Cryptosporidium.",
       "Emergency colonoscopy to assess mucosal damage": "Invasive evaluation is unnecessary for a self-limited illness in a healthy host.",
       "Lifelong prophylactic nitazoxanide administration": "Lifelong therapy is not needed once the immune system controls the infection normally."}),

Q(TAG_PROT, "Cyclospora: transmission and outbreak source",
  "Multiple restaurant patrons develop prolonged watery diarrhea with fatigue and cyclical symptoms over several weeks after eating a salad containing imported fresh raspberries and basil. Stool exam reveals oocysts that are acid-fast variable and larger than those of Cryptosporidium. Which organism is most likely responsible?",
  ["Cyclospora cayetanensis",
   "Cryptosporidium parvum",
   "Cystoisospora belli",
   "Giardia lamblia",
   "Entamoeba coli"],
  "Cyclospora cayetanensis causes outbreaks linked to imported fresh produce such as berries and leafy herbs, and its oocysts require days to weeks in the environment to become infectious, so person-to-person spread is uncommon. Trimethoprim-sulfamethoxazole is the treatment of choice.",
  difficulty="medium",
  why={"Cryptosporidium parvum": "Cryptosporidium oocysts are smaller and this organism is less associated with fresh produce outbreaks.",
       "Cystoisospora belli": "Cystoisospora is spread mainly by direct fecal-oral contact, not fresh produce outbreaks.",
       "Giardia lamblia": "Giardia cysts are not acid-fast and do not match this oocyst description.",
       "Entamoeba coli": "This is a nonpathogenic commensal ameba, not a cause of diarrheal outbreaks."}),

Q(TAG_PROT, "Cyclospora: oocyst identification",
  "A researcher examines an unstained wet mount of stool from a patient with recent travel to a region with unreliable water treatment and finds round structures roughly 8 to 10 micrometers in diameter that autofluoresce blue-green under ultraviolet light. Which organism is identified by this property?",
  ["Cyclospora cayetanensis",
   "Cryptosporidium parvum",
   "Toxoplasma gondii",
   "Entamoeba histolytica",
   "Balantidium coli"],
  "Cyclospora oocysts have a distinctive autofluorescence under ultraviolet microscopy, which helps distinguish them from the smaller, non-fluorescent Cryptosporidium oocysts seen in the same specimens. Modified acid-fast staining shows variable, sometimes wrinkled staining.",
  difficulty="hard",
  why={"Cryptosporidium parvum": "Cryptosporidium oocysts are smaller and do not autofluoresce under ultraviolet light.",
       "Toxoplasma gondii": "Toxoplasma oocysts are shed by cats and are not identified this way in routine human stool testing.",
       "Entamoeba histolytica": "Entamoeba cysts do not autofluoresce and are identified by other morphologic features.",
       "Balantidium coli": "Balantidium is a large ciliate identified by its cilia, not by autofluorescence."}),

Q(TAG_PROT, "Cyclospora: differentiating from Cryptosporidium",
  "Two stool specimens both show acid-fast staining oocysts in patients with watery diarrhea. One set of oocysts measures about 4 to 6 micrometers, and the other measures about 8 to 10 micrometers and stains variably. Which statement correctly matches size to organism?",
  ["The smaller oocysts are Cryptosporidium and the larger are Cyclospora",
   "The smaller oocysts are Cyclospora and the larger are Cryptosporidium",
   "Both sizes represent Cystoisospora at different developmental stages",
   "Both sizes represent the same organism at different hydration states",
   "The size difference reflects staining artifact rather than species"],
  "Cryptosporidium oocysts are smaller, at about 4 to 6 micrometers, while Cyclospora oocysts are larger, at about 8 to 10 micrometers, and stain acid-fast more variably. Cystoisospora oocysts are larger still and distinctly ellipsoidal rather than round.",
  difficulty="medium",
  why={"The smaller oocysts are Cyclospora and the larger are Cryptosporidium": "The size relationship is reversed.",
       "Both sizes represent Cystoisospora at different developmental stages": "Cystoisospora oocysts are larger still and ellipsoidal, not matching either size here.",
       "Both sizes represent the same organism at different hydration states": "Oocyst size does not vary with hydration; the sizes reflect two distinct species.",
       "The size difference reflects staining artifact rather than species": "The size difference is a genuine and reliable distinguishing feature between the two organisms."}),

# ================= Plasmodium & Babesia =================
Q(TAG_PROT, "P. falciparum: malaria in pregnancy",
  "A primigravid woman in a malaria-endemic region delivers a low-birth-weight infant. Placental histology shows heavy sequestration of parasitized red cells within the intervillous space. Which receptor interaction most likely mediates this pattern of sequestration?",
  ["Binding of PfEMP1 to chondroitin sulfate A",
   "Binding of PfEMP1 to ICAM-1 on endothelium",
   "Binding of merozoites to the Duffy antigen",
   "Binding of sporozoites to hepatocyte receptors",
   "Binding of gametocytes to mosquito midgut cells"],
  "In placental malaria, a specific PfEMP1 variant binds chondroitin sulfate A on the syncytiotrophoblast, sequestering infected cells in the placenta, especially in first pregnancies with less protective antibody. This contributes to low birth weight and maternal anemia.",
  difficulty="hard",
  why={"Binding of PfEMP1 to ICAM-1 on endothelium": "ICAM-1 binding mediates sequestration in cerebral malaria, not the placenta-specific pattern.",
       "Binding of merozoites to the Duffy antigen": "Duffy binding is the vivax red cell invasion pathway, not placental sequestration.",
       "Binding of sporozoites to hepatocyte receptors": "That interaction mediates liver-stage invasion, not placental disease.",
       "Binding of gametocytes to mosquito midgut cells": "That step occurs in the mosquito during transmission, unrelated to placental pathology."}),

Q(TAG_PROT, "Malaria: thick and thin smear technique",
  "A febrile returning traveler has a blood smear ordered to evaluate for malaria. The laboratory prepares both a thick and a thin film from the same sample. What is the main purpose of the thick film compared with the thin film?",
  ["It concentrates red cells to increase parasite detection sensitivity",
   "It preserves red cell morphology to identify the infecting species",
   "It measures hemoglobin concentration to assess anemia severity",
   "It stains white cells to calculate a differential count",
   "It fixes the sample for long-term storage before shipping"],
  "The thick film lyses red cells and concentrates parasites over a smaller area, increasing sensitivity for detecting low-level parasitemia. The thin film preserves red cell and parasite morphology, which is used to identify the infecting Plasmodium species.",
  difficulty="easy",
  why={"It preserves red cell morphology to identify the infecting species": "Preserved morphology for species identification is the role of the thin film.",
       "It measures hemoglobin concentration to assess anemia severity": "Neither film is used to directly measure hemoglobin concentration.",
       "It stains white cells to calculate a differential count": "A differential count is obtained from other hematology methods, not this smear pairing.",
       "It fixes the sample for long-term storage before shipping": "The films are prepared to be read promptly, not primarily for storage."}),

Q(TAG_PROT, "Babesia: co-transmission with Lyme disease",
  "A patient bitten by a tick in coastal Massachusetts develops fever and fatigue. Testing reveals both intraerythrocytic ring forms on smear and a positive Lyme IgM. Which statement about this situation is correct?",
  ["The same Ixodes tick can transmit both pathogens simultaneously",
   "A false-positive smear explains the ring forms seen here",
   "Lyme disease itself directly produces the ring forms observed",
   "Coinfection is impossible since the pathogens use different vectors",
   "The ring forms indicate a laboratory contamination artifact"],
  "Babesia microti and Borrelia burgdorferi share the same Ixodes scapularis tick vector, so coinfection is well recognized, particularly in the northeastern United States. Coinfected patients may have more severe or prolonged symptoms than with either infection alone.",
  difficulty="medium",
  why={"A false-positive smear explains the ring forms seen here": "Ring forms on smear in this setting reflect true Babesia parasitemia, not a false positive.",
       "Lyme disease itself directly produces the ring forms observed": "Borrelia does not infect red cells or create ring forms.",
       "Coinfection is impossible since the pathogens use different vectors": "Both Babesia microti and Borrelia burgdorferi share the same Ixodes tick vector.",
       "The ring forms indicate a laboratory contamination artifact": "The clinical and smear findings together support a genuine coinfection."}),

Q(TAG_PROT, "Malaria: fever periodicity by species",
  "A patient with confirmed malaria reports fever spikes recurring with chills roughly every 48 hours, corresponding to synchronized red cell rupture. Which species is most classically associated with this tertian pattern?",
  ["Plasmodium vivax",
   "Plasmodium malariae",
   "Plasmodium knowlesi",
   "Trypanosoma cruzi",
   "Babesia microti"],
  "Plasmodium vivax and P. ovale classically cause a tertian pattern with fever roughly every 48 hours, corresponding to a synchronized 48-hour erythrocytic cycle. P. malariae instead follows a quartan pattern with fever about every 72 hours.",
  difficulty="medium",
  why={"Plasmodium malariae": "P. malariae classically produces a quartan pattern with fever every 72 hours.",
       "Plasmodium knowlesi": "P. knowlesi has a daily quotidian cycle rather than a 48-hour tertian pattern.",
       "Trypanosoma cruzi": "Chagas disease does not produce a synchronized periodic fever cycle.",
       "Babesia microti": "Babesiosis typically causes a less predictable, non-periodic fever pattern."}),

Q(TAG_PROT, "Malaria: rapid diagnostic testing",
  "In a rural clinic without microscopy capability, a febrile patient from a malaria-endemic area is tested using an immunochromatographic strip that detects a falciparum-specific antigen. Which antigen does this rapid test most commonly detect?",
  ["Histidine-rich protein 2",
   "Circumsporozoite surface protein",
   "Merozoite surface protein 3",
   "Glycophorin A receptor protein",
   "Duffy binding protein ligand"],
  "Most rapid diagnostic tests for falciparum malaria detect histidine-rich protein 2, a parasite antigen released into the blood, allowing point-of-care diagnosis without a microscope. Some newer panels also add a pan-species lactate dehydrogenase target.",
  difficulty="medium",
  why={"Circumsporozoite surface protein": "This antigen is a sporozoite-stage marker used mainly in vaccine research, not routine rapid tests.",
       "Merozoite surface protein 3": "This is not the antigen targeted by standard commercial rapid diagnostic tests.",
       "Glycophorin A receptor protein": "This is a host red cell receptor, not a parasite antigen detected by the test.",
       "Duffy binding protein ligand": "This ligand is used by P. vivax for invasion and is not the falciparum rapid test target."}),

Q(TAG_PROT, "Babesia vs Plasmodium: smear differentiation",
  "A blood smear shows small intraerythrocytic ring forms without any visible brown-black pigment and occasional extracellular forms outside red cells. Which feature most helps distinguish this organism from Plasmodium on smear?",
  ["Lack of hemozoin deposits inside parasitized erythrocytes",
   "Presence of gametocytes shaped like a banana",
   "Presence of schizonts containing merozoite rosettes",
   "Presence of a dormant hepatic parasite stage",
   "Presence of synchronized fever every 48 hours"],
  "Babesia does not digest hemoglobin into hemozoin pigment the way Plasmodium does, so infected cells lack the pigment granules seen with malaria. Babesia also has no liver stage and no synchronized periodicity, unlike several Plasmodium species.",
  difficulty="hard",
  why={"Presence of gametocytes shaped like a banana": "Banana-shaped gametocytes are characteristic of P. falciparum, not Babesia.",
       "Presence of schizonts containing merozoite rosettes": "Rosette-forming schizonts are a Plasmodium feature.",
       "Presence of a dormant hepatic parasite stage": "Babesia has no liver stage, unlike Plasmodium vivax and ovale.",
       "Presence of synchronized fever every 48 hours": "Babesiosis typically lacks the synchronized periodicity seen in some Plasmodium infections."}),

Q(TAG_PROT, "Malaria: relapse vs recrudescence terminology",
  "A patient treated for malaria six weeks ago now has recurrent fever and parasitemia. The treating physician must decide whether this represents relapse, recrudescence, or reinfection. Which statement correctly defines recrudescence?",
  ["Recurrence from parasites that persisted in the blood at low levels",
   "Recurrence from dormant parasites reactivating in the liver",
   "Recurrence from a completely new infective mosquito bite",
   "Recurrence from parasites acquired through a blood transfusion",
   "Recurrence from resistant parasites transmitted congenitally"],
  "Recrudescence refers to recurrent illness from blood-stage parasites that were never fully cleared and persisted below detectable levels, seen with any species, including falciparum and malariae. Relapse specifically refers to reactivation of dormant liver hypnozoites in vivax and ovale.",
  difficulty="hard",
  why={"Recurrence from dormant parasites reactivating in the liver": "That mechanism defines relapse, which occurs with hypnozoite-forming species.",
       "Recurrence from a completely new infective mosquito bite": "That describes reinfection, a distinct new exposure.",
       "Recurrence from parasites acquired through a blood transfusion": "Transfusion-transmitted malaria is a separate route of new infection, not recrudescence.",
       "Recurrence from resistant parasites transmitted congenitally": "Congenital transmission describes a different route of acquisition, not recrudescence."}),

# ================= Toxoplasma, trypanosomes, Leishmania, free-living amoebae =================
Q(TAG_PROT, "Toxoplasma gondii: congenital infection triad",
  "An infant born to a mother with untreated primary Toxoplasma infection during pregnancy is found to have chorioretinitis, hydrocephalus, and diffuse intracranial calcifications on imaging. Which trimester of maternal infection carries the highest risk of this severe congenital presentation?",
  ["First trimester infection, though transmission is less frequent then",
   "Third trimester infection, when transmission is most frequent",
   "Second trimester infection, with risk evenly distributed",
   "Infection is equally severe no matter the trimester",
   "Only postpartum maternal infection causes this triad"],
  "Transmission of Toxoplasma to the fetus becomes more likely as pregnancy progresses, but severity is inversely related to gestational age: first-trimester infection is transmitted less often yet causes the most devastating disease, while third-trimester infection is transmitted more often but is usually milder or subclinical at birth.",
  difficulty="hard",
  why={"Third trimester infection, when transmission is most frequent": "Third-trimester infection is transmitted more often but usually causes milder or subclinical disease.",
       "Second trimester infection, with risk evenly distributed": "Risk and severity are not evenly distributed across trimesters.",
       "Infection is equally severe no matter the trimester": "Severity is inversely related to gestational age at infection.",
       "Only postpartum maternal infection causes this triad": "Postpartum maternal infection does not cross the placenta to affect the fetus."}),

Q(TAG_PROT, "Toxoplasma gondii: definitive host and oocyst shedding",
  "A veterinarian wants to counsel cat owners about reducing Toxoplasma transmission risk. In which host does the parasite complete its sexual cycle and produce oocysts shed in feces?",
  ["Domestic and wild cats, the definitive hosts",
   "Rodents and birds, the intermediate hosts",
   "Sheep and pigs, the reservoir hosts",
   "Humans, who shed oocysts after eating meat",
   "Mosquitoes, which transmit sporozoites by biting"],
  "Cats and other felids are the definitive hosts in which Toxoplasma undergoes sexual reproduction, producing oocysts shed in feces that become infectious after a period in the environment. Humans and most warm-blooded animals are intermediate hosts harboring tissue cysts only.",
  difficulty="easy",
  why={"Rodents and birds, the intermediate hosts": "Intermediate hosts harbor tissue cysts but do not support the sexual cycle.",
       "Sheep and pigs, the reservoir hosts": "Livestock are intermediate hosts with tissue cysts, not the site of sexual reproduction.",
       "Humans, who shed oocysts after eating meat": "Humans are intermediate hosts and do not shed oocysts.",
       "Mosquitoes, which transmit sporozoites by biting": "Toxoplasma is not transmitted by mosquito bite."}),

Q(TAG_PROT, "Toxoplasma gondii: acute infection in immunocompetent host",
  "A healthy 25-year-old woman who recently adopted a kitten develops mild fever and tender posterior cervical lymphadenopathy resembling mononucleosis. Heterophile antibody testing is negative. Which additional feature would support acute toxoplasmosis over Epstein-Barr virus infection?",
  ["A recent history of handling cat litter or raw meat",
   "Splenomegaly with markedly elevated liver transaminases",
   "Exudative pharyngitis with palatal petechiae",
   "A positive monospot test on repeat testing",
   "Severe fatigue lasting more than two months"],
  "Acute toxoplasmosis in immunocompetent adults often mimics mononucleosis with fever and lymphadenopathy but is heterophile-negative, so a history of exposure to cat feces or undercooked meat, combined with Toxoplasma serology, points toward this diagnosis over EBV.",
  difficulty="medium",
  why={"Splenomegaly with markedly elevated liver transaminases": "These features are common to both infections and do not favor toxoplasmosis specifically.",
       "Exudative pharyngitis with palatal petechiae": "Pharyngitis with petechiae is more typical of EBV mononucleosis.",
       "A positive monospot test on repeat testing": "A positive heterophile test would instead support EBV infection.",
       "Severe fatigue lasting more than two months": "Prolonged fatigue occurs with both and is not specific to either infection."}),

Q(TAG_PROT, "Chagas disease: acute presentation and Romana sign",
  "A child in rural Argentina develops unilateral painless periorbital swelling with conjunctival injection several days after a nocturnal insect bite near the eye, followed by fever and malaise. Which organism is responsible for this early finding?",
  ["Trypanosoma cruzi",
   "Trypanosoma brucei",
   "Leishmania braziliensis",
   "Toxoplasma gondii",
   "Onchocerca volvulus"],
  "Romana sign, unilateral painless periorbital edema at the site of triatomine bug feeding or contamination near the eye, is a classic marker of acute Trypanosoma cruzi infection. It resolves as the acute phase subsides, well before chronic cardiac or gastrointestinal disease appears.",
  difficulty="medium",
  why={"Trypanosoma brucei": "T. brucei causes African sleeping sickness and is transmitted by the tsetse fly, not a triatomine bug.",
       "Leishmania braziliensis": "Cutaneous leishmaniasis produces a chronic ulcer, not acute unilateral periorbital swelling.",
       "Toxoplasma gondii": "Toxoplasma does not cause this vector-associated periorbital sign.",
       "Onchocerca volvulus": "Onchocerca causes chronic skin nodules and eye disease over years, not an acute bite-site swelling."}),

Q(TAG_PROT, "Chagas disease: diagnostic testing by phase",
  "A physician is evaluating two patients for Trypanosoma cruzi infection: one with a two-week history of fever after a known triatomine exposure, and another with a decades-long history of dilated cardiomyopathy from an endemic country. Which testing strategy correctly matches each phase?",
  ["Blood smear for the acute case and serology for the chronic case",
   "Serology for the acute case and blood smear for the chronic case",
   "Skin biopsy for both the acute and chronic presentations",
   "Stool examination for both the acute and chronic presentations",
   "Urine antigen testing for both the acute and chronic presentations"],
  "During acute Chagas disease, circulating parasitemia is high enough to detect trypomastigotes directly on blood smear. In chronic disease, parasitemia is low and intermittent, so diagnosis relies on serologic antibody testing rather than direct visualization.",
  difficulty="hard",
  why={"Serology for the acute case and blood smear for the chronic case": "The correct pairing is reversed, since parasitemia is detectable early and antibody testing is used in the low-parasitemia chronic phase.",
       "Skin biopsy for both the acute and chronic presentations": "Skin biopsy is not the diagnostic method for either phase of Chagas disease.",
       "Stool examination for both the acute and chronic presentations": "Stool testing detects intestinal parasites, not this bloodborne trypanosome.",
       "Urine antigen testing for both the acute and chronic presentations": "Urine antigen testing is not a standard method for either phase."}),

Q(TAG_PROT, "Sleeping sickness: trypomastigote morphology",
  "A blood smear from a patient with fever and lymphadenopathy after travel to East Africa shows extracellular, elongated organisms with a single flagellum, an undulating membrane, and a densely staining posterior organelle. Which structure provides energy for this organism's motility?",
  ["Mitochondrial DNA concentrated in the kinetoplast",
   "A contractile vacuole near the anterior pole",
   "Glycogen granules stored in surface vesicles",
   "Chloroplast-derived organelles retained from evolution",
   "A calcium-rich exoskeleton along the cell body"],
  "The kinetoplast is a specialized region of mitochondrial DNA associated with the single large mitochondrion of trypanosomes, supporting the energy demands of the flagellum and undulating membrane that drive motility through blood and tissue.",
  difficulty="hard",
  why={"A contractile vacuole near the anterior pole": "Contractile vacuoles regulate osmotic balance in some protozoa, not motility energy here.",
       "Glycogen granules stored in surface vesicles": "Glycogen storage is not the structure responsible for flagellar motility.",
       "Chloroplast-derived organelles retained from evolution": "Trypanosomes are not photosynthetic and lack chloroplasts.",
       "A calcium-rich exoskeleton along the cell body": "Trypanosomes have a flexible pellicle, not a rigid mineralized exoskeleton."}),

Q(TAG_PROT, "Sleeping sickness: gambiense vs rhodesiense",
  "Two patients present with African trypanosomiasis. One, from West Africa, has a slowly progressive illness over many months. The other, from East Africa, has a rapidly progressive illness over a few weeks with early cardiac involvement. Which subspecies pairing explains this difference?",
  ["Gambiense causes the chronic form and rhodesiense the acute form",
   "Rhodesiense causes the chronic form and gambiense the acute form",
   "Both subspecies cause an identically rapid course everywhere",
   "The difference reflects host nutrition rather than subspecies",
   "The difference reflects vector species rather than parasite subspecies"],
  "Trypanosoma brucei gambiense causes a chronic, indolent West African form of sleeping sickness that may take months to years to reach the central nervous system, while T. brucei rhodesiense causes a fulminant East African form with early systemic and cardiac involvement.",
  difficulty="medium",
  why={"Rhodesiense causes the chronic form and gambiense the acute form": "The pairing is reversed.",
       "Both subspecies cause an identically rapid course everywhere": "The two subspecies differ clearly in tempo of disease.",
       "The difference reflects host nutrition rather than subspecies": "The clinical tempo is a recognized feature of the two parasite subspecies themselves.",
       "The difference reflects vector species rather than parasite subspecies": "Both subspecies are transmitted by tsetse flies; the difference is in the parasite, not the vector."}),

Q(TAG_PROT, "Leishmaniasis: vector and amastigote stage",
  "A dermatologist biopsies a chronic, painless ulcer with a raised border on the forearm of a patient who recently traveled to Central America. Microscopy of the biopsy shows macrophages packed with small oval organisms bearing a kinetoplast but no external flagellum. Which vector transmits the infective flagellated form of this organism?",
  ["The sandfly, which injects promastigotes while feeding",
   "The tsetse fly, which injects trypomastigotes while feeding",
   "The reduviid bug, which deposits organisms in its feces",
   "The Anopheles mosquito, which injects sporozoites while feeding",
   "The Ixodes tick, which regurgitates organisms during a blood meal"],
  "Leishmania is transmitted by the bite of an infected female sandfly, which injects flagellated promastigotes into the skin. These are phagocytosed by macrophages and transform into the intracellular, non-flagellated amastigote stage seen on biopsy.",
  difficulty="medium",
  why={"The tsetse fly, which injects trypomastigotes while feeding": "The tsetse fly transmits African trypanosomes, not Leishmania.",
       "The reduviid bug, which deposits organisms in its feces": "The reduviid bug transmits Chagas disease through fecal contamination, not by direct injection.",
       "The Anopheles mosquito, which injects sporozoites while feeding": "Anopheles mosquitoes transmit malaria sporozoites, not Leishmania.",
       "The Ixodes tick, which regurgitates organisms during a blood meal": "Ixodes ticks transmit Lyme disease and babesiosis, not leishmaniasis."}),

Q(TAG_PROT, "Visceral leishmaniasis: post-kala-azar dermal complication",
  "A patient successfully treated for visceral leishmaniasis in India two years ago now develops hypopigmented and nodular skin lesions on the face and trunk without recurrent fever or organomegaly. Which condition explains this finding?",
  ["Post-kala-azar dermal leishmaniasis",
   "Relapse of untreated visceral leishmaniasis",
   "Secondary cutaneous tuberculosis infection",
   "Leprosy acquired from an unrelated exposure",
   "Drug-induced hypopigmentation from prior therapy"],
  "Post-kala-azar dermal leishmaniasis is a recognized sequela that can appear months to years after apparently successful treatment of visceral disease, especially in South Asia and East Africa, and represents parasite persistence in the skin without visceral relapse.",
  difficulty="hard",
  why={"Relapse of untreated visceral leishmaniasis": "True visceral relapse would bring back fever and organomegaly, which are absent here.",
       "Secondary cutaneous tuberculosis infection": "This presentation is a recognized sequela of treated kala-azar, not a new tuberculous infection.",
       "Leprosy acquired from an unrelated exposure": "The timing and history after treated kala-azar point to a specific known complication rather than a coincidental new disease.",
       "Drug-induced hypopigmentation from prior therapy": "The nodular and hypopigmented lesions reflect parasite persistence in skin, not a drug reaction."}),

Q(TAG_PROT, "Leishmaniasis: treatment options",
  "A patient with confirmed visceral leishmaniasis and preserved renal function requires systemic therapy. Which agent is now preferred over pentavalent antimonials in most settings because of a better safety profile?",
  ["Liposomal amphotericin B",
   "Intravenous pentamidine isethionate",
   "Oral miltefosine as monotherapy",
   "Intramuscular sodium stibogluconate",
   "Oral fluconazole at a high dose"],
  "Liposomal amphotericin B has largely replaced pentavalent antimonials as first-line therapy for visceral leishmaniasis in many regions because of comparable efficacy with substantially less toxicity, allowing shorter courses and better tolerability.",
  difficulty="medium",
  why={"Intravenous pentamidine isethionate": "Pentamidine is a second-line option with more toxicity than liposomal amphotericin.",
       "Oral miltefosine as monotherapy": "Miltefosine is an alternative oral option but is not the preferred first-line agent in most settings.",
       "Intramuscular sodium stibogluconate": "This is a pentavalent antimonial, the very class being replaced.",
       "Oral fluconazole at a high dose": "Azoles have limited and inconsistent efficacy against Leishmania."}),

Q(TAG_PROT, "Naegleria fowleri: CSF findings",
  "A previously healthy teenager who swam in a warm freshwater lake develops severe headache, fever, and altered mental status within a week. Lumbar puncture shows neutrophilic pleocytosis, low glucose, and motile organisms on a wet mount. Which additional feature is most characteristic of this infection?",
  ["Rapid progression to coma and death in a matter of days",
   "A slowly progressive course over several months",
   "Spontaneous resolution without any treatment",
   "Eosinophilic pleocytosis rather than neutrophilic",
   "Formation of calcified granulomas on imaging"],
  "Naegleria fowleri causes primary amebic meningoencephalitis, a fulminant illness that enters through the cribriform plate after warm freshwater exposure and typically progresses to coma and death within about a week despite treatment, unlike the indolent course of granulomatous amebic encephalitis.",
  difficulty="medium",
  why={"A slowly progressive course over several months": "That indolent course is more typical of Acanthamoeba encephalitis.",
       "Spontaneous resolution without any treatment": "Untreated primary amebic meningoencephalitis is almost always fatal.",
       "Eosinophilic pleocytosis rather than neutrophilic": "Eosinophilic meningitis is more characteristic of Angiostrongylus infection.",
       "Formation of calcified granulomas on imaging": "Granuloma formation is a feature of chronic granulomatous amebic encephalitis, not this fulminant illness."}),

Q(TAG_PROT, "Acanthamoeba: keratitis risk factors",
  "A contact lens wearer who rinses her lenses with tap water develops severe eye pain out of proportion to exam findings, with a ring-shaped corneal infiltrate that has been unresponsive to topical antibacterial drops. Which organism is most likely responsible?",
  ["Acanthamoeba species",
   "Pseudomonas aeruginosa",
   "Herpes simplex virus",
   "Fusarium species",
   "Staphylococcus epidermidis"],
  "Acanthamoeba keratitis is strongly linked to contact lens wear combined with exposure to tap water or homemade lens solutions, producing severe pain out of proportion to findings and a ring infiltrate that fails to respond to standard antibacterial therapy.",
  difficulty="medium",
  why={"Pseudomonas aeruginosa": "Bacterial keratitis typically improves with antibacterial therapy, unlike this case.",
       "Herpes simplex virus": "Herpetic keratitis classically shows a dendritic ulcer rather than a ring infiltrate.",
       "Fusarium species": "Fungal keratitis is linked more to organic trauma than to tap-water lens rinsing.",
       "Staphylococcus epidermidis": "This organism would be expected to respond to standard antibacterial drops."}),

Q(TAG_PROT, "Trichomonas vaginalis: strawberry cervix and diagnosis",
  "A 24-year-old woman has frothy, malodorous yellow-green vaginal discharge and vulvar itching. Speculum exam reveals a cervix with punctate hemorrhages giving a strawberry appearance. Which test is most useful at the point of care?",
  ["Wet mount showing motile flagellated organisms",
   "Whiff test showing a fishy odor with potassium hydroxide",
   "KOH preparation showing branching pseudohyphae",
   "Gram stain showing clue cells with adherent bacteria",
   "Culture showing gram-negative diplococci"],
  "Trichomonas vaginalis is diagnosed at the bedside by wet mount, which shows motile, flagellated, pear-shaped trophozoites. The classic strawberry cervix reflects punctate submucosal hemorrhages and is seen in only a minority of cases, so microscopy remains essential.",
  difficulty="easy",
  why={"Whiff test showing a fishy odor with potassium hydroxide": "A positive whiff test is characteristic of bacterial vaginosis.",
       "KOH preparation showing branching pseudohyphae": "Pseudohyphae on KOH prep indicate candidal vaginitis.",
       "Gram stain showing clue cells with adherent bacteria": "Clue cells are the hallmark of bacterial vaginosis, not trichomoniasis.",
       "Culture showing gram-negative diplococci": "That finding would indicate gonococcal infection instead."}),

# ================= Cestodes and trematodes =================
Q(TAG_HELM, "Taenia: proglottid identification",
  "A patient reports periodically passing small, flat, motile segments in the stool that can crawl short distances. Microscopic examination of a segment shows a uterus with more than 12 lateral branches. Which species does this most likely represent?",
  ["Taenia saginata",
   "Taenia solium",
   "Diphyllobothrium latum",
   "Hymenolepis nana",
   "Echinococcus granulosus"],
  "Taenia saginata, acquired from undercooked beef, is distinguished from T. solium by having proglottids with more than 12 lateral uterine branches and greater motility, allowing active migration through the anus rather than passive passage.",
  difficulty="hard",
  why={"Taenia solium": "T. solium proglottids typically show fewer than 12 lateral uterine branches.",
       "Diphyllobothrium latum": "This tapeworm releases eggs through a uterine pore rather than shedding motile branched proglottids.",
       "Hymenolepis nana": "This small tapeworm has a very different proglottid structure and is usually asymptomatic.",
       "Echinococcus granulosus": "This tiny tapeworm lives only in canine hosts and does not shed proglottids in human stool."}),

Q(TAG_HELM, "Neurocysticercosis: imaging findings by stage",
  "A patient from an endemic region has new-onset seizures. Brain MRI shows a cystic lesion with a visible scolex and surrounding edema, without contrast enhancement. Which stage of the causative lesion does this represent?",
  ["The early vesicular stage, when the parasite is alive",
   "The colloidal stage, when the parasite is degenerating",
   "The granular-nodular stage, with a calcifying scar",
   "The calcified stage, representing a dead scolex",
   "An abscess stage, with active bacterial superinfection"],
  "In the vesicular stage of neurocysticercosis, the cyst contains a live, visible scolex and provokes little host inflammation, so there is minimal enhancement. As the parasite dies in later stages, the cyst degenerates, enhances, and eventually calcifies.",
  difficulty="hard",
  why={"The colloidal stage, when the parasite is degenerating": "That stage shows ring enhancement and surrounding edema from parasite death, not a live visible scolex.",
       "The granular-nodular stage, with a calcifying scar": "This later stage shows a shrinking nodular lesion, not a well-formed cyst with a live scolex.",
       "The calcified stage, representing a dead scolex": "A calcified lesion appears dense on CT and lacks a visible fluid cyst.",
       "An abscess stage, with active bacterial superinfection": "Neurocysticercosis is a parasitic, not bacterial, process."}),

Q(TAG_HELM, "Echinococcus: definitive and intermediate hosts",
  "A sheep farmer's dog frequently eats the offal of slaughtered sheep. Which sequence correctly describes the life cycle stage occurring in the dog compared with the sheep?",
  ["Adult tapeworm in the dog and hydatid cysts in the sheep",
   "Hydatid cysts in the dog and adult tapeworm in the sheep",
   "Adult tapeworm in both the dog and the sheep",
   "Hydatid cysts in both the dog and the sheep",
   "Free-living larvae in the dog and eggs in the sheep"],
  "Dogs and other canids are the definitive host, harboring the small adult tapeworm in the intestine and passing eggs in feces. Sheep, as intermediate hosts, ingest these eggs and develop hydatid cysts in organs such as the liver and lungs.",
  difficulty="medium",
  why={"Hydatid cysts in the dog and adult tapeworm in the sheep": "The host roles are reversed.",
       "Adult tapeworm in both the dog and the sheep": "Sheep develop tissue cysts, not the adult intestinal worm.",
       "Hydatid cysts in both the dog and the sheep": "Dogs harbor the adult tapeworm in the intestine, not tissue cysts.",
       "Free-living larvae in the dog and eggs in the sheep": "Neither host stage is free-living outside the body in this cycle."}),

Q(TAG_HELM, "Echinococcus: granulosus vs multilocularis",
  "Two patients have hepatic Echinococcus infection. One has a single well-defined unilocular cyst with daughter cysts, amenable to surgery or PAIR. The other has an infiltrative, tumor-like lesion with poorly defined margins invading adjacent liver tissue. Which species pairing explains this difference?",
  ["E. granulosus causes the unilocular form and E. multilocularis the infiltrative form",
   "E. multilocularis causes the unilocular form and E. granulosus the infiltrative form",
   "Both presentations are caused by E. granulosus at different time points",
   "Both presentations are caused by E. multilocularis in different hosts",
   "The difference depends on patient age rather than species"],
  "Echinococcus granulosus produces the classic well-defined, unilocular hydatid cyst with daughter cysts, while Echinococcus multilocularis causes an infiltrative, tumor-like alveolar lesion that invades surrounding tissue and behaves more aggressively, mimicking malignancy on imaging.",
  difficulty="hard",
  why={"E. multilocularis causes the unilocular form and E. granulosus the infiltrative form": "The species-pattern pairing is reversed.",
       "Both presentations are caused by E. granulosus at different time points": "E. granulosus consistently forms a well-defined unilocular cyst, not an infiltrative lesion.",
       "Both presentations are caused by E. multilocularis in different hosts": "E. multilocularis characteristically produces the infiltrative pattern, not the unilocular one.",
       "The difference depends on patient age rather than species": "The growth pattern is determined by the infecting species, not the patient's age."}),

Q(TAG_HELM, "Diphyllobothrium latum: vitamin B12 competition",
  "A patient who regularly eats raw freshwater fish develops macrocytic anemia with glossitis and a low serum vitamin B12 level. Stool examination shows operculated eggs. Which mechanism explains the vitamin deficiency?",
  ["The tapeworm avidly absorbs dietary B12 within the intestinal lumen",
   "The tapeworm secretes a toxin that destroys gastric intrinsic factor",
   "The tapeworm causes chronic blood loss leading to iron deficiency",
   "The tapeworm invades the ileal mucosa and blocks all absorption",
   "The tapeworm produces antibodies against gastric parietal cells"],
  "Diphyllobothrium latum, the fish tapeworm, competes with the host for luminal vitamin B12, absorbing much of it along its length and leading to a macrocytic, megaloblastic anemia resembling pernicious anemia but caused by nutrient competition rather than autoimmunity.",
  difficulty="medium",
  why={"The tapeworm secretes a toxin that destroys gastric intrinsic factor": "Intrinsic factor is not directly destroyed; the worm instead competes for the vitamin itself.",
       "The tapeworm causes chronic blood loss leading to iron deficiency": "This organism causes B12 deficiency and macrocytic anemia, not iron deficiency from blood loss.",
       "The tapeworm invades the ileal mucosa and blocks all absorption": "The worm remains luminal and does not invade the mucosa.",
       "The tapeworm produces antibodies against gastric parietal cells": "That autoimmune mechanism describes pernicious anemia, an unrelated condition."}),

Q(TAG_HELM, "Schistosoma: swimmer's itch and cercarial penetration",
  "A group of people wading in a freshwater lake develop an itchy papular rash on exposed skin within hours, which resolves over several days without further symptoms. Which process explains this early reaction?",
  ["An allergic response to cercariae penetrating the skin",
   "Egg deposition triggering a granulomatous skin reaction",
   "Adult worms migrating through subcutaneous tissue",
   "A toxin released by miracidia in the water",
   "Direct injury from the intermediate host snail"],
  "Cercarial dermatitis, or swimmer's itch, is a hypersensitivity reaction to schistosome cercariae penetrating the skin, often from bird schistosomes that cannot complete their life cycle in humans, producing a self-limited itchy rash without systemic disease.",
  difficulty="medium",
  why={"Egg deposition triggering a granulomatous skin reaction": "Egg-related granulomas occur later and in visceral tissues, not as an early skin rash.",
       "Adult worms migrating through subcutaneous tissue": "Adult worms reside in blood vessels, not migrating through the skin at this stage.",
       "A toxin released by miracidia in the water": "Miracidia infect snails, not humans, and are not the cause of this skin reaction.",
       "Direct injury from the intermediate host snail": "The snail is not in direct contact with the skin; the free-swimming cercariae cause the reaction."}),

Q(TAG_HELM, "Schistosoma: acute Katayama fever",
  "Four weeks after freshwater exposure in sub-Saharan Africa, a traveler develops fever, urticaria, myalgia, and marked eosinophilia, with hepatosplenomegaly on exam. Egg excretion has not yet begun. Which process is responsible for this acute illness?",
  ["An immune complex reaction to early maturing worms and eggs",
   "Direct toxin release from migrating cercariae in the skin",
   "Bacterial superinfection of the initial skin penetration site",
   "Autoimmune destruction of red cells triggered by the parasite",
   "Mechanical obstruction of the portal vein by adult worms"],
  "Katayama fever is a serum sickness-like acute reaction driven by immune complexes forming against maturing schistosomes and their earliest eggs, occurring weeks after primary exposure and before eggs are reliably detected in stool or urine.",
  difficulty="hard",
  why={"Direct toxin release from migrating cercariae in the skin": "The skin-penetration phase causes local itching, not this systemic serum sickness-like illness weeks later.",
       "Bacterial superinfection of the initial skin penetration site": "There is no evidence of bacterial infection in this systemic presentation.",
       "Autoimmune destruction of red cells triggered by the parasite": "Hemolysis is not the mechanism of this acute febrile syndrome.",
       "Mechanical obstruction of the portal vein by adult worms": "Portal disease develops later from egg-induced fibrosis, not acute worm obstruction."}),

Q(TAG_HELM, "Schistosoma haematobium: egg identification",
  "A urine sample from a patient with hematuria and travel to Lake Malawi is examined for ova. Which egg morphology confirms this specific infection?",
  ["An egg with a prominent terminal spine",
   "An egg with a prominent lateral spine",
   "An egg with a small knob-like operculum",
   "An egg that is round with a thick shell",
   "An egg containing a fully formed larva already"],
  "Schistosoma haematobium eggs have a characteristic terminal spine and are found in urine, reflecting the worm's location in the vesical venous plexus. S. mansoni eggs, found in stool, instead have a prominent lateral spine.",
  difficulty="medium",
  why={"An egg with a prominent lateral spine": "A lateral spine is the identifying feature of S. mansoni eggs, found in stool rather than urine.",
       "An egg with a small knob-like operculum": "An operculated egg describes flukes such as Paragonimus or Clonorchis, not Schistosoma.",
       "An egg that is round with a thick shell": "Schistosome eggs are oval with a spine, not round.",
       "An egg containing a fully formed larva already": "Taenia eggs contain a fully developed oncosphere; schistosome eggs contain a miracidium recognized instead by its spine."}),

Q(TAG_HELM, "Paragonimus westermani: pulmonary presentation",
  "A man from Southeast Asia who enjoys eating spicy raw crab dishes develops chronic cough with brownish, blood-streaked sputum and patchy infiltrates on chest imaging that have persisted despite antituberculous therapy. Sputum acid-fast smears are repeatedly negative. Which organism is most likely responsible?",
  ["Paragonimus westermani",
   "Mycobacterium tuberculosis",
   "Clonorchis sinensis",
   "Strongyloides stercoralis",
   "Schistosoma japonicum"],
  "Paragonimus westermani, acquired from undercooked crab or crayfish, migrates to the lungs and causes a chronic cough with rust-brown sputum containing eggs, often mistaken for tuberculosis until repeatedly negative acid-fast smears prompt reconsideration.",
  difficulty="medium",
  why={"Mycobacterium tuberculosis": "Repeatedly negative acid-fast smears and lack of response to antituberculous therapy argue against tuberculosis.",
       "Clonorchis sinensis": "Clonorchis resides in the bile ducts and causes hepatobiliary rather than pulmonary disease.",
       "Strongyloides stercoralis": "Strongyloides causes transient pulmonary migration, not chronic productive symptoms like these.",
       "Schistosoma japonicum": "This species mainly causes intestinal and hepatic disease, not a chronic lung infection from crab ingestion."}),

Q(TAG_HELM, "Clonorchis sinensis: transmission and reservoir hosts",
  "A public health investigator is tracing an outbreak of biliary fluke infection in a fishing community that regularly eats raw freshwater fish. Besides humans, which group of animals commonly serves as a reservoir host that sustains transmission?",
  ["Fish-eating mammals such as cats and dogs",
   "Migratory waterfowl such as ducks and geese",
   "Grazing livestock such as cattle and goats",
   "Freshwater snails serving as a second host",
   "Biting insects that feed on human blood"],
  "Clonorchis sinensis persists in nature partly because fish-eating mammals such as cats and dogs also harbor adult flukes in their bile ducts after eating infected raw fish, sustaining transmission even where human infection is controlled.",
  difficulty="medium",
  why={"Migratory waterfowl such as ducks and geese": "Waterfowl are reservoirs for some other trematodes, not the primary reservoir for this fluke.",
       "Grazing livestock such as cattle and goats": "Cattle and goats are not significant reservoirs for this fish-borne fluke.",
       "Freshwater snails serving as a second host": "Snails are an intermediate host in the life cycle, not a reservoir host maintaining transmission alongside humans.",
       "Biting insects that feed on human blood": "Clonorchis is acquired by ingestion, not through an insect bite."}),

# ================= Nematodes =================
Q(TAG_HELM, "Toxocara: visceral vs ocular larva migrans",
  "Two children are evaluated after exposure to soil contaminated with dog feces. A 2-year-old with pica has fever, hepatomegaly, and eosinophilia of 30%. An 8-year-old has unilateral vision loss with a granulomatous retinal mass but no eosinophilia. Which explains the difference between these two presentations?",
  ["The child's age and larval burden affect whether disease is visceral or ocular",
   "The two children are infected with different Toxocara species",
   "Only the older child was actually infected with Toxocara",
   "Ocular disease requires prior visceral disease to occur first",
   "The eosinophilia difference reflects an unrelated allergic condition"],
  "The same organism, Toxocara canis, can produce either visceral larva migrans, typically in young children with pica and heavy exposure and marked eosinophilia, or ocular larva migrans, usually in older children with a smaller larval burden confined to the eye and little systemic eosinophilia.",
  difficulty="hard",
  why={"The two children are infected with different Toxocara species": "The same species, Toxocara canis, can cause either pattern depending on host factors.",
       "Only the older child was actually infected with Toxocara": "Both presentations are recognized forms of toxocariasis in the appropriate host.",
       "Ocular disease requires prior visceral disease to occur first": "Ocular larva migrans typically occurs in older children without a preceding visceral illness.",
       "The eosinophilia difference reflects an unrelated allergic condition": "The differing eosinophilia reflects the localized nature of ocular disease, not a separate allergic process."}),

Q(TAG_HELM, "Wuchereria bancrofti: nocturnal periodicity",
  "A patient from a filariasis-endemic region has recurrent limb swelling. Blood samples drawn at midday are repeatedly negative for microfilariae despite strong clinical suspicion. What change in testing would most likely improve detection?",
  ["Drawing blood late at night, when the organisms circulate",
   "Drawing blood immediately after a large meal",
   "Testing stool instead of blood for the organism",
   "Using a fluorescent antibody stain on skin scrapings",
   "Repeating the same midday blood draw several times"],
  "Wuchereria bancrofti microfilariae characteristically show nocturnal periodicity, circulating in peripheral blood mainly at night to coincide with the biting habits of the mosquito vector, so blood should be drawn late at night to maximize detection.",
  difficulty="medium",
  why={"Drawing blood immediately after a large meal": "Meal timing does not affect the presence of this bloodborne parasite.",
       "Testing stool instead of blood for the organism": "Microfilariae circulate in blood, not in stool.",
       "Using a fluorescent antibody stain on skin scrapings": "Skin snip testing is used for Onchocerca, not Wuchereria.",
       "Repeating the same midday blood draw several times": "Microfilariae are scarce in blood during the day regardless of how many times it is sampled."}),

Q(TAG_PROT, "Babesia: severe disease after splenectomy",
  "A 68-year-old man with a history of splenectomy after a car accident develops fever, hemolytic anemia, and thrombocytopenia two weeks after a camping trip in New England. A blood smear shows intraerythrocytic ring forms, some arranged in tetrads. What best explains the severity of his illness?",
  ["The spleen normally clears infected red cells, and its absence removes that defense",
   "Splenectomy directly increases the number of infecting sporozoites delivered by the tick",
   "Splenectomy causes a permanent deficiency of antibody production against this organism",
   "Splenectomy allows the organism to invade the liver instead of red blood cells",
   "Splenectomy activates a dormant hepatic stage of this same organism"],
  "The spleen filters and clears parasitized, poorly deformable red cells and helps control intraerythrocytic infections; asplenic patients (along with the elderly and immunosuppressed) develop markedly more severe babesiosis, sometimes with very high parasitemia, because that clearance mechanism is gone.",
  difficulty="hard",
  why={"Splenectomy directly increases the number of infecting": "The tick inoculates a fixed small number of organisms regardless of the recipient's spleen status.",
       "Splenectomy causes a permanent deficiency of antibody": "Splenectomy impairs clearance of encapsulated organisms and blood-stage parasites more than it causes a global antibody defect.",
       "Splenectomy allows the organism to invade the liver": "Babesia does not have a hepatic stage; it infects red blood cells directly, unlike Plasmodium.",
       "Splenectomy activates a dormant hepatic stage of this": "A dormant hepatic stage (hypnozoite) is a feature of Plasmodium vivax and ovale, not Babesia."}),

Q(TAG_PROT, "Malaria: congenital transmission",
  "An infant born to a mother who immigrated from a malaria-endemic country develops fever, poor feeding, and hepatosplenomegaly in the first week of life. The mother was asymptomatic during pregnancy. Thick and thin blood smears from the infant show intraerythrocytic parasites. How did the infant most likely acquire this infection?",
  ["Transplacental passage of parasitized red cells into fetal circulation",
   "A mosquito bite sustained by the infant shortly after birth",
   "Ingestion of parasite cysts in breast milk during early feeding",
   "Reactivation of a parasite acquired earlier from a household contact",
   "Contamination of the umbilical stump by soil-borne parasite spores"],
  "Malaria can be transmitted congenitally when infected maternal red blood cells cross the placenta, particularly in mothers from endemic areas with partial immunity who may have low-level parasitemia without symptoms during pregnancy; the newborn then presents with fever and hepatosplenomegaly rather than a classic mosquito-acquired infection.",
  difficulty="hard",
  why={"A mosquito bite sustained by the infant shortly": "Symptoms in the first week of life are too early to reflect a new postnatal mosquito-borne infection given the parasite's life cycle.",
       "Ingestion of parasite cysts in breast milk": "Malaria parasites are not transmitted through breast milk ingestion.",
       "Reactivation of a parasite acquired earlier from a": "A neonate has not had time to acquire and then reactivate an infection from a household contact.",
       "Contamination of the umbilical stump by soil-borne": "Malaria parasites require a mosquito vector or direct blood transfer, not soil contamination."}),
]
