"""Additional virus questions: arboviruses/rabies/prions, enteroviruses/noro/rota,
HIV/ART, influenza, measles/mumps/RSV/parainfluenza, and HPV/parvovirus/polyoma/pox."""
from qcore import Q
from tables import *
TAG_RNA = "RNA Viruses"
TAG_HIV = "HIV & Antiretrovirals"
TAG_DNA = "DNA Viruses (Non-Herpes)"

QUESTIONS = [
# ================= Arboviruses, rabies, prions =================
Q(TAG_RNA, "West Nile virus: neuroinvasive disease",
  "A 72-year-old man in late summer develops fever and headache, then over two days progressive weakness of one arm with preserved sensation. CSF shows lymphocytic pleocytosis and IgM against a mosquito-borne flavivirus. Which mechanism distinguishes this illness from Guillain-Barre syndrome?",
  ["Infection of anterior horn motor neurons, sparing sensory pathways",
   "Autoimmune demyelination of peripheral nerve roots after infection",
   "Diffuse cortical infarction from vasculitis of small vessels",
   "Direct viral invasion of the neuromuscular junction endplate",
   "Toxin-mediated blockade of acetylcholine release at synapses"],
  "West Nile virus can produce a poliomyelitis-like syndrome by infecting anterior horn motor neurons, causing asymmetric limb weakness with normal sensation. Guillain-Barre, by contrast, is a post-infectious demyelinating polyradiculoneuropathy with symmetric ascending weakness and sensory involvement. Most West Nile infections are asymptomatic or mild febrile illness; neuroinvasive disease is more common in older or immunosuppressed patients.",
  difficulty="hard",
  why={"Autoimmune demyelination of peripheral": "This describes Guillain-Barre, the diagnosis this presentation is being distinguished from.",
       "Diffuse cortical infarction": "Vasculitic infarction would give cortical deficits, not isolated limb weakness with sparing of sensation.",
       "Direct viral invasion of the neuromuscular junction": "This describes botulinum toxin, which blocks neuromuscular transmission rather than infecting neurons.",
       "Toxin-mediated blockade of acetylcholine": "This describes botulism, a toxin-mediated disease with no CSF pleocytosis."},
  table=None),

Q(TAG_RNA, "Ebola: transmission and containment",
  "During an outbreak in a rural clinic, several health workers who cared for a patient with hemorrhagic fever become ill a week later, while people who only shared a waiting room remain well. Which principle best explains this pattern of spread?",
  ["Transmission requires direct contact with infected blood or secretions",
   "Transmission occurs efficiently through small airborne respiratory droplets",
   "Transmission depends on an intermediate mosquito vector present indoors",
   "Transmission requires weeks of casual proximity in a shared space",
   "Transmission occurs only after the incubation period has fully ended"],
  "Ebola virus spreads through direct contact with the blood, vomitus, or other body fluids of a symptomatic or deceased patient, which is why caregivers and those handling bodies at funerals are at highest risk while casual contacts are not infected. It is not spread efficiently by air or by an insect vector, and patients are not contagious until symptoms begin. Strict barrier precautions and safe burial practices interrupt chains of transmission.",
  why={"Transmission occurs efficiently through small airborne": "Ebola is not an efficient airborne pathogen; large droplet and contact spread predominate.",
       "Transmission depends on an intermediate mosquito vector": "Ebola is not arthropod-borne; fruit bats are the presumed natural reservoir.",
       "Transmission requires weeks of casual proximity": "Casual, non-fluid contact does not transmit the virus even over time.",
       "Transmission occurs only after the incubation period has fully ended": "Patients become contagious once symptoms begin, not only after incubation ends."},
  table=None),

Q(TAG_RNA, "HTLV-1: HAM/TSP",
  "A 50-year-old woman from the Caribbean develops slowly progressive spastic weakness of both legs, urinary urgency, and hyperreflexia over several years, without optic neuritis or relapsing episodes. Serology is positive for a retrovirus transmitted by breastfeeding and blood transfusion. Which condition does this describe?",
  ["HTLV-1-associated myelopathy with chronic lower-limb paraparesis",
   "Multiple sclerosis with a primary progressive course",
   "Subacute combined degeneration from cobalamin deficiency",
   "Tabes dorsalis from tertiary neurosyphilis infection",
   "Guillain-Barre syndrome with an ascending pattern"],
  "HTLV-1 infects CD4 T cells and can cause HTLV-1-associated myelopathy/tropical spastic paraparesis (HAM/TSP), a chronic progressive spastic paraparesis with bladder dysfunction, most common in endemic areas of the Caribbean, Japan, and Africa. Unlike multiple sclerosis, it lacks relapsing-remitting episodes and optic involvement, and serology confirms HTLV-1. The same virus can instead cause adult T-cell leukemia/lymphoma in a minority of carriers.",
  difficulty="hard",
  why={"Multiple sclerosis with a primary progressive": "MS typically shows white matter lesions on MRI and often optic or relapsing features, and does not require HTLV-1 serology.",
       "Subacute combined degeneration from cobalamin": "This presents with dorsal column loss and peripheral neuropathy from vitamin B12 deficiency, not retroviral serology.",
       "Tabes dorsalis from tertiary neurosyphilis": "Tabes dorsalis causes sensory ataxia and lightning pains with positive syphilis serology, not HTLV-1.",
       "Guillain-Barre syndrome with an ascending": "GBS is acute and monophasic, not slowly progressive over years."},
  table=None),

Q(TAG_RNA, "Creutzfeldt-Jakob disease: diagnostic pearls",
  "A 65-year-old develops rapidly progressive dementia over two months along with myoclonic jerks triggered by startle. An EEG shows periodic sharp wave complexes, and CSF is positive for 14-3-3 protein. Which of the following is the most likely diagnosis?",
  ["Sporadic Creutzfeldt-Jakob disease",
   "Herpes simplex encephalitis",
   "Lewy body dementia with hallucinations",
   "Normal pressure hydrocephalus",
   "Paraneoplastic limbic encephalitis"],
  "Sporadic Creutzfeldt-Jakob disease presents with rapidly progressive dementia and myoclonus over weeks to months. Supportive findings include periodic sharp wave complexes on EEG, elevated CSF 14-3-3 protein (a marker of neuronal injury), and cortical ribboning with basal ganglia hyperintensity on diffusion-weighted MRI. It results from accumulation of the misfolded, protease-resistant prion protein PrPsc.",
  difficulty="medium",
  why={"Herpes simplex encephalitis": "HSV encephalitis causes fever and temporal lobe findings, with PCR-positive CSF, rather than periodic sharp waves and 14-3-3 elevation.",
       "Lewy body dementia with hallucinations": "This progresses over years with visual hallucinations and parkinsonism, far more slowly than CJD.",
       "Normal pressure hydrocephalus": "This classically causes gait apraxia, incontinence, and dementia with ventriculomegaly, not myoclonus or periodic EEG discharges.",
       "Paraneoplastic limbic encephalitis": "This usually evolves over weeks with prominent memory and psychiatric symptoms and antineuronal antibodies, not the EEG pattern described."},
  table=None),

# ================= Enteroviruses, rhinovirus, norovirus, rotavirus =================
Q(TAG_RNA, "Coxsackie A: herpangina",
  "A 4-year-old has abrupt fever, sore throat, and painful small vesicles and ulcers confined to the soft palate, tonsillar pillars, and uvula, with no lesions on the hands or feet. Which virus is the most likely cause?",
  ["Coxsackievirus A",
   "Herpes simplex virus type 1",
   "Coxsackievirus B",
   "Adenovirus",
   "Epstein-Barr virus"],
  "Herpangina, caused mainly by coxsackievirus A, produces painful vesicular lesions limited to the posterior oropharynx (soft palate, uvula, tonsillar pillars), sparing the anterior mouth, hands, and feet. This distinguishes it from hand-foot-mouth disease, which also involves the palms, soles, and buccal mucosa. Both are self-limited fecal-oral enteroviral infections most common in summer and fall.",
  difficulty="easy",
  why={"Herpes simplex virus type 1": "Primary HSV gingivostomatitis involves the anterior gums, lips, and buccal mucosa, not just the posterior pharynx.",
       "Coxsackievirus B": "Coxsackie B favors myocarditis, pericarditis, and pleurodynia rather than herpangina.",
       "Adenovirus": "Adenovirus causes pharyngoconjunctival fever with exudative pharyngitis and conjunctivitis, not isolated posterior vesicles.",
       "Epstein-Barr virus": "EBV pharyngitis has exudative tonsillitis and lymphadenopathy without discrete vesicles."},
  table=None),

Q(TAG_RNA, "Echovirus: neonatal sepsis-like illness",
  "A 6-day-old infant develops fever, poor feeding, and lethargy. Blood and CSF cultures show no bacterial growth, but CSF PCR detects an enterovirus. The mother had a mild febrile illness just before delivery. Which feature is most characteristic of this infection in neonates?",
  ["It can produce severe disease with irritability and hepatitis",
   "It causes a chronic latent infection reactivating in adulthood",
   "It is transmitted only through respiratory droplets after birth",
   "It produces a vesicular rash limited to a single dermatome",
   "It requires no supportive care because it never becomes severe"],
  "Echoviruses (and other non-polio enteroviruses) can cause severe neonatal disease acquired perinatally, presenting with a sepsis-like picture of fever, irritability, and sometimes hepatitis, myocarditis, or coagulopathy that mimics bacterial infection. Diagnosis relies on enterovirus PCR of blood or CSF since bacterial cultures are negative. Management is supportive, as no specific antiviral is routinely used.",
  difficulty="medium",
  why={"It causes a chronic latent infection reactivating": "Enteroviruses do not establish the kind of latency seen with herpesviruses.",
       "It is transmitted only through respiratory droplets": "Perinatal transmission occurs from maternal blood, secretions, or stool around delivery, not only by respiratory droplets afterward.",
       "It produces a vesicular rash limited to a single dermatome": "A dermatomal vesicular rash describes herpes zoster, not enteroviral sepsis.",
       "It requires no supportive care because it never becomes severe": "Neonatal enterovirus infection can be severe and even fatal, requiring supportive intensive care."},
  table=None),

Q(TAG_RNA, "Poliovirus: vaccine-derived strains",
  "In a region with low vaccination coverage that still uses oral polio vaccine, several children develop acute flaccid paralysis. Genetic sequencing shows the isolate is related to the vaccine strain but has regained neurovirulence. What does this represent?",
  ["Circulating vaccine-derived poliovirus reverting after prolonged spread",
   "A laboratory contamination event entirely unrelated to community transmission",
   "A wholly new wild poliovirus serotype never used in any vaccine",
   "An adverse reaction confined to the vaccinated child alone",
   "A bacterial coinfection producing a similar paralytic illness"],
  "The live attenuated oral polio vaccine can, in under-immunized populations, be transmitted person to person through fecal-oral spread long enough to revert point mutations and regain neurovirulence, producing circulating vaccine-derived poliovirus outbreaks. This is one reason many countries have shifted to inactivated polio vaccine, which cannot revert because it contains no live virus. High vaccination coverage prevents the sustained transmission this requires.",
  difficulty="hard",
  why={"A laboratory contamination event entirely unrelated": "The scenario describes community transmission and reversion, not a laboratory error.",
       "A wholly new wild poliovirus serotype never used": "The isolate is genetically related to the vaccine strain, not an unrelated wild serotype.",
       "An adverse reaction confined to the vaccinated child": "Multiple children are affected through onward community spread, not an isolated reaction.",
       "A bacterial coinfection producing a similar paralytic": "The paralysis is caused by the poliovirus isolate itself, not a separate bacterial process."},
  table=None),

Q(TAG_RNA, "Coxsackie B: pleurodynia",
  "A 30-year-old man has sudden severe stabbing chest and upper abdominal pain that worsens with breathing and coughing, along with fever and headache, lasting several days and then resolving completely. Cardiac enzymes and ECG are normal. Which virus is most likely responsible?",
  ["Coxsackievirus B",
   "Coxsackievirus A",
   "Rhinovirus",
   "Respiratory syncytial virus",
   "Adenovirus"],
  "Coxsackievirus B causes epidemic pleurodynia (Bornholm disease), an illness of sudden pleuritic chest and abdominal wall pain from myositis of the intercostal and diaphragmatic muscles, typically self-limited over several days. The same virus family also causes myocarditis and aseptic meningitis, so cardiac and neurologic evaluation is reasonable, but the normal enzymes and ECG here support pleurodynia rather than myocarditis.",
  difficulty="medium",
  why={"Coxsackievirus A": "Coxsackie A is more associated with herpangina and hand-foot-mouth disease than pleurodynia.",
       "Rhinovirus": "Rhinovirus causes upper respiratory symptoms, not pleuritic muscle pain.",
       "Respiratory syncytial virus": "RSV mainly causes bronchiolitis and pneumonia in infants, not pleurodynia in adults.",
       "Adenovirus": "Adenovirus more typically causes pharyngoconjunctival fever or pneumonia, not this pattern of chest wall pain."},
  table=None),

Q(TAG_RNA, "Rotavirus: stool diagnosis and secondary lactose intolerance",
  "An 8-month-old with watery diarrhea and vomiting has a stool sample sent for testing, which is positive by antigen immunoassay for a naked, segmented double-stranded RNA virus. After the acute illness resolves, the infant develops loose stools whenever given milk. What explains the persistent symptom?",
  ["Villous tip destruction causing transient secondary lactase deficiency",
   "Chronic carriage of live virus shed continuously in the stool",
   "An allergic reaction to cow's milk protein triggered by the recent infection",
   "Bacterial overgrowth of the small intestine following the illness",
   "Permanent destruction of pancreatic acinar cells by the virus"],
  "Rotavirus infects and destroys the villous tips of small bowel enterocytes, where brush-border lactase is located, producing a temporary secondary lactose intolerance that resolves as the mucosa regenerates over one to two weeks. Antigen immunoassay of stool is a rapid way to confirm the naked, segmented double-stranded RNA virus. Management is supportive rehydration; a temporary lactose-reduced diet can help in symptomatic infants.",
  difficulty="medium",
  why={"Chronic carriage of live virus shed continuously": "Rotavirus shedding declines after the acute illness and does not explain a milk-specific symptom.",
       "An allergic reaction to cow's milk protein triggered": "True milk protein allergy is a separate immune process, not the typical mechanism after rotavirus.",
       "Bacterial overgrowth of the small intestine following": "Bacterial overgrowth is not the usual mechanism of post-rotavirus lactose intolerance.",
       "Permanent destruction of pancreatic acinar cells": "Rotavirus damages the intestinal brush border, not the pancreas, and the effect is temporary, not permanent."},
  table=None),

Q(TAG_RNA, "Norovirus: viral classification and vaccine challenge",
  "Researchers attempting to develop a norovirus vaccine face difficulty because the virus has many antigenically distinct genogroups and genotypes that circulate and change over time. To which virus family does norovirus belong, and how is it typically diagnosed?",
  ["Caliciviridae; diagnosed by RT-PCR of stool",
   "Picornaviridae; diagnosed by routine stool culture",
   "Reoviridae; diagnosed by electron microscopy alone",
   "Adenoviridae; diagnosed by antigen skin testing",
   "Astroviridae; diagnosed by paired acute and convalescent serum"],
  "Norovirus is a non-enveloped, positive-sense single-stranded RNA virus in the Caliciviridae family. It does not grow well in standard cell culture, so diagnosis relies on RT-PCR of stool. Its extensive antigenic diversity and rapid evolution, similar in concept to influenza, are major obstacles to developing a broadly protective vaccine.",
  difficulty="hard",
  why={"Picornaviridae; diagnosed by routine stool culture": "Picornaviridae includes enteroviruses and rhinovirus, and norovirus is not reliably recovered by routine stool culture.",
       "Reoviridae; diagnosed by electron microscopy alone": "Reoviridae includes rotavirus; electron microscopy is not the standard clinical diagnostic method for norovirus today.",
       "Adenoviridae; diagnosed by antigen skin testing": "Adenoviruses are DNA viruses, and there is no antigen skin test used for enteric viral diagnosis.",
       "Astroviridae; diagnosed by paired acute and convalescent serum": "Astrovirus is a distinct, less common cause of gastroenteritis, and paired serology is not how norovirus is diagnosed."},
  table=None),

Q(TAG_RNA, "Rhinovirus: trigger for asthma exacerbation",
  "A 9-year-old with a history of reactive airway disease develops a runny nose and mild sore throat, then two days later has increased wheezing and needs his rescue inhaler far more often. Testing confirms a common cold virus. Which statement about this pathogen is correct?",
  ["It is a leading viral cause of asthma flare-ups in children",
   "It typically causes flare-ups only in children without any atopy",
   "It requires antiviral therapy to prevent progression to pneumonia",
   "It spreads mainly through contaminated water rather than secretions",
   "It is effectively prevented by the seasonal inactivated vaccine"],
  "Rhinovirus is the most frequent viral trigger of asthma and COPD exacerbations, provoking bronchial inflammation and hyperreactivity in susceptible airways even though the primary infection is a mild upper respiratory illness. There is no specific antiviral treatment or vaccine for rhinovirus; management targets the asthma exacerbation itself with bronchodilators and, when indicated, corticosteroids.",
  difficulty="medium",
  why={"It typically causes flare-ups only in children without any atopy": "Rhinovirus-triggered flare-ups are common precisely in atopic, asthmatic children, not limited to non-atopic children.",
       "It requires antiviral therapy to prevent progression to pneumonia": "No specific antiviral is used for rhinovirus, and most infections stay confined to the upper airway.",
       "It spreads mainly through contaminated water rather than secretions": "Rhinovirus spreads through respiratory droplets and contaminated hands or surfaces, not water.",
       "It is effectively prevented by the seasonal inactivated vaccine": "The seasonal inactivated vaccine targets influenza; no rhinovirus vaccine exists because of its many serotypes."},
  table=None),

Q(TAG_RNA, "Enterovirus D68: acute flaccid myelitis",
  "In late summer, a cluster of children develop a respiratory illness with wheezing, and a few days later some develop sudden asymmetric limb weakness with normal sensation and MRI showing gray matter lesions of the spinal cord. Which virus has been linked to these outbreaks?",
  ["Enterovirus D68",
   "Respiratory syncytial virus",
   "Parainfluenza virus type 3",
   "Adenovirus type 7",
   "Human metapneumovirus"],
  "Enterovirus D68 causes seasonal outbreaks of severe respiratory illness, especially wheezing in children, and has been associated with clusters of acute flaccid myelitis, a polio-like illness with asymmetric limb weakness from spinal cord gray matter involvement. Unlike wild poliovirus, EV-D68 is not eliminated by the polio vaccine, and treatment is supportive since no specific antiviral is proven effective.",
  difficulty="hard",
  why={"Respiratory syncytial virus": "RSV causes bronchiolitis and pneumonia but is not the virus linked to these acute flaccid myelitis clusters.",
       "Parainfluenza virus type 3": "Parainfluenza causes croup and bronchiolitis without the described neurologic clusters.",
       "Adenovirus type 7": "Adenovirus can cause severe pneumonia but is not the organism implicated in these outbreaks.",
       "Human metapneumovirus": "This causes bronchiolitis similar to RSV but has not been the described cause of these paralysis clusters."},
  table=None),

# ================= HIV & antiretrovirals =================
Q(TAG_HIV, "HIV: gp41 and fusion inhibitors",
  "A patient with multidrug-resistant HIV is started on a subcutaneously injected drug that prevents the conformational change needed for the viral and cell membranes to merge. Which HIV protein does this drug target?",
  ["gp41",
   "gp120",
   "Reverse transcriptase",
   "Integrase",
   "Protease"],
  "Enfuvirtide is a fusion inhibitor that binds gp41 and blocks the conformational change required for fusion of the viral envelope with the host cell membrane, preventing entry. Because it must be injected subcutaneously twice daily, it is generally reserved for heavily treatment-experienced patients with resistance to other classes.",
  difficulty="hard",
  why={"gp120": "gp120 mediates initial binding to CD4 and a coreceptor, which is instead blocked by CCR5 antagonists.",
       "Reverse transcriptase": "Reverse transcriptase is targeted by NRTIs and NNRTIs, not fusion inhibitors.",
       "Integrase": "Integrase is targeted by drugs such as dolutegravir, acting after entry.",
       "Protease": "Protease inhibitors act on viral maturation, a step after entry and integration."},
  table=None),

Q(TAG_HIV, "HIV: tenofovir nephrotoxicity",
  "A patient on a tenofovir disoproxil fumarate-containing regimen develops glucosuria and phosphaturia with normal serum glucose, along with a rising creatinine. Which process explains these findings?",
  ["Proximal tubular dysfunction resembling Fanconi syndrome",
   "Immune complex deposition causing membranous nephropathy",
   "Crystal formation obstructing the distal collecting ducts",
   "Direct hemolysis releasing hemoglobin into the tubules",
   "Rhabdomyolysis with myoglobin-induced tubular injury"],
  "Tenofovir disoproxil fumarate can cause proximal renal tubular dysfunction resembling Fanconi syndrome, with glucosuria despite normal blood glucose, phosphate wasting, and a rise in creatinine, along with reduced bone mineral density. Tenofovir alafenamide achieves similar antiviral activity with lower plasma tenofovir levels and less renal and bone toxicity.",
  difficulty="medium",
  why={"Immune complex deposition causing membranous": "Membranous nephropathy is not the typical tenofovir toxicity pattern.",
       "Crystal formation obstructing the distal": "Tubular injury here reflects direct proximal tubular toxicity, not distal crystal obstruction.",
       "Direct hemolysis releasing hemoglobin": "Tenofovir is not associated with hemolysis.",
       "Rhabdomyolysis with myoglobin-induced": "Myopathy with rhabdomyolysis is more characteristic of other drug classes, not this tenofovir pattern."},
  table=None),

Q(TAG_HIV, "HIV: protease inhibitor metabolic effects",
  "A patient started on a ritonavir-boosted protease inhibitor develops truncal fat accumulation, peripheral fat loss, and elevated triglycerides and LDL cholesterol after several months. Why is ritonavir included at a low dose in this regimen?",
  ["It inhibits CYP3A4 to raise blood levels of the companion drug",
   "It independently suppresses viral replication at the dose used",
   "It reverses the lipid abnormalities caused by the other drug",
   "It prevents the development of integrase strand transfer resistance",
   "It blocks renal tubular secretion to extend the drug's half-life"],
  "Low-dose ritonavir is used as a pharmacologic booster because it potently inhibits hepatic CYP3A4, raising and prolonging plasma levels of the coadministered protease inhibitor so it can be dosed less frequently. Protease inhibitors as a class are linked to lipodystrophy, dyslipidemia, and insulin resistance, which ritonavir does not treat or prevent.",
  difficulty="medium",
  why={"It independently suppresses viral replication at the dose": "At the low booster dose, ritonavir contributes little direct antiviral activity.",
       "It reverses the lipid abnormalities caused by the other": "Ritonavir itself worsens, rather than reverses, dyslipidemia.",
       "It prevents the development of integrase strand transfer": "Boosting affects drug metabolism, not resistance to an unrelated drug class.",
       "It blocks renal tubular secretion to extend the drug's": "The mechanism is hepatic enzyme inhibition, not renal tubular secretion."},
  table=None),

Q(TAG_HIV, "HIV: window period marker sequence",
  "A person with a high-risk exposure ten days ago wants to know the earliest marker that could detect infection if it has occurred. Which marker becomes detectable first after HIV transmission?",
  ["Plasma HIV RNA",
   "p24 antigen",
   "IgM antibody to HIV",
   "IgG antibody to HIV",
   "CD4 lymphocyte decline"],
  "After transmission, plasma HIV RNA becomes detectable first, often within about ten days, followed roughly a week later by p24 antigen, and then by antibodies (IgM before IgG) over the following weeks. CD4 decline is a chronic marker of disease progression, not an early diagnostic clue. This sequence is the basis for nucleic acid testing during the earliest acute window period.",
  difficulty="hard",
  why={"p24 antigen": "p24 antigen appears somewhat later than plasma RNA, once viral protein accumulates to detectable levels.",
       "IgM antibody to HIV": "IgM appears only after RNA and antigen, once the immune response begins generating antibody.",
       "IgG antibody to HIV": "IgG is the last of these markers to appear, often weeks after exposure.",
       "CD4 lymphocyte decline": "CD4 decline occurs gradually over the course of untreated disease, not as an early window-period marker."},
  table=None),

Q(TAG_HIV, "HIV: baseline resistance genotyping",
  "Before starting antiretroviral therapy in a newly diagnosed, treatment-naive patient, the clinician orders a genotypic test looking for drug-relevant mutations. What is the main purpose of this test at this point in care?",
  ["To detect viral variants transmitted from another host that affect drug choice",
   "To measure the absolute CD4 count for staging the underlying disease",
   "To confirm the diagnosis in place of an antibody or RNA screening test used earlier",
   "To determine whether the patient instead qualifies for PrEP now",
   "To identify a coreceptor switch before starting any nucleoside analog"],
  "Baseline genotypic resistance testing before starting therapy detects mutations transmitted from a resistant source, which can occur even in people who have never taken antiretrovirals, and guides selection of a fully active initial regimen. It is not used to diagnose HIV, stage disease, or replace tropism testing, which is a separate assay performed specifically before starting a CCR5 antagonist.",
  difficulty="medium",
  why={"To measure the absolute CD4 count for staging": "CD4 count is measured by flow cytometry, a separate test from genotypic resistance testing.",
       "To confirm the diagnosis in place of an antibody": "Diagnosis relies on antigen/antibody or RNA testing, not resistance genotyping.",
       "To determine whether the patient instead qualifies for PrEP": "PrEP is pre-exposure prophylaxis for uninfected patients and is irrelevant once HIV is diagnosed.",
       "To identify a coreceptor switch before starting any nucleoside": "Tropism testing, a separate assay, is needed only before starting a CCR5 antagonist, not nucleoside drugs."},
  table=None),

Q(TAG_HIV, "HIV: breastfeeding and vertical transmission",
  "A woman with HIV on fully suppressive antiretroviral therapy asks whether she can breastfeed her newborn. In a well-resourced setting with reliable access to formula, which statement best reflects current guidance?",
  ["Formula feeding is recommended because breastfeeding still carries some transmission risk",
   "Breastfeeding is completely safe and carries no risk once viral load is undetectable",
   "Breastfeeding is required because formula feeding is more likely to transmit infection to the infant",
   "Breastfeeding transmits the virus only if the mother develops mastitis",
   "Formula feeding is discouraged because it increases the infant's HIV risk"],
  "Even with maternal viral suppression, breastfeeding carries a small residual risk of transmission through breast milk, so in settings where safe, affordable formula is reliably available, formula feeding is recommended to eliminate that risk. In resource-limited settings where formula feeding carries its own mortality risks from malnutrition and unsafe water, breastfeeding with maternal ART is instead favored because it reduces transmission substantially compared with no treatment.",
  difficulty="medium",
  why={"Breastfeeding is completely safe and carries no risk": "Suppression greatly reduces but does not eliminate the small transmission risk through breast milk.",
       "Breastfeeding is required because formula feeding is more": "Formula itself does not transmit HIV; the guidance favors formula specifically where it can be prepared safely.",
       "Breastfeeding transmits the virus only if the mother develops mastitis": "Mastitis raises the risk further, but transmission can occur through breast milk even without it.",
       "Formula feeding is discouraged because it increases the infant's": "Formula feeding does not raise HIV risk; any downside relates to nutrition and water safety in low-resource settings."},
  table=None),

Q(TAG_HIV, "HIV: CMV retinitis at low CD4 count",
  "A patient with HIV and a CD4 count of 40 cells/µL reports painless floaters and blurred vision in one eye. Fundoscopic exam shows perivascular hemorrhages and yellow-white granular retinal infiltrates. Which organism is most likely responsible?",
  ["Cytomegalovirus",
   "Toxoplasma gondii",
   "Varicella-zoster virus",
   "Candida albicans",
   "Cryptococcus neoformans"],
  "CMV retinitis occurs almost exclusively at very low CD4 counts, typically below 50 cells/µL, and produces a characteristic 'pizza pie' fundus appearance with hemorrhages and fluffy white infiltates along the retinal vessels, threatening vision if untreated. It is treated with ganciclovir or valganciclovir, and immune reconstitution with antiretroviral therapy is essential to prevent recurrence.",
  difficulty="medium",
  why={"Toxoplasma gondii": "Ocular toxoplasmosis causes focal necrotizing retinochoroiditis, more often with vitreous inflammation, and is less strictly tied to CD4 below 50.",
       "Varicella-zoster virus": "VZV can cause progressive outer retinal necrosis, a rapidly destructive but less common pattern than CMV retinitis.",
       "Candida albicans": "Candida endophthalmitis usually follows fungemia or intravenous drug use rather than advanced HIV alone.",
       "Cryptococcus neoformans": "Cryptococcus more typically causes meningitis in advanced HIV rather than this retinal appearance."},
  table=None),

Q(TAG_HIV, "HIV: Kaposi sarcoma and HHV-8",
  "A patient with HIV and a low CD4 count has several violaceous, non-blanching plaques on the skin and palate. Biopsy shows spindle cells and slit-like vascular spaces. Which virus is necessary for this tumor to develop?",
  ["Human herpesvirus 8",
   "Epstein-Barr virus",
   "Human papillomavirus",
   "Human herpesvirus 6",
   "JC virus"],
  "Kaposi sarcoma is caused by human herpesvirus 8 (KSHV), which infects endothelial cells and drives proliferation of spindle cells forming vascular channels, producing violaceous cutaneous and mucosal plaques or nodules. It occurs at any CD4 count but is more extensive with advanced immunosuppression, and antiretroviral therapy alone can induce regression in many patients.",
  difficulty="easy",
  why={"Epstein-Barr virus": "EBV is linked to Burkitt lymphoma, nasopharyngeal carcinoma, and hairy leukoplakia, not Kaposi sarcoma.",
       "Human papillomavirus": "HPV causes squamous lesions such as warts and cervical dysplasia, not vascular spindle-cell tumors.",
       "Human herpesvirus 6": "HHV-6 causes roseola infantum and can reactivate in transplant patients, but it does not cause Kaposi sarcoma.",
       "JC virus": "JC virus causes progressive multifocal leukoencephalopathy, a demyelinating brain disease, not a vascular skin tumor."},
  table=None),

# ================= Influenza =================
Q(TAG_RNA, "Influenza: viral structure and genome",
  "An orthomyxovirus isolated from a patient's nasal swab has a segmented, negative-sense single-stranded RNA genome enclosed in a lipid envelope studded with two distinct surface glycoproteins. Which family of viruses does this describe?",
  ["Influenza virus",
   "Rhinovirus",
   "Rotavirus",
   "Adenovirus",
   "Coronavirus"],
  "Influenza viruses are enveloped orthomyxoviruses with a segmented, negative-sense single-stranded RNA genome (eight segments for influenza A and B), studded with hemagglutinin and neuraminidase spikes. The segmented genome allows reassortment when two strains infect the same cell, which underlies antigenic shift.",
  difficulty="easy",
  why={"Rhinovirus": "Rhinovirus is a non-enveloped picornavirus with a single, non-segmented positive-sense RNA genome.",
       "Rotavirus": "Rotavirus is non-enveloped with a segmented double-stranded RNA genome, not single-stranded.",
       "Adenovirus": "Adenovirus is a non-enveloped virus with a double-stranded DNA genome.",
       "Coronavirus": "Coronavirus is enveloped but has a single, non-segmented positive-sense RNA genome."},
  table=None),

Q(TAG_RNA, "Influenza: hemagglutinin function",
  "Which statement correctly describes the function of the influenza hemagglutinin protein during infection?",
  ["It binds sialic acid receptors on respiratory epithelium to mediate entry",
   "It cleaves sialic acid to release newly formed virions from the host cell surface",
   "It reverse transcribes the viral RNA genome into complementary DNA",
   "It assembles progeny genome segments into a functional virion core",
   "It suppresses interferon signaling within the infected host cell"],
  "Hemagglutinin binds sialic acid residues on the surface of respiratory epithelial cells, mediating viral attachment and subsequent fusion and entry. Antibodies against hemagglutinin are the main target of protective immunity and the basis for most vaccine formulations, which is why antigenic changes in hemagglutinin drive the need for updated vaccines.",
  difficulty="medium",
  why={"It cleaves sialic acid to release newly formed virions": "That function belongs to neuraminidase, which releases budding virions from the cell surface.",
       "It reverse transcribes the viral RNA genome into": "Influenza uses an RNA-dependent RNA polymerase, not reverse transcriptase, and this is not hemagglutinin's role.",
       "It assembles progeny genome segments into a functional": "Genome packaging involves other viral proteins, not hemagglutinin.",
       "It suppresses interferon signaling within the infected host": "Interferon antagonism is mediated by nonstructural protein NS1, not hemagglutinin."},
  table=None),

Q(TAG_RNA, "Influenza: neuraminidase function",
  "Oseltamivir and zanamivir both inhibit an influenza surface enzyme. What does this enzyme normally do during the viral life cycle?",
  ["Cleaves sialic acid so newly formed virions can detach and spread",
   "Binds sialic acid receptors to initiate attachment and cell entry",
   "Copies the negative-sense genome into new viral RNA segments",
   "Cleaves the host cell membrane to allow viral fusion and entry",
   "Packages the eight genome segments into an assembling virion"],
  "Neuraminidase cleaves sialic acid residues on the host cell surface and on newly made viral glycoproteins, preventing aggregation and allowing progeny virions to detach and spread to new cells. Neuraminidase inhibitors block this step, trapping newly formed virus at the cell surface and limiting spread within the respiratory tract.",
  difficulty="medium",
  why={"Binds sialic acid receptors to initiate attachment": "Receptor binding for entry is the role of hemagglutinin, not neuraminidase.",
       "Copies the negative-sense genome into new viral RNA": "Genome replication is carried out by the viral RNA-dependent RNA polymerase.",
       "Cleaves the host cell membrane to allow viral fusion": "Membrane fusion during entry is mediated by hemagglutinin after a conformational change, not by neuraminidase.",
       "Packages the eight genome segments into an assembling": "Segment packaging involves specific packaging signals and other viral proteins, not neuraminidase."},
  table=None),

Q(TAG_RNA, "Influenza: reassortment and the mixing vessel",
  "Pigs are often described as a 'mixing vessel' for novel pandemic influenza strains because their respiratory epithelium expresses receptors recognized by both avian and human influenza viruses. What can result when both strains infect the same pig cell?",
  ["Reassortment of genome segments creating a new antigenic subtype",
   "Simple point mutation of hemagglutinin producing seasonal drift",
   "Complete inactivation of both viruses through viral interference",
   "Transfer of drug resistance genes through bacterial conjugation",
   "Formation of a stable latent reservoir within the pig's neurons"],
  "Because influenza has a segmented genome, coinfection of a single cell by two different strains, such as an avian and a human virus, allows whole genome segments to reassort into a novel combination. If this hybrid virus acquires a hemagglutinin the human population has no immunity to while retaining the ability to transmit efficiently between people, it can trigger a pandemic. This differs from antigenic drift, which involves gradual point mutations rather than segment exchange.",
  difficulty="medium",
  why={"Simple point mutation of hemagglutinin producing seasonal": "Point mutation describes antigenic drift, a distinct and more gradual process than segment reassortment.",
       "Complete inactivation of both viruses through viral": "Viral interference can occur in some settings but is not the mechanism underlying pandemic emergence.",
       "Transfer of drug resistance genes through bacterial conjugation": "Conjugation is a bacterial process and is unrelated to how influenza viruses exchange genetic material.",
       "Formation of a stable latent reservoir within the pig's neurons": "Influenza does not establish this kind of neuronal latency; pigs serve as a site of coinfection and reassortment, not viral dormancy."},
  table=None),

Q(TAG_RNA, "Influenza: classic presentation versus the common cold",
  "A 28-year-old develops abrupt onset of fever to 39.5°C, severe myalgias, headache, and a dry cough, feeling too unwell to get out of bed. A coworker with a common cold has had three days of gradually worsening nasal congestion and sore throat without fever. Which feature best distinguishes the first illness as influenza?",
  ["Sudden fever and body aches out of proportion to nasal symptoms",
   "A gradual rise in nasal congestion over several days without fever",
   "A mild sore throat that resolves quickly without other symptoms",
   "A complete absence of cough throughout the entire illness course",
   "Symptoms that stay confined to the nose and throat alone"],
  "Influenza classically causes an abrupt onset of high fever, severe myalgia, headache, and malaise, often out of proportion to modest respiratory symptoms, whereas rhinovirus colds develop gradually with predominant nasal congestion, sneezing, and sore throat and little or no fever in adults. This clinical distinction is imperfect, but the abruptness and severity of systemic symptoms favor influenza.",
  difficulty="easy",
  why={"A gradual rise in nasal congestion over several days": "This gradual, congestion-predominant pattern is more typical of a rhinovirus cold.",
       "A mild sore throat that resolves quickly without other": "Isolated mild sore throat without systemic illness is more typical of a cold than influenza.",
       "A complete absence of cough throughout the entire illness": "Influenza usually does include cough, and its absence would not point toward influenza.",
       "Symptoms that stay confined to the nose and throat alone": "Influenza typically produces prominent systemic symptoms beyond the nose and throat alone."},
  table=None),

Q(TAG_RNA, "Influenza: Reye syndrome and aspirin",
  "A 7-year-old recovering from influenza is given aspirin for fever and several days later develops vomiting, confusion, and elevated liver transaminases without jaundice. Which mechanism underlies this complication?",
  ["Mitochondrial injury causing microvesicular hepatic steatosis and encephalopathy",
   "Direct viral invasion of hepatocytes causing acute fulminant hepatitis",
   "An IgE-mediated hypersensitivity reaction to the aspirin itself",
   "Bacterial superinfection of the liver from a translocated gut organism",
   "Autoimmune destruction of hepatocytes triggered by molecular mimicry"],
  "Reye syndrome is a rare but serious complication linked to aspirin use during viral illnesses, particularly influenza and varicella, in children. It causes mitochondrial dysfunction leading to microvesicular hepatic steatosis, hyperammonemia, and encephalopathy, typically without jaundice. This is why aspirin is avoided for fever in children, with acetaminophen or ibuprofen used instead.",
  difficulty="medium",
  why={"Direct viral invasion of hepatocytes causing acute fulminant": "Reye syndrome is a toxic-metabolic mitochondrial injury linked to aspirin, not direct viral hepatocyte invasion.",
       "An IgE-mediated hypersensitivity reaction to the aspirin": "The mechanism is metabolic mitochondrial toxicity, not an IgE-mediated allergic reaction.",
       "Bacterial superinfection of the liver from a translocated": "There is no bacterial translocation involved in Reye syndrome.",
       "Autoimmune destruction of hepatocytes triggered by molecular": "The injury is toxic-metabolic rather than autoimmune."},
  table=None),

Q(TAG_RNA, "Influenza: biphasic illness and secondary bacterial pneumonia",
  "A 68-year-old man with influenza improves over four days, then develops a new fever, productive cough, and worsening hypoxia on day seven. What does this biphasic pattern most likely indicate?",
  ["A secondary bacterial pneumonia complicating the resolving viral illness",
   "A second, unrelated episode of primary influenza infection",
   "An expected late peak of the original uncomplicated viral illness",
   "A drug fever caused by the antiviral medication he was given",
   "A pulmonary embolism unrelated to the preceding respiratory illness"],
  "A pattern of initial improvement from influenza followed by renewed fever and respiratory decline is the classic signature of secondary bacterial pneumonia, most often from Streptococcus pneumoniae or Staphylococcus aureus, which take advantage of influenza-damaged respiratory epithelium and impaired neutrophil function. Recognizing this biphasic course prompts evaluation for bacterial superinfection and empiric antibacterial therapy while continuing supportive care.",
  difficulty="medium",
  why={"A second, unrelated episode of primary influenza infection": "Reinfection with influenza this soon after the first illness would be unusual and does not explain the abrupt worsening after initial improvement.",
       "An expected late peak of the original uncomplicated viral illness": "Uncomplicated influenza typically improves steadily rather than worsening again after a period of improvement.",
       "A drug fever caused by the antiviral medication he was given": "Antiviral-induced fever is uncommon and would not typically produce worsening hypoxia and productive cough.",
       "A pulmonary embolism unrelated to the preceding respiratory illness": "PE can cause hypoxia but would not typically present with a productive cough and fever in this classic biphasic pattern."},
  table=None),

Q(TAG_RNA, "Influenza: rapid antigen test limitations",
  "A hospitalized patient has a clinical picture strongly suggestive of influenza, but a rapid antigen test from a nasal swab is negative. What is the most appropriate next step?",
  ["Send a nucleic acid amplification test given its higher sensitivity",
   "Conclude that influenza is excluded and search for another cause",
   "Repeat the identical rapid antigen test immediately for confirmation",
   "Begin antibiotics only, since influenza has already been ruled out",
   "Order serologic antibody titers to confirm the diagnosis acutely"],
  "Rapid antigen tests for influenza have only moderate sensitivity, so a negative result in a patient with a compatible clinical picture, especially one sick enough to be hospitalized, does not exclude the diagnosis. Nucleic acid amplification testing (RT-PCR) is far more sensitive and specific and is preferred when the result will change management, such as decisions about antiviral therapy or isolation.",
  difficulty="easy",
  why={"Conclude that influenza is excluded and search for another": "A negative rapid antigen test does not reliably exclude influenza because of its limited sensitivity.",
       "Repeat the identical rapid antigen test immediately for": "Repeating the same insensitive test does not improve diagnostic accuracy the way a more sensitive method would.",
       "Begin antibiotics only, since influenza has already been ruled": "Influenza has not been ruled out by a single negative antigen test, so this conclusion is premature.",
       "Order serologic antibody titers to confirm the diagnosis acutely": "Antibody titers rise over weeks and are not useful for acute diagnosis."},
  table=None),

Q(TAG_RNA, "Influenza: timing of oseltamivir treatment",
  "A previously healthy 35-year-old with two days of typical influenza symptoms asks whether starting oseltamivir now would still help. A hospitalized 80-year-old with five days of severe influenza pneumonia is also being considered for the drug. Which statement about timing is correct?",
  ["Benefit is greatest within 48 hours, but later treatment remains useful in severe disease",
   "The drug provides no benefit whatsoever if started after 48 hours in anyone",
   "The drug must be started within the first six hours of symptom onset to work at all",
   "Timing does not matter because oseltamivir acts by boosting the immune response",
   "Only patients with severe disease qualify for oseltamivir regardless of timing"],
  "Antiviral treatment with a neuraminidase inhibitor such as oseltamivir provides the greatest reduction in symptom duration when started within 48 hours of symptom onset in outpatients. However, hospitalized patients with severe or progressive influenza are still treated even beyond 48 hours, since ongoing viral replication may still be contributing to illness. Outpatient treatment decisions in healthy young adults weigh modest benefit against cost and side effects.",
  difficulty="medium",
  why={"The drug provides no benefit whatsoever if started after": "Some benefit is still expected in severe or hospitalized illness even after 48 hours, so this absolute statement is incorrect.",
       "The drug must be started within the first six hours of symptom": "The commonly cited benefit window is 48 hours, not six hours.",
       "Timing does not matter because oseltamivir acts by boosting": "Oseltamivir works by inhibiting viral neuraminidase directly, not by boosting immune response, and timing does matter.",
       "Only patients with severe disease qualify for oseltamivir": "Outpatients with mild illness can also be treated, particularly those at high risk for complications, so this restriction is incorrect."},
  table=None),

Q(TAG_RNA, "Influenza: zanamivir contraindication",
  "A patient with a history of moderate persistent asthma is diagnosed with influenza and is considering an inhaled neuraminidase inhibitor. Why might this particular antiviral be a poor choice for this patient?",
  ["It can precipitate bronchospasm in patients with underlying airway disease",
   "It is inactivated by inhaled corticosteroids used for asthma control",
   "It requires intravenous administration incompatible with home use",
   "It selectively targets only influenza B and would miss influenza A",
   "It interacts with albuterol to cause dangerous cardiac arrhythmias"],
  "Zanamivir is delivered as a dry powder inhaler and can trigger bronchospasm, so it is generally avoided in patients with asthma or COPD, in whom oral oseltamivir is preferred instead. Both drugs are neuraminidase inhibitors active against influenza A and B; the concern with zanamivir is specific to its inhaled route of delivery.",
  difficulty="medium",
  why={"It is inactivated by inhaled corticosteroids used for asthma": "There is no described inactivation of zanamivir by inhaled corticosteroids.",
       "It requires intravenous administration incompatible with home": "Zanamivir is inhaled, not intravenous; an intravenous neuraminidase inhibitor (peramivir) exists as a separate agent.",
       "It selectively targets only influenza B and would miss influenza": "Zanamivir, like oseltamivir, is active against both influenza A and B.",
       "It interacts with albuterol to cause dangerous cardiac arrhythmias": "No such dangerous interaction with albuterol is described; the concern is direct bronchospasm from the inhaled powder."},
  table=None),

Q(TAG_RNA, "Influenza: M2 inhibitors and resistance",
  "Amantadine and rimantadine block the M2 ion channel of influenza to prevent viral uncoating. Which statement about their current clinical use is correct?",
  ["They are not recommended because resistance in influenza A is now widespread",
   "They remain first-line therapy for both influenza A and influenza B",
   "They are used only for influenza B, which lacks a neuraminidase target",
   "They work by inhibiting viral neuraminidase rather than the M2 channel",
   "They are preferred over oseltamivir because they cause fewer side effects overall"],
  "M2 ion channel blockers act only against influenza A, since influenza B lacks the M2 protein, and are no longer recommended because circulating influenza A strains have widespread resistance to this class. Neuraminidase inhibitors such as oseltamivir and zanamivir, which are active against both influenza A and B, are now preferred first-line agents.",
  difficulty="medium",
  why={"They remain first-line therapy for both influenza A and": "Widespread resistance and lack of influenza B activity mean they are not first-line for either type.",
       "They are used only for influenza B, which lacks a": "The opposite is true: these drugs act only on influenza A, which has the M2 channel, and influenza B lacks it.",
       "They work by inhibiting viral neuraminidase rather than the": "Their mechanism is M2 ion channel blockade, not neuraminidase inhibition.",
       "They are preferred over oseltamivir because they cause fewer": "They are avoided, not preferred, due to resistance rather than any side-effect advantage."},
  table=None),

Q(TAG_RNA, "Influenza: live attenuated vaccine contraindications",
  "A pediatrician is deciding between the live attenuated intranasal influenza vaccine and the inactivated injectable vaccine for a 4-year-old with persistent asthma. Which factor should lead to choosing the inactivated vaccine instead?",
  ["Live attenuated vaccine can worsen wheezing in reactive airway disease",
   "Inactivated vaccine provides no protection in children under five",
   "Live attenuated vaccine cannot be given to any child under eighteen",
   "Inactivated vaccine requires a booster dose only in adults, not children",
   "Live attenuated vaccine is contraindicated only in children over age two"],
  "The live attenuated influenza vaccine is contraindicated in children with asthma or recurrent wheezing because it has been associated with increased wheezing episodes, as well as in pregnancy and immunocompromised states. The inactivated injectable vaccine is safe in these groups and is the preferred choice for a child with persistent asthma.",
  difficulty="medium",
  why={"Inactivated vaccine provides no protection in children under": "The inactivated vaccine is approved and effective in young children, including those under five.",
       "Live attenuated vaccine cannot be given to any child under": "The live vaccine is approved for healthy children starting around age two, not restricted to those eighteen and older.",
       "Inactivated vaccine requires a booster dose only in adults, not": "Booster or two-dose priming schedules for young children relate to prior vaccination history, not an adults-only requirement.",
       "Live attenuated vaccine is contraindicated only in children over": "The contraindication in asthma and wheezing applies broadly by underlying condition, not restricted to children over a specific age."},
  table=None),

Q(TAG_RNA, "Influenza: groups at highest risk for complications",
  "During a moderate influenza season, public health officials prioritize certain groups for early vaccination and prompt antiviral treatment if infected. Which group is at the highest risk for severe influenza complications?",
  ["Pregnant women, young children, and adults with chronic lung or heart disease",
   "Healthy adolescents who have never previously received a vaccine",
   "Office workers with no chronic conditions and frequent business travel",
   "Adults with well-controlled seasonal allergic rhinitis alone",
   "College students living in dormitories with no other risk factors"],
  "Pregnant women, young children, older adults, and people with chronic cardiopulmonary disease, diabetes, or immunosuppression are at the highest risk for severe influenza complications such as pneumonia, hospitalization, and death, and are prioritized for vaccination and prompt antiviral therapy. Congregate living settings like dormitories increase transmission risk but do not by themselves confer the same degree of complication risk as these underlying host factors.",
  difficulty="easy",
  why={"Healthy adolescents who have never previously received a": "Lack of prior vaccination increases susceptibility to infection but does not by itself place a healthy adolescent in the highest complication-risk category.",
       "Office workers with no chronic conditions and frequent business": "Travel increases exposure risk but does not confer the same complication risk as chronic disease or extremes of age.",
       "Adults with well-controlled seasonal allergic rhinitis alone": "Well-controlled allergic rhinitis alone is not considered a major risk factor for severe influenza.",
       "College students living in dormitories with no other risk": "Congregate housing raises transmission risk but is not itself a host risk factor for severe complications."},
  table=None),

Q(TAG_RNA, "Influenza: avian influenza transmission",
  "Several poultry farm workers develop severe pneumonia after prolonged contact with sick birds during an outbreak of H5N1 avian influenza, while their family members without direct bird contact remain well. Which statement best describes the epidemiology of this strain?",
  ["Transmission occurs mainly through animal contact, not sustained human spread",
   "Transmission occurs efficiently and sustainably from person to person",
   "Transmission requires a mosquito vector present on the farm",
   "Transmission is prevented entirely by existing seasonal influenza vaccines each year",
   "Transmission occurs equally well through casual, non-occupational contact"],
  "Highly pathogenic avian influenza strains such as H5N1 are transmitted primarily from infected birds to humans through close contact with sick or dead poultry, and human-to-human transmission remains rare and inefficient, which is why household contacts without direct bird exposure generally stay well. The concern for pandemic potential lies in the possibility that reassortment or mutation could eventually allow efficient human-to-human spread.",
  difficulty="medium",
  why={"Transmission occurs efficiently and sustainably from person": "Current avian influenza strains have not achieved efficient sustained human-to-human transmission, which is the pattern this vignette illustrates.",
       "Transmission requires a mosquito vector present on the farm": "Avian influenza spreads through respiratory secretions and contact with infected birds, not by an insect vector.",
       "Transmission is prevented entirely by existing seasonal influenza": "Seasonal vaccines target circulating human strains and do not reliably protect against a distinct avian subtype.",
       "Transmission occurs equally well through casual, non-occupational": "The pattern described, illness in exposed workers but not unexposed family, argues against equally efficient casual transmission."},
  table=None),

Q(TAG_RNA, "Influenza B versus influenza A",
  "Public health surveillance data show that one influenza type causes seasonal epidemics but has never caused a pandemic and disproportionately affects children, while the other type undergoes reassortment and has caused pandemics. Which statement correctly distinguishes the two?",
  ["Influenza B does not undergo antigenic shift because it lacks an animal reservoir",
   "Influenza A causes milder disease overall and mainly affects school-age children each year",
   "Influenza B has caused every major pandemic recorded in the last century",
   "Influenza A cannot undergo antigenic drift, only antigenic shift",
   "Influenza B has an equally broad range of animal reservoirs as influenza A"],
  "Influenza A infects a wide range of animal hosts, including birds and pigs, which allows reassortment (antigenic shift) and has produced every influenza pandemic. Influenza B circulates mainly in humans and lacks this animal reservoir, so it undergoes only antigenic drift and never shift, and it tends to disproportionately affect children while generally causing less severe epidemics than influenza A.",
  difficulty="medium",
  why={"Influenza A causes milder disease overall and mainly affects": "Influenza A is generally associated with more severe disease and broader age impact, and influenza B is the one more associated with pediatric predominance.",
       "Influenza B has caused every major pandemic recorded in the last": "Every recorded pandemic has been caused by influenza A, not influenza B.",
       "Influenza A cannot undergo antigenic drift, only antigenic shift": "Influenza A undergoes both drift and shift; it is influenza B that is limited to drift alone.",
       "Influenza B has an equally broad range of animal reservoirs as": "Influenza B lacks the extensive animal reservoirs of influenza A, which is exactly why it cannot undergo shift."},
  table=None),

# ================= Measles, mumps, RSV, parainfluenza =================
Q(TAG_RNA, "Measles: MMR vaccine and pregnancy",
  "A woman planning to conceive is found to be non-immune to measles on prenatal screening. Her physician recommends vaccination now with a specific precaution. What is that precaution?",
  ["Avoid conception for at least one month after receiving the live vaccine",
   "Receive the vaccine only during the second trimester of pregnancy",
   "Combine the vaccine with a course of prophylactic antiviral therapy",
   "Delay vaccination until after delivery regardless of exposure risk",
   "Receive a double dose of vaccine to ensure adequate antibody titers"],
  "MMR is a live attenuated vaccine and is contraindicated during pregnancy because of a theoretical risk to the fetus, so women should avoid becoming pregnant for at least one month after vaccination and should not be vaccinated once pregnancy has begun. Non-immune pregnant women who are exposed to measles can instead receive immune globulin for post-exposure protection.",
  difficulty="medium",
  why={"Receive the vaccine only during the second trimester of": "Live vaccines are avoided throughout pregnancy, not merely restricted to a specific trimester.",
       "Combine the vaccine with a course of prophylactic antiviral": "There is no antiviral routinely paired with MMR vaccination.",
       "Delay vaccination until after delivery regardless of exposure": "The recommendation for a woman planning conception is to vaccinate beforehand, not to delay until after delivery.",
       "Receive a double dose of vaccine to ensure adequate antibody": "A double dose is not part of standard practice; the key precaution is timing relative to conception."},
  table=None),

Q(TAG_RNA, "Measles: giant cell pneumonia in immunocompromised patients",
  "A child with acute lymphoblastic leukemia develops progressive respiratory failure and diffuse infiltrates on chest imaging weeks after a known measles exposure, without ever developing the typical rash. Lung biopsy shows multinucleated giant cells with viral inclusions. What does this represent?",
  ["Severe measles pneumonitis occurring in a patient with no rash",
   "A typical case of measles with the rash simply overlooked by staff",
   "Superimposed bacterial pneumonia unrelated to the measles exposure",
   "A hypersensitivity pneumonitis triggered by chemotherapy exposure",
   "Cytomegalovirus pneumonitis coincidentally occurring at the same time"],
  "Severely immunocompromised patients, particularly those with impaired cell-mediated immunity such as leukemia patients, can develop measles giant cell (Hecht) pneumonia, a severe and often fatal pneumonitis with multinucleated giant cells containing viral inclusions, frequently without the typical rash because the exanthem depends on an intact immune response. This atypical, rashless presentation can delay recognition of measles as the cause.",
  difficulty="hard",
  why={"A typical case of measles with the rash simply overlooked": "The rash is often genuinely absent in this immunocompromised presentation rather than merely missed by observers.",
       "Superimposed bacterial pneumonia unrelated to the measles": "The biopsy finding of multinucleated giant cells with viral inclusions points to direct measles pneumonitis, not a separate bacterial process.",
       "A hypersensitivity pneumonitis triggered by chemotherapy": "Hypersensitivity pneumonitis would not show giant cells with viral inclusions on biopsy.",
       "Cytomegalovirus pneumonitis coincidentally occurring at the": "CMV can cause pneumonitis in immunocompromised hosts, but the scenario's known exposure and biopsy findings point specifically to measles."},
  table=None),

Q(TAG_RNA, "Mumps: pancreatitis and amylase source",
  "A 10-year-old with parotid swelling develops new abdominal pain and vomiting, and serum amylase is markedly elevated. Which additional test would help determine whether the elevated amylase reflects pancreatic involvement rather than the parotitis alone?",
  ["Serum lipase, which rises specifically with pancreatic injury",
   "Serum creatinine, which rises specifically with parotid injury",
   "Serum bilirubin, which rises specifically with salivary gland injury",
   "Serum ferritin, which rises specifically with viral parotitis",
   "Serum uric acid, which rises specifically with pancreatic injury"],
  "Both the salivary glands and the pancreas produce amylase, so an elevated amylase during mumps parotitis could reflect either source. Serum lipase is more specific to the pancreas, so a concurrently elevated lipase alongside abdominal pain supports true mumps pancreatitis rather than amylase elevation from parotid inflammation alone.",
  difficulty="medium",
  why={"Serum creatinine, which rises specifically with parotid": "Creatinine reflects renal function and is not linked to parotid gland injury.",
       "Serum bilirubin, which rises specifically with salivary gland": "Bilirubin reflects hepatic or hemolytic processes, not salivary gland injury.",
       "Serum ferritin, which rises specifically with viral parotitis": "Ferritin is a nonspecific acute-phase reactant and does not localize to the parotid gland.",
       "Serum uric acid, which rises specifically with pancreatic": "Uric acid is not a specific marker for pancreatic injury."},
  table=None),

Q(TAG_RNA, "RSV: mechanism of bronchiolar obstruction",
  "A 4-month-old with RSV bronchiolitis has diffuse wheezing and hyperinflation on chest imaging. Which process in the small airways best explains the wheezing and air trapping?",
  ["Necrosis of bronchiolar epithelium with mucus plugging the narrow lumen",
   "Bronchospasm from IgE-mediated mast cell degranulation in the airway wall",
   "Fibrous scarring of the bronchioles from chronic inflammatory injury",
   "Eosinophilic infiltration identical to that seen in allergic asthma",
   "Vascular congestion of the bronchial mucosa without epithelial damage"],
  "RSV infects and necroses bronchiolar epithelial cells, provoking sloughing, edema, and excessive mucus production that plugs the narrow airways of infants, producing a ball-valve effect with air trapping, wheezing, and hyperinflation. This differs mechanistically from the IgE-mediated bronchospasm of allergic asthma, even though both present with wheezing.",
  difficulty="medium",
  why={"Bronchospasm from IgE-mediated mast cell degranulation": "This mechanism describes an allergic or asthmatic process, not the epithelial necrosis and mucus plugging typical of RSV bronchiolitis.",
       "Fibrous scarring of the bronchioles from chronic inflammatory": "Fibrous scarring reflects a chronic process, not the acute infectious injury of RSV bronchiolitis.",
       "Eosinophilic infiltration identical to that seen in allergic": "RSV bronchiolitis is characterized by neutrophilic and lymphocytic inflammation with epithelial necrosis, not an eosinophil-predominant allergic pattern.",
       "Vascular congestion of the bronchial mucosa without epithelial": "RSV causes direct epithelial necrosis, not simply vascular congestion with intact epithelium."},
  table=None),

Q(TAG_RNA, "RSV: disease in older adults",
  "A 78-year-old with chronic obstructive pulmonary disease develops cough, wheezing, and hypoxia during winter. Testing reveals RSV rather than influenza. Which statement about RSV in this population is correct?",
  ["It is an underrecognized cause of pneumonia and COPD flares in this group",
   "It causes disease exclusively in infants and essentially never affects older adults",
   "It cannot be diagnosed by any laboratory test available for adult patients",
   "It is always a much milder illness in older adults than in young infants",
   "It has no available vaccine formulation approved for any adult age group"],
  "While RSV is best known as a cause of bronchiolitis in infants, it is increasingly recognized as a significant cause of pneumonia and exacerbations of chronic lung and heart disease in older adults, with morbidity approaching that of influenza in some studies. Vaccines targeting the RSV fusion protein have since been approved for use in older adults to reduce this burden, and RSV can be detected using the same PCR or antigen assays used in children.",
  difficulty="medium",
  why={"It causes disease exclusively in infants and essentially never": "RSV also causes clinically significant disease in older adults, particularly those with underlying cardiopulmonary disease.",
       "It cannot be diagnosed by any laboratory test available for": "The same molecular and antigen tests used in pediatric patients are used to diagnose RSV in adults.",
       "It is always a much milder illness in older adults than in": "RSV can cause severe pneumonia and exacerbations in older adults, comparable in severity to influenza in some cases.",
       "It has no available vaccine formulation approved for any adult": "RSV vaccines have been approved specifically for use in older adults."},
  table=None),

Q(TAG_RNA, "Parainfluenza: viral structure and receptor use",
  "Parainfluenza virus, like measles and mumps, belongs to the paramyxovirus family. Which pair of surface proteins mediates its attachment and membrane fusion?",
  ["Hemagglutinin-neuraminidase and a fusion protein",
   "Hemagglutinin and a separate neuraminidase protein",
   "A single glycoprotein that performs both attachment and fusion",
   "Spike protein and a membrane protein, as in coronaviruses",
   "Capsid protein VP1 mediating both receptor binding and entry"],
  "Parainfluenza virus, a paramyxovirus, uses a combined hemagglutinin-neuraminidase protein for attachment to sialic acid receptors and receptor destruction, paired with a separate fusion (F) protein that mediates merging of the viral envelope with the host cell membrane. This differs from orthomyxoviruses like influenza, which use separate hemagglutinin and neuraminidase proteins rather than a single combined protein.",
  difficulty="hard",
  why={"Hemagglutinin and a separate neuraminidase protein": "This describes influenza virus, an orthomyxovirus with two separate surface proteins rather than a single combined one.",
       "A single glycoprotein that performs both attachment and fusion": "Paramyxoviruses use two distinct proteins, one for attachment and one for fusion, not a single combined glycoprotein.",
       "Spike protein and a membrane protein, as in coronaviruses": "Spike and membrane proteins are characteristic of coronaviruses, an unrelated virus family.",
       "Capsid protein VP1 mediating both receptor binding and entry": "VP1 is a capsid protein of non-enveloped picornaviruses such as poliovirus, not an enveloped paramyxovirus."},
  table=None),

Q(TAG_RNA, "Measles: vitamin A supplementation",
  "In a region with a measles outbreak, health officials recommend vitamin A supplementation for all hospitalized children with the infection, regardless of their baseline nutritional status. What is the rationale for this recommendation?",
  ["It reduces the risk of measles-related mortality and blindness",
   "It directly inhibits viral replication in respiratory epithelium",
   "It prevents transmission of the virus to unvaccinated contacts",
   "It replaces the need for the measles vaccine in future outbreaks",
   "It treats the maculopapular rash and shortens its duration"],
  "The World Health Organization recommends two doses of vitamin A for children with acute measles because it reduces the risk of severe complications, including mortality and corneal damage leading to blindness, particularly in settings where vitamin A deficiency is common. It does not act as a direct antiviral, does not prevent transmission, and does not substitute for vaccination as primary prevention.",
  difficulty="medium",
  why={"It directly inhibits viral replication in respiratory": "Vitamin A does not have a direct antiviral mechanism against measles replication.",
       "It prevents transmission of the virus to unvaccinated contacts": "Vitamin A affects the individual patient's outcome, not the infectiousness of the illness to others.",
       "It replaces the need for the measles vaccine in future outbreaks": "Vaccination remains the primary prevention strategy; vitamin A is a treatment adjunct for those already infected.",
       "It treats the maculopapular rash and shortens its duration": "Vitamin A's benefit relates to reducing severe complications like blindness and death, not shortening the rash itself."},
  table=None),

Q(TAG_RNA, "Measles: distinguishing from rubella",
  "Two children have similar-appearing maculopapular rashes that spread from the head downward. One has had a high fever, cough, coryza, and conjunctivitis for several days before the rash appeared, with tender posterior cervical nodes. The other has had only mild fever with prominent posterior auricular and suboccipital lymphadenopathy and a milder illness overall. Which child most likely has rubella rather than measles?",
  ["The child with a shorter course and swelling behind the ears",
   "The child with several days of cough, coryza, and conjunctivitis",
   "The child with the higher fever and more prolonged prodrome",
   "The child whose rash spread from the head downward over days",
   "The child with tender posterior cervical lymph node swelling"],
  "Rubella typically causes a milder illness than measles, with a shorter prodrome, low-grade fever, and characteristic posterior auricular and suboccipital lymphadenopathy, whereas measles has a several-day prodrome of high fever with the three C's: cough, coryza, and conjunctivitis, often with Koplik spots before the rash. Both produce a cephalocaudal maculopapular rash, so the accompanying systemic features and lymph node pattern are the more useful distinguishing clues.",
  difficulty="medium",
  why={"The child with several days of cough, coryza, and conjunctivitis": "This prodrome of high fever with cough, coryza, and conjunctivitis is classic for measles, not rubella.",
       "The child with the higher fever and more prolonged prodrome": "A higher fever and longer prodrome are more typical of measles than the milder course of rubella.",
       "The child whose rash spread from the head downward over days": "Both measles and rubella can spread cephalocaudally, so this shared feature does not distinguish rubella from measles.",
       "The child with tender posterior cervical lymph node swelling": "Posterior cervical adenopathy is a nonspecific finding shared by several viral illnesses and is not the classic clue distinguishing rubella."},
  table=None),

# ================= HPV, parvovirus, polyomaviruses, poxviruses =================
Q(TAG_DNA, "HPV: viral structure and site of infection",
  "Human papillomavirus is a non-enveloped virus that establishes infection almost exclusively within a specific layer of the epidermis. Which feature best explains why HPV requires microabrasions or trauma to establish infection?",
  ["It must reach and infect proliferating basal keratinocytes to replicate",
   "It requires a lipid envelope that is destroyed by intact skin oils",
   "It needs to bind a receptor expressed only on mature blood vessels",
   "It can only survive within hair follicles below the skin surface",
   "It depends on ultraviolet light exposure to activate its capsid"],
  "HPV is a small, non-enveloped double-stranded DNA virus that specifically infects basal keratinocytes, the proliferating stem-cell layer of the epidermis, which it can only reach through minor breaks or microabrasions in the overlying differentiated squamous layers. Once established, the viral life cycle is tightly linked to keratinocyte differentiation as cells move toward the skin surface.",
  difficulty="medium",
  why={"It requires a lipid envelope that is destroyed by intact": "HPV is non-enveloped, so envelope disruption by skin oils is not a relevant concept here.",
       "It needs to bind a receptor expressed only on mature blood": "HPV infects epidermal keratinocytes rather than vascular endothelium.",
       "It can only survive within hair follicles below the skin": "While follicles can be a route of entry, the defining requirement is access to basal keratinocytes generally, not follicles specifically.",
       "It depends on ultraviolet light exposure to activate its capsid": "HPV infection does not require UV activation of the viral capsid to establish infection."},
  table=None),

Q(TAG_DNA, "Parvovirus B19: hydrops fetalis mechanism",
  "A pregnant woman at 20 weeks gestation develops a mild febrile illness with a lacy rash. Several weeks later, ultrasound shows fetal ascites, pleural effusion, and skin edema. Which mechanism explains this fetal complication?",
  ["Viral destruction of fetal erythroid progenitors causing severe anemia",
   "Transplacental transfer of maternal IgG causing fetal hemolysis",
   "Direct viral infection of the fetal heart valves causing endocarditis in utero",
   "Placental infarction from maternal vasculitis triggered by the virus",
   "Fetal neural tube injury from viral invasion of the developing spine"],
  "Parvovirus B19 binds the P antigen on erythroid progenitor cells and can cross the placenta, destroying fetal red cell precursors and causing severe fetal anemia. This anemia can precipitate high-output cardiac failure with fetal hydrops, manifesting as ascites, pleural or pericardial effusion, and skin edema. Intrauterine transfusion can be lifesaving when hydrops is identified.",
  difficulty="hard",
  why={"Transplacental transfer of maternal IgG causing fetal hemolysis": "This describes an antibody-mediated process resembling hemolytic disease of the newborn, not the direct erythroid progenitor infection caused by parvovirus B19.",
       "Direct viral infection of the fetal heart valves causing": "Parvovirus B19 does not cause fetal endocarditis; cardiac failure here follows from severe anemia rather than valve infection.",
       "Placental infarction from maternal vasculitis triggered by the": "The mechanism is direct viral destruction of fetal erythroid cells, not placental vasculitis and infarction.",
       "Fetal neural tube injury from viral invasion of the developing": "Parvovirus B19 targets erythroid progenitors, not neural tube tissue."},
  table=None),

Q(TAG_DNA, "JC virus: natalizumab and PML risk",
  "A patient with multiple sclerosis on natalizumab develops progressive cognitive decline, weakness, and visual disturbances over several weeks. MRI shows non-enhancing white matter lesions without mass effect. Which factor most directly increased this patient's risk for this complication?",
  ["Use of a monoclonal antibody that impairs immune surveillance of the CNS",
   "Use of a corticosteroid taper that suppressed innate immunity for months",
   "A recent live vaccine that reactivated a latent neurotropic virus",
   "Chronic use of a disease-modifying oral antifungal medication",
   "A prior bone marrow transplant performed for the underlying disease"],
  "Natalizumab, a monoclonal antibody that blocks leukocyte trafficking into the central nervous system by targeting alpha-4 integrin, impairs immune surveillance of the CNS and increases the risk of progressive multifocal leukoencephalopathy from reactivation of latent JC virus, particularly in patients who are JC virus antibody-positive with longer treatment duration. This risk requires monitoring and consideration of drug discontinuation if PML is suspected.",
  difficulty="hard",
  why={"Use of a corticosteroid taper that suppressed innate immunity": "While immunosuppression in general raises PML risk, this patient's risk is specifically tied to natalizumab's mechanism of blocking CNS immune surveillance.",
       "A recent live vaccine that reactivated a latent neurotropic": "Live vaccines are not a described trigger for JC virus reactivation in this setting.",
       "Chronic use of a disease-modifying oral antifungal medication": "Antifungal medications are not linked to JC virus reactivation or PML risk.",
       "A prior bone marrow transplant performed for the underlying": "Bone marrow transplantation is not part of this patient's history or the classic risk factor illustrated here; natalizumab therapy is the relevant exposure."},
  table=None),

Q(TAG_DNA, "Smallpox: vaccinia vaccine complications",
  "Historical smallpox vaccination used live vaccinia virus inoculated into the skin. Which complication was a recognized risk of this vaccine, particularly in people with an underlying skin condition?",
  ["Eczema vaccinatum, a severe disseminated skin infection",
   "Reactivation of latent varicella-zoster virus in a dermatome",
   "A chronic carrier state with lifelong shedding of vaccinia",
   "Progressive multifocal leukoencephalopathy from viral reactivation",
   "Congenital malformation when given during any trimester of pregnancy"],
  "The live vaccinia vaccine against smallpox could cause eczema vaccinatum, a severe and potentially life-threatening disseminated cutaneous vaccinia infection in people with atopic dermatitis or other skin barrier defects, as well as rare myocarditis and pericarditis. These risks are why the vaccine was reserved for at-risk groups such as laboratory workers after disease eradication rather than given routinely.",
  difficulty="medium",
  why={"Reactivation of latent varicella-zoster virus in a dermatome": "Vaccinia is a distinct poxvirus from varicella-zoster and does not reactivate latent VZV.",
       "A chronic carrier state with lifelong shedding of vaccinia": "Vaccinia infection from vaccination is self-limited in immunocompetent people rather than producing lifelong shedding.",
       "Progressive multifocal leukoencephalopathy from viral": "PML is associated with JC virus reactivation, not vaccinia vaccination.",
       "Congenital malformation when given during any trimester of": "The described concern for pregnancy relates more to fetal vaccinia infection risk than classic teratogenic malformation, and the eczema vaccinatum complication is the one tied to skin disease specifically."},
  table=None),

Q(TAG_DNA, "Molluscum contagiosum: Henderson-Patterson bodies",
  "A biopsy of a dome-shaped, umbilicated skin papule shows keratinocytes containing large eosinophilic cytoplasmic inclusions that displace the nucleus to the periphery. Which organism produces this histologic finding?",
  ["Molluscum contagiosum virus",
   "Human papillomavirus",
   "Varicella-zoster virus",
   "Herpes simplex virus",
   "Staphylococcus aureus"],
  "Molluscum contagiosum virus, a poxvirus, produces large cytoplasmic inclusion bodies called Henderson-Patterson (molluscum) bodies within infected keratinocytes, visible as eosinophilic material that pushes the nucleus to the cell periphery. Clinically this produces small, flesh-colored, dome-shaped papules with central umbilication, most common in children and in immunocompromised or sexually active adults.",
  difficulty="easy",
  why={"Human papillomavirus": "HPV produces koilocytes with perinuclear halos, not the discrete cytoplasmic inclusion bodies described here.",
       "Varicella-zoster virus": "VZV produces multinucleated giant cells with Cowdry type A intranuclear inclusions, not cytoplasmic Henderson-Patterson bodies.",
       "Herpes simplex virus": "HSV also produces multinucleated giant cells with intranuclear inclusions rather than the large cytoplasmic bodies described.",
       "Staphylococcus aureus": "A bacterial organism would not produce a characteristic intracytoplasmic viral inclusion body on histology."},
  table=None),
]
