from tables import *
R = {
"Enterobius": dict(d="easy",
  c="Albendazole for the household, repeated in two weeks",
  o={"Praziquantel for the child only": "Praziquantel given to the child only",
     "Metronidazole for the child only": "Metronidazole given to the child only",
     "Ivermectin for the child and a stool": "Ivermectin for the child, with stool ova and parasites",
     "No treatment": "No treatment, since the infection is self-limited"},
  why={"Praziquantel given to the child only": "Praziquantel treats flukes and tapeworms, not pinworm.",
       "Metronidazole given to the child only": "Metronidazole treats protozoa such as Giardia.",
       "Ivermectin for the child, with stool ova and parasites": "Pinworm eggs are rarely found in stool; the tape test is used.",
       "No treatment, since the infection is self-limited": "Autoinfection keeps it going, and household members are often infected."},
  table=NEMATODES),

"Ascaris": dict(d="medium",
  why={"Hematogenous spread of adult worms to the lungs": "Adults stay in the intestine; only larvae migrate.",
       "Allergic bronchopulmonary aspergillosis": "ABPA occurs in asthma and cystic fibrosis, with high IgE and bronchiectasis.",
       "Cysts forming in the lung parenchyma": "Lung cysts suggest echinococcosis or paragonimiasis.",
       "Autoinfection with filariform larvae": "Autoinfection is a Strongyloides feature."},
  table=NEMATODES),

"Strongyloides: hyperinfection": dict(d="hard",
  c="Autoinfection, which steroids allow to run unchecked",
  o={"Its eggs are ingested from soil": "Its eggs are swallowed from soil and obstruct the gut",
     "It is transmitted by blackfly": "It is transmitted through blackfly bites",
     "It forms hydatid cysts": "It forms hydatid cysts within the liver",
     "It is acquired from undercooked pork": "It is acquired by eating undercooked pork"},
  why={"Its eggs are swallowed from soil and obstruct the gut": "That describes Ascaris, which does not autoinfect.",
       "It is transmitted through blackfly bites": "Blackflies transmit Onchocerca.",
       "It forms hydatid cysts within the liver": "Hydatid disease is caused by Echinococcus.",
       "It is acquired by eating undercooked pork": "Pork transmits Taenia solium and Trichinella."},
  table=NEMATODES),

"Hookworm": dict(d="medium",
  c="Adult worms attach to the mucosa and suck blood",
  o={"Larvae invade and lyse red blood cells": "Larvae invade and lyse circulating red cells",
     "Adults compete for vitamin B12": "Adult worms compete for vitamin B12 in the ileum",
     "Eggs obstruct the bile duct": "Eggs obstruct the common bile duct",
     "Larvae cause hemolysis in the lungs": "Migrating larvae cause hemolysis in the lungs"},
  why={"Larvae invade and lyse circulating red cells": "Hookworm larvae migrate through tissue but do not parasitize red cells.",
       "Adult worms compete for vitamin B12 in the ileum": "That is Diphyllobothrium, which causes macrocytic anemia.",
       "Eggs obstruct the common bile duct": "Biliary obstruction occurs with Ascaris or liver flukes.",
       "Migrating larvae cause hemolysis in the lungs": "Lung migration causes transient pneumonitis, not hemolysis."},
  table=NEMATODES),

"Trichinella": dict(d="medium",
  why={"Taenia solium": "T. solium cysticercosis affects the brain, and muscle cysts are usually silent.",
       "Toxoplasma gondii": "Toxoplasmosis causes lymphadenopathy or encephalitis, not severe myositis.",
       "Toxocara canis": "Toxocara causes visceral larva migrans with hepatomegaly in toddlers.",
       "Echinococcus granulosus": "Echinococcus forms hydatid cysts in liver and lung."},
  table=NEMATODES),

"Toxocara": dict(d="medium",
  why={"Ascaris lumbricoides": "Ascaris matures in the human intestine and causes obstruction.",
       "Enterobius vermicularis": "Pinworm causes perianal itching without eosinophilia or hepatomegaly.",
       "Onchocerca volvulus": "Onchocerca causes skin nodules and eye disease after blackfly bites.",
       "Trichinella spiralis": "Trichinella causes myositis and periorbital edema after eating undercooked meat."},
  table=NEMATODES),

"Onchocerca": dict(d="medium",
  why={"Mosquito; diethylcarbamazine": "Mosquitoes transmit lymphatic filariasis, and DEC is dangerous in onchocerciasis.",
       "Deer fly (Chrysops); albendazole": "Deer flies transmit Loa loa.",
       "Sandfly; amphotericin B": "Sandflies transmit leishmaniasis.",
       "Tsetse fly; suramin": "Tsetse flies transmit African trypanosomiasis."},
  table=NEMATODES),

"Loa loa": dict(d="hard",
  c="Deer fly; heavy microfilaremia risks encephalopathy",
  o={"Blackfly; ivermectin causes blindness": "Blackfly; ivermectin itself causes blindness",
     "Culex mosquito": "Culex mosquito; ivermectin causes hemolysis",
     "Sandfly": "Sandfly; ivermectin causes cardiotoxicity",
     "Tsetse fly": "Tsetse fly; ivermectin has no activity at all"},
  why={"Blackfly; ivermectin itself causes blindness": "Blackflies carry Onchocerca, and ivermectin treats rather than causes blindness.",
       "Culex mosquito; ivermectin causes hemolysis": "Culex carries Wuchereria, and hemolysis is not the concern.",
       "Sandfly; ivermectin causes cardiotoxicity": "Sandflies carry Leishmania.",
       "Tsetse fly; ivermectin has no activity at all": "Tsetse flies carry trypanosomes."},
  table=NEMATODES),

"Wuchereria bancrofti": dict(d="medium",
  why={"Onchocerca volvulus; blackflies": "Onchocerca causes skin and eye disease, not limb elephantiasis.",
       "Loa loa; deer flies": "Loa loa causes transient Calabar swellings and eye migration.",
       "Dracunculus medinensis; copepods in water": "Guinea worm emerges through a skin blister.",
       "Schistosoma mansoni; freshwater snails": "Schistosomiasis causes portal hypertension."},
  table=NEMATODES),

"Taenia solium: transmission": dict(d="hard",
  c="Ingesting eggs shed in a tapeworm carrier's feces",
  o={"Eating undercooked pork containing": "Eating undercooked pork containing cysticerci",
     "Drinking water with copepods": "Drinking water that contains infected copepods",
     "Skin penetration by larvae": "Skin penetration by infective larvae",
     "Mosquito bite": "The bite of an infected mosquito"},
  why={"Eating undercooked pork containing cysticerci": "That gives an intestinal tapeworm, not tissue cysts.",
       "Drinking water that contains infected copepods": "Copepods transmit Dracunculus and Diphyllobothrium.",
       "Skin penetration by infective larvae": "That is how hookworm, Strongyloides, and schistosomes enter.",
       "The bite of an infected mosquito": "No mosquito transmits this tapeworm."},
  table=CESTODES_TREMATODES),

"Neurocysticercosis": dict(d="medium",
  c="Albendazole with steroids and antiseizure drugs",
  o={"Metronidazole": "A course of oral metronidazole",
     "Pyrimethamine and sulfadiazine": "Pyrimethamine combined with sulfadiazine",
     "Liposomal amphotericin B": "Intravenous liposomal amphotericin B",
     "Ivermectin": "A course of oral ivermectin"},
  why={"A course of oral metronidazole": "Metronidazole treats protozoa and anaerobes.",
       "Pyrimethamine combined with sulfadiazine": "That treats toxoplasmosis, which gives ring-enhancing lesions with edema.",
       "Intravenous liposomal amphotericin B": "That treats invasive fungal infection.",
       "A course of oral ivermectin": "Ivermectin treats nematodes, not cestode cysts."},
  table=CESTODES_TREMATODES),

"Echinococcus": dict(d="medium",
  why={"The cyst contains bacteria that cause sepsis": "Hydatid cysts are parasitic, not bacterial.",
       "The cyst is malignant": "Hydatid cysts are benign, though alveolar echinococcosis behaves invasively.",
       "Aspiration causes massive bleeding from vascular malformations": "Bleeding is not the main hazard here.",
       "The fluid contains a neurotoxin": "The fluid is antigenic rather than neurotoxic."},
  table=CESTODES_TREMATODES),

"Diphyllobothrium latum": dict(d="medium",
  c="The worm competes for vitamin B12 in the gut",
  o={"The worm sucks blood from the intestinal": "The worm sucks blood from the intestinal mucosa",
     "Larvae invade the bone marrow": "Larvae invade and damage the bone marrow",
     "Eggs cause hemolysis": "Eggs in the circulation cause hemolysis",
     "The worm blocks iron absorption": "The worm blocks iron absorption in the duodenum"},
  why={"The worm sucks blood from the intestinal mucosa": "That is hookworm, which causes microcytic iron deficiency.",
       "Larvae invade and damage the bone marrow": "This tapeworm stays in the gut lumen.",
       "Eggs in the circulation cause hemolysis": "Eggs pass in stool and do not enter blood.",
       "The worm blocks iron absorption in the duodenum": "The deficiency is of B12, which causes macrocytic anemia."},
  table=CESTODES_TREMATODES),

"Schistosoma mansoni": dict(d="medium",
  c="Cercariae penetrating skin in snail-infested freshwater",
  o={"Eating raw freshwater fish": "Eating raw or undercooked freshwater fish",
     "Eating undercooked crab": "Eating undercooked crab or crayfish",
     "Mosquito bite": "The bite of an infected mosquito",
     "Eating eggs in contaminated soil": "Swallowing eggs from contaminated soil"},
  why={"Eating raw or undercooked freshwater fish": "That transmits Clonorchis and Diphyllobothrium.",
       "Eating undercooked crab or crayfish": "That transmits Paragonimus.",
       "The bite of an infected mosquito": "Mosquitoes transmit filariae and arboviruses.",
       "Swallowing eggs from contaminated soil": "That is how Ascaris and Trichuris spread."},
  table=CESTODES_TREMATODES),

"Schistosoma haematobium": dict(d="medium",
  why={"Urothelial (transitional cell) carcinoma": "Urothelial carcinoma is linked to smoking and aniline dyes.",
       "Adenocarcinoma of the urachus": "Urachal adenocarcinoma arises at the bladder dome and is unrelated.",
       "Small cell carcinoma": "Small cell bladder carcinoma is rare and not parasite-related.",
       "Rhabdomyosarcoma": "Bladder rhabdomyosarcoma occurs in young children."},
  table=CESTODES_TREMATODES),

"Clonorchis & Paragonimus": dict(d="medium",
  why={"Paragonimus westermani": "Paragonimus comes from crab and causes lung disease with hemoptysis.",
       "Schistosoma japonicum": "S. japonicum causes portal hypertension, not biliary obstruction.",
       "Fasciola hepatica": "Fasciola comes from watercress and causes biliary disease but is not linked to cancer this way.",
       "Echinococcus multilocularis": "That forms an invasive cystic liver mass from fox feces."},
  table=CESTODES_TREMATODES),

"Helminth immunity: eosinophils": dict(d="medium",
  c="IgE-coated worms trigger eosinophil degranulation",
  o={"Neutrophil oxidative burst": "Neutrophil oxidative burst driven by IL-17",
     "Cytotoxic CD8 T-cell killing": "Cytotoxic CD8 T cells killing infected cells",
     "Complement-mediated lysis": "Complement-mediated lysis by the membrane attack complex",
     "Interferon-α from plasmacytoid": "Interferon-alpha from plasmacytoid dendritic cells"},
  why={"Neutrophil oxidative burst driven by IL-17": "Neutrophils handle extracellular bacteria and fungi.",
       "Cytotoxic CD8 T cells killing infected cells": "CD8 cells kill virus-infected cells; worms are extracellular.",
       "Complement-mediated lysis by the membrane attack complex": "MAC lyses Neisseria and some bacteria, not large worms.",
       "Interferon-alpha from plasmacytoid dendritic cells": "Type I interferon is an antiviral response."}),

"Anthelmintic drugs": dict(d="medium",
  c="Albendazole binds beta-tubulin and blocks glucose uptake",
  o={"Praziquantel — binds glutamate": "Praziquantel binds glutamate-gated chloride channels",
     "Ivermectin — increases calcium": "Ivermectin increases membrane calcium permeability",
     "Pyrantel pamoate — inhibits β-tubulin": "Pyrantel pamoate inhibits beta-tubulin assembly",
     "Diethylcarbamazine — inhibits DNA gyrase": "Diethylcarbamazine inhibits bacterial DNA gyrase"},
  why={"Praziquantel binds glutamate-gated chloride channels": "Those channels are the ivermectin target; praziquantel raises calcium permeability.",
       "Ivermectin increases membrane calcium permeability": "That is praziquantel's mechanism.",
       "Pyrantel pamoate inhibits beta-tubulin assembly": "Pyrantel is a depolarizing nicotinic agonist.",
       "Diethylcarbamazine inhibits bacterial DNA gyrase": "Gyrase is a bacterial target of fluoroquinolones."},
  table=ANTHELMINTICS),
}
