from tables import *
R = {
"TB: acid-fast cell wall": dict(d="easy",
  why={"Teichoic acids": "Teichoic acids are in Gram-positive walls and do not confer acid-fastness.",
       "Lipopolysaccharide": "LPS is the Gram-negative outer membrane endotoxin.",
       "Poly-D-glutamate": "That protein capsule is unique to B. anthracis.",
       "Peptidoglycan lacking muramic acid": "That describes chlamydial walls."},
  table=STAINS),

"TB: granuloma immunology": dict(d="medium",
  c="IL-12 driving Th1 cells to make IFN-gamma, with TNF",
  o={"IL-4 and IL-13": "IL-4 and IL-13 released by Th2 cells",
     "IL-17 from Th17": "IL-17 from Th17 cells recruiting neutrophils",
     "IL-10 and TGF-β": "IL-10 and TGF-beta from regulatory T cells",
     "IgE-mediated": "IgE-mediated degranulation of tissue mast cells"},
  why={"IL-4 and IL-13 released by Th2 cells": "Th2 responses drive allergy and helminth defense and worsen mycobacterial control.",
       "IL-17 from Th17 cells": "Th17 responses recruit neutrophils for extracellular bacteria and fungi.",
       "IL-10 and TGF-beta": "Regulatory cytokines suppress the response that builds granulomas.",
       "IgE-mediated degranulation": "That is immediate hypersensitivity, not granuloma formation."},
  table=IMMUNODEF),

"TB: primary vs reactivation": dict(d="medium",
  c="Upper lobe apices, where oxygen tension is highest",
  o={"Lower lobes, because of greater": "The lower lobes, where blood flow is greatest",
     "Right middle lobe": "The right middle lobe, because of bronchial anatomy",
     "Pleura only": "The pleura alone, because perfusion there is low",
     "Hilar nodes": "The hilar nodes, because of lymphatic drainage"},
  why={"The lower lobes, where blood flow is greatest": "Lower zones are involved in primary disease, not reactivation.",
       "The right middle lobe": "Middle lobe syndrome relates to bronchial compression, not TB reactivation.",
       "The pleura alone": "Pleural TB occurs but is not the typical reactivation site.",
       "The hilar nodes": "Hilar adenopathy characterizes primary infection."}),

"TB: miliary disease": dict(d="medium",
  c="Hematogenous spread that can seed many organs",
  o={"It reflects spread through the airways": "It reflects airway spread from a single lung cavity",
     "It is caused only by nontuberculous": "It is caused only by nontuberculous mycobacteria",
     "It does not occur in adults": "It occurs only in children, never in adults",
     "It is usually confined": "It is usually confined to the hilar lymph nodes"},
  why={"It reflects airway spread from a single lung cavity": "Endobronchial spread gives patchy infiltrates, not uniform tiny nodules everywhere.",
       "It is caused only by nontuberculous mycobacteria": "M. tuberculosis is the usual cause, though NTM can disseminate in AIDS.",
       "It occurs only in children, never in adults": "It is most common at the extremes of age and with immunosuppression.",
       "It is usually confined to the hilar lymph nodes": "By definition the infection is disseminated."}),

"TB: skin test interpretation": dict(d="medium",
  why={"Negative; induration must be at least 15 mm in any person": "The 15 mm cutoff applies only to people with no risk factors; healthcare work lowers it to 10 mm.",
       "Positive only if she has HIV": "The 5 mm cutoff applies in HIV, but 12 mm is positive for her regardless.",
       "Indeterminate, because erythema": "Only induration is measured; erythema is ignored.",
       "False-positive from prior BCG": "She was born in the US and BCG effects wane; an IGRA can clarify if needed."},
  table=TST),

"TB: latent treatment": dict(d="medium",
  why={"Rifampin, isoniazid, pyrazinamide, and ethambutol for 6 months": "Four-drug therapy is for active disease, which he does not have.",
       "No treatment": "Treating latent infection prevents later reactivation.",
       "Streptomycin for 2 months": "Streptomycin is a second-line injectable, not used for latent infection.",
       "Azithromycin weekly": "Azithromycin is used for MAC prophylaxis, not latent TB."},
  table=TB_DRUGS),

"TB drugs: isoniazid": dict(d="easy",
  c="Isoniazid; give pyridoxine (vitamin B6)",
  o={"Ethambutol; supplemental folate": "Ethambutol; give supplemental folate",
     "Rifampin; supplemental thiamine": "Rifampin; give supplemental thiamine",
     "Pyrazinamide; allopurinol": "Pyrazinamide; give allopurinol",
     "Isoniazid; supplemental cobalamin": "Isoniazid; give supplemental cobalamin"},
  why={"Ethambutol; give supplemental folate": "Ethambutol causes optic neuritis, and folate does not prevent it.",
       "Rifampin; give supplemental thiamine": "Rifampin causes orange fluids and drug interactions, not neuropathy.",
       "Pyrazinamide; give allopurinol": "Pyrazinamide raises uric acid, but allopurinol does not prevent that effect.",
       "Isoniazid; give supplemental cobalamin": "The right drug, but the vitamin is pyridoxine, not B12."},
  table=TB_DRUGS),

"TB drugs: RIPE adverse effects": dict(d="medium",
  why={"Isoniazid — orange fluids": "The three pairings are scrambled; isoniazid causes neuropathy and hepatitis.",
       "Pyrazinamide — orange fluids": "Pyrazinamide causes hyperuricemia and hepatotoxicity.",
       "Ethambutol — orange fluids": "Ethambutol causes optic neuritis, not discolored secretions.",
       "Rifampin — optic neuritis": "Rifampin causes orange fluids; ethambutol causes optic neuritis."},
  table=TB_DRUGS),

"MAC in AIDS": dict(d="medium",
  c="Mycobacterium avium complex; a macrolide plus ethambutol",
  o={"Mycobacterium kansasii": "Mycobacterium kansasii; isoniazid as single-drug therapy",
     "Mycobacterium marinum": "Mycobacterium marinum; doxycycline as single-drug therapy",
     "Mycobacterium leprae": "Mycobacterium leprae; dapsone as single-drug therapy",
     "Mycobacterium tuberculosis": "Mycobacterium tuberculosis; standard RIPE therapy"},
  why={"Mycobacterium kansasii": "M. kansasii causes cavitary lung disease, and monotherapy is never adequate.",
       "Mycobacterium marinum": "M. marinum causes skin nodules after water exposure.",
       "Mycobacterium leprae": "M. leprae causes skin and nerve disease and cannot be cultured from blood.",
       "Mycobacterium tuberculosis": "TB is possible at any CD4 count, but the lab identified a non-tuberculous species."}),

"M. marinum": dict(d="medium",
  why={"Sporothrix schenckii": "Sporotrichosis gives a similar pattern but follows soil or rose-thorn injury and shows yeast, not acid-fast rods.",
       "Mycobacterium leprae": "M. leprae causes anesthetic skin lesions and nerve thickening, not aquarium-related nodules.",
       "Nocardia brasiliensis": "Nocardia can spread this way but is only weakly acid-fast and comes from soil.",
       "Mycobacterium avium complex": "MAC causes lung or disseminated disease rather than a lymphocutaneous arm lesion."}),

"Leprosy: immune spectrum": dict(d="hard",
  c="A Th2 response with weak cell-mediated immunity",
  o={"A Th1-dominant response": "A Th1 response with tight granulomas and few organisms",
     "A Th17 response": "A Th17 response producing neutrophilic abscesses",
     "An IgE-mediated response": "An IgE-mediated response with blood eosinophilia",
     "A strong CD8 cytotoxic": "A strong CD8 response that clears infected cells"},
  why={"A Th1 response with tight granulomas": "That is tuberculoid leprosy, with few well-defined lesions and rare bacilli.",
       "A Th17 response": "Th17 responses drive neutrophilic infections, not this histology.",
       "An IgE-mediated response": "IgE and eosinophils dominate in allergy and helminth infection.",
       "A strong CD8 response that clears infected cells": "If organisms were being cleared, the biopsy would not be packed with bacilli."},
  table=LEPROSY),

"Leprosy: treatment": dict(d="medium",
  c="Dapsone; hemolysis and methemoglobinemia",
  o={"Rifampin; hepatitis": "Rifampin; drug-induced hepatitis",
     "Clofazimine; skin discoloration": "Clofazimine; red-brown skin discoloration",
     "Isoniazid; peripheral neuropathy": "Isoniazid; peripheral neuropathy",
     "Ethambutol; optic neuritis": "Ethambutol; optic neuritis"},
  why={"Rifampin; drug-induced hepatitis": "Rifampin is used, but hepatitis is not the reason for checking G6PD.",
       "Clofazimine; red-brown skin discoloration": "Clofazimine is used, but discoloration is cosmetic and unrelated to G6PD.",
       "Isoniazid; peripheral neuropathy": "Isoniazid is a TB drug and is not part of leprosy therapy.",
       "Ethambutol; optic neuritis": "Ethambutol is a TB drug and is not used for leprosy."},
  table=LEPROSY),

"Mycoplasma: walking pneumonia": dict(d="medium",
  why={"It produces a carbapenemase": "Mycoplasma makes no beta-lactamase; it simply has no target.",
       "It is an obligate intracellular organism": "Mycoplasma is extracellular and can be grown on special media.",
       "It has altered penicillin-binding proteins": "It has no PBPs at all, since it lacks a cell wall.",
       "It has an outer membrane impermeable": "Mycoplasma has a single membrane and no outer membrane."},
  table=ATYPICAL_PNA),

"Bacterial vaginosis": dict(d="easy",
  why={"Fluconazole": "Fluconazole treats candidiasis, which has normal pH and pseudohyphae.",
       "Ceftriaxone plus doxycycline": "That regimen treats gonorrhea and chlamydia, which cause cervicitis.",
       "Topical clotrimazole": "Clotrimazole is an antifungal and does not act on anaerobes.",
       "Oral penicillin": "Penicillin does not restore the normal flora or cover these anaerobes."},
  table=VAGINITIS),

"Vaginitis differential": dict(d="easy",
  c="Frothy green discharge, high pH, strawberry cervix",
  o={"Thick white 'cottage cheese'": "Thick white discharge, normal pH, pseudohyphae on KOH",
     "Thin gray discharge": "Thin gray discharge, high pH, clue cells, no inflammation",
     "Mucopurulent cervical discharge": "Mucopurulent cervical discharge with intracellular diplococci",
     "Painful grouped vesicles": "Painful grouped vesicles and ulcers on the vulva"},
  why={"Thick white discharge, normal pH": "That is candidal vaginitis.",
       "Thin gray discharge, high pH, clue cells": "That is bacterial vaginosis, which lacks inflammation and motile organisms.",
       "Mucopurulent cervical discharge": "That suggests gonococcal cervicitis.",
       "Painful grouped vesicles": "That is genital herpes."},
  table=VAGINITIS),

"Whipple disease": dict(d="hard",
  why={"Giardia lamblia": "Giardia causes malabsorption but shows trophozoites, not PAS-positive macrophages.",
       "Mycobacterium avium complex": "MAC also fills macrophages but the organisms are acid-fast and it occurs in advanced HIV.",
       "Cryptosporidium parvum": "Cryptosporidium causes watery diarrhea with acid-fast oocysts.",
       "Yersinia enterocolitica": "Yersinia causes acute enterocolitis and pseudoappendicitis."},
  table=STAINS),

"Chancroid": dict(d="medium",
  c="Single-dose azithromycin, or ceftriaxone IM",
  o={"Benzathine penicillin G": "A single IM dose of benzathine penicillin G",
     "Acyclovir": "A course of oral acyclovir",
     "Doxycycline for 21 days": "A 21-day course of oral doxycycline",
     "Metronidazole": "A single 2 gram dose of metronidazole"},
  why={"A single IM dose of benzathine penicillin G": "That treats syphilis, which causes a painless indurated chancre.",
       "A course of oral acyclovir": "Acyclovir treats herpes, which causes grouped vesicles rather than a deep purulent ulcer.",
       "A 21-day course of oral doxycycline": "That is the LGV regimen, where the ulcer is painless and transient.",
       "A single 2 gram dose of metronidazole": "Metronidazole treats trichomoniasis."},
  table=GENITAL_ULCERS),
}
