from tables import *
R = {
"HSV-1: latency": dict(d="easy",
  why={"Oral epithelial basal cells": "Epithelial cells are where lytic replication occurs; they turn over and cannot harbor latency.",
       "B lymphocytes": "EBV and HHV-8 are latent in B cells.",
       "Salivary gland ductal cells": "Salivary glands shed virus but are not the latency site.",
       "Monocytes and macrophages": "CMV is latent in the monocyte lineage."},
  table=HERPES),

"Tzanck smear": dict(d="medium",
  why={"EBV and CMV": "These do not produce multinucleated giant cells in skin scrapings.",
       "Molluscum contagiosum virus": "Molluscum produces intracytoplasmic inclusion bodies, not multinucleated cells.",
       "Coxsackievirus A": "Hand-foot-mouth vesicles do not show these giant cells.",
       "Measles virus": "Measles giant cells occur in lymphoid tissue and lung, not vesicle scrapings."},
  table=HERPES),

"HSV encephalitis": dict(d="easy",
  why={"IV ceftriaxone and vancomycin": "That covers bacterial meningitis, which shows neutrophils and low glucose.",
       "Oral valacyclovir": "Oral therapy is inadequate for CNS disease.",
       "IV ganciclovir": "Ganciclovir targets CMV, which causes encephalitis mainly in advanced immunosuppression.",
       "Supportive care": "Untreated HSV encephalitis has very high mortality."},
  table=HERPES_DRUGS),

"Acyclovir mechanism": dict(d="medium",
  c="Viral thymidine kinase activates it; it terminates DNA chains",
  o={"It binds viral neuraminidase": "It binds and inhibits viral neuraminidase",
     "It inhibits viral uncoating": "It inhibits viral uncoating within endosomes",
     "It blocks host ribonucleotide": "It blocks the host ribonucleotide reductase enzyme",
     "It is a pyrophosphate analog": "It is a pyrophosphate analog needing no activation"},
  why={"It binds and inhibits viral neuraminidase": "That is oseltamivir, used for influenza.",
       "It inhibits viral uncoating within endosomes": "That is amantadine, an old influenza A drug.",
       "It blocks the host ribonucleotide reductase": "Acting on a host enzyme would not give selectivity.",
       "It is a pyrophosphate analog needing no activation": "That describes foscarnet, used for resistant virus."},
  table=HERPES_DRUGS),

"Neonatal HSV": dict(d="medium",
  why={"Vaginal delivery with neonatal erythromycin eye ointment": "Ointment prevents gonococcal conjunctivitis, not HSV.",
       "Vaginal delivery; primary infection carries minimal risk": "Primary infection near term carries the highest transmission risk.",
       "Induce labor immediately": "Hastening vaginal delivery increases exposure.",
       "Give HSV immune globulin to the neonate": "No HSV immune globulin is used for this purpose."}),

"Varicella": dict(d="easy",
  c="It spreads by aerosols and becomes latent in sensory ganglia",
  o={"Lesions all appear at the same stage": "Lesions all appear at one stage, mostly on the limbs",
     "It is caused by a poxvirus": "It is caused by a poxvirus replicating in the cytoplasm",
     "Aspirin is the preferred antipyretic": "Aspirin is the preferred antipyretic for the fever",
     "Adults have milder disease": "Adults reliably have milder disease than children"},
  why={"Lesions all appear at one stage": "That is smallpox; varicella shows lesions in several stages at once.",
       "It is caused by a poxvirus": "VZV is a herpesvirus that replicates in the nucleus.",
       "Aspirin is the preferred antipyretic": "Aspirin risks Reye syndrome in this setting.",
       "Adults reliably have milder disease": "Adults have more severe disease, including pneumonia."},
  table=HERPES),

"Herpes zoster": dict(d="easy",
  c="VZV reactivation from a sensory ganglion; recombinant vaccine",
  o={"Primary infection with HSV-2": "Primary HSV-2 infection; no vaccine is available",
     "Reactivation of HSV-1": "HSV-1 reactivation in the trigeminal ganglion; live vaccine",
     "Coxsackievirus infection": "Coxsackievirus infection of sensory neurons; killed vaccine",
     "Autoimmune vasculitis": "An autoimmune vasculitis; no vaccine is available"},
  why={"Primary HSV-2 infection": "Genital herpes causes recurrent genital lesions, not a thoracic dermatomal band.",
       "HSV-1 reactivation in the trigeminal ganglion": "That causes cold sores, and the zoster vaccine is not live.",
       "Coxsackievirus infection of sensory neurons": "Coxsackievirus causes hand-foot-mouth disease and herpangina.",
       "An autoimmune vasculitis": "Vasculitis does not respect a single dermatome."},
  table=HERPES),

"EBV: infectious mononucleosis": dict(d="medium",
  c="Reactive CD8 T cells responding to infected B cells",
  o={"EBV-infected B cells": "Circulating EBV-infected B lymphocytes",
     "Neoplastic Reed-Sternberg cells": "Neoplastic Reed-Sternberg cells in the blood",
     "Plasma cells producing heterophile": "Plasma cells making heterophile antibodies",
     "Virus-infected monocytes": "Virus-infected circulating monocytes"},
  why={"Circulating EBV-infected B lymphocytes": "Infected B cells are a small minority; the atypical cells are responding T cells.",
       "Neoplastic Reed-Sternberg cells": "Those are found in Hodgkin lymphoma tissue, not in this blood smear.",
       "Plasma cells making heterophile antibodies": "Heterophile antibodies are produced, but the large cells are T cells.",
       "Virus-infected circulating monocytes": "EBV targets B cells via CD21, not monocytes."},
  table=HERPES),

"EBV: malignancies": dict(d="medium",
  why={"Human herpesvirus 8": "HHV-8 causes Kaposi sarcoma and primary effusion lymphoma.",
       "Human papillomavirus type 16": "HPV causes cervical and oropharyngeal squamous carcinoma.",
       "HTLV-1": "HTLV-1 causes adult T-cell leukemia/lymphoma.",
       "Hepatitis B virus": "HBV causes hepatocellular carcinoma."},
  table=HERPES),

"CMV: congenital": dict(d="medium",
  why={"Patent ductus arteriosus": "PDA with cataracts and deafness suggests congenital rubella.",
       "Hutchinson teeth": "Hutchinson teeth indicate congenital syphilis.",
       "Chorioretinitis with hydrocephalus from a protozoan": "That describes congenital toxoplasmosis with diffuse calcifications.",
       "Limb hypoplasia and cicatricial skin scars": "Those indicate congenital varicella syndrome."},
  table=TORCH),

"CMV: immunocompromised": dict(d="hard",
  c="Neutropenia; CMV UL97 kinase activates the drug",
  o={"Nephrotoxicity; viral thymidine kinase": "Nephrotoxicity; viral thymidine kinase activates it",
     "Hypocalcemia and seizures": "Hypocalcemia and seizures; no activation is needed",
     "Hemolytic anemia": "Hemolytic anemia; host adenosine deaminase activates it",
     "Lactic acidosis": "Lactic acidosis; reverse transcriptase activates it"},
  why={"Nephrotoxicity; viral thymidine kinase": "CMV has no thymidine kinase, and nephrotoxicity is a foscarnet and cidofovir problem.",
       "Hypocalcemia and seizures": "That describes foscarnet, which needs no viral kinase.",
       "Hemolytic anemia": "Adenosine deaminase does not activate this drug.",
       "Lactic acidosis": "Lactic acidosis relates to NRTIs used in HIV."},
  table=HERPES_DRUGS),

"HHV-6: roseola": dict(d="easy",
  why={"Measles virus": "Measles has the rash appear while the child is febrile and toxic, with Koplik spots.",
       "Parvovirus B19": "Fifth disease causes slapped cheeks and a lacy rash without preceding high fever.",
       "Rubella virus": "Rubella causes postauricular adenopathy and a mild rash without high fever.",
       "Group A Streptococcus": "Scarlet fever produces a sandpaper rash with pharyngitis."},
  table=RASHES),

"HHV-8: Kaposi sarcoma": dict(d="medium",
  c="HHV-8, which also causes primary effusion lymphoma",
  o={"It is EBV": "EBV, which enters B cells through CD21",
     "It is HPV": "HPV, whose E6 protein inactivates p53",
     "It is Bartonella": "Bartonella, a bacterium treated with erythromycin",
     "It is HTLV-1": "HTLV-1, which causes adult T-cell leukemia"},
  why={"EBV": "EBV drives lymphomas and nasopharyngeal carcinoma, not these vascular skin plaques.",
       "HPV": "HPV causes squamous lesions and warts.",
       "Bartonella": "Bacillary angiomatosis looks similar but shows neutrophils and bacilli on biopsy.",
       "HTLV-1": "HTLV-1 causes a T-cell leukemia with hypercalcemia and lytic bone lesions."},
  table=HERPES),

"Herpesvirus structure": dict(d="medium",
  c="Enveloped dsDNA viruses that establish lifelong latency",
  o={"Non-enveloped ssDNA": "Non-enveloped single-stranded DNA viruses",
     "Enveloped RNA viruses": "Enveloped RNA viruses replicating in the cytoplasm",
     "Circular dsDNA viruses": "Circular dsDNA viruses that use reverse transcriptase",
     "Naked icosahedral viruses": "Naked icosahedral viruses resistant to detergents"},
  why={"Non-enveloped single-stranded DNA viruses": "That describes parvovirus B19.",
       "Enveloped RNA viruses replicating in the cytoplasm": "Herpesviruses are DNA viruses that replicate in the nucleus.",
       "Circular dsDNA viruses that use reverse transcriptase": "That describes hepatitis B.",
       "Naked icosahedral viruses resistant to detergents": "Herpesviruses are enveloped and are destroyed by detergents."},
  table=DNA_VIRUSES),

"Parvovirus B19": dict(d="medium",
  c="Transient aplastic crisis from erythroid precursor infection",
  o={"Acute chest syndrome": "Acute chest syndrome caused directly by the virus",
     "Splenic sequestration": "Splenic sequestration from immune complex deposition",
     "Osteomyelitis": "Hematogenous osteomyelitis of a long bone",
     "Hemolytic uremic syndrome": "Hemolytic uremic syndrome with kidney failure"},
  why={"Acute chest syndrome caused directly by the virus": "Acute chest syndrome is a vaso-occlusive complication, not direct viral injury.",
       "Splenic sequestration from immune complex deposition": "Sequestration is a sickle complication unrelated to this virus.",
       "Hematogenous osteomyelitis": "Parvovirus does not cause bone infection.",
       "Hemolytic uremic syndrome": "HUS follows Shiga toxin infections."},
  table=RASHES),

"HPV: oncogenesis": dict(d="medium",
  why={"E6 binds Rb and E7 activates telomerase only": "The targets are swapped; E6 degrades p53 and E7 binds Rb.",
       "The virus inserts an oncogene next to c-MYC": "That describes the Burkitt lymphoma translocation, not HPV.",
       "The virus encodes a viral cyclin that activates CDK6": "That is an HHV-8 strategy.",
       "LANA inactivates p53": "LANA is the HHV-8 latency protein."}),

"HPV: warts": dict(d="easy",
  why={"Types 16 and 18": "Those are high-risk oncogenic types causing dysplasia and cancer.",
       "Types 1 and 2 only": "Those cause common and plantar warts.",
       "Type 31 only": "Type 31 is another high-risk oncogenic type.",
       "Types 45 and 52 only": "Those are also high-risk oncogenic types."}),

"Molluscum contagiosum": dict(d="medium",
  why={"It has a single-stranded genome": "Poxviruses have double-stranded DNA.",
       "It uses reverse transcriptase": "Only hepadnaviruses and retroviruses use reverse transcriptase.",
       "It is non-enveloped": "Poxviruses are enveloped.",
       "It is a circular genome that integrates": "Poxvirus DNA is linear and does not integrate."},
  table=DNA_VIRUSES),

"Smallpox vs chickenpox": dict(d="medium",
  why={"Superficial vesicles in different stages": "That is varicella.",
       "A rash concentrated on the trunk": "Varicella is centripetal; smallpox is centrifugal.",
       "Lesions that crust within 24 hours": "Smallpox lesions evolve slowly over days.",
       "Mild prodrome with low-grade fever": "Smallpox has a severe prodrome with high fever and prostration."}),

"Adenovirus": dict(d="easy",
  why={"Enterovirus 70; it is an enveloped RNA virus": "Enterovirus 70 causes hemorrhagic conjunctivitis, and enteroviruses are non-enveloped.",
       "HSV-1; it is an enveloped dsDNA virus": "Enveloped viruses are inactivated by drying and chlorination.",
       "Chlamydia trachomatis; it forms elementary bodies": "Chlamydial conjunctivitis is not a pool-associated outbreak illness.",
       "Measles virus; it is a paramyxovirus": "Measles causes a systemic febrile exanthem, and it is enveloped."},
  table=DNA_VIRUSES),

"JC virus: PML": dict(d="hard",
  why={"HSV encephalitis": "HSV causes acute temporal lobe encephalitis with fever and seizures.",
       "Primary CNS lymphoma from EBV": "CNS lymphoma enhances with contrast and causes mass effect.",
       "Toxoplasma encephalitis": "Toxoplasmosis gives ring-enhancing lesions with edema.",
       "Subacute sclerosing panencephalitis": "SSPE follows measles years later, mainly in children."}),

"DNA virus rules": dict(d="medium",
  why={"All are enveloped": "Papilloma, polyoma, adeno, and parvoviruses are naked.",
       "All are single-stranded and circular": "Most are double-stranded, and several are linear.",
       "All replicate in the cytoplasm": "Only poxviruses replicate in the cytoplasm.",
       "None can establish latency": "Herpesviruses are defined by lifelong latency."},
  table=DNA_VIRUSES),

"Viral envelope & transmission": dict(d="easy",
  why={"It has a helical nucleocapsid": "Capsid symmetry does not determine environmental stability.",
       "It has a segmented genome": "Segmentation allows reassortment but not bile resistance.",
       "It buds from the plasma membrane": "Budding is how enveloped viruses form, which makes them fragile.",
       "It has a positive-sense RNA genome": "Genome polarity does not affect survival in the gut."}),
}
