from tables import *
R = {
"S. aureus: identification": dict(d="easy",
  why={"Novobiocin": "Novobiocin resistance separates S. saprophyticus from other coagulase-negative staph; it does not identify S. aureus.",
       "Optochin": "Optochin sensitivity identifies S. pneumoniae, which is catalase-negative and grows in pairs, not clusters.",
       "Bacitracin": "Bacitracin sensitivity identifies group A strep among catalase-negative beta-hemolytic cocci.",
       "Bile esculin": "Bile esculin hydrolysis identifies group D organisms (Enterococcus, S. gallolyticus), which are catalase-negative."},
  table=GPC_ALGORITHM),

"S. aureus: TSST-1 mechanism": dict(d="medium",
  c="A superantigen links MHC II to T-cell receptor Vbeta chains",
  o={"A toxin ADP-ribosylates elongation": "A toxin ADP-ribosylates elongation factor 2 in host cells",
     "A toxin cleaves": "A protease cleaves desmoglein-1 in the superficial epidermis",
     "Lipid A": "Lipid A binds TLR4 and CD14 on circulating macrophages",
     "A toxin ADP-ribosylates the Gs": "A toxin ADP-ribosylates Gs alpha, locking adenylyl cyclase on"},
  why={"A toxin ADP-ribosylates elongation": "EF-2 ribosylation is diphtheria toxin and Pseudomonas exotoxin A; it kills cells but does not produce this cytokine-driven shock.",
       "A protease cleaves": "Exfoliative toxin causes bullous impetigo and scalded skin syndrome, not shock with multiorgan failure.",
       "Lipid A": "Lipid A is Gram-negative endotoxin; this is a Gram-positive toxin-mediated illness.",
       "A toxin ADP-ribosylates Gs": "That is cholera and ETEC heat-labile toxin, which cause secretory diarrhea."},
  table=TOXINS),

"S. aureus: food poisoning": dict(d="easy",
  why={"It is produced after spores": "That is C. perfringens, which takes 8-16 hours and causes diarrhea; S. aureus forms no spores.",
       "It is a neurotoxin": "Botulinum toxin blocks acetylcholine release and causes descending paralysis over 12-36 hours.",
       "It is released when": "Mucosal invasion (Shigella, Campylobacter) causes fever and bloody stools after 1-3 days.",
       "It is a heat-labile toxin": "Heat-labile toxins (cholera, ETEC) are made in the gut and cause watery diarrhea, not rapid vomiting."},
  table=DIARRHEA),

"S. aureus: protein A": dict(d="medium",
  why={"Cleavage of secretory IgA": "IgA protease belongs to S. pneumoniae, H. influenzae, and Neisseria, and aids mucosal colonization.",
       "Conversion of fibrinogen": "That is coagulase, a different S. aureus factor that walls off abscesses.",
       "Lysis of red blood cells": "Hemolysins (alpha-toxin) do this; protein A binds antibody instead.",
       "Polyclonal activation": "Superantigens (TSST-1, enterotoxins) activate T cells; protein A acts on IgG."}),

"S. aureus: MRSA resistance": dict(d="medium",
  c="mecA-encoded PBP2a with low beta-lactam affinity",
  o={"Production of a plasmid": "Plasmid-encoded penicillinase that hydrolyzes penicillins",
     "Replacement of D-Ala-D-Ala": "Precursors ending in D-Ala-D-Lac instead of D-Ala-D-Ala",
     "Loss of outer membrane": "Loss of outer membrane porin channels",
     "Methylation of the 23S": "Methylation of the 23S ribosomal RNA target"},
  why={"Plasmid-encoded penicillinase": "Penicillinase alone is defeated by oxacillin and by sulbactam, yet both failed here.",
       "Precursors ending in D-Ala-D-Lac": "That is vancomycin resistance (VRE, VRSA), not beta-lactam resistance.",
       "Loss of outer membrane porin": "Staphylococci are Gram-positive and have no outer membrane.",
       "Methylation of the 23S": "23S methylation causes macrolide and clindamycin resistance."},
  table=RESISTANCE),

"S. aureus: bullous impetigo / exfoliative toxin": dict(d="medium",
  why={"Desmoglein-3": "Desmoglein-3 is the target in pemphigus vulgaris, which causes painful mucosal erosions.",
       "Hemidesmosomes": "Hemidesmosome antigens (BP180/230) are targeted in bullous pemphigoid, giving tense subepidermal blisters.",
       "Type VII collagen": "Anti-type VII collagen causes epidermolysis bullosa acquisita, with trauma-induced blisters.",
       "Keratin intermediate": "Keratin mutations cause inherited epidermolysis bullosa simplex, not an acute febrile illness."}),

"S. aureus: scalded skin vs TEN": dict(d="hard",
  c="Split in the stratum granulosum, no keratinocyte necrosis",
  o={"Full-thickness epidermal": "Full-thickness necrosis of the epidermis",
     "Subepidermal blister": "Subepidermal blister filled with eosinophils",
     "Suprabasal acantholysis": "Suprabasal acantholysis with a tombstone basal layer",
     "Dermal leukocytoclastic": "Leukocytoclastic vasculitis in the dermal vessels"},
  why={"Full-thickness necrosis": "That is toxic epidermal necrolysis, which is drug-induced and involves mucosa (spared here).",
       "Subepidermal blister": "Bullous pemphigoid gives tense blisters in the elderly, not diffuse sloughing in a neonate.",
       "Suprabasal acantholysis": "Pemphigus vulgaris causes oral erosions and affects adults.",
       "Leukocytoclastic vasculitis": "Vasculitis causes palpable purpura rather than a positive Nikolsky sign."}),

"S. aureus: right-sided endocarditis": dict(d="easy",
  why={"Streptococcus sanguinis": "Viridans strep cause subacute left-sided disease on damaged valves after dental work.",
       "Enterococcus faecalis": "Enterococcal endocarditis follows GU or GI procedures, usually in older patients.",
       "Staphylococcus epidermidis": "S. epidermidis infects prosthetic valves and catheters, not native tricuspid valves.",
       "Streptococcus gallolyticus": "S. gallolyticus endocarditis should prompt colonoscopy for colon cancer."},
  table=STREP),

"S. aureus: chronic granulomatous disease": dict(d="hard",
  c="Their catalase destroys the H2O2 the phagocyte could borrow",
  o={"They secrete superoxide dismutase that": "Their superoxide dismutase inactivates neutrophil elastase",
     "They lack a cell wall": "They lack a cell wall and so resist lysozyme",
     "They produce IgA protease": "Their IgA protease cleaves opsonizing antibody",
     "They block phagolysosome": "They block phagolysosome fusion inside macrophages"},
  why={"Their superoxide dismutase": "SOD protects bacteria from oxygen radicals, but CGD neutrophils cannot make those radicals at all.",
       "They lack a cell wall": "Mycoplasma lacks a cell wall and is not a CGD pathogen.",
       "Their IgA protease": "IgA protease aids mucosal colonization by S. pneumoniae, H. influenzae, and Neisseria.",
       "They block phagolysosome": "That is how mycobacteria and Legionella survive, and it is unrelated to catalase."},
  table=IMMUNODEF),

"S. aureus: osteomyelitis": dict(d="medium",
  c="S. aureus, using MSCRAMM adhesins for bone matrix",
  o={"Salmonella": "Salmonella, using its Vi capsular antigen",
     "Pseudomonas": "Pseudomonas aeruginosa, using pyocyanin pigment",
     "Streptococcus pyogenes": "Streptococcus pyogenes, using its hyaluronic acid capsule",
     "Kingella": "Kingella kingae, using urease to invade bone"},
  why={"Salmonella": "Salmonella osteomyelitis is characteristic of sickle cell disease, not a healthy child.",
       "Pseudomonas": "Pseudomonas follows puncture wounds through sneakers; pyocyanin is a pigment, not an adhesin.",
       "Streptococcus pyogenes": "GAS causes skin and soft tissue infection far more often than hematogenous osteomyelitis.",
       "Kingella": "Kingella causes septic arthritis in children under 4 and is not urease-driven."}),

"S. epidermidis: biofilm": dict(d="easy",
  c="Polysaccharide biofilm coating the prosthesis",
  o={"Protein A": "Protein A binding the Fc portion of IgG",
     "Exfoliative toxin": "Exfoliative toxin cleaving epidermal cadherins",
     "Urease": "Urease splitting urea into ammonia",
     "Polysaccharide capsule": "A capsule that blocks C3b deposition on the surface"},
  why={"Protein A": "Protein A is an S. aureus factor; this isolate is coagulase-negative.",
       "Exfoliative toxin": "Exfoliative toxin causes skin blistering, not indolent prosthetic infection.",
       "Urease": "Urease matters for struvite stones and H. pylori, not joint hardware.",
       "A capsule that blocks C3b": "Capsules matter most for pneumococcus and meningococcus; biofilm explains device infection."},
  table=STAPH),

"S. saprophyticus: UTI": dict(d="easy",
  why={"Staphylococcus epidermidis": "S. epidermidis is novobiocin-sensitive and rarely causes cystitis in healthy women.",
       "Enterococcus faecalis": "Enterococcus is catalase-negative and grows in chains, not clusters.",
       "Streptococcus agalactiae": "GBS is catalase-negative and matters mainly in pregnancy and neonates.",
       "Staphylococcus aureus": "S. aureus is coagulase-positive; in urine it suggests hematogenous seeding."},
  table=STAPH),

"S. pyogenes: scarlet fever": dict(d="easy",
  why={"Bacitracin resistant and CAMP": "That pattern is group B strep, which causes neonatal disease, not scarlet fever.",
       "Optochin sensitive": "Optochin sensitivity and bile solubility identify S. pneumoniae, which is alpha-hemolytic.",
       "Grows in 6.5% NaCl": "Salt tolerance and bile esculin hydrolysis identify Enterococcus.",
       "Coagulase positive": "Coagulase and mannitol fermentation identify S. aureus, a catalase-positive cluster former."},
  table=STREP),

"S. pyogenes: M protein & rheumatic fever": dict(d="medium",
  c="M protein, via antibodies cross-reacting with myosin",
  o={"Streptolysin S": "Streptolysin S, via direct lysis of cardiac myocytes",
     "Erythrogenic toxin": "Erythrogenic toxin, via superantigen T-cell activation",
     "Hyaluronic acid capsule": "Hyaluronic acid capsule, via immune complex deposition",
     "Lipoteichoic acid": "Lipoteichoic acid, via TLR2-mediated septic shock"},
  why={"Streptolysin S": "Streptolysin S lyses cells on blood agar but does not cause the delayed, immune-mediated valve damage.",
       "Erythrogenic toxin": "Erythrogenic (pyrogenic) toxin causes scarlet fever and streptococcal toxic shock, which are acute.",
       "Hyaluronic acid capsule": "The capsule resembles host tissue and is poorly immunogenic, so it does not drive antibody-mediated damage.",
       "Lipoteichoic acid": "LTA contributes to adherence and sepsis physiology, not to molecular mimicry."},
  table=GAS_SEQUELAE),

"S. pyogenes: PSGN vs ARF": dict(d="medium",
  c="It follows skin or throat infection and antibiotics do not prevent it",
  o={"It follows only pharyngeal": "It follows only pharyngeal infection and penicillin prevents it",
     "It is caused by antibodies that": "It is caused by antibodies against type IV collagen",
     "It is a type I": "It is a type I (IgE-mediated) hypersensitivity reaction",
     "Complement levels": "Complement levels are characteristically elevated"},
  why={"It follows only pharyngeal": "That describes rheumatic fever; this boy had impetigo, which can still cause nephritis.",
       "It is caused by antibodies against type IV collagen": "Anti-GBM (type IV collagen) disease is Goodpasture syndrome, with lung hemorrhage.",
       "It is a type I": "PSGN is type III, driven by immune complexes, not IgE.",
       "Complement levels": "Serum C3 is low, which is a hallmark of PSGN."},
  table=GAS_SEQUELAE),

"S. pyogenes: streptolysin O / ASO": dict(d="medium",
  why={"Streptolysin S": "Streptolysin S is oxygen-stable and non-immunogenic, so no useful antibody titer forms.",
       "Streptokinase": "Streptokinase dissolves fibrin and is not the standard serologic marker.",
       "Pyrogenic exotoxin A": "SpeA causes scarlet fever and toxic shock but is not routinely measured.",
       "Hyaluronic acid capsule": "The capsule mimics host connective tissue and provokes little antibody."}),

"S. pyogenes: erysipelas": dict(d="easy",
  c="Upper dermis and lymphatics, usually group A strep",
  o={"It involves deep fascia": "Deep fascia, requiring emergency surgical debridement",
     "It is caused by a dermatophyte": "A dermatophyte confined to the stratum corneum",
     "It is caused by toxin-mediated": "Toxin-mediated splitting of the stratum granulosum",
     "It is a reaction to viral": "A reaction to viral infection of keratinocytes"},
  why={"Deep fascia": "Necrotizing fasciitis causes pain out of proportion, dusky skin, and crepitus, not a sharply raised border.",
       "A dermatophyte": "Tinea causes an itchy annular scaly plaque without fever.",
       "Toxin-mediated splitting": "Staphylococcal scalded skin causes sloughing, not a demarcated red plaque.",
       "A reaction to viral": "Viral exanthems are widespread and not sharply demarcated or tender."}),

"S. pyogenes: necrotizing fasciitis treatment": dict(d="medium",
  why={"Vancomycin": "Vancomycin covers MRSA but does not shut down exotoxin synthesis.",
       "Gentamicin": "Aminoglycosides have poor activity against streptococci and do not block toxin production.",
       "Metronidazole": "Metronidazole covers anaerobes; this is a confirmed group A strep infection.",
       "Rifampin": "Rifampin is not used here and breeds resistance when given alone."}),

"S. pyogenes: virulence summary": dict(d="medium",
  why={"Streptolysin O": "Streptolysin O is an oxygen-labile pore-forming hemolysin and the basis of the ASO titer.",
       "Hyaluronidase": "Hyaluronidase degrades ground substance, a different route of spread.",
       "C5a peptidase": "C5a peptidase blocks neutrophil chemotaxis.",
       "DNase": "DNase liquefies pus and provides the anti-DNase B titer."}),

"S. agalactiae: neonatal sepsis": dict(d="medium",
  c="A sialic acid-rich polysaccharide capsule",
  o={"M protein": "M protein anchored in the cell wall",
     "Protein A": "Protein A that binds immunoglobulin Fc",
     "Pili with IgA protease": "Pili combined with secreted IgA protease",
     "Lipooligosaccharide": "Lipooligosaccharide in the outer membrane"},
  why={"M protein": "M protein belongs to group A strep and underlies rheumatic fever.",
       "Protein A": "Protein A is an S. aureus factor.",
       "Pili combined with secreted IgA protease": "IgA protease characterizes S. pneumoniae, H. influenzae, and Neisseria.",
       "Lipooligosaccharide": "LOS is found in Gram-negative organisms; GBS is Gram-positive."},
  table=STREP),

"S. agalactiae: prevention": dict(d="medium",
  c="Screen at 36-37 weeks, give IV penicillin in labor",
  o={"Oral amoxicillin during": "Oral amoxicillin in the first trimester for every woman",
     "Conjugate vaccination": "Conjugate vaccination of the neonate right after birth",
     "Erythromycin ointment": "Erythromycin ointment to the neonate's eyes at birth",
     "Treating the mother with oral": "Oral penicillin for 10 days when screening is positive"},
  why={"Oral amoxicillin in the first trimester": "Early treatment fails because women become recolonized before delivery.",
       "Conjugate vaccination": "No licensed GBS vaccine exists, and a neonatal vaccine would act too late.",
       "Erythromycin ointment": "Eye prophylaxis prevents gonococcal conjunctivitis, not GBS sepsis.",
       "Oral penicillin for 10 days": "Antenatal courses do not eradicate carriage; the drug must be given during labor."}),

"S. pneumoniae: lobar pneumonia": dict(d="easy",
  why={"Bacitracin sensitive": "Bacitracin sensitivity identifies group A strep, which is beta-hemolytic.",
       "Coagulase positive": "Coagulase identifies S. aureus, a catalase-positive cluster former.",
       "CAMP test positive": "A positive CAMP test identifies group B strep.",
       "Growth in 6.5% NaCl": "Salt tolerance identifies Enterococcus."},
  table=STREP),

"S. pneumoniae: asplenia & capsule": dict(d="medium",
  c="A polysaccharide capsule cleared by splenic macrophages",
  o={"A peptidoglycan-free": "A cell wall that contains no peptidoglycan",
     "An endospore coat": "An endospore coat that resists heat and drying",
     "Mycolic acids": "Mycolic acids within the cell envelope",
     "A lipooligosaccharide": "A lipooligosaccharide that lacks O antigen"},
  why={"A cell wall that contains no peptidoglycan": "Mycoplasma lacks a cell wall and is not associated with post-splenectomy sepsis.",
       "An endospore coat": "Spores are formed by Bacillus and Clostridium, which are not encapsulated splenic pathogens.",
       "Mycolic acids": "Mycolic acids belong to mycobacteria, controlled by T cells rather than the spleen.",
       "A lipooligosaccharide": "LOS is a Gram-negative feature; pneumococcus is Gram-positive."},
  table=IMMUNODEF),

"S. pneumoniae: vaccines": dict(d="hard",
  c="The carrier protein recruits T-cell help for class switching",
  o={"The polysaccharide is converted": "The polysaccharide is presented as peptide on MHC I",
     "The carrier protein directly": "The carrier protein directly activates TLR4 on B cells",
     "It induces mainly IgM": "It elicits mainly IgM from marginal zone B cells",
     "It causes a T-cell": "It gives a T-independent response, stronger in infants"},
  why={"The polysaccharide is presented as peptide on MHC I": "Polysaccharides are not presented as peptides, and MHC I drives CD8 responses.",
       "The carrier protein directly activates TLR4": "TLR4 responds to LPS; the benefit comes from T-cell help, not innate signaling.",
       "It elicits mainly IgM": "IgM without memory is what the plain polysaccharide vaccine does.",
       "It gives a T-independent response": "T-independent responses are weak in infants, which is the problem conjugation solves."},
  table=VACCINES),

"S. pneumoniae: penicillin resistance": dict(d="hard",
  c="Mosaic PBP genes acquired by transformation",
  o={"Plasmid-encoded": "A plasmid-encoded beta-lactamase enzyme",
     "Efflux pump": "Overexpression of a multidrug efflux pump",
     "Reduced outer membrane": "Reduced expression of outer membrane porins",
     "Ribosomal methylation": "Methylation of the ribosomal drug target"},
  why={"A plasmid-encoded beta-lactamase": "Pneumococci do not make beta-lactamase, and the stem says none was produced.",
       "Overexpression of a multidrug efflux pump": "Efflux contributes to macrolide and tetracycline resistance, not penicillin.",
       "Reduced expression of outer membrane porins": "Gram-positive organisms have no outer membrane.",
       "Methylation of the ribosomal drug target": "Ribosomal methylation affects macrolides, not cell-wall agents."},
  table=RESISTANCE),

"S. pneumoniae: IgA protease & otitis": dict(d="easy",
  why={"Degrades the Fc region of IgG": "Protein A binds IgG Fc and belongs to S. aureus.",
       "Cleaves C5a": "C5a peptidase is a group A strep factor.",
       "Hydrolyzes urea": "Urease is used by Proteus, Klebsiella, and H. pylori.",
       "Degrades hyaluronic acid": "Hyaluronidase spreads through connective tissue and is typical of GAS and clostridia."}),

"S. pneumoniae: pneumolysin & meningitis": dict(d="medium",
  why={"Ceftriaxone alone": "Ceftriaxone alone misses resistant pneumococci and does not cover Listeria in this age group.",
       "Penicillin G alone": "Penicillin monotherapy is inadequate empirically because of resistance.",
       "Vancomycin and gentamicin": "Gentamicin penetrates the CSF poorly and adds nothing against pneumococcus.",
       "Ampicillin and gentamicin": "That is a neonatal regimen and misses resistant pneumococci."},
  table=MENINGITIS_AGE),

"Viridans strep: subacute endocarditis": dict(d="medium",
  why={"Protein A": "Protein A is an S. aureus factor that binds IgG.",
       "Lipoteichoic acid–bound M protein": "M protein belongs to group A strep.",
       "Polyribosylribitol phosphate capsule": "PRP is the H. influenzae type b capsule.",
       "Pili with IgA protease": "IgA protease aids mucosal colonization by other organisms and does not bind vegetations."},
  table=STREP),

"S. gallolyticus: colon cancer": dict(d="medium",
  why={"Transesophageal echocardiogram of the tricuspid": "Echocardiography is part of endocarditis care, but tricuspid imaging does not address the key association.",
       "Upper endoscopy": "The association is with colonic, not gastric or duodenal, disease.",
       "Dental radiographs": "Dental sources suggest viridans strep endocarditis instead.",
       "HIV antibody testing": "This organism does not signal HIV infection."},
  table=STREP),

"Enterococcus: identification": dict(d="easy",
  why={"Streptococcus gallolyticus": "S. gallolyticus is bile esculin-positive but cannot grow in 6.5% NaCl.",
       "Staphylococcus saprophyticus": "S. saprophyticus is catalase-positive and forms clusters.",
       "Streptococcus agalactiae": "GBS is beta-hemolytic, CAMP-positive, and does not tolerate 6.5% salt.",
       "Streptococcus pyogenes": "GAS is PYR-positive but is beta-hemolytic and bile esculin-negative."},
  table=STREP),

"Enterococcus: treatment & synergy": dict(d="hard",
  c="The cell wall agent lets the aminoglycoside enter the cell",
  o={"Aminoglycosides inhibit": "Aminoglycosides inhibit the beta-lactamases enterococci produce",
     "Enterococci are intrinsically": "Enterococci are intrinsically resistant to ampicillin alone",
     "The combination prevents": "The combination prevents biofilm from forming on the valve",
     "Aminoglycosides are required to cross": "Only aminoglycosides penetrate the vegetation itself"},
  why={"Aminoglycosides inhibit the beta-lactamases": "Aminoglycosides do not inhibit beta-lactamases; inhibitors such as sulbactam do.",
       "Enterococci are intrinsically resistant to ampicillin alone": "E. faecalis is usually ampicillin-susceptible; ampicillin is simply not bactericidal alone.",
       "The combination prevents biofilm": "Synergy is about killing, not biofilm prevention.",
       "Only aminoglycosides penetrate the vegetation": "Both drugs reach the vegetation; the issue is bactericidal activity."}),

"Enterococcus: VRE": dict(d="medium",
  c="D-Ala-D-Lac precursors; use linezolid or daptomycin",
  o={"Altered PBP2a": "Altered PBP2a target; use ceftaroline",
     "Plasmid β-lactamase": "Plasmid beta-lactamase; use ampicillin-sulbactam",
     "Efflux pump": "Drug efflux pump; use tetracycline",
     "Methylated 23S rRNA": "Methylated 23S rRNA; use azithromycin"},
  why={"Altered PBP2a target": "PBP2a explains MRSA, not vancomycin resistance.",
       "Plasmid beta-lactamase": "Beta-lactamase does not degrade vancomycin, which is a glycopeptide.",
       "Drug efflux pump": "Efflux is not the mechanism of vanA resistance, and tetracyclines are not used for this bacteremia.",
       "Methylated 23S rRNA": "That confers macrolide resistance and is unrelated to cell wall targets."},
  table=RESISTANCE),

"S. aureus: vancomycin mechanism": dict(d="medium",
  c="Binds D-Ala-D-Ala precursors, blocking cross-linking",
  o={"Binds PBPs covalently": "Binds penicillin-binding proteins to block transpeptidation",
     "Inhibits the bactoprenol": "Inhibits the bactoprenol lipid carrier in the membrane",
     "Inserts into the membrane": "Inserts into the membrane, forming calcium-dependent channels",
     "Inhibits the conversion of UDP": "Inhibits conversion of UDP-GlcNAc to UDP-MurNAc"},
  why={"Binds penicillin-binding proteins": "That is how beta-lactams work; vancomycin binds the substrate instead of the enzyme.",
       "Inhibits the bactoprenol lipid carrier": "That is bacitracin, which is used only topically.",
       "Inserts into the membrane": "That is daptomycin, which is inactivated by pulmonary surfactant.",
       "Inhibits conversion of UDP-GlcNAc": "That is fosfomycin, used as a single dose for cystitis."},
  table=CELL_WALL),

"S. aureus: hemolysis & catalase": dict(d="easy",
  why={"Staphylococcus aureus": "All staphylococci are catalase-positive and would bubble.",
       "Staphylococcus epidermidis": "Also a catalase-positive staphylococcus.",
       "Micrococcus luteus": "Micrococcus is catalase-positive as well.",
       "Staphylococcus saprophyticus": "Another catalase-positive staphylococcus."},
  table=GPC_ALGORITHM),

"S. aureus: skin abscess management": dict(d="medium",
  why={"Exfoliative toxin": "Exfoliative toxin causes bullous impetigo and scalded skin, not a deep fluctuant abscess.",
       "Enterotoxin B": "Enterotoxins cause food poisoning and can act as superantigens.",
       "Coagulase": "Coagulase forms a fibrin wall and identifies S. aureus, but it does not destroy leukocytes.",
       "Protein A": "Protein A impairs opsonization but is present in nearly all strains, not just community MRSA."}),
}
