from tables import *
R = {
"Meningitis by age": dict(d="medium",
  c="Ampicillin with cefotaxime or gentamicin",
  o={"Ceftriaxone plus vancomycin": "Ceftriaxone combined with vancomycin",
     "Vancomycin alone": "Vancomycin given alone",
     "Acyclovir alone": "Acyclovir given alone",
     "Azithromycin plus ceftriaxone": "Azithromycin combined with ceftriaxone"},
  why={"Ceftriaxone combined with vancomycin": "That misses Listeria and risks kernicterus in a neonate.",
       "Vancomycin given alone": "Vancomycin misses all three common neonatal Gram-negative and Listeria pathogens.",
       "Acyclovir given alone": "Acyclovir is added when HSV is suspected but does not treat bacteria.",
       "Azithromycin combined with ceftriaxone": "That combination does not cover Listeria or neonatal Gram-negatives."},
  table=MENINGITIS_AGE),

"CSF interpretation": dict(d="medium",
  why={"Enterovirus": "Enteroviral meningitis has normal glucose and a milder course.",
       "Neisseria meningitidis": "Bacterial meningitis is acute with neutrophils, not lymphocytes.",
       "HSV-1": "HSV encephalitis causes acute temporal lobe findings with red cells in CSF.",
       "Guillain-Barré syndrome": "GBS causes high protein with a normal cell count and no fever."},
  table=CSF),

"Pneumonia by host": dict(d="easy",
  why={"Healthy college student with walking pneumonia — Klebsiella pneumoniae": "Walking pneumonia in young adults is usually Mycoplasma.",
       "Post-influenza cavitary pneumonia — Mycoplasma pneumoniae": "Post-influenza cavitary disease is typically S. aureus.",
       "Alcohol use disorder with currant-jelly sputum — Legionella": "Currant-jelly sputum is classic for Klebsiella.",
       "Neonate in the first week — Streptococcus pneumoniae": "Early neonatal pneumonia is usually group B strep or E. coli."},
  table=ATYPICAL_PNA),

"UTI organisms & urinalysis": dict(d="medium",
  why={"The organism is urease-positive": "Urease raises urine pH but does not affect the nitrite test.",
       "The organism has no cell wall": "Enterococcus has a cell wall; Mycoplasma is the one that does not.",
       "The urine pH was too low": "Urine pH does not determine nitrite conversion.",
       "Nitrite is positive only in pyelonephritis": "Nitrite reflects the organism, not the site of infection."},
  table=LACTOSE),

"Osteomyelitis associations": dict(d="easy",
  why={"Sickle cell disease — Pasteurella multocida": "Sickle cell disease is associated with Salmonella.",
       "Cat bite — Salmonella": "Cat bites transmit Pasteurella multocida.",
       "Injection drug use — Mycobacterium tuberculosis only": "Injection use is associated with S. aureus, Pseudomonas, and Candida.",
       "Vertebral osteomyelitis in a TB-endemic region — Kingella kingae": "Vertebral TB is Pott disease; Kingella affects toddlers."}),

"Bloody vs watery diarrhea": dict(d="easy",
  why={"Vibrio cholerae": "Cholera causes massive watery diarrhea without blood.",
       "Enterotoxigenic E. coli": "ETEC is toxin-mediated and non-inflammatory.",
       "Giardia lamblia": "Giardia causes fatty, non-bloody diarrhea.",
       "Norovirus": "Norovirus causes watery diarrhea and vomiting."},
  table=DIARRHEA),

"Food poisoning by incubation": dict(d="easy",
  why={"Clostridium perfringens": "C. perfringens takes 8-16 hours because toxin is made in the gut.",
       "Salmonella enteritidis": "Salmonella needs 1-3 days to invade and cause symptoms.",
       "Listeria monocytogenes": "Listeria has an incubation of days to weeks.",
       "Campylobacter jejuni": "Campylobacter takes 2-5 days to cause illness."},
  table=DIARRHEA),

"TORCH infections": dict(d="medium",
  why={"CMV — diffuse intracranial calcifications with hydrocephalus": "CMV causes periventricular calcifications; diffuse ones suggest toxoplasmosis.",
       "Toxoplasmosis — periventricular calcifications and deafness as the main finding": "Those findings describe CMV.",
       "Syphilis — limb hypoplasia and cicatricial scars": "Limb hypoplasia and scars indicate congenital varicella.",
       "HSV — Hutchinson teeth": "Hutchinson teeth indicate congenital syphilis."},
  table=TORCH),

"Genital ulcers": dict(d="medium",
  why={"Painless indurated ulcer with rubbery nodes — HSV-2": "That description fits syphilis; HSV causes painful vesicles.",
       "Painful grouped vesicles on an erythematous base — Treponema pallidum": "Vesicles indicate herpes, not syphilis.",
       "Painless beefy-red ulcer that bleeds easily, with Donovan bodies — Chlamydia trachomatis L1–L3": "Donovan bodies indicate Klebsiella granulomatis.",
       "Painless transient papule then painful inguinal buboes — Klebsiella granulomatis": "That sequence describes LGV."},
  table=GENITAL_ULCERS),

"Childhood rashes": dict(d="easy",
  why={"Slapped cheeks and a lacy rash — rubella": "Slapped cheeks indicate parvovirus B19.",
       "Sandpaper rash, strawberry tongue, circumoral pallor — parvovirus B19": "That is scarlet fever from group A strep.",
       "Cough, coryza, conjunctivitis, Koplik spots, then a descending rash — coxsackie A": "That describes measles.",
       "Vesicles on the palms, soles, and mouth — measles": "That describes hand-foot-and-mouth disease from coxsackie A."},
  table=RASHES),

"Rashes on palms and soles": dict(d="easy",
  why={"Epidemic typhus": "Typhus spares the palms and soles and spreads outward from the trunk.",
       "Pityriasis rosea": "Pityriasis rosea follows skin lines on the trunk.",
       "Varicella in children": "Varicella is centripetal and spares palms and soles.",
       "Tinea versicolor": "Tinea versicolor affects the trunk and shoulders."},
  table=RICKETTSIAE),

"Live vaccines": dict(d="easy",
  why={"Tdap": "Tdap is a toxoid and acellular vaccine recommended in every pregnancy.",
       "Inactivated influenza vaccine": "Inactivated influenza vaccine is recommended in pregnancy.",
       "Hepatitis B vaccine": "The HBV vaccine is recombinant and safe in pregnancy.",
       "RSV prefusion F vaccine": "The maternal RSV vaccine is recommended at 32-36 weeks."},
  table=VACCINES),

"Vaccine types": dict(d="easy",
  why={"Hepatitis B": "The HBV vaccine is recombinant surface antigen, not a toxoid.",
       "HPV": "The HPV vaccine uses virus-like particles.",
       "Varicella": "Varicella vaccine is live attenuated.",
       "Pneumococcal conjugate": "PCV is polysaccharide conjugated to a carrier protein."},
  table=VACCINES),

"Passive immunization": dict(d="medium",
  c="Newborn of an HBsAg-positive mother",
  o={"Influenza exposure in a healthy adult": "Influenza exposure in an otherwise healthy adult",
     "Measles exposure in an immune adult": "Measles exposure in an already immune adult",
     "Pertussis exposure in a vaccinated adult": "Pertussis exposure in a vaccinated adult",
     "Norovirus exposure on a cruise ship": "Norovirus exposure aboard a cruise ship"},
  why={"Influenza exposure in an otherwise healthy adult": "Influenza is managed with vaccination and antivirals, not immune globulin.",
       "Measles exposure in an already immune adult": "An immune adult needs nothing; immune globulin is for susceptible high-risk contacts.",
       "Pertussis exposure in a vaccinated adult": "Contacts receive azithromycin prophylaxis, not antibody.",
       "Norovirus exposure aboard a cruise ship": "No vaccine or immune globulin exists for norovirus."},
  table=VACCINES),

"Bite wounds": dict(d="medium",
  why={"Pasteurella multocida": "Pasteurella comes from cat and dog mouths rather than human bites.",
       "Capnocytophaga canimorsus": "Capnocytophaga follows dog bites in asplenic patients.",
       "Bartonella henselae": "Bartonella follows cat scratches.",
       "Francisella tularensis": "Francisella comes from rabbits, ticks, and deer flies."},
  table=ZOONOSES),

"Infections and cancer": dict(d="medium",
  why={"HHV-8 — nasopharyngeal carcinoma": "HHV-8 causes Kaposi sarcoma; EBV causes nasopharyngeal carcinoma.",
       "HTLV-1 — Burkitt lymphoma": "HTLV-1 causes adult T-cell leukemia; EBV causes Burkitt lymphoma.",
       "H. pylori — esophageal adenocarcinoma": "H. pylori causes gastric adenocarcinoma and MALT lymphoma.",
       "Clonorchis sinensis — hepatocellular carcinoma from aflatoxin": "Clonorchis causes cholangiocarcinoma; aflatoxin comes from Aspergillus."}),

"Hospital-acquired infections": dict(d="easy",
  why={"Streptococcus pyogenes": "GAS causes skin and soft tissue infection rather than catheter-associated UTI.",
       "Legionella pneumophila": "Legionella causes pneumonia from water aerosols.",
       "Neisseria gonorrhoeae": "Gonorrhea is sexually transmitted.",
       "Mycoplasma pneumoniae": "Mycoplasma causes atypical pneumonia."},
  table=LACTOSE),

"Infections in immune deficiency": dict(d="medium",
  c="Bruton agammaglobulinemia — encapsulated bacteria",
  o={"Terminal complement deficiency — Pneumocystis": "Terminal complement deficiency — Pneumocystis pneumonia",
     "DiGeorge syndrome — recurrent Neisseria": "DiGeorge syndrome — recurrent Neisseria bacteremia",
     "Chronic granulomatous disease — recurrent Giardia": "Chronic granulomatous disease — recurrent giardiasis",
     "Asplenia — Candida esophagitis": "Asplenia — recurrent Candida esophagitis"},
  why={"Terminal complement deficiency — Pneumocystis pneumonia": "Terminal complement defects predispose to Neisseria.",
       "DiGeorge syndrome — recurrent Neisseria bacteremia": "DiGeorge is a T-cell defect, so fungal and viral infections predominate.",
       "Chronic granulomatous disease — recurrent giardiasis": "Giardia is associated with antibody deficiency; CGD gives catalase-positive infections.",
       "Asplenia — recurrent Candida esophagitis": "Asplenia predisposes to encapsulated bacteria; Candida esophagitis suggests T-cell deficiency."},
  table=IMMUNODEF),

"Epidemiology: vectors": dict(d="easy",
  c="Aedes mosquito — dengue, Zika, and yellow fever",
  o={"Anopheles mosquito — West Nile virus": "Anopheles mosquito — West Nile virus",
     "Ixodes tick — Rocky Mountain spotted fever": "Ixodes tick — Rocky Mountain spotted fever",
     "Tsetse fly — Chagas disease": "Tsetse fly — Chagas disease",
     "Sandfly — African sleeping sickness": "Sandfly — African sleeping sickness"},
  why={"Anopheles mosquito — West Nile virus": "Anopheles transmits malaria; Culex transmits West Nile.",
       "Ixodes tick — Rocky Mountain spotted fever": "RMSF is transmitted by Dermacentor.",
       "Tsetse fly — Chagas disease": "Tsetse flies transmit African trypanosomiasis; reduviid bugs transmit Chagas.",
       "Sandfly — African sleeping sickness": "Sandflies transmit leishmaniasis."},
  table=TICKBORNE),

"Epidemiology: geography": dict(d="easy",
  why={"Great Lakes and Mississippi/Ohio basins — Paracoccidioides": "That region is home to Blastomyces and Histoplasma.",
       "Latin America — Blastomyces": "Latin America is where Paracoccidioides is found.",
       "Ohio and Mississippi River valleys — Coccidioides": "Those valleys are home to Histoplasma.",
       "Worldwide pigeon droppings — Histoplasma only": "Pigeon droppings are associated with Cryptococcus as well."},
  table=DIMORPHIC),
}
