from tables import *
R = {
"Giardia": dict(d="easy",
  why={"Asplenia": "Asplenia predisposes to encapsulated bacteria, not protozoa.",
       "Terminal complement deficiency": "That causes recurrent Neisseria infection.",
       "Chronic granulomatous disease": "CGD causes catalase-positive bacterial and fungal infections.",
       "Sickle cell disease": "Sickle cell disease predisposes to Salmonella and encapsulated organisms."},
  table=INTESTINAL_PROTOZOA),

"Entamoeba histolytica": dict(d="medium",
  c="Metronidazole, then a luminal agent such as paromomycin",
  o={"Surgical drainage alone": "Surgical drainage of the abscess alone",
     "Albendazole": "A course of oral albendazole",
     "Praziquantel": "A course of oral praziquantel",
     "Ivermectin": "A course of oral ivermectin"},
  why={"Surgical drainage of the abscess alone": "Most amebic abscesses resolve with drug therapy, and drainage alone leaves infection.",
       "A course of oral albendazole": "Albendazole treats helminths.",
       "A course of oral praziquantel": "Praziquantel treats flukes and tapeworms.",
       "A course of oral ivermectin": "Ivermectin treats Strongyloides and filariae."},
  table=INTESTINAL_PROTOZOA),

"Cryptosporidium": dict(d="medium",
  c="Chlorine-resistant oocysts; ART is the key treatment in AIDS",
  o={"It is killed by standard chlorination": "It is reliably killed by standard water chlorination",
     "It invades the liver": "It invades the liver and forms abscesses",
     "Metronidazole cures it": "Metronidazole reliably cures it in AIDS patients",
     "It is a helminth": "It is a helminth whose eggs are passed in stool"},
  why={"It is reliably killed by standard water chlorination": "Oocysts resist chlorine, which is why filtration is needed.",
       "It invades the liver and forms abscesses": "Liver abscess is caused by Entamoeba histolytica.",
       "Metronidazole reliably cures it in AIDS patients": "Metronidazole is ineffective; nitazoxanide helps only with immune recovery.",
       "It is a helminth whose eggs are passed in stool": "It is a protozoan that sheds acid-fast oocysts."},
  table=INTESTINAL_PROTOZOA),

"Toxoplasma: AIDS": dict(d="medium",
  c="Pyrimethamine, sulfadiazine, and leucovorin",
  o={"Amphotericin B plus flucytosine": "Amphotericin B combined with flucytosine",
     "Metronidazole": "A course of intravenous metronidazole",
     "Albendazole plus steroids": "Albendazole combined with corticosteroids",
     "Whole-brain radiation": "Whole-brain radiation therapy"},
  why={"Amphotericin B combined with flucytosine": "That treats cryptococcal meningitis, which causes headache without ring lesions.",
       "A course of intravenous metronidazole": "Metronidazole does not treat Toxoplasma.",
       "Albendazole combined with corticosteroids": "That treats neurocysticercosis, which shows cysts with a scolex.",
       "Whole-brain radiation therapy": "Radiation treats CNS lymphoma, the main alternative diagnosis."},
  table=BLOOD_TISSUE_PROTOZOA),

"Toxoplasma: congenital": dict(d="easy",
  c="Avoid cat litter and undercooked meat",
  o={"Avoid unpasteurized soft cheeses only": "Avoid only unpasteurized soft cheeses",
     "Get the MMR vaccine during pregnancy": "Receive the MMR vaccine during pregnancy",
     "Avoid mosquito exposure": "Avoid all mosquito exposure",
     "Take prophylactic acyclovir": "Take prophylactic acyclovir from 36 weeks"},
  why={"Avoid only unpasteurized soft cheeses": "That prevents listeriosis, which causes sepsis rather than this triad.",
       "Receive the MMR vaccine during pregnancy": "MMR is live and contraindicated in pregnancy.",
       "Avoid all mosquito exposure": "That would reduce Zika risk, which causes microcephaly with different calcifications.",
       "Take prophylactic acyclovir from 36 weeks": "That reduces neonatal herpes in women with genital HSV."},
  table=TORCH),

"P. falciparum: severe malaria": dict(d="hard",
  c="PfEMP1 on infected cells binds and blocks brain capillaries",
  o={"Hypnozoites in the liver": "Hypnozoites in the liver release merozoites into CSF",
     "Direct invasion of neurons": "Direct invasion of neurons by sporozoites",
     "Hemolysis-induced kernicterus": "Kernicterus produced by brisk hemolysis",
     "Immune complex vasculitis": "Immune complex vasculitis of the cerebral arteries"},
  why={"Hypnozoites in the liver release merozoites into CSF": "P. falciparum forms no hypnozoites, and they never enter CSF.",
       "Direct invasion of neurons by sporozoites": "Sporozoites go to hepatocytes, not neurons.",
       "Kernicterus produced by brisk hemolysis": "Kernicterus is a neonatal problem from unconjugated bilirubin.",
       "Immune complex vasculitis of the cerebral arteries": "Cerebral malaria is obstructive sequestration, not vasculitis."},
  table=MALARIA),

"P. falciparum: blood smear": dict(d="medium",
  why={"P. vivax; it infects only reticulocytes": "Vivax enlarges red cells and shows Schüffner dots, which are absent here.",
       "P. malariae; it infects only old RBCs": "P. malariae shows band forms and low parasitemia.",
       "P. ovale; it infects only young RBCs": "P. ovale also enlarges cells and shows stippling.",
       "Babesia microti; it forms Maltese crosses": "Babesia shows no gametocytes or pigment and follows a tick bite."},
  table=MALARIA),

"P. vivax: hypnozoites": dict(d="medium",
  why={"Chloroquine; hemoglobin electrophoresis": "Chloroquine clears blood stages but leaves hypnozoites untouched.",
       "Artesunate; ECG": "Artesunate treats severe acute malaria and does not act on liver stages.",
       "Mefloquine; psychiatric screening": "Mefloquine is a blood-stage drug used for prophylaxis.",
       "Doxycycline; pregnancy test": "Doxycycline is a prophylactic partner drug and does not kill hypnozoites."},
  table=MALARIA),

"Malaria: life cycle": dict(d="easy",
  c="Sporozoites, which go first to the liver",
  o={"Merozoites, which infect red blood cells directly": "Merozoites, which infect red cells directly",
     "Gametocytes, which mature in the spleen": "Gametocytes, which mature within the spleen",
     "Trophozoites, which infect macrophages": "Trophozoites, which infect tissue macrophages",
     "Oocysts, which lodge in the lung": "Oocysts, which lodge within the lung"},
  why={"Merozoites, which infect red cells directly": "Merozoites are released from the liver later, not injected by the mosquito.",
       "Gametocytes, which mature within the spleen": "Gametocytes are taken up by mosquitoes and mature in the insect.",
       "Trophozoites, which infect tissue macrophages": "Trophozoites are an intraerythrocytic stage.",
       "Oocysts, which lodge within the lung": "Oocysts form on the mosquito midgut wall."},
  table=MALARIA),

"Malaria: host protective factors": dict(d="medium",
  why={"Duffy antigen positivity": "Being Duffy-negative protects against P. vivax; positivity does not protect.",
       "Blood group O deficiency": "Blood group O is associated with milder falciparum disease.",
       "Hereditary hemochromatosis": "Iron overload does not protect and may worsen some infections.",
       "Selective IgA deficiency": "IgA deficiency affects mucosal defense, not malaria."},
  table=MALARIA),

"Antimalarial drugs": dict(d="hard",
  c="It blocks heme polymerization; PfCRT effluxes it",
  o={"It inhibits dihydrofolate reductase": "It inhibits dihydrofolate reductase; DHFR mutations cause resistance",
     "It inhibits the mitochondrial electron": "It inhibits the mitochondrial electron transport chain",
     "It forms free radicals by reacting with iron": "It forms free radicals with heme iron; Kelch13 alters this",
     "It blocks the Duffy antigen": "It blocks the Duffy antigen on red cell surfaces"},
  why={"It inhibits dihydrofolate reductase": "That is pyrimethamine and proguanil.",
       "It inhibits the mitochondrial electron transport chain": "That is atovaquone, where cytochrome b mutations cause resistance.",
       "It forms free radicals with heme iron": "That is the artemisinin mechanism.",
       "It blocks the Duffy antigen on red cell surfaces": "No antimalarial works this way; Duffy status is a host factor."},
  table=MALARIA),

"Babesia": dict(d="medium",
  why={"Chloroquine": "Chloroquine treats malaria, not Babesia.",
       "Doxycycline alone": "Doxycycline treats the other Ixodes-borne infections but not babesiosis.",
       "Primaquine": "Primaquine eradicates malarial liver stages, which Babesia does not have.",
       "Albendazole": "Albendazole treats helminths."},
  table=TICKBORNE),

"Chagas disease": dict(d="medium",
  c="Reduviid bug feces rubbed into the bite or eye",
  o={"Bite of a tsetse fly": "The bite of an infected tsetse fly",
     "Bite of a female sandfly": "The bite of a female sandfly",
     "Anopheles mosquito bite": "The bite of an Anopheles mosquito",
     "Eating undercooked pork": "Eating undercooked pork products"},
  why={"The bite of an infected tsetse fly": "Tsetse flies transmit African trypanosomiasis.",
       "The bite of a female sandfly": "Sandflies transmit leishmaniasis.",
       "The bite of an Anopheles mosquito": "Anopheles transmits malaria.",
       "Eating undercooked pork products": "Pork transmits Taenia solium and Trichinella."},
  table=BLOOD_TISSUE_PROTOZOA),

"African trypanosomiasis": dict(d="hard",
  c="Antigenic variation of the surface glycoprotein coat",
  o={"Periodic rupture of infected red blood cells": "Periodic rupture of infected red blood cells",
     "Reactivation of hypnozoites": "Reactivation of dormant hypnozoites in the liver",
     "Cyclic release of endotoxin": "Cyclic release of bacterial endotoxin",
     "Formation of cysts in skeletal muscle": "Formation of cysts within skeletal muscle"},
  why={"Periodic rupture of infected red blood cells": "That is malaria, which shows intraerythrocytic parasites.",
       "Reactivation of dormant hypnozoites in the liver": "Hypnozoites belong to P. vivax and P. ovale.",
       "Cyclic release of bacterial endotoxin": "Trypanosomes are protozoa and have no endotoxin.",
       "Formation of cysts within skeletal muscle": "Muscle cysts occur in trichinellosis and cysticercosis."},
  table=BLOOD_TISSUE_PROTOZOA),

"Visceral leishmaniasis": dict(d="medium",
  why={"Tsetse fly; suramin": "The tsetse fly transmits sleeping sickness.",
       "Reduviid bug; benznidazole": "The reduviid bug transmits Chagas disease.",
       "Anopheles mosquito; artemether": "Anopheles transmits malaria, which does not fill macrophages with amastigotes.",
       "Ixodes tick; atovaquone": "Ixodes transmits babesiosis, which infects red cells."},
  table=BLOOD_TISSUE_PROTOZOA),

"Cutaneous leishmaniasis": dict(d="medium",
  why={"Cutaneous anthrax": "Anthrax forms a painless black eschar within days, with marked edema.",
       "Sporotrichosis": "Sporotrichosis spreads as a chain of nodules along lymphatics.",
       "Pyoderma gangrenosum": "Pyoderma gangrenosum has violaceous undermined borders and is linked to IBD.",
       "Mycobacterium marinum infection": "M. marinum follows aquarium or water exposure."},
  table=BLOOD_TISSUE_PROTOZOA),

"Trichomonas vaginalis": dict(d="easy",
  c="Metronidazole for her and for her partners",
  o={"Metronidazole for her only": "Metronidazole given to her alone",
     "Fluconazole": "A single oral dose of fluconazole",
     "Ceftriaxone plus doxycycline": "Ceftriaxone combined with doxycycline",
     "Clindamycin cream": "Intravaginal clindamycin cream"},
  why={"Metronidazole given to her alone": "Untreated partners cause rapid reinfection in this STI.",
       "A single oral dose of fluconazole": "Fluconazole treats candidal vaginitis, which has normal pH.",
       "Ceftriaxone combined with doxycycline": "That treats gonorrhea and chlamydia.",
       "Intravaginal clindamycin cream": "Clindamycin treats bacterial vaginosis."},
  table=VAGINITIS),

"Naegleria fowleri": dict(d="medium",
  why={"Hematogenous spread from a skin ulcer": "There is no skin lesion, and this organism does not spread from skin.",
       "Through a contact lens injury to the cornea": "That is the Acanthamoeba keratitis route.",
       "Retrograde axonal transport from a bite": "That describes rabies virus.",
       "Through infected mosquito saliva": "No mosquito vector is involved."},
  table=BLOOD_TISSUE_PROTOZOA),

"Acanthamoeba keratitis": dict(d="medium",
  why={"Pseudomonas aeruginosa": "Pseudomonas keratitis progresses rapidly with purulent discharge and a corneal ulcer.",
       "Herpes simplex virus": "HSV causes a dendritic corneal ulcer with reduced sensation.",
       "Onchocerca volvulus": "Onchocerca causes keratitis after blackfly exposure in endemic regions.",
       "Naegleria fowleri": "Naegleria causes fatal meningoencephalitis, not keratitis."},
  table=BLOOD_TISSUE_PROTOZOA),
}
