from tables import *
R = {
"Coxsackie A: hand-foot-mouth": dict(d="easy",
  why={"An enveloped dsDNA herpesvirus": "Herpetic gingivostomatitis affects the mouth but not palms and soles.",
       "A non-enveloped ssDNA parvovirus": "Parvovirus B19 causes slapped cheeks and a lacy rash.",
       "An enveloped negative-sense paramyxovirus": "Measles causes a descending rash with Koplik spots.",
       "A segmented dsRNA reovirus": "Rotavirus causes diarrhea, not a vesicular rash."},
  table=RNA_FAMILIES),

"Poliovirus": dict(d="medium",
  why={"Dorsal root ganglion sensory neurons": "Sensation is intact, which excludes sensory ganglion involvement.",
       "Schwann cells of peripheral nerves": "Demyelination causes Guillain-Barre, which is symmetric and ascending.",
       "Neuromuscular junction acetylcholine receptors": "That is myasthenia gravis, with fatigable weakness.",
       "Upper motor neurons in the corticospinal tract": "Upper motor neuron injury causes spasticity and hyperreflexia."}),

"Rhinovirus": dict(d="easy",
  why={"It is enveloped": "Rhinoviruses are non-enveloped like other picornaviruses.",
       "It has a DNA genome": "It has a positive-sense RNA genome.",
       "It binds CD4": "It binds ICAM-1; CD4 is the HIV receptor.",
       "It has a segmented genome": "Picornavirus genomes are not segmented."},
  table=RNA_FAMILIES),

"Enteroviral meningitis": dict(d="easy",
  c="Enteroviruses such as echovirus and coxsackievirus",
  o={"Neisseria meningitidis": "Neisseria meningitidis bacterial infection",
     "HSV-1": "Herpes simplex virus type 1 infection",
     "Cryptococcus neoformans": "Cryptococcus neoformans fungal infection",
     "Mycobacterium tuberculosis": "Mycobacterium tuberculosis infection"},
  why={"Neisseria meningitidis": "Bacterial meningitis shows neutrophils and low CSF glucose.",
       "Herpes simplex virus type 1": "HSV-1 causes encephalitis with focal deficits; HSV-2 causes meningitis less often.",
       "Cryptococcus neoformans": "Cryptococcal meningitis has low glucose and occurs in immunosuppression.",
       "Mycobacterium tuberculosis": "TB meningitis is subacute with very high protein and low glucose."},
  table=CSF),

"Norovirus": dict(d="easy",
  why={"Rotavirus": "Rotavirus mainly affects young children and is now vaccine-preventable.",
       "Enterotoxigenic E. coli": "ETEC causes traveler's diarrhea rather than explosive outbreaks on ships.",
       "Giardia lamblia": "Giardia causes subacute fatty diarrhea over weeks.",
       "Hepatitis A virus": "HAV causes hepatitis after a long incubation, not 48-hour vomiting."},
  table=DIARRHEA),

"Rotavirus": dict(d="medium",
  why={"Guillain-Barré syndrome": "That has been linked to influenza vaccination historically, not rotavirus vaccine.",
       "Febrile seizures": "Febrile seizures follow MMRV more than rotavirus vaccine.",
       "Vaccine-derived paralysis": "That is a risk of oral polio vaccine.",
       "Aseptic meningitis": "That was associated with certain mumps vaccine strains."},
  table=VACCINES),

"Dengue": dict(d="hard",
  c="Cross-reactive antibody enhances entry into Fc-bearing cells",
  o={"Her first infection made her immune": "Her first infection made her immune to every serotype",
     "The virus has become resistant": "The virus has become resistant to interferon",
     "Prior infection left latent virus": "Her prior infection left latent virus in the liver",
     "Her first infection destroyed her platelets": "Her first infection permanently destroyed platelets"},
  why={"Her first infection made her immune to every serotype": "Immunity is serotype-specific, which is why reinfection occurs.",
       "The virus has become resistant to interferon": "Interferon resistance does not explain the link to prior infection.",
       "Her prior infection left latent virus in the liver": "Flaviviruses do not establish latency.",
       "Her first infection permanently destroyed platelets": "Thrombocytopenia is acute and reversible."},
  table=ARBO),

"Yellow fever": dict(d="medium",
  c="A flavivirus spread by Aedes, with a live vaccine",
  o={"It is a filovirus": "A filovirus spread by bats and primates",
     "It is a bunyavirus": "A bunyavirus spread through rodent urine",
     "It is a hepatitis virus": "A hepatitis virus spread by the fecal-oral route",
     "It is a DNA virus": "A DNA virus replicating in hepatocyte nuclei"},
  why={"A filovirus spread by bats and primates": "That describes Ebola and Marburg, which spread by body fluid contact.",
       "A bunyavirus spread through rodent urine": "That describes hantavirus, which causes pulmonary or renal syndromes.",
       "A hepatitis virus spread by the fecal-oral route": "HAV and HEV cause hepatitis without a mosquito vector.",
       "A DNA virus replicating in hepatocyte nuclei": "That suggests hepatitis B, which is bloodborne."},
  table=ARBO),

"West Nile virus": dict(d="medium",
  why={"Poliovirus": "Polio is essentially eliminated in the US and affects unvaccinated children.",
       "Rabies virus": "Rabies causes hydrophobia and agitation after an animal exposure.",
       "HSV-1": "HSV encephalitis causes temporal lobe findings, not flaccid limb weakness.",
       "Eastern equine encephalitis alphavirus": "EEE is rare, occurs in the eastern US, and lacks the bird die-off clue."},
  table=ARBO),

"Zika virus": dict(d="medium",
  c="An Aedes-borne flavivirus also spread sexually",
  o={"It is a togavirus": "A togavirus spread only by respiratory droplets",
     "It is a herpesvirus": "A herpesvirus that becomes latent in neurons",
     "It is a parvovirus": "A parvovirus infecting erythroid precursor cells",
     "It is a picornavirus": "A picornavirus spread by the fecal-oral route"},
  why={"A togavirus spread only by respiratory droplets": "Rubella is the togavirus spread by droplets; Zika needs a vector.",
       "A herpesvirus that becomes latent in neurons": "Flaviviruses do not establish latency.",
       "A parvovirus infecting erythroid precursor cells": "Parvovirus B19 causes hydrops fetalis, not microcephaly.",
       "A picornavirus spread by the fecal-oral route": "Fecal-oral picornaviruses do not cause congenital microcephaly."},
  table=ARBO),

"Rubella: congenital": dict(d="medium",
  why={"Cytomegalovirus": "Congenital CMV causes periventricular calcifications and deafness, without PDA or cataracts.",
       "Parvovirus B19": "Parvovirus causes hydrops fetalis from fetal anemia.",
       "Measles virus": "Measles in pregnancy causes prematurity, not this triad.",
       "Zika virus": "Zika causes severe microcephaly with subcortical calcifications."},
  table=TORCH),

"SARS-CoV-2": dict(d="easy",
  c="Spike binds ACE2 and host TMPRSS2 primes fusion",
  o={"Hemagglutinin binds sialic acid": "Hemagglutinin binds sialic acid; neuraminidase releases virions",
     "The F protein binds ICAM-1": "The fusion (F) protein binds ICAM-1 on epithelium",
     "gp120 binds CD4": "The gp120 protein binds CD4 and the CCR5 co-receptor",
     "The virus enters through the P antigen": "The virus enters through the P antigen on red cell precursors"},
  why={"Hemagglutinin binds sialic acid": "That is influenza.",
       "The fusion (F) protein binds ICAM-1": "RSV uses an F protein, and ICAM-1 is the rhinovirus receptor.",
       "The gp120 protein binds CD4": "That is HIV.",
       "The virus enters through the P antigen": "That is parvovirus B19."},
  table=RNA_FAMILIES),

"Influenza: antigenic shift": dict(d="medium",
  c="Reassortment of genome segments in a co-infected host",
  o={"Point mutations in hemagglutinin": "Point mutations accumulating in hemagglutinin",
     "Recombination between two DNA": "Recombination between two DNA viruses",
     "Phenotypic mixing without genetic": "Phenotypic mixing with no genetic change",
     "Transposition of a viral oncogene": "Transposition of a viral oncogene"},
  why={"Point mutations accumulating in hemagglutinin": "That is antigenic drift, which causes seasonal epidemics rather than pandemics.",
       "Recombination between two DNA viruses": "Influenza is an RNA virus.",
       "Phenotypic mixing with no genetic change": "Phenotypic mixing is not heritable and cannot create a new strain.",
       "Transposition of a viral oncogene": "Influenza carries no oncogene."}),

"Influenza: treatment & complications": dict(d="medium",
  c="Staphylococcus aureus; it inhibits neuraminidase",
  o={"Streptococcus pyogenes": "Streptococcus pyogenes; it blocks hemagglutinin binding",
     "Pseudomonas aeruginosa": "Pseudomonas aeruginosa; it inhibits viral RNA polymerase",
     "Mycoplasma pneumoniae": "Mycoplasma pneumoniae; it blocks the M2 ion channel",
     "Legionella": "Legionella pneumophila; it inhibits viral uncoating"},
  why={"Streptococcus pyogenes": "GAS is a less common post-influenza pathogen, and oseltamivir does not block hemagglutinin.",
       "Pseudomonas aeruginosa": "Pseudomonas pneumonia occurs in ventilated or bronchiectatic patients.",
       "Mycoplasma pneumoniae": "Mycoplasma causes indolent walking pneumonia, and M2 blockers are amantadine.",
       "Legionella pneumophila": "Legionella comes from water aerosols, and uncoating inhibition is amantadine."}),

"Measles: Koplik spots": dict(d="easy",
  why={"Vitamin D": "Vitamin D does not alter measles outcomes.",
       "Zinc": "Zinc helps in diarrheal illness, not measles.",
       "Vitamin C": "Vitamin C has no established benefit here.",
       "Folic acid": "Folate does not affect measles severity."},
  table=PARAMYXO),

"Measles: complications": dict(d="medium",
  why={"Myocarditis; progressive multifocal leukoencephalopathy": "PML is caused by JC virus in immunosuppressed patients.",
       "Hepatitis; Reye syndrome": "Reye syndrome follows aspirin use in varicella or influenza.",
       "Orchitis; sterility": "Orchitis is a mumps complication.",
       "Aplastic crisis; hydrops fetalis": "Those are parvovirus B19 complications."},
  table=PARAMYXO),

"Mumps": dict(d="easy",
  why={"Hydrops fetalis": "That is a parvovirus B19 complication.",
       "Hepatocellular carcinoma": "HCC follows chronic hepatitis B or C.",
       "Guillain-Barré syndrome after gastroenteritis": "That follows Campylobacter infection.",
       "Kaposi sarcoma": "Kaposi sarcoma is caused by HHV-8."},
  table=PARAMYXO),

"RSV: bronchiolitis": dict(d="medium",
  c="The fusion (F) protein, which drives syncytium formation",
  o={"Hemagglutinin-neuraminidase (HN)": "The combined hemagglutinin-neuraminidase (HN) protein",
     "Hemagglutinin": "The hemagglutinin protein that binds sialic acid",
     "Neuraminidase": "The neuraminidase that releases budding virions",
     "Spike protein": "The spike protein that binds its cellular receptor"},
  why={"The combined hemagglutinin-neuraminidase (HN) protein": "HN is found on parainfluenza and mumps, not RSV.",
       "The hemagglutinin protein that binds sialic acid": "RSV lacks hemagglutinin, unlike other paramyxoviruses.",
       "The neuraminidase that releases budding virions": "RSV has no neuraminidase; that is an influenza protein.",
       "The spike protein that binds its cellular receptor": "Spike is the coronavirus attachment protein."},
  table=PARAMYXO),

"Parainfluenza: croup": dict(d="easy",
  why={"Haemophilus influenzae type b": "Hib causes epiglottitis with drooling and a thumb sign.",
       "Respiratory syncytial virus": "RSV causes wheezing bronchiolitis rather than stridor with a barking cough.",
       "Bordetella pertussis": "Pertussis causes paroxysmal coughing with a whoop, without stridor.",
       "Streptococcus pyogenes": "GAS causes pharyngitis, not subglottic narrowing."},
  table=PARAMYXO),

"Rabies": dict(d="medium",
  why={"Hematogenous spread through the choroid plexus": "Rabies virus travels within nerves and is rarely detected in blood.",
       "Infected monocytes crossing the blood-brain barrier": "It does not use a Trojan horse mechanism.",
       "Through the cribriform plate from the nasal mucosa only": "That route is used by Naegleria.",
       "Anterograde transport from the spinal cord": "Spread to the CNS is retrograde; anterograde movement occurs later, to salivary glands."}),

"Rabies: post-exposure prophylaxis": dict(d="medium",
  c="Wound washing, rabies immune globulin, and vaccine doses",
  o={"Rabies vaccine alone": "The rabies vaccine series alone",
     "Rabies immune globulin alone": "Rabies immune globulin alone",
     "Observe the patient": "Observation of the patient for symptoms",
     "Oral acyclovir": "A course of oral acyclovir"},
  why={"The rabies vaccine series alone": "Vaccine alone is too slow for an unvaccinated person; immune globulin bridges the gap.",
       "Rabies immune globulin alone": "Passive antibody wanes without active immunization.",
       "Observation of the patient for symptoms": "Once symptoms begin, rabies is nearly always fatal.",
       "A course of oral acyclovir": "Acyclovir has no activity against rabies virus."},
  table=VACCINES),

"Ebola": dict(d="medium",
  c="An enveloped filovirus spread by contact with body fluids",
  o={"It is spread mainly by Aedes": "A virus spread mainly by Aedes mosquitoes",
     "It is a DNA virus with a latent": "A DNA virus with a latent phase in neurons",
     "It is spread only by rodent": "A virus spread only by rodent urine aerosols",
     "It is a naked virus spread fecal-orally": "A naked virus spread by the fecal-oral route"},
  why={"A virus spread mainly by Aedes mosquitoes": "That describes dengue, Zika, and yellow fever.",
       "A DNA virus with a latent phase in neurons": "That describes herpesviruses.",
       "A virus spread only by rodent urine aerosols": "That describes hantavirus.",
       "A naked virus spread by the fecal-oral route": "That describes enteric viruses such as norovirus."},
  table=RNA_FAMILIES),

"Hantavirus": dict(d="medium",
  why={"Yersinia pestis from flea bites": "Plague causes buboes or pneumonic disease with a rodent-flea exposure.",
       "Coxiella burnetii from livestock": "Q fever causes atypical pneumonia and hepatitis.",
       "Coccidioides immitis from desert soil": "Coccidioidomycosis progresses over weeks with erythema nodosum.",
       "Influenza A from pigs": "Influenza does not cause this abrupt capillary leak syndrome with hemoconcentration."},
  table=RNA_FAMILIES),

"Segmented RNA viruses": dict(d="medium",
  why={"Paramyxovirus, rhabdovirus, filovirus": "These are non-segmented negative-sense viruses.",
       "Picornavirus, calicivirus, flavivirus": "These are non-segmented positive-sense viruses.",
       "Retrovirus, coronavirus, togavirus": "Retroviruses are diploid but not segmented.",
       "Hepadnavirus, herpesvirus, poxvirus": "These are DNA viruses."},
  table=RNA_FAMILIES),

"Positive vs negative sense RNA": dict(d="medium",
  why={"Negative-sense RNA viruses are all DNA viruses": "They are RNA viruses by definition.",
       "Positive-sense viruses always have envelopes": "Picornaviruses and caliciviruses are naked.",
       "Negative-sense genomes are single-stranded DNA": "Their genomes are RNA.",
       "Positive-sense genomes need reverse transcriptase": "Only retroviruses do; most are translated directly."},
  table=RNA_FAMILIES),

"HTLV-1": dict(d="hard",
  why={"EBV, via CD21 on B cells": "EBV causes B-cell lymphomas, not a CD4 T-cell leukemia with hypercalcemia.",
       "HHV-8, via LANA": "HHV-8 causes Kaposi sarcoma and effusion lymphoma.",
       "HPV, via E6 and E7": "HPV causes squamous cell carcinomas.",
       "HIV-1, via Nef": "HIV causes immunodeficiency and secondary lymphomas, not this leukemia."}),

"Prion disease": dict(d="hard",
  why={"Infection with a slow RNA virus lacking an envelope": "Prions contain no nucleic acid.",
       "Mutation in the huntingtin gene": "Huntington disease progresses over years with chorea and family history.",
       "Autoantibodies against NMDA receptors": "Anti-NMDA encephalitis causes psychiatric symptoms and seizures and often responds to immunotherapy.",
       "Accumulation of hyperphosphorylated tau": "Tau accumulates in Alzheimer disease, which progresses over years without myoclonus."}),
}
