from tables import *
R = {
"E. coli: UTI & culture": dict(d="medium",
  c="P fimbriae binding Gal-Gal on kidney epithelium",
  o={"K1 capsule": "The K1 polysialic acid capsule",
     "Shiga-like toxin": "Phage-encoded Shiga-like toxin",
     "Heat-stable enterotoxin": "Heat-stable enterotoxin raising cGMP",
     "Intimin with the translocated": "Intimin with its translocated receptor (Tir)"},
  why={"The K1 polysialic acid capsule": "K1 strains cause neonatal meningitis, not ascending UTI.",
       "Phage-encoded Shiga-like toxin": "Shiga-like toxin belongs to EHEC and causes bloody diarrhea and HUS.",
       "Heat-stable enterotoxin": "ST is an ETEC toxin causing traveler's diarrhea.",
       "Intimin with its translocated receptor": "Intimin and Tir mediate attaching and effacing lesions in EPEC and EHEC."},
  table=ECOLI),

"E. coli: ETEC": dict(d="medium",
  why={"Activates guanylyl cyclase, raising cGMP": "That is the heat-stable toxin, not the heat-labile one.",
       "Cleaves 28S rRNA": "That is Shiga toxin, which causes bloody diarrhea.",
       "Causes attaching-and-effacing": "A/E lesions are EPEC and EHEC, which do not act through cAMP.",
       "Disrupts tight junctions by glucosylating Rho": "Rho glucosylation is C. difficile toxin activity."},
  table=ECOLI),

"E. coli: EHEC & HUS": dict(d="medium",
  c="Removal of an adenine from 28S ribosomal RNA",
  o={"ADP-ribosylation of EF-2": "ADP-ribosylation of elongation factor 2",
     "ADP-ribosylation of Gs": "ADP-ribosylation of the Gs alpha subunit",
     "Activation of guanylyl cyclase": "Direct activation of guanylyl cyclase C",
     "Pore formation in RBC": "Pore formation within red cell membranes"},
  why={"ADP-ribosylation of elongation factor 2": "That is diphtheria and Pseudomonas exotoxin A, which do not cause HUS.",
       "ADP-ribosylation of the Gs alpha subunit": "Cholera and ETEC LT act this way and cause watery diarrhea.",
       "Direct activation of guanylyl cyclase C": "ETEC heat-stable toxin raises cGMP without bloody stools.",
       "Pore formation within red cell membranes": "Direct hemolysis would not injure glomerular endothelium or lower platelets."},
  table=ECOLI),

"E. coli: EIEC vs EPEC": dict(d="medium",
  why={"Enteroinvasive E. coli (EIEC)": "EIEC invades colonic mucosa and causes dysentery with fever.",
       "Enterotoxigenic E. coli (ETEC)": "ETEC is toxin-mediated and does not efface microvilli.",
       "Enterohemorrhagic E. coli (EHEC)": "EHEC also forms A/E lesions but adds Shiga-like toxin and bloody stools.",
       "Uropathogenic E. coli (UPEC)": "UPEC causes urinary infection, not diarrhea."},
  table=ECOLI),

"E. coli: neonatal meningitis": dict(d="medium",
  why={"P fimbriae": "P fimbriae mediate pyelonephritis in the urinary tract.",
       "Heat-labile toxin": "LT causes watery diarrhea, not meningitis.",
       "Type III secretion of Tir": "Tir injection produces intestinal A/E lesions.",
       "Vi antigen": "Vi is the Salmonella Typhi capsular antigen."},
  table=MENINGITIS_AGE),

"Klebsiella: aspiration pneumonia": dict(d="medium",
  why={"Swarming motility": "Swarming is characteristic of Proteus; Klebsiella is non-motile.",
       "Hydrogen sulfide production": "H2S production is a Salmonella and Proteus feature seen on selective agar.",
       "Pyoverdine pigment": "Pyoverdine is a Pseudomonas siderophore.",
       "A poly-D-glutamate capsule": "Protein capsules are unique to B. anthracis."},
  table=LACTOSE),

"Klebsiella: carbapenem resistance": dict(d="hard",
  why={"Extended-spectrum β-lactamase; cefepime": "ESBL producers remain carbapenem-susceptible, and cefepime is unreliable against them.",
       "PBP2a; ceftaroline": "PBP2a is the MRSA mechanism in a Gram-positive organism.",
       "AmpC β-lactamase; ceftriaxone": "AmpC does not usually destroy carbapenems, and ceftriaxone would fail.",
       "Altered D-Ala-D-Lac; daptomycin": "That is vancomycin resistance, and daptomycin has no Gram-negative activity."},
  table=RESISTANCE),

"Proteus: struvite stones": dict(d="easy",
  why={"Catalase": "Catalase breaks down hydrogen peroxide and does not alkalinize urine.",
       "Coagulase": "Coagulase identifies S. aureus, a Gram-positive coccus.",
       "β-lactamase": "Beta-lactamase causes drug resistance, not stone formation.",
       "Lecithinase": "Lecithinase is the C. perfringens alpha-toxin."},
  table=UREASE),

"Salmonella Typhi: typhoid fever": dict(d="hard",
  c="It has a Vi capsule and survives inside macrophages",
  o={"It has an animal reservoir": "It has an animal reservoir in poultry and reptiles",
     "It is non-motile and has a very low": "It is non-motile and has a very low infectious dose",
     "It mainly causes watery diarrhea": "It mainly causes watery diarrhea via a cAMP-raising toxin",
     "It is best treated with oral vancomycin": "It is best treated with oral vancomycin therapy"},
  why={"It has an animal reservoir in poultry and reptiles": "Non-typhoidal Salmonella has animal reservoirs; S. Typhi infects only humans.",
       "It is non-motile and has a very low infectious dose": "That describes Shigella; Salmonella is motile and needs a large inoculum.",
       "It mainly causes watery diarrhea via a cAMP-raising toxin": "That is cholera; typhoid is a systemic illness that often begins with constipation.",
       "It is best treated with oral vancomycin therapy": "Oral vancomycin acts only in the gut lumen and is used for C. difficile."},
  table=SALM_SHIG),

"Salmonella: stool culture": dict(d="medium",
  why={"Lactose fermentation; E. coli": "Lactose fermenters turn yellow-orange on this agar, not black.",
       "Swarming; Proteus": "Proteus can produce H2S but swarming is seen on blood agar, and the history points to Salmonella.",
       "Pyocyanin; Pseudomonas": "Pyocyanin is a blue-green pigment, not a black precipitate.",
       "Tellurite reduction; Corynebacterium": "Tellurite agar is used for diphtheria, not stool pathogens."},
  table=SALM_SHIG),

"Salmonella: non-typhoidal": dict(d="medium",
  c="Oral rehydration only, since antibiotics prolong shedding",
  o={"Ciprofloxacin for 14 days": "A 14-day course of oral ciprofloxacin",
     "IV ceftriaxone": "A course of intravenous ceftriaxone",
     "Cholecystectomy": "Cholecystectomy to prevent chronic carriage",
     "Oral vancomycin": "A course of oral vancomycin therapy"},
  why={"A 14-day course of oral ciprofloxacin": "Antibiotics do not shorten uncomplicated illness and can prolong carriage.",
       "A course of intravenous ceftriaxone": "IV therapy is reserved for severe or invasive disease and high-risk hosts.",
       "Cholecystectomy": "Surgery is considered only for chronic S. Typhi carriers with gallstones.",
       "A course of oral vancomycin therapy": "Vancomycin has no activity against Gram-negative organisms."},
  table=SALM_SHIG),

"Salmonella: sickle cell osteomyelitis": dict(d="easy",
  why={"Pasteurella multocida": "Pasteurella follows cat and dog bites.",
       "Pseudomonas aeruginosa": "Pseudomonas follows nail punctures through sneakers.",
       "Mycobacterium tuberculosis": "TB causes vertebral Pott disease over a longer course.",
       "Kingella kingae": "Kingella affects children under 4 without sickle cell disease."}),

"Shigella: pathogenesis": dict(d="medium",
  c="Acid resistance, so a tiny inoculum survives the stomach",
  o={"A polysaccharide capsule": "A polysaccharide capsule resisting phagocytosis",
     "Production of urease": "Production of urease to neutralize gastric acid",
     "Spore formation": "Formation of spores that survive gastric acid",
     "An animal reservoir": "An animal reservoir that amplifies the inoculum"},
  why={"A polysaccharide capsule": "Shigella is not encapsulated, and a capsule would not explain the low dose.",
       "Production of urease": "Urease buffering is how H. pylori survives, not Shigella.",
       "Formation of spores": "Shigella forms no spores.",
       "An animal reservoir": "Humans are the only reservoir for Shigella."},
  table=SALM_SHIG),

"Shigella vs Salmonella: host immunity": dict(d="medium",
  c="Salmonella is acid-labile and needs a large inoculum",
  o={"Salmonella is non-motile": "Salmonella is non-motile in the intestinal lumen",
     "Salmonella lacks flagella": "Salmonella lacks flagella and cannot swim",
     "Salmonella is an obligate": "Salmonella is an obligate intracellular organism",
     "Salmonella forms spores": "Salmonella forms spores within the stomach"},
  why={"Salmonella is non-motile in the intestinal lumen": "Salmonella is motile; Shigella is the non-motile one.",
       "Salmonella lacks flagella and cannot swim": "Salmonella has flagella, which is how it is serotyped (H antigen).",
       "Salmonella is an obligate intracellular organism": "It is facultative, growing on ordinary laboratory media.",
       "Salmonella forms spores within the stomach": "No enteric Gram-negative rod forms spores."},
  table=SALM_SHIG),

"Yersinia enterocolitica": dict(d="medium",
  why={"Campylobacter jejuni": "Campylobacter causes bloody diarrhea from poultry, not a normal appendix with adenitis.",
       "Shigella sonnei": "Shigella causes dysentery with small-volume bloody stools.",
       "Enterotoxigenic E. coli": "ETEC causes watery traveler's diarrhea without adenitis.",
       "Clostridium perfringens": "C. perfringens food poisoning resolves in a day without lymphadenopathy."},
  table=DIARRHEA),

"Vibrio cholerae: mechanism": dict(d="medium",
  c="The Gs alpha subunit, switching on adenylyl cyclase",
  o={"Gi α-subunit": "The Gi alpha subunit, inhibiting adenylyl cyclase",
     "Guanylyl cyclase C": "Guanylyl cyclase C, which raises cGMP",
     "Rho GTPase": "Rho GTPase, which controls the cytoskeleton",
     "Elongation factor 2": "Elongation factor 2, which drives translation"},
  why={"The Gi alpha subunit": "Gi ribosylation is pertussis toxin, which causes cough rather than diarrhea.",
       "Guanylyl cyclase C": "ETEC heat-stable toxin acts there, with milder watery diarrhea.",
       "Rho GTPase": "Rho is the C. difficile toxin target and causes colitis.",
       "Elongation factor 2": "EF-2 is the diphtheria toxin target."},
  table=TOXINS),

"Vibrio: culture": dict(d="hard",
  c="Sucrose fermentation; Vibrio tolerates alkaline pH and bile",
  o={"Lactose fermentation": "Lactose fermentation; Vibrio requires a high salt medium",
     "Hydrogen sulfide production": "Hydrogen sulfide production; Vibrio grows anaerobically",
     "Pigment production": "Pigment production; Vibrio needs factors X and V",
     "Urease activity": "Urease activity; Vibrio tolerates a strongly acid medium"},
  why={"Lactose fermentation": "TCBS contains sucrose, not lactose, and V. cholerae is not halophilic.",
       "Hydrogen sulfide production": "Vibrio is a facultative anaerobe and does not blacken this medium.",
       "Pigment production": "Factors X and V are Haemophilus requirements.",
       "Urease activity": "V. cholerae is acid-sensitive, which is why the infectious dose is high."},
  table=VIBRIO),

"Vibrio vulnificus": dict(d="medium",
  why={"Vibrio parahaemolyticus; hypochlorhydria": "V. parahaemolyticus causes self-limited gastroenteritis, not fulminant sepsis with bullae.",
       "Aeromonas hydrophila; diabetes": "Aeromonas causes wound infection after freshwater exposure.",
       "Staphylococcus aureus; injection drug use": "S. aureus sepsis is not linked to raw oysters.",
       "Pasteurella multocida; splenectomy": "Pasteurella follows animal bites."},
  table=VIBRIO),

"Campylobacter: Guillain-Barré": dict(d="medium",
  c="Molecular mimicry between bacterial LOS and gangliosides",
  o={"Direct invasion of peripheral": "Direct bacterial invasion of peripheral nerves",
     "A neurotoxin that blocks": "A neurotoxin that blocks acetylcholine release",
     "Immune complex deposition": "Immune complex deposition within the vasa nervorum",
     "Toxin-mediated inhibition": "Toxin-mediated inhibition of spinal glycine release"},
  why={"Direct bacterial invasion of peripheral nerves": "Campylobacter does not invade nerves; the damage is autoimmune.",
       "A neurotoxin that blocks acetylcholine release": "That is botulism, which causes descending paralysis without preceding diarrhea.",
       "Immune complex deposition within the vasa nervorum": "That mechanism causes vasculitic mononeuritis multiplex, as in polyarteritis nodosa.",
       "Toxin-mediated inhibition of spinal glycine release": "Blocking glycine causes tetanus, with rigidity rather than weakness."}),

"H. pylori: virulence & disease": dict(d="easy",
  why={"Catalase": "Catalase counters oxidative killing but does not neutralize gastric acid.",
       "Coagulase": "Coagulase is an S. aureus enzyme.",
       "Lipase": "Lipase does not protect against acid.",
       "Mucinase alone": "Mucus penetration helps, but ammonia production is what neutralizes acid."},
  table=UREASE),

"H. pylori: treatment": dict(d="medium",
  c="Bismuth quadruple therapy for fourteen days",
  o={"PPI, amoxicillin, and clarithromycin": "Clarithromycin triple therapy for fourteen days",
     "PPI alone": "Proton pump inhibitor alone for eight weeks",
     "Amoxicillin monotherapy": "Amoxicillin as single-drug therapy",
     "Vancomycin and rifaximin": "Oral vancomycin combined with rifaximin"},
  why={"Clarithromycin triple therapy": "Triple therapy fails when local clarithromycin resistance exceeds 15%.",
       "Proton pump inhibitor alone": "Acid suppression may heal the ulcer but leaves the infection, so it recurs.",
       "Amoxicillin as single-drug therapy": "Single-agent therapy does not eradicate H. pylori and breeds resistance.",
       "Oral vancomycin combined with rifaximin": "Neither drug is active against H. pylori."}),

"H. pylori: MALT lymphoma": dict(d="medium",
  why={"Total gastrectomy": "Surgery is unnecessary when antibiotics alone can cause regression.",
       "R-CHOP chemotherapy": "Chemotherapy is reserved for high-grade or non-responsive disease.",
       "Radiation therapy": "Radiation is used when eradication fails or with t(11;18).",
       "Observation only": "Untreated infection keeps driving the lymphoma."}),

"Bacteroides fragilis: abscess": dict(d="medium",
  why={"Aztreonam": "Aztreonam covers aerobic Gram-negative rods only.",
       "Gentamicin": "Aminoglycoside uptake requires oxygen, so they fail against anaerobes.",
       "Ceftriaxone": "Ceftriaxone has poor anaerobic coverage and is degraded by B. fragilis beta-lactamase.",
       "Vancomycin": "Vancomycin covers Gram-positive organisms."}),

"Lactose fermentation": dict(d="easy",
  why={"Proteus mirabilis": "Proteus is a non-lactose fermenter and swarms on blood agar.",
       "Pseudomonas aeruginosa": "Pseudomonas does not ferment lactose and is oxidase-positive.",
       "Salmonella enterica": "Salmonella is a non-fermenter that produces H2S.",
       "Shigella sonnei": "Shigella is a non-fermenter without H2S."},
  table=LACTOSE),

"Reactive arthritis": dict(d="medium",
  why={"Staphylococcus aureus and Streptococcus pyogenes": "These cause septic arthritis with positive cultures, not a sterile reactive process.",
       "Borrelia burgdorferi and Treponema pallidum": "Lyme and syphilis cause different joint and systemic syndromes.",
       "Neisseria meningitidis and Haemophilus influenzae": "These cause invasive infection rather than post-infectious arthritis.",
       "Mycobacterium tuberculosis and Nocardia": "These cause chronic granulomatous infections."}),
}
