from tables import *
R = {
"HIV: entry & CCR5": dict(d="medium",
  c="gp120 binding the CCR5 co-receptor on target cells",
  o={"gp41-mediated fusion": "gp41-mediated fusion with the endosomal membrane",
     "Reverse transcription": "Reverse transcription of the viral RNA genome",
     "Integration of proviral DNA": "Integration of proviral DNA into host chromatin",
     "Cleavage of Gag-Pol": "Cleavage of the Gag-Pol polyprotein by protease"},
  why={"gp41-mediated fusion": "Fusion is blocked by enfuvirtide, not by a co-receptor deletion.",
       "Reverse transcription": "That step is targeted by NRTIs and NNRTIs.",
       "Integration of proviral DNA": "That step is blocked by integrase inhibitors.",
       "Cleavage of the Gag-Pol polyprotein": "That step is blocked by protease inhibitors."},
  table=HIV_DRUGS),

"HIV: genes & proteins": dict(d="medium",
  c="pol codes reverse transcriptase, integrase, and protease",
  o={"gag — gp120 and gp41": "gag codes the gp120 and gp41 envelope proteins",
     "env — p24 capsid": "env codes the p24 capsid and p17 matrix proteins",
     "tat — viral protease": "tat codes the viral protease enzyme",
     "nef — reverse transcriptase": "nef codes the reverse transcriptase enzyme"},
  why={"gag codes the gp120 and gp41": "gag makes the capsid and matrix; env makes gp120 and gp41.",
       "env codes the p24 capsid": "The assignments are reversed; env makes the envelope glycoproteins.",
       "tat codes the viral protease": "tat is a regulatory transactivator, not an enzyme gene.",
       "nef codes the reverse transcriptase": "nef downregulates MHC I and CD4."},
  table=HIV_DRUGS),

"HIV: diagnosis": dict(d="medium",
  c="A 4th-generation antigen/antibody assay, plus HIV RNA",
  o={"HIV Western blot alone": "An HIV Western blot performed alone",
     "CD4 count": "A CD4 T-lymphocyte count",
     "HIV antibody-only rapid test": "An antibody-only rapid HIV test",
     "HIV genotype resistance testing only": "HIV genotype resistance testing alone"},
  why={"An HIV Western blot performed alone": "Western blot is obsolete and misses acute infection.",
       "A CD4 T-lymphocyte count": "CD4 counts stage disease but do not diagnose infection.",
       "An antibody-only rapid HIV test": "Antibodies may not have developed yet in acute infection.",
       "HIV genotype resistance testing alone": "Resistance testing is done after diagnosis, not to make it."}),

"HIV: NRTIs": dict(d="medium",
  c="HLA-B*57:01, which predicts abacavir hypersensitivity",
  o={"G6PD level": "A G6PD level, because of dapsone-like hemolysis",
     "CCR5 tropism": "A CCR5 tropism assay, since abacavir targets CCR5",
     "HLA-B*15:02": "HLA-B*15:02, because of carbamazepine-related SJS",
     "Creatine kinase": "A creatine kinase level, because of rhabdomyolysis"},
  why={"A G6PD level": "G6PD testing matters before dapsone or primaquine, not abacavir.",
       "A CCR5 tropism assay": "Tropism testing is required before maraviroc; abacavir is an NRTI.",
       "HLA-B*15:02": "That allele predicts carbamazepine reactions in Southeast Asian patients.",
       "A creatine kinase level": "CK is monitored with daptomycin and statins."},
  table=HIV_DRUGS),

"HIV: NNRTIs": dict(d="medium",
  c="They bind RT allosterically and need no phosphorylation",
  o={"They are incorporated into viral DNA": "They are incorporated into viral DNA as chain terminators",
     "They inhibit integrase": "They inhibit the viral integrase enzyme",
     "They are active against HIV-2": "They are reliably active against HIV-2",
     "They block viral entry": "They block viral entry by binding gp41"},
  why={"They are incorporated into viral DNA as chain terminators": "That describes NRTIs.",
       "They inhibit the viral integrase enzyme": "That describes the -tegravir drugs.",
       "They are reliably active against HIV-2": "HIV-2 is intrinsically resistant to NNRTIs.",
       "They block viral entry by binding gp41": "That is enfuvirtide."},
  table=HIV_DRUGS),

"HIV: integrase & protease inhibitors": dict(d="hard",
  c="It inhibits CYP3A4, raising protease inhibitor levels",
  o={"It induces CYP3A4": "It induces CYP3A4 in order to reduce toxicity",
     "It inhibits integrase strand transfer": "It inhibits integrase strand transfer directly",
     "It blocks CCR5": "It blocks the CCR5 co-receptor on host cells",
     "It is a chain terminator": "It acts as a DNA chain terminator"},
  why={"It induces CYP3A4": "Induction would lower drug levels; ritonavir inhibits the enzyme.",
       "It inhibits integrase strand transfer": "That is the mechanism of dolutegravir and related drugs.",
       "It blocks the CCR5 co-receptor": "That is maraviroc.",
       "It acts as a DNA chain terminator": "That describes NRTIs."},
  table=HIV_DRUGS),

"HIV: opportunistic infections by CD4 count": dict(d="easy",
  why={"Pneumocystis pneumonia": "Pneumocystis typically occurs below 200.",
       "Oral candidiasis": "Thrush can appear at higher counts, often below 500.",
       "Herpes zoster": "Zoster can occur at relatively preserved counts.",
       "Pulmonary tuberculosis": "TB can occur at any CD4 count."},
  table=HIV_OI),

"HIV: perinatal transmission": dict(d="hard",
  c="IV zidovudine, cesarean delivery, and infant prophylaxis",
  o={"Vaginal delivery without further": "Vaginal delivery with no further intervention",
     "Stop ART at delivery": "Stopping ART at delivery to spare the neonate",
     "Give HIV immune globulin": "Giving HIV immune globulin to the infant",
     "Breastfeeding plus infant zidovudine": "Breastfeeding combined with infant zidovudine"},
  why={"Vaginal delivery with no further intervention": "With a viral load above 1,000, vaginal delivery raises transmission risk.",
       "Stopping ART at delivery": "Stopping ART raises viral load and transmission risk.",
       "Giving HIV immune globulin to the infant": "No such product is used for HIV prophylaxis.",
       "Breastfeeding combined with infant zidovudine": "Breastfeeding is avoided in the US because milk transmits HIV."}),

"HIV: PrEP & PEP": dict(d="medium",
  c="Start three-drug prophylaxis within 72 hours for 28 days",
  o={"Wait for the worker's HIV test": "Wait for the worker's HIV test to become positive",
     "Give HIV immune globulin": "Give HIV immune globulin as passive protection",
     "Start tenofovir-emtricitabine for 7 days": "Start tenofovir-emtricitabine for seven days",
     "No action is needed": "No action is needed for percutaneous exposures"},
  why={"Wait for the worker's HIV test to become positive": "Prophylaxis must start before infection is established.",
       "Give HIV immune globulin": "No HIV immune globulin exists for this purpose.",
       "Start tenofovir-emtricitabine for seven days": "Prophylaxis uses three drugs for a full 28 days.",
       "No action is needed for percutaneous exposures": "Needlestick exposure to viremic blood carries real risk."},
  table=HIV_DRUGS),

"HIV: IRIS": dict(d="hard",
  why={"ART failure due to resistance": "His viral load fell and CD4 rose, so ART is working.",
       "A new bacterial meningitis": "CSF cultures are sterile and the picture fits an inflammatory response.",
       "Drug-induced aseptic meningitis from dolutegravir": "That is not a recognized effect of integrase inhibitors.",
       "Progressive multifocal leukoencephalopathy": "PML causes focal deficits without fever, and is not an acute flare."},
  table=HIV_OI),

"HAV": dict(d="easy",
  why={"IgG anti-HAV": "IgG indicates past infection or vaccination, not acute illness.",
       "HBsAg": "HBsAg indicates hepatitis B infection.",
       "HCV RNA": "HCV RNA indicates hepatitis C, which rarely presents with acute icteric hepatitis.",
       "Anti-HBs": "Anti-HBs indicates immunity to hepatitis B."},
  table=HEPATITIS),

"HBV serology: window period": dict(d="hard",
  why={"Immunity from vaccination": "Vaccination produces anti-HBs without anti-HBc.",
       "Chronic hepatitis B": "Chronic infection keeps HBsAg positive beyond 6 months.",
       "Past, resolved infection with immunity": "Resolved infection shows anti-HBs plus IgG anti-HBc.",
       "False-positive result; no HBV infection": "IgM anti-HBc is specific for recent infection."},
  table=HBV_SEROLOGY),

"HBV serology: vaccination": dict(d="easy",
  why={"Acute infection": "Acute infection shows HBsAg and IgM anti-HBc.",
       "Chronic infection": "Chronic infection shows persistent HBsAg.",
       "Past natural infection": "Natural infection leaves anti-HBc, which is absent here.",
       "Window period": "The window period shows IgM anti-HBc as the only marker."},
  table=HBV_SEROLOGY),

"HBV: replication": dict(d="hard",
  why={"It replicates in the cytoplasm using RNA-dependent RNA polymerase": "HBV is a DNA virus that replicates through an RNA intermediate in the nucleus and capsid.",
       "It is a single-stranded linear DNA virus": "Its genome is partially double-stranded and circular.",
       "It integrates using integrase like HIV": "HBV lacks integrase; integration is incidental and not required.",
       "It requires HDV to replicate": "The dependence runs the other way: HDV needs HBsAg."},
  table=HEPATITIS),

"HBV: histology": dict(d="medium",
  why={"Councilman bodies from apoptosis in yellow fever": "Councilman bodies are apoptotic hepatocytes, not granular cytoplasm.",
       "Mallory-Denk bodies from alcohol injury": "Mallory bodies are eosinophilic intracytoplasmic inclusions of damaged keratin.",
       "Steatosis from hepatitis C genotype 3": "Steatosis shows fat vacuoles, not ground-glass cytoplasm.",
       "Owl's eye inclusions from CMV": "Those are intranuclear inclusions with a halo."},
  table=HEPATITIS),

"HBV: extrahepatic": dict(d="medium",
  why={"Granulomatosis with polyangiitis": "GPA is ANCA-positive and involves the lungs and sinuses.",
       "Cryoglobulinemic vasculitis": "That is associated with hepatitis C and causes palpable purpura and neuropathy.",
       "Takayasu arteritis": "Takayasu affects the aorta and its branches in young women.",
       "IgA vasculitis": "IgA vasculitis causes purpura, arthritis, and nephritis, mainly in children."},
  table=HEPATITIS),

"HCV: treatment": dict(d="medium",
  why={"Inhibitor of the NS3/4A serine protease": "That is the -previr class.",
       "Inhibitor of the NS5A replication complex protein": "That is velpatasvir, the partner drug here.",
       "Reverse transcriptase inhibitor": "HCV has no reverse transcriptase.",
       "Interferon receptor agonist": "Interferon is no longer standard therapy."},
  table=HCV_DAA),

"HCV: chronicity & no vaccine": dict(d="hard",
  why={"It integrates into host DNA": "HCV replicates in the cytoplasm and does not integrate.",
       "It becomes latent in neurons": "Latency in neurons is a herpesvirus property.",
       "It has a DNA genome that cannot be targeted by antibodies": "HCV is an RNA virus, and antibodies do form.",
       "It is a defective virus that needs HBV": "That describes hepatitis D."},
  table=HEPATITIS),

"HDV": dict(d="medium",
  why={"It is a DNA virus that replicates independently": "HDV is an RNA virus that depends on HBV for its envelope.",
       "It is spread mainly by the fecal-oral route": "It is bloodborne, like HBV.",
       "Superinfection is milder than simultaneous co-infection": "Superinfection is the more severe scenario.",
       "The HBV vaccine does not protect against it": "Preventing HBV prevents HDV."},
  table=HEPATITIS),

"HEV": dict(d="medium",
  why={"Hepatitis A virus": "HAV is also waterborne but is not notably severe in pregnancy.",
       "Hepatitis B virus": "HBV is bloodborne and sexually transmitted.",
       "Hepatitis C virus": "HCV is bloodborne and rarely causes acute fulminant hepatitis.",
       "Yellow fever virus": "Yellow fever requires a mosquito vector and causes hemorrhagic disease."},
  table=HEPATITIS),

"Hepatitis: transmission summary": dict(d="easy",
  why={"Hepatitis B and hepatitis D": "Both are bloodborne and can become chronic.",
       "Hepatitis C and hepatitis D": "Both are bloodborne and chronic.",
       "Hepatitis B and hepatitis C": "Both are bloodborne and chronic.",
       "Hepatitis A and hepatitis C": "HAV fits, but HCV is bloodborne and usually chronic."},
  table=HEPATITIS),
}
