from tables import *
R = {
"Candida: oral thrush": dict(d="easy",
  why={"Biopsy for squamous cell carcinoma": "Carcinoma presents as a fixed ulcer or mass that does not scrape off.",
       "Testing for EBV to confirm oral hairy leukoplakia": "Hairy leukoplakia cannot be scraped off and sits on the lateral tongue.",
       "Tuberculin skin test": "TB does not cause scrapable white oral plaques.",
       "Serum iron studies": "Iron deficiency causes glossitis and angular cheilitis, not pseudomembranes."},
  table=OPP_FUNGI),

"Candida: morphology & invasive disease": dict(d="medium",
  c="Micafungin, which blocks beta-glucan synthesis",
  o={"Amphotericin B, which inhibits squalene": "Amphotericin B, which inhibits squalene epoxidase",
     "Fluconazole, which binds ergosterol": "Fluconazole, which binds ergosterol to form pores",
     "Terbinafine, which inhibits 14α": "Terbinafine, which inhibits 14-alpha-demethylase",
     "Griseofulvin": "Griseofulvin, which disrupts microtubule spindles"},
  why={"Amphotericin B, which inhibits squalene epoxidase": "Amphotericin binds ergosterol; squalene epoxidase is the terbinafine target.",
       "Fluconazole, which binds ergosterol to form pores": "Fluconazole blocks ergosterol synthesis rather than binding it.",
       "Terbinafine, which inhibits 14-alpha-demethylase": "Terbinafine acts on squalene epoxidase and is used for dermatophytes.",
       "Griseofulvin, which disrupts microtubule spindles": "Griseofulvin is oral therapy for tinea capitis, not candidemia."},
  table=ANTIFUNGALS),

"Candida: immune defense": dict(d="medium",
  why={"Neutrophil oxidative burst": "Neutrophil defects lead to invasive candidiasis, which he does not have.",
       "Complement C5–C9": "Terminal complement deficiency predisposes to Neisseria.",
       "B cells and immunoglobulin production": "Antibody defects cause encapsulated bacterial infections.",
       "Splenic macrophages": "Asplenia predisposes to encapsulated bacteria."},
  table=IMMUNODEF),

"Aspergillus: invasive disease": dict(d="medium",
  why={"Fluconazole": "Fluconazole has no mold activity.",
       "Caspofungin alone as first-line": "Echinocandins are salvage or combination therapy, not first-line.",
       "Trimethoprim-sulfamethoxazole": "TMP-SMX treats Pneumocystis and Nocardia.",
       "Nystatin": "Nystatin is topical only."},
  table=OPP_FUNGI),

"Aspergillus: ABPA": dict(d="medium",
  c="Allergic bronchopulmonary aspergillosis; steroids",
  o={"Invasive aspergillosis; voriconazole": "Invasive aspergillosis; treat with voriconazole",
     "Aspergilloma; surgical resection": "Aspergilloma; treat with surgical resection",
     "Eosinophilic granulomatosis": "Eosinophilic granulomatosis; treat with cyclophosphamide",
     "Löffler syndrome from Ascaris": "Loffler syndrome from Ascaris; treat with albendazole"},
  why={"Invasive aspergillosis; treat with voriconazole": "Invasive disease occurs in neutropenia and causes vascular invasion.",
       "Aspergilloma; treat with surgical resection": "A fungus ball fills a preexisting cavity and causes hemoptysis.",
       "Eosinophilic granulomatosis; treat with cyclophosphamide": "EGPA has vasculitis, neuropathy, and positive ANCA in some patients.",
       "Loffler syndrome from Ascaris": "That causes transient infiltrates during larval migration, not chronic bronchiectasis."},
  table=OPP_FUNGI),

"Mucormycosis": dict(d="medium",
  c="Liposomal amphotericin B",
  o={"Voriconazole": "Intravenous voriconazole",
     "Fluconazole": "Intravenous fluconazole",
     "Micafungin": "Intravenous micafungin",
     "Terbinafine": "Oral terbinafine"},
  why={"Intravenous voriconazole": "Mucorales are intrinsically resistant, and voriconazole use may predispose to them.",
       "Intravenous fluconazole": "Fluconazole has no activity against molds.",
       "Intravenous micafungin": "Echinocandins have little activity against Mucorales.",
       "Oral terbinafine": "Terbinafine is used for dermatophytes."},
  table=OPP_FUNGI),

"Cryptococcus: meningitis": dict(d="medium",
  c="Amphotericin B with flucytosine, then fluconazole",
  o={"Fluconazole alone": "Fluconazole alone as induction therapy",
     "Caspofungin": "Caspofungin as induction therapy",
     "Trimethoprim-sulfamethoxazole plus steroids": "Trimethoprim-sulfamethoxazole plus corticosteroids",
     "Ceftriaxone plus vancomycin": "Ceftriaxone combined with vancomycin"},
  why={"Fluconazole alone as induction therapy": "Fluconazole alone is inferior for induction and is used later for consolidation.",
       "Caspofungin as induction therapy": "Echinocandins have essentially no activity against Cryptococcus.",
       "Trimethoprim-sulfamethoxazole plus corticosteroids": "That regimen treats Pneumocystis pneumonia.",
       "Ceftriaxone combined with vancomycin": "That covers bacterial meningitis, which has neutrophils in CSF."},
  table=OPP_FUNGI),

"Histoplasma": dict(d="medium",
  why={"Blastomyces dermatitidis": "Blastomyces yeasts are large with broad-based buds, not tiny intracellular forms.",
       "Coccidioides immitis": "Coccidioides forms large spherules filled with endospores.",
       "Leishmania donovani": "Leishmania amastigotes are intracellular too but have a kinetoplast and come from sandfly exposure.",
       "Cryptococcus neoformans": "Cryptococcus is encapsulated and extracellular, usually causing meningitis."},
  table=DIMORPHIC),

"Blastomyces": dict(d="medium",
  why={"Penicillin": "Penicillin has no antifungal activity.",
       "Fluconazole alone": "Fluconazole is less effective than itraconazole for blastomycosis.",
       "Caspofungin": "Echinocandins are not used for dimorphic fungi.",
       "Isoniazid": "Isoniazid treats tuberculosis, which this resembles but is not."},
  table=DIMORPHIC),

"Coccidioides": dict(d="medium",
  c="A desert soil mold whose arthroconidia form spherules",
  o={"It is a yeast found in bird droppings": "A yeast from bird droppings in the Ohio River valley",
     "It is spread person to person": "An organism spread person to person by droplets",
     "It is a normal-flora yeast": "A normal-flora yeast that forms pseudohyphae",
     "It is a thermally monomorphic": "A monomorphic fungus with broad-based budding"},
  why={"A yeast from bird droppings in the Ohio River valley": "That describes Histoplasma, which is found in a different region.",
       "An organism spread person to person by droplets": "Coccidioidomycosis is acquired from soil, not from people.",
       "A normal-flora yeast that forms pseudohyphae": "That describes Candida.",
       "A monomorphic fungus with broad-based budding": "Broad-based budding describes Blastomyces, which is dimorphic."},
  table=DIMORPHIC),

"Paracoccidioides": dict(d="hard",
  why={"Blastomyces dermatitidis": "Blastomyces has a single broad-based bud, not many peripheral buds.",
       "Histoplasma capsulatum": "Histoplasma yeasts are small and sit inside macrophages.",
       "Cryptococcus gattii": "Cryptococcus has a thick capsule and narrow-based budding.",
       "Sporothrix schenckii": "Sporothrix forms cigar-shaped yeasts after skin inoculation."},
  table=DIMORPHIC),

"Dimorphism": dict(d="easy",
  c="Molds in the environment, yeasts at body temperature",
  o={"They grow as yeasts in soil": "They grow as yeasts in soil and as molds in tissue",
     "They grow only at 42°C": "They grow only at 42 degrees Celsius",
     "They switch between septate": "They switch between septate and nonseptate hyphae by pH",
     "They are obligate intracellular": "They are obligate intracellular organisms in all phases"},
  why={"They grow as yeasts in soil and as molds in tissue": "The relationship is reversed: cold is mold, heat is yeast.",
       "They grow only at 42 degrees Celsius": "That temperature is a feature of Campylobacter culture.",
       "They switch between septate and nonseptate hyphae by pH": "Septation distinguishes Aspergillus from Mucorales and is not temperature-dependent.",
       "They are obligate intracellular organisms in all phases": "Only Histoplasma is notably intracellular, and it is culturable."},
  table=DIMORPHIC),

"Pneumocystis": dict(d="medium",
  c="TMP-SMX with corticosteroids",
  o={"TMP-SMX alone": "TMP-SMX given without corticosteroids",
     "Fluconazole": "Fluconazole given intravenously",
     "Amphotericin B": "Amphotericin B given intravenously",
     "Ganciclovir": "Ganciclovir given intravenously"},
  why={"TMP-SMX given without corticosteroids": "Steroids are indicated when PaO2 is below 70, as here, to reduce mortality.",
       "Fluconazole given intravenously": "Pneumocystis lacks ergosterol, so azoles do not work.",
       "Amphotericin B given intravenously": "Amphotericin binds ergosterol, which this organism lacks.",
       "Ganciclovir given intravenously": "Ganciclovir treats CMV pneumonitis."},
  table=OPP_FUNGI),

"Sporothrix": dict(d="medium",
  why={"Penicillin": "Penicillin has no antifungal activity.",
       "Amphotericin B for all cases": "Amphotericin is reserved for disseminated or severe disease.",
       "Caspofungin": "Echinocandins are inactive against Sporothrix.",
       "Isoniazid": "Isoniazid treats mycobacteria, including M. marinum mimics."},
  table=DIMORPHIC),

"Tinea versicolor": dict(d="easy",
  why={"It is caused by Trichophyton rubrum": "Dermatophytes cause annular scaly plaques, not hypopigmented macules.",
       "It is caused by Candida albicans": "Candida causes moist intertriginous rashes with satellite lesions.",
       "It is caused by Sporothrix": "Sporothrix causes nodules after inoculation.",
       "It is a bacterial infection with Corynebacterium minutissimum": "Erythrasma fluoresces coral-red and is not scaly in this pattern."}),

"Dermatophytes & treatment": dict(d="medium",
  why={"Oral fluconazole, which inhibits β-glucan synthase": "Fluconazole inhibits 14-alpha-demethylase, not glucan synthase.",
       "Nystatin, which binds ergosterol": "Nystatin is topical and does not treat nails.",
       "Griseofulvin, which inhibits 14α-demethylase": "Griseofulvin disrupts microtubules and is used mainly for tinea capitis.",
       "Oral ketoconazole, which disrupts microtubules": "Ketoconazole is an azole and carries hepatotoxicity and endocrine effects."},
  table=ANTIFUNGALS),

"Amphotericin B": dict(d="medium",
  why={"Inhibits 14α-demethylase; hydration has no effect": "That is the azole mechanism, and hydration does reduce amphotericin nephrotoxicity.",
       "Inhibits β-glucan synthase; co-administered probenecid": "That is the echinocandin mechanism; probenecid is used with cidofovir.",
       "Converted to 5-FU; leucovorin rescue": "That is flucytosine, and leucovorin is not used with it.",
       "Inhibits squalene epoxidase; potassium restriction": "That is terbinafine, and potassium must be replaced rather than restricted."},
  table=ANTIFUNGALS),

"Azole antifungals": dict(d="medium",
  why={"Bind ergosterol directly and induce hepatic CYP": "Amphotericin binds ergosterol, and azoles inhibit rather than induce CYP.",
       "Inhibit β-glucan synthesis and compete for renal excretion": "That is the echinocandin target, and the interaction is hepatic.",
       "Inhibit microtubules and displace drugs from albumin": "That describes griseofulvin.",
       "Inhibit squalene epoxidase and block P-glycoprotein": "That describes terbinafine."},
  table=ANTIFUNGALS),

"Flucytosine": dict(d="hard",
  why={"Viral thymidine kinase phosphorylates it; nephrotoxicity": "Viral kinases activate acyclovir, not an antifungal.",
       "It needs no activation; hepatotoxicity": "It requires fungal cytosine deaminase for activation.",
       "Host kinases convert it to a chain terminator; peripheral neuropathy": "Host cells lack the deaminase, which is the basis of selectivity.",
       "Hepatic CYP450 converts it to an active epoxide; visual disturbances": "Visual disturbances are a voriconazole effect."},
  table=ANTIFUNGALS),
}
