from tables import *
R = {
"Endotoxin": dict(d="medium",
  why={"It is a secreted protein toxin encoded on a plasmid": "That describes exotoxins; endotoxin is a structural lipid-sugar molecule.",
       "It is highly antigenic and can be converted to a toxoid": "Endotoxin is weakly antigenic and cannot be made into a toxoid.",
       "It is found in the cell wall of Gram-positive bacteria": "LPS is unique to Gram-negative outer membranes.",
       "It acts as a superantigen that binds MHC II": "Superantigens are protein exotoxins of staphylococci and streptococci."},
  table=ENDO_EXO),

"Gram-positive cell wall": dict(d="easy",
  why={"Lipopolysaccharide": "LPS is Gram-negative and signals through TLR4.",
       "Periplasmic space": "The periplasm lies between the two Gram-negative membranes.",
       "Outer membrane porins": "Porins are Gram-negative channels.",
       "O antigen": "The O antigen is the outer polysaccharide of Gram-negative LPS."}),

"Organisms that stain poorly with Gram stain": dict(d="easy",
  why={"Staphylococcus aureus": "S. aureus stains strongly Gram-positive.",
       "Escherichia coli": "E. coli stains well as a Gram-negative rod.",
       "Clostridium perfringens": "C. perfringens is a large Gram-positive rod on smear.",
       "Streptococcus pneumoniae": "Pneumococci stain as lancet-shaped Gram-positive diplococci."},
  table=STAINS),

"Special stains": dict(d="medium",
  why={"Periodic acid-Schiff — Mycobacterium leprae": "PAS highlights Tropheryma whipplei; M. leprae is acid-fast.",
       "Ziehl-Neelsen — Tropheryma whipplei": "Ziehl-Neelsen stains mycobacteria, not Whipple bacilli.",
       "Silver stain — Streptococcus pyogenes": "Silver stains are used for Legionella, Bartonella, and fungi.",
       "Congo red — Legionella pneumophila": "Congo red detects amyloid, not bacteria."},
  table=STAINS),

"Special culture media": dict(d="medium",
  why={"Legionella — Löwenstein-Jensen": "Löwenstein-Jensen is for mycobacteria; Legionella needs BCYE.",
       "Mycobacterium tuberculosis — buffered charcoal yeast extract": "BCYE is the Legionella medium.",
       "Corynebacterium diphtheriae — Eaton agar": "Eaton agar grows Mycoplasma; diphtheria uses tellurite or Löffler.",
       "Fungi — thiosulfate-citrate-bile salts-sucrose agar": "TCBS is for Vibrio; fungi grow on Sabouraud."},
  table=MEDIA),

"Transformation": dict(d="easy",
  why={"Transduction": "Transduction needs a bacteriophage and is not blocked by DNase.",
       "Conjugation": "Conjugation requires cell-to-cell contact through a pilus.",
       "Transposition": "Transposition moves DNA within a single cell.",
       "Lysogenic conversion": "Lysogenic conversion requires a prophage, not free DNA."},
  table=GENETICS),

"Conjugation": dict(d="easy",
  why={"Transformation": "Transformation takes up naked DNA and needs no contact.",
       "Generalized transduction": "Transduction is phage-mediated and requires no pilus.",
       "Specialized transduction": "That also involves a phage rather than direct contact.",
       "Recombination by homologous gene conversion": "Gene conversion rearranges existing DNA within one organism."},
  table=GENETICS),

"Transduction": dict(d="hard",
  c="Generalized moves any gene; specialized moves flanking genes",
  o={"Generalized transduction requires a sex pilus": "Generalized transduction requires a sex pilus",
     "Specialized transduction occurs only in the lytic": "Specialized transduction happens only in the lytic cycle",
     "Generalized transduction moves only toxin genes": "Generalized transduction moves only toxin genes",
     "There is no difference": "There is no meaningful difference between them"},
  why={"Generalized transduction requires a sex pilus": "Pili are used in conjugation, not transduction.",
       "Specialized transduction happens only in the lytic cycle": "It arises from imprecise excision of a prophage in the lysogenic cycle.",
       "Generalized transduction moves only toxin genes": "It can move any segment of host DNA by packaging error.",
       "There is no meaningful difference": "They differ in phage cycle and in which genes can move."},
  table=GENETICS),

"Transposons": dict(d="medium",
  why={"Integron promoter": "Integrons capture gene cassettes but do not themselves jump between molecules.",
       "Prophage": "A prophage is integrated viral DNA, not a self-mobilizing element of this kind.",
       "F factor": "The F factor drives conjugation between cells.",
       "Episome requiring homologous recombination": "Transposition needs no sequence homology."},
  table=GENETICS),

"Oxygen requirements": dict(d="medium",
  c="It lacks catalase or superoxide dismutase",
  o={"It lacks cytochrome oxidase": "It lacks cytochrome oxidase activity",
     "It requires CO2 for growth": "It requires added CO2 in order to grow",
     "It has no ribosomes": "It has no ribosomes of its own",
     "It lacks peptidoglycan": "It lacks peptidoglycan in its cell wall"},
  why={"It lacks cytochrome oxidase activity": "Oxidase status is an identification test, not the reason oxygen is lethal.",
       "It requires added CO2 in order to grow": "Capnophilic organisms still tolerate oxygen.",
       "It has no ribosomes of its own": "All bacteria have ribosomes.",
       "It lacks peptidoglycan in its cell wall": "Anaerobes do have peptidoglycan."}),

"Facultative intracellular bacteria": dict(d="medium",
  why={"Chlamydia trachomatis": "Chlamydia is an obligate intracellular energy parasite.",
       "Rickettsia rickettsii": "Rickettsia cannot be grown on artificial media.",
       "Coxiella burnetii": "Coxiella is an obligate intracellular organism.",
       "Ehrlichia chaffeensis": "Ehrlichia grows only inside host leukocytes."}),

"Encapsulated bacteria & testing": dict(d="medium",
  c="Quellung reaction; capsules block phagocytosis",
  o={"Elek test": "Elek test; capsules are toxin-producing structures",
     "CAMP test": "CAMP test; capsules make organisms beta-hemolytic",
     "Weil-Felix": "Weil-Felix; capsules cross-react with Proteus antigens",
     "Coagulase test": "Coagulase test; capsules are composed of fibrin"},
  why={"Elek test": "The Elek test detects diphtheria toxin production.",
       "CAMP test": "The CAMP test identifies group B strep and has nothing to do with capsules.",
       "Weil-Felix": "Weil-Felix is an old rickettsial serologic test.",
       "Coagulase test": "Coagulase identifies S. aureus; capsules are polysaccharide, not fibrin."},
  table=VACCINES),

"Type III secretion": dict(d="medium",
  c="Salmonella, Shigella, Yersinia, Pseudomonas, and E. coli",
  o={"Streptococcus pneumoniae and Staphylococcus": "Streptococcus pneumoniae and Staphylococcus aureus",
     "Mycoplasma and Ureaplasma": "Mycoplasma species and Ureaplasma species",
     "Clostridium tetani and Clostridium": "Clostridium tetani and Clostridium botulinum",
     "Treponema and Borrelia": "Treponema species and Borrelia species"},
  why={"Streptococcus pneumoniae and Staphylococcus aureus": "These are Gram-positive and lack the outer membrane the injectisome spans.",
       "Mycoplasma species and Ureaplasma species": "These lack a cell wall and this secretion apparatus.",
       "Clostridium tetani and Clostridium botulinum": "These act by secreted neurotoxins, not injected effectors.",
       "Treponema species and Borrelia species": "Spirochetes do not use type III secretion."}),

"Bacterial growth curve": dict(d="medium",
  why={"Lag phase; log phase": "Little wall synthesis happens in lag phase, and spores form later.",
       "Stationary phase; lag phase": "Beta-lactams work best when cells divide, which is log phase.",
       "Death phase; log phase": "Dying cells are not actively building wall.",
       "Log phase; lag phase": "The first half is right, but sporulation begins in stationary phase."}),

"Exotoxin mechanisms: cAMP": dict(d="medium",
  c="Cholera toxin acting on Gs and pertussis toxin on Gi",
  o={"Diphtheria toxin and Pseudomonas": "Diphtheria toxin and Pseudomonas exotoxin A",
     "Tetanospasmin and botulinum": "Tetanospasmin and botulinum neurotoxin",
     "Shiga toxin and Shiga-like": "Shiga toxin and Shiga-like toxin of EHEC",
     "Streptolysin O and α-toxin": "Streptolysin O and the alpha-toxin of C. perfringens"},
  why={"Diphtheria toxin and Pseudomonas exotoxin A": "Both inactivate EF-2 and stop protein synthesis.",
       "Tetanospasmin and botulinum neurotoxin": "Both are proteases that cleave SNARE proteins.",
       "Shiga toxin and Shiga-like toxin": "Both cleave 28S rRNA.",
       "Streptolysin O and the alpha-toxin": "Both damage membranes directly."},
  table=TOXINS),

"Superantigens": dict(d="easy",
  c="Staphylococcus aureus and Streptococcus pyogenes",
  o={"Clostridium tetani and Clostridium": "Clostridium tetani and Clostridium botulinum",
     "Vibrio cholerae and enterotoxigenic": "Vibrio cholerae and enterotoxigenic E. coli",
     "Bacillus anthracis and Bordetella": "Bacillus anthracis and Bordetella pertussis",
     "Corynebacterium diphtheriae and Pseudomonas": "Corynebacterium diphtheriae and Pseudomonas aeruginosa"},
  why={"Clostridium tetani and Clostridium botulinum": "These make neurotoxins that cleave SNAREs.",
       "Vibrio cholerae and enterotoxigenic E. coli": "These make secretory enterotoxins acting on cyclases.",
       "Bacillus anthracis and Bordetella pertussis": "These act through cyclase and protease toxins.",
       "Corynebacterium diphtheriae and Pseudomonas aeruginosa": "Both inactivate EF-2."},
  table=TOXINS),

"Pigment producers": dict(d="easy",
  why={"Actinomyces israelii — blue-green": "Actinomyces forms yellow sulfur granules.",
       "Pseudomonas aeruginosa — golden yellow": "Pseudomonas makes blue-green pyocyanin.",
       "Staphylococcus aureus — red": "S. aureus is golden yellow.",
       "Aspergillus fumigatus — yellow sulfur granules": "Sulfur granules belong to Actinomyces."}),

"Bacterial virulence: IgA protease": dict(d="easy",
  c="Streptococcus pneumoniae, H. influenzae, and Neisseria",
  o={"Staphylococcus aureus and Streptococcus pyogenes": "Staphylococcus aureus and Streptococcus pyogenes",
     "Escherichia coli and Klebsiella": "Escherichia coli and Klebsiella pneumoniae",
     "Clostridium perfringens and Clostridium": "Clostridium perfringens and Clostridium difficile",
     "Mycobacterium tuberculosis and Nocardia": "Mycobacterium tuberculosis and Nocardia species"},
  why={"Staphylococcus aureus and Streptococcus pyogenes": "These use protein A and M protein instead.",
       "Escherichia coli and Klebsiella pneumoniae": "These rely on fimbriae and capsules.",
       "Clostridium perfringens and Clostridium difficile": "These act through exotoxins.",
       "Mycobacterium tuberculosis and Nocardia species": "These survive inside phagocytes using cell wall lipids."}),

"Spores & heat resistance": dict(d="easy",
  c="Calcium complexed with dipicolinic acid",
  o={"Lipid A": "Lipid A in the outer membrane",
     "Mycolic acid": "Mycolic acid in the cell envelope",
     "Teichoic acid": "Teichoic acid in the cell wall",
     "Hyaluronic acid": "Hyaluronic acid in the capsule"},
  why={"Lipid A": "Lipid A is the toxic portion of Gram-negative endotoxin.",
       "Mycolic acid": "Mycolic acids make mycobacteria acid-fast.",
       "Teichoic acid": "Teichoic acid is a Gram-positive wall component that triggers cytokines.",
       "Hyaluronic acid": "That is the group A strep capsule."}),

"Catalase-positive organisms": dict(d="medium",
  c="Staphylococcus aureus, Serratia, Nocardia, and Aspergillus",
  o={"Streptococcus pyogenes and Streptococcus pneumoniae": "Streptococcus pyogenes and Streptococcus pneumoniae",
     "Neisseria meningitidis and Neisseria gonorrhoeae": "Neisseria meningitidis and Neisseria gonorrhoeae",
     "Pneumocystis and Cryptococcus": "Pneumocystis jirovecii and Cryptococcus neoformans",
     "Enteroviruses and herpesviruses": "Enteroviruses and herpesviruses"},
  why={"Streptococcus pyogenes and Streptococcus pneumoniae": "Streptococci are catalase-negative and are handled normally in CGD.",
       "Neisseria meningitidis and Neisseria gonorrhoeae": "Neisserial infections point to terminal complement deficiency.",
       "Pneumocystis jirovecii and Cryptococcus neoformans": "These suggest T-cell deficiency, as in HIV.",
       "Enteroviruses and herpesviruses": "Severe viral infections suggest T-cell or antibody defects."},
  table=IMMUNODEF),
}
