from tables import *
R = {
"Penicillins: mechanism": dict(d="easy",
  c="It mimics D-Ala-D-Ala and blocks transpeptidase enzymes",
  o={"It binds D-Ala-D-Ala directly": "It binds D-Ala-D-Ala directly, blocking glycosyltransferase",
     "It inhibits bacterial DNA gyrase": "It inhibits bacterial DNA gyrase and topoisomerase IV",
     "It binds the 30S": "It binds the 30S subunit and causes mRNA misreading",
     "It inhibits dihydropteroate": "It inhibits dihydropteroate synthase in folate synthesis"},
  why={"It binds D-Ala-D-Ala directly": "That is vancomycin, which binds the substrate rather than the enzyme.",
       "It inhibits bacterial DNA gyrase": "That is the fluoroquinolone mechanism.",
       "It binds the 30S subunit": "That describes aminoglycosides.",
       "It inhibits dihydropteroate synthase": "That is the sulfonamide mechanism."},
  table=CELL_WALL),

"Penicillinase-resistant penicillins": dict(d="easy",
  why={"Penicillin G": "Penicillin G is destroyed by staphylococcal penicillinase.",
       "Ampicillin": "Ampicillin is also penicillinase-sensitive.",
       "Aztreonam": "Aztreonam covers only Gram-negative rods.",
       "Ceftazidime": "Ceftazidime targets Pseudomonas and has weak staphylococcal activity."}),

"Aminopenicillins: EBV rash": dict(d="easy",
  c="Amoxicillin rash during EBV mononucleosis",
  o={"IgE-mediated anaphylaxis": "IgE-mediated anaphylaxis to the penicillin",
     "Scarlet fever": "Scarlet fever from resistant group A streptococci",
     "Stevens-Johnson syndrome": "Stevens-Johnson syndrome triggered by amoxicillin",
     "Toxic shock syndrome": "Staphylococcal toxic shock syndrome"},
  why={"IgE-mediated anaphylaxis": "Anaphylaxis causes urticaria, wheeze, and hypotension within minutes.",
       "Scarlet fever": "Scarlet fever produces a sandpaper rash with strawberry tongue, and would not start after antibiotics.",
       "Stevens-Johnson syndrome": "SJS involves mucosal erosions and skin detachment, not a benign morbilliform rash.",
       "Staphylococcal toxic shock syndrome": "TSS causes fever, hypotension, and multiorgan failure."}),

"Cephalosporins: generations": dict(d="medium",
  why={"Cefazolin": "Cefazolin is first-generation and covers MSSA only.",
       "Ceftriaxone": "Ceftriaxone does not cover MRSA or Pseudomonas.",
       "Cefepime": "Cefepime adds Pseudomonas coverage but not MRSA.",
       "Cefoxitin": "Cefoxitin is second-generation with anaerobic coverage."},
  table=CEPHS),

"Ceftriaxone: adverse effect": dict(d="medium",
  c="It displaces bilirubin from albumin, risking kernicterus",
  o={"Ceftriaxone causes gray baby": "It causes gray baby syndrome in neonates",
     "Ceftriaxone is not active": "It has no activity against Neisseria species",
     "Ceftriaxone causes cartilage": "It causes cartilage damage in growing infants",
     "Ceftriaxone is nephrotoxic": "It is directly nephrotoxic in neonates"},
  why={"It causes gray baby syndrome": "Gray baby syndrome is caused by chloramphenicol.",
       "It has no activity against Neisseria": "Ceftriaxone is the drug of choice for gonococcal infection.",
       "It causes cartilage damage": "Cartilage toxicity is a fluoroquinolone concern.",
       "It is directly nephrotoxic": "Ceftriaxone causes biliary sludging rather than nephrotoxicity."},
  table=ABX_TOX),

"Carbapenems": dict(d="medium",
  c="It blocks renal dehydropeptidase; imipenem can cause seizures",
  o={"It inhibits β-lactamases": "It inhibits beta-lactamases; imipenem causes ototoxicity",
     "It increases CNS penetration": "It increases CNS penetration; imipenem causes hyperkalemia",
     "It blocks tubular secretion": "It blocks tubular secretion; imipenem causes flushing",
     "It inhibits CYP3A4": "It inhibits CYP3A4; imipenem prolongs the QT interval"},
  why={"It inhibits beta-lactamases": "Cilastatin is not a beta-lactamase inhibitor, and ototoxicity is an aminoglycoside effect.",
       "It increases CNS penetration": "Cilastatin does not aid CNS entry, and hyperkalemia is a TMP-SMX effect.",
       "It blocks tubular secretion": "Probenecid blocks tubular secretion; flushing occurs with rapid vancomycin infusion.",
       "It inhibits CYP3A4": "Cilastatin does not affect CYP enzymes."}),

"Aztreonam": dict(d="medium",
  why={"Piperacillin": "Piperacillin is a penicillin and would cross-react.",
       "Cefepime": "Cephalosporins carry some cross-reactivity risk after anaphylaxis.",
       "Imipenem": "Carbapenems share the beta-lactam ring and carry a small cross-reactivity risk.",
       "Ampicillin": "Ampicillin is a penicillin and is contraindicated after anaphylaxis."}),

"β-lactamase inhibitors": dict(d="easy",
  c="It inactivates beta-lactamases from bite-wound flora",
  o={"Clavulanate blocks renal secretion": "It blocks renal secretion of amoxicillin, raising drug levels",
     "Clavulanate has its own strong activity": "It has strong intrinsic activity against MRSA",
     "Clavulanate inhibits bacterial protein": "It inhibits bacterial protein synthesis directly",
     "Clavulanate prevents amoxicillin-induced": "It prevents the diarrhea amoxicillin causes"},
  why={"It blocks renal secretion of amoxicillin": "Probenecid does that; clavulanate acts on bacterial enzymes.",
       "It has strong intrinsic activity against MRSA": "Clavulanate has little antibacterial activity of its own and does not cover MRSA.",
       "It inhibits bacterial protein synthesis": "It is a beta-lactamase inhibitor, not a ribosomal agent.",
       "It prevents the diarrhea amoxicillin causes": "Clavulanate actually increases diarrhea."}),

"Daptomycin": dict(d="hard",
  why={"It cannot penetrate lung tissue due to size": "It reaches the lung, but surfactant neutralizes it there.",
       "It causes bronchospasm": "Bronchospasm is not the reason it fails in pneumonia.",
       "It is a prodrug activated only in the heart": "Daptomycin needs no tissue-specific activation.",
       "It concentrates in bile": "Daptomycin is cleared renally, and bile levels are irrelevant here."},
  table=ABX_TOX),

"Aminoglycosides: mechanism & toxicity": dict(d="medium",
  c="Binds 30S, causing misreading; uptake needs oxygen",
  o={"It binds the 50S subunit": "Binds 50S and blocks translocation; anaerobes efflux it",
     "It inhibits DNA gyrase": "Inhibits DNA gyrase; anaerobes lack that enzyme",
     "It inhibits cell wall synthesis": "Inhibits cell wall synthesis; anaerobes lack peptidoglycan",
     "It binds 30S and blocks aminoacyl-tRNA": "Binds 30S and blocks tRNA; anaerobes lack ribosomes"},
  why={"Binds 50S and blocks translocation": "That is the macrolide mechanism, and efflux is not why anaerobes resist aminoglycosides.",
       "Inhibits DNA gyrase": "Fluoroquinolones target gyrase, and anaerobes do possess it.",
       "Inhibits cell wall synthesis": "Anaerobes do have peptidoglycan; this is not a cell wall agent.",
       "Binds 30S and blocks tRNA": "That is tetracycline's action, and all bacteria have ribosomes."},
  table=PROTEIN_SYNTH),

"Tetracyclines": dict(d="easy",
  c="Avoid milk, antacids, and iron; use sun protection",
  o={"Expect orange discoloration": "Expect orange discoloration of the urine and tears",
     "Avoid alcohol because of a disulfiram": "Avoid alcohol because of a disulfiram-like reaction",
     "Monitor for red-green": "Watch for loss of red-green color discrimination",
     "Take with high-dose calcium": "Take with high-dose calcium to protect the teeth"},
  why={"Expect orange discoloration": "That is rifampin.",
       "Avoid alcohol because of a disulfiram-like reaction": "That is metronidazole.",
       "Watch for loss of red-green color discrimination": "That is ethambutol.",
       "Take with high-dose calcium": "Calcium chelates tetracyclines and blocks absorption."},
  table=PROTEIN_SYNTH),

"Macrolides": dict(d="medium",
  c="QT prolongation; it binds 23S rRNA on the 50S subunit",
  o={"Ototoxicity": "Ototoxicity; it binds the 30S ribosomal subunit",
     "Tendon rupture": "Tendon rupture; it inhibits bacterial DNA gyrase",
     "Aplastic anemia": "Aplastic anemia; it inhibits peptidyl transferase",
     "Hyperkalemia": "Hyperkalemia; it blocks the epithelial sodium channel"},
  why={"Ototoxicity; it binds the 30S": "Ototoxicity and 30S binding describe aminoglycosides.",
       "Tendon rupture": "Tendon rupture and gyrase inhibition describe fluoroquinolones.",
       "Aplastic anemia": "Aplastic anemia and peptidyl transferase inhibition describe chloramphenicol.",
       "Hyperkalemia": "ENaC blockade and hyperkalemia describe trimethoprim."},
  table=PROTEIN_SYNTH),

"Clindamycin": dict(d="easy",
  why={"Gray baby syndrome": "That is chloramphenicol in neonates.",
       "Disulfiram-like reaction": "That is metronidazole with alcohol.",
       "Tendon rupture": "That is a fluoroquinolone effect.",
       "Photosensitivity": "That is typical of tetracyclines and sulfonamides."},
  table=ABX_TOX),

"Linezolid": dict(d="hard",
  why={"Linezolid inhibits CYP2D6": "Linezolid is not a significant CYP inhibitor.",
       "Linezolid blocks dopamine receptors": "Dopamine blockade causes neuroleptic malignant syndrome, which has rigidity rather than clonus.",
       "Linezolid inhibits GABA-A receptors": "That would cause seizures, as with imipenem.",
       "Linezolid causes hyponatremia": "SIADH is not a linezolid effect and would not cause clonus."},
  table=ABX_TOX),

"Chloramphenicol": dict(d="medium",
  c="Marrow suppression, aplastic anemia, gray baby syndrome",
  o={"Nephrotoxicity and ototoxicity": "Nephrotoxicity together with ototoxicity",
     "Tendon rupture and QT": "Tendon rupture together with QT prolongation",
     "Hyperkalemia and kernicterus": "Hyperkalemia together with kernicterus",
     "Pulmonary fibrosis": "Pulmonary fibrosis with peripheral neuropathy"},
  why={"Nephrotoxicity together with ototoxicity": "That pair describes aminoglycosides and vancomycin.",
       "Tendon rupture together with QT prolongation": "That pair describes fluoroquinolones.",
       "Hyperkalemia together with kernicterus": "That pair describes TMP-SMX.",
       "Pulmonary fibrosis with peripheral neuropathy": "Pulmonary fibrosis suggests nitrofurantoin."},
  table=ABX_TOX),

"Protein synthesis: subunit targets": dict(d="medium",
  c="30S: aminoglycosides, tetracyclines; 50S: the rest",
  o={"30S: macrolides, clindamycin": "30S: macrolides and clindamycin; 50S: aminoglycosides",
     "30S: linezolid, tetracyclines": "30S: linezolid and tetracyclines; 50S: macrolides",
     "30S: chloramphenicol, aminoglycosides": "30S: chloramphenicol and aminoglycosides; 50S: linezolid",
     "All bind the 50S": "All of these drugs bind the 50S subunit"},
  why={"30S: macrolides and clindamycin": "Macrolides and clindamycin act on the 50S subunit.",
       "30S: linezolid and tetracyclines": "Linezolid binds 23S rRNA in the 50S subunit.",
       "30S: chloramphenicol and aminoglycosides": "Chloramphenicol is a 50S agent.",
       "All of these drugs bind the 50S subunit": "Aminoglycosides and tetracyclines bind the 30S subunit."},
  table=PROTEIN_SYNTH),

"TMP-SMX: mechanism": dict(d="easy",
  why={"Sulfamethoxazole: dihydrofolate reductase": "The two enzymes are swapped in this option.",
       "Both inhibit dihydrofolate reductase": "Only trimethoprim inhibits DHFR; sulfamethoxazole acts earlier.",
       "Sulfamethoxazole: DNA gyrase": "Neither drug targets nucleic acid enzymes.",
       "Sulfamethoxazole: PABA synthesis": "Sulfonamides are PABA analogs that compete at dihydropteroate synthase."}),

"TMP-SMX: adverse effects": dict(d="hard",
  why={"Sulfamethoxazole causes type IV renal tubular acidosis by destroying the adrenal gland": "The drug does not damage the adrenal gland.",
       "Trimethoprim stimulates aldosterone": "Trimethoprim opposes the effect of aldosterone at the collecting duct.",
       "Rhabdomyolysis": "There is no muscle injury here, and CK would be elevated.",
       "Sulfamethoxazole causes hemolysis": "Hemolysis occurs in G6PD deficiency but does not usually cause this degree of hyperkalemia."},
  table=ABX_TOX),

"Fluoroquinolones": dict(d="medium",
  why={"Inhibits RNA polymerase": "That is rifampin, which causes hepatotoxicity and orange fluids.",
       "Blocks the 30S subunit": "That describes aminoglycosides and tetracyclines.",
       "Inhibits cell wall synthesis": "Cell wall agents do not cause tendinopathy.",
       "Forms free radicals that damage DNA": "That is metronidazole's mechanism."},
  table=ABX_TOX),

"Metronidazole": dict(d="medium",
  why={"Inhibits alcohol dehydrogenase": "It inhibits aldehyde dehydrogenase, causing acetaldehyde to accumulate.",
       "Induces CYP2E1": "CYP induction does not explain the flushing reaction.",
       "Causes serotonin release": "Serotonin syndrome is a linezolid interaction.",
       "Blocks histamine metabolism": "Histamine metabolism is not the mechanism here."},
  table=ABX_TOX),

"Nitrofurantoin": dict(d="medium",
  why={"It is inactivated in acidic urine": "It actually works well in acidic urine.",
       "It is excreted mainly in bile": "It is excreted renally, which is why it concentrates in urine.",
       "It only covers Gram-positive organisms": "It covers E. coli and enterococci, though not Proteus or Pseudomonas.",
       "It is a prodrug activated only in the liver": "It is activated by bacterial nitroreductases."},
  table=ABX_TOX),

"Polymyxins": dict(d="hard",
  why={"Binds D-Ala-D-Ala; ototoxicity": "That is vancomycin, which has no Gram-negative activity.",
       "Inhibits 50S; myelosuppression": "That describes linezolid or chloramphenicol.",
       "Inhibits DNA gyrase; tendinopathy": "That describes fluoroquinolones.",
       "Blocks folate synthesis; hyperkalemia": "That describes TMP-SMX."},
  table=CELL_WALL),

"Antibiotics in pregnancy": dict(d="easy",
  why={"Cephalexin": "Cephalosporins are considered safe in pregnancy.",
       "Amoxicillin-clavulanate": "Penicillins are safe in pregnancy.",
       "Nitrofurantoin in the second trimester": "Nitrofurantoin is acceptable in the second trimester, though avoided near term.",
       "Fosfomycin": "Fosfomycin is a safe single-dose option for cystitis."}),

"Bacteriostatic vs bactericidal": dict(d="medium",
  why={"Tetracyclines and macrolides": "Both are bacteriostatic.",
       "Clindamycin and sulfonamides": "Both are bacteriostatic.",
       "Chloramphenicol and tetracyclines": "Both are bacteriostatic.",
       "Macrolides and clindamycin": "Both are bacteriostatic."}),

"Resistance mechanisms": dict(d="medium",
  why={"Vancomycin — β-lactamase production": "Vancomycin is a glycopeptide and is unaffected by beta-lactamases.",
       "Fluoroquinolones — methylation of 23S rRNA": "23S methylation affects macrolides, not gyrase inhibitors.",
       "Macrolides — D-Ala-D-Lac substitution": "That change causes vancomycin resistance.",
       "Tetracyclines — altered PBPs": "Altered PBPs affect beta-lactams; tetracycline resistance is by efflux."},
  table=RESISTANCE),

"Rifampin monotherapy": dict(d="medium",
  why={"It is inactive in the body without a second drug": "Rifampin is highly active on its own; the problem is rapid resistance.",
       "It is only bacteriostatic": "Rifampin is bactericidal.",
       "It cannot reach intracellular organisms": "It penetrates cells and biofilm well.",
       "It is inactivated by β-lactamases": "Beta-lactamases do not act on rifampin."},
  table=RESISTANCE),

"Endocarditis prophylaxis": dict(d="medium",
  why={"A 30-year-old with mitral valve prolapse without regurgitation": "MVP without regurgitation is not a high-risk lesion.",
       "A 25-year-old with a surgically repaired atrial septal defect 10 years ago": "Fully repaired defects need prophylaxis only for the first 6 months.",
       "A 50-year-old with hypertrophic cardiomyopathy": "HCM alone is not an indication.",
       "A 40-year-old undergoing colonoscopy": "GI procedures do not require prophylaxis."}),

"Antibiotic prophylaxis: HIV": dict(d="medium",
  why={"Azithromycin to prevent MAC": "MAC prophylaxis is considered below 50 and is often unnecessary once ART starts.",
       "Fluconazole to prevent Cryptococcus": "Primary antifungal prophylaxis is not routine.",
       "Valganciclovir to prevent CMV": "Primary CMV prophylaxis is not recommended.",
       "Isoniazid to prevent TB regardless of TST": "Isoniazid is given only for latent infection confirmed by testing."},
  table=HIV_OI),

"Fosfomycin & bacitracin: cell wall steps": dict(d="hard",
  why={"Vancomycin → fosfomycin": "The order is scrambled; fosfomycin acts first, in the cytoplasm.",
       "β-lactams → vancomycin": "Beta-lactams act last, at cross-linking.",
       "Bacitracin → β-lactams": "Bacitracin acts after fosfomycin, at the carrier step.",
       "Fosfomycin → β-lactams": "Beta-lactams act after vancomycin, not before bacitracin."},
  table=CELL_WALL),
}
