from tables import *
R = {
"C. diphtheriae: toxin mechanism": dict(d="medium",
  c="ADP-ribosylation of elongation factor 2",
  o={"Cleavage of 28S rRNA": "Cleavage of an adenine from 28S ribosomal RNA",
     "ADP-ribosylation of Gi": "ADP-ribosylation of Gi, which raises cAMP",
     "Cleavage of SNARE": "Cleavage of SNARE fusion proteins at the synapse",
     "Formation of pores": "Pore formation in cholesterol-rich membranes"},
  why={"Cleavage of an adenine": "That is Shiga and Shiga-like toxin, which cause dysentery and HUS.",
       "ADP-ribosylation of Gi": "That is pertussis toxin, which causes whooping cough with lymphocytosis.",
       "Cleavage of SNARE": "SNARE cleavage describes tetanus and botulinum toxins, which cause paralysis.",
       "Pore formation": "Streptolysin O and listeriolysin O form pores; they do not stop translation."},
  table=TOXINS),

"C. diphtheriae: lysogenic conversion": dict(d="medium",
  c="Lysogenic conversion by a toxin-encoding prophage",
  o={"Transformation with naked": "Transformation with naked chromosomal DNA",
     "Conjugation of an F plasmid": "Conjugation transferring an F plasmid",
     "Generalized transduction": "Generalized transduction during the lytic cycle",
     "Transposition of a chromosomal": "Transposition of a chromosomal pathogenicity island"},
  why={"Transformation with naked chromosomal DNA": "Transformation moves free DNA and is typical of pneumococcus, H. influenzae, and Neisseria.",
       "Conjugation transferring an F plasmid": "Conjugation needs a sex pilus and mainly spreads resistance plasmids.",
       "Generalized transduction": "Generalized transduction moves random host genes, not a specific toxin gene in every toxigenic strain.",
       "Transposition": "Transposons jump within a cell and do not explain the requirement for a specific phage."},
  table=GENETICS),

"C. diphtheriae: laboratory ID": dict(d="medium",
  c="Club-shaped rods with metachromatic granules",
  o={"Boxcar-shaped rods": "Boxcar-shaped rods with central spores on blood agar",
     "Gram-negative diplococci": "Gram-negative diplococci on Thayer-Martin agar",
     "Lancet-shaped diplococci": "Lancet-shaped diplococci that dissolve in bile",
     "Acid-fast branching": "Acid-fast branching filaments on modified staining"},
  why={"Boxcar-shaped rods": "Boxcar rods with spores describe Bacillus species, not Corynebacterium.",
       "Gram-negative diplococci": "That describes Neisseria, which causes gonorrhea or meningitis.",
       "Lancet-shaped diplococci": "Bile-soluble diplococci are pneumococci, a cause of pneumonia and meningitis.",
       "Acid-fast branching filaments": "That describes Nocardia, a soil organism affecting immunocompromised patients."},
  table=MEDIA),

"C. diphtheriae: treatment & complications": dict(d="medium",
  c="Equine antitoxin; watch for myocarditis",
  o={"IV immunoglobulin": "IV immunoglobulin; watch for coronary aneurysms",
     "Tetanus immune globulin": "Tetanus immune globulin; watch for laryngospasm",
     "Corticosteroids": "Corticosteroids; watch for hemolytic uremic syndrome",
     "Diphtheria toxoid": "Diphtheria toxoid; watch for rheumatic valve disease"},
  why={"IV immunoglobulin": "IVIG and coronary aneurysms describe Kawasaki disease, which has no pseudomembrane.",
       "Tetanus immune globulin": "TIG neutralizes tetanospasmin and has no activity against diphtheria toxin.",
       "Corticosteroids": "Steroids do not neutralize toxin, and HUS follows Shiga toxin infections.",
       "Diphtheria toxoid": "Toxoid is for prevention; it acts too slowly to treat established disease."}),


"B. anthracis: cutaneous anthrax": dict(d="medium",
  why={"A polysaccharide capsule containing sialic acid": "Sialic acid capsules are found in group B strep and meningococcus B.",
       "Mycolic acid": "Mycolic acids belong to mycobacteria and cause acid-fastness.",
       "A lipooligosaccharide": "LOS is a Gram-negative outer membrane component.",
       "A hyaluronic acid capsule": "Group A strep has the hyaluronic acid capsule."}),

"B. anthracis: toxins": dict(d="hard",
  why={"It is a zinc metalloprotease": "Lethal factor cleaves MAPKK and kills macrophages, but it does not raise cAMP.",
       "It ADP-ribosylates Gs": "That is cholera and heat-labile toxin, which cause diarrhea.",
       "It glucosylates Rho": "Rho glucosylation is C. difficile toxin activity.",
       "It is a phospholipase C": "Lecithinase is the C. perfringens alpha-toxin of gas gangrene."},
  table=TOXINS),

"B. anthracis: inhalational anthrax": dict(d="medium",
  c="Ciprofloxacin with meropenem and linezolid",
  o={"Oral amoxicillin alone": "Oral amoxicillin as single-drug therapy",
     "Ceftriaxone alone": "Ceftriaxone as single-drug therapy",
     "Metronidazole": "Metronidazole as single-drug therapy",
     "Aztreonam": "Aztreonam as single-drug therapy"},
  why={"Oral amoxicillin": "Oral monotherapy is inadequate for systemic anthrax, which needs IV multidrug therapy.",
       "Ceftriaxone": "Cephalosporins are unreliable against B. anthracis and are not recommended.",
       "Metronidazole": "Metronidazole covers anaerobes; B. anthracis is aerobic.",
       "Aztreonam": "Aztreonam covers only Gram-negative rods."}),

"B. cereus: reheated rice": dict(d="easy",
  why={"Clostridium perfringens": "C. perfringens causes diarrhea 8-16 hours later, not rapid vomiting.",
       "Vibrio cholerae": "Cholera causes massive watery diarrhea after a longer incubation.",
       "Clostridium botulinum": "Botulinum toxin causes paralysis, not brief vomiting.",
       "Enterotoxigenic E. coli": "ETEC causes traveler's watery diarrhea after 1-3 days."},
  table=DIARRHEA),

"C. tetani: tetanospasmin": dict(d="medium",
  c="Glycine and GABA from inhibitory spinal interneurons",
  o={"Acetylcholine from α-motor": "Acetylcholine from motor neurons at the neuromuscular junction",
     "Dopamine from substantia": "Dopamine from neurons of the substantia nigra",
     "Glutamate from upper motor": "Glutamate released by upper motor neurons",
     "Norepinephrine from sympathetic": "Norepinephrine from postganglionic sympathetic fibers"},
  why={"Acetylcholine from motor neurons": "Blocking ACh release at the NMJ is botulinum toxin and causes flaccid paralysis.",
       "Dopamine": "Dopamine loss causes parkinsonism, not tetanic spasms.",
       "Glutamate": "Glutamate is excitatory; blocking it would reduce, not increase, muscle tone.",
       "Norepinephrine": "Autonomic instability occurs in tetanus but is not the primary toxin target."},
  table=CLOSTRIDIA),

"C. tetani: wound prophylaxis": dict(d="medium",
  c="Tdap plus tetanus immune globulin and wound cleaning",
  o={"Tdap alone": "Tetanus toxoid (Tdap) alone with wound cleaning",
     "Tetanus immune globulin alone": "Tetanus immune globulin alone with wound cleaning",
     "Oral penicillin alone": "Oral penicillin alone with wound cleaning",
     "No treatment unless": "Wound cleaning only, with observation for symptoms"},
  why={"Tetanus toxoid (Tdap) alone": "Toxoid takes weeks to work, which is too slow for a dirty wound in an unvaccinated patient.",
       "Tetanus immune globulin alone": "TIG gives only short-lived protection and leaves him unimmunized.",
       "Oral penicillin alone": "Antibiotics reduce organism burden but do not neutralize toxin or provide immunity.",
       "Wound cleaning only": "Waiting for symptoms is dangerous, since bound toxin cannot be reversed."}),

"C. botulinum: infant botulism": dict(d="medium",
  c="Spores germinate in the gut and toxin blocks ACh release",
  o={"Preformed toxin is absorbed": "Preformed toxin is absorbed and blocks spinal glycine release",
     "Antibodies against presynaptic": "Antibodies against presynaptic voltage-gated calcium channels",
     "Antibodies against postsynaptic": "Antibodies against postsynaptic acetylcholine receptors",
     "Demyelination of peripheral": "Demyelination of peripheral nerves after enteric infection"},
  why={"Preformed toxin is absorbed and blocks spinal glycine release": "Blocking glycine is tetanus and causes rigidity, not floppiness.",
       "Antibodies against presynaptic voltage-gated calcium channels": "That is Lambert-Eaton syndrome, seen in adults with small cell lung cancer.",
       "Antibodies against postsynaptic acetylcholine receptors": "That is myasthenia gravis, with fatigable weakness rather than sudden infant hypotonia.",
       "Demyelination of peripheral nerves": "Guillain-Barre causes ascending weakness and is rare at this age."},
  table=CLOSTRIDIA),

"C. botulinum vs other paralyses": dict(d="medium",
  c="Descending paralysis from cranial nerves, no sensory loss",
  o={"Ascending paralysis": "Ascending paralysis that starts in the legs",
     "Elevated CSF protein": "Elevated CSF protein with a normal cell count",
     "Preceding Campylobacter": "A preceding episode of Campylobacter diarrhea",
     "Loss of vibration": "Loss of vibration sense in both feet"},
  why={"Ascending paralysis": "Ascending weakness is the classic Guillain-Barre pattern.",
       "Elevated CSF protein": "Albuminocytologic dissociation is a Guillain-Barre finding.",
       "A preceding episode of Campylobacter": "Campylobacter is the classic trigger for Guillain-Barre.",
       "Loss of vibration sense": "Botulism causes no sensory loss; this points to a polyneuropathy."}),

"C. perfringens: gas gangrene": dict(d="easy",
  c="Alpha-toxin, a lecithinase (phospholipase C)",
  o={"Tetanospasmin": "Tetanospasmin, a protease acting on SNAREs",
     "Exfoliative toxin": "Exfoliative toxin, a protease acting on the skin",
     "Toxin B, a glucosyltransferase": "Toxin B, a glucosyltransferase acting on Rho",
     "Pyrogenic exotoxin A": "Pyrogenic exotoxin A, acting as a superantigen"},
  why={"Tetanospasmin": "Tetanospasmin causes spastic paralysis, not muscle necrosis with gas.",
       "Exfoliative toxin": "Exfoliative toxin splits the superficial epidermis in staphylococcal disease.",
       "Toxin B": "Toxin B damages colonocytes in C. difficile colitis.",
       "Pyrogenic exotoxin A": "SpeA causes scarlet fever and streptococcal toxic shock."},
  table=CLOSTRIDIA),

"C. perfringens: lab features": dict(d="medium",
  why={"Bacillus anthracis": "B. anthracis is aerobic and causes eschar or mediastinitis rather than myonecrosis.",
       "Clostridium tetani": "C. tetani shows terminal spores and causes spastic paralysis without tissue necrosis.",
       "Listeria monocytogenes": "Listeria is a small motile rod causing meningitis and food-borne illness.",
       "Actinomyces israelii": "Actinomyces forms branching filaments and sulfur granules."}),

"C. perfringens: food poisoning": dict(d="medium",
  c="Spores survive cooking and release toxin during gut sporulation",
  o={"Preformed heat-stable enterotoxin": "Preformed heat-stable enterotoxin acting on the vagus nerve",
     "Invasion of M cells": "Invasion of M cells overlying Peyer patches",
     "Toxin-mediated ADP-ribosylation": "Toxin-mediated ADP-ribosylation of Gi in enterocytes",
     "Adherence and effacement": "Adherence with effacement of intestinal microvilli"},
  why={"Preformed heat-stable enterotoxin": "That is S. aureus or B. cereus emetic toxin, which causes vomiting within hours.",
       "Invasion of M cells": "M-cell invasion describes Salmonella and Shigella, which cause fever and dysentery.",
       "Toxin-mediated ADP-ribosylation": "Gi ribosylation is pertussis toxin, which does not cause diarrhea.",
       "Adherence with effacement": "Attaching and effacing lesions describe EPEC and EHEC."},
  table=DIARRHEA),

"C. difficile: pathogenesis": dict(d="medium",
  c="Glucosylation of Rho GTPases, wrecking the cytoskeleton",
  o={"ADP-ribosylation of Gs": "ADP-ribosylation of Gs, which raises cAMP",
     "Cleavage of the 28S rRNA": "Cleavage of the 28S rRNA of the 60S subunit",
     "Formation of pores that lyse": "Formation of pores that lyse neutrophils",
     "Increase in cGMP": "Increase in cGMP through guanylyl cyclase activation"},
  why={"ADP-ribosylation of Gs": "That mechanism (cholera, ETEC LT) causes watery diarrhea without pseudomembranes.",
       "Cleavage of the 28S rRNA": "Shiga toxin acts this way and causes dysentery and HUS.",
       "Formation of pores that lyse neutrophils": "Panton-Valentine leukocidin does this in staphylococcal disease.",
       "Increase in cGMP": "ETEC heat-stable toxin raises cGMP and causes traveler's diarrhea."},
  table=CLOSTRIDIA),

"C. difficile: risk & diagnosis": dict(d="medium",
  c="Test only diarrheal stool, for toxin or toxin genes",
  o={"Stool culture for spores": "Stool culture for spores is the preferred diagnostic test",
     "Proton pump inhibitors lower": "Proton pump inhibitors lower the risk of infection",
     "Alcohol-based hand sanitizer": "Alcohol-based hand sanitizer reliably kills the spores",
     "Only clindamycin": "Only clindamycin is associated with this infection"},
  why={"Stool culture for spores": "Culture is slow and cannot distinguish colonization from disease.",
       "Proton pump inhibitors lower the risk": "PPIs raise the risk, probably by reducing gastric acid.",
       "Alcohol-based hand sanitizer": "Spores resist alcohol, so soap and water are required.",
       "Only clindamycin": "Fluoroquinolones, cephalosporins, and carbapenems are also common culprits."}),

"C. difficile: treatment": dict(d="medium",
  why={"IV vancomycin": "IV vancomycin does not reach the colonic lumen, so it fails here.",
       "Oral metronidazole plus IV clindamycin": "Clindamycin is a common cause of this disease, not a treatment.",
       "Loperamide": "Slowing the gut can precipitate toxic megacolon.",
       "IV ceftriaxone": "Cephalosporins predispose to C. difficile rather than treat it."},
  table=CLOSTRIDIA),

"Actinomyces: sulfur granules": dict(d="medium",
  why={"Trimethoprim-sulfamethoxazole": "TMP-SMX treats Nocardia, which is aerobic and weakly acid-fast.",
       "Amphotericin B": "Amphotericin treats invasive fungal infection, not a bacterial filament.",
       "Isoniazid, rifampin": "RIPE therapy is for tuberculosis, which forms caseating granulomas.",
       "Fluconazole": "Fluconazole is an antifungal with no antibacterial activity."},
  table=GPR),

"Nocardia: lung & brain": dict(d="medium",
  c="Trimethoprim-sulfamethoxazole",
  o={"Penicillin G": "High-dose intravenous penicillin G",
     "Isoniazid monotherapy": "Isoniazid given as single-drug therapy",
     "Metronidazole": "Metronidazole given intravenously",
     "Doxycycline": "Doxycycline given orally"},
  why={"High-dose intravenous penicillin G": "Penicillin is the drug for Actinomyces, which is anaerobic and non-acid-fast.",
       "Isoniazid": "Isoniazid treats mycobacteria; Nocardia is only weakly acid-fast and responds differently.",
       "Metronidazole": "Metronidazole covers anaerobes; Nocardia is a strict aerobe.",
       "Doxycycline": "Doxycycline is not reliable for CNS nocardiosis."},
  table=GPR),

"Spore formers: sterilization": dict(d="easy",
  c="Steam autoclaving at 121 degrees C under pressure",
  o={"70% isopropyl": "Wiping with 70% isopropyl alcohol",
     "Boiling at 100": "Boiling at 100 degrees C for five minutes",
     "Chlorhexidine": "Scrubbing with a chlorhexidine solution",
     "Quaternary ammonium": "Treating with quaternary ammonium compounds"},
  why={"Wiping with 70% isopropyl alcohol": "Alcohol does not kill spores, which is why C. difficile requires soap and water.",
       "Boiling at 100 degrees C for five minutes": "Spores survive boiling; higher temperature under pressure is needed.",
       "Scrubbing with a chlorhexidine solution": "Chlorhexidine is not sporicidal.",
       "Treating with quaternary ammonium compounds": "Quaternary ammonium compounds lack sporicidal activity."}),

"Listeria: pregnancy & neonates": dict(d="medium",
  why={"Ceftriaxone": "Listeria is intrinsically resistant to all cephalosporins.",
       "Vancomycin": "Vancomycin is not the standard therapy and has poor CSF penetration.",
       "Azithromycin": "Macrolides are not reliable for invasive listeriosis.",
       "Metronidazole": "Metronidazole covers anaerobes; Listeria is a facultative aerobe."},
  table=GPR),

"Listeria: actin rockets": dict(d="hard",
  why={"Streptolysin O; internalin": "Streptolysin O is a group A strep hemolysin and does not mediate escape from phagosomes.",
       "Lecithinase; flagellin": "Lecithinase is the C. perfringens alpha-toxin; flagellin drives motility, not actin rockets.",
       "Protein A; coagulase": "Both are S. aureus factors and neither supports intracellular spread.",
       "IpaB; VirG": "These are Shigella proteins, which use a similar strategy but are Gram-negative."}),
}
