from tables import *
R = {
"Y. pestis: bubonic plague": dict(d="medium",
  why={"Tick bite; doxycycline": "Ticks transmit RMSF, Lyme, and tularemia, not plague.",
       "Mosquito bite; chloroquine": "Mosquitoes transmit malaria and arboviruses.",
       "Inhalation of spores; ciprofloxacin": "Spore inhalation describes anthrax; Y. pestis forms no spores.",
       "Ingestion of undercooked meat; supportive care": "Plague is not food-borne and is fatal without antibiotics."},
  table=ZOONOSES),

"Y. pestis: morphology": dict(d="easy",
  why={"Gram-positive rods in chains with central spores": "That describes Bacillus species.",
       "Spirochetes between red cells": "Spirochetes on smear suggest relapsing fever Borrelia.",
       "Intracellular morulae in monocytes": "Morulae indicate Ehrlichia.",
       "Acid-fast beaded rods": "Acid-fast rods indicate mycobacteria or Nocardia."}),

"Francisella: ulceroglandular tularemia": dict(d="medium",
  c="Streptomycin or gentamicin",
  o={"Penicillin G": "Intravenous penicillin G",
     "Ceftriaxone": "Intravenous ceftriaxone",
     "Metronidazole": "Intravenous metronidazole",
     "Vancomycin": "Intravenous vancomycin"},
  why={"Intravenous penicillin G": "Beta-lactams are unreliable against this facultative intracellular organism.",
       "Intravenous ceftriaxone": "Cephalosporins perform poorly in tularemia despite in vitro activity.",
       "Intravenous metronidazole": "Metronidazole covers anaerobes; Francisella is aerobic.",
       "Intravenous vancomycin": "Vancomycin has no Gram-negative activity."},
  table=ZOONOSES),

"Brucella: undulant fever": dict(d="medium",
  why={"Coxiella burnetii; doxycycline alone": "Q fever comes from livestock aerosols and causes pneumonia or hepatitis, not sacroiliitis.",
       "Listeria monocytogenes; ampicillin": "Listeria causes meningitis and febrile gastroenteritis, not months of undulant fever.",
       "Mycobacterium bovis; RIPE therapy": "M. bovis causes scrofula or pulmonary disease, with caseating granulomas.",
       "Salmonella Typhi; ceftriaxone": "Typhoid causes rose spots and relative bradycardia over weeks, not months of relapsing fever."},
  table=ZOONOSES),

"Pasteurella multocida: cat bite": dict(d="easy",
  why={"Bartonella henselae; azithromycin": "Cat scratch disease causes regional lymphadenopathy after weeks, not cellulitis in hours.",
       "Staphylococcus aureus; cephalexin alone": "Staph cellulitis develops more slowly, and cephalexin misses Pasteurella.",
       "Capnocytophaga canimorsus; vancomycin": "Capnocytophaga causes sepsis in asplenic patients after dog bites.",
       "Eikenella corrodens; metronidazole": "Eikenella follows human bites and is resistant to metronidazole."},
  table=ZOONOSES),

"Bartonella: cat scratch disease": dict(d="medium",
  c="Stellate necrotizing granulomas with microabscesses",
  o={"Caseating granulomas": "Caseating granulomas containing acid-fast bacilli",
     "Reed-Sternberg cells": "Reed-Sternberg cells in a mixed infiltrate",
     "Sheets of atypical lymphocytes": "Sheets of monomorphic atypical lymphocytes",
     "Non-caseating granulomas": "Non-caseating granulomas with Schaumann bodies"},
  why={"Caseating granulomas containing acid-fast bacilli": "That indicates tuberculous lymphadenitis (scrofula).",
       "Reed-Sternberg cells": "Those indicate Hodgkin lymphoma, which causes painless nodes and B symptoms.",
       "Sheets of monomorphic atypical lymphocytes": "That suggests non-Hodgkin lymphoma.",
       "Non-caseating granulomas with Schaumann bodies": "Those suggest sarcoidosis, which is not linked to kitten scratches."}),

"Bartonella: bacillary angiomatosis": dict(d="medium",
  why={"Liposomal doxorubicin": "That treats Kaposi sarcoma, which shows spindle cells and no bacilli.",
       "Valganciclovir": "Valganciclovir treats CMV disease.",
       "Trimethoprim-sulfamethoxazole": "TMP-SMX is not the treatment for Bartonella.",
       "Surgical excision only": "Lesions are multiple and respond to antibiotics."}),

"Zoonoses: matching exposures": dict(d="medium",
  why={"Cattle placentas in a slaughterhouse — Leptospira": "Birth product aerosols transmit Coxiella burnetii (Q fever).",
       "Rabbits and deer flies — Brucella": "Rabbits and deer flies transmit Francisella tularensis.",
       "Armadillos — Coxiella burnetii": "Armadillos are a reservoir for Mycobacterium leprae.",
       "Prairie dog fleas — Francisella": "Rodent fleas transmit Yersinia pestis."},
  table=ZOONOSES),

"Syphilis: primary chancre": dict(d="medium",
  why={"Gram stain of the exudate": "Treponemes are too thin to be seen on Gram stain.",
       "Tzanck smear": "A Tzanck smear detects herpesvirus giant cells in a painful vesicular lesion.",
       "Nontreponemal serology alone": "RPR and VDRL can still be negative this early in primary syphilis.",
       "Culture on Thayer-Martin agar": "That medium isolates Neisseria; T. pallidum cannot be cultured."},
  table=SYPH_TESTS),

"Syphilis: secondary": dict(d="easy",
  why={"Oral doxycycline for 7 days": "Doxycycline is an alternative only in penicillin allergy, and 7 days is too short.",
       "IV aqueous penicillin G for 14 days": "IV therapy is reserved for neurosyphilis and ocular or otic disease.",
       "IM ceftriaxone single dose": "Ceftriaxone is not the standard regimen for secondary syphilis.",
       "Oral acyclovir": "Acyclovir treats herpes, which causes painful vesicles instead."},
  table=SYPHILIS_STAGES),

"Syphilis: Jarisch-Herxheimer": dict(d="medium",
  c="Cytokine release after rapid killing of spirochetes",
  o={"IgE-mediated penicillin allergy": "An IgE-mediated allergic reaction to penicillin",
     "Serum sickness": "Serum sickness caused by immune complexes",
     "Superinfection with Staphylococcus": "Superinfection with Staphylococcus aureus",
     "Progression to neurosyphilis": "Early progression to neurosyphilis"},
  why={"An IgE-mediated allergic reaction": "Anaphylaxis causes urticaria, wheeze, and hypotension within minutes, not fever and myalgias.",
       "Serum sickness": "Serum sickness appears after 1-2 weeks with arthralgias and nephritis.",
       "Superinfection with Staphylococcus aureus": "A new bacterial infection would not begin within hours of the first dose.",
       "Early progression to neurosyphilis": "Neurosyphilis develops over years and does not flare within hours."}),

"Syphilis: serology": dict(d="hard",
  c="A biologic false-positive from anti-cardiolipin antibodies",
  o={"Early primary syphilis": "Untreated early primary syphilis",
     "Successfully treated past syphilis": "Syphilis that was successfully treated in the past",
     "Latent syphilis": "Untreated latent syphilis",
     "Neurosyphilis": "Undiagnosed neurosyphilis"},
  why={"Untreated early primary syphilis": "A treponemal test would be positive, and it is negative here.",
       "Syphilis that was successfully treated": "Treponemal tests stay positive for life after real infection.",
       "Untreated latent syphilis": "Latent syphilis requires a positive treponemal test.",
       "Undiagnosed neurosyphilis": "Neurosyphilis would also be treponemal-positive and usually symptomatic."},
  table=SYPH_TESTS),

"Syphilis: tertiary": dict(d="hard",
  c="Endarteritis obliterans of the vasa vasorum",
  o={"Cystic medial degeneration": "Cystic medial degeneration from a fibrillin mutation",
     "Granulomatous inflammation": "Granulomatous inflammation of the arch in a young woman",
     "Atherosclerosis": "Atherosclerosis involving the abdominal aorta",
     "Immune complex deposition": "Immune complex deposition within the adventitia"},
  why={"Cystic medial degeneration": "That is Marfan syndrome, which affects young patients without neurologic signs.",
       "Granulomatous inflammation of the arch": "That is Takayasu arteritis, with pulse deficits in young Asian women.",
       "Atherosclerosis involving the abdominal aorta": "Atherosclerotic aneurysms are infrarenal, not ascending.",
       "Immune complex deposition within the adventitia": "Immune complex vasculitis does not cause ascending aortic aneurysm."},
  table=SYPHILIS_STAGES),

"Syphilis: congenital": dict(d="medium",
  why={"Erythromycin ointment at birth": "Eye ointment prevents gonococcal conjunctivitis only.",
       "Measles-mumps-rubella vaccination of the mother during pregnancy": "MMR is a live vaccine and is contraindicated in pregnancy.",
       "Avoiding cat litter during pregnancy": "That prevents toxoplasmosis, which causes chorioretinitis and hydrocephalus.",
       "Delivering by cesarean section": "Syphilis crosses the placenta, so cesarean delivery does not prevent it."},
  table=TORCH),

"Lyme disease: erythema migrans": dict(d="easy",
  why={"Dermacentor tick; oral doxycycline": "Dermacentor transmits RMSF and tularemia, not Lyme disease.",
       "Ixodes tick; IV ceftriaxone for all patients": "IV therapy is reserved for carditis, meningitis, or refractory arthritis.",
       "Body louse; oral penicillin": "Body lice transmit epidemic typhus, trench fever, and relapsing fever.",
       "Lone star tick (Amblyomma); no treatment needed": "Amblyomma transmits ehrlichiosis, and Lyme disease requires treatment."},
  table=TICKBORNE),

"Lyme disease: tick & co-infection": dict(d="medium",
  why={"Rocky Mountain spotted fever and tularemia": "Both are transmitted by Dermacentor ticks.",
       "Ehrlichiosis and plague": "Ehrlichiosis comes from Amblyomma and plague from fleas.",
       "Epidemic typhus and trench fever": "Both are louse-borne.",
       "Chagas disease and leishmaniasis": "These come from reduviid bugs and sandflies in other regions."},
  table=TICKBORNE),

"Lyme disease: disseminated": dict(d="medium",
  c="Early disseminated Lyme disease; IV ceftriaxone",
  o={"Sarcoidosis; prednisone": "Neurosarcoidosis; treat with prednisone",
     "Guillain-Barré syndrome; IVIG": "Guillain-Barre syndrome; treat with IVIG",
     "Viral myocarditis; supportive care": "Viral myocarditis; provide supportive care",
     "Acute rheumatic fever; penicillin": "Acute rheumatic fever; treat with penicillin"},
  why={"Neurosarcoidosis": "Sarcoidosis can cause facial palsy but is rare in children and lacks the exposure history.",
       "Guillain-Barre syndrome": "GBS causes ascending weakness and areflexia, not isolated facial palsy with heart block.",
       "Viral myocarditis": "Viral myocarditis does not explain bilateral facial palsy.",
       "Acute rheumatic fever": "ARF follows strep pharyngitis and causes carditis with a murmur and arthritis."},
  table=LYME_STAGES),

"Relapsing fever": dict(d="hard",
  c="Antigenic variation of variable major outer proteins",
  o={"Periodic release of merozoites": "Periodic release of merozoites from lysed red cells",
     "Reactivation of latent virus": "Reactivation of latent virus in dorsal root ganglia",
     "Periodic release of endotoxin": "Periodic endotoxin release from a hepatic abscess",
     "Cyclic neutropenia": "Cyclic neutropenia with recurring bacterial infection"},
  why={"Periodic release of merozoites": "That is malaria, which shows intraerythrocytic parasites rather than spirochetes.",
       "Reactivation of latent virus": "Ganglionic reactivation causes zoster, not recurrent fevers.",
       "Periodic endotoxin release from a hepatic abscess": "An abscess causes continuous, not cyclic, fever with focal findings.",
       "Cyclic neutropenia": "Cyclic neutropenia causes recurrent mouth ulcers and infections from infancy."},
  table=TICKBORNE),

"Leptospira: Weil disease": dict(d="medium",
  c="Water or soil contaminated with rodent urine",
  o={"Bite of an infected mosquito": "The bite of an infected mosquito",
     "Undercooked pork": "Eating undercooked pork products",
     "Inhalation of bird droppings": "Inhaling dust from dried bird droppings",
     "Unpasteurized milk": "Drinking unpasteurized milk"},
  why={"The bite of an infected mosquito": "Mosquitoes transmit malaria and arboviruses, not leptospires.",
       "Eating undercooked pork": "Pork transmits Yersinia, Trichinella, and Taenia solium.",
       "Inhaling dust from dried bird droppings": "That transmits Histoplasma, Cryptococcus, and Chlamydia psittaci.",
       "Drinking unpasteurized milk": "Unpasteurized dairy transmits Brucella, Listeria, and Campylobacter."},
  table=ZOONOSES),

"Spirochetes: visualization": dict(d="medium",
  c="Only Borrelia is thick enough for Giemsa or Wright stain",
  o={"All spirochetes Gram-stain": "All spirochetes stain strongly Gram-positive",
     "Treponema pallidum is easily grown": "Treponema pallidum grows readily on blood agar",
     "Leptospira is best seen in a Wright": "Leptospira is best seen on a Wright-stained smear",
     "Spirochetes lack an outer membrane": "Spirochetes have no outer membrane at all"},
  why={"All spirochetes stain strongly Gram-positive": "Spirochetes have a Gram-negative-type envelope and stain poorly either way.",
       "Treponema pallidum grows readily on blood agar": "T. pallidum cannot be cultured on artificial media.",
       "Leptospira is best seen on a Wright-stained smear": "Leptospira is too thin; dark-field or silver stains are used.",
       "Spirochetes have no outer membrane at all": "They do have an outer membrane, with endoflagella in the periplasm."}),
}
