from tables import *
R = {
"S. epidermidis: contaminant vs true infection": dict(d="medium",
  c="Likely a skin contaminant; no therapy is needed",
  o={"True bacteremia requiring 6 weeks": "True bacteremia needing six weeks of vancomycin",
     "Endocarditis requiring echocardiography": "Endocarditis needing echocardiography and surgery",
     "Evidence of MRSA requiring decolonization": "Evidence of MRSA requiring nasal decolonization",
     "Evidence of toxic shock syndrome": "Evidence of staphylococcal toxic shock syndrome"},
  why={"True bacteremia needing six weeks of vancomycin": "True bacteremia usually shows growth in several bottles and a clinical decline.",
       "Endocarditis needing echocardiography and surgery": "He has no murmur, prosthesis, or persistent bacteremia.",
       "Evidence of MRSA requiring nasal decolonization": "This is a coagulase-negative organism, not S. aureus.",
       "Evidence of staphylococcal toxic shock syndrome": "TSS involves fever, rash, hypotension, and multiorgan failure."},
  table=STAPH),

"S. saprophyticus: virulence & treatment": dict(d="easy",
  c="It adheres to uroepithelium and responds to standard cystitis drugs",
  o={"It is a skin contaminant": "It is a skin contaminant that should not be treated",
     "It is intrinsically resistant": "It is intrinsically resistant to all oral antibiotics",
     "It causes cystitis mainly in catheterized": "It causes cystitis mainly in catheterized elderly men",
     "It is identified by optochin": "It is identified by its sensitivity to optochin"},
  why={"It is a skin contaminant that should not be treated": "At this colony count with symptoms it is the pathogen.",
       "It is intrinsically resistant to all oral antibiotics": "It responds well to nitrofurantoin and TMP-SMX.",
       "It causes cystitis mainly in catheterized elderly men": "It is typical of young, sexually active women.",
       "It is identified by its sensitivity to optochin": "Optochin testing applies to alpha-hemolytic streptococci."},
  table=STAPH),

"Viridans streptococci: caries & treatment": dict(d="medium",
  c="Streptococcus mutans; penicillin G or ceftriaxone",
  o={"Streptococcus sanguinis": "Streptococcus sanguinis; vancomycin plus rifampin",
     "Streptococcus mitis": "Streptococcus mitis; clindamycin as monotherapy",
     "Streptococcus mutans; metronidazole": "Streptococcus mutans; metronidazole therapy",
     "Streptococcus anginosus": "Streptococcus anginosus; doxycycline therapy"},
  why={"Streptococcus sanguinis; vancomycin plus rifampin": "S. sanguinis causes endocarditis but is not the main caries organism, and that regimen is for prosthetic staphylococcal infection.",
       "Streptococcus mitis; clindamycin as monotherapy": "Clindamycin is not adequate for endocarditis.",
       "Streptococcus mutans; metronidazole therapy": "The organism is right, but metronidazole covers anaerobes.",
       "Streptococcus anginosus; doxycycline therapy": "The anginosus group causes abscesses, and doxycycline is not used for endocarditis."},
  table=STREP),

"Listeria: epidemiology": dict(d="easy",
  why={"It forms heat-resistant spores": "Listeria forms no spores.",
       "It produces a preformed heat-stable toxin": "Listeriosis is an invasive infection, not a toxin-mediated one.",
       "It requires a mosquito vector": "It is food-borne.",
       "It is killed only by boiling": "Ordinary cooking kills it; the problem is growth in chilled ready-to-eat food."},
  table=GPR),

"Botulism: wound & adult": dict(d="hard",
  c="Wound botulism; give equine heptavalent antitoxin",
  o={"Foodborne botulism": "Foodborne botulism; give human botulism immune globulin",
     "Tetanus": "Tetanus; give diazepam alone for the spasms",
     "Myasthenia gravis": "Myasthenia gravis; give pyridostigmine",
     "Guillain-Barré": "Guillain-Barre syndrome; give IVIG"},
  why={"Foodborne botulism; give human botulism immune globulin": "He has no GI symptoms or food source, and BabyBIG is for infants.",
       "Tetanus; give diazepam alone": "Tetanus causes rigidity and spasms, not flaccid weakness.",
       "Myasthenia gravis; give pyridostigmine": "Myasthenia causes fatigable weakness without pupillary involvement or sudden onset.",
       "Guillain-Barre syndrome; give IVIG": "GBS is ascending with areflexia and sensory symptoms."},
  table=CLOSTRIDIA),

"Neonatal tetanus": dict(d="medium",
  c="Maternal tetanus toxoid plus clean cord care",
  o={"Erythromycin eye ointment": "Erythromycin eye ointment given at birth",
     "Neonatal BCG vaccination": "BCG vaccination given to the newborn",
     "Oral penicillin for all newborns": "Oral penicillin given to all newborns",
     "Hepatitis B vaccine at birth": "Hepatitis B vaccination given at birth"},
  why={"Erythromycin eye ointment given at birth": "That prevents gonococcal conjunctivitis.",
       "BCG vaccination given to the newborn": "BCG protects against severe tuberculosis.",
       "Oral penicillin given to all newborns": "Universal antibiotics are not effective prevention and drive resistance.",
       "Hepatitis B vaccination given at birth": "That prevents perinatal hepatitis B."},
  table=CLOSTRIDIA),

"Actinomyces: pelvic infection": dict(d="medium",
  c="Actinomyces israelii; normal mucosal flora",
  o={"Nocardia asteroides; soil": "Nocardia asteroides; found in soil",
     "Mycobacterium tuberculosis": "Mycobacterium tuberculosis; found in human lungs",
     "Aspergillus fumigatus": "Aspergillus fumigatus; found in decaying vegetation",
     "Clostridium perfringens": "Clostridium perfringens; found in soil and colon"},
  why={"Nocardia asteroides; found in soil": "Nocardia is aerobic, weakly acid-fast, and infects the lungs and brain.",
       "Mycobacterium tuberculosis; found in human lungs": "TB causes caseating granulomas with acid-fast bacilli.",
       "Aspergillus fumigatus; found in decaying vegetation": "Aspergillus forms septate hyphae, not bacterial filaments.",
       "Clostridium perfringens; found in soil and colon": "C. perfringens causes gas gangrene with boxcar rods."},
  table=GPR),

"Nocardia: skin & microbiology": dict(d="hard",
  why={"Chromoblastomycosis": "That is a fungal infection with sclerotic bodies on biopsy.",
       "Sporotrichosis": "Sporotrichosis spreads along lymphatics rather than forming grain-filled sinuses.",
       "Gas gangrene": "Gas gangrene is acute, painful, and rapidly progressive.",
       "Cellulitis from Streptococcus pyogenes": "Streptococcal cellulitis is acute and does not form grains."},
  table=GPR),

"N. meningitidis: epidemiology": dict(d="easy",
  c="The quadrivalent conjugate vaccine (MenACWY)",
  o={"Serogroup B vaccine only": "A serogroup B protein vaccine alone",
     "BCG": "The BCG vaccine",
     "Typhoid Vi vaccine": "The typhoid Vi polysaccharide vaccine",
     "Japanese encephalitis vaccine": "The Japanese encephalitis vaccine"},
  why={"A serogroup B protein vaccine alone": "Serogroup B is not the epidemic strain in this region and is not required for Hajj.",
       "The BCG vaccine": "BCG protects against severe tuberculosis.",
       "The typhoid Vi polysaccharide vaccine": "That protects against typhoid fever, a different travel risk.",
       "The Japanese encephalitis vaccine": "That is for rural Asia, not the African meningitis belt."},
  table=NEISSERIA),

"H. influenzae: meningitis management": dict(d="medium",
  why={"Ampicillin alone; no prophylaxis": "Many strains make beta-lactamase, and contacts need prophylaxis.",
       "Vancomycin; azithromycin prophylaxis": "Vancomycin lacks Gram-negative activity.",
       "Gentamicin; ciprofloxacin prophylaxis": "Aminoglycosides penetrate the CSF poorly.",
       "Penicillin G; penicillin V prophylaxis": "Penicillin is inadequate against beta-lactamase producers."},
  table=HAEMOPHILUS_BORD_LEG),

"Pertussis: clinical stages": dict(d="medium",
  why={"Catarrhal stage; the vaccine is live and reverts": "The catarrhal stage is the early cold-like phase, and acellular vaccine contains no live organism.",
       "Convalescent stage; she lacks complement": "The convalescent stage has a waning cough, and complement is not involved.",
       "Catarrhal stage; she has IgA deficiency": "She is past the catarrhal stage, and IgA deficiency is not the usual reason.",
       "Paroxysmal stage; the vaccine protects only against parapertussis": "The stage is right, but the vaccine targets B. pertussis."},
  table=HAEMOPHILUS_BORD_LEG),

"Legionella: laboratory": dict(d="medium",
  why={"The organism lacks a cell wall and grows on Eaton agar": "That describes Mycoplasma.",
       "The organism is acid-fast and grows on Löwenstein-Jensen medium": "That describes mycobacteria.",
       "The organism is an obligate intracellular pathogen that cannot be cultured": "Legionella is facultative intracellular and can be cultured on BCYE.",
       "The organism needs factor X and V on chocolate agar": "That describes Haemophilus influenzae."},
  table=MEDIA),

"Moraxella catarrhalis: epidemiology": dict(d="easy",
  why={"S. aureus, S. pyogenes, and Enterococcus": "These are not the usual COPD exacerbation organisms.",
       "Legionella, Chlamydia psittaci, and Coxiella": "These cause atypical pneumonia rather than routine COPD flares.",
       "Klebsiella, Proteus, and E. coli": "These are more typical of aspiration or hospital-acquired infection.",
       "Mycobacterium avium, Nocardia, and Aspergillus": "These cause chronic or opportunistic lung disease."},
  table=HAEMOPHILUS_BORD_LEG),

"Burkholderia cepacia": dict(d="hard",
  why={"Pseudomonas aeruginosa": "Pseudomonas is more common in CF but usually responds to antipseudomonal drugs and does not bar transplant.",
       "Staphylococcus aureus": "S. aureus predominates in early CF and is treatable.",
       "Stenotrophomonas maltophilia": "Stenotrophomonas is resistant but is not a transplant contraindication.",
       "Haemophilus influenzae": "H. influenzae causes milder CF airway infection."},
  table=ANTI_PSEUDOMONAL),

"Klebsiella: liver abscess & ESBL": dict(d="hard",
  why={"Ceftriaxone": "ESBLs hydrolyze third-generation cephalosporins.",
       "Ampicillin-sulbactam": "Klebsiella is intrinsically ampicillin-resistant, and sulbactam is unreliable against ESBLs.",
       "Cefazolin": "First-generation cephalosporins are readily destroyed by ESBLs.",
       "Aztreonam": "Aztreonam is hydrolyzed by ESBLs."},
  table=RESISTANCE),

"Serratia & Enterobacter: AmpC": dict(d="hard",
  why={"Acquisition of PBP2a; vancomycin": "PBP2a is the MRSA mechanism in a Gram-positive organism.",
       "Loss of 30S binding; tetracycline": "Ribosomal changes do not explain cephalosporin failure.",
       "Target mutation in DNA gyrase; ampicillin": "Gyrase mutations affect fluoroquinolones.",
       "Efflux of polymyxins; colistin": "Colistin resistance is not the issue with a cephalosporin."},
  table=RESISTANCE),

"Acinetobacter": dict(d="medium",
  why={"Neisseria meningitidis": "Meningococcus causes meningitis and sepsis, not ventilator pneumonia.",
       "Haemophilus influenzae": "H. influenzae is usually susceptible and causes community infections.",
       "Moraxella catarrhalis": "Moraxella causes respiratory infections but is not carbapenem-resistant.",
       "Bordetella pertussis": "Pertussis causes whooping cough in the community."},
  table=ANTI_PSEUDOMONAL),

"Salmonella Typhi: carriers & vaccines": dict(d="medium",
  why={"The terminal ileum; there is no vaccine": "Two typhoid vaccines exist, and carriage is gallbladder-based.",
       "The liver; a toxoid vaccine": "There is no typhoid toxoid vaccine.",
       "Mesenteric lymph nodes; a conjugate pertussis-typhoid vaccine": "No such combination vaccine exists.",
       "The spleen; BCG": "BCG protects against tuberculosis."},
  table=SALM_SHIG),

"Shigella: treatment & complications": dict(d="medium",
  why={"Antibiotics are contraindicated because they always cause HUS": "The HUS concern applies to EHEC, not Shigella.",
       "Shigella produces cholera-like toxin, so rehydration is the only treatment": "Shigella is invasive and antibiotics help.",
       "Shigella is spread mainly by undercooked poultry": "Poultry is the Salmonella and Campylobacter route; Shigella spreads person to person.",
       "Shigella has a very high infectious dose": "Its infectious dose is remarkably low."},
  table=SALM_SHIG),

"Vibrio parahaemolyticus": dict(d="easy",
  why={"Vibrio vulnificus": "V. vulnificus causes fulminant sepsis in people with liver disease.",
       "Clostridium botulinum": "Botulism causes paralysis, not diarrhea.",
       "Hepatitis E virus": "HEV causes hepatitis after weeks, not acute diarrhea.",
       "Diphyllobothrium latum": "That tapeworm causes B12 deficiency over months."},
  table=VIBRIO),

"Campylobacter: microbiology & treatment": dict(d="medium",
  why={"It is a spore-forming Gram-positive rod treated with vancomycin": "Campylobacter is a Gram-negative curved rod.",
       "It is a non-motile rod spread only person to person": "It is motile and comes mainly from animal sources.",
       "It produces cholera toxin": "It causes invasive inflammatory diarrhea instead.",
       "It is resistant to macrolides by nature": "Macrolides are the treatment of choice."},
  table=DIARRHEA),

"Plague: pneumonic form": dict(d="medium",
  why={"Contact precautions only, because plague is spread only by fleas": "Pneumonic plague spreads by respiratory droplets between people.",
       "Airborne precautions with negative pressure only, and no prophylaxis": "Droplet precautions suffice, and contacts do need prophylaxis.",
       "No precautions, because plague does not spread person to person": "Pneumonic plague is highly transmissible.",
       "Isolation of the patient's pets only": "Isolating pets does not address human-to-human spread."},
  table=ZOONOSES),

"Francisella: pathogenesis": dict(d="hard",
  why={"Yersinia pestis; it forms a poly-D-glutamate capsule": "Y. pestis has an F1 protein capsule and is flea-borne.",
       "Bacillus anthracis; it forms spores in the lung": "Anthrax spores germinate in mediastinal nodes after inhalation.",
       "Coxiella burnetii; it forms elementary bodies": "Elementary bodies belong to Chlamydia; Coxiella has a small-cell variant.",
       "Brucella abortus; it is spread by fleas": "Brucella comes from unpasteurized dairy and livestock contact."},
  table=ZOONOSES),

"Brucella: pathogenesis & lab safety": dict(d="hard",
  why={"They produce a toxin that cleaves hCG; they form spores": "Brucella makes no such toxin and forms no spores.",
       "They cross the placenta through a type III secretion system; they cause anaphylaxis": "Placental tropism is due to erythritol, not a secretion system.",
       "They block progesterone receptors; they are acid-fast": "Brucella is not acid-fast.",
       "They are spread by ticks in barns; they need BSL-1 handling only": "Brucella requires BSL-3 precautions."},
  table=ZOONOSES),

"Capnocytophaga": dict(d="medium",
  why={"Pasteurella multocida": "Pasteurella causes rapid local cellulitis rather than fulminant sepsis.",
       "Bartonella henselae": "Bartonella causes regional lymphadenopathy after cat exposure.",
       "Eikenella corrodens": "Eikenella follows human bites.",
       "Streptococcus pyogenes": "GAS causes cellulitis or necrotizing fasciitis, usually after skin breach."},
  table=ZOONOSES),

"Bartonella quintana": dict(d="medium",
  why={"Rickettsia prowazekii": "Epidemic typhus is also louse-borne but causes a rash and no endocarditis.",
       "Borrelia recurrentis": "Louse-borne relapsing fever causes recurrent fevers with spirochetes on smear.",
       "Coxiella burnetii": "Q fever endocarditis follows livestock exposure.",
       "Bartonella henselae": "B. henselae is cat-associated and causes cat scratch disease."},
  table=ZOONOSES),

"Lyme: serologic testing": dict(d="medium",
  why={"Serology is negative in late Lyme disease, so diagnose clinically": "Serology is almost always positive in late disease.",
       "Blood culture on routine media": "B. burgdorferi does not grow on routine media.",
       "Dark-field microscopy of synovial fluid": "Dark-field is used for Treponema in primary syphilis lesions.",
       "Wright-stained blood smear showing spirochetes": "Only relapsing fever Borrelia is visible on blood smear."},
  table=LYME_STAGES),

"Leptospira: reservoir & shedding": dict(d="medium",
  why={"It forms spores in animal feces": "Leptospira forms no spores.",
       "It is carried in the salivary glands of fleas": "Fleas carry plague and murine typhus.",
       "It persists in animal lung cavities": "The renal tubules are the carrier site.",
       "It grows in the animals' red blood cells": "It is not an intraerythrocytic organism."},
  table=ZOONOSES),

"Anaplasma": dict(d="medium",
  why={"Amblyomma americanum, the lone star tick": "Amblyomma carries Ehrlichia, which forms morulae in monocytes.",
       "Dermacentor variabilis": "Dermacentor carries RMSF and tularemia.",
       "Ornithodoros soft tick": "Ornithodoros carries tick-borne relapsing fever.",
       "Rhipicephalus sanguineus": "That tick carries RMSF in parts of the southwest."},
  table=TICKBORNE),

"Murine typhus & Rickettsia summary": dict(d="hard",
  why={"Rickettsia rickettsii": "RMSF follows a tick bite and involves the palms and soles.",
       "Rickettsia prowazekii": "Epidemic typhus is louse-borne in crowded settings.",
       "Coxiella burnetii": "Q fever causes pneumonia or hepatitis without a rash.",
       "Ehrlichia chaffeensis": "Ehrlichiosis is tick-borne and usually rash-free with cytopenias."},
  table=RICKETTSIAE),

"Leprosy: tuberculoid": dict(d="medium",
  why={"Isoniazid alone; by skin contact with the plaque": "Isoniazid is a TB drug, and monotherapy is inadequate.",
       "Clofazimine alone; by mosquito bites": "No mosquito transmits leprosy, and monotherapy is inadequate.",
       "Penicillin; by sexual contact": "Leprosy is not sexually transmitted and does not respond to penicillin.",
       "No treatment; it is not transmissible": "Untreated disease progresses and causes nerve damage."},
  table=LEPROSY),

"Nontuberculous mycobacteria: overview": dict(d="medium",
  why={"They are all obligate human pathogens transmitted by aerosol": "They are environmental organisms without human-to-human spread.",
       "They cause positive IGRA results in most cases": "IGRAs are specific for M. tuberculosis antigens.",
       "They are treated with isoniazid monotherapy": "Most are resistant, and combination therapy is required.",
       "They cannot cause lung disease in immunocompetent hosts": "MAC and M. kansasii cause lung disease in people with structural lung disease."}),

"Mycoplasma: molecular features": dict(d="medium",
  why={"It has a poly-D-glutamate capsule": "That capsule is unique to B. anthracis.",
       "It has mycolic acids": "Mycolic acids belong to mycobacteria.",
       "It has two membranes with LPS and a thick peptidoglycan wall": "Mycoplasma has one membrane and no wall.",
       "It forms endospores": "Mycoplasma forms no spores."},
  table=ATYPICAL_PNA),

"HACEK & Kingella": dict(d="hard",
  why={"Haemophilus ducreyi": "H. ducreyi causes chancroid, a genital ulcer disease.",
       "Neisseria gonorrhoeae": "Gonococcal arthritis occurs in sexually active adults.",
       "Salmonella enteritidis": "Salmonella arthritis or osteomyelitis is seen in sickle cell disease.",
       "Pasteurella multocida": "Pasteurella follows animal bites."}),

"Gardnerella: pathophysiology": dict(d="medium",
  why={"Candida overgrowth producing ammonia": "Candida does not raise vaginal pH or produce amines.",
       "Trichomonas consuming lactic acid": "Trichomonas raises pH but the clue cells here indicate BV.",
       "Neisseria gonorrhoeae producing urease": "Gonococci do not produce urease or this discharge.",
       "Estrogen deficiency thinning the epithelium only": "Atrophic vaginitis raises pH but lacks clue cells and amines."},
  table=VAGINITIS),

"HIV: monitoring": dict(d="easy",
  why={"p24 antigen and Western blot": "Those are diagnostic tools, not monitoring tests.",
       "HIV antibody titer and ESR": "Antibody titers do not track disease activity.",
       "Monospot and CBC": "Monospot tests for EBV.",
       "IGRA and chest radiograph": "Those screen for tuberculosis."},
  table=HIV_OI),

"HIV: pathogenesis": dict(d="hard",
  why={"Thymus": "Thymic output declines over time but is not the earliest site of massive depletion.",
       "Bone marrow": "Marrow is affected late and indirectly.",
       "Peripheral blood B cells": "HIV targets CD4 T cells, not B cells.",
       "Spleen red pulp": "The red pulp filters red cells rather than housing CCR5+ memory T cells."}),

"HIV-associated conditions": dict(d="hard",
  why={"Minimal change disease": "Minimal change disease is idiopathic or drug-related and responds to steroids.",
       "Membranous nephropathy": "Membranous nephropathy is linked to hepatitis B, lupus, and solid tumors.",
       "Crescentic glomerulonephritis": "Crescentic GN presents with nephritic features and rapid decline.",
       "Diabetic nodular glomerulosclerosis": "That requires long-standing diabetes."},
  table=HIV_OI),
}
