from tables import *
R = {
"RMSF: clinical": dict(d="medium",
  why={"Amoxicillin": "Beta-lactams are inactive against obligate intracellular rickettsiae.",
       "Chloramphenicol only if older than 8": "Chloramphenicol is inferior and carries marrow toxicity; doxycycline is preferred at any age.",
       "Azithromycin": "Macrolides are not reliable therapy for RMSF.",
       "Ceftriaxone": "Ceftriaxone does not penetrate host cells or cover rickettsiae."},
  table=TICKBORNE),

"RMSF: pathogenesis": dict(d="medium",
  c="Vascular endothelial cells",
  o={"Hepatocytes": "Hepatocytes in the liver",
     "Monocytes": "Circulating blood monocytes",
     "Neutrophils": "Circulating neutrophils",
     "Erythrocytes": "Circulating erythrocytes"},
  why={"Hepatocytes in the liver": "Hepatitis can occur but does not explain the rash or capillary leak.",
       "Circulating blood monocytes": "Ehrlichia infects monocytes; R. rickettsii targets endothelium.",
       "Circulating neutrophils": "Anaplasma infects granulocytes.",
       "Circulating erythrocytes": "Malaria and Babesia infect red cells."},
  table=RICKETTSIAE),

"Epidemic typhus": dict(d="medium",
  c="Rickettsia prowazekii; later Brill-Zinsser disease",
  o={"Rickettsia typhi": "Rickettsia typhi; later Guillain-Barre syndrome",
     "Rickettsia rickettsii": "Rickettsia rickettsii; later chronic arthritis",
     "Bartonella quintana": "Bartonella quintana; later bacillary angiomatosis",
     "Borrelia recurrentis": "Borrelia recurrentis; later chronic meningitis"},
  why={"Rickettsia typhi": "Murine typhus is flea-borne and milder, and it is not followed by recrudescence.",
       "Rickettsia rickettsii": "RMSF is tick-borne with a rash that starts peripherally and involves palms and soles.",
       "Bartonella quintana": "Trench fever is louse-borne but causes 5-day fevers and shin pain, not this rash.",
       "Borrelia recurrentis": "Louse-borne relapsing fever causes recurring febrile episodes, not a fixed exanthem."},
  table=RICKETTSIAE),

"Ehrlichiosis": dict(d="medium",
  why={"Anaplasma phagocytophilum": "Anaplasma forms morulae in granulocytes and is spread by Ixodes ticks.",
       "Babesia microti": "Babesia parasites lie within red cells and cause hemolysis.",
       "Rickettsia rickettsii": "RMSF usually has a prominent rash and does not form morulae.",
       "Borrelia burgdorferi": "Lyme disease causes erythema migrans without morulae."},
  table=TICKBORNE),

"Coxiella: Q fever": dict(d="hard",
  c="A resistant spore-like form inhaled from birth products",
  o={"It is spread only by tick": "It is spread to humans only by tick bites",
     "It spreads person to person": "It spreads person to person by respiratory droplets",
     "It is acquired by eating": "It is acquired by eating undercooked lamb",
     "It requires a mosquito": "It requires a mosquito vector to reach humans"},
  why={"It is spread to humans only by tick bites": "Ticks maintain it in animals, but human infection is by inhalation.",
       "It spreads person to person by respiratory droplets": "Person-to-person spread essentially does not occur.",
       "It is acquired by eating undercooked lamb": "Unpasteurized milk can transmit it, but aerosol exposure explains outbreaks.",
       "It requires a mosquito vector": "No mosquito vector is involved."},
  table=ZOONOSES),

"Culture-negative endocarditis": dict(d="medium",
  why={"Staphylococcus aureus": "S. aureus grows readily in blood culture.",
       "Streptococcus sanguinis": "Viridans strep are easily cultured from blood.",
       "Enterococcus faecalis": "Enterococci grow readily on routine media.",
       "Escherichia coli": "E. coli grows readily and rarely causes endocarditis."},
  table=ZOONOSES),

"Chlamydia: life cycle": dict(d="medium",
  c="Elementary bodies enter cells; reticulate bodies divide",
  o={"The reticulate body is the infectious": "Reticulate bodies are the infectious extracellular form",
     "It replicates in the nucleus": "It replicates in the nucleus using host DNA polymerase",
     "It synthesizes its own ATP": "It makes its own ATP and needs no host cell",
     "It has a thick peptidoglycan": "It has a thick peptidoglycan wall rich in muramic acid"},
  why={"Reticulate bodies are the infectious extracellular form": "The roles are reversed; reticulate bodies are fragile and intracellular.",
       "It replicates in the nucleus": "Chlamydiae replicate in a cytoplasmic inclusion, not the nucleus.",
       "It makes its own ATP": "They are energy parasites that take host ATP.",
       "It has a thick peptidoglycan wall": "Their wall lacks classic muramic acid, which is why beta-lactams fail."},
  table=CHLAMYDIA_SEROVARS),

"Chlamydia trachomatis: urogenital": dict(d="easy",
  why={"A single dose of IM ceftriaxone": "Ceftriaxone treats gonorrhea, which was excluded here.",
       "Penicillin G": "Chlamydiae lack classic peptidoglycan, so beta-lactams do not work.",
       "Metronidazole for 7 days": "Metronidazole treats trichomoniasis and bacterial vaginosis.",
       "Fluconazole single dose": "Fluconazole treats candidal vaginitis."},
  table=CHLAMYDIA_SEROVARS),

"Chlamydia: PID & Fitz-Hugh-Curtis": dict(d="medium",
  c="Ectopic pregnancy and tubal infertility",
  o={"Cervical cancer": "Invasive cervical carcinoma",
     "Hepatocellular carcinoma": "Hepatocellular carcinoma",
     "Bladder cancer": "Carcinoma of the bladder",
     "Osteomyelitis": "Chronic pelvic osteomyelitis"},
  why={"Invasive cervical carcinoma": "Cervical cancer is caused by high-risk HPV, not chlamydial salpingitis.",
       "Hepatocellular carcinoma": "Perihepatitis causes adhesions on the capsule, not liver cancer.",
       "Carcinoma of the bladder": "Bladder squamous carcinoma is linked to Schistosoma haematobium.",
       "Chronic pelvic osteomyelitis": "PID does not typically spread to bone."}),

"Chlamydia: neonatal pneumonia": dict(d="medium",
  why={"IV ampicillin and gentamicin": "That regimen targets early-onset bacterial sepsis in the first week.",
       "IV acyclovir": "Acyclovir treats neonatal HSV, which causes vesicles or encephalitis.",
       "Ceftriaxone": "Ceftriaxone does not cover Chlamydia and risks kernicterus in neonates.",
       "Oral amoxicillin": "Beta-lactams are ineffective against Chlamydia."},
  table=CHLAMYDIA_SEROVARS),

"Chlamydia: serotypes": dict(d="medium",
  why={"A–C": "Serovars A-C cause trachoma, a chronic eye infection.",
       "D–K": "Serovars D-K cause urethritis and cervicitis without buboes.",
       "A–K": "That range mixes ocular and genital serovars and is not the LGV group.",
       "Serovars of C. psittaci": "C. psittaci causes pneumonia after bird exposure."},
  table=CHLAMYDIA_SEROVARS),

"Chlamydia: trachoma": dict(d="medium",
  c="C. trachomatis A-C; spread by hands, flies, and cloths",
  o={"C. trachomatis serovars D–K": "C. trachomatis serovars D-K; acquired at birth",
     "Onchocerca volvulus": "Onchocerca volvulus; spread by blackfly bites",
     "Neisseria gonorrhoeae": "Neisseria gonorrhoeae; spread by sexual contact",
     "Acanthamoeba": "Acanthamoeba; from contaminated lens solution"},
  why={"C. trachomatis serovars D-K": "Those serovars cause neonatal conjunctivitis, which does not scar the lids this way.",
       "Onchocerca volvulus": "River blindness causes keratitis and skin nodules, not entropion from lid scarring.",
       "Neisseria gonorrhoeae": "Gonococcal conjunctivitis is hyperacute and purulent.",
       "Acanthamoeba": "Acanthamoeba keratitis is painful and affects contact lens wearers."},
  table=CHLAMYDIA_SEROVARS),

"Chlamydophila pneumoniae & psittaci": dict(d="easy",
  why={"Coxiella burnetii; ciprofloxacin": "Q fever comes from livestock, and doxycycline is the treatment.",
       "Histoplasma capsulatum; itraconazole": "Histoplasma comes from bird or bat droppings in river valleys, not sick parrots.",
       "Cryptococcus neoformans; fluconazole": "Cryptococcus causes meningitis in immunocompromised hosts.",
       "Legionella pneumophila; amoxicillin": "Legionella comes from water aerosols and does not respond to amoxicillin."},
  table=ATYPICAL_PNA),

"Atypical pneumonia: organism features": dict(d="medium",
  c="Obligate intracellular growth, using host ATP or cofactors",
  o={"Lack of a cell wall": "Absence of a cell wall, with membrane cholesterol",
     "Acid-fast staining": "Acid-fast staining caused by mycolic acids",
     "Spread only by arthropod": "Transmission exclusively by arthropod vectors",
     "Easy growth on blood agar": "Ready growth on ordinary blood agar plates"},
  why={"Absence of a cell wall": "That is Mycoplasma, which is not obligately intracellular.",
       "Acid-fast staining caused by mycolic acids": "That describes mycobacteria and Nocardia.",
       "Transmission exclusively by arthropod vectors": "Chlamydia and Coxiella spread without arthropods.",
       "Ready growth on ordinary blood agar plates": "None of these three grows on cell-free media."},
  table=ATYPICAL_PNA),
}
