from tables import *
R = {
"N. meningitidis: identification": dict(d="easy",
  why={"Ferments glucose only": "Glucose-only fermentation identifies N. gonorrhoeae, which does not cause epidemic meningitis.",
       "Ferments lactose rapidly": "Neisseria species do not ferment lactose; that pattern suggests enteric Gram-negative rods.",
       "Ferments neither": "Moraxella catarrhalis is asaccharolytic and rarely causes meningitis.",
       "Ferments sucrose only": "Sucrose-only fermentation is not a Neisseria pattern."},
  table=NEISSERIA),

"N. meningitidis: Waterhouse-Friderichsen": dict(d="medium",
  c="Lipooligosaccharide shed during heavy bacteremia",
  o={"An A-B exotoxin": "An A-B exotoxin that ADP-ribosylates EF-2",
     "A superantigen": "A superantigen that binds MHC class II molecules",
     "A protein capsule": "A protein capsule made of poly-D-glutamate",
     "IgA1 protease": "An IgA1 protease secreted at mucosal surfaces"},
  why={"An A-B exotoxin": "EF-2 inactivation is diphtheria and Pseudomonas exotoxin A, which do not cause adrenal hemorrhage.",
       "A superantigen": "Superantigens cause staphylococcal and streptococcal toxic shock without this adrenal lesion.",
       "A protein capsule": "Poly-D-glutamate capsules are unique to B. anthracis.",
       "An IgA1 protease": "IgA protease helps colonization but does not drive shock and DIC."},
  table=ENDO_EXO),

"N. meningitidis: complement deficiency": dict(d="medium",
  c="Low CH50 from terminal complement deficiency",
  o={"Absent B cells": "Absent B cells on peripheral flow cytometry",
     "Abnormal dihydrorhodamine": "An abnormal dihydrorhodamine flow cytometry test",
     "Low serum IgA": "Low serum IgA with normal IgG and IgM",
     "Deficiency of C1 esterase": "Deficiency of the C1 esterase inhibitor protein"},
  why={"Absent B cells": "Agammaglobulinemia causes recurrent encapsulated bacterial and enteroviral infections from infancy.",
       "An abnormal dihydrorhodamine": "That indicates chronic granulomatous disease, with catalase-positive infections.",
       "Low serum IgA": "IgA deficiency causes sinopulmonary infection and giardiasis, not recurrent meningococcemia.",
       "Deficiency of the C1 esterase inhibitor": "C1-INH deficiency causes hereditary angioedema, not infection."},
  table=IMMUNODEF),

"N. meningitidis: chemoprophylaxis": dict(d="easy",
  c="Rifampin, ciprofloxacin, or one dose of ceftriaxone",
  o={"Oral penicillin V": "A 10-day course of oral penicillin V",
     "Azithromycin": "A five-day course of oral azithromycin",
     "Vancomycin": "A course of intravenous vancomycin",
     "No prophylaxis": "No prophylaxis unless she develops symptoms"},
  why={"A 10-day course of oral penicillin V": "Penicillin treats disease but does not reliably clear nasopharyngeal carriage.",
       "A five-day course of oral azithromycin": "Azithromycin is only an alternative and is not first-line for contacts.",
       "A course of intravenous vancomycin": "Vancomycin has no Gram-negative activity.",
       "No prophylaxis unless she develops symptoms": "Waiting is unsafe, since disease can progress within hours."},
  table=NEISSERIA),

"N. meningitidis: vaccines": dict(d="hard",
  c="Its polysialic acid capsule mimics human neural molecules",
  o={"Serogroup B lacks a capsule": "Serogroup B organisms have no capsule at all",
     "Serogroup B only infects": "Serogroup B infects only infants and young children",
     "Serogroup B capsule is identical": "Its capsule is identical to that of H. influenzae type b",
     "Serogroup B undergoes phase": "Its capsule undergoes phase variation every generation"},
  why={"Serogroup B organisms have no capsule": "Serogroup B is encapsulated; the problem is that the capsule resembles self.",
       "Serogroup B infects only infants": "It causes disease across age groups, including adolescents.",
       "Its capsule is identical to that of H. influenzae type b": "Hib capsule is polyribosylribitol phosphate, a different polymer.",
       "Its capsule undergoes phase variation every generation": "Pili and Opa proteins vary in gonococci; the B capsule is stable."},
  table=VACCINES),

"N. gonorrhoeae: urethritis & treatment": dict(d="easy",
  c="One IM dose of ceftriaxone, plus doxycycline",
  o={"Oral penicillin V": "A 10-day course of oral penicillin V",
     "Azithromycin alone": "A single oral dose of azithromycin alone",
     "Metronidazole": "A single 2 gram oral dose of metronidazole",
     "Ciprofloxacin alone": "A single oral dose of ciprofloxacin alone"},
  why={"A 10-day course of oral penicillin V": "Penicillin resistance in gonococci is widespread.",
       "A single oral dose of azithromycin alone": "Monotherapy is no longer recommended because of rising resistance.",
       "A single 2 gram oral dose of metronidazole": "Metronidazole treats trichomoniasis, not gonorrhea.",
       "A single oral dose of ciprofloxacin alone": "Fluoroquinolone resistance is common, so they are no longer used empirically."},
  table=NEISSERIA),

"N. gonorrhoeae: antigenic variation": dict(d="hard",
  c="Pilin varies by gene conversion and Opa proteins switch",
  o={"The organism is an obligate": "It is an obligate intracellular organism hidden from antibody",
     "It has a polysaccharide capsule": "It has a polysaccharide capsule that is poorly immunogenic",
     "It produces a superantigen": "It produces a superantigen that deletes memory T cells",
     "It lacks surface proteins": "It lacks surface proteins that antibodies could recognize"},
  why={"It is an obligate intracellular organism": "Gonococci are extracellular for much of infection and can be cultured.",
       "It has a polysaccharide capsule": "N. gonorrhoeae has no capsule, unlike the meningococcus.",
       "It produces a superantigen": "Gonococci do not produce a superantigen.",
       "It lacks surface proteins": "It has abundant surface proteins; the issue is that they change constantly."},
  table=NEISSERIA),

"N. gonorrhoeae: ophthalmia neonatorum": dict(d="medium",
  c="Neisseria gonorrhoeae; erythromycin eye ointment",
  o={"Chlamydia trachomatis": "Chlamydia trachomatis; oral erythromycin at birth",
     "Staphylococcus aureus": "Staphylococcus aureus; chlorhexidine bathing at birth",
     "Herpes simplex virus": "Herpes simplex virus; IV acyclovir at birth",
     "Pseudomonas aeruginosa": "Pseudomonas aeruginosa; topical gentamicin at birth"},
  why={"Chlamydia trachomatis": "Chlamydial conjunctivitis appears at 5-14 days, is less purulent, and is not prevented by ointment.",
       "Staphylococcus aureus": "Staphylococcal conjunctivitis is not this hyperacute and is not routinely prevented.",
       "Herpes simplex virus": "HSV causes vesicular keratoconjunctivitis, not copious pus.",
       "Pseudomonas aeruginosa": "Pseudomonas conjunctivitis occurs mainly in preterm or ICU infants."}),

"N. gonorrhoeae: disseminated infection": dict(d="medium",
  why={"Reactive arthritis after Chlamydia": "Reactive arthritis is sterile and follows infection by weeks, without pustules or tenosynovitis.",
       "Acute rheumatic fever": "ARF follows strep pharyngitis and features carditis and migratory arthritis.",
       "Lyme arthritis": "Lyme arthritis is a late monoarthritis of the knee after a tick exposure.",
       "Staphylococcal septic arthritis": "Staphylococcal arthritis is usually a single hot joint without the dermatitis-tenosynovitis triad."}),

"Neisseria: selective media": dict(d="medium",
  why={"Vancomycin: fungi": "The pairings are scrambled; vancomycin acts on Gram-positive bacteria.",
       "Vancomycin: Neisseria commensals": "Vancomycin does not inhibit Neisseria, which is why the organism survives on this medium.",
       "All additives inhibit anaerobes": "The medium is not designed for anaerobes.",
       "All additives inhibit Gram-negative rods": "Only colistin targets Gram-negatives here."},
  table=MEDIA),

"Moraxella catarrhalis": dict(d="medium",
  c="Amoxicillin-clavulanate, since most strains make beta-lactamase",
  o={"Vancomycin": "Vancomycin, because the organism has altered PBPs",
     "Azithromycin": "Azithromycin, because the organism has no cell wall",
     "Doxycycline": "Doxycycline, because the organism lives inside cells",
     "Metronidazole": "Metronidazole, because the organism is an anaerobe"},
  why={"Vancomycin": "Vancomycin has no Gram-negative activity, and altered PBPs are a pneumococcal mechanism.",
       "Azithromycin": "Moraxella has a cell wall; Mycoplasma is the organism that lacks one.",
       "Doxycycline": "Moraxella is extracellular, not an intracellular pathogen.",
       "Metronidazole": "Moraxella is aerobic, so metronidazole is inactive."},
  table=HAEMOPHILUS_BORD_LEG),

"H. influenzae type b: epiglottitis": dict(d="easy",
  c="The polyribosylribitol phosphate capsule",
  o={"Lipooligosaccharide": "Lipooligosaccharide in the outer membrane",
     "IgA protease": "Secreted IgA protease at the mucosal surface",
     "Pili": "Pili that mediate epithelial attachment",
     "Outer membrane protein P6": "Outer membrane protein P6 in the cell envelope"},
  why={"Lipooligosaccharide": "LOS contributes to inflammation but is not the vaccine target.",
       "Secreted IgA protease": "IgA protease aids colonization and is shared with several mucosal pathogens.",
       "Pili": "Pili help attachment, but the conjugate vaccine targets the capsule.",
       "Outer membrane protein P6": "P6 is used only as a carrier or research antigen, not the protective target."},
  table=HAEMOPHILUS_BORD_LEG),

"H. influenzae: growth factors": dict(d="medium",
  c="It needs factors X and V, which lysed RBCs supply",
  o={"It requires cysteine and iron": "It requires cysteine and iron supplied by S. aureus",
     "It requires 10% CO2": "It requires the 10% CO2 that S. aureus generates",
     "S. aureus secretes β-lactamase": "S. aureus secretes beta-lactamase that protects it",
     "It requires cholesterol": "It requires cholesterol released from lysed staphylococci"},
  why={"It requires cysteine and iron": "Cysteine and iron are the growth requirements of Legionella on BCYE agar.",
       "It requires the 10% CO2": "Capnophilic growth does not explain satellite colonies around a hemolytic organism.",
       "S. aureus secretes beta-lactamase": "There is no penicillin in the agar; the issue is nutritional.",
       "It requires cholesterol": "Sterol requirement is a Mycoplasma feature."},
  table=MEDIA),

"H. influenzae: nontypeable disease": dict(d="medium",
  c="Otitis media and COPD flares from unencapsulated strains",
  o={"Epiglottitis caused by type b": "Epiglottitis caused by encapsulated type b strains",
     "Meningitis in infants": "Infant meningitis caused by encapsulated type b strains",
     "Septic arthritis in young": "Septic arthritis in toddlers from type b strains",
     "Waterhouse-Friderichsen": "Waterhouse-Friderichsen syndrome with adrenal hemorrhage"},
  why={"Epiglottitis caused by encapsulated type b": "Invasive type b disease has become rare since Hib vaccination.",
       "Infant meningitis caused by encapsulated type b": "Hib meningitis is now uncommon in vaccinated populations.",
       "Septic arthritis in toddlers": "This was a type b syndrome and is now rare.",
       "Waterhouse-Friderichsen syndrome": "That is classically meningococcal, not Haemophilus."},
  table=HAEMOPHILUS_BORD_LEG),

"B. pertussis: toxin mechanism": dict(d="medium",
  c="ADP-ribosylation of Gi, removing cyclase inhibition",
  o={"ADP-ribosylation of Gs": "ADP-ribosylation of Gs, locking it in the active state",
     "Glucosylation of Rho": "Glucosylation of Rho-family GTPases in the cytosol",
     "Cleavage of SNARE": "Cleavage of SNARE proteins at nerve terminals",
     "Activation of guanylyl cyclase": "Direct activation of membrane guanylyl cyclase"},
  why={"ADP-ribosylation of Gs": "That is cholera and ETEC heat-labile toxin, which cause watery diarrhea.",
       "Glucosylation of Rho": "Rho glucosylation is C. difficile toxin activity.",
       "Cleavage of SNARE": "SNARE cleavage causes tetanus or botulism.",
       "Direct activation of membrane guanylyl cyclase": "ETEC heat-stable toxin raises cGMP in the gut."},
  table=TOXINS),

"B. pertussis: treatment & prevention": dict(d="medium",
  c="Azithromycin for him and for all household contacts",
  o={"Amoxicillin for the patient only": "Amoxicillin for the patient only, with no prophylaxis",
     "No antibiotics because": "No antibiotics, since the paroxysmal stage has begun",
     "Oseltamivir": "Oseltamivir for both the patient and his sister",
     "Pertussis immune globulin": "Pertussis immune globulin given to the infant sister"},
  why={"Amoxicillin for the patient only": "Amoxicillin is not effective, and untreated contacts keep transmitting to the infant.",
       "No antibiotics": "Macrolides still reduce transmission even when the cough will not improve.",
       "Oseltamivir": "Oseltamivir treats influenza and has no antibacterial activity.",
       "Pertussis immune globulin": "There is no standard immune globulin product for pertussis prophylaxis."}),

"Legionella: clinical": dict(d="medium",
  why={"Cold agglutinin titer": "Cold agglutinins suggest Mycoplasma, which causes milder walking pneumonia.",
       "Sputum culture on sheep blood agar": "Legionella does not grow on standard blood agar.",
       "India ink stain": "India ink detects Cryptococcus in CSF.",
       "Acid-fast stain": "Acid-fast staining detects mycobacteria and Nocardia."},
  table=ATYPICAL_PNA),

"Legionella: intracellular pathogen & treatment": dict(d="easy",
  c="Levofloxacin or azithromycin",
  o={"Ceftriaxone alone": "Ceftriaxone given as single-drug therapy",
     "Ampicillin": "Ampicillin given as single-drug therapy",
     "Vancomycin": "Vancomycin given as single-drug therapy",
     "Aztreonam": "Aztreonam given as single-drug therapy"},
  why={"Ceftriaxone": "Beta-lactams penetrate host cells poorly and fail against intracellular Legionella.",
       "Ampicillin": "Ampicillin does not reach the intracellular compartment and lacks activity.",
       "Vancomycin": "Vancomycin covers Gram-positive organisms only.",
       "Aztreonam": "Aztreonam does not accumulate inside macrophages."},
  table=ATYPICAL_PNA),

"Pseudomonas: identification": dict(d="medium",
  why={"Staphyloxanthin": "Staphyloxanthin is the golden pigment of S. aureus and is an antioxidant.",
       "Prodigiosin": "Prodigiosin is the red pigment of Serratia marcescens.",
       "Melanin": "Melanin is a Cryptococcus virulence factor.",
       "Pyoverdine alone": "Pyoverdine is a yellow-green siderophore, but pyocyanin is the blue pigment that generates radicals."}),

"Pseudomonas: exotoxin A": dict(d="medium",
  why={"Cleaves 28S rRNA": "That is Shiga toxin, which causes dysentery and HUS.",
       "ADP-ribosylates Gs": "Gs ribosylation is cholera toxin, which causes watery diarrhea.",
       "Binds 30S ribosomal subunit": "That describes aminoglycoside antibiotics, not a bacterial toxin.",
       "Inhibits peptidyl transferase": "That is chloramphenicol's mechanism."},
  table=TOXINS),

"Pseudomonas: clinical syndromes": dict(d="easy",
  why={"Painless black eschar after handling wool": "That is cutaneous anthrax from B. anthracis.",
       "Lymphocutaneous nodules after a rose-thorn": "That is sporotrichosis, a fungal infection.",
       "Bull's-eye rash after a tick bite": "Erythema migrans indicates Lyme disease.",
       "Bullous impetigo in a neonate": "Bullous impetigo is caused by S. aureus exfoliative toxin."}),

"Pseudomonas: antibiotics": dict(d="medium",
  why={"Piperacillin-tazobactam": "Piperacillin-tazobactam has reliable antipseudomonal activity.",
       "Cefepime": "Cefepime is a fourth-generation cephalosporin with antipseudomonal coverage.",
       "Meropenem": "Meropenem covers Pseudomonas, unlike ertapenem.",
       "Aztreonam": "Aztreonam covers Gram-negative rods including Pseudomonas."},
  table=ANTI_PSEUDOMONAL),

"Pseudomonas: hot tub folliculitis": dict(d="easy",
  why={"Staphylococcus aureus": "Staphylococcal folliculitis is not linked to hot tub exposure in outbreaks.",
       "Malassezia furfur": "Malassezia folliculitis is chronic and not water-associated.",
       "Legionella pneumophila": "Legionella from water aerosols causes pneumonia, not folliculitis.",
       "Mycobacterium marinum": "M. marinum causes nodules after aquarium or water exposure to broken skin."}),

"Pseudomonas: ecthyma gangrenosum": dict(d="medium",
  why={"Bacillus anthracis": "Anthrax eschars follow animal product exposure, not neutropenia.",
       "Rickettsia rickettsii": "RMSF causes a petechial rash starting at the wrists and ankles.",
       "Streptococcus pyogenes": "GAS causes painful cellulitis or necrotizing fasciitis, not this painless necrotic ulcer.",
       "Neisseria meningitidis": "Meningococcemia causes widespread purpura with shock, not an isolated lesion."}),
}
