"""Fourth pass: remove the last of the 'longest answer is correct' signal by extending one distractor."""
def _o(pairs): return dict(o=dict(pairs))
R = {
"S. aureus: scalded skin vs TEN": _o([("Suprabasal acantholysis with a tombstone basal layer", "Suprabasal acantholysis with a tombstone basal cell layer")]),
"S. pyogenes: PSGN vs ARF": _o([("It follows only pharyngeal infection and penicillin prevents it", "It follows only pharyngeal infection, and penicillin reliably prevents it")]),
"S. pneumoniae: vaccines": _o([("The carrier protein directly activates TLR4 on B cells", "The carrier protein directly activates TLR4 receptors on B cells")]),
"Spore formers: sterilization": _o([("Treating with quaternary ammonium compounds", "Treating with quaternary ammonium compounds only")]),
"N. meningitidis: chemoprophylaxis": _o([("No prophylaxis unless she develops symptoms", "No prophylaxis unless she develops symptoms herself")]),
"Pseudomonas: exotoxin A": _o([("Inhibits peptidyl transferase", "Inhibits the peptidyl transferase center")]),
"Campylobacter: Guillain-Barré": _o([("Toxin-mediated inhibition of spinal glycine release", "Toxin-mediated inhibition of spinal glycine release in the cord")]),
"H. pylori: virulence & disease": _o([("Catalase, which neutralizes hydrogen peroxide", "Catalase, which neutralizes hydrogen peroxide in the mucus")]),
"Y. pestis: morphology": _o([("Gram-positive rods in chains with central spores", "Gram-positive rods in long chains with central spores")]),
"Pasteurella multocida: cat bite": _o([("Staphylococcus aureus; cephalexin alone", "Staphylococcus aureus; treat with cephalexin alone")]),
"Syphilis: secondary": _o([("IV aqueous penicillin G for 14 days", "IV aqueous penicillin G given for 14 days")]),
"Syphilis: serology": _o([("Syphilis that was successfully treated in the past", "Syphilis that was successfully treated several years ago")]),
"Leptospira: Weil disease": _o([("Inhaling dust from dried bird droppings", "Inhaling dust from dried bird droppings or guano")]),
"Spirochetes: visualization": _o([("Leptospira is best seen on a Wright-stained smear", "Leptospira is best seen on a Wright-stained smear of blood")]),
"Chlamydia: neonatal pneumonia": _o([("IV ampicillin and gentamicin", "IV ampicillin combined with gentamicin")]),
"Chlamydia: trachoma": _o([("Neisseria gonorrhoeae; spread by sexual contact", "Neisseria gonorrhoeae; spread through sexual contact only")]),
"Daptomycin": _o([("It is a prodrug activated only in the heart; monitor troponin", "It is a prodrug activated only within the heart; monitor troponin")]),
"Clindamycin": _o([("Disulfiram-like reaction", "Disulfiram-like reaction with alcohol")]),
"Endotoxin": _o([("It is highly antigenic and can be converted to a toxoid vaccine", "It is highly antigenic and can be converted into a toxoid vaccine")]),
"Type III secretion": _o([("Streptococcus pneumoniae and Staphylococcus aureus", "Streptococcus pneumoniae and Staphylococcus aureus strains")]),
"Bacterial virulence: IgA protease": _o([("Clostridium perfringens and Clostridium difficile", "Clostridium perfringens and Clostridioides difficile")]),
"Spores & heat resistance": _o([("Mycolic acid in the cell envelope", "Mycolic acid within the waxy cell envelope")]),
"Catalase-positive organisms": _o([("Streptococcus pyogenes and Streptococcus pneumoniae", "Streptococcus pyogenes and Streptococcus pneumoniae only")]),
"HSV-1: latency": _o([("Oral epithelial basal cells", "Basal cells of the oral epithelium")]),
"Varicella": _o([("It is caused by a poxvirus replicating in the cytoplasm", "It is caused by a poxvirus that replicates in the cytoplasm")]),
"EBV: infectious mononucleosis": _o([("Neoplastic Reed-Sternberg cells in the blood", "Neoplastic Reed-Sternberg cells circulating in the blood")]),
"Parvovirus B19": _o([("Splenic sequestration from immune complex deposition", "Splenic sequestration from immune complex deposition in the spleen")]),
"Molluscum contagiosum": _o([("It has a circular genome that integrates into host DNA", "It has a circular genome that integrates into the host genome")]),
"Viral envelope & transmission": _o([("It has a positive-sense RNA genome", "It carries a positive-sense RNA genome")]),
"Enteroviral meningitis": _o([("Neisseria meningitidis bacterial infection", "Neisseria meningitidis causing bacterial infection")]),
"Dengue": _o([("Her first infection made her immune to every serotype", "Her first infection made her immune to every serotype of dengue")]),
"Influenza: antigenic shift": _o([("Point mutations accumulating in hemagglutinin", "Point mutations accumulating in hemagglutinin over time")]),
"Positive vs negative sense RNA": _o([("Positive-sense genomes all require reverse transcriptase", "Positive-sense genomes all require reverse transcriptase to replicate")]),
"HTLV-1": _o([("EBV, which enters B cells through CD21", "EBV, which enters B lymphocytes through CD21")]),
"HIV: genes & proteins": _o([("env codes the p24 capsid and p17 matrix proteins", "env codes the p24 capsid and p17 matrix proteins of the virion")]),
"HIV: integrase & protease inhibitors": _o([("It inhibits integrase strand transfer directly", "It directly inhibits the integrase strand transfer reaction")]),
"HIV: PrEP & PEP": _o([("Wait for the worker's HIV test to become positive", "Wait for the worker's HIV test to become positive first")]),
"HDV": _o([("Superinfection is milder than a simultaneous co-infection", "Superinfection is milder than a simultaneous co-infection would be")]),
"Paracoccidioides": _o([("Blastomyces dermatitidis", "Blastomyces dermatitidis yeast")]),
"Cryptosporidium": _o([("It is reliably killed by standard water chlorination", "It is reliably killed by standard water chlorination systems")]),
"P. falciparum: severe malaria": _o([("Hypnozoites in the liver release merozoites into CSF", "Hypnozoites in the liver release merozoites into CSF directly")]),
"Trichomonas vaginalis": _o([("Ceftriaxone combined with doxycycline", "Ceftriaxone combined with doxycycline for seven days")]),
"Naegleria fowleri": _o([("Through a contact lens injury to the cornea", "Through a contact lens-related injury to the cornea")]),
"Ascaris": _o([("Hematogenous spread of adult worms to the lungs", "Hematogenous spread of the adult worms to the lungs")]),
"Loa loa": _o([("Tsetse fly; ivermectin has no activity at all", "Tsetse fly; ivermectin has no activity at all here")]),
"Neurocysticercosis": _o([("Pyrimethamine combined with sulfadiazine", "Pyrimethamine combined with sulfadiazine and leucovorin")]),
"UTI organisms & urinalysis": _o([("Nitrite is positive only in pyelonephritis", "Nitrite turns positive only in acute pyelonephritis")]),
"Rashes on palms and soles": _o([("Varicella in children", "Varicella in young children")]),
"Epidemiology: vectors": _o([("Ixodes tick — Rocky Mountain spotted fever", "Ixodes tick — Rocky Mountain spotted fever and typhus")]),
"N. meningitidis: epidemiology": _o([("The typhoid Vi polysaccharide vaccine", "The typhoid Vi polysaccharide vaccine for travelers")]),
"Anaplasma": _o([("Amblyomma americanum, known as the lone star tick", "Amblyomma americanum, commonly called the lone star tick")]),
"HIV: pathogenesis": _o([("Peripheral blood B cells", "Peripheral blood B lymphocytes")]),
}
