from qcore import Q
T = "Gram+ Rods & Branching"
QUESTIONS = [
# ---------------- Corynebacterium diphtheriae ----------------
Q(T, "C. diphtheriae: toxin mechanism",
  "A 6-year-old unvaccinated immigrant has fever, sore throat, and marked neck swelling. The gray-white membrane on the posterior pharynx, shown, bleeds when scraped. Which mechanism explains the toxin's effect on host cells?",
  ["ADP-ribosylation of elongation factor 2, halting protein synthesis", "Cleavage of 28S rRNA of the 60S ribosomal subunit", "ADP-ribosylation of Gi, raising cAMP", "Cleavage of SNARE proteins", "Formation of pores in cholesterol-containing membranes"],
  "Diphtheria causes an adherent gray pseudomembrane of necrotic epithelium, fibrin, and leukocytes. It can obstruct the airway, and cervical lymphadenopathy gives a 'bull neck.' Diphtheria toxin is an A-B toxin: the B subunit binds heparin-binding EGF receptor, and the A subunit ADP-ribosylates EF-2, killing the cell. Pseudomonas exotoxin A works the same way. Shiga toxin cleaves 28S rRNA. Pertussis toxin ribosylates Gi. Tetanus and botulinum toxins cleave SNAREs.",
  img="diphtheria-membrane.jpg"),
Q(T, "C. diphtheriae: lysogenic conversion",
  "Only strains of Corynebacterium diphtheriae infected by a specific temperate bacteriophage can cause diphtheria. What genetic process explains this?",
  ["Lysogenic conversion: the tox gene is carried by a prophage (β-phage)", "Transformation with naked chromosomal DNA", "Conjugation of an F plasmid", "Generalized transduction during the lytic cycle", "Transposition of a chromosomal pathogenicity island"],
  "In lysogenic conversion, a temperate phage integrates as a prophage and brings new genes that the bacterium expresses. Toxins encoded this way ('ABCDE'): shigA-like toxin (Shiga-like toxin of EHEC), Botulinum toxin (some types), Cholera toxin, Diphtheria toxin, and Erythrogenic toxin of S. pyogenes."),
Q(T, "C. diphtheriae: laboratory ID",
  "A throat swab from a patient with suspected diphtheria is sent to the lab. Which finding would support the diagnosis?",
  ["Club-shaped rods with metachromatic (volutin) granules and black colonies on tellurite agar", "Boxcar-shaped rods with central spores on blood agar", "Gram-negative diplococci on Thayer-Martin agar", "Lancet-shaped diplococci with bile solubility", "Acid-fast branching filaments"],
  "C. diphtheriae is a Gram-positive club-shaped rod arranged in 'Chinese letter' (V and L) patterns, as in the image. It has polyphosphate granules that stain metachromatically with methylene blue. It forms black colonies on cystine-tellurite agar and grows on Loeffler medium. The Elek test (immunodiffusion) confirms that the strain makes toxin.",
  img="cdiphtheriae-gram.jpg"),
Q(T, "C. diphtheriae: treatment & complications",
  "A 5-year-old with pharyngeal diphtheria is admitted. Along with antibiotics, which treatment is most urgent, and which complication should be monitored for?",
  ["Equine diphtheria antitoxin; myocarditis with heart block", "IV immunoglobulin; coronary aneurysms", "Tetanus immune globulin; laryngospasm", "Corticosteroids; hemolytic uremic syndrome", "Diphtheria toxoid; rheumatic valvular disease"],
  "Antitoxin neutralizes circulating toxin that has not yet entered cells, so give it quickly without waiting for culture. Erythromycin or penicillin kills the organism and stops transmission. Toxin damage to the heart causes myocarditis and arrhythmias, often in weeks 1–2. Neuropathy, including palatal and cranial nerve palsies, comes later. Prevention is diphtheria toxoid in DTaP and Tdap, which produces antitoxin antibodies."),
# ---------------- Listeria ----------------
Q(T, "Listeria: pregnancy & neonates",
  "A 28-year-old woman at 30 weeks' gestation has flu-like fever and myalgias after eating unpasteurized soft cheese and deli meats. Two days later she delivers a preterm infant with sepsis and disseminated microabscesses. Blood cultures from the infant grow Gram-positive rods with tumbling motility at 25°C. What is the drug of choice?",
  ["Ampicillin", "Ceftriaxone", "Vancomycin", "Azithromycin", "Metronidazole"],
  "Listeria monocytogenes grows at refrigerator temperatures ('cold enrichment') and contaminates deli meats, soft cheeses, and unpasteurized dairy. It crosses the placenta, causing amnionitis, preterm delivery, and granulomatosis infantiseptica. It also causes meningitis in neonates, the elderly, and the immunosuppressed. Listeria is intrinsically resistant to cephalosporins. Treat with ampicillin, often plus gentamicin. TMP-SMX is used in penicillin allergy."),
Q(T, "Listeria: actin rockets",
  "An intracellular Gram-positive rod escapes the phagosome using a pore-forming toxin. It then polymerizes host actin at one pole to push into neighboring cells without being exposed to antibody. Which bacterial proteins mediate these two steps?",
  ["Listeriolysin O; ActA", "Streptolysin O; internalin", "Lecithinase; flagellin", "Protein A; coagulase", "IpaB; VirG"],
  "Listeria enters cells by internalin binding E-cadherin. Listeriolysin O lyses the phagosome membrane so it can reach the cytosol. ActA recruits the Arp2/3 complex to build 'actin rockets' that push into adjacent cells. Because it stays intracellular, cell-mediated immunity is essential for clearance, which explains susceptibility during pregnancy, old age, and immunosuppression. Shigella uses a similar actin-based spread (IcsA/VirG)."),
# ---------------- Bacillus anthracis ----------------
Q(T, "B. anthracis: cutaneous anthrax",
  "A 50-year-old man who imports goat hair and hides from West Africa develops a painless papule on his neck. It becomes a vesicle and then the black eschar with surrounding edema shown. Gram stain of the lesion shows large rods in chains. Which virulence factor is unique among bacteria?",
  ["A capsule made of poly-D-glutamic acid (protein)", "A polysaccharide capsule containing sialic acid", "Mycolic acid in the cell wall", "A lipooligosaccharide outer membrane", "A hyaluronic acid capsule"],
  "Cutaneous anthrax causes a painless ulcer with a black eschar and marked edema. Almost all other bacterial capsules are polysaccharide, but B. anthracis has a poly-D-glutamate (protein) capsule that is antiphagocytic. It is an aerobic, spore-forming Gram-positive rod that grows in long chains ('boxcars'). It is a hazard of wool and hide work and of bioterrorism.",
  img="anthrax-eschar.jpg"),
Q(T, "B. anthracis: toxins",
  "Anthrax toxin has three components. Protective antigen binds host receptors and forms a channel. One component raises intracellular cAMP and causes massive tissue edema. What is the mechanism of that component?",
  ["It is a calmodulin-dependent adenylyl cyclase (edema factor)", "It is a zinc metalloprotease that cleaves MAP kinase kinase (lethal factor)", "It ADP-ribosylates Gs", "It glucosylates Rho GTPases", "It is a phospholipase C that degrades lecithin"],
  "Edema factor is itself an adenylyl cyclase, activated by host calmodulin. It raises cAMP and causes edema, and impairs neutrophils. Lethal factor is a zinc protease that cleaves MAPKK, causing macrophage death and cytokine release. Protective antigen delivers both. B. pertussis also secretes an adenylate cyclase toxin, separate from pertussis toxin, which ADP-ribosylates Gi. Cholera and heat-labile toxins raise cAMP by ADP-ribosylating Gs."),
Q(T, "B. anthracis: inhalational anthrax",
  "A postal worker develops flu-like illness that progresses over 3 days to hypotension and respiratory failure. Chest radiograph shows a widened mediastinum without infiltrates. Blood cultures grow the organism shown. Which is the most appropriate initial antibiotic treatment?",
  ["Ciprofloxacin plus additional agents such as meropenem and linezolid", "Oral amoxicillin alone", "Ceftriaxone alone", "Metronidazole", "Aztreonam"],
  "Inhaled spores are carried to mediastinal lymph nodes, where they germinate and cause hemorrhagic mediastinitis (widened mediastinum), then sepsis and meningitis. Treat systemic anthrax with a fluoroquinolone (ciprofloxacin), plus a bactericidal drug and a protein synthesis inhibitor. Add anti-protective antigen antibodies (raxibacumab, obiltoxaximab). The Gram stain shows large Gram-positive rods in chains. Post-exposure prophylaxis is ciprofloxacin or doxycycline for 60 days plus vaccine.",
  img="anthrax-gram.jpg"),
Q(T, "B. cereus: reheated rice",
  "Several diners develop vomiting 2 hours after eating fried rice at a restaurant. The rice was cooked the previous day and left at room temperature. The responsible toxin (cereulide) is most similar in clinical behavior to the toxin of which organism?",
  ["Staphylococcus aureus", "Clostridium perfringens", "Vibrio cholerae", "Clostridium botulinum", "Enterotoxigenic E. coli"],
  "Bacillus cereus spores survive cooking and germinate in rice left at room temperature. The emetic form comes from preformed, heat-stable cereulide. It causes vomiting within 1–5 hours, just like S. aureus enterotoxin. A separate diarrheal form comes from heat-labile enterotoxin made in the gut (8–18 h), resembling C. perfringens."),
# ---------------- Clostridium tetani ----------------
Q(T, "C. tetani: tetanospasmin",
  "A 45-year-old farmer who has not had a booster in 25 years steps on a rusty nail. Ten days later he develops trismus, risus sardonicus, and spasms that arch his back, as shown. The toxin responsible inhibits release of which neurotransmitter, and from which cells?",
  ["Glycine and GABA from Renshaw cells and other inhibitory interneurons in the spinal cord", "Acetylcholine from α-motor neurons at the neuromuscular junction", "Dopamine from substantia nigra neurons", "Glutamate from upper motor neurons", "Norepinephrine from sympathetic postganglionic fibers"],
  "Tetanospasmin enters peripheral nerve endings and travels by retrograde axonal transport (dynein) to the spinal cord. There it cleaves synaptobrevin (VAMP) in inhibitory interneurons, blocking glycine and GABA release. The result is unopposed motor activity: spastic paralysis, lockjaw, risus sardonicus, and opisthotonus (shown in Sir Charles Bell's painting). Botulinum toxin cleaves SNAREs at the NMJ and causes flaccid paralysis.",
  img="opisthotonus.jpg"),
Q(T, "C. tetani: wound prophylaxis",
  "A 35-year-old man has a deep puncture wound contaminated with soil. He is unsure of his tetanus vaccination history. What is the most appropriate management?",
  ["Tetanus-diphtheria-pertussis toxoid (Tdap) plus human tetanus immune globulin, and wound cleaning", "Tdap alone", "Tetanus immune globulin alone", "Oral penicillin alone", "No treatment unless symptoms develop"],
  "For a dirty or major wound in a patient with unknown vaccination or fewer than 3 prior doses, give both active immunization (toxoid) and passive immunization (TIG), at different sites. TIG neutralizes free toxin, but it cannot reverse toxin already bound in neurons. Once tetanus develops, treat with TIG, metronidazole, benzodiazepines for spasms, airway support, and wound debridement. Tetanus infection itself does not confer immunity, so survivors still need vaccination."),
# ---------------- Clostridium botulinum ----------------
Q(T, "C. botulinum: infant botulism",
  "A 4-month-old girl has constipation for 3 days, then a weak cry, poor feeding, ptosis, and a symmetric descending flaccid weakness. Her parents sweetened her pacifier with honey. What is the mechanism of her illness?",
  ["Spores germinate in the gut and toxin cleaves SNARE proteins, blocking acetylcholine release at the NMJ", "Preformed toxin is absorbed and blocks glycine release in the spinal cord", "Antibodies against presynaptic voltage-gated calcium channels", "Antibodies against postsynaptic acetylcholine receptors", "Demyelination of peripheral nerves after enteric infection"],
  "In infant botulism, spores (e.g., from honey or soil) germinate in the immature infant gut and make toxin there. In adults, disease usually comes from ingesting preformed toxin in home-canned foods. Botulinum toxin cleaves SNAREs (SNAP-25, syntaxin, synaptobrevin) so ACh vesicles cannot fuse. The result is symmetric descending flaccid paralysis with cranial nerve findings first (diplopia, ptosis, dysphagia). Treat infants with human botulism immune globulin (BabyBIG) and adults with equine antitoxin."),
Q(T, "C. botulinum vs other paralyses",
  "A 40-year-old man develops blurred vision, diplopia, dysphagia, and then descending bilateral arm weakness 24 hours after eating home-canned green beans. Mental status is normal. Pupils are dilated and poorly reactive. Which feature best distinguishes this from Guillain-Barré syndrome?",
  ["Descending paralysis beginning with cranial nerves, with no sensory loss", "Ascending paralysis starting in the legs", "Elevated CSF protein with normal cell count", "Preceding Campylobacter jejuni diarrhea", "Loss of vibration sense in the feet"],
  "Botulism causes a descending paralysis that starts with cranial nerves ('4 Ds': diplopia, dysarthria, dysphagia, dysphonia). It includes anticholinergic signs such as fixed dilated pupils and dry mouth, without sensory changes or fever. Guillain-Barré is an ascending, often sensory-involved demyelinating polyneuropathy. It follows infections such as Campylobacter and shows albuminocytologic dissociation in CSF."),
# ---------------- Clostridium perfringens ----------------
Q(T, "C. perfringens: gas gangrene",
  "A 32-year-old man has severe pain, swelling, bronze-to-purple discoloration, hemorrhagic bullae, and crepitus in his thigh 2 days after a crush injury with a contaminated open fracture, as shown. Which toxin is chiefly responsible for the tissue destruction?",
  ["α-toxin, a lecithinase (phospholipase C)", "Tetanospasmin", "Exfoliative toxin", "Toxin B, a glucosyltransferase", "Pyrogenic exotoxin A"],
  "Clostridial myonecrosis (gas gangrene) follows deep, contaminated, devitalized wounds. C. perfringens α-toxin is a phospholipase C (lecithinase) that breaks down cell membranes. It causes myonecrosis, hemolysis, and gas in tissues (crepitus). Treatment is emergent surgical debridement plus high-dose penicillin and clindamycin. Hyperbaric oxygen is sometimes added.",
  img="gas-gangrene.jpg"),
Q(T, "C. perfringens: lab features",
  "A Gram stain from a necrotic wound shows the organisms pictured: large, boxcar-shaped Gram-positive rods with few neutrophils. The isolate grows only anaerobically and shows a double zone of hemolysis on blood agar. What is the organism?",
  ["Clostridium perfringens", "Bacillus anthracis", "Clostridium tetani", "Listeria monocytogenes", "Actinomyces israelii"],
  "C. perfringens is a large, rectangular Gram-positive rod that rarely shows spores in tissue. It produces a characteristic double zone of β-hemolysis: a narrow complete zone from θ-toxin and a wider incomplete zone from α-toxin. Lecithinase activity appears as opacity on egg-yolk agar (Nagler reaction). Few neutrophils are seen because the toxins destroy them. B. anthracis is also a large boxcar rod but is aerobic.",
  img="cperf-gram.jpg"),
Q(T, "C. perfringens: food poisoning",
  "About 12 hours after a buffet dinner of slow-cooled beef stew and gravy, many attendees develop watery diarrhea and cramps without vomiting or fever. Symptoms resolve within 24 hours. What is the most likely mechanism?",
  ["Spores survive cooking, germinate as food cools slowly, and enterotoxin is released in the gut during sporulation", "Preformed heat-stable enterotoxin acts on the vagus nerve", "Invasion of M cells in Peyer patches", "Toxin-mediated ADP-ribosylation of Gi in enterocytes", "Adherence and effacement of microvilli"],
  "C. perfringens type A food poisoning comes from reheated or slowly cooled meats and gravies. Large numbers of vegetative cells are eaten, then sporulate in the intestine and release a heat-labile enterotoxin that disrupts tight junctions. Incubation is 8–16 hours, with watery diarrhea and cramps. Type C strains (β-toxin) cause necrotizing enteritis ('pigbel')."),
# ---------------- Clostridioides difficile ----------------
Q(T, "C. difficile: pathogenesis",
  "A 72-year-old woman develops profuse watery diarrhea, fever, and leukocytosis 1 week after starting clindamycin for a dental abscess. Colectomy specimen findings are shown. What is the mechanism of the principal toxins?",
  ["Glucosylation of Rho-family GTPases, disrupting the actin cytoskeleton", "ADP-ribosylation of Gs, raising cAMP", "Cleavage of the 28S rRNA of the 60S subunit", "Formation of pores that lyse neutrophils", "Increase in cGMP through guanylyl cyclase activation"],
  "The colon shows yellow-white pseudomembranes (plaques of fibrin, mucus, and inflammatory debris): pseudomembranous colitis. C. difficile toxin A (enterotoxin) and toxin B (cytotoxin) glucosylate and inactivate Rho, Rac, and Cdc42. This breaks down the cytoskeleton and tight junctions, killing colonocytes. Binary toxin appears in hypervirulent strains such as ribotype 027. ETEC heat-stable toxin increases cGMP.",
  img="pmc.jpg"),
Q(T, "C. difficile: risk & diagnosis",
  "A hospitalized patient has had 4 loose stools per day since receiving antibiotics. Which statement about C. difficile infection is correct?",
  ["Diagnosis requires detecting toxin or toxin genes in unformed stool; test only symptomatic patients", "Stool culture for spores is the preferred diagnostic test", "Proton pump inhibitors lower the risk of infection", "Alcohol-based hand sanitizer reliably kills the spores", "Only clindamycin is associated with this infection"],
  "Test for C. difficile with PCR for toxin genes, or with GDH antigen plus toxin EIA, and only on diarrheal stool, because asymptomatic colonization is common. Risk factors: antibiotics (clindamycin, fluoroquinolones, cephalosporins, carbapenems), age, hospitalization, and PPIs. Spores resist alcohol, so contact precautions and soap-and-water handwashing are needed. Bleach-based cleaners disinfect surfaces."),
Q(T, "C. difficile: treatment",
  "A 60-year-old man has his first episode of non-severe C. difficile colitis. Which treatment is recommended?",
  ["Oral fidaxomicin (or oral vancomycin)", "IV vancomycin", "Oral metronidazole plus IV clindamycin", "Loperamide", "IV ceftriaxone"],
  "First-line treatment for an initial episode is oral fidaxomicin (a macrolide-like RNA polymerase inhibitor with lower relapse rates) or oral vancomycin. IV vancomycin does not reach the colonic lumen. Metronidazole is now reserved for when those drugs are unavailable. Fulminant disease is treated with oral vancomycin plus IV metronidazole, and sometimes colectomy. Multiple recurrences are treated with fecal microbiota transplant. Bezlotoxumab (anti–toxin B antibody) reduces recurrence."),
# ---------------- Actinomyces ----------------
Q(T, "Actinomyces: sulfur granules",
  "A 45-year-old man with poor dentition develops a firm, slowly enlarging mass at the angle of his jaw that drains through multiple sinus tracts. The yellow grains in the drainage are examined histologically, as shown. The organism is a Gram-positive, branching, non–acid-fast anaerobe. What is the treatment of choice?",
  ["Penicillin", "Trimethoprim-sulfamethoxazole", "Amphotericin B", "Isoniazid, rifampin, pyrazinamide, ethambutol", "Fluconazole"],
  "Actinomyces israelii is normal oral flora. After dental work or trauma it causes cervicofacial 'lumpy jaw' abscesses with sinus tracts that cross tissue planes. Pus contains yellow 'sulfur granules,' which are masses of filaments with a club-shaped rim, as shown. It can also cause pelvic actinomycosis with IUDs. Treat with penicillin and drainage. Mnemonic SNAP: Sulfonamides for Nocardia, Actinomyces gets Penicillin.",
  img="actinomyces.jpg"),
# ---------------- Nocardia ----------------
Q(T, "Nocardia: lung & brain",
  "A 55-year-old kidney transplant recipient on tacrolimus and prednisone has a cavitating lung nodule and new seizures. MRI shows a ring-enhancing brain lesion. Sputum shows the organism pictured: weakly acid-fast (modified Kinyoun), branching, beaded filaments. The organism is an aerobe found in soil. What is the treatment?",
  ["Trimethoprim-sulfamethoxazole", "Penicillin G", "Isoniazid monotherapy", "Metronidazole", "Doxycycline"],
  "Nocardia (N. asteroides complex) is an aerobic, weakly acid-fast, branching Gram-positive filament from soil. In immunocompromised hosts it causes pneumonia that can mimic TB, and it spreads to the brain (abscess) and skin. It is catalase-positive. Treat with TMP-SMX, often combined with imipenem or amikacin for severe or CNS disease. Actinomyces, in contrast, is anaerobic, non–acid-fast, and treated with penicillin.",
  img="nocardia.jpg"),
Q(T, "Spore formers: sterilization",
  "An operating room instrument is contaminated with Clostridium and Bacillus spores. Which method reliably destroys the spores?",
  ["Autoclaving with steam at 121°C under pressure", "70% isopropyl alcohol wipe", "Boiling at 100°C for 5 minutes", "Chlorhexidine hand scrub", "Quaternary ammonium compounds"],
  "Endospores have a keratin-like coat, dipicolinic acid, and calcium in the core. They resist heat, drying, and most disinfectants. Autoclaving (121°C for about 15 min at 15 psi) is sporicidal. Alcohol, chlorhexidine, and quaternary ammonium compounds do not kill spores. Spore-forming Gram-positive rods: Bacillus anthracis, B. cereus, Clostridium species, and C. difficile. Coxiella also forms a spore-like form."),
]
