from qcore import Q
T = "Gram− Cocci & Respiratory Rods"
QUESTIONS = [
# ---------------- Neisseria meningitidis ----------------
Q(T, "N. meningitidis: identification",
  "An 18-year-old college freshman living in a dormitory has sudden fever, headache, neck stiffness, and a petechial rash on his legs. A Gram stain of his CSF is shown. The organism grows on chocolate agar and is oxidase-positive. Which carbohydrate fermentation pattern identifies it?",
  ["Ferments both glucose and maltose", "Ferments glucose only", "Ferments lactose rapidly", "Ferments neither glucose nor maltose", "Ferments sucrose only"],
  "The CSF shows neutrophils with Gram-negative diplococci. Fever, meningismus, and petechiae in a young adult living in close quarters point to N. meningitidis. Meningococci ferment Maltose and glucose ('MeninGococci'). Gonococci ferment Glucose only ('GonoCoccus'). Both are oxidase-positive, and meningococcus has a polysaccharide capsule, while gonococcus does not.",
  img="nmen-csf.webp"),
Q(T, "N. meningitidis: Waterhouse-Friderichsen",
  "A 16-year-old girl dies within 12 hours of developing fever, purpura fulminans, and refractory shock. The autopsy findings in her adrenal glands are shown. Which bacterial component mainly drives this outcome?",
  ["Lipooligosaccharide (endotoxin) released in large amounts during bacteremia", "An A-B exotoxin that ADP-ribosylates EF-2", "A superantigen that binds MHC class II", "A protein capsule of poly-D-glutamate", "IgA1 protease"],
  "The adrenals show bilateral hemorrhagic necrosis: Waterhouse-Friderichsen syndrome. It results from meningococcemia with DIC and shock. Meningococci shed large amounts of lipooligosaccharide (LOS) in outer membrane blebs. LOS activates TLR4/MD-2, triggering massive TNF, IL-1, and IL-6 release, DIC, and vascular collapse. Adrenal hemorrhage causes acute adrenal insufficiency.",
  img="wfs-adrenal.webp"),
Q(T, "N. meningitidis: complement deficiency",
  "A 22-year-old man has his second episode of meningococcal meningitis. Other infections have been uncommon. Which laboratory abnormality is most likely?",
  ["Low total hemolytic complement (CH50) from a deficiency of C5–C9", "Absent B cells on flow cytometry", "Abnormal dihydrorhodamine flow test", "Low serum IgA with normal IgG", "Deficiency of C1 esterase inhibitor"],
  "Terminal complement components (C5–C9) form the membrane attack complex, which is especially important for killing Neisseria. Deficiency causes recurrent Neisseria bacteremia and meningitis, screened with a low CH50. Eculizumab and ravulizumab (anti-C5) cause the same susceptibility, so patients need meningococcal vaccination before starting them. C1-INH deficiency causes hereditary angioedema."),
Q(T, "N. meningitidis: chemoprophylaxis",
  "A college student is hospitalized with meningococcal meningitis. Her roommate is healthy. Which drug is appropriate post-exposure prophylaxis for the roommate?",
  ["Rifampin, ciprofloxacin, or a single dose of ceftriaxone", "Oral penicillin V", "Azithromycin", "Vancomycin", "No prophylaxis unless symptoms develop"],
  "Close contacts of meningococcal disease (household, roommates, daycare, anyone exposed to oral secretions) should receive prophylaxis within 24 hours. Options: rifampin, ciprofloxacin, or ceftriaxone. Ceftriaxone is preferred in pregnancy. These drugs eradicate nasopharyngeal carriage. Rifampin is also used for H. influenzae type b contacts. Rifampin turns body fluids orange."),
Q(T, "N. meningitidis: vaccines",
  "A 16-year-old receives the routine adolescent meningococcal vaccine. The MenACWY vaccine contains conjugated capsular polysaccharide, but serogroup B vaccines are made from surface proteins. Why?",
  ["The serogroup B capsule (polysialic acid) resembles human neural cell adhesion molecules and is poorly immunogenic", "Serogroup B lacks a capsule", "Serogroup B only infects infants", "Serogroup B capsule is identical to H. influenzae type b", "Serogroup B undergoes phase variation of its capsule every generation"],
  "The serogroup B capsule is α2-8–linked polysialic acid, the same structure found on human NCAM in fetal brain. It is poorly immunogenic, and there is concern about autoimmunity. MenB vaccines therefore use outer membrane proteins, such as factor H–binding protein. MenACWY is given at 11–12 years with a booster at 16, and to asplenic and complement-deficient patients."),
# ---------------- Neisseria gonorrhoeae ----------------
Q(T, "N. gonorrhoeae: urethritis & treatment",
  "A 24-year-old man has dysuria and purulent urethral discharge 3 days after unprotected intercourse. The Gram stain of the discharge is depicted. What is the recommended treatment?",
  ["Ceftriaxone 500 mg IM once, plus doxycycline if chlamydia is not excluded", "Oral penicillin V for 10 days", "Azithromycin alone", "Metronidazole 2 g once", "Ciprofloxacin alone"],
  "Intracellular Gram-negative diplococci inside neutrophils in urethral discharge diagnose gonorrhea in men. Treat with single-dose IM ceftriaxone. Widespread resistance rules out penicillin and fluoroquinolones. Co-infection with Chlamydia is common, so doxycycline for 7 days is added unless chlamydia NAAT is negative. Partners should be treated, and patients are tested for other STIs.",
  img="gc-gram.webp"),
Q(T, "N. gonorrhoeae: antigenic variation",
  "A 22-year-old woman has her third episode of gonococcal cervicitis in 2 years, each time from a new infection. Why hasn't prior infection protected her, and why is there no vaccine?",
  ["Pilin undergoes antigenic variation by gene conversion, and Opa proteins undergo phase variation", "The organism is an obligate intracellular pathogen hidden from antibodies", "It has a polysaccharide capsule that is poorly immunogenic", "It produces a superantigen that deletes memory T cells", "It lacks surface proteins"],
  "Gonococcal pili attach to mucosal epithelium. The pilE gene recombines with silent pilS copies (gene conversion), producing endless antigenic variants. Opa proteins switch on and off (phase variation). This lets gonococci avoid antibody responses, allows repeated reinfection, and has prevented vaccine development. Gonococci also make IgA protease and LOS."),
Q(T, "N. gonorrhoeae: ophthalmia neonatorum",
  "A 3-day-old infant has bilateral eyelid swelling with copious purulent discharge, as shown. The mother had no prenatal care. What is the most likely organism, and what prevents this?",
  ["Neisseria gonorrhoeae; erythromycin eye ointment at birth", "Chlamydia trachomatis; oral erythromycin at birth", "Staphylococcus aureus; chlorhexidine bathing", "Herpes simplex virus; IV acyclovir at birth", "Pseudomonas aeruginosa; topical gentamicin"],
  "Gonococcal ophthalmia neonatorum appears 2–5 days after birth with hyperacute purulent conjunctivitis. It can perforate the cornea. Universal erythromycin ointment prophylaxis prevents it. Treat with a single dose of ceftriaxone (cefotaxime if hyperbilirubinemic). Chlamydial conjunctivitis appears later (5–14 days), is less purulent, and is not prevented by eye ointment. It is treated with oral erythromycin.",
  img="ophthalmia.webp"),
Q(T, "N. gonorrhoeae: disseminated infection",
  "A 20-year-old sexually active woman has fever, migratory polyarthralgias, tenosynovitis of the wrist extensors, and a few pustules on her hands. Which is the most likely diagnosis?",
  ["Disseminated gonococcal infection", "Reactive arthritis after Chlamydia", "Acute rheumatic fever", "Lyme arthritis", "Staphylococcal septic arthritis"],
  "Disseminated gonococcal infection presents either as the triad of tenosynovitis, dermatitis (a few pustules on the extremities), and polyarthralgia, or as purulent monoarthritis, often of the knee. It is the most common cause of septic arthritis in sexually active young adults. Joint cultures are often negative, so NAAT the genital, rectal, and pharyngeal sites. Treat with IV ceftriaxone."),
Q(T, "Neisseria: selective media",
  "A cervical swab is plated on Thayer-Martin agar to isolate N. gonorrhoeae from normal flora. Thayer-Martin is chocolate agar with vancomycin, colistin (polymyxin), nystatin, and trimethoprim. What does each additive inhibit?",
  ["Vancomycin: Gram-positives; colistin: other Gram-negatives; nystatin: fungi; trimethoprim: Proteus", "Vancomycin: fungi; colistin: Gram-positives; nystatin: protozoa; trimethoprim: anaerobes", "Vancomycin: Neisseria commensals; colistin: yeasts; nystatin: Gram-negatives; trimethoprim: streptococci", "All additives inhibit anaerobes only", "All additives inhibit Gram-negative rods only"],
  "Thayer-Martin (VPN + trimethoprim) is a selective medium. Vancomycin kills Gram-positives, colistin/polymyxin kills most Gram-negatives except Neisseria, nystatin kills fungi, and trimethoprim inhibits swarming Proteus. Today, NAAT of urine or genital swabs is the standard diagnostic test."),
# ---------------- Moraxella ----------------
Q(T, "Moraxella catarrhalis",
  "A child with otitis media fails high-dose amoxicillin. Middle ear fluid grows Gram-negative diplococci that are oxidase-positive and do not ferment carbohydrates. What change in therapy is most appropriate?",
  ["Amoxicillin-clavulanate, because most strains produce β-lactamase", "Vancomycin, because of altered PBPs", "Azithromycin, because the organism lacks a cell wall", "Doxycycline, because it is intracellular", "Metronidazole, because it is anaerobic"],
  "Moraxella catarrhalis is a Gram-negative diplococcus that causes otitis media, sinusitis, and COPD exacerbations. Nearly all strains produce β-lactamase, so amoxicillin-clavulanate is appropriate after amoxicillin failure. Nontypeable H. influenzae also often makes β-lactamase."),
# ---------------- Haemophilus influenzae ----------------
Q(T, "H. influenzae type b: epiglottitis",
  "A 3-year-old unvaccinated child has high fever, drooling, muffled voice, and sits leaning forward. The lateral neck radiograph is shown. Which bacterial structure is the main virulence factor and the target of the vaccine that would have prevented this?",
  ["Polyribosylribitol phosphate (PRP) capsule", "Lipooligosaccharide", "IgA protease", "Pili", "Outer membrane protein P6"],
  "The 'thumb sign' (swollen epiglottis) on lateral radiograph indicates acute epiglottitis. In unvaccinated children, it is classically caused by H. influenzae type b. The type b capsule, polyribosylribitol phosphate (PRP), is antiphagocytic and the key virulence factor. The Hib vaccine conjugates PRP to a protein carrier (e.g., tetanus toxoid) to produce a T-cell–dependent response in infants. Do not examine the throat, and secure the airway first.",
  img="epiglottitis.webp"),
Q(T, "H. influenzae: growth factors",
  "A sputum Gram stain shows small, pleomorphic Gram-negative coccobacilli, as shown. The organism grows on chocolate agar but not on sheep blood agar. On blood agar it grows only as tiny satellite colonies around S. aureus. Why?",
  ["It requires hemin (factor X) and NAD+ (factor V); S. aureus hemolyzes RBCs and releases NAD", "It requires cysteine and iron, supplied by S. aureus", "It requires 10% CO2 produced by S. aureus", "S. aureus secretes β-lactamase that protects it from penicillin in the agar", "It requires cholesterol released from lysed staphylococci"],
  "H. influenzae needs both factor X (hematin) and factor V (NAD+). Chocolate agar (heated blood) releases both. Sheep blood agar has factor X locked inside intact RBCs and has NADases that destroy factor V. β-hemolytic S. aureus lyses RBCs and secretes NAD, so H. influenzae 'satellites' around it. Legionella, in contrast, needs cysteine and iron on buffered charcoal yeast extract.",
  img="hflu-gram.webp"),
Q(T, "H. influenzae: nontypeable disease",
  "Since widespread Hib vaccination, which of the following remains a common infection caused by H. influenzae?",
  ["Otitis media and COPD exacerbations caused by nontypeable (unencapsulated) strains", "Epiglottitis caused by type b", "Meningitis in infants caused by type b", "Septic arthritis in young children caused by type b", "Waterhouse-Friderichsen syndrome"],
  "Hib vaccine protects only against encapsulated type b, which caused invasive disease (meningitis, epiglottitis, septic arthritis, bacteremia). Nontypeable strains have no capsule and are not covered. They still cause mucosal infections: otitis media ('MOPS'), sinusitis, conjunctivitis, bronchitis, and COPD exacerbations. Treat mucosal infections with amoxicillin ± clavulanate and invasive disease with ceftriaxone."),
# ---------------- Bordetella pertussis ----------------
Q(T, "B. pertussis: toxin mechanism",
  "A 4-month-old has paroxysms of coughing followed by an inspiratory 'whoop' and post-tussive vomiting after 2 weeks of mild rhinorrhea. CBC shows marked lymphocytosis (WBC 32,000/μL, 80% lymphocytes). What is the mechanism of the main toxin?",
  ["ADP-ribosylation of Gi, preventing inhibition of adenylyl cyclase", "ADP-ribosylation of Gs, locking it in the active state", "Glucosylation of Rho GTPases", "Cleavage of SNARE proteins", "Activation of guanylyl cyclase"],
  "Pertussis toxin ADP-ribosylates the inhibitory Gi protein, so adenylyl cyclase is no longer inhibited and cAMP rises. It also blocks lymphocyte homing to lymph nodes, causing lymphocytosis, and impairs phagocyte function. B. pertussis also makes adenylate cyclase toxin, tracheal cytotoxin (kills ciliated cells), and filamentous hemagglutinin. The disease has catarrhal, paroxysmal, and convalescent stages. Infants are at highest risk of apnea and death."),
Q(T, "B. pertussis: treatment & prevention",
  "A 16-year-old has had 3 weeks of paroxysmal coughing. Nasopharyngeal PCR is positive for Bordetella pertussis. His 2-month-old sister lives with him. Which management is most appropriate?",
  ["Azithromycin for the patient and prophylactic azithromycin for all household contacts", "Amoxicillin for the patient only", "No antibiotics because the paroxysmal stage has begun", "Oseltamivir for the patient and sister", "Pertussis immune globulin for the sister"],
  "Macrolides (azithromycin; TMP-SMX if allergic) given during the paroxysmal stage do not shorten the cough, which is toxin-mediated. They do eliminate carriage and reduce transmission. All household contacts get prophylaxis, especially infants. Waning immunity from acellular vaccines lets adolescents and adults act as reservoirs. Tdap is recommended at ages 11–12 and during every pregnancy (27–36 weeks) to protect newborns through maternal IgG."),
# ---------------- Legionella ----------------
Q(T, "Legionella: clinical",
  "A 64-year-old smoker has high fever, nonproductive cough, confusion, watery diarrhea, and a serum sodium of 128 mEq/L. He recently stayed at a hotel with a large air-conditioning cooling tower. Sputum Gram stain shows many neutrophils but no organisms. Which test is best for rapid diagnosis?",
  ["Urine antigen test", "Cold agglutinin titer", "Sputum culture on sheep blood agar", "India ink stain", "Acid-fast stain"],
  "Legionnaires' disease is an atypical pneumonia with high fever, GI symptoms, confusion, hyponatremia, and elevated LFTs. It is acquired by inhaling aerosols from contaminated water (cooling towers, hot tubs, showers), not by person-to-person spread. Legionella stains poorly with Gram stain and needs silver stain. It grows on buffered charcoal yeast extract with cysteine and iron. The urine antigen detects serogroup 1, the most common cause."),
Q(T, "Legionella: intracellular pathogen & treatment",
  "Legionella pneumophila survives within alveolar macrophages by blocking phagosome-lysosome fusion. Which antibiotic is appropriate for Legionnaires' disease?",
  ["Levofloxacin or azithromycin", "Ceftriaxone alone", "Ampicillin", "Vancomycin", "Aztreonam"],
  "Legionella uses a type IV secretion system (Dot/Icm) to create a replicative vacuole in macrophages and amoebae. The drug must reach inside cells: a respiratory fluoroquinolone (levofloxacin) or a macrolide (azithromycin) is used. β-lactams do not reach intracellular organisms well. Pontiac fever is a milder, self-limited flu-like illness from the same organism."),
# ---------------- Pseudomonas aeruginosa ----------------
Q(T, "Pseudomonas: identification",
  "A 12-year-old boy with cystic fibrosis has worsening cough and sputum. Sputum grows a non–lactose-fermenting, oxidase-positive Gram-negative rod with a grape-like odor. It produces the water-soluble blue-green pigment shown in the left tube. Which bacterial product causes the pigment and contributes to tissue damage?",
  ["Pyocyanin, which generates reactive oxygen species", "Staphyloxanthin, a carotenoid antioxidant", "Prodigiosin", "Melanin", "Pyoverdine alone, a siderophore"],
  "P. aeruginosa is an aerobic, non–lactose-fermenting, oxidase-positive Gram-negative rod. It smells grape-like (aminoacetophenone) and makes pyocyanin (blue-green) and pyoverdine (yellow-green, fluorescent siderophore). Pyocyanin redox-cycles to produce superoxide and H2O2, damaging tissue. In CF, mucoid (alginate-producing) strains form biofilms in the airways. Serratia makes red prodigiosin.",
  img="pseudomonas-pigment.webp"),
Q(T, "Pseudomonas: exotoxin A",
  "A patient with extensive burns develops a green-tinged wound infection and sepsis. The organism secretes a toxin that inhibits host protein synthesis by the same mechanism as diphtheria toxin. What does the toxin do?",
  ["ADP-ribosylates elongation factor 2", "Cleaves 28S rRNA", "ADP-ribosylates Gs", "Binds 30S ribosomal subunit", "Inhibits peptidyl transferase"],
  "P. aeruginosa exotoxin A ADP-ribosylates EF-2 (like diphtheria toxin), causing tissue necrosis. Other virulence factors include phospholipase C, elastase, a type III secretion system (ExoS, ExoU), LPS, and alginate. Burn wounds, ventilator-associated pneumonia, catheters, and neutropenia are classic settings."),
Q(T, "Pseudomonas: clinical syndromes",
  "Which of the following is most characteristic of Pseudomonas aeruginosa infection?",
  ["Osteomyelitis after a nail puncture through a sneaker sole", "Painless black eschar after handling wool", "Lymphocutaneous nodules after a rose-thorn prick", "Bull's-eye rash after a tick bite", "Bullous impetigo in a neonate"],
  "Pseudomonas thrives in moist environments. Its classic infections: nail-puncture osteomyelitis through sneakers, hot tub folliculitis, malignant (necrotizing) otitis externa in diabetics, swimmer's ear, ventilator-associated pneumonia, burn wound infection, CF lung infection, UTI with catheters, contact lens keratitis, and ecthyma gangrenosum in neutropenic patients (necrotic skin lesions from vascular invasion)."),
Q(T, "Pseudomonas: antibiotics",
  "A 58-year-old on mechanical ventilation for 6 days develops ventilator-associated pneumonia with Pseudomonas aeruginosa. Which antibiotic would be inactive against this organism?",
  ["Ertapenem", "Piperacillin-tazobactam", "Cefepime", "Meropenem", "Aztreonam"],
  "Antipseudomonal drugs: extended-spectrum penicillins (piperacillin-tazobactam), cephalosporins (ceftazidime, cefepime, ceftolozane-tazobactam), carbapenems (imipenem, meropenem, but not ertapenem), aztreonam, fluoroquinolones (ciprofloxacin, levofloxacin), aminoglycosides, and polymyxins/colistin. Ertapenem lacks reliable activity against Pseudomonas and Acinetobacter. Pseudomonas quickly develops resistance through efflux, porin loss (OprD, carbapenems), and β-lactamases."),
Q(T, "Pseudomonas: hot tub folliculitis",
  "Two days after using a poorly chlorinated hot tub at a hotel, a 30-year-old woman develops itchy red papules and pustules on her trunk and buttocks in areas covered by her swimsuit. Which organism is most likely?",
  ["Pseudomonas aeruginosa", "Staphylococcus aureus", "Malassezia furfur", "Legionella pneumophila", "Mycobacterium marinum"],
  "Hot tub folliculitis is a self-limited Pseudomonas infection of hair follicles. It clusters under swimsuit areas where water sits against the skin, 1–2 days after exposure. It usually resolves without treatment. Legionella from hot tubs causes pneumonia (and Pontiac fever), not folliculitis. M. marinum causes 'fish tank granuloma' on the hands."),
Q(T, "Pseudomonas: ecthyma gangrenosum",
  "A 45-year-old woman with acute myeloid leukemia has an absolute neutrophil count of 100/μL after chemotherapy. She develops fever and a painless skin lesion that becomes a necrotic ulcer with a black center and red halo. Biopsy shows Gram-negative rods invading dermal vessel walls. What is the organism?",
  ["Pseudomonas aeruginosa", "Bacillus anthracis", "Rickettsia rickettsii", "Streptococcus pyogenes", "Neisseria meningitidis"],
  "Ecthyma gangrenosum is a necrotic skin lesion of Pseudomonas bacteremia in neutropenic patients. Organisms invade vessel walls and cause thrombosis and necrosis. Febrile neutropenia needs immediate empiric antipseudomonal β-lactam therapy (cefepime, piperacillin-tazobactam, or meropenem)."),
]
