from qcore import Q
T = "Enteric Gram− Rods"
QUESTIONS = [
# ---------------- E. coli ----------------
Q(T, "E. coli: UTI & culture",
  "A 26-year-old woman has fever, flank pain, and costovertebral angle tenderness. Urine culture on eosin-methylene blue agar grows the colonies shown, which have a green metallic sheen. The strain has a specific adhesin that lets it ascend to the kidney. Which virulence factor is it?",
  ["P fimbriae binding the Gal-Gal (P blood group) antigen on uroepithelium", "K1 capsule", "Shiga-like toxin", "Heat-stable enterotoxin", "Intimin with the translocated intimin receptor (Tir)"],
  "A green metallic sheen on EMB agar is characteristic of E. coli, which ferments lactose vigorously. Uropathogenic E. coli (UPEC) is the leading cause of UTI and pyelonephritis. Type 1 fimbriae bind mannose on bladder epithelium (cystitis). P fimbriae (pap genes) bind Gal-Gal residues on kidney epithelium and are linked to pyelonephritis. K1 capsule causes neonatal meningitis. Intimin/Tir is EPEC and EHEC.",
  img="ecoli-emb.jpg"),
Q(T, "E. coli: ETEC",
  "A student traveling in Mexico develops profuse watery, non-bloody diarrhea and cramps. The most common cause of traveler's diarrhea makes two toxins. What does the heat-labile toxin do?",
  ["ADP-ribosylates Gs, raising cAMP", "Activates guanylyl cyclase, raising cGMP", "Cleaves 28S rRNA", "Causes attaching-and-effacing lesions", "Disrupts tight junctions by glucosylating Rho"],
  "Enterotoxigenic E. coli (ETEC) makes heat-labile toxin (LT), which acts like cholera toxin: it ADP-ribosylates Gs, raises cAMP, and drives CFTR chloride secretion. Heat-stable toxin (ST) activates guanylyl cyclase C and raises cGMP. Neither is invasive, so there is no blood or inflammation. Treatment is fluids, and severe cases may get azithromycin or rifaximin. Mnemonic: 'Labile in the Air (cAMP), Stable on the Ground (cGMP).'"),
Q(T, "E. coli: EHEC & HUS",
  "A 5-year-old develops bloody diarrhea after eating an undercooked hamburger at a fair. Five days later he is pale, with petechiae and decreased urine output. Labs show hemoglobin 7 g/dL with schistocytes, platelets 40,000/μL, and creatinine 3.1 mg/dL. The causative strain does not ferment sorbitol. What is the mechanism of its main toxin?",
  ["Cleavage of an adenine from 28S rRNA of the 60S ribosomal subunit", "ADP-ribosylation of EF-2", "ADP-ribosylation of Gs", "Activation of guanylyl cyclase", "Pore formation in RBC membranes"],
  "E. coli O157:H7 (EHEC) makes Shiga-like toxin, a phage-encoded AB5 toxin. It removes an adenine from 28S rRNA, halting protein synthesis. The toxin damages glomerular endothelium, causing hemolytic uremic syndrome: microangiopathic hemolytic anemia, thrombocytopenia, and acute kidney injury. EHEC does not ferment sorbitol, unlike most E. coli. It is non-invasive, so fever is often absent. Antibiotics may increase toxin release and HUS risk, so treatment is supportive."),
Q(T, "E. coli: EIEC vs EPEC",
  "Which E. coli pathotype causes non-bloody diarrhea in infants in resource-limited settings by attaching to enterocytes and destroying microvilli with pedestal formation, without producing toxin?",
  ["Enteropathogenic E. coli (EPEC)", "Enteroinvasive E. coli (EIEC)", "Enterotoxigenic E. coli (ETEC)", "Enterohemorrhagic E. coli (EHEC)", "Uropathogenic E. coli (UPEC)"],
  "EPEC attaches via bundle-forming pili and intimin, injecting its own receptor (Tir) through a type III secretion system. This causes attaching-and-effacing lesions with actin pedestals. The result is malabsorption and watery diarrhea in children ('P for Pediatrics'). EIEC invades colonic mucosa like Shigella and causes dysentery. EHEC also forms A/E lesions but adds Shiga-like toxin."),
Q(T, "E. coli: neonatal meningitis",
  "A 5-day-old infant develops fever, lethargy, and a bulging fontanelle. CSF grows a lactose-fermenting Gram-negative rod. Which virulence factor is most associated with this organism's ability to cause meningitis?",
  ["K1 capsular antigen", "P fimbriae", "Heat-labile toxin", "Type III secretion of Tir", "Vi antigen"],
  "The three leading causes of neonatal meningitis are group B strep, E. coli, and Listeria. Most E. coli meningitis strains carry the K1 capsule, a polysialic acid capsule (similar to meningococcus serogroup B) that resists phagocytosis and complement. Empiric neonatal therapy is ampicillin plus gentamicin or cefotaxime (ceftazidime/cefepime in some protocols)."),
# ---------------- Klebsiella ----------------
Q(T, "Klebsiella: aspiration pneumonia",
  "A 58-year-old man with alcohol use disorder has fever and a cough producing thick, bloody 'currant-jelly' sputum. CXR shows right upper lobe consolidation with a bulging fissure. Sputum culture on MacConkey agar grows the mucoid pink colonies shown. Which feature of the organism gives this colony appearance?",
  ["A large polysaccharide capsule", "Swarming motility from peritrichous flagella", "Hydrogen sulfide production", "Pyoverdine pigment", "A poly-D-glutamate capsule"],
  "Klebsiella pneumoniae is a non-motile, lactose-fermenting Gram-negative rod with a thick polysaccharide capsule. This makes large, mucoid pink colonies on MacConkey agar. It causes aspiration pneumonia in alcoholics and diabetics (currant-jelly sputum, upper lobes, abscess formation), UTIs, and liver abscesses (hypervirulent strains). Klebsiella is also urease-positive. Mnemonic '4 A's': Aspiration pneumonia, Abscess in lungs and liver, Alcohol use disorder, di-A-betes.",
  img="kleb-mucoid.jpg"),
Q(T, "Klebsiella: carbapenem resistance",
  "An ICU patient has bacteremia with Klebsiella pneumoniae resistant to all penicillins, cephalosporins, and meropenem. Which enzyme is most likely responsible, and which drug remains active?",
  ["KPC carbapenemase; ceftazidime-avibactam", "Extended-spectrum β-lactamase; cefepime", "PBP2a; ceftaroline", "AmpC β-lactamase; ceftriaxone", "Altered D-Ala-D-Lac; daptomycin"],
  "Klebsiella pneumoniae carbapenemase (KPC) is a plasmid-encoded class A enzyme that hydrolyzes carbapenems. Newer β-lactamase inhibitors such as avibactam, vaborbactam, and relebactam inhibit KPC. Metallo-β-lactamases (NDM) are not inhibited by avibactam and may need aztreonam-avibactam or cefiderocol. ESBL producers are treated with carbapenems."),
# ---------------- Proteus ----------------
Q(T, "Proteus: struvite stones",
  "A 60-year-old woman with recurrent UTIs has a large staghorn calculus in her renal pelvis. Urine pH is 8.0. The urine culture grows a non–lactose-fermenting Gram-negative rod that swarms across blood agar, as shown. Which enzyme is responsible for the stone?",
  ["Urease", "Catalase", "Coagulase", "β-lactamase", "Lecithinase"],
  "Proteus mirabilis is highly motile and swarms in waves on agar. Its urease splits urea into ammonia and CO2, alkalinizing the urine. Magnesium ammonium phosphate (struvite) precipitates and forms staghorn calculi, which can harbor bacteria. Other urease-positive organisms: Klebsiella, S. saprophyticus, H. pylori, Nocardia, Cryptococcus, Ureaplasma ('CHuNKS PUNCH').",
  img="proteus-swarm.jpg"),
# ---------------- Salmonella ----------------
Q(T, "Salmonella Typhi: typhoid fever",
  "A 28-year-old man returns from Bangladesh with 10 days of step-wise rising fever, headache, and abdominal pain with constipation. Pulse is 72/min despite a temperature of 40°C. Faint salmon-colored macules are seen on his trunk, as shown. Blood cultures grow a non–lactose-fermenting, H2S-producing, motile Gram-negative rod. Which statement about this organism is correct?",
  ["It has a Vi capsule and survives within macrophages, spreading through reticuloendothelial tissues", "It has an animal reservoir in poultry and reptiles", "It is non-motile and has a very low infectious dose", "It mainly causes watery diarrhea through a cAMP-raising toxin", "It is best treated with oral vancomycin"],
  "Typhoid fever: fever with relative bradycardia, abdominal pain, constipation then diarrhea, rose spots, and hepatosplenomegaly. S. Typhi has only a human reservoir. It invades through Peyer patches, survives in macrophages, and spreads through the reticuloendothelial system. The Vi capsule resists complement. Complications include intestinal perforation and hemorrhage. Treat with ceftriaxone or azithromycin (fluoroquinolone resistance is common). Chronic carriers harbor it in the gallbladder, especially with gallstones.",
  img="rose-spots.jpg"),
Q(T, "Salmonella: stool culture",
  "Stool from a patient with diarrhea after eating undercooked eggs is plated on Hektoen enteric agar. The colonies are shown: non–lactose-fermenting colonies with black centers. What does the black color indicate, and which organism is it?",
  ["Hydrogen sulfide production; Salmonella", "Lactose fermentation; E. coli", "Swarming; Proteus", "Pyocyanin; Pseudomonas", "Tellurite reduction; Corynebacterium"],
  "Hektoen enteric agar is selective and differential for stool pathogens. Lactose, sucrose, and salicin fermenters turn yellow-orange. Non-fermenters stay green or blue-green. H2S producers make black precipitates with ferric salts. Salmonella produces H2S and is motile. Shigella makes green colonies without H2S and is non-motile. These features separate the two non-lactose fermenters.",
  img="he-agar.jpg"),
Q(T, "Salmonella: non-typhoidal",
  "A 25-year-old woman has fever, cramps, and diarrhea 24 hours after eating undercooked chicken. Her roommate keeps a pet iguana. Stool culture grows non-typhoidal Salmonella. She is otherwise healthy, and symptoms are improving. What is the most appropriate management?",
  ["Oral rehydration only; antibiotics can prolong fecal shedding", "Ciprofloxacin for 14 days", "IV ceftriaxone", "Cholecystectomy to prevent carriage", "Oral vancomycin"],
  "Non-typhoidal Salmonella (Enteritidis, Typhimurium) comes from poultry, eggs, and reptiles. It causes self-limited inflammatory gastroenteritis. Antibiotics do not shorten illness in healthy adults and can prolong carriage. Treat patients who are severely ill, infants, adults over 50, or immunocompromised, and those with sickle cell disease, prostheses, or vascular grafts. Salmonella is a notable cause of osteomyelitis in sickle cell disease."),
Q(T, "Salmonella: sickle cell osteomyelitis",
  "A 10-year-old boy with sickle cell disease has fever and focal pain and swelling of the tibia. MRI confirms osteomyelitis. Besides S. aureus, which organism is especially associated with osteomyelitis in this population?",
  ["Salmonella species", "Pasteurella multocida", "Pseudomonas aeruginosa", "Mycobacterium tuberculosis", "Kingella kingae"],
  "Functional asplenia and bowel microinfarcts (which let enteric bacteria into the blood) predispose sickle cell patients to Salmonella osteomyelitis. S. aureus is still the most common cause overall. Pasteurella follows cat or dog bites. Pseudomonas follows puncture wounds through sneakers. Pott disease is TB of the spine."),
# ---------------- Shigella ----------------
Q(T, "Shigella: pathogenesis",
  "Several toddlers at a daycare develop fever, abdominal cramps, and frequent small-volume stools with blood and mucus. Stool culture grows a non-motile, non–lactose-fermenting Gram-negative rod that does not produce H2S. Which feature explains the very low infectious dose?",
  ["Acid resistance, so as few as 10–200 organisms survive gastric passage", "A polysaccharide capsule", "Production of urease to neutralize gastric acid", "Spore formation", "An animal reservoir that amplifies the inoculum"],
  "Shigella is extremely acid-stable, so fewer than 200 organisms cause disease. It spreads person to person and fecal-orally ('fingers, flies, food, feces, fomites'). It enters M cells, is taken up by macrophages (which it kills), and invades colonocytes from the basolateral side. It spreads cell to cell via actin polymerization (IcsA). S. dysenteriae makes Shiga toxin. Treat severe cases with azithromycin or ciprofloxacin. Complications: reactive arthritis and, rarely, HUS."),
Q(T, "Shigella vs Salmonella: host immunity",
  "Salmonella infection is more common in patients taking proton pump inhibitors, while Shigella is not much affected by gastric acid. Which feature of Salmonella explains this difference?",
  ["Salmonella is acid-labile and needs a large inoculum (~10⁵ organisms)", "Salmonella is non-motile", "Salmonella lacks flagella", "Salmonella is an obligate intracellular organism", "Salmonella forms spores in the stomach"],
  "Salmonella is acid-sensitive, so its infectious dose is high, and reduced gastric acid (PPIs, gastrectomy, antacids) raises the risk. Shigella resists acid, and a tiny inoculum is enough. Other contrasts: Salmonella is motile, makes H2S, and has animal reservoirs (except Typhi). Shigella is non-motile, makes no H2S, and has only human reservoirs. Both are non–lactose fermenters and both invade."),
# ---------------- Yersinia enterocolitica ----------------
Q(T, "Yersinia enterocolitica",
  "A 12-year-old has fever, right lower quadrant pain, and diarrhea after a holiday meal that included pork chitterlings. At laparoscopy the appendix is normal, but the mesenteric lymph nodes are enlarged. Which organism is most likely?",
  ["Yersinia enterocolitica", "Campylobacter jejuni", "Shigella sonnei", "Enterotoxigenic E. coli", "Clostridium perfringens"],
  "Y. enterocolitica comes from pork, unpasteurized milk, and pet feces. It causes enterocolitis and mesenteric adenitis that mimics appendicitis ('pseudoappendicitis'). It grows at refrigerator temperatures (cold enrichment). Iron overload and deferoxamine therapy increase risk, since deferoxamine acts as a siderophore for Yersinia. It is associated with reactive arthritis and erythema nodosum."),
# ---------------- Vibrio ----------------
Q(T, "Vibrio cholerae: mechanism",
  "Aid workers in a refugee camp see many patients with massive, painless, 'rice-water' diarrhea (up to 1 L/hour) and severe dehydration. A Gram stain of the stool is depicted. The toxin permanently activates which host protein?",
  ["Gs α-subunit, activating adenylyl cyclase and raising cAMP", "Gi α-subunit, inhibiting adenylyl cyclase", "Guanylyl cyclase C, raising cGMP", "Rho GTPase", "Elongation factor 2"],
  "V. cholerae is a comma-shaped, flagellated, oxidase-positive Gram-negative rod. Cholera toxin (AB5, phage-encoded) ADP-ribosylates Gsα so it cannot hydrolyze GTP. Adenylyl cyclase stays on, cAMP rises, and PKA phosphorylates CFTR, causing massive Cl−, Na+, and water secretion. The illness is non-inflammatory, with no fever or blood. The mainstay of treatment is oral rehydration solution, which relies on intact Na+-glucose cotransport (SGLT1). Doxycycline or azithromycin shortens illness.",
  img="vibrio-gram.jpg"),
Q(T, "Vibrio: culture",
  "Stool from a patient with suspected cholera is plated on thiosulfate-citrate-bile salts-sucrose (TCBS) agar, shown. V. cholerae forms yellow colonies (left) and V. parahaemolyticus forms green colonies (right). What does the yellow color reflect, and why does Vibrio grow on this medium?",
  ["Sucrose fermentation; Vibrio tolerates the high alkaline pH and bile of TCBS", "Lactose fermentation; Vibrio requires high salt", "Hydrogen sulfide production; Vibrio is an anaerobe", "Pigment production; Vibrio requires X and V factors", "Urease activity; Vibrio is acid-tolerant"],
  "TCBS is alkaline (pH ~8.6) and contains bile salts, which inhibit most other intestinal flora but allow Vibrio to grow. V. cholerae ferments sucrose, forming yellow colonies. V. parahaemolyticus and V. vulnificus do not, and stay green. V. cholerae is acid-sensitive, so it needs a large inoculum. Vibrio grows well in alkaline media.",
  img="tcbs.jpg"),
Q(T, "Vibrio vulnificus",
  "A 55-year-old man with alcoholic cirrhosis develops fever, hypotension, and hemorrhagic bullae on his legs 1 day after eating raw oysters in Louisiana. What is the most likely organism, and what increases his risk?",
  ["Vibrio vulnificus; liver disease and iron overload", "Vibrio parahaemolyticus; hypochlorhydria", "Aeromonas hydrophila; diabetes", "Staphylococcus aureus; injection drug use", "Pasteurella multocida; splenectomy"],
  "V. vulnificus lives in warm coastal waters and oysters. In people with liver disease, hemochromatosis, or immunosuppression, it causes fulminant sepsis with hemorrhagic bullae after eating raw shellfish. It also causes necrotizing wound infections after seawater exposure. Mortality is high. Treat with doxycycline plus ceftriaxone and debride. V. parahaemolyticus mainly causes seafood-associated gastroenteritis."),
# ---------------- Campylobacter ----------------
Q(T, "Campylobacter: Guillain-Barré",
  "A 30-year-old man had bloody diarrhea and fever after a barbecue with undercooked chicken. The stool organism was curved and comma- or S-shaped, as shown on electron micrograph, and grew at 42°C under microaerophilic conditions. Three weeks later he develops ascending weakness and areflexia. What mechanism links the infection to his neurologic disease?",
  ["Molecular mimicry between lipooligosaccharide and peripheral nerve gangliosides", "Direct invasion of peripheral nerves by the bacteria", "A neurotoxin that blocks acetylcholine release", "Immune complex deposition in the vasa nervorum", "Toxin-mediated inhibition of glycine release"],
  "Campylobacter jejuni is a leading cause of bacterial gastroenteritis worldwide. It comes from poultry, unpasteurized milk, and puppies. It grows at 42°C ('Campylobacter likes the hot campfire'). Its LOS resembles GM1 and GQ1b gangliosides. Antibodies cross-react with nerves and cause Guillain-Barré syndrome, or Miller Fisher syndrome with anti-GQ1b. It is also a cause of reactive arthritis.",
  img="campy-sem.jpg"),
# ---------------- Helicobacter pylori ----------------
Q(T, "H. pylori: virulence & disease",
  "A 45-year-old man has epigastric pain relieved by meals. Endoscopy shows a duodenal ulcer. The gastric antral biopsy (Giemsa stain) is shown, with curved rods in the surface mucus. Which enzyme lets this organism survive in the stomach?",
  ["Urease, which produces ammonia to buffer gastric acid", "Catalase, which neutralizes hydrogen peroxide", "Coagulase, which forms a fibrin shield", "Lipase, which digests the mucous layer", "Mucinase alone"],
  "H. pylori is a curved, flagellated, microaerophilic Gram-negative rod. It colonizes the gastric antrum and uses urease to make ammonia, buffering acid around itself. It causes chronic gastritis, over 90% of duodenal ulcers and most gastric ulcers, gastric adenocarcinoma, and MALT lymphoma. The CagA protein is associated with greater cancer risk. Diagnose with urea breath test, stool antigen, or biopsy.",
  img="hpylori.jpg"),
Q(T, "H. pylori: treatment",
  "A patient with a biopsy-confirmed H. pylori gastric ulcer lives where clarithromycin resistance exceeds 15%. Which regimen is preferred?",
  ["Bismuth quadruple therapy: PPI, bismuth, tetracycline, and metronidazole", "PPI, amoxicillin, and clarithromycin", "PPI alone for 8 weeks", "Amoxicillin monotherapy", "Vancomycin and rifaximin"],
  "In areas with high clarithromycin resistance, or with prior macrolide exposure, bismuth quadruple therapy for 14 days is first-line. Triple therapy (PPI + clarithromycin + amoxicillin, or metronidazole if penicillin-allergic) works only where resistance is low. Confirm eradication with urea breath test or stool antigen at least 4 weeks after antibiotics and 2 weeks off PPIs. PPIs suppress the organism and cause false negatives."),
Q(T, "H. pylori: MALT lymphoma",
  "Endoscopy in a 60-year-old woman with dyspepsia shows a gastric mass. Biopsy reveals extranodal marginal zone B-cell lymphoma with H. pylori infection and no t(11;18). What is the most appropriate first treatment?",
  ["H. pylori eradication therapy", "Total gastrectomy", "R-CHOP chemotherapy", "Radiation therapy", "Observation only"],
  "Low-grade gastric MALT lymphoma is driven by chronic H. pylori antigen stimulation of B cells. Eradicating H. pylori causes regression in most localized cases. Tumors with t(11;18) (API2-MALT1) usually do not respond to eradication alone and need radiation or immunotherapy."),
# ---------------- Anaerobes / general ----------------
Q(T, "Bacteroides fragilis: abscess",
  "Five days after surgery for a perforated colon, a 50-year-old man develops fever. CT shows a pelvic abscess. Culture grows anaerobic Gram-negative rods that are bile-resistant and produce β-lactamase. Which antibiotic has the best activity against this organism?",
  ["Metronidazole", "Aztreonam", "Gentamicin", "Ceftriaxone", "Vancomycin"],
  "Bacteroides fragilis is the most important anaerobe in intra-abdominal abscesses. Its polysaccharide capsule promotes abscess formation. Like other obligate anaerobes it lacks catalase and superoxide dismutase, and aminoglycosides do not work (oxygen-dependent uptake). Good anaerobic coverage: metronidazole, carbapenems, β-lactam/β-lactamase inhibitors (piperacillin-tazobactam, ampicillin-sulbactam). Resistance to clindamycin is rising. Anaerobic infections are foul-smelling and form gas."),
Q(T, "Lactose fermentation",
  "A Gram-negative rod from a urine culture forms pink colonies on MacConkey agar. Which organism could it be?",
  ["Klebsiella pneumoniae", "Proteus mirabilis", "Pseudomonas aeruginosa", "Salmonella enterica", "Shigella sonnei"],
  "MacConkey agar has bile salts and crystal violet, which inhibit Gram-positives, plus lactose and a pH indicator. Lactose fermenters make acid and turn pink: Citrobacter, E. coli, Enterobacter, Klebsiella, Serratia (late) — 'Lactose is key to ECEKS.' Non-fermenters (Proteus, Pseudomonas, Salmonella, Shigella, Yersinia) form colorless colonies."),
Q(T, "Reactive arthritis",
  "Three weeks after a bout of Shigella dysentery, a 28-year-old HLA-B27–positive man develops conjunctivitis, dysuria, and asymmetric knee and ankle arthritis. Joint fluid culture is sterile. Which pair of organisms is also classically associated with this syndrome?",
  ["Campylobacter and Chlamydia trachomatis", "Staphylococcus aureus and Streptococcus pyogenes", "Borrelia burgdorferi and Treponema pallidum", "Neisseria meningitidis and Haemophilus influenzae", "Mycobacterium tuberculosis and Nocardia"],
  "Reactive arthritis (conjunctivitis, urethritis, and arthritis) is a sterile, HLA-B27–associated seronegative spondyloarthropathy. It follows GI infection (Shigella, Salmonella, Yersinia, Campylobacter, C. difficile) or GU infection (Chlamydia trachomatis). Treatment is NSAIDs. Antibiotics are given for active chlamydial infection."),
]
