from qcore import Q
Z = "Zoonotic Bacteria"
S = "Spirochetes"
QUESTIONS = [
# ---------------- Yersinia pestis ----------------
Q(Z, "Y. pestis: bubonic plague",
  "A 22-year-old man camping in rural New Mexico develops high fever, chills, and an extremely tender, swollen inguinal mass that ruptures and drains, as shown. He handled a dead prairie dog. A Wayson stain of the aspirate shows bipolar-staining ('safety pin') Gram-negative coccobacilli. How was this infection most likely transmitted, and what is the treatment?",
  ["Flea bite; gentamicin or streptomycin", "Tick bite; doxycycline", "Mosquito bite; chloroquine", "Inhalation of spores; ciprofloxacin", "Ingestion of undercooked meat; supportive care"],
  "Yersinia pestis is carried by rodents (prairie dogs, ground squirrels, rats) and spread by flea bites. Bubonic plague causes very painful buboes in regional nodes. Septicemic and pneumonic forms can follow, and pneumonic plague spreads person to person by droplets. Virulence factors include the F1 capsule, Yop proteins injected by a type III secretion system (block phagocytosis), and plasminogen activator. Treat with an aminoglycoside (gentamicin, streptomycin) or a fluoroquinolone/doxycycline.",
  img="bubo.webp"),
Q(Z, "Y. pestis: morphology",
  "A blood smear from a febrile patient with a painful axillary bubo is shown (Wayson stain). What is the characteristic appearance of the organism?",
  ["Bipolar ('safety pin') staining of Gram-negative rods", "Gram-positive rods in chains with central spores", "Spirochetes between red cells", "Intracellular morulae in monocytes", "Acid-fast beaded rods"],
  "Y. pestis stains more densely at both ends with Wayson, Giemsa, or Wright stains, giving a 'safety pin' look. It is a facultative intracellular, non-motile, Gram-negative coccobacillus. Because of its bioterrorism potential and person-to-person droplet spread in pneumonic plague, the lab must be warned.",
  img="ypestis-wayson.webp"),
# ---------------- Francisella tularensis ----------------
Q(Z, "Francisella: ulceroglandular tularemia",
  "A hunter in Arkansas develops fever and a painful ulcer on his hand, shown, with tender, enlarged axillary lymph nodes, 4 days after skinning a wild rabbit. The organism is a tiny Gram-negative coccobacillus that needs cysteine-enriched media and poses a serious laboratory infection hazard. What is the most appropriate treatment?",
  ["Streptomycin or gentamicin", "Penicillin G", "Ceftriaxone", "Metronidazole", "Vancomycin"],
  "Francisella tularensis is carried by rabbits and other small mammals and spread by ticks, deer flies, handling animal carcasses, or aerosols. Ulceroglandular tularemia is the most common form. The organism is a facultative intracellular pathogen of macrophages and forms granulomas. It is highly infectious, so notify the lab. Treat with an aminoglycoside. Doxycycline or ciprofloxacin is used for milder disease.",
  img="tularemia.webp"),
# ---------------- Brucella ----------------
Q(Z, "Brucella: undulant fever",
  "A 40-year-old woman who recently moved from Mexico has had 2 months of fever that rises in the evening and falls by morning, drenching sweats, back pain from sacroiliitis, and hepatosplenomegaly. She regularly eats unpasteurized goat cheese. Which organism is most likely, and what is the treatment?",
  ["Brucella melitensis; doxycycline plus rifampin", "Coxiella burnetii; doxycycline alone", "Listeria monocytogenes; ampicillin", "Mycobacterium bovis; RIPE therapy", "Salmonella Typhi; ceftriaxone"],
  "Brucellosis (undulant or Malta fever) is caught from unpasteurized dairy or contact with infected cattle, goats, sheep, or pigs. It is a facultative intracellular Gram-negative coccobacillus that survives in macrophages of the reticuloendothelial system and forms non-caseating granulomas. It causes relapsing fever, sweats, arthralgia, sacroiliitis, spondylitis, and hepatosplenomegaly. Treat with doxycycline plus rifampin (or plus streptomycin/gentamicin) for at least 6 weeks."),
# ---------------- Pasteurella ----------------
Q(Z, "Pasteurella multocida: cat bite",
  "A 34-year-old woman is bitten on the hand by her cat. Twelve hours later the area is red, swollen, and painful with serous drainage. Which organism is most likely, and what is the treatment?",
  ["Pasteurella multocida; amoxicillin-clavulanate", "Bartonella henselae; azithromycin", "Staphylococcus aureus; cephalexin alone", "Capnocytophaga canimorsus; vancomycin", "Eikenella corrodens; metronidazole"],
  "Pasteurella multocida is an encapsulated Gram-negative coccobacillus found in the mouths of cats and dogs. It causes rapidly developing cellulitis (within 24 hours) after bites or scratches, and sometimes osteomyelitis or tenosynovitis because cat teeth penetrate deeply. Amoxicillin-clavulanate covers Pasteurella, anaerobes, and staph and strep, and is also used as prophylaxis for bites. Eikenella comes from human bites. Capnocytophaga causes sepsis after dog bites in asplenic patients."),
# ---------------- Bartonella ----------------
Q(Z, "Bartonella: cat scratch disease",
  "An 8-year-old boy has a tender, enlarged epitrochlear and axillary lymph node for 3 weeks. There is a small papule at the site of a kitten scratch on his hand, as shown. Lymph node biopsy would most likely show which finding?",
  ["Stellate necrotizing granulomas with neutrophilic microabscesses", "Caseating granulomas with acid-fast bacilli", "Reed-Sternberg cells", "Sheets of atypical lymphocytes", "Non-caseating granulomas with Schaumann bodies"],
  "Cat scratch disease is caused by Bartonella henselae, which is spread among kittens by fleas. It causes a papule at the inoculation site, then regional lymphadenopathy with stellate necrotizing granulomas. Most cases resolve on their own, but azithromycin can speed recovery. The organism stains with Warthin-Starry silver stain. It can also cause Parinaud oculoglandular syndrome, culture-negative endocarditis, and, in immunocompromised hosts, bacillary angiomatosis.",
  img="catscratch.webp"),
Q(Z, "Bartonella: bacillary angiomatosis",
  "A man with AIDS and a CD4 count of 40/μL has multiple red-purple, friable, vascular papules on his skin. Biopsy shows lobular capillary proliferation with neutrophilic infiltrate and clumps of bacteria on Warthin-Starry stain. What is the treatment?",
  ["Erythromycin or doxycycline", "Liposomal doxorubicin", "Valganciclovir", "Trimethoprim-sulfamethoxazole", "Surgical excision only"],
  "Bacillary angiomatosis (Bartonella henselae or quintana) looks like Kaposi sarcoma. Biopsy separates them: bacillary angiomatosis has neutrophils and bacilli, while KS has spindle cells and lymphocytes and is HHV-8–positive. Treat with erythromycin or doxycycline. B. quintana (spread by body lice) also causes trench fever, and B. henselae can cause peliosis hepatis."),
Q(Z, "Zoonoses: matching exposures",
  "Which pairing of exposure and organism is correct?",
  ["Parrots and other birds — Chlamydia psittaci", "Cattle placentas in a slaughterhouse — Leptospira interrogans", "Rabbits and deer flies — Brucella abortus", "Armadillos — Coxiella burnetii", "Prairie dog fleas — Francisella tularensis"],
  "High-yield zoonoses: Chlamydia psittaci from parrots and birds; Coxiella burnetii from aerosols of cattle and sheep birthing products (Q fever); Leptospira from water contaminated with rat or animal urine; Francisella from rabbits, ticks, and deer flies; Brucella from unpasteurized dairy and livestock; Yersinia pestis from rodent fleas; Mycobacterium leprae from armadillos; Borrelia from Ixodes ticks; Pasteurella from cat and dog bites; Bartonella from cats."),
# ---------------- Treponema pallidum ----------------
Q(S, "Syphilis: primary chancre",
  "A 30-year-old man has a single painless, indurated ulcer with a clean base on his finger, as shown, and painless regional lymphadenopathy. He reports unprotected sex with multiple partners. The organism cannot be grown in routine culture. Which test gives the fastest direct confirmation from the lesion?",
  ["Dark-field microscopy (or PCR) of the lesion exudate", "Gram stain of the exudate", "Tzanck smear", "Nontreponemal serology alone, which is always positive at this stage", "Culture on Thayer-Martin agar"],
  "A primary chancre is painless, indurated, and clean-based. It usually appears on the genitals but can be extragenital, as here on a finger. Treponema pallidum is too thin for Gram stain and cannot be cultured on artificial media. Dark-field microscopy or PCR shows motile spirochetes. Nontreponemal tests (VDRL/RPR) can be negative early in primary syphilis. Chancroid (H. ducreyi) causes painful ulcers ('you do cry'). HSV causes painful grouped vesicles.",
  img="chancre.webp"),
Q(S, "Syphilis: secondary",
  "A 25-year-old woman has malaise, generalized lymphadenopathy, patchy hair loss, and the non-pruritic rash on her palms shown. She also has broad, moist, flat-topped lesions in the perianal area. Which is the recommended treatment?",
  ["A single dose of IM benzathine penicillin G", "Oral doxycycline for 7 days", "IV aqueous penicillin G for 14 days", "IM ceftriaxone single dose", "Oral acyclovir"],
  "Secondary syphilis (weeks to months after the chancre) is the disseminated stage. It causes a diffuse maculopapular rash that involves the palms and soles, condylomata lata (highly infectious moist papules), alopecia, mucous patches, and lymphadenopathy. RPR/VDRL titers are highest here. Primary, secondary, and early latent syphilis are treated with one dose of IM benzathine penicillin G. Neurosyphilis and ocular or otic syphilis need IV aqueous penicillin G.",
  img="syph-palms.webp"),
Q(S, "Syphilis: Jarisch-Herxheimer",
  "Four hours after receiving benzathine penicillin G for secondary syphilis, a patient develops fever, chills, myalgias, headache, and worsening of his rash. What is the cause?",
  ["Release of lipoproteins and cytokines (TNF, IL-6) after rapid killing of spirochetes", "IgE-mediated penicillin allergy", "Serum sickness from immune complexes", "Superinfection with Staphylococcus aureus", "Progression to neurosyphilis"],
  "The Jarisch-Herxheimer reaction is a self-limited flu-like reaction within 24 hours of treating spirochetal infections (syphilis, Lyme, leptospirosis, relapsing fever). Dying organisms release lipoproteins that trigger cytokine release. Treat it with antipyretics. It is not an allergy, so penicillin should be continued."),
Q(S, "Syphilis: serology",
  "A 32-year-old woman with systemic lupus erythematosus has a positive RPR (1:4) at a prenatal visit. A treponemal-specific test (FTA-ABS) is negative. What best explains this?",
  ["A biologic false-positive, because the nontreponemal test detects antibodies to cardiolipin", "Early primary syphilis", "Successfully treated past syphilis", "Latent syphilis", "Neurosyphilis"],
  "Nontreponemal tests (VDRL, RPR) detect antibodies to cardiolipin-cholesterol-lecithin. They are used for screening and for following treatment response, since titers fall after therapy. False positives occur with SLE and antiphospholipid syndrome, pregnancy, viral infections (EBV, hepatitis), injection drug use, leprosy, and malaria. Treponemal tests (FTA-ABS, TP-PA, EIA) are specific and usually stay positive for life, even after treatment."),
Q(S, "Syphilis: tertiary",
  "A 70-year-old man has shooting pains in his legs, a wide-based stamping gait, and a positive Romberg sign. His pupils constrict with accommodation but not with light. CXR shows a dilated ascending aorta with eggshell calcification. Which pathologic process underlies the aortic lesion?",
  ["Endarteritis obliterans of the vasa vasorum, causing medial necrosis ('tree-bark' intima)", "Cystic medial degeneration from fibrillin mutation", "Granulomatous inflammation of the aortic arch in a young woman", "Atherosclerosis of the abdominal aorta", "Immune complex deposition in the adventitia"],
  "Tertiary syphilis appears years to decades later. Tabes dorsalis involves the dorsal columns and roots (lightning pains, sensory ataxia, positive Romberg, Charcot joints). Argyll Robertson pupils accommodate but do not react to light. Cardiovascular syphilis comes from endarteritis obliterans of the vasa vasorum, which weakens the media of the ascending aorta. The result is aneurysm and aortic regurgitation. Gummas (granulomas) occur in skin, bone, and liver. Neurosyphilis requires IV aqueous penicillin G."),
Q(S, "Syphilis: congenital",
  "A 9-year-old child has notched, peg-shaped upper central incisors (shown), a saddle nose, interstitial keratitis, and sensorineural hearing loss. Which intervention would have prevented this condition?",
  ["Screening and treating the mother with penicillin during pregnancy", "Erythromycin ointment at birth", "Measles-mumps-rubella vaccination of the mother during pregnancy", "Avoiding cat litter during pregnancy", "Delivering by cesarean section"],
  "Congenital syphilis comes from transplacental spread and can cause stillbirth, hydrops, and early findings (rhinorrhea 'snuffles', rash, hepatosplenomegaly, periostitis). Late findings include Hutchinson teeth, mulberry molars, saddle nose, saber shins, interstitial keratitis, and eighth nerve deafness (Hutchinson triad). All pregnant women are screened. Penicillin is the only adequate treatment in pregnancy, so penicillin-allergic women are desensitized.",
  img="hutchinson.webp"),
# ---------------- Borrelia burgdorferi ----------------
Q(S, "Lyme disease: erythema migrans",
  "A 40-year-old man in Connecticut develops fever, fatigue, and the expanding rash shown on his thigh 10 days after hiking in June. What is the vector, and what is the treatment?",
  ["Ixodes scapularis tick; oral doxycycline", "Dermacentor tick; oral doxycycline", "Ixodes tick; IV ceftriaxone for all patients", "Body louse; oral penicillin", "Lone star tick (Amblyomma); no treatment needed"],
  "Erythema migrans is an expanding annular 'bull's-eye' rash at the tick bite site. It is the hallmark of early localized Lyme disease, caused by Borrelia burgdorferi. The vector is the black-legged (deer) tick Ixodes scapularis. White-footed mice are reservoirs and deer host the adult ticks. It is most common in the Northeast and upper Midwest. Treat with doxycycline (amoxicillin or cefuroxime in young children or pregnancy). Diagnosis is clinical, since serology is often negative this early.",
  img="em-rash.webp"),
Q(S, "Lyme disease: tick & co-infection",
  "The tick shown (adult female, adult male, nymph, and larva next to a dime) is the vector of Lyme disease. Nymphs cause most infections. Which two other infections are spread by the same tick?",
  ["Babesiosis and anaplasmosis", "Rocky Mountain spotted fever and tularemia", "Ehrlichiosis and plague", "Epidemic typhus and trench fever", "Chagas disease and leishmaniasis"],
  "Ixodes scapularis nymphs are poppy-seed sized and often go unnoticed. Transmission of B. burgdorferi usually needs more than 36–48 hours of attachment, because spirochetes move from tick midgut to salivary glands after feeding starts. The same tick carries Babesia microti and Anaplasma phagocytophilum (and Powassan virus), so co-infection can occur. Dermacentor carries RMSF and tularemia. Amblyomma (lone star tick) carries Ehrlichia chaffeensis.",
  img="ixodes.webp"),
Q(S, "Lyme disease: disseminated",
  "A 12-year-old boy in Wisconsin has bilateral facial nerve palsy and, on ECG, a second-degree AV block, 6 weeks after a summer camping trip. What is the most likely diagnosis, and what is appropriate therapy?",
  ["Early disseminated Lyme disease; IV ceftriaxone", "Sarcoidosis; prednisone", "Guillain-Barré syndrome; IVIG", "Viral myocarditis; supportive care", "Acute rheumatic fever; penicillin"],
  "Early disseminated Lyme disease (weeks to months after the bite) causes multiple EM lesions, cranial neuropathies (classically bilateral facial palsy), lymphocytic meningitis, radiculopathy, and carditis (AV block). Symptomatic or high-degree heart block needs IV ceftriaxone. Late Lyme disease causes migratory, then chronic, large-joint oligoarthritis (knee) and encephalopathy. Lyme is 'Key Lyme pie': facial nerve (Key), AV block (Lyme), migrans (pie)."),
# ---------------- Borrelia recurrentis / relapsing fever ----------------
Q(S, "Relapsing fever",
  "A 25-year-old man who spent a week in a rustic cabin in the Sierra Nevada has recurring 3-day episodes of high fever separated by about a week without fever. A Wright-Giemsa blood smear drawn during a fever is shown. What explains the recurring fevers?",
  ["Antigenic variation of the variable major outer membrane proteins", "Periodic release of merozoites from lysed red cells", "Reactivation of latent virus in dorsal root ganglia", "Periodic release of endotoxin from a hepatic abscess", "Cyclic neutropenia"],
  "Relapsing fever is caused by Borrelia recurrentis (body louse, epidemic) or by Borrelia hermsii and other tick-borne species (soft Ornithodoros ticks in rodent-infested cabins). Spirochetes are visible between RBCs on Giemsa or Wright smears taken during fever. Each relapse reflects a new antigenic variant, created by switching of variable major proteins, that escapes the existing antibody. Treat with doxycycline and watch for Jarisch-Herxheimer reactions.",
  img="borrelia-smear.webp"),
# ---------------- Leptospira ----------------
Q(S, "Leptospira: Weil disease",
  "A 30-year-old man develops fever, severe myalgias of the calves, and conjunctival suffusion 10 days after cleaning up floodwater in Hawaii. He then becomes jaundiced with acute kidney injury and pulmonary hemorrhage. The organism is a thin, hooked spirochete, shown on electron micrograph. What is the source of infection?",
  ["Water or soil contaminated with animal (rat) urine", "Bite of an infected mosquito", "Undercooked pork", "Inhalation of bird droppings", "Unpasteurized milk"],
  "Leptospira interrogans is shed in the urine of rats, dogs, and livestock and enters through broken skin or mucosa in contaminated water. This is common in the tropics (Hawaii), after floods, and among surfers and sewer workers. Leptospirosis is biphasic: flu-like illness with conjunctival suffusion and calf pain, then an immune phase. Weil disease is the severe form, with jaundice, AKI, hemorrhage, and myocarditis. Treat with doxycycline or penicillin (IV penicillin or ceftriaxone if severe).",
  img="lepto-sem.webp"),
Q(S, "Spirochetes: visualization",
  "Which statement about spirochetes is correct?",
  ["Borrelia is large enough to see with aniline dyes (Wright or Giemsa); Treponema and Leptospira need dark-field or other methods", "All spirochetes Gram-stain strongly positive", "Treponema pallidum is easily grown on blood agar", "Leptospira is best seen in a Wright-stained blood smear", "Spirochetes lack an outer membrane"],
  "Spirochetes are thin, spiral bacteria with axial filaments (endoflagella) inside a Gram-negative-type outer membrane. Only Borrelia is big enough to see with Wright or Giemsa stain ('BLT: Borrelia is Big'). Treponema is seen with dark-field microscopy or fluorescent antibody. Leptospira is seen with dark-field or silver stains."),
]
