from qcore import Q
T = "Rickettsiae & Chlamydiae"
QUESTIONS = [
# ---------------- Rickettsia rickettsii ----------------
Q(T, "RMSF: clinical",
  "A 7-year-old girl in North Carolina has 4 days of high fever, headache, and myalgias. The rash shown began on her wrists and ankles and spread to her trunk, palms, and soles. Labs show thrombocytopenia and a sodium of 130 mEq/L. She had a tick removed 1 week ago. What is the most appropriate treatment?",
  ["Doxycycline", "Amoxicillin", "Chloramphenicol only if older than 8 years", "Azithromycin", "Ceftriaxone"],
  "Rocky Mountain spotted fever (Rickettsia rickettsii, spread by Dermacentor dog and wood ticks) is most common in the south-central and southeastern US, despite its name. The rash starts at the wrists and ankles and spreads centrally, including the palms and soles. Doxycycline is the treatment for all ages, including young children, because the risk of death outweighs the small risk of tooth staining from a short course. Start it on clinical suspicion. Delay raises mortality.",
  img="rmsf.jpg"),
Q(T, "RMSF: pathogenesis",
  "Rickettsia rickettsii infects and multiplies inside a particular host cell type, which causes the rash, edema, hypotension, and multiorgan damage of Rocky Mountain spotted fever. Which cell type is it?",
  ["Vascular endothelial cells", "Hepatocytes", "Monocytes", "Neutrophils", "Erythrocytes"],
  "Rickettsiae are obligate intracellular bacteria. They cannot make their own CoA and NAD+ and must take them from host cells. R. rickettsii infects endothelial (and vascular smooth muscle) cells, causing widespread vasculitis, increased vascular permeability, edema, hypovolemia, hyponatremia, thrombocytopenia, and petechial or necrotic skin lesions. Encephalitis and noncardiogenic pulmonary edema can occur. Classic triad: headache, fever, rash."),
# ---------------- Epidemic / endemic typhus ----------------
Q(T, "Epidemic typhus",
  "During a humanitarian crisis, several people in a crowded refugee camp develop high fever, severe headache, and a maculopapular rash that starts on the trunk and spreads outward, sparing the palms, soles, and face. Many have body lice. Which organism is most likely, and what phenomenon can occur years later?",
  ["Rickettsia prowazekii; recrudescence as Brill-Zinsser disease", "Rickettsia typhi; Guillain-Barré syndrome", "Rickettsia rickettsii; chronic arthritis", "Bartonella quintana; bacillary angiomatosis", "Borrelia recurrentis; chronic meningitis"],
  "Epidemic typhus (R. prowazekii) is spread by human body lice (and flying squirrels in the US) in crowded, unsanitary conditions. The rash is centrifugal: it starts on the trunk and spreads outward, sparing the palms and soles. This is the opposite of RMSF ('rickettsii on the wrists, typhus on the trunk'). Latent infection can reactivate years later as Brill-Zinsser disease. Endemic (murine) typhus, R. typhi, is spread by fleas and is milder. Treat all with doxycycline."),
# ---------------- Ehrlichia / Anaplasma ----------------
Q(T, "Ehrlichiosis",
  "A 55-year-old man from Arkansas has fever, headache, and myalgias 1 week after a tick bite. There is no rash. Labs show leukopenia, thrombocytopenia, and elevated transaminases. A blood smear is shown, with a mulberry-like cluster inside a monocyte (arrow). What is the most likely organism?",
  ["Ehrlichia chaffeensis", "Anaplasma phagocytophilum", "Babesia microti", "Rickettsia rickettsii", "Borrelia burgdorferi"],
  "Human monocytic ehrlichiosis (Ehrlichia chaffeensis, spread by the lone star tick Amblyomma americanum) causes fever with leukopenia, thrombocytopenia, and transaminitis. It usually has no rash. The morulae (berry-like clusters of bacteria in vacuoles) are in monocytes. Anaplasma phagocytophilum (Ixodes tick) forms morulae in granulocytes (neutrophils). Babesia appears inside RBCs. Treat both with doxycycline.",
  img="ehrlichia.jpg"),
# ---------------- Coxiella ----------------
Q(T, "Coxiella: Q fever",
  "Several workers at a sheep farm develop fever, severe headache, and atypical pneumonia with elevated liver enzymes during lambing season. No one has a rash, and no one recalls a tick bite. Which feature of the organism explains how it spreads?",
  ["It forms a highly resistant spore-like small-cell variant that is inhaled in aerosols from birth products", "It is spread only by tick bites", "It spreads person to person by respiratory droplets", "It is acquired by eating undercooked lamb", "It requires a mosquito vector"],
  "Coxiella burnetii causes Q fever. It is an obligate intracellular organism, but unlike the rickettsiae it is usually inhaled (no arthropod vector needed) and causes no rash. Infected cattle, sheep, and goats shed huge numbers in placentas and amniotic fluid. Its resistant small-cell variant survives in the environment and a single organism can cause infection. Acute illness: pneumonia, hepatitis (fibrin-ring granulomas), fever. Chronic Q fever causes culture-negative endocarditis. Treat with doxycycline."),
Q(T, "Culture-negative endocarditis",
  "A 60-year-old man with a prosthetic aortic valve has months of low-grade fever, weight loss, and a new murmur. Repeated blood cultures are negative. He works in a slaughterhouse. Which organism is a classic cause of culture-negative endocarditis in this setting?",
  ["Coxiella burnetii", "Staphylococcus aureus", "Streptococcus sanguinis", "Enterococcus faecalis", "Escherichia coli"],
  "Culture-negative endocarditis is often caused by organisms that are hard to grow: Coxiella burnetii, Bartonella species, and the HACEK group (Haemophilus, Aggregatibacter, Cardiobacterium, Eikenella, Kingella). Diagnose Coxiella with serology (high phase I IgG in chronic disease) or PCR. Prior antibiotics are the most common cause of negative cultures overall."),
# ---------------- Chlamydia biology ----------------
Q(T, "Chlamydia: life cycle",
  "A cell culture inoculated with a cervical swab shows intracytoplasmic inclusions (stained brown) after incubation, as shown. The organism alternates between an infectious extracellular form and a replicating intracellular form. Which statement about this organism is correct?",
  ["The elementary body is infectious and enters cells; the reticulate body replicates by binary fission", "The reticulate body is the infectious form that survives outside cells", "It replicates in the nucleus using host DNA polymerase", "It synthesizes its own ATP and does not require host cells", "It has a thick peptidoglycan cell wall rich in muramic acid"],
  "Chlamydiae are obligate intracellular bacteria. The small, dense elementary body ('Enters') is taken up by endocytosis and turns into the reticulate body ('Replicates') inside an inclusion that avoids lysosomal fusion. Reticulate bodies divide and convert back to elementary bodies, which are released. Chlamydiae cannot make their own ATP. Their cell wall lacks classic peptidoglycan (reduced muramic acid), so β-lactams are ineffective. Glycogen-rich C. trachomatis inclusions stain with iodine. Cytoplasmic inclusions can be seen on Giemsa stain or fluorescent antibody.",
  img="chlamydia-incl.jpg"),
Q(T, "Chlamydia trachomatis: urogenital",
  "A 19-year-old woman has mucopurulent cervical discharge and friable cervix. Nucleic acid amplification testing of a vaginal swab is positive for Chlamydia trachomatis and negative for gonorrhea. She is not pregnant. What is the preferred treatment?",
  ["Doxycycline for 7 days", "A single dose of IM ceftriaxone", "Penicillin G", "Metronidazole for 7 days", "Fluconazole single dose"],
  "C. trachomatis serovars D–K cause the most common bacterial STI: urethritis, cervicitis, epididymitis, proctitis, PID, and neonatal conjunctivitis and pneumonia. Many infections are asymptomatic, so sexually active women under 25 are screened yearly by NAAT. Doxycycline for 7 days is preferred. In pregnancy, azithromycin is used. Treat partners and retest in 3 months."),
Q(T, "Chlamydia: PID & Fitz-Hugh-Curtis",
  "A 23-year-old woman has lower abdominal pain, cervical motion tenderness, and right upper quadrant pain that worsens with breathing. Laparoscopy shows 'violin-string' adhesions between the liver capsule and the anterior abdominal wall. Which long-term complication of her underlying infection is she most at risk for?",
  ["Ectopic pregnancy and tubal infertility", "Cervical cancer", "Hepatocellular carcinoma", "Bladder cancer", "Osteomyelitis"],
  "Pelvic inflammatory disease from Chlamydia or gonorrhea ascends to the endometrium and fallopian tubes (salpingitis). Scarring causes infertility, ectopic pregnancy, chronic pelvic pain, and tubo-ovarian abscess. Fitz-Hugh-Curtis syndrome is perihepatitis with adhesions from spread of infection. Outpatient treatment is IM ceftriaxone plus doxycycline plus metronidazole."),
Q(T, "Chlamydia: neonatal pneumonia",
  "A 6-week-old infant has a staccato cough and tachypnea without fever. Bilateral interstitial infiltrates are seen on CXR. CBC shows eosinophilia. The infant had conjunctivitis at 10 days of age. What is the appropriate treatment?",
  ["Oral azithromycin or erythromycin", "IV ampicillin and gentamicin", "IV acyclovir", "Ceftriaxone", "Oral amoxicillin"],
  "Chlamydia trachomatis acquired at birth causes conjunctivitis at 5–14 days and an afebrile pneumonia at 1–3 months with a staccato cough and eosinophilia. Treat with an oral macrolide. Erythromycin in infants under 6 weeks is associated with hypertrophic pyloric stenosis, so azithromycin is often preferred. Topical prophylaxis at birth does not prevent chlamydial conjunctivitis."),
Q(T, "Chlamydia: serotypes",
  "A 30-year-old man who has sex with men has a painless genital papule that heals, then 3 weeks later develops painful, suppurating inguinal lymph nodes above and below the inguinal ligament (the 'groove sign'), with proctitis. Which C. trachomatis serovars cause this?",
  ["L1–L3", "A–C", "D–K", "A–K", "Serovars of C. psittaci"],
  "C. trachomatis serovars: A–C (Africa, blindness, chronic infection) cause trachoma, a leading infectious cause of blindness, spread by hands, flies, and fomites. D–K cause urogenital infection and neonatal disease. L1–L3 cause lymphogranuloma venereum, which invades lymphatics: painless ulcer, then painful buboes and proctocolitis. LGV can lead to strictures, fistulas, and genital elephantiasis. Treat LGV with doxycycline for 21 days."),
Q(T, "Chlamydia: trachoma",
  "A 55-year-old woman from rural Ethiopia has eyelid scarring that turns her lashes inward to scrape the cornea, with corneal opacity. She had recurrent follicular conjunctivitis as a child. Which organism causes this, and how is it spread?",
  ["C. trachomatis serovars A–C; by hands, flies, and shared cloths", "C. trachomatis serovars D–K; at birth", "Onchocerca volvulus; by blackfly bites", "Neisseria gonorrhoeae; sexual contact", "Acanthamoeba; contaminated contact lens solution"],
  "Trachoma is chronic keratoconjunctivitis from repeated C. trachomatis A–C infection in poor sanitary conditions. Scarring causes entropion and trichiasis (lashes rubbing the cornea), then corneal opacity and blindness. The WHO SAFE strategy: Surgery, Antibiotics (mass azithromycin), Facial cleanliness, and Environmental improvement. Onchocerca causes 'river blindness.'"),
Q(T, "Chlamydophila pneumoniae & psittaci",
  "A 60-year-old pet shop owner has fever, headache, dry cough, and hepatosplenomegaly. CXR shows patchy infiltrates. Several of his parrots have died recently. What is the most likely organism, and what is the treatment?",
  ["Chlamydia psittaci; doxycycline", "Coxiella burnetii; ciprofloxacin", "Histoplasma capsulatum; itraconazole", "Cryptococcus neoformans; fluconazole", "Legionella pneumophila; amoxicillin"],
  "Psittacosis (C. psittaci) is inhaled from dried droppings or secretions of infected birds, especially parrots. It causes atypical pneumonia with headache, relative bradycardia, and hepatosplenomegaly. Treat with doxycycline. C. pneumoniae spreads person to person, causes mild atypical pneumonia and pharyngitis in young adults, and has been linked to atherosclerosis. Histoplasma and Cryptococcus are fungi found in bird and bat droppings."),
Q(T, "Atypical pneumonia: organism features",
  "Which feature is shared by Chlamydia, Rickettsia, and Coxiella?",
  ["Obligate intracellular growth, depending on the host for ATP or cofactors", "Lack of a cell wall and cholesterol in the membrane", "Acid-fast staining due to mycolic acids", "Spread only by arthropod vectors", "Easy growth on blood agar"],
  "Obligate intracellular bacteria (Rickettsia, Chlamydia, Coxiella; 'stay inside when it is Really Chilly and Cold') cannot make enough ATP or cofactors on their own and do not grow on artificial media. They are treated with drugs that get into cells: tetracyclines, macrolides, and fluoroquinolones. Mycoplasma is the organism that lacks a cell wall and has cholesterol (sterols) in its membrane."),
]
