from qcore import Q
M = "Mycobacteria"
X = "Mycoplasma & Other Bacteria"
QUESTIONS = [
# ---------------- M. tuberculosis ----------------
Q(M, "TB: acid-fast cell wall",
  "A 45-year-old man from the Philippines has 2 months of productive cough, night sweats, weight loss, and hemoptysis. A Ziehl-Neelsen stain of his sputum is shown, with red rods against a blue background. What cell wall component explains this staining property?",
  ["Mycolic acids", "Teichoic acids", "Lipopolysaccharide", "Poly-D-glutamate", "Peptidoglycan lacking muramic acid"],
  "Mycobacteria have a waxy cell envelope rich in long-chain mycolic acids. This makes them resist decolorization with acid-alcohol after carbol fuchsin staining (acid-fast). They stain poorly with Gram stain. Cord factor (trehalose dimycolate) makes virulent M. tuberculosis grow in serpentine cords, inhibits neutrophil migration, and activates macrophages to form granulomas (TNF-α release). Sulfatides block phagolysosome fusion.",
  img="tb-zn.webp"),
Q(M, "TB: granuloma immunology",
  "A lymph node biopsy from a patient with tuberculosis is shown: a caseating granuloma with epithelioid macrophages and Langhans giant cells around central necrosis. Which cytokine pathway is most essential for forming and maintaining this lesion?",
  ["IL-12 from macrophages driving Th1 cells to secrete IFN-γ, plus TNF-α", "IL-4 and IL-13 from Th2 cells", "IL-17 from Th17 cells recruiting neutrophils", "IL-10 and TGF-β from regulatory T cells", "IgE-mediated mast cell degranulation"],
  "Infected macrophages present antigen and secrete IL-12. This drives CD4+ Th1 cells to produce IFN-γ, which activates macrophages to kill bacteria and become epithelioid cells and giant cells. TNF-α keeps the granuloma intact. That is why TNF inhibitors (infliximab, adalimumab, etanercept) can reactivate latent TB, so patients are screened first. Defects in IL-12/IFN-γ signaling cause disseminated mycobacterial infections. Tuberculin skin test reactions are type IV hypersensitivity.",
  img="tb-granuloma.webp"),
Q(M, "TB: primary vs reactivation",
  "Primary tuberculosis typically involves the lower lobes with hilar lymph node involvement (Ghon complex). Reactivation tuberculosis in adults usually involves which area, and why?",
  ["Apical-posterior upper lobes, because of high oxygen tension", "Lower lobes, because of greater blood flow", "Right middle lobe, because of bronchial anatomy", "Pleura only, because of low perfusion", "Hilar nodes, because of lymphatic drainage"],
  "In primary TB, inhaled bacilli land in the well-ventilated lower or middle lobes, forming a Ghon focus plus hilar lymph node, which together make the Ghon complex (calcified later as a Ranke complex). Most people contain the infection (latent TB). Reactivation, often with immune compromise, favors the apices because M. tuberculosis is an obligate aerobe that thrives where oxygen tension is high. It forms fibrocaseous cavities that spread infection."),
Q(M, "TB: miliary disease",
  "An 82-year-old woman on chronic prednisone has had 3 weeks of fever, weight loss, and confusion. Her chest radiograph is shown, with innumerable 1- to 3-mm nodules in both lungs. Which statement about this condition is correct?",
  ["It reflects hematogenous spread of M. tuberculosis, and it can involve the meninges, liver, spleen, and bone marrow", "It reflects spread through the airways from a single cavity", "It is caused only by nontuberculous mycobacteria", "It does not occur in adults", "It is usually confined to the hilar lymph nodes"],
  "Miliary TB (millet-seed nodules) is hematogenous spread in patients with weak cell-mediated immunity (the very young or old, HIV, steroids, TNF inhibitors). Extrapulmonary TB includes meningitis (basilar, with CN palsies and low CSF glucose), Pott disease (vertebral osteomyelitis), adrenal insufficiency, scrofula (cervical lymphadenitis), renal TB ('sterile pyuria'), and pericarditis. Sputum smears are often negative, and tuberculin tests may be anergic.",
  img="miliary-tb.webp"),
Q(M, "TB: skin test interpretation",
  "A 30-year-old nurse born in the US has a routine tuberculin skin test, shown being measured at 48 hours. The induration measures 12 mm. She has no symptoms and a normal chest radiograph. How should this be interpreted?",
  ["Positive; evaluate and treat for latent TB infection", "Negative; induration must be at least 15 mm in any person", "Positive only if she has HIV", "Indeterminate, because erythema must also be measured", "False-positive from prior BCG vaccination by definition"],
  "Thresholds for induration (not redness): ≥5 mm in HIV, close contacts of active TB, fibrotic changes on CXR, organ transplant, or immunosuppression. ≥10 mm in recent immigrants from high-prevalence countries, injection drug users, residents and workers in high-risk settings (healthcare, prisons), and children under 4. ≥15 mm in people with no risk factors. Interferon-γ release assays (IGRAs) are not affected by BCG and need only one visit. Neither test separates latent from active TB.",
  img="mantoux.webp"),
Q(M, "TB: latent treatment",
  "A 28-year-old man with a positive interferon-γ release assay has no symptoms and a normal chest radiograph. Which regimen is appropriate?",
  ["Rifampin daily for 4 months", "Rifampin, isoniazid, pyrazinamide, and ethambutol for 6 months", "No treatment", "Streptomycin for 2 months", "Azithromycin weekly"],
  "Latent TB infection (positive TST or IGRA with no active disease) is treated to prevent reactivation. Preferred regimens: 3 months of weekly isoniazid + rifapentine, 4 months of daily rifampin, or 3 months of daily isoniazid + rifampin. Six to 9 months of isoniazid (with pyridoxine) is an alternative. Active TB must be excluded first, with CXR and sputum if symptomatic, to avoid monotherapy and resistance."),
Q(M, "TB drugs: isoniazid",
  "A 50-year-old woman on RIPE therapy for pulmonary TB develops burning paresthesias in her feet. Which drug is responsible, and how could this have been prevented?",
  ["Isoniazid; supplemental pyridoxine (vitamin B6)", "Ethambutol; supplemental folate", "Rifampin; supplemental thiamine", "Pyrazinamide; allopurinol", "Isoniazid; supplemental cobalamin"],
  "Isoniazid is a prodrug activated by mycobacterial catalase-peroxidase (KatG). It inhibits InhA and blocks mycolic acid synthesis. It competes with pyridoxine, causing peripheral neuropathy and sideroblastic anemia, so B6 is given with it. It is also hepatotoxic, especially in older patients, and inhibits CYP450. Slow acetylators (NAT2) have higher levels and more toxicity. It can cause drug-induced lupus. Isoniazid overdose causes seizures treated with pyridoxine. Resistance most often comes from katG mutations."),
Q(M, "TB drugs: RIPE adverse effects",
  "A patient being treated for active TB notices orange urine and tears, loses red-green color discrimination, and has an elevated serum uric acid. Which drug pairings are correct?",
  ["Rifampin — orange fluids; ethambutol — optic neuritis; pyrazinamide — hyperuricemia", "Isoniazid — orange fluids; rifampin — optic neuritis; ethambutol — hyperuricemia", "Pyrazinamide — orange fluids; isoniazid — optic neuritis; rifampin — hyperuricemia", "Ethambutol — orange fluids; pyrazinamide — optic neuritis; isoniazid — hyperuricemia", "Rifampin — optic neuritis; ethambutol — orange fluids; pyrazinamide — hepatotoxicity only"],
  "Rifampin inhibits DNA-dependent RNA polymerase. It turns body fluids red-orange and strongly induces CYP450, reducing levels of warfarin, OCPs, and HIV protease inhibitors (rifabutin is preferred with PIs). Ethambutol inhibits arabinosyltransferase (arabinogalactan synthesis) and causes optic neuritis with red-green color blindness. Pyrazinamide works in acidic phagolysosomes and causes hyperuricemia (gout) and hepatotoxicity. All but ethambutol are hepatotoxic. Standard therapy is RIPE for 2 months, then isoniazid + rifampin for 4 months."),
# ---------------- NTM ----------------
Q(M, "MAC in AIDS",
  "A man with AIDS and a CD4 count of 30/μL has fever, night sweats, weight loss, diarrhea, and hepatosplenomegaly. Blood cultures grow acid-fast bacilli that are not M. tuberculosis. What is the most likely organism and treatment?",
  ["Mycobacterium avium complex; clarithromycin (or azithromycin) plus ethambutol", "Mycobacterium kansasii; isoniazid alone", "Mycobacterium marinum; doxycycline", "Mycobacterium leprae; dapsone", "Mycobacterium tuberculosis; RIPE"],
  "Disseminated MAC occurs at CD4 counts below 50/μL. It comes from the environment (water, soil) and is not spread person to person. It causes fever, weight loss, diarrhea, anemia, and elevated alkaline phosphatase. Treat with a macrolide plus ethambutol, sometimes with rifabutin. Azithromycin prophylaxis is no longer routine if ART is started right away. MAC also causes cavitary lung disease in people with bronchiectasis and nodular bronchiectasis in thin older women ('Lady Windermere')."),
Q(M, "M. marinum",
  "A 45-year-old man who cleans his home aquarium develops a series of nodules that ulcerate, spreading up his forearm from a finger scrape. Biopsy shows granulomas with acid-fast bacilli that grow best at 30–32°C. What is the organism?",
  ["Mycobacterium marinum", "Sporothrix schenckii", "Mycobacterium leprae", "Nocardia brasiliensis", "Mycobacterium avium complex"],
  "M. marinum causes 'fish tank granuloma': skin nodules after exposure of broken skin to fresh or salt water. It can spread in a lymphocutaneous (sporotrichoid) pattern. It grows at lower temperatures, so it stays in the cooler extremities. Treat with clarithromycin plus ethambutol or rifampin. Sporothrix gives a similar pattern after rose-thorn or soil exposure."),
# ---------------- M. leprae ----------------
Q(M, "Leprosy: immune spectrum",
  "A 35-year-old man from Brazil has diffuse, symmetric skin nodules, loss of the lateral eyebrows, 'leonine' facies, and stocking-glove sensory loss. Skin biopsy is shown: sheets of foamy macrophages (Virchow cells) filled with acid-fast bacilli and few lymphocytes. Which immune response characterizes this form of disease?",
  ["A Th2-dominant response with poor cell-mediated immunity and a negative lepromin skin test", "A Th1-dominant response with well-formed granulomas and few organisms", "A Th17 response with neutrophilic abscesses", "An IgE-mediated response with eosinophilia", "A strong CD8 cytotoxic response that clears infected cells"],
  "Leprosy (Hansen disease) forms a spectrum. Lepromatous leprosy reflects a Th2-dominant response (IL-4, IL-10) with poor macrophage activation, many bacilli, diffuse lesions, and high infectivity. It can be fatal. Tuberculoid leprosy reflects a strong Th1 response with few well-demarcated hypoesthetic plaques, thickened nerves, granulomas, and few bacilli. M. leprae grows best at cool temperatures (skin, peripheral nerves, nose, testes). It cannot be cultured on artificial media and has an armadillo reservoir in the southern US.",
  img="leprosy-ll.webp"),
Q(M, "Leprosy: treatment",
  "A patient with multibacillary leprosy starts treatment. Before starting, a G6PD level is checked because of one of the drugs. Which drug, and what toxicity is the concern?",
  ["Dapsone; hemolytic anemia and methemoglobinemia", "Rifampin; hepatitis", "Clofazimine; skin discoloration", "Isoniazid; peripheral neuropathy", "Ethambutol; optic neuritis"],
  "Multidrug therapy for multibacillary (lepromatous) leprosy is dapsone plus rifampin plus clofazimine for 12 months. Tuberculoid (paucibacillary) leprosy needs dapsone plus rifampin for 6 months, or the same three drugs per WHO. Dapsone is a folate synthesis inhibitor (like sulfonamides). It causes hemolysis in G6PD deficiency, methemoglobinemia, and agranulocytosis. Clofazimine causes red-brown skin discoloration. Erythema nodosum leprosum is treated with thalidomide or steroids."),
# ---------------- Mycoplasma ----------------
Q(X, "Mycoplasma: walking pneumonia",
  "A 19-year-old military recruit has 2 weeks of low-grade fever, headache, sore throat, and a persistent dry cough. He looks well, but CXR shows patchy bilateral interstitial infiltrates that look worse than the exam. His blood agglutinates when cooled to 4°C. Why is amoxicillin ineffective against the most likely organism?",
  ["It lacks a peptidoglycan cell wall", "It produces a carbapenemase", "It is an obligate intracellular organism that lacks ATP synthesis", "It has altered penicillin-binding proteins", "It has an outer membrane impermeable to β-lactams"],
  "Mycoplasma pneumoniae is the classic cause of atypical 'walking' pneumonia in young adults living close together (dorms, military, prisons). It has no cell wall, so β-lactams do not work and it is not seen on Gram stain. Its membrane contains sterols (cholesterol), and it grows on Eaton agar. Cold agglutinins are IgM against the I antigen on RBCs and can cause hemolytic anemia. Other findings: erythema multiforme, SJS, bullous myringitis. Treat with a macrolide, doxycycline, or fluoroquinolone."),
# ---------------- Gardnerella ----------------
Q(X, "Bacterial vaginosis",
  "A 27-year-old woman has a thin, gray-white vaginal discharge with a fishy odor that is stronger after intercourse. Vaginal pH is 5.0, and a whiff test with KOH is positive. The wet mount is shown. What is the appropriate treatment?",
  ["Metronidazole", "Fluconazole", "Ceftriaxone plus doxycycline", "Topical clotrimazole", "Oral penicillin"],
  "Bacterial vaginosis is an overgrowth of Gardnerella vaginalis and anaerobes that replaces H2O2-producing lactobacilli. The wet mount shows clue cells: vaginal epithelial cells covered with coccobacilli so their borders are blurred. Other findings: pH above 4.5, a fishy amine odor on KOH (whiff test), and little inflammation (few WBCs). Treat with oral or vaginal metronidazole or clindamycin. It raises the risk of preterm birth and PID. It is not a classic STI, and male partners are not treated.",
  img="clue-cells.webp"),
Q(X, "Vaginitis differential",
  "Which set of findings best describes Trichomonas vaginalis vaginitis?",
  ["Frothy yellow-green discharge, pH >4.5, 'strawberry' cervix, motile flagellated organisms on wet mount", "Thick white 'cottage cheese' discharge, pH <4.5, pseudohyphae on KOH", "Thin gray discharge, pH >4.5, clue cells, no inflammation", "Mucopurulent cervical discharge with intracellular diplococci", "Painful grouped vesicles on the vulva"],
  "Trichomoniasis is a sexually transmitted protozoan infection. It causes frothy yellow-green, foul-smelling discharge, itching, punctate cervical hemorrhages ('strawberry cervix'), and pH above 4.5. Motile trophozoites are seen on wet mount, and NAAT is most sensitive. Treat both patient and partners with metronidazole. Candida vaginitis has normal pH (<4.5) and pseudohyphae. BV has clue cells."),
# ---------------- Tropheryma whipplei ----------------
Q(X, "Whipple disease",
  "A 55-year-old white man has chronic diarrhea with steatorrhea, weight loss, migratory arthralgias, and memory problems. A duodenal biopsy is shown after periodic acid-Schiff (PAS) staining: the lamina propria is packed with foamy, PAS-positive macrophages. What is the most likely organism?",
  ["Tropheryma whipplei", "Giardia lamblia", "Mycobacterium avium complex", "Cryptosporidium parvum", "Yersinia enterocolitica"],
  "Whipple disease is caused by Tropheryma whipplei, a Gram-positive actinomycete. It most often affects older white men. The lamina propria fills with foamy PAS-positive, diastase-resistant macrophages, which block lymphatic drainage and cause malabsorption. Extraintestinal features: arthralgias, cardiac involvement (culture-negative endocarditis), and neurologic signs (oculomasticatory myorhythmia, dementia). Treat with IV ceftriaxone, then 1 year of TMP-SMX. MAC in AIDS also causes PAS-positive macrophages, but those are acid-fast.",
  img="whipple.webp"),
# ---------------- Haemophilus ducreyi ----------------
Q(X, "Chancroid",
  "A 26-year-old man who recently visited Southeast Asia has a painful, soft genital ulcer with ragged, undermined edges and a gray purulent base, plus a painful, fluctuant inguinal node. Gram stain shows Gram-negative coccobacilli in parallel chains ('school of fish'). What is the treatment?",
  ["Azithromycin single dose or ceftriaxone IM", "Benzathine penicillin G", "Acyclovir", "Doxycycline for 21 days", "Metronidazole"],
  "Chancroid (Haemophilus ducreyi) causes painful genital ulcers ('you do cry') with painful suppurative inguinal adenopathy. In contrast, syphilis causes a painless indurated chancre, LGV a painless transient ulcer then painful buboes, and donovanosis (Klebsiella granulomatis) painless beefy-red ulcers with Donovan bodies. HSV causes painful vesicles and shallow ulcers. Treat chancroid with azithromycin or ceftriaxone."),
]
