from qcore import Q
T = "Bacterial Structure, Genetics & Lab"
QUESTIONS = [
Q(T, "Endotoxin",
  "A 70-year-old man with E. coli pyelonephritis develops fever, hypotension, and DIC. Which statement about the bacterial molecule mainly responsible is correct?",
  ["Its lipid A component binds CD14/TLR4 on macrophages and is heat-stable", "It is a secreted protein toxin encoded on a plasmid", "It is highly antigenic and can be converted to a toxoid vaccine", "It is found in the cell wall of Gram-positive bacteria", "It acts as a superantigen that binds MHC II"],
  "Endotoxin (LPS) is part of the outer membrane of Gram-negative bacteria (cocci and rods). Lipid A is the toxic part: it binds LPS-binding protein, CD14, and TLR4/MD-2, triggering IL-1, IL-6, and TNF-α. This causes fever and shock. LPS also activates the alternative complement pathway (C3a, C5a) and tissue factor or factor XII (DIC). Endotoxin is heat-stable, weakly antigenic, and cannot be made into a toxoid. Exotoxins are secreted proteins, often encoded on phages or plasmids, highly antigenic, and heat-labile (with exceptions)."),
Q(T, "Gram-positive cell wall",
  "Which structure is present in Gram-positive but not Gram-negative bacteria, and induces TNF and IL-1 release via TLR2?",
  ["Lipoteichoic acid", "Lipopolysaccharide", "Periplasmic space", "Outer membrane porins", "O antigen"],
  "Gram-positive bacteria have a thick peptidoglycan layer with teichoic and lipoteichoic acids, which activate TLR2 and trigger cytokines. Gram-negatives have a thin peptidoglycan layer in a periplasmic space between the inner and outer membranes. The outer membrane contains LPS (lipid A, core, O antigen) and porins. In the Gram stain, the thin Gram-negative wall and lipid-rich outer membrane lose the crystal violet-iodine complex when alcohol is applied, so they take up the pink safranin counterstain."),
Q(T, "Organisms that stain poorly with Gram stain",
  "Which organism is not visualized well with a Gram stain, and why?",
  ["Mycoplasma pneumoniae, because it has no cell wall", "Staphylococcus aureus, because of its capsule", "Escherichia coli, because of its outer membrane", "Clostridium perfringens, because of spores", "Streptococcus pneumoniae, because of autolysins"],
  "'These Microbes May Lack Real Color': Treponema and Leptospira (too thin; use dark-field), Mycobacteria (mycolic acids; acid-fast stain), Mycoplasma (no cell wall; serology/PCR), Legionella (mostly intracellular; silver stain), Rickettsia (intracellular; Giemsa), Chlamydia (intracellular, no classic peptidoglycan; Giemsa or fluorescent antibody). Bartonella, Ehrlichia, Anaplasma, and Coxiella also stain poorly."),
Q(T, "Special stains",
  "Which pairing of stain and organism is correct?",
  ["India ink — Cryptococcus neoformans capsule", "Periodic acid-Schiff — Mycobacterium leprae", "Ziehl-Neelsen — Tropheryma whipplei", "Silver stain — Streptococcus pyogenes", "Congo red — Legionella pneumophila"],
  "Giemsa: Chlamydia, Borrelia, Rickettsia, trypanosomes, Plasmodium, Toxoplasma. PAS: glycogen and mucopolysaccharides (Tropheryma whipplei in macrophages). Ziehl-Neelsen (carbol fuchsin): mycobacteria, Nocardia (modified), Cryptosporidium oocysts. India ink: Cryptococcus capsule (mucicarmine stains it red in tissue). Silver stain: Helicobacter, Legionella, Bartonella, fungi (Pneumocystis, Candida). Fluorescent antibody: Legionella, Pneumocystis, Chlamydia."),
Q(T, "Special culture media",
  "Which pairing of organism and preferred culture medium is correct?",
  ["Bordetella pertussis — Bordet-Gengou or Regan-Lowe agar", "Legionella — Löwenstein-Jensen agar", "Mycobacterium tuberculosis — buffered charcoal yeast extract", "Corynebacterium diphtheriae — Eaton agar", "Fungi — thiosulfate-citrate-bile salts-sucrose agar"],
  "Media to know: H. influenzae — chocolate agar with factors V and X. N. gonorrhoeae/meningitidis — Thayer-Martin. B. pertussis — Bordet-Gengou (potato) or Regan-Lowe. C. diphtheriae — tellurite, Löffler. M. tuberculosis — Löwenstein-Jensen, Middlebrook. Mycoplasma — Eaton (cholesterol). Legionella — BCYE with cysteine and iron. Fungi — Sabouraud. Vibrio — TCBS. Lactose fermenters — MacConkey, EMB. E. coli O157:H7 — sorbitol MacConkey. Anaerobes — anaerobic blood agar."),
Q(T, "Transformation",
  "Encapsulated S. pneumoniae DNA is mixed with live, unencapsulated, avirulent pneumococci. When injected into mice, the mixture kills them, and virulent encapsulated bacteria are recovered. Adding DNase to the DNA first prevents this. Which process is shown?",
  ["Transformation", "Transduction", "Conjugation", "Transposition", "Lysogenic conversion"],
  "This is Griffith's experiment (with Avery's DNase control). Transformation is the uptake of naked DNA from the environment by competent bacteria and is blocked by DNase. Naturally competent organisms: S. pneumoniae, H. influenzae type b, Neisseria ('SHiN'). The same process spreads mosaic PBP genes that give pneumococcal penicillin resistance."),
Q(T, "Conjugation",
  "A plasmid encoding an extended-spectrum β-lactamase spreads from Klebsiella to E. coli in the gut of a hospitalized patient. The transfer requires direct cell-to-cell contact through a sex pilus. Which process is this?",
  ["Conjugation", "Transformation", "Generalized transduction", "Specialized transduction", "Recombination by homologous gene conversion"],
  "Conjugation transfers DNA through a sex pilus encoded by the F (fertility) factor. F+ × F− transfers a copy of the plasmid only. In Hfr cells the F factor has integrated into the chromosome, so chromosomal genes near the integration site can also move. Conjugation is the main way multidrug resistance plasmids (R plasmids) spread among Gram-negatives. It is not affected by DNase."),
Q(T, "Transduction",
  "During lytic infection, a bacteriophage accidentally packages a random fragment of host bacterial DNA instead of its own genome and delivers it to a new bacterium. How does this differ from specialized transduction?",
  ["Generalized transduction moves any host gene; specialized transduction moves only genes next to the prophage insertion site after faulty excision", "Generalized transduction requires a sex pilus", "Specialized transduction occurs only in the lytic cycle", "Generalized transduction moves only toxin genes", "There is no difference"],
  "Generalized transduction is a packaging error during the lytic cycle: any bacterial DNA can be carried. Specialized transduction happens in the lysogenic cycle when a prophage excises imprecisely and takes flanking bacterial genes with it. Phage-encoded toxin genes (diphtheria, cholera, botulinum, Shiga-like, erythrogenic) are transferred by lysogenic conversion."),
Q(T, "Transposons",
  "The vanA vancomycin resistance gene cluster is carried on a DNA segment that can jump from a plasmid into the bacterial chromosome or into other plasmids, with no homology required. What is this element?",
  ["Transposon", "Integron promoter", "Prophage", "F factor", "Episome requiring homologous recombination"],
  "Transposons are mobile elements flanked by inverted repeats. They encode transposase and move between DNA molecules without needing sequence homology. They can carry resistance genes (vanA on Tn1546) from plasmids to chromosomes and between species. Integrons gather resistance gene cassettes behind one promoter."),
Q(T, "Oxygen requirements",
  "An organism that grows only in the absence of oxygen causes a foul-smelling, gas-forming abscess. Why can't it survive in oxygen?",
  ["It lacks catalase and/or superoxide dismutase, so reactive oxygen species damage it", "It lacks cytochrome oxidase", "It requires CO2 for growth", "It has no ribosomes", "It lacks peptidoglycan"],
  "Obligate anaerobes (Clostridium, Bacteroides, Fusobacterium, Actinomyces, Cutibacterium) lack catalase and/or SOD and are killed by O2-derived radicals. They cause foul-smelling abscesses and gas. They are resistant to aminoglycosides, which need O2-dependent uptake. Obligate aerobes (Nocardia, Pseudomonas, Mycobacterium tuberculosis, Bacillus) need oxygen. Reactivation TB favors the oxygen-rich apices."),
Q(T, "Facultative intracellular bacteria",
  "Which organism can survive and replicate inside macrophages but can also be grown on artificial media, so it is a facultative (not obligate) intracellular pathogen?",
  ["Listeria monocytogenes", "Chlamydia trachomatis", "Rickettsia rickettsii", "Coxiella burnetii", "Ehrlichia chaffeensis"],
  "Facultative intracellular organisms ('Some Nasty Bugs May Live FacultativeLY'): Salmonella, Neisseria, Brucella, Mycobacterium, Listeria, Francisella, Legionella, Yersinia pestis. Control depends on cell-mediated immunity and granuloma formation. Obligate intracellular organisms (Rickettsia, Chlamydia, Coxiella, Ehrlichia, Anaplasma) cannot be grown on artificial media."),
Q(T, "Encapsulated bacteria & testing",
  "Adding type-specific anticapsular antiserum to a bacterial suspension makes the capsule appear swollen under the microscope. What is this test, and which statement about capsules is correct?",
  ["Quellung reaction; capsules block phagocytosis, and conjugate vaccines make capsules more immunogenic in children", "Elek test; capsules are toxin-producing structures", "CAMP test; capsules make organisms β-hemolytic", "Weil-Felix; capsules cross-react with Proteus antigens", "Coagulase test; capsules are made of fibrin"],
  "The quellung reaction identifies encapsulated organisms. Capsules are antiphagocytic, and IgG plus C3b opsonization overcomes them. Encapsulated organisms: S. pneumoniae, H. influenzae type b, N. meningitidis, E. coli K1, Salmonella, Klebsiella, group B strep, Cryptococcus. The spleen is critical for clearing them, so asplenic patients need vaccines (PCV/PPSV, Hib, MenACWY/MenB)."),
Q(T, "Type III secretion",
  "Several Gram-negative pathogens use a needle-like 'injectisome' to deliver effector proteins directly into host cell cytoplasm. Which group of organisms has this system?",
  ["Salmonella, Shigella, Yersinia, Pseudomonas, and E. coli (EPEC/EHEC)", "Streptococcus pneumoniae and Staphylococcus aureus", "Mycoplasma and Ureaplasma", "Clostridium tetani and Clostridium botulinum", "Treponema and Borrelia"],
  "Type III secretion systems ('injectisomes') are found in Gram-negative pathogens including Pseudomonas, Salmonella, Shigella, Yersinia, Vibrio, Chlamydia, and E. coli. They deliver effectors that alter host cytoskeleton, block phagocytosis, and induce apoptosis. Yersinia Yops, Salmonella SPI-1 invasion proteins, and EPEC Tir are examples. Gram-positive bacteria lack this system."),
Q(T, "Bacterial growth curve",
  "A bacterial culture passes through lag, exponential (log), stationary, and death phases. During which phase are β-lactam antibiotics most effective, and during which phase do Bacillus and Clostridium begin to form spores?",
  ["Log phase; stationary phase", "Lag phase; log phase", "Stationary phase; lag phase", "Death phase; log phase", "Log phase; lag phase"],
  "In log phase, bacteria are actively dividing and building cell walls, so β-lactams work best. In stationary phase, nutrients are depleted and growth equals death. Spore formation (sporulation) starts here in Bacillus and Clostridium, and the large, slow-growing inocula of deep infections explain penicillin's reduced effect (Eagle effect)."),
Q(T, "Exotoxin mechanisms: cAMP",
  "Which two bacterial toxins both raise intracellular cAMP, but by different mechanisms?",
  ["Cholera toxin (ADP-ribosylates Gs, keeping it on) and pertussis toxin (ADP-ribosylates Gi, turning off inhibition)", "Diphtheria toxin and Pseudomonas exotoxin A", "Tetanospasmin and botulinum toxin", "Shiga toxin and Shiga-like toxin", "Streptolysin O and α-toxin of C. perfringens"],
  "Cholera toxin and ETEC heat-labile toxin ADP-ribosylate Gs, keeping adenylyl cyclase on. Pertussis toxin ADP-ribosylates Gi, removing inhibition. Anthrax edema factor and B. pertussis adenylate cyclase toxin are adenylyl cyclases themselves. Diphtheria toxin and exotoxin A inactivate EF-2. Tetanus and botulinum toxins are proteases that cleave SNAREs. Shiga toxins cleave 28S rRNA."),
Q(T, "Superantigens",
  "Which organisms make toxins that act as superantigens?",
  ["Staphylococcus aureus (TSST-1, enterotoxins) and Streptococcus pyogenes (pyrogenic exotoxins)", "Clostridium tetani and Clostridium botulinum", "Vibrio cholerae and enterotoxigenic E. coli", "Bacillus anthracis and Bordetella pertussis", "Corynebacterium diphtheriae and Pseudomonas aeruginosa"],
  "Superantigens bind outside the peptide groove of MHC II and cross-link it to the TCR Vβ region. This activates many T cells at once and triggers a cytokine storm (IL-2, IFN-γ, TNF). Causes: S. aureus TSST-1 (toxic shock syndrome), staphylococcal enterotoxins (food poisoning; they also act on the vagus nerve), and S. pyogenes SpeA and SpeC (scarlet fever, streptococcal toxic shock)."),
Q(T, "Pigment producers",
  "Which pairing of organism and pigment is correct?",
  ["Serratia marcescens — red", "Actinomyces israelii — blue-green", "Pseudomonas aeruginosa — golden yellow", "Staphylococcus aureus — red", "Aspergillus fumigatus — yellow sulfur granules"],
  "Pigment producers: Actinomyces israelii — yellow 'sulfur' granules. S. aureus — golden yellow (staphyloxanthin, an antioxidant). P. aeruginosa — blue-green (pyocyanin, pyoverdine). Serratia marcescens — red (prodigiosin), a cause of UTIs and pneumonia in hospitalized patients. Aspergillus niger — black mold."),
Q(T, "Bacterial virulence: IgA protease",
  "Which group of organisms makes IgA protease to colonize mucosal surfaces?",
  ["Streptococcus pneumoniae, Haemophilus influenzae type b, and Neisseria", "Staphylococcus aureus and Streptococcus pyogenes", "Escherichia coli and Klebsiella", "Clostridium perfringens and Clostridium difficile", "Mycobacterium tuberculosis and Nocardia"],
  "'SHiN' organisms make IgA protease: S. pneumoniae, H. influenzae type b, and Neisseria (gonorrhoeae and meningitidis). IgA protease cleaves secretory IgA1 at the hinge. These same organisms are also naturally transformable. Other virulence factors: protein A (S. aureus), M protein (GAS), and type III secretion systems (Gram-negatives)."),
Q(T, "Spores & heat resistance",
  "Which is the core component that helps bacterial endospores resist heat?",
  ["Dipicolinic acid complexed with calcium", "Lipid A", "Mycolic acid", "Teichoic acid", "Hyaluronic acid"],
  "Endospores form under nutrient stress. They have a keratin-like coat and a dehydrated core with calcium dipicolinate. They survive boiling, drying, and chemicals, and have no metabolic activity. Autoclaving (121°C, 15 min) kills them. Spore-forming organisms: Bacillus anthracis, B. cereus, Clostridium (tetani, botulinum, perfringens, difficile), and Coxiella burnetii (spore-like form)."),
Q(T, "Catalase-positive organisms",
  "A child with recurrent infections is suspected of having chronic granulomatous disease. Which organisms would be typical infections?",
  ["Staphylococcus aureus, Serratia, Nocardia, Burkholderia cepacia, and Aspergillus", "Streptococcus pyogenes and Streptococcus pneumoniae", "Neisseria meningitidis and Neisseria gonorrhoeae", "Pneumocystis and Cryptococcus", "Enteroviruses and herpesviruses"],
  "In CGD, NADPH oxidase is deficient. Catalase-positive organisms destroy the H2O2 that phagocytes could otherwise borrow to make bleach. Typical pathogens: S. aureus, Serratia, Nocardia, Burkholderia cepacia, and Aspergillus ('Cats Need PLACESS': Pseudomonas, Listeria, Aspergillus, Candida, E. coli, S. aureus, Serratia, Nocardia, Burkholderia). Treatment includes TMP-SMX and itraconazole prophylaxis and IFN-γ."),
]
