from qcore import Q
H = "Herpesviruses"
D = "DNA Viruses (Non-Herpes)"
QUESTIONS = [
# ---------------- HSV ----------------
Q(H, "HSV-1: latency",
  "A 20-year-old woman gets painful grouped vesicles on the lip, shown, every time she has a sunburn or a stressful exam. Between episodes she has no lesions. Where does the virus reside between outbreaks?",
  ["Trigeminal ganglion sensory neurons", "Oral epithelial basal cells", "B lymphocytes", "Salivary gland ductal cells", "Monocytes and macrophages"],
  "HSV-1 infects mucosal epithelium, then travels retrograde along sensory axons to the trigeminal ganglion, where it stays latent as an episome. Stress, UV light, fever, or immunosuppression cause reactivation. The virus travels back down the axon to the same site, giving recurrent herpes labialis. HSV-2 usually becomes latent in sacral ganglia (genital herpes). EBV is latent in B cells, CMV in monocytes, and HHV-8 in B cells and endothelium.",
  img="herpes-labialis.webp"),
Q(H, "Tzanck smear",
  "Scrapings from the base of an unroofed vesicle are stained with Giemsa, shown. Which viruses produce this finding?",
  ["HSV-1, HSV-2, and VZV", "EBV and CMV", "Molluscum contagiosum virus", "Coxsackievirus A", "Measles virus"],
  "A Tzanck smear shows multinucleated giant cells with molded nuclei and intranuclear (Cowdry A) inclusions. These are typical of HSV-1, HSV-2, and VZV infection. It cannot tell them apart and is insensitive, so PCR of vesicle fluid is now preferred. Measles also forms multinucleated giant cells (Warthin-Finkeldey) in lymphoid tissue and lung.",
  img="tzanck.webp"),
Q(H, "HSV encephalitis",
  "A 35-year-old man has fever, confusion, personality change, and olfactory hallucinations. MRI shows edema of the right temporal lobe. CSF shows a lymphocytic pleocytosis with red blood cells. What is the most appropriate treatment?",
  ["IV acyclovir", "IV ceftriaxone and vancomycin", "Oral valacyclovir", "IV ganciclovir", "Supportive care; the condition is self-limited"],
  "HSV-1 is the most common cause of sporadic fatal encephalitis. It is a hemorrhagic necrotizing encephalitis of the temporal lobes, with RBCs in the CSF. Diagnose with CSF HSV PCR. Start empiric IV acyclovir immediately, because delay increases death and disability. Survivors may have memory loss and Klüver-Bucy-like features."),
Q(H, "Acyclovir mechanism",
  "Acyclovir is effective against HSV and VZV but has little effect on uninfected host cells. Which property explains this selectivity?",
  ["It must first be monophosphorylated by viral thymidine kinase, and then acts as a chain terminator of viral DNA polymerase", "It binds viral neuraminidase", "It inhibits viral uncoating in endosomes", "It blocks host ribonucleotide reductase", "It is a pyrophosphate analog that needs no activation"],
  "Acyclovir and valacyclovir (the prodrug), famciclovir, and penciclovir are guanosine analogs. Viral TK adds the first phosphate, and host kinases add the next two. The triphosphate inhibits viral DNA polymerase and terminates the chain. The drug is inactive against latent virus. Resistance usually comes from TK mutations, treated with foscarnet (a pyrophosphate analog that needs no activation). Toxicity: crystalline nephropathy, so keep patients well hydrated. CMV lacks TK; ganciclovir is phosphorylated by CMV UL97 kinase."),
Q(H, "Neonatal HSV",
  "A 38-week pregnant woman has painful vesicles on her vulva for the first time. She has no history of genital herpes. What is the most appropriate management at delivery?",
  ["Cesarean delivery to reduce the risk of neonatal HSV", "Vaginal delivery with neonatal erythromycin eye ointment", "Vaginal delivery; primary infection carries minimal risk", "Induce labor immediately", "Give HSV immune globulin to the neonate"],
  "Neonatal HSV is usually caught during delivery through an infected birth canal. The risk is highest with a primary maternal infection near term, because there is a lot of virus and no protective maternal IgG. Active lesions or prodromal symptoms at labor call for cesarean delivery. Suppressive acyclovir from 36 weeks is used for women with recurrent herpes. Neonatal HSV can be localized (skin, eyes, mouth), CNS, or disseminated, and is treated with IV acyclovir."),
# ---------------- VZV ----------------
Q(H, "Varicella",
  "An unvaccinated 6-year-old has fever and an itchy rash that started on the face and trunk and spread to the limbs. Lesions are in different stages at once — macules, papules, vesicles, and crusts — as shown. Which statement about this infection is correct?",
  ["It spreads by respiratory droplets and aerosols, and the virus becomes latent in dorsal root ganglia", "Lesions all appear at the same stage and are concentrated on the extremities", "It is caused by a poxvirus that replicates in the cytoplasm", "Aspirin is the preferred antipyretic", "Adults have milder disease than children"],
  "Chickenpox (primary VZV) spreads by aerosols and contact with lesions. It is contagious from about 2 days before the rash until all lesions crust. Crops of lesions in different stages ('dewdrops on a rose petal') start centrally. Smallpox, in contrast, has lesions all at the same stage that are denser on the face and limbs. Complications: bacterial skin superinfection (S. pyogenes, S. aureus), pneumonia (worse in adults and pregnancy), encephalitis/cerebellitis, and Reye syndrome with aspirin. Prevent with the live attenuated vaccine. VariZIG is used for exposed high-risk people.",
  img="varicella.webp"),
Q(H, "Herpes zoster",
  "A 72-year-old man has had burning pain for 3 days on one side of his neck and shoulder, followed by the grouped vesicles in a band shown. What is the pathogenesis, and which vaccine would have lowered his risk?",
  ["Reactivation of VZV latent in a dorsal root ganglion; recombinant adjuvanted glycoprotein E vaccine", "Primary infection with HSV-2; no vaccine exists", "Reactivation of HSV-1 in the trigeminal ganglion; live attenuated vaccine", "Coxsackievirus infection of sensory neurons; inactivated vaccine", "Autoimmune vasculitis; no vaccine exists"],
  "Shingles is VZV reactivation from a sensory ganglion as cell-mediated immunity wanes with age or immunosuppression. It causes a painful dermatomal vesicular rash that does not cross the midline. Complications: postherpetic neuralgia, zoster ophthalmicus (V1; Hutchinson sign on the nose tip predicts eye involvement), Ramsay Hunt syndrome (facial palsy, ear vesicles), and dissemination. Recombinant zoster vaccine (Shingrix), a 2-dose non-live vaccine, is recommended for all adults 50 and older and immunocompromised adults 19 and older. Treat within 72 hours with valacyclovir or famciclovir.",
  img="zoster.webp"),
# ---------------- EBV ----------------
Q(H, "EBV: infectious mononucleosis",
  "A 17-year-old has fever, exudative pharyngitis, posterior cervical lymphadenopathy, fatigue, and splenomegaly. Peripheral smear shows many large lymphocytes with abundant cytoplasm that scallops around neighboring RBCs. What are these atypical lymphocytes?",
  ["Reactive cytotoxic CD8+ T cells responding to infected B cells", "EBV-infected B cells", "Neoplastic Reed-Sternberg cells", "Plasma cells producing heterophile antibodies", "Virus-infected monocytes"],
  "EBV enters B cells through CD21 (complement receptor 2), which binds viral gp350. The atypical lymphocytes (Downey cells) are reactive CD8+ T cells attacking infected B cells. Heterophile antibodies (Monospot, which agglutinates sheep or horse RBCs) are positive in most adolescents and adults. Avoid contact sports for at least 3–4 weeks because of splenic rupture risk. Amoxicillin causes a rash. CMV causes a heterophile-negative mono-like illness."),
Q(H, "EBV: malignancies",
  "A 7-year-old boy from equatorial Africa has a rapidly enlarging jaw mass. Biopsy shows a 'starry sky' pattern of monomorphic B cells with a high proliferation index and t(8;14). Which virus is associated with this tumor and with nasopharyngeal carcinoma?",
  ["Epstein-Barr virus", "Human herpesvirus 8", "Human papillomavirus type 16", "HTLV-1", "Hepatitis B virus"],
  "EBV-associated cancers: endemic Burkitt lymphoma (jaw, t(8;14) c-MYC), nasopharyngeal carcinoma (southern China, North Africa), Hodgkin lymphoma (mixed cellularity), post-transplant lymphoproliferative disorder, primary CNS lymphoma in AIDS, and some gastric carcinomas. EBV also causes oral hairy leukoplakia in HIV (white, corrugated plaques on the lateral tongue that cannot be scraped off). HTLV-1 causes adult T-cell leukemia/lymphoma."),
# ---------------- CMV ----------------
Q(H, "CMV: congenital",
  "A newborn is small for gestational age with petechiae ('blueberry muffin' rash), hepatosplenomegaly, and microcephaly. Head CT shows periventricular calcifications. Tissue from an affected infant, shown, contains enlarged cells with large intranuclear inclusions surrounded by a clear halo. What is the most likely long-term complication?",
  ["Sensorineural hearing loss", "Patent ductus arteriosus", "Hutchinson teeth", "Chorioretinitis with hydrocephalus from a protozoan", "Limb hypoplasia and cicatricial skin scars"],
  "Congenital CMV is the most common congenital infection and the leading non-genetic cause of sensorineural hearing loss. Infected cells are cytomegalic with 'owl's eye' intranuclear inclusions. Classic findings: periventricular calcifications, microcephaly, chorioretinitis, and hepatosplenomegaly. Congenital toxoplasmosis has diffuse or basal ganglia calcifications and hydrocephalus. Congenital rubella causes PDA, cataracts, and deafness. Congenital varicella causes limb hypoplasia and scars. Treat symptomatic newborns with valganciclovir.",
  img="cmv-owl.webp"),
Q(H, "CMV: immunocompromised",
  "A man with AIDS and a CD4 count of 30/μL reports 'floaters' and blurred vision. Fundoscopy shows fluffy yellow-white retinal lesions with hemorrhage ('pizza pie'). He is started on ganciclovir. Which toxicity is most likely, and what enzyme activates the drug?",
  ["Neutropenia (bone marrow suppression); CMV UL97 protein kinase", "Nephrotoxicity; viral thymidine kinase", "Hypocalcemia and seizures; no activation needed", "Hemolytic anemia; host adenosine deaminase", "Lactic acidosis; reverse transcriptase"],
  "CMV retinitis occurs at CD4 below 50. CMV also causes colitis, esophagitis (linear ulcers), and pneumonitis in transplant patients. Ganciclovir (IV) and valganciclovir (oral prodrug) are phosphorylated by CMV UL97 kinase, then by host kinases, and inhibit viral DNA polymerase. Toxicity: myelosuppression (leukopenia, neutropenia, thrombocytopenia). For resistant CMV, foscarnet (nephrotoxic, causes electrolyte disturbances and seizures) and cidofovir (nephrotoxic, give with probenecid) do not need viral kinase activation."),
# ---------------- HHV-6 / HHV-8 ----------------
Q(H, "HHV-6: roseola",
  "A 10-month-old has 3 days of fever to 40°C with a brief febrile seizure. When the fever breaks, a rose-pink maculopapular rash appears on the trunk and spreads to the face. The child now looks well. What is the most likely cause?",
  ["Human herpesvirus 6", "Measles virus", "Parvovirus B19", "Rubella virus", "Group A Streptococcus"],
  "Roseola infantum (exanthem subitum, sixth disease) is caused by HHV-6, and less often HHV-7. It affects children 6 months to 2 years. Several days of high fever, which can cause febrile seizures, are followed by a rash that appears after the fever resolves. The virus stays latent in T cells."),
Q(H, "HHV-8: Kaposi sarcoma",
  "A 40-year-old man with untreated HIV has multiple violaceous plaques and nodules on his legs and trunk, as shown. Biopsy shows spindle cells forming slit-like vascular spaces with extravasated RBCs. Which statement about the virus is correct?",
  ["It is HHV-8, transmitted sexually and through saliva, and also causes primary effusion lymphoma and multicentric Castleman disease", "It is EBV, which infects B cells via CD21", "It is HPV, which inactivates p53 with E6", "It is Bartonella, a bacterium treated with erythromycin", "It is HTLV-1, which causes adult T-cell leukemia"],
  "Kaposi sarcoma is a vascular tumor of lymphatic endothelial origin driven by HHV-8 (KSHV). Latency proteins such as LANA (latency-associated nuclear antigen) inactivate p53. It occurs in AIDS (often MSM), transplant recipients, older Mediterranean men, and in Africa. HHV-8 also causes primary effusion lymphoma and multicentric Castleman disease. Treat with ART and, if needed, chemotherapy. Bacillary angiomatosis looks similar but has neutrophils.",
  img="kaposi.webp"),
Q(H, "Herpesvirus structure",
  "Which feature is shared by all human herpesviruses?",
  ["Enveloped, linear dsDNA viruses that acquire their envelope from the nuclear membrane and establish latency", "Non-enveloped ssDNA viruses", "Enveloped RNA viruses that replicate in the cytoplasm", "Circular dsDNA viruses with reverse transcriptase", "Naked icosahedral viruses resistant to detergents"],
  "Herpesviruses (HSV-1, HSV-2, VZV, EBV, CMV, HHV-6, HHV-7, HHV-8) are enveloped, icosahedral, linear dsDNA viruses. They replicate in the nucleus and bud from the nuclear membrane. All establish lifelong latency. Because they are enveloped, they are sensitive to drying and detergents and spread by close contact (saliva, sexual contact, transplacental, transplant)."),
# ---------------- Parvovirus B19 ----------------
Q(D, "Parvovirus B19",
  "A 6-year-old has bright red cheeks and a lacy, reticular rash on the arms and trunk, as shown, after a mild febrile illness. His 9-year-old brother has sickle cell disease. Which complication should the brother be monitored for if infected?",
  ["Transient aplastic crisis from infection of erythroid precursors", "Acute chest syndrome caused directly by the virus", "Splenic sequestration from immune complexes", "Osteomyelitis", "Hemolytic uremic syndrome"],
  "Parvovirus B19 is the smallest DNA virus: non-enveloped and single-stranded. It uses the P blood group antigen (globoside) to enter erythroid progenitors in the bone marrow, where it replicates and lyses them. In children it causes erythema infectiosum ('slapped cheek', fifth disease). The rash appears once the child is no longer contagious. In adults it causes symmetric arthritis. With chronic hemolysis (sickle cell, hereditary spherocytosis) it causes aplastic crisis. In pregnancy it causes hydrops fetalis. In the immunocompromised it causes chronic pure red cell aplasia.",
  img="fifth.webp"),
# ---------------- HPV ----------------
Q(D, "HPV: oncogenesis",
  "A 32-year-old woman's cervical biopsy shows high-grade squamous intraepithelial lesion with koilocytes (squamous cells with wrinkled nuclei and perinuclear clearing). HPV type 16 is detected. What is the mechanism of oncogenesis?",
  ["E6 promotes degradation of p53 and E7 binds and inactivates Rb", "E6 binds Rb and E7 activates telomerase only", "The virus inserts an oncogene next to c-MYC", "The virus encodes a viral cyclin that activates CDK6", "LANA inactivates p53"],
  "High-risk HPV (16, 18, 31, 33) integrates into the host genome. E6 recruits E6AP to ubiquitinate p53 for degradation, and E7 binds Rb and frees E2F to drive the cell cycle. HPV causes cervical, anal, penile, vulvar, and oropharyngeal squamous cell carcinomas. Low-risk types 6 and 11 cause condylomata acuminata and laryngeal papillomas. The 9-valent vaccine uses L1 capsid virus-like particles (no DNA) and is recommended at 9–12 years, up to age 26 (shared decision-making to 45)."),
Q(D, "HPV: warts",
  "A 25-year-old man has multiple soft, cauliflower-like, skin-colored papules on the penile shaft. Which HPV types most often cause these lesions?",
  ["Types 6 and 11", "Types 16 and 18", "Types 1 and 2 only", "Type 31 only", "Types 45 and 52 only"],
  "Condylomata acuminata (anogenital warts) are caused by low-risk HPV 6 and 11. These types also cause recurrent respiratory papillomatosis in children infected at birth. Common warts (verruca vulgaris) and plantar warts come from types 1, 2, and 4. Condylomata lata of secondary syphilis are flat and moist, not cauliflower-like. Treatments include imiquimod, podophyllotoxin, cryotherapy, and excision."),
# ---------------- Poxviruses ----------------
Q(D, "Molluscum contagiosum",
  "A 5-year-old has many small, pearly, dome-shaped papules with central umbilication on her trunk. A biopsy is shown, with large eosinophilic intracytoplasmic inclusions. Which feature of the causative virus is unique among DNA viruses?",
  ["It replicates in the cytoplasm and carries its own DNA-dependent RNA polymerase", "It has a single-stranded genome", "It uses reverse transcriptase", "It is non-enveloped", "It is a circular genome that integrates into host DNA"],
  "Molluscum contagiosum is a poxvirus. Poxviruses are the largest DNA viruses and the only ones that replicate in the cytoplasm, so they bring their own transcription machinery. The lesions contain molluscum bodies (Henderson-Patterson bodies). Spread is by skin contact, fomites, or sexually in adults. Extensive or giant lesions suggest HIV. Other poxviruses: variola (smallpox), vaccinia, and monkeypox (mpox).",
  img="molluscum.webp"),
Q(D, "Smallpox vs chickenpox",
  "A health official is taught to tell smallpox from chickenpox using the historical photograph shown. Which finding favors smallpox?",
  ["Deep, firm pustules all at the same stage, concentrated on the face and extremities including palms and soles", "Superficial vesicles in different stages at the same time", "A rash concentrated on the trunk", "Lesions that crust within 24 hours", "Mild prodrome with low-grade fever"],
  "Smallpox (variola) has a severe febrile prodrome, then a centrifugal rash (face and limbs, including palms and soles). Deep, firm, synchronous lesions progress together from macule to papule to vesicle to pustule to scab. Varicella is centripetal, with superficial lesions in different stages. Smallpox was eradicated in 1980 by vaccinia vaccination. Tecovirimat inhibits orthopoxvirus envelope protein p37.",
  img="smallpox.webp"),
# ---------------- Adenovirus ----------------
Q(D, "Adenovirus",
  "Several children who swam in the same pool develop fever, sore throat, and bilateral red, watery conjunctivitis. What is the most likely cause, and why does it resist disinfection?",
  ["Adenovirus; it is a non-enveloped dsDNA virus", "Enterovirus 70; it is an enveloped RNA virus", "HSV-1; it is an enveloped dsDNA virus", "Chlamydia trachomatis; it forms elementary bodies", "Measles virus; it is a paramyxovirus"],
  "Adenovirus is a non-enveloped, linear dsDNA virus with fibers on its capsid. It resists drying and inadequate chlorination. It causes pharyngoconjunctival fever (pools), epidemic keratoconjunctivitis, febrile pharyngitis, pneumonia (outbreaks in military recruits, who receive an oral vaccine), acute hemorrhagic cystitis, gastroenteritis (types 40/41), and myocarditis. It is serious in transplant recipients and treated with cidofovir."),
# ---------------- Polyomavirus ----------------
Q(D, "JC virus: PML",
  "A 45-year-old woman with relapsing multiple sclerosis on natalizumab develops progressive hemiparesis, visual field loss, and cognitive decline over weeks. MRI shows asymmetric, non-enhancing white matter lesions without mass effect. What is the diagnosis?",
  ["Progressive multifocal leukoencephalopathy from JC virus infection of oligodendrocytes", "HSV encephalitis", "Primary CNS lymphoma from EBV", "Toxoplasma encephalitis", "Subacute sclerosing panencephalitis"],
  "JC polyomavirus (non-enveloped, circular dsDNA) reactivates with severe immunosuppression: AIDS with CD4 below 200, and drugs such as natalizumab (anti-α4 integrin) and rituximab. It kills oligodendrocytes, causing demyelination. There is no specific antiviral, so treatment is immune reconstitution (ART, stopping the drug). BK polyomavirus causes nephropathy and hemorrhagic cystitis in kidney and bone marrow transplant recipients."),
Q(D, "DNA virus rules",
  "Which statement about DNA viruses is correct?",
  ["All are double-stranded except parvovirus, and all replicate in the nucleus except poxviruses", "All are enveloped", "All are single-stranded and circular", "All replicate in the cytoplasm", "None can establish latency"],
  "DNA virus rules: all are dsDNA except Parvoviridae (ssDNA, 'part of a virus'). All are linear except papilloma-, polyoma-, and hepadnaviruses (circular). All are icosahedral except poxviruses (complex). All replicate in the nucleus except poxviruses. Families: Herpes-, Hepadna- (HBV), Adeno-, Parvo-, Papilloma-, Polyoma-, and Poxviruses ('HHAPPPPy'). Naked (non-enveloped) DNA viruses: papilloma, adeno, parvo, polyoma."),
Q(D, "Viral envelope & transmission",
  "A virus is resistant to ether, bile, and drying, and spreads efficiently by the fecal-oral route. Which structural feature most likely explains this?",
  ["It lacks a lipid envelope (naked capsid)", "It has a helical nucleocapsid", "It has a segmented genome", "It buds from the plasma membrane", "It has a positive-sense RNA genome"],
  "Enveloped viruses carry a host-derived lipid membrane that detergents, bile, and drying destroy, so they need close contact (respiratory, sexual, blood). Naked viruses (picornaviruses, caliciviruses such as norovirus, reoviruses such as rotavirus, hepatitis A and E, adenovirus, papilloma, parvo, polyoma) survive in the environment and the GI tract and spread fecal-orally or by fomites. Mnemonic for naked RNA viruses: 'Naked CPR and hepEAtitis' (Calici, Picorna, Reo, Hepevirus/HEV, HAV)."),
]
