from qcore import Q
T = "RNA Viruses"
QUESTIONS = [
# ---------------- Picornaviruses ----------------
Q(T, "Coxsackie A: hand-foot-mouth",
  "A 2-year-old in daycare has low-grade fever, painful oral ulcers, and vesicles on the palms, soles, and around the mouth, as shown. Several classmates are sick. What type of virus causes this?",
  ["A non-enveloped, positive-sense ssRNA picornavirus", "An enveloped dsDNA herpesvirus", "A non-enveloped ssDNA parvovirus", "An enveloped negative-sense paramyxovirus", "A segmented dsRNA reovirus"],
  "Hand-foot-and-mouth disease is caused mainly by coxsackievirus A16 and enterovirus 71. These are enteroviruses (Picornaviridae): small, naked, positive-sense ssRNA viruses spread fecal-orally and by respiratory secretions, peaking in summer and fall. Coxsackie A also causes herpangina (posterior pharyngeal vesicles). Coxsackie B causes myocarditis and pericarditis, pleurodynia (Bornholm disease), and aseptic meningitis. Picornaviruses: Poliovirus, Echovirus, Rhinovirus, Coxsackievirus, HAV ('PERCH').",
  img="hfmd.jpg"),
Q(T, "Poliovirus",
  "An unvaccinated 8-year-old in Afghanistan has fever, then sudden asymmetric flaccid paralysis of the right leg with absent reflexes and intact sensation. Which cells does the virus destroy?",
  ["Anterior horn motor neurons of the spinal cord", "Dorsal root ganglion sensory neurons", "Schwann cells of peripheral nerves", "Neuromuscular junction acetylcholine receptors", "Upper motor neurons in the corticospinal tract"],
  "Poliovirus multiplies in the oropharynx and Peyer patches, spreads through the blood, and in a small share of infections kills anterior horn cells. This causes asymmetric flaccid (lower motor neuron) paralysis with areflexia and fasciculations and no sensory loss. CSF shows lymphocytosis. The US uses inactivated (Salk) IPV, which gives IgG but less gut IgA. Oral live attenuated (Sabin) OPV gives mucosal IgA and herd immunity but can rarely revert and cause vaccine-derived paralysis."),
Q(T, "Rhinovirus",
  "The most common cause of the common cold grows best at 33°C and does not survive the stomach. Which property explains why it does not cause gastroenteritis, unlike other picornaviruses?",
  ["It is acid-labile", "It is enveloped", "It has a DNA genome", "It binds CD4", "It has a segmented genome"],
  "Rhinoviruses are picornaviruses that bind ICAM-1 on respiratory epithelium. They grow best at cooler nasal temperatures and are acid-labile, so they are destroyed in the stomach. There are over 100 serotypes, so there is no vaccine and reinfections are common. Enteroviruses (polio, coxsackie, echo) are acid-stable and replicate in the gut."),
Q(T, "Enteroviral meningitis",
  "In late August, a 20-year-old has headache, fever, photophobia, and neck stiffness. CSF shows 150 WBC/μL (mostly lymphocytes), normal glucose, and mildly elevated protein. What is the most common cause of this syndrome?",
  ["Enteroviruses (echovirus, coxsackievirus)", "Neisseria meningitidis", "HSV-1", "Cryptococcus neoformans", "Mycobacterium tuberculosis"],
  "Aseptic (viral) meningitis shows lymphocytic pleocytosis, normal glucose, and normal or slightly elevated protein. Enteroviruses cause most cases, peaking in summer and fall. Other causes: HSV-2 (can recur as Mollaret meningitis), VZV, mumps, HIV, arboviruses, and LCMV. Bacterial meningitis shows neutrophils, low glucose, and high protein. TB and fungal meningitis show lymphocytes with low glucose and high protein."),
# ---------------- Calicivirus / Reovirus ----------------
Q(T, "Norovirus",
  "Hundreds of passengers on a cruise ship develop sudden nausea, projectile vomiting, and watery diarrhea lasting 1–2 days. Alcohol-based hand sanitizers have not stopped the spread. What is the most likely cause?",
  ["Norovirus", "Rotavirus", "Enterotoxigenic E. coli", "Giardia lamblia", "Hepatitis A virus"],
  "Norovirus (Caliciviridae, naked positive-sense ssRNA) is the most common cause of viral gastroenteritis in adults and of outbreaks in closed settings (cruise ships, nursing homes, schools). The infectious dose is very low. It survives on surfaces and resists alcohol. Soap and water and bleach cleaners are needed. Immunity is short-lived and strain-specific. It damages small intestinal villi (brush border)."),
Q(T, "Rotavirus",
  "A 9-month-old unvaccinated infant in winter has vomiting, fever, and profuse watery diarrhea causing dehydration. Stool antigen testing finds a non-enveloped, segmented, double-stranded RNA virus. Which rare adverse effect is associated with the oral vaccine that prevents it?",
  ["Intussusception", "Guillain-Barré syndrome", "Febrile seizures", "Vaccine-derived paralysis", "Aseptic meningitis"],
  "Rotavirus (Reoviridae: naked, segmented dsRNA — 'Rotavirus = Right out the Anus') is the leading cause of severe dehydrating diarrhea in young children worldwide. It destroys villous tips, causing malabsorption. The live oral vaccines (RotaTeq, Rotarix) carry a small risk of intussusception, so they must start before 15 weeks and finish by 8 months. The segmented genome allows reassortment."),
# ---------------- Flaviviruses ----------------
Q(T, "Dengue",
  "A 25-year-old returns from Puerto Rico with high fever, severe retro-orbital headache, and intense joint and muscle pain ('breakbone fever'). Labs show leukopenia and thrombocytopenia, and a tourniquet test is positive. She had dengue 3 years ago. Why is her risk of severe dengue higher now?",
  ["Non-neutralizing antibodies from a prior serotype increase viral entry into Fc receptor–bearing cells (antibody-dependent enhancement)", "Her first infection made her immune to all serotypes", "The virus has become resistant to interferon", "Prior infection left latent virus in her liver", "Her first infection destroyed her platelets permanently"],
  "Dengue (flavivirus, carried by Aedes aegypti mosquitoes) has 4 serotypes. A second infection with a different serotype carries a higher risk of severe dengue (hemorrhage, plasma leakage, shock). Cross-reactive, non-neutralizing IgG binds the virus and helps it enter monocytes through Fc receptors (antibody-dependent enhancement). Treatment is supportive. Avoid NSAIDs and aspirin. The vaccine is used only in people with documented prior infection."),
Q(T, "Yellow fever",
  "A traveler returning from the Amazon has fever, jaundice, black vomit, and bleeding. Liver biopsy shows midzonal necrosis with eosinophilic apoptotic hepatocytes. Which statement about this infection is correct?",
  ["It is a flavivirus spread by Aedes mosquitoes, and a live attenuated vaccine is available", "It is a filovirus spread by bats and primates", "It is a bunyavirus spread by rodent urine", "It is a hepatitis virus spread by the fecal-oral route", "It is a DNA virus that replicates in hepatocyte nuclei"],
  "Yellow fever (flavivirus, Aedes aegypti) has a jungle cycle with monkeys and an urban cycle with humans. Severe cases cause hepatitis (jaundice), hemorrhage (black vomit), and kidney failure. The liver shows Councilman bodies (apoptotic hepatocytes). Prevent it with the live attenuated 17D vaccine, which is required for travel to endemic areas and contraindicated in severe immunosuppression and infants under 6 months."),
Q(T, "West Nile virus",
  "A 68-year-old man in Colorado in August has fever, confusion, and acute asymmetric flaccid weakness of one arm. Several dead crows were recently found in his neighborhood. What is the most likely cause?",
  ["West Nile virus", "Poliovirus", "Rabies virus", "HSV-1", "Eastern equine encephalitis alphavirus"],
  "West Nile virus is a flavivirus. Birds are the reservoir (crows and jays die of it), Culex mosquitoes are the vector, and humans are dead-end hosts. Most infections cause no symptoms. Neuroinvasive disease (meningitis, encephalitis, polio-like acute flaccid paralysis) is most common in the elderly and immunocompromised. Diagnose with CSF IgM. It is the most common arboviral encephalitis in the US."),
Q(T, "Zika virus",
  "A pregnant woman had a mild illness with fever, maculopapular rash, conjunctivitis, and joint pain while visiting Brazil. Her infant is born with severe microcephaly and intracranial calcifications. Which statement about the virus is correct?",
  ["It is an Aedes-borne flavivirus that can also be spread sexually and transplacentally", "It is a togavirus spread only by respiratory droplets", "It is a herpesvirus that becomes latent in neurons", "It is a parvovirus that infects erythroid precursors", "It is a picornavirus spread by the fecal-oral route"],
  "Zika virus (flavivirus) is spread mainly by Aedes mosquitoes, and also sexually and from mother to fetus. It infects neural progenitor cells, causing congenital Zika syndrome: severe microcephaly, subcortical calcifications, eye abnormalities, and contractures. In adults it is usually mild but is associated with Guillain-Barré syndrome."),
# ---------------- Togaviruses ----------------
Q(T, "Rubella: congenital",
  "A newborn has cataracts, sensorineural deafness, a continuous machine-like murmur, and the 'blueberry muffin' skin lesions shown. The mother, recently immigrated, had a mild rash with postauricular lymphadenopathy in the first trimester. Which virus is responsible?",
  ["Rubella virus (togavirus)", "Cytomegalovirus", "Parvovirus B19", "Measles virus", "Zika virus"],
  "Congenital rubella syndrome (first-trimester infection) causes the classic triad of PDA (or pulmonary artery stenosis), cataracts, and sensorineural deafness, plus 'blueberry muffin' purpura from extramedullary hematopoiesis. Postnatal rubella (German measles, 3-day measles) is mild: fever, postauricular and occipital lymphadenopathy, a pink rash that starts on the face and spreads downward, and arthralgia in women. Prevent with MMR, a live vaccine given before pregnancy, not during.",
  img="blueberry.jpg"),
# ---------------- Coronavirus ----------------
Q(T, "SARS-CoV-2",
  "Which statement correctly describes how SARS-CoV-2 enters host cells?",
  ["The spike protein binds ACE2 and is cleaved by host TMPRSS2 to trigger membrane fusion", "Hemagglutinin binds sialic acid, and neuraminidase releases new virions", "The F protein binds ICAM-1", "gp120 binds CD4 and CCR5", "The virus enters through the P antigen on erythroid cells"],
  "SARS-CoV-2 is an enveloped, positive-sense ssRNA coronavirus. Its spike (S) protein binds angiotensin-converting enzyme 2 (ACE2), found on respiratory epithelium, type II pneumocytes, and endothelium. Host proteases (TMPRSS2 or cathepsins) prime fusion. mRNA vaccines encode the spike protein. Nirmatrelvir (with ritonavir boosting) inhibits the main protease (Mpro), and remdesivir inhibits RNA-dependent RNA polymerase."),
# ---------------- Orthomyxovirus ----------------
Q(T, "Influenza: antigenic shift",
  "A new influenza A strain spreads worldwide, causing a pandemic. Genetic analysis shows it has a hemagglutinin gene from an avian strain and other genes from human and swine strains. Which process produced it?",
  ["Reassortment of genome segments in a co-infected host (antigenic shift)", "Point mutations in hemagglutinin (antigenic drift)", "Recombination between two DNA viruses", "Phenotypic mixing without genetic change", "Transposition of a viral oncogene"],
  "Influenza is an enveloped, segmented (8 segments), negative-sense ssRNA orthomyxovirus. Antigenic shift is reassortment of whole segments (HA or NA) between animal and human strains in a co-infected host, often pigs. It produces a new subtype and can cause pandemics. Antigenic drift is gradual point mutations in HA and NA, causing seasonal epidemics, which is why the vaccine is updated every year. Hemagglutinin binds sialic acid for entry, and neuraminidase releases new virions."),
Q(T, "Influenza: treatment & complications",
  "A 70-year-old with confirmed influenza A gets better, then 5 days later develops high fever, rigors, and a cavitating necrotizing pneumonia. What is the most likely organism, and how does oseltamivir work?",
  ["Staphylococcus aureus; inhibits neuraminidase, blocking release of progeny virions", "Streptococcus pyogenes; inhibits hemagglutinin binding", "Pseudomonas aeruginosa; inhibits viral RNA polymerase", "Mycoplasma pneumoniae; blocks M2 ion channel", "Legionella; inhibits viral uncoating"],
  "Secondary bacterial pneumonia after influenza is often caused by S. aureus (including MRSA), S. pneumoniae, and H. influenzae. Oseltamivir and zanamivir inhibit neuraminidase, so new virions cannot be released. They work best within 48 hours of symptom onset but are given to hospitalized and high-risk patients regardless. Baloxavir inhibits the cap-dependent endonuclease. Amantadine and rimantadine (M2 channel blockers) are no longer used because of resistance. The inactivated vaccine is recommended yearly for everyone 6 months and older."),
# ---------------- Paramyxoviruses ----------------
Q(T, "Measles: Koplik spots",
  "An unvaccinated 4-year-old has 3 days of high fever, cough, coryza, and conjunctivitis. The buccal mucosa shows the small white spots on a red base pictured. Which supplement reduces the risk of severe disease and death?",
  ["Vitamin A", "Vitamin D", "Zinc", "Vitamin C", "Folic acid"],
  "Koplik spots (bluish-white spots on red buccal mucosa opposite the molars) appear before the rash of measles (rubeola), a paramyxovirus. The prodrome is the '3 Cs' (cough, coryza, conjunctivitis) with high fever. Vitamin A lowers mortality and complications, including corneal damage (keratitis causing blindness) and pneumonia, and is recommended for all children with measles.",
  img="koplik.jpg"),
Q(T, "Measles: complications",
  "A child has a maculopapular rash that began at the hairline and spread downward over 3 days, as shown, after a high fever with cough and conjunctivitis. Which complication is the most common cause of death from this infection, and which rare complication appears years later?",
  ["Pneumonia; subacute sclerosing panencephalitis (SSPE)", "Myocarditis; progressive multifocal leukoencephalopathy", "Hepatitis; Reye syndrome", "Orchitis; sterility", "Aplastic crisis; hydrops fetalis"],
  "Measles spreads by aerosol and is extremely contagious. The rash is erythematous and maculopapular, starting at the hairline and face and spreading downward, sparing the palms and soles, and later darkening. Complications: pneumonia (giant cell pneumonia; the most common cause of death), otitis media, acute encephalitis, 'immune amnesia' from destroyed memory lymphocytes, and SSPE (a fatal chronic encephalitis 7–10 years later from defective M-protein virus). Lymph nodes show Warthin-Finkeldey giant cells.",
  img="measles-rash.jpg"),
Q(T, "Mumps",
  "An unvaccinated 16-year-old boy has fever and painful swelling of both parotid glands, similar to the child shown. One week later he develops painful swelling of one testicle. Which other complication is also associated with this virus?",
  ["Aseptic meningitis and pancreatitis", "Hydrops fetalis", "Hepatocellular carcinoma", "Guillain-Barré syndrome after gastroenteritis", "Kaposi sarcoma"],
  "Mumps (paramyxovirus) causes parotitis, orchitis (usually after puberty; rarely sterility), aseptic meningitis, and pancreatitis ('POM': Parotitis, Orchitis, Meningitis). It can also cause sensorineural hearing loss and oophoritis. Serum amylase may be elevated from the salivary glands. It is prevented by MMR, and outbreaks still occur in close-contact settings such as college campuses.",
  img="mumps.jpg"),
Q(T, "RSV: bronchiolitis",
  "A 3-month-old in January has rhinorrhea, cough, wheezing, crackles, nasal flaring, and poor feeding. Pulse oximetry shows 91% saturation. Which viral protein is targeted by the monoclonal antibody nirsevimab (and palivizumab) used for prevention?",
  ["Fusion (F) protein, which causes syncytia", "Hemagglutinin", "Neuraminidase", "Hemagglutinin-neuraminidase (HN)", "Spike protein"],
  "RSV (a paramyxovirus/pneumovirus) is the leading cause of bronchiolitis and pneumonia in infants. Its F protein fuses infected cells into syncytia ('syncytial'). Unlike other paramyxoviruses, RSV lacks hemagglutinin. Treatment is supportive (oxygen, suction, fluids). Prevention: nirsevimab (long-acting anti-F antibody) for infants, the maternal RSV vaccine at 32–36 weeks, and RSV vaccines for older adults. Ribavirin is rarely used."),
Q(T, "Parainfluenza: croup",
  "An 18-month-old has 2 days of rhinorrhea followed by a barking cough, hoarse voice, and inspiratory stridor that worsens at night. Frontal neck radiograph shows subglottic narrowing (steeple sign). What is the most likely cause?",
  ["Parainfluenza virus", "Haemophilus influenzae type b", "Respiratory syncytial virus", "Bordetella pertussis", "Streptococcus pyogenes"],
  "Croup (laryngotracheobronchitis) is most often caused by parainfluenza virus types 1 and 2 (paramyxovirus). It affects children 6 months to 3 years. Treat with a single dose of dexamethasone and nebulized racemic epinephrine for moderate to severe stridor. Epiglottitis (thumb sign; drooling, toxic appearance) was classically caused by Hib. Bacterial tracheitis is often caused by S. aureus."),
# ---------------- Rhabdovirus ----------------
Q(T, "Rabies",
  "A 30-year-old man dies of an encephalitis with agitation, hydrophobia (painful laryngeal spasms when drinking), and hypersalivation. Months earlier he found a bat in his bedroom. The brain at autopsy is shown, with eosinophilic cytoplasmic inclusions in neurons. How did the virus reach his CNS?",
  ["Retrograde fast axonal transport along peripheral nerves (dynein)", "Hematogenous spread through the choroid plexus", "Infected monocytes crossing the blood-brain barrier", "Through the cribriform plate from the nasal mucosa only", "Anterograde transport from the spinal cord"],
  "Rabies is a bullet-shaped, enveloped, negative-sense ssRNA rhabdovirus. It binds nicotinic ACh receptors at the neuromuscular junction, enters peripheral nerves, and travels retrograde by dynein to the CNS. The incubation can last weeks to months (longer with bites far from the head). Negri bodies (cytoplasmic inclusions) are seen in the hippocampus and Purkinje cells. In the US, bats are the most common source, and bites may go unnoticed. Once symptoms begin, the disease is almost always fatal.",
  img="negri.jpg"),
Q(T, "Rabies: post-exposure prophylaxis",
  "A previously unvaccinated 25-year-old is bitten on the hand by a raccoon that ran away. What is the most appropriate management?",
  ["Wound cleaning, human rabies immune globulin infiltrated at the wound, and a series of rabies vaccine doses", "Rabies vaccine alone", "Rabies immune globulin alone", "Observe the patient for symptoms", "Oral acyclovir"],
  "Post-exposure prophylaxis for a previously unvaccinated person is thorough wound washing, HRIG infiltrated around the wound (passive immunity), and inactivated rabies vaccine on days 0, 3, 7, and 14, plus day 28 if immunocompromised (active immunity). HRIG and vaccine are given at different sites. For a healthy dog, cat, or ferret that can be observed for 10 days, PEP can be delayed. Raccoons, skunks, bats, and foxes are presumed rabid."),
# ---------------- Filovirus / Bunyavirus / Arenavirus ----------------
Q(T, "Ebola",
  "A health worker returning from West Africa has fever, severe diarrhea and vomiting, then bleeding from IV sites and DIC. Which statement about this virus is correct?",
  ["It is a filamentous, enveloped, negative-sense ssRNA filovirus spread by direct contact with body fluids", "It is spread mainly by Aedes mosquitoes", "It is a DNA virus with a latent phase in neurons", "It is spread only by rodent urine aerosols", "It is a naked virus spread fecal-orally"],
  "Ebola and Marburg are filoviruses (long filaments, negative-sense ssRNA). Fruit bats are the likely reservoir. Human-to-human spread is by contact with blood and body fluids, including during burials, which causes hospital outbreaks. The virus infects endothelium, macrophages, and hepatocytes, causing hemorrhagic fever with high mortality. Management: strict contact isolation and supportive care. Monoclonal antibodies (Inmazeb, Ebanga) and the rVSV-ZEBOV vaccine are available for Zaire ebolavirus."),
Q(T, "Hantavirus",
  "A 30-year-old man who cleaned out a rodent-infested cabin in New Mexico develops fever and myalgias, then rapidly progressive noncardiogenic pulmonary edema and shock. Labs show thrombocytopenia and hemoconcentration. What is the most likely cause?",
  ["Hantavirus (Sin Nombre virus), a bunyavirus inhaled from rodent excreta", "Yersinia pestis from flea bites", "Coxiella burnetii from livestock", "Coccidioides immitis from desert soil", "Influenza A from pigs"],
  "Hantavirus pulmonary syndrome (Sin Nombre virus, reservoir the deer mouse) comes from inhaling aerosolized rodent urine and droppings. It causes capillary leak, pulmonary edema, and shock, with high mortality. Old World hantaviruses cause hemorrhagic fever with renal syndrome. Bunyaviruses (segmented, negative-sense) also include Crimean-Congo hemorrhagic fever (ticks) and La Crosse encephalitis (mosquitoes)."),
Q(T, "Segmented RNA viruses",
  "Which group lists only viruses with segmented genomes?",
  ["Bunyavirus, orthomyxovirus (influenza), arenavirus, reovirus (rotavirus)", "Paramyxovirus, rhabdovirus, filovirus", "Picornavirus, calicivirus, flavivirus", "Retrovirus, coronavirus, togavirus", "Hepadnavirus, herpesvirus, poxvirus"],
  "Segmented RNA viruses ('BOARs'): Bunyaviruses, Orthomyxoviruses, Arenaviruses (LCMV, Lassa fever), and Reoviruses. Segmentation allows reassortment, which is the basis of influenza antigenic shift. Negative-sense ssRNA viruses must bring their own RNA-dependent RNA polymerase. Their naked genome is not infectious, while positive-sense genomes can serve directly as mRNA."),
Q(T, "Positive vs negative sense RNA",
  "When purified RNA genome from one virus is injected into a susceptible cell, it produces infectious progeny. For another virus, purified genome alone does not. What explains the difference?",
  ["Positive-sense RNA can be translated directly by host ribosomes; negative-sense RNA needs a virion-packaged RNA-dependent RNA polymerase", "Negative-sense RNA viruses are all DNA viruses", "Positive-sense viruses always have envelopes", "Negative-sense genomes are single-stranded DNA", "Positive-sense genomes need reverse transcriptase"],
  "Positive-sense ssRNA genomes (picornavirus, calicivirus, flavivirus, togavirus, coronavirus, hepevirus, and retrovirus, although retroviruses use reverse transcriptase) act as mRNA and are infectious by themselves. Negative-sense ssRNA viruses (orthomyxo, paramyxo, rhabdo, filo, bunya, arena, deltavirus) and dsRNA viruses (reo) carry their own RNA-dependent RNA polymerase, so purified genome alone is not infectious. Most RNA viruses replicate in the cytoplasm. Influenza and retroviruses replicate in the nucleus."),
Q(T, "HTLV-1",
  "A 55-year-old woman from southern Japan has lytic bone lesions, hypercalcemia, and skin infiltrates. Peripheral smear shows lymphocytes with lobulated, 'cloverleaf' nuclei. Which virus is associated with this malignancy?",
  ["HTLV-1, a retrovirus whose Tax protein activates host growth genes", "EBV, via CD21 on B cells", "HHV-8, via LANA", "HPV, via E6 and E7", "HIV-1, via Nef"],
  "Adult T-cell leukemia/lymphoma is caused by human T-lymphotropic virus type 1, which is endemic in Japan, the Caribbean, and West Africa. It spreads through breastfeeding, sex, and blood. Tax transactivates IL-2, IL-2R, and NF-κB, driving CD4+ T-cell proliferation. HTLV-1 also causes tropical spastic paraparesis (HTLV-associated myelopathy)."),
# ---------------- Prions ----------------
Q(T, "Prion disease",
  "A 62-year-old woman has rapidly progressive dementia over 4 months, with myoclonic jerks triggered by startle. EEG shows periodic sharp wave complexes, and MRI shows cortical ribboning and basal ganglia hyperintensity. Brain biopsy shows spongiform change without inflammation. What is the molecular basis?",
  ["Conversion of normal α-helical prion protein (PrPc) into a protease-resistant β-pleated sheet form (PrPsc)", "Infection with a slow RNA virus lacking an envelope", "Mutation in the huntingtin gene", "Autoantibodies against NMDA receptors", "Accumulation of hyperphosphorylated tau"],
  "Creutzfeldt-Jakob disease is a prion disease. Misfolded PrPsc (β-pleated sheet) acts as a template that converts normal PrPc, forming aggregates that cause spongiform degeneration. It can be sporadic (most cases), familial (PRNP mutations; fatal familial insomnia, GSS), iatrogenic (corneal and dural grafts, contaminated instruments, cadaveric growth hormone), or variant (bovine spongiform encephalopathy, from beef). Prions resist standard sterilization. CSF 14-3-3 and RT-QuIC help with diagnosis."),
]
