from qcore import Q
H = "HIV & Antiretrovirals"
P = "Hepatitis Viruses"
QUESTIONS = [
# ---------------- HIV ----------------
Q(H, "HIV: entry & CCR5",
  "A man with many known exposures to HIV has never been infected. Genetic testing shows he is homozygous for a 32-base-pair deletion in a gene encoding a host protein. Which step of HIV infection does this block?",
  ["gp120 binding to the CCR5 co-receptor on macrophages and CD4+ T cells", "gp41-mediated fusion with the endosome", "Reverse transcription of viral RNA", "Integration of proviral DNA", "Cleavage of Gag-Pol by viral protease"],
  "HIV gp120 binds CD4, then a co-receptor: CCR5 (macrophage-tropic, R5, early infection) or CXCR4 (T-cell-tropic, X4, later). gp41 then causes fusion. Homozygous CCR5-Δ32 gives strong resistance to R5 strains, and heterozygotes progress more slowly. Maraviroc blocks CCR5 and requires a tropism assay first. Enfuvirtide binds gp41 and blocks fusion."),
Q(H, "HIV: genes & proteins",
  "Which pairing of HIV gene and product is correct?",
  ["pol — reverse transcriptase, integrase, and protease", "gag — gp120 and gp41", "env — p24 capsid and p17 matrix", "tat — viral protease", "nef — reverse transcriptase"],
  "HIV structural genes: gag makes p24 capsid, p17 matrix, and nucleocapsid. pol makes reverse transcriptase, integrase, and protease. env makes gp160, which host proteases cleave into gp120 (attachment) and gp41 (fusion). Regulatory genes: tat (transactivation of transcription), rev (nuclear export of unspliced mRNA), and nef (downregulates MHC I and CD4). HIV is a diploid, positive-sense ssRNA retrovirus."),
Q(H, "HIV: diagnosis",
  "A 28-year-old man has fever, pharyngitis, a maculopapular rash, and lymphadenopathy 3 weeks after unprotected sex with a new partner. A monospot test is negative. Which test is most appropriate?",
  ["HIV-1/2 antigen/antibody combination immunoassay (detects p24 antigen), with HIV RNA if acute infection is suspected", "HIV Western blot alone", "CD4 count", "HIV antibody-only rapid test", "HIV genotype resistance testing only"],
  "Acute retroviral syndrome is a mono-like illness 2–4 weeks after infection. Viral load is very high and the patient is highly contagious. Antibodies may not have formed yet, but p24 antigen and HIV RNA are detectable. The 4th-generation Ag/Ab assay is the screening test, followed by an HIV-1/HIV-2 differentiation immunoassay and then HIV RNA if indeterminate. Western blot is no longer used. Infants born to HIV-positive mothers are tested with HIV RNA/DNA PCR because maternal IgG crosses the placenta."),
Q(H, "HIV: NRTIs",
  "A patient is being evaluated for HIV treatment with abacavir, lamivudine, and dolutegravir. Which pretreatment test is required, and why?",
  ["HLA-B*57:01, because carriers are at high risk of a hypersensitivity reaction to abacavir", "G6PD level, because of dapsone-like hemolysis", "CCR5 tropism, because abacavir targets CCR5", "HLA-B*15:02, because of Stevens-Johnson syndrome from carbamazepine", "Creatine kinase, because of rhabdomyolysis"],
  "NRTIs (tenofovir, emtricitabine, lamivudine, abacavir, zidovudine) are nucleoside or nucleotide analogs. Host kinases phosphorylate them (tenofovir is already a nucleotide), and they terminate DNA chains synthesized by reverse transcriptase. Class toxicity: mitochondrial toxicity and lactic acidosis. Specific toxicities: abacavir hypersensitivity (HLA-B*57:01), tenofovir disoproxil nephrotoxicity (Fanconi syndrome) and bone loss, zidovudine bone marrow suppression (macrocytic anemia). Lamivudine, emtricitabine, and tenofovir also treat HBV."),
Q(H, "HIV: NNRTIs",
  "How do non-nucleoside reverse transcriptase inhibitors such as efavirenz differ from NRTIs?",
  ["They bind a site near the RT active site allosterically and do not need phosphorylation", "They are incorporated into viral DNA as chain terminators", "They inhibit integrase", "They are active against HIV-2", "They block viral entry by binding gp41"],
  "NNRTIs (efavirenz, rilpivirine, doravirine, nevirapine) bind a hydrophobic pocket on HIV-1 RT, changing its shape. They need no activation and do not compete with nucleotides. They are inactive against HIV-2. A single mutation can cause high-level resistance. Toxicities: rash; efavirenz causes vivid dreams and CNS effects; nevirapine causes hepatotoxicity."),
Q(H, "HIV: integrase & protease inhibitors",
  "A patient on an HIV regimen boosted with ritonavir develops hyperglycemia, dyslipidemia, and redistribution of fat to the abdomen and dorsocervical area. Why is ritonavir added to other drugs of its class?",
  ["It strongly inhibits CYP3A4, raising levels of co-administered protease inhibitors", "It induces CYP3A4 to reduce toxicity", "It inhibits integrase strand transfer", "It blocks CCR5", "It is a chain terminator"],
  "Protease inhibitors (-navir: darunavir, atazanavir, lopinavir) block HIV protease cleavage of the Gag-Pol polyprotein, producing immature, non-infectious virions. Low-dose ritonavir (or cobicistat) inhibits CYP3A4 to 'boost' other PIs. PI toxicities: hyperglycemia, dyslipidemia, lipodystrophy, GI upset, many drug interactions (rifampin lowers PI levels, so rifabutin is used), and atazanavir hyperbilirubinemia. Integrase inhibitors (-tegravir: dolutegravir, bictegravir, raltegravir) block strand transfer. They are first-line and can cause weight gain and increased CK."),
Q(H, "HIV: opportunistic infections by CD4 count",
  "Which infection typically occurs only when the CD4 count falls below 50 cells/μL?",
  ["CMV retinitis", "Pneumocystis pneumonia", "Oral candidiasis", "Herpes zoster", "Pulmonary tuberculosis"],
  "CD4 thresholds: under 500 — oral thrush, zoster, TB, oral hairy leukoplakia, Kaposi sarcoma can occur. Under 200 — Pneumocystis pneumonia, HIV-associated dementia, PML, histoplasmosis/coccidioidomycosis. Under 100 — Toxoplasma encephalitis, cryptococcal meningitis, Candida esophagitis, Bartonella. Under 50 — CMV retinitis and colitis, disseminated MAC, primary CNS lymphoma (EBV). TB can occur at any CD4 count."),
Q(H, "HIV: perinatal transmission",
  "A pregnant woman with HIV has taken ART throughout pregnancy. At 36 weeks her viral load is 3,000 copies/mL. What is the best way to lower the risk of transmission to her infant?",
  ["Intrapartum IV zidovudine, scheduled cesarean at 38 weeks, infant antiretroviral prophylaxis, and avoiding breastfeeding", "Vaginal delivery without further intervention", "Stop ART at delivery to avoid neonatal toxicity", "Give HIV immune globulin to the infant", "Breastfeeding plus infant zidovudine"],
  "The goal is an undetectable viral load. If the viral load near delivery is above 1,000 copies/mL: IV zidovudine during labor and scheduled cesarean at 38 weeks. All exposed infants receive antiretroviral prophylaxis (zidovudine, or combination therapy if high risk). In the US, avoiding breastfeeding is still recommended, although shared decision-making is now allowed for women with sustained viral suppression."),
Q(H, "HIV: PrEP & PEP",
  "A healthcare worker has a needlestick from a patient with HIV and a detectable viral load. What is the most appropriate management?",
  ["Start 3-drug post-exposure prophylaxis as soon as possible (within 72 hours) for 28 days", "Wait for the worker's HIV test to turn positive before treating", "Give HIV immune globulin", "Start tenofovir-emtricitabine for 7 days", "No action is needed for percutaneous exposures"],
  "Post-exposure prophylaxis (for example, tenofovir-emtricitabine plus dolutegravir or raltegravir) should start within hours and no later than 72 hours, and continue for 28 days, with baseline and follow-up HIV testing. Pre-exposure prophylaxis (daily TDF/FTC or TAF/FTC, or injectable cabotegravir or lenacapavir) is for HIV-negative people at ongoing risk. The risk of transmission from a percutaneous exposure is about 0.3%."),
Q(H, "HIV: IRIS",
  "Three weeks after starting ART, a man with AIDS (CD4 count 20/μL) who is being treated for cryptococcal meningitis develops worsening headache and fever. His CD4 count has risen and his viral load has fallen sharply. CSF cultures are now sterile. What is the most likely explanation?",
  ["Immune reconstitution inflammatory syndrome", "ART failure due to resistance", "A new bacterial meningitis", "Drug-induced aseptic meningitis from dolutegravir", "Progressive multifocal leukoencephalopathy"],
  "IRIS is a paradoxical inflammatory worsening of a known infection (or unmasking of an occult one) as the recovering immune system responds to antigens from Cryptococcus, TB, MAC, CMV, PML, and others. Risk is highest with very low baseline CD4 and rapid viral suppression. For cryptococcal meningitis, ART is delayed 4–6 weeks after starting antifungals to reduce this risk. For TB, ART is started within 2 weeks unless there is TB meningitis."),
# ---------------- Hepatitis ----------------
Q(P, "HAV",
  "A 24-year-old man returns from a trip to Mexico with fever, malaise, anorexia, dark urine, and jaundice. ALT is 2,400 U/L. He is not vaccinated. Which test result confirms the most likely diagnosis?",
  ["IgM anti-HAV", "IgG anti-HAV", "HBsAg", "HCV RNA", "Anti-HBs"],
  "Hepatitis A is a naked, positive-sense ssRNA picornavirus (hepatovirus) spread fecal-orally through contaminated food, water, and shellfish, travel, and outbreaks among MSM, homeless people, and injection drug users. It causes acute, self-limited hepatitis without a chronic phase. IgM anti-HAV marks acute infection. IgG marks past infection or vaccination. Prevention: inactivated vaccine for all children and at-risk adults, and vaccine or immune globulin after exposure."),
Q(P, "HBV serology: window period",
  "A 30-year-old injection drug user had acute hepatitis 2 months ago and is now recovering. Serology: HBsAg negative, anti-HBs negative, IgM anti-HBc positive. How should this be interpreted?",
  ["Window period of acute hepatitis B", "Immunity from vaccination", "Chronic hepatitis B", "Past, resolved infection with immunity", "False-positive result; no HBV infection"],
  "In the window period, HBsAg has cleared but anti-HBs is not yet detectable. IgM anti-HBc is the only marker of acute infection. Key patterns: HBsAg+ with IgM anti-HBc → acute infection. HBsAg+ for more than 6 months with IgG anti-HBc → chronic. Anti-HBs+ with IgG anti-HBc → resolved infection (immune). Anti-HBs alone → vaccinated. HBeAg and HBV DNA indicate active replication and high infectivity."),
Q(P, "HBV serology: vaccination",
  "A nursing student's hepatitis B panel shows anti-HBs positive, HBsAg negative, and anti-HBc negative. What does this mean?",
  ["Immunity from vaccination", "Acute infection", "Chronic infection", "Past natural infection", "Window period"],
  "The HBV vaccine contains recombinant HBsAg only, so vaccinated people develop anti-HBs but not anti-HBc. Anti-HBc (to the core antigen) appears only after real infection. It is given to all infants at birth. Infants of HBsAg-positive mothers also receive HBIG plus vaccine within 12 hours of birth."),
Q(P, "HBV: replication",
  "Chronic hepatitis B is hard to cure because a stable form of the viral genome persists in hepatocyte nuclei. Which feature of HBV replication is correct?",
  ["The partially double-stranded circular DNA is converted into covalently closed circular DNA (cccDNA), transcribed into pregenomic RNA, and reverse-transcribed into new DNA", "It replicates in the cytoplasm using RNA-dependent RNA polymerase", "It is a single-stranded linear DNA virus", "It integrates using integrase like HIV", "It requires HDV to replicate"],
  "HBV (Hepadnaviridae) is an enveloped virus with a partially dsDNA circular genome. In the nucleus it is repaired into cccDNA, which acts as a template. Pregenomic RNA is reverse-transcribed by the viral polymerase (which has RT activity) inside the capsid. Nucleoside or nucleotide RT inhibitors (tenofovir, entecavir) suppress replication, but cccDNA persists. Integration of HBV DNA contributes to hepatocellular carcinoma, even without cirrhosis."),
Q(P, "HBV: histology",
  "A liver biopsy from a patient with long-standing viral hepatitis is shown. Many hepatocytes have finely granular, pale eosinophilic cytoplasm. Immunostaining for a viral surface antigen is positive. What is this finding, and what causes it?",
  ["Ground-glass hepatocytes from HBsAg accumulating in the endoplasmic reticulum", "Councilman bodies from apoptosis in yellow fever", "Mallory-Denk bodies from alcohol injury", "Steatosis from hepatitis C genotype 3", "Owl's eye inclusions from CMV"],
  "Ground-glass hepatocytes are typical of chronic hepatitis B. Large amounts of HBsAg fill a swollen, smooth endoplasmic reticulum. HBV extrahepatic diseases (immune complex): polyarteritis nodosa, membranous nephropathy, and serum sickness-like prodrome (arthralgias, rash). Chronic HCV shows lymphoid aggregates and macrovesicular steatosis.",
  img="ground-glass.webp"),
Q(P, "HBV: extrahepatic",
  "A 45-year-old man with chronic hepatitis B develops fever, weight loss, testicular pain, mononeuritis multiplex, and hypertension. Angiography shows microaneurysms of the renal and mesenteric arteries. ANCA is negative. What is the most likely diagnosis?",
  ["Polyarteritis nodosa", "Granulomatosis with polyangiitis", "Cryoglobulinemic vasculitis", "Takayasu arteritis", "IgA vasculitis"],
  "HBV is associated with polyarteritis nodosa, an immune complex vasculitis of medium arteries that spares the lungs. It causes 'string of pearls' microaneurysms and involves the kidneys, GI tract, skin, and nerves. HBV is also associated with membranous nephropathy. HCV is associated with mixed cryoglobulinemia, membranoproliferative GN, porphyria cutanea tarda, and lichen planus."),
Q(P, "HCV: treatment",
  "A 50-year-old man with chronic HCV (genotype 1) and no cirrhosis is treated with sofosbuvir and velpatasvir for 12 weeks. What is the mechanism of sofosbuvir?",
  ["Nucleotide inhibitor of the NS5B RNA-dependent RNA polymerase", "Inhibitor of the NS3/4A serine protease", "Inhibitor of the NS5A replication complex protein", "Reverse transcriptase inhibitor", "Interferon receptor agonist"],
  "HCV direct-acting antivirals cure more than 95% of patients. Classes: NS5B polymerase inhibitors (-buvir: sofosbuvir), NS5A inhibitors (-asvir: velpatasvir, ledipasvir, pibrentasvir), and NS3/4A protease inhibitors (-previr: glecaprevir, grazoprevir). Cure is a sustained virologic response (undetectable RNA 12 weeks after treatment). All adults should be screened once, and pregnant women each pregnancy. Diagnose with anti-HCV antibody, then HCV RNA."),
Q(P, "HCV: chronicity & no vaccine",
  "Most people infected with hepatitis C develop chronic infection, and there is still no vaccine. Which property best explains both facts?",
  ["The RNA polymerase lacks proofreading, producing quasispecies with hypervariable envelope (E2) regions that escape antibodies", "It integrates into host DNA", "It becomes latent in neurons", "It has a DNA genome that cannot be targeted by antibodies", "It is a defective virus that needs HBV"],
  "HCV is an enveloped, positive-sense ssRNA flavivirus (hepacivirus). The error-prone NS5B polymerase creates quasispecies, and hypervariable region 1 of E2 changes constantly, allowing immune escape. It is spread mainly by blood (injection drug use, historical transfusions), less often sexually or vertically. Most cases become chronic, leading to cirrhosis and HCC. Extrahepatic: mixed cryoglobulinemia, MPGN, porphyria cutanea tarda, lichen planus, and B-cell lymphoma."),
Q(P, "HDV",
  "A man with known chronic hepatitis B, previously stable, has a sudden severe flare of hepatitis after injection drug use. A second infection is suspected. Which statement about the most likely co-pathogen is correct?",
  ["It is a defective RNA virus that needs HBsAg for its envelope; superinfection of a chronic HBV carrier carries a high risk of severe disease", "It is a DNA virus that replicates independently", "It is spread mainly by the fecal-oral route", "Superinfection is milder than simultaneous co-infection", "The HBV vaccine does not protect against it"],
  "Hepatitis D (delta virus) is a circular negative-sense ssRNA satellite virus. It needs HBsAg from HBV for its coat. Co-infection (HBV and HDV together) usually resolves. Superinfection of an HBV carrier more often causes fulminant hepatitis and rapidly progressive cirrhosis. Preventing HBV through vaccination also prevents HDV. Diagnose with anti-HDV antibody and HDV RNA."),
Q(P, "HEV",
  "During an outbreak linked to contaminated drinking water in South Asia, a 26-year-old woman in her third trimester develops jaundice, encephalopathy, and coagulopathy. What is the most likely cause?",
  ["Hepatitis E virus", "Hepatitis A virus", "Hepatitis B virus", "Hepatitis C virus", "Yellow fever virus"],
  "Hepatitis E (naked, positive-sense ssRNA hepevirus) spreads fecal-orally through contaminated water (genotypes 1 and 2) and undercooked pork, venison, and shellfish (genotypes 3 and 4). It is usually self-limited but has high mortality in pregnant women (fulminant hepatic failure). It can become chronic in transplant recipients. Diagnose with IgM anti-HEV or HEV RNA."),
Q(P, "Hepatitis: transmission summary",
  "Which hepatitis viruses are spread mainly by the fecal-oral route and do not cause chronic infection in immunocompetent hosts?",
  ["Hepatitis A and hepatitis E", "Hepatitis B and hepatitis D", "Hepatitis C and hepatitis D", "Hepatitis B and hepatitis C", "Hepatitis A and hepatitis C"],
  "'The vowels hit your bowels': HAV and HEV are spread fecal-orally and are naked RNA viruses, with no chronic carrier state (except HEV in immunosuppressed hosts). HBV, HCV, and HDV spread by blood, sex, and vertically and can become chronic. Chronic infection can lead to cirrhosis and HCC. Chronicity after acute infection: HBV is about 5% in adults but about 90% in neonates. HCV is 60–80%."),
]
