from qcore import Q
T = "Fungi & Antifungals"
QUESTIONS = [
# ---------------- Candida ----------------
Q(T, "Candida: oral thrush",
  "A 35-year-old man has white plaques on his tongue and palate that scrape off to leave a red, bleeding base, as shown. He has lost weight and has had recurrent zoster. Which is the most appropriate next step besides treating the lesions?",
  ["HIV testing", "Biopsy for squamous cell carcinoma", "Testing for EBV to confirm oral hairy leukoplakia", "Tuberculin skin test", "Serum iron studies"],
  "Oral candidiasis (thrush) produces white pseudomembranous plaques that can be scraped off, unlike oral hairy leukoplakia (EBV). Thrush in an adult without a clear cause (inhaled steroids, dentures, antibiotics, diabetes) suggests impaired T-cell immunity, so test for HIV. Treat with clotrimazole troches, nystatin suspension, or oral fluconazole. Candida esophagitis (odynophagia) is AIDS-defining and usually occurs at CD4 below 100.",
  img="thrush.webp"),
Q(T, "Candida: morphology & invasive disease",
  "A patient in the ICU receiving total parenteral nutrition through a central line has fever despite broad-spectrum antibiotics. Blood cultures grow a yeast that forms the pseudohyphae shown and germ tubes at 37°C. Which drug is first-line, and what is its mechanism?",
  ["Micafungin (an echinocandin), which inhibits β-(1,3)-glucan synthase in the cell wall", "Amphotericin B, which inhibits squalene epoxidase", "Fluconazole, which binds ergosterol and forms pores", "Terbinafine, which inhibits 14α-demethylase", "Griseofulvin, which disrupts microtubules"],
  "Candida albicans is a normal-flora yeast that forms pseudohyphae and, at 37°C, germ tubes. Candidemia risk factors: central lines, TPN, broad-spectrum antibiotics, neutropenia, and abdominal surgery. Echinocandins (caspofungin, micafungin, anidulafungin) are first-line. They inhibit cell wall β-glucan synthesis. They are poor against Cryptococcus. Remove the central line, and do an ophthalmologic exam for endophthalmitis. Candida auris is often multidrug-resistant.",
  img="candida-gram.webp"),
Q(T, "Candida: immune defense",
  "A child has chronic, recurrent Candida infections of the skin, nails, and mucous membranes but not invasive candidiasis. Which arm of immunity is most likely defective?",
  ["T cells (especially Th17 responses)", "Neutrophil oxidative burst", "Complement C5–C9", "B cells and immunoglobulin production", "Splenic macrophages"],
  "T cells, especially Th17 and IL-17/IL-22 signaling, protect skin and mucosal surfaces from Candida. Defects (chronic mucocutaneous candidiasis from AIRE mutation in APS-1, STAT1 gain-of-function, HIV, hyper-IgE syndrome from STAT3) cause superficial infection. Neutrophils prevent invasive disease: neutropenia and CGD lead to candidemia and deep infection."),
# ---------------- Aspergillus ----------------
Q(T, "Aspergillus: invasive disease",
  "A 50-year-old man with acute myeloid leukemia has been neutropenic for 3 weeks. He develops fever, pleuritic chest pain, and hemoptysis. CT shows nodules with a surrounding 'halo' of ground-glass opacity. Lung biopsy is shown. What is the preferred treatment?",
  ["Voriconazole", "Fluconazole", "Caspofungin alone as first-line", "Trimethoprim-sulfamethoxazole", "Nystatin"],
  "Invasive aspergillosis occurs in prolonged neutropenia, hematopoietic stem cell transplant, and high-dose steroids. The hyphae are septate and branch at acute (45°) angles (shown). They invade blood vessels, causing infarction, hemoptysis, and the CT 'halo sign.' Serum galactomannan supports the diagnosis. Voriconazole is first-line (isavuconazole is an alternative). Voriconazole toxicities include visual disturbances, photosensitivity (and skin cancer with long use), hepatotoxicity, and CYP interactions. Fluconazole has no activity against Aspergillus.",
  img="aspergillus.webp"),
Q(T, "Aspergillus: ABPA",
  "A 22-year-old woman with poorly controlled asthma has recurrent wheezing, cough with brown mucus plugs, and fleeting infiltrates. Labs show peripheral eosinophilia and a markedly elevated total IgE. CT shows central bronchiectasis. What is the diagnosis and main treatment?",
  ["Allergic bronchopulmonary aspergillosis; systemic corticosteroids ± itraconazole", "Invasive aspergillosis; voriconazole", "Aspergilloma; surgical resection", "Eosinophilic granulomatosis with polyangiitis; cyclophosphamide", "Löffler syndrome from Ascaris; albendazole"],
  "ABPA is a hypersensitivity reaction (type I and III) to Aspergillus growing in airways, seen in asthma and cystic fibrosis. It causes eosinophilia, high IgE, Aspergillus-specific IgE and IgG, and central bronchiectasis. Treat with corticosteroids, with itraconazole to reduce fungal load. Aspergilloma (fungus ball) grows in a preexisting cavity, such as an old TB cavity, and presents with hemoptysis. Aspergillus flavus makes aflatoxin, which is associated with HCC (p53 mutations)."),
# ---------------- Mucor ----------------
Q(T, "Mucormycosis",
  "A 45-year-old man in diabetic ketoacidosis develops facial pain, proptosis, and a black necrotic eschar on the palate and nasal turbinate. A specimen is shown: broad, ribbon-like, nonseptate hyphae branching at wide angles. Along with surgical debridement, which drug is first-line?",
  ["Liposomal amphotericin B", "Voriconazole", "Fluconazole", "Micafungin", "Terbinafine"],
  "Mucormycosis (Mucor, Rhizopus) invades blood vessels and causes rhinocerebral infection with necrosis and spread to the orbit and brain. It occurs in DKA (acidosis releases iron from transferrin, and the fungus uses the free iron to grow; it also has ketone reductase), neutropenia, deferoxamine therapy, and transplant. Treat with emergency debridement plus high-dose liposomal amphotericin B, then posaconazole or isavuconazole. Voriconazole is not active and may even predispose to mucormycosis.",
  img="mucor.webp"),
# ---------------- Cryptococcus ----------------
Q(T, "Cryptococcus: meningitis",
  "A man with AIDS (CD4 60/μL) has 2 weeks of headache, fever, and confusion. Opening pressure on lumbar puncture is 35 cm H2O. An India ink preparation of the CSF is shown. What is the appropriate initial therapy?",
  ["Amphotericin B plus flucytosine, then fluconazole, with serial LPs to lower intracranial pressure", "Fluconazole alone", "Caspofungin", "Trimethoprim-sulfamethoxazole plus steroids", "Ceftriaxone plus vancomycin"],
  "Cryptococcus neoformans is an encapsulated yeast found in soil and pigeon droppings. It is inhaled and spreads to the meninges in AIDS (CD4 below 100) and other immunosuppression. India ink shows yeasts with clear halos (capsules), as here. The CSF cryptococcal antigen (latex agglutination) is more sensitive. Other virulence factors: melanin (laccase), urease, and growth at 37°C. Induction therapy is amphotericin B plus flucytosine, followed by fluconazole for consolidation and maintenance. Remove CSF to control high pressure. Delay ART 4–6 weeks.",
  img="crypto-ink.webp"),
# ---------------- Endemic dimorphic fungi ----------------
Q(T, "Histoplasma",
  "A 40-year-old man with HIV (CD4 90/μL) from Ohio has fever, weight loss, hepatosplenomegaly, pancytopenia, and painful oral ulcers. He explores caves. A lymph node aspirate (Diff-Quik stain) is shown: macrophages packed with tiny oval yeasts (2–4 μm). What is the most likely organism?",
  ["Histoplasma capsulatum", "Blastomyces dermatitidis", "Coccidioides immitis", "Leishmania donovani", "Cryptococcus neoformans"],
  "Histoplasma is found in the Ohio and Mississippi River valleys, in soil contaminated with bird and bat droppings (caves, chicken coops). The yeast is small and grows inside macrophages. It causes pulmonary disease that can mimic TB (calcified hilar nodes). Disseminated disease in AIDS causes pancytopenia, hepatosplenomegaly, oral ulcers, and adrenal insufficiency. Urine and serum antigen detection helps. Leishmania amastigotes are also found in macrophages, but they have a kinetoplast. Treat severe disease with liposomal amphotericin B, then itraconazole.",
  img="histo-mac.webp"),
Q(T, "Blastomyces",
  "A 50-year-old man from Wisconsin who hunts along riverbanks has a chronic pneumonia and verrucous, crusted skin lesions on his face, plus a lytic bone lesion. Tissue shows large (8–15 μm), thick-walled yeasts with a single broad-based bud, as shown. What is the treatment for moderate disease?",
  ["Itraconazole", "Penicillin", "Fluconazole alone", "Caspofungin", "Isoniazid"],
  "Blastomyces dermatitidis lives in the Great Lakes, Ohio and Mississippi River basins, and southeastern US, often near waterways and decaying wood. Inhaled conidia become large yeasts with broad-based budding ('Blasto Buds Broadly'). It causes pneumonia and spreads to skin (verrucous lesions that can mimic SCC), bone, and the GU tract (prostate). Treat mild to moderate disease with itraconazole and severe or CNS disease with amphotericin B.",
  img="blasto.webp"),
Q(T, "Coccidioides",
  "A 30-year-old Filipino man who moved to Arizona has fever, cough, and painful red nodules on his shins after a dust storm. Weeks later he develops meningitis. Tissue shows the structure pictured: a large spherule filled with endospores. Which statement is correct?",
  ["The fungus is a mold in desert soil, and inhaled arthroconidia become spherules in tissue; dissemination is more common in Filipino and Black patients and in pregnancy", "It is a yeast found in bird droppings in the Ohio River valley", "It is spread person to person by respiratory droplets", "It is a normal-flora yeast that forms pseudohyphae", "It is a thermally monomorphic fungus with broad-based budding"],
  "Coccidioides immitis and C. posadasii are found in the southwestern US (San Joaquin Valley, Arizona) and northern Mexico. Arthroconidia are released by dust storms, earthquakes, and construction. Illness (valley fever) can include erythema nodosum ('desert bumps') and arthralgias ('desert rheumatism'). Dissemination to skin, bone, and meninges is more common in Filipino and Black patients, pregnancy, and immunosuppression. Treat with fluconazole or itraconazole, or amphotericin B for severe disease. Meningitis needs lifelong fluconazole.",
  img="cocci-spherule.webp"),
Q(T, "Paracoccidioides",
  "A 50-year-old coffee farmer from rural Brazil has chronic pneumonia and painful mulberry-like ulcers of the mouth and lips. A silver stain of tissue is shown: large yeast cells with multiple narrow-based buds around the edge. What is the organism?",
  ["Paracoccidioides brasiliensis", "Blastomyces dermatitidis", "Histoplasma capsulatum", "Cryptococcus gattii", "Sporothrix schenckii"],
  "Paracoccidioides is found in Latin America and affects mainly male agricultural workers. It is dimorphic, and the yeast forms multiple buds around its edge, like a 'captain's wheel' or 'Mickey Mouse ears.' It causes chronic pulmonary disease and ulcerating mucocutaneous lesions. Estrogen inhibits the change from mold to yeast, which may explain why it affects men more. Treat with itraconazole.",
  img="paracocci.webp"),
Q(T, "Dimorphism",
  "Histoplasma, Blastomyces, Coccidioides, Paracoccidioides, and Sporothrix are thermally dimorphic. What does this mean?",
  ["They grow as molds at environmental temperature (25°C) and as yeasts at body temperature (37°C), except Coccidioides, which forms spherules in tissue", "They grow as yeasts in soil and molds in tissue", "They grow only at 42°C", "They switch between septate and nonseptate hyphae depending on pH", "They are obligate intracellular in all phases"],
  "'Cold = mold, heat = yeast.' Dimorphic fungi are inhaled as conidia from the mold form in the environment and change to yeast (or spherules in Coccidioides) in the body. Most endemic mycoses cause mild pneumonia in healthy people, which can disseminate in immunocompromised hosts. They are generally treated with itraconazole or fluconazole (mild) or amphotericin B (severe)."),
# ---------------- Pneumocystis ----------------
Q(T, "Pneumocystis",
  "A 36-year-old man with untreated HIV (CD4 90/μL) has 3 weeks of progressive dyspnea on exertion, dry cough, and fever. He desaturates with walking. CXR shows bilateral diffuse interstitial ('ground-glass') infiltrates, and serum LDH is high. A silver (GMS) stain of bronchoalveolar lavage fluid shows cup-shaped cysts. His PaO2 on room air is 62 mmHg. What is the most appropriate treatment?",
  ["TMP-SMX plus corticosteroids", "TMP-SMX alone", "Fluconazole", "Amphotericin B", "Ganciclovir"],
  "Pneumocystis jirovecii is a yeast-like fungus with no ergosterol, so standard antifungals are inactive. It is diagnosed by GMS stain (cup- or crescent-shaped cysts) or fluorescent antibody on BAL or induced sputum. It occurs at CD4 below 200, with steroids, and after transplants. Elevated β-D-glucan supports the diagnosis. Treat with TMP-SMX (alternatives: pentamidine, atovaquone, primaquine-clindamycin). Add steroids if PaO2 is below 70 mmHg or the A-a gradient is above 35. Prophylaxis at CD4 below 200 is TMP-SMX.",
  ),
# ---------------- Sporothrix ----------------
Q(T, "Sporothrix",
  "A 55-year-old gardener pricked her finger on a rose thorn. Weeks later a painless ulcerating nodule appeared at the site, followed by a chain of nodules spreading up the forearm along lymphatic channels, as shown. Culture at 25°C grows a mold. At 37°C it grows as cigar-shaped yeasts. What is the treatment?",
  ["Itraconazole", "Penicillin", "Amphotericin B for all cases", "Caspofungin", "Isoniazid"],
  "Sporotrichosis (Sporothrix schenckii, 'rose gardener's disease') is a dimorphic fungus inoculated from thorns, sphagnum moss, hay, soil, or cat scratches. It spreads along lymphatics (lymphocutaneous or sporotrichoid spread). It rarely disseminates except in immunocompromised hosts. Treat with itraconazole. Saturated potassium iodide is an older option. Nocardia brasiliensis and M. marinum can spread in a similar pattern.",
  img="sporotrichosis.webp"),
# ---------------- Superficial ----------------
Q(T, "Tinea versicolor",
  "A 20-year-old has many light, finely scaling macules on his upper chest and back that became more noticeable after a summer at the beach. A KOH preparation of the skin scale is shown. Which statement is correct?",
  ["It is caused by Malassezia furfur, and KOH shows short hyphae and yeasts ('spaghetti and meatballs')", "It is caused by Trichophyton rubrum, and KOH shows septate hyphae only", "It is caused by Candida albicans, and KOH shows pseudohyphae", "It is caused by Sporothrix, and KOH shows cigar-shaped yeasts", "It is a bacterial infection with Corynebacterium minutissimum"],
  "Pityriasis (tinea) versicolor is caused by the lipophilic yeast Malassezia. It thrives in hot, humid conditions. Azelaic acid from the yeast inhibits tyrosinase, causing hypopigmentation, which is more visible after tanning. Lesions can also be pink or hyperpigmented. Treat with topical selenium sulfide or azoles. Malassezia also causes seborrheic dermatitis, and it can cause fungemia in infants on lipid-rich TPN.",
  img="malassezia.webp"),
Q(T, "Dermatophytes & treatment",
  "A 45-year-old man has an itchy annular plaque with a raised, scaly border and central clearing on his arm. He also has thick, yellow, crumbly toenails. KOH of the toenail shows septate branching hyphae. Which drug is most appropriate for the onychomycosis, and what is its mechanism?",
  ["Oral terbinafine, which inhibits squalene epoxidase", "Oral fluconazole, which inhibits β-glucan synthase", "Nystatin, which binds ergosterol", "Griseofulvin, which inhibits 14α-demethylase", "Oral ketoconazole, which disrupts microtubules"],
  "Dermatophytes (Trichophyton, Microsporum, Epidermophyton) digest keratin in skin, hair, and nails, causing tinea corporis (ringworm), cruris, pedis, capitis, and onychomycosis (tinea unguium). Terbinafine inhibits squalene epoxidase, and toxic squalene builds up. It concentrates in keratin and is first-line for onychomycosis. Monitor LFTs. Griseofulvin disrupts microtubule spindles, deposits in keratin, and is used for tinea capitis in children. It is teratogenic and induces CYP450. Topical azoles or terbinafine treat tinea corporis.",
  ),
# ---------------- Antifungal pharmacology ----------------
Q(T, "Amphotericin B",
  "A patient receiving amphotericin B for disseminated histoplasmosis develops rising creatinine, hypokalemia, and hypomagnesemia. What is the drug's mechanism, and what reduces the kidney toxicity?",
  ["Binds ergosterol and forms membrane pores; normal saline loading and lipid formulations reduce nephrotoxicity", "Inhibits 14α-demethylase; hydration has no effect", "Inhibits β-glucan synthase; co-administered probenecid", "Converted to 5-FU; leucovorin rescue", "Inhibits squalene epoxidase; potassium restriction"],
  "Amphotericin B binds ergosterol (the fungal membrane sterol) and forms pores, causing ions to leak. It is used for serious systemic mycoses. Toxicities: nephrotoxicity from afferent vasoconstriction and distal tubular damage (type 1 RTA, hypokalemia, hypomagnesemia), infusion reactions (fevers and chills, 'shake and bake'), hypotension, anemia (reduced EPO), and arrhythmias. Saline loading and liposomal formulations reduce kidney injury. Nystatin works the same way but is too toxic for systemic use, so it is topical or swish-and-swallow only."),
Q(T, "Azole antifungals",
  "A patient taking fluconazole prophylaxis after a stem cell transplant has a rising tacrolimus level. What is the mechanism of azoles, and why did the drug level rise?",
  ["Inhibit fungal cytochrome P450 14α-demethylase (lanosterol → ergosterol) and also inhibit human CYP3A4", "Bind ergosterol directly and induce hepatic CYP enzymes", "Inhibit β-glucan synthesis and compete for renal excretion", "Inhibit microtubules and displace drugs from albumin", "Inhibit squalene epoxidase and block P-glycoprotein"],
  "Azoles (fluconazole, itraconazole, voriconazole, posaconazole, isavuconazole, ketoconazole) inhibit fungal 14α-demethylase, which blocks ergosterol synthesis. They also inhibit human CYP3A4, raising levels of tacrolimus, cyclosporine, warfarin, and statins. Ketoconazole also inhibits steroid synthesis (gynecomastia, adrenal insufficiency). Fluconazole reaches the CSF and is used for cryptococcal maintenance and Candida. It does not cover molds or C. krusei. Itraconazole is used for dimorphic fungi. Voriconazole is first-line for Aspergillus."),
Q(T, "Flucytosine",
  "Flucytosine is combined with amphotericin B for cryptococcal meningitis. How is it activated, and what is its main toxicity?",
  ["Fungal cytosine deaminase converts it to 5-fluorouracil, which inhibits thymidylate synthase; bone marrow suppression", "Viral thymidine kinase phosphorylates it; nephrotoxicity", "It needs no activation; hepatotoxicity", "Host kinases convert it to a chain terminator; peripheral neuropathy", "Hepatic CYP450 converts it to an active epoxide; visual disturbances"],
  "Flucytosine is taken up through fungal cytosine permease and deaminated to 5-FU by fungal cytosine deaminase, which mammalian cells lack. It inhibits thymidylate synthase and DNA and RNA synthesis. It is used only in combination (with amphotericin B for Cryptococcus) because resistance develops quickly when used alone. Toxicity: bone marrow suppression, especially with kidney impairment, since the drug is renally cleared."),
]
