from qcore import Q
T = "Protozoa"
QUESTIONS = [
# ---------------- Intestinal ----------------
Q(T, "Giardia",
  "A 28-year-old man develops foul-smelling, greasy, floating stools, bloating, flatulence, and weight loss 2 weeks after a backpacking trip where he drank untreated stream water. No blood or fever. Stool microscopy shows the trophozoite form illustrated: pear-shaped, with two nuclei, a ventral sucking disk, and flagella. Which condition predisposes to chronic infection?",
  ["Selective IgA deficiency", "Asplenia", "Terminal complement deficiency", "Chronic granulomatous disease", "Sickle cell disease"],
  "Giardia lamblia (intestinalis) cysts are ingested in water that has not been filtered (beavers are reservoirs, and the cysts resist chlorination) or spread person to person (daycare, MSM). Trophozoites attach to the duodenal mucosa with a ventral sucking disk and cause malabsorption: fatty diarrhea, bloating, and no invasion or blood. Diagnose with stool antigen or PCR, or by finding cysts or trophozoites. Treat with tinidazole, metronidazole, or nitazoxanide. IgA deficiency and hypogammaglobulinemia (CVID, XLA) cause chronic or recurrent giardiasis.",
  img="giardia.jpg"),
Q(T, "Entamoeba histolytica",
  "A 35-year-old man who recently returned from Mexico has bloody diarrhea with cramps. Stool shows the trophozoites pictured, containing ingested red blood cells. Weeks later he develops fever and right upper quadrant pain, and ultrasound shows a single liver abscess. What is the appropriate treatment?",
  ["Metronidazole followed by a luminal agent such as paromomycin", "Surgical drainage alone", "Albendazole", "Praziquantel", "Ivermectin"],
  "Entamoeba histolytica cysts are ingested fecal-orally. Invasive trophozoites cause flask-shaped colonic ulcers and amebic dysentery. Trophozoites that eat RBCs (erythrophagocytosis) are specific for E. histolytica, as opposed to non-pathogenic E. dispar. Spread through the portal vein causes liver abscess with 'anchovy paste' contents, usually without a positive stool at that stage. Diagnose with serology and antigen or PCR. Treat with metronidazole (tissue), then a luminal agent (paromomycin or iodoquinol) to clear cysts. Most abscesses do not need drainage.",
  img="entamoeba.jpg"),
Q(T, "Cryptosporidium",
  "A man with AIDS (CD4 40/μL) has had months of profuse watery diarrhea and weight loss. A modified acid-fast stain of stool is shown, with small red-staining oocysts (4–6 μm). Which statement about this organism is correct?",
  ["Its oocysts resist chlorine, so it causes waterborne outbreaks, and immune reconstitution with ART is key in AIDS", "It is killed by standard chlorination of drinking water", "It invades the liver and causes abscesses", "Metronidazole cures it in AIDS patients", "It is a helminth whose eggs are passed in stool"],
  "Cryptosporidium parvum and hominis are small apicomplexan parasites. Their oocysts are acid-fast and resist chlorine, causing outbreaks from pools and municipal water. In healthy hosts the diarrhea is self-limited (nitazoxanide can shorten it). In AIDS with low CD4 it causes chronic, severe watery diarrhea and can involve the biliary tree (sclerosing cholangitis). The main treatment is ART, since antiparasitic drugs work poorly. Filtering water prevents it. Cyclospora and Cystoisospora are also acid-fast but larger.",
  img="crypto-af.jpg"),
# ---------------- Toxoplasma ----------------
Q(T, "Toxoplasma: AIDS",
  "A 38-year-old man with AIDS (CD4 45/μL), not on prophylaxis, has headache, fever, confusion, and left hemiparesis. MRI shows multiple ring-enhancing lesions at the gray-white junction and basal ganglia. Toxoplasma IgG is positive. What is the treatment?",
  ["Pyrimethamine plus sulfadiazine plus leucovorin", "Amphotericin B plus flucytosine", "Metronidazole", "Albendazole plus steroids", "Whole-brain radiation"],
  "Toxoplasma gondii reactivates as encephalitis when CD4 falls below 100, causing multiple ring-enhancing lesions. The main alternative is primary CNS lymphoma (EBV-associated, usually a single periventricular lesion, positive EBV PCR in CSF). A response to empiric anti-Toxoplasma therapy within 2 weeks supports the diagnosis. Pyrimethamine inhibits DHFR, and leucovorin (folinic acid) protects the bone marrow. TMP-SMX is used for prophylaxis at CD4 below 100 in seropositive patients."),
Q(T, "Toxoplasma: congenital",
  "A newborn has chorioretinitis, hydrocephalus, and diffuse intracranial calcifications scattered through the brain parenchyma. The mother owns several outdoor cats and ate undercooked lamb during pregnancy. Which pregnancy recommendation would have lowered the risk?",
  ["Avoid handling cat litter and eating undercooked meat", "Avoid unpasteurized soft cheeses only", "Get the MMR vaccine during pregnancy", "Avoid mosquito exposure", "Take prophylactic acyclovir from 36 weeks"],
  "Cats are the definitive host. Oocysts are shed in cat feces, and tissue cysts are found in undercooked meat (pork, lamb, venison). Primary infection during pregnancy can cross the placenta, causing the triad of chorioretinitis, hydrocephalus, and diffuse intracranial calcifications, plus 'blueberry muffin' rash. Congenital CMV has periventricular calcifications and microcephaly. Spiramycin is used in pregnancy to lower transmission, and pyrimethamine-sulfadiazine to treat a confirmed fetal infection."),
# ---------------- Malaria ----------------
Q(T, "P. falciparum: severe malaria",
  "A 30-year-old woman returning from Nigeria has fever, confusion, seizures, jaundice, and dark urine. A thin blood smear is shown, containing crescent (banana)-shaped gametocytes. Parasitemia is 12%. What explains her cerebral symptoms?",
  ["Infected RBCs express PfEMP1, which binds endothelial receptors (ICAM-1) and blocks cerebral microvessels", "Hypnozoites in the liver release merozoites into the CSF", "Direct invasion of neurons by sporozoites", "Hemolysis-induced kernicterus", "Immune complex vasculitis of cerebral arteries"],
  "P. falciparum causes the most severe malaria. Infected RBCs develop knobs displaying PfEMP1, which binds ICAM-1, CD36, and EPCR on endothelium. This sequestration in the brain, kidney, lung, and placenta causes cerebral malaria, acute kidney injury ('blackwater fever' from hemoglobinuria), ARDS, hypoglycemia, and severe anemia. Smears show multiple small rings per cell and banana-shaped gametocytes. Severe malaria is treated with IV artesunate. Uncomplicated chloroquine-resistant malaria is treated with artemether-lumefantrine or atovaquone-proguanil.",
  img="pf-gametocyte.jpg"),
Q(T, "P. falciparum: blood smear",
  "A Giemsa-stained thin smear from a febrile traveler is shown: many small, delicate ring forms, some RBCs containing more than one ring, and double-dotted chromatin. No enlarged RBCs or Schüffner dots are seen. Which species is most likely, and why does it cause such high parasitemia?",
  ["P. falciparum; it infects RBCs of all ages", "P. vivax; it infects only reticulocytes", "P. malariae; it infects only old RBCs", "P. ovale; it infects only young RBCs", "Babesia microti; it forms Maltese crosses"],
  "P. falciparum invades RBCs of any age, so parasitemia can exceed 5–10%. P. vivax and ovale prefer reticulocytes and P. malariae prefers older RBCs, which limits their parasitemia. Mature trophozoites and schizonts are usually absent from falciparum smears because they sequester in microvessels. The fever pattern is irregular. Always suspect falciparum in a febrile traveler from sub-Saharan Africa.",
  img="pf-rings.jpg"),
Q(T, "P. vivax: hypnozoites",
  "A 25-year-old soldier treated for malaria after deployment in Afghanistan has another episode 7 months later. His blood smear 7 months earlier showed enlarged RBCs with stippling (Schüffner dots) and an amoeboid trophozoite, as shown. Which drug should have been added to prevent relapse, and what test is required first?",
  ["Primaquine (or tafenoquine); G6PD testing", "Chloroquine; hemoglobin electrophoresis", "Artesunate; ECG", "Mefloquine; psychiatric screening", "Doxycycline; pregnancy test"],
  "P. vivax and P. ovale form dormant liver hypnozoites that can reactivate months later. Blood-stage drugs (chloroquine, or artemisinin combinations for resistant vivax) do not reach them. Primaquine or tafenoquine eradicates hypnozoites but causes hemolysis in G6PD deficiency, so test first. Both avoid pregnancy. Vivax and ovale have 48-hour (tertian) fevers and enlarged RBCs with Schüffner dots. P. vivax enters RBCs through the Duffy antigen, so Duffy-negative people (common in West Africa) are resistant.",
  img="pvivax.jpg"),
Q(T, "Malaria: life cycle",
  "In the Plasmodium life cycle, which stage is injected into humans by the female Anopheles mosquito, and where does it go first?",
  ["Sporozoites, which travel to the liver and infect hepatocytes", "Merozoites, which infect red blood cells directly", "Gametocytes, which mature in the spleen", "Trophozoites, which infect macrophages", "Oocysts, which lodge in the lung"],
  "Anopheles injects sporozoites, which travel to hepatocytes and form schizonts (and hypnozoites in vivax and ovale). Merozoites are released and invade RBCs, going through ring, trophozoite, and schizont stages. RBC lysis on a cycle causes fever: every 48 hours for vivax and ovale (tertian), every 72 hours for malariae (quartan; nephrotic syndrome), and irregular for falciparum. Some parasites become gametocytes, which a mosquito takes up to complete sexual reproduction."),
Q(T, "Malaria: host protective factors",
  "Which host trait protects against P. falciparum malaria?",
  ["Sickle cell trait (HbAS)", "Duffy antigen positivity", "Blood group O deficiency", "Hereditary hemochromatosis", "Selective IgA deficiency"],
  "Traits selected in malaria-endemic areas: sickle cell trait (infected RBCs sickle and are cleared), α- and β-thalassemia, G6PD deficiency (oxidative stress kills parasites), hereditary ovalocytosis, and HbC. Duffy-negative RBCs resist P. vivax. Blood group O is associated with milder falciparum disease."),
Q(T, "Antimalarial drugs",
  "Chloroquine kills blood-stage Plasmodium. What is its mechanism, and how does P. falciparum become resistant?",
  ["It blocks heme polymerase so toxic free heme builds up in the food vacuole; resistance comes from the PfCRT transporter pumping it out", "It inhibits dihydrofolate reductase; resistance comes from DHFR mutations", "It inhibits the mitochondrial electron transport chain; resistance comes from cytochrome b mutations", "It forms free radicals by reacting with iron; resistance comes from the Kelch13 gene", "It blocks the Duffy antigen; resistance comes from Duffy-negative parasites"],
  "Chloroquine concentrates in the parasite food vacuole and blocks polymerization of heme into hemozoin, so toxic free heme builds up. PfCRT mutations pump chloroquine out, which is widespread in falciparum. Artemisinins form free radicals when activated by heme iron (Kelch13 mutations cause partial resistance). Atovaquone inhibits cytochrome bc1, proguanil inhibits DHFR, and mefloquine can cause neuropsychiatric effects. Primaquine acts on liver stages. Quinine and quinidine cause cinchonism."),
# ---------------- Babesia ----------------
Q(T, "Babesia",
  "A 70-year-old man without a spleen who lives on Nantucket has fever, fatigue, hemolytic anemia, and dark urine in July. A thin blood smear is shown, with small intraerythrocytic ring forms (arrow) and no hemozoin pigment. Elsewhere on the slide, a few rings are arranged in tetrads. What is the treatment?",
  ["Atovaquone plus azithromycin", "Chloroquine", "Doxycycline alone", "Primaquine", "Albendazole"],
  "Babesia microti is spread by Ixodes ticks in the Northeast and upper Midwest, often with Lyme or Anaplasma. It infects RBCs, causing hemolysis. Asplenia, old age, and immunosuppression lead to severe disease. Smear: rings without pigment, and Maltese cross tetrads that are pathognomonic. It resembles falciparum, but there is no travel history, no gametocytes, and no hemozoin. Treat with atovaquone plus azithromycin (clindamycin plus quinine if severe). Exchange transfusion is used for very high parasitemia.",
  img="babesia.jpg"),
# ---------------- Trypanosomes ----------------
Q(T, "Chagas disease",
  "A 45-year-old woman who grew up in rural Bolivia has progressive dyspnea, arrhythmias, and dilated cardiomyopathy. She also has dysphagia from megaesophagus and chronic constipation. As a child she had unilateral painless periorbital swelling like that in the right image. A peripheral smear from an acute case (left image) shows C- and S-shaped flagellated organisms. How is the parasite transmitted?",
  ["Feces of a reduviid (triatomine, 'kissing') bug rubbed into the bite wound or conjunctiva", "Bite of a tsetse fly", "Bite of a female sandfly", "Anopheles mosquito bite", "Eating undercooked pork"],
  "Trypanosoma cruzi causes Chagas disease in Latin America. The triatomine bug bites near the face and defecates, and infected feces enter the bite or conjunctiva (Romaña sign: unilateral periorbital swelling). Chronic disease destroys autonomic ganglia, causing dilated cardiomyopathy with apical aneurysm and arrhythmias, megaesophagus (secondary achalasia), and megacolon. It can also spread by transfusion, transplant, and from mother to fetus. Treat acute or young patients with benznidazole or nifurtimox.",
  img=["tcruzi.jpg", "romana.jpg"]),
Q(T, "African trypanosomiasis",
  "A traveler returning from a safari in East Africa had a painful chancre at a fly bite, then recurrent fevers, posterior cervical lymphadenopathy (Winterbottom sign), and later daytime somnolence and confusion. Why do the fevers recur in waves?",
  ["Antigenic variation of the variable surface glycoprotein (VSG) coat", "Periodic rupture of infected red blood cells", "Reactivation of hypnozoites in the liver", "Cyclic release of endotoxin", "Formation of cysts in skeletal muscle"],
  "Trypanosoma brucei rhodesiense (East African, acute) and gambiense (West African, chronic) are spread by tsetse flies. Trypomastigotes switch their VSG coat repeatedly, escaping antibody responses and causing waves of fever and parasitemia. Late stages invade the CNS (sleeping sickness). Treatment: suramin (blood-borne stage, rhodesiense) or fexinidazole/pentamidine (gambiense). Melarsoprol is used for CNS disease (arsenical; toxic). Eflornithine is combined with nifurtimox for gambiense CNS disease."),
# ---------------- Leishmania ----------------
Q(T, "Visceral leishmaniasis",
  "A 30-year-old man from Bihar, India, has months of fever, weight loss, massive splenomegaly, hepatomegaly, darkened skin, and pancytopenia. A splenic aspirate is shown: macrophages filled with small oval organisms, each with a nucleus and a rod-shaped kinetoplast. What is the vector, and what is the treatment?",
  ["Sandfly; liposomal amphotericin B", "Tsetse fly; suramin", "Reduviid bug; benznidazole", "Anopheles mosquito; artemether", "Ixodes tick; atovaquone"],
  "Leishmania donovani causes visceral leishmaniasis (kala-azar, 'black fever'). It is spread by female sandflies (Phlebotomus, Lutzomyia). Amastigotes live inside macrophages of the spleen, liver, and bone marrow, causing pancytopenia and hypergammaglobulinemia. Diagnose by finding amastigotes with kinetoplasts or by rK39 serology. Treat with liposomal amphotericin B. Sodium stibogluconate (pentavalent antimony) and miltefosine are alternatives. Histoplasma in macrophages lacks a kinetoplast.",
  img="leish-amast.jpg"),
Q(T, "Cutaneous leishmaniasis",
  "A soldier returning from Iraq has a painless ulcer on his forearm with raised, indurated edges, as shown, that has slowly grown over 2 months at the site of an insect bite. What is the most likely diagnosis?",
  ["Cutaneous leishmaniasis", "Cutaneous anthrax", "Sporotrichosis", "Pyoderma gangrenosum", "Mycobacterium marinum infection"],
  "Cutaneous leishmaniasis (L. major, L. tropica in the Old World; L. mexicana, L. braziliensis in the New World) causes a painless papule that becomes a volcano-like ulcer with raised edges at a sandfly bite. It is common in military members returning from the Middle East and Afghanistan. L. braziliensis can later cause destructive mucocutaneous disease of the nose and mouth ('espundia'). Diagnose with biopsy or scraping showing amastigotes, or PCR.",
  img="leish-ulcer.jpg"),
# ---------------- Trichomonas ----------------
Q(T, "Trichomonas vaginalis",
  "A 24-year-old woman has frothy, malodorous yellow-green discharge and vulvar itching. Vaginal pH is 6.0, and punctate cervical hemorrhages are seen. A stained specimen from culture is shown: pear-shaped trophozoites with anterior flagella and an undulating membrane. How should she be treated?",
  ["Metronidazole for her and her sexual partners", "Metronidazole for her only", "Fluconazole", "Ceftriaxone plus doxycycline", "Clindamycin cream"],
  "Trichomonas vaginalis is a sexually transmitted flagellated protozoan that exists only as a trophozoite (no cyst). It is diagnosed by NAAT or by seeing motile trophozoites on wet mount. It causes vaginitis (strawberry cervix), urethritis in men, and adverse pregnancy outcomes, and it increases HIV transmission. Treat with metronidazole (7 days for women) and treat partners at the same time.",
  img="trich.jpg"),
# ---------------- Free-living amebae ----------------
Q(T, "Naegleria fowleri",
  "A 12-year-old boy has severe headache, fever, stiff neck, altered smell, and seizures 5 days after swimming in a warm freshwater lake in Texas in August. CSF shows neutrophilic pleocytosis, low glucose, and amebic trophozoites like those shown. How did the organism reach the CNS?",
  ["Through the cribriform plate along olfactory nerves", "Hematogenous spread from a skin ulcer", "Through a contact lens injury to the cornea", "Retrograde axonal transport from a bite", "Through infected mosquito saliva"],
  "Naegleria fowleri, the 'brain-eating ameba,' lives in warm freshwater (lakes, hot springs, poorly chlorinated pools, and nasal rinsing with tap water). It enters the nose and travels through the cribriform plate along olfactory nerves, causing primary amebic meningoencephalitis, which is almost always fatal within days. Treatment includes amphotericin B and miltefosine. Acanthamoeba causes contact lens keratitis and granulomatous amebic encephalitis in immunocompromised hosts.",
  img="naegleria.jpg"),
Q(T, "Acanthamoeba keratitis",
  "A 25-year-old contact lens wearer who rinses her lenses in tap water has severe eye pain out of proportion to exam findings, photophobia, and a ring-shaped corneal infiltrate. Which organism is most likely?",
  ["Acanthamoeba", "Pseudomonas aeruginosa", "Herpes simplex virus", "Onchocerca volvulus", "Naegleria fowleri"],
  "Acanthamoeba keratitis occurs in contact lens wearers exposed to non-sterile water. It causes intense pain, a ring infiltrate, and perineural infiltrates. Diagnose with confocal microscopy, culture, or PCR of corneal scrapings (cysts are double-walled). Treat with topical biguanides (PHMB, chlorhexidine) and diamidines. Pseudomonas also causes contact lens keratitis but progresses faster with purulent discharge."),
]
