from qcore import Q
T = "Helminths"
QUESTIONS = [
# ---------------- Intestinal nematodes ----------------
Q(T, "Enterobius",
  "A 5-year-old girl wakes at night scratching her perianal area. Her mother presses clear tape to the perianal skin in the morning, and the slide shows the eggs pictured: oval, flattened on one side, with a thin shell and a larva inside. What is the most appropriate management?",
  ["Albendazole or pyrantel pamoate for the child and all household members, repeated in 2 weeks", "Praziquantel for the child only", "Metronidazole for the child only", "Ivermectin for the child and a stool ova and parasite exam in 1 week", "No treatment; the infection is self-limited"],
  "Enterobius vermicularis (pinworm) is the most common helminth infection in the US. Females lay eggs on the perianal skin at night, causing pruritus ani and autoinfection by the fecal-oral route. Eggs are found by the tape test, not in stool. Treat everyone in the household with albendazole, mebendazole, or pyrantel pamoate, repeated after 2 weeks to kill newly hatched worms. Wash bedding.",
  img="enterobius.jpg"),
Q(T, "Ascaris",
  "A 6-year-old in rural Guatemala had cough, wheezing, and eosinophilia with fleeting lung infiltrates. Weeks later he develops colicky abdominal pain and vomiting from intestinal obstruction. Stool shows the egg pictured: thick, bumpy (mammillated) shell. What explains the earlier pulmonary symptoms?",
  ["Larvae migrating through the lungs (Löffler syndrome)", "Hematogenous spread of adult worms to the lungs", "Allergic bronchopulmonary aspergillosis", "Cysts forming in the lung parenchyma", "Autoinfection with filariform larvae"],
  "Ascaris lumbricoides eggs are ingested from contaminated soil or food. Larvae hatch in the intestine, cross the gut wall, travel to the lungs, climb the trachea, and are swallowed to become adult worms in the small intestine. The lung phase causes Löffler syndrome (transient eosinophilic pneumonitis). Heavy worm burdens cause obstruction, biliary blockage, and malnutrition. Treat with albendazole or mebendazole.",
  img="ascaris.jpg"),
Q(T, "Strongyloides: hyperinfection",
  "A 60-year-old man from Jamaica starts high-dose prednisone for a COPD exacerbation. Two weeks later he develops diffuse abdominal pain, respiratory failure, a serpiginous periumbilical rash, and E. coli bacteremia with meningitis. Stool and sputum show the larvae pictured. Which feature of this parasite explains his condition?",
  ["It completes its life cycle inside the host (autoinfection), and corticosteroids allow uncontrolled multiplication", "Its eggs are ingested from soil and cause only intestinal obstruction", "It is transmitted by blackfly bites", "It forms hydatid cysts in the liver", "It is acquired from undercooked pork"],
  "Strongyloides stercoralis filariform larvae penetrate skin, migrate through the lungs, and become adults in the duodenum. Eggs hatch in the gut into rhabditiform larvae, which appear in stool. Some turn into filariform larvae and reinfect through the colon or perianal skin (autoinfection), so infection can persist for decades. Corticosteroids and HTLV-1 infection allow hyperinfection or dissemination, and larvae carry gut bacteria into the blood (Gram-negative sepsis, meningitis). Treat with ivermectin. Screen and treat people from endemic areas before immunosuppression. Larva currens is a fast-moving serpiginous rash.",
  img="strongy.jpg"),
Q(T, "Hookworm",
  "A 10-year-old who often walks barefoot in the rural southeastern US has fatigue, pallor, and an itchy rash on his feet from weeks earlier. Labs show microcytic anemia and eosinophilia. How does this parasite cause anemia?",
  ["Adult worms attach to the small intestinal mucosa and suck blood", "Larvae invade and lyse red blood cells", "Adults compete for vitamin B12 in the ileum", "Eggs obstruct the bile duct", "Larvae cause hemolysis in the lungs"],
  "Hookworms (Necator americanus, Ancylostoma duodenale) penetrate the skin of bare feet (ground itch), migrate through the lungs, and attach to the small intestine, where they feed on blood. This causes iron deficiency anemia. Treat with albendazole or mebendazole plus iron. Diphyllobothrium latum causes B12 deficiency. Dog and cat hookworm larvae cause cutaneous larva migrans, a creeping eruption."),
Q(T, "Trichinella",
  "Several family members develop fever, periorbital edema, severe muscle pain, splinter hemorrhages, and marked eosinophilia with elevated creatine kinase 2 weeks after eating undercooked bear meat from a hunting trip. What is the most likely organism?",
  ["Trichinella spiralis", "Taenia solium", "Toxoplasma gondii", "Toxocara canis", "Echinococcus granulosus"],
  "Trichinellosis comes from eating larvae encysted in undercooked meat: pork, bear, walrus, and wild game. Larvae mature in the intestine (GI symptoms), and new larvae spread through the blood and encyst in striated muscle ('nurse cells'). This causes fever, myositis, periorbital edema, eosinophilia, and high CK. Treat with albendazole plus steroids for severe myositis."),
Q(T, "Toxocara",
  "A 3-year-old who eats dirt at a playground frequented by dogs has fever, hepatomegaly, wheezing, and marked eosinophilia. Months later, a whitish retinal granuloma is found that could be mistaken for retinoblastoma. What is the organism?",
  ["Toxocara canis", "Ascaris lumbricoides", "Enterobius vermicularis", "Onchocerca volvulus", "Trichinella spiralis"],
  "Toxocara canis and cati (dog and cat roundworms) eggs are ingested from soil. Humans are dead-end hosts, and larvae migrate without maturing. This causes visceral larva migrans (fever, hepatomegaly, eosinophilia, wheezing) and ocular larva migrans (retinal granuloma, leukocoria). Treat with albendazole, plus steroids for eye disease."),
# ---------------- Tissue nematodes ----------------
Q(T, "Onchocerca",
  "A 40-year-old man who lived near fast-flowing rivers in West Africa has intensely itchy, thickened, depigmented skin ('leopard skin'), subcutaneous nodules, and progressive vision loss. What is the vector, and what is the treatment?",
  ["Blackfly (Simulium); ivermectin", "Mosquito; diethylcarbamazine", "Deer fly (Chrysops); albendazole", "Sandfly; amphotericin B", "Tsetse fly; suramin"],
  "Onchocerca volvulus ('river blindness') is spread by blackflies that breed in fast-flowing rivers. Adults live in skin nodules, and microfilariae move through the skin and eye, causing dermatitis, keratitis, and blindness. Diagnose with skin snips. Treat with ivermectin, which kills microfilariae ('iverMectin for river blindness'). Doxycycline kills adults by targeting their Wolbachia endosymbiont. Rapid microfilarial death can cause a Mazzotti inflammatory reaction."),
Q(T, "Loa loa",
  "A 35-year-old woman from Cameroon noticed a worm crossing the conjunctiva of her eye and has had recurring, transient, itchy swellings of her forearms. A daytime blood smear shows sheathed microfilariae, as shown. What is the vector, and why is care needed before giving ivermectin?",
  ["Deer fly (Chrysops); high microfilarial loads risk fatal encephalopathy after ivermectin or DEC", "Blackfly; ivermectin causes blindness", "Culex mosquito; ivermectin causes hemolysis", "Sandfly; ivermectin causes cardiotoxicity", "Tsetse fly; ivermectin is inactive"],
  "Loa loa (African eye worm) is spread by deer flies (mango flies) in the rainforests of Central and West Africa. It causes Calabar swellings (transient angioedema) and adult worms migrating across the eye. Microfilariae circulate in the daytime. Treat with diethylcarbamazine, but only if the microfilarial load is low. Heavy loads can cause fatal encephalopathy with DEC or ivermectin, so apheresis or albendazole is used first.",
  img="loa.jpg"),
Q(T, "Wuchereria bancrofti",
  "A man from coastal India has massive, hard swelling of one leg with thickened, fissured skin, shown, after years of recurrent fevers with lymphangitis. Blood smears drawn at midnight show microfilariae. What is the organism and vector?",
  ["Wuchereria bancrofti; mosquitoes", "Onchocerca volvulus; blackflies", "Loa loa; deer flies", "Dracunculus medinensis; copepods in water", "Schistosoma mansoni; freshwater snails"],
  "Lymphatic filariasis (Wuchereria bancrofti, Brugia malayi) is spread by mosquitoes. Adults block lymphatics, causing lymphedema, elephantiasis, and hydrocele over years. Microfilariae circulate at night (nocturnal periodicity). Treat with DEC or with ivermectin plus albendazole (mass drug administration). Doxycycline targets Wolbachia. Tropical pulmonary eosinophilia is an immune reaction to microfilariae in the lung.",
  img="elephantiasis.jpg"),
# ---------------- Cestodes ----------------
Q(T, "Taenia solium: transmission",
  "The scolex shown (four suckers and a double crown of hooks) was recovered from a patient's stool after treatment. The patient ate undercooked pork in rural Mexico. His household contact develops neurocysticercosis. How did the contact acquire cysticercosis?",
  ["Ingesting T. solium eggs shed in the carrier's feces (fecal-oral)", "Eating undercooked pork containing cysticerci", "Drinking water with copepods", "Skin penetration by larvae", "Mosquito bite"],
  "Taenia solium has two routes. Eating cysticerci in undercooked pork gives an intestinal tapeworm (taeniasis), usually mild. Ingesting eggs from human feces (from a tapeworm carrier, by the fecal-oral route) gives cysticercosis: larvae spread to tissues, including the brain, muscle, and eye. Vegetarians can get neurocysticercosis from carriers in the household. Treat taeniasis with praziquantel or niclosamide.",
  img="tsolium-scolex.jpg"),
Q(T, "Neurocysticercosis",
  "A 28-year-old man who immigrated from Honduras has new-onset seizures. Brain CT is shown, with multiple cystic lesions (some with a visible scolex) and scattered calcifications. What is the most appropriate treatment for viable cysts?",
  ["Albendazole with corticosteroids and antiseizure medication", "Metronidazole", "Pyrimethamine and sulfadiazine", "Liposomal amphotericin B", "Ivermectin"],
  "Neurocysticercosis is the most common cause of acquired epilepsy worldwide. Cysts appear as 'cyst with a dot' (scolex), and calcified dead cysts are also seen. Treat viable cysts with albendazole (± praziquantel) and steroids, which limit inflammation as dying cysts provoke edema, along with antiseizure drugs. Calcified lesions only need seizure control. Hydrocephalus may need a shunt.",
  img="ncc-ct.jpg"),
Q(T, "Echinococcus",
  "A 40-year-old sheep farmer from the Middle East has right upper quadrant fullness. Ultrasound shows a large liver cyst with daughter cysts and an eggshell-calcified wall. A surgical specimen is shown. Why must aspiration or surgery be done with extreme care?",
  ["Spillage of cyst fluid can cause anaphylaxis and seed new cysts", "The cyst contains bacteria that cause sepsis", "The cyst is malignant", "Aspiration causes massive bleeding from vascular malformations", "The fluid contains a neurotoxin"],
  "Echinococcus granulosus: dogs are definitive hosts and sheep are intermediate hosts. Humans ingest eggs from dog feces, and larvae form hydatid cysts (liver more often than lung) containing protoscolices ('hydatid sand'). Rupture releases antigenic fluid, which can cause anaphylaxis, and seeds daughter cysts. Treat with albendazole plus surgery or PAIR (puncture, aspiration, injection of hypertonic saline or ethanol, re-aspiration). E. multilocularis (foxes) causes an invasive, tumor-like alveolar liver lesion.",
  img="hydatid.jpg"),
Q(T, "Diphyllobothrium latum",
  "A 60-year-old man from Finland who regularly eats raw freshwater fish has fatigue, glossitis, a macrocytic anemia, and impaired vibration sense. Stool shows the egg pictured: operculated, with a small knob at the other end. What causes the anemia?",
  ["The tapeworm competes for vitamin B12 in the small intestine", "The worm sucks blood from the intestinal mucosa", "Larvae invade the bone marrow", "Eggs cause hemolysis", "The worm blocks iron absorption in the duodenum"],
  "Diphyllobothrium latum (fish tapeworm) comes from undercooked freshwater fish (sushi, gefilte fish, Scandinavia, Great Lakes). It can grow several meters long in the small intestine and absorbs dietary B12, causing megaloblastic anemia and neurologic deficits. Treat with praziquantel or niclosamide, plus B12.",
  img="dlatum.jpg"),
# ---------------- Trematodes ----------------
Q(T, "Schistosoma mansoni",
  "A 35-year-old man from Egypt has hematemesis from esophageal varices and splenomegaly, but normal liver function. Liver biopsy shows periportal ('pipestem') fibrosis with granulomas around eggs. Stool shows the egg pictured, with a large lateral spine. How was the infection acquired?",
  ["Cercariae penetrating the skin in freshwater with snails", "Eating raw freshwater fish", "Eating undercooked crab", "Mosquito bite", "Eating eggs in contaminated soil"],
  "Snails release cercariae into freshwater, and cercariae penetrate the skin (swimmer's itch). Schistosomes live in venous plexuses. S. mansoni (Africa, South America; lateral spine) and S. japonicum (Asia; small spine) live in mesenteric veins. Eggs lodge in the portal venules and trigger Th2 granulomas and fibrosis. The result is presinusoidal portal hypertension with preserved liver function. Treat with praziquantel.",
  img="schisto-mansoni.jpg"),
Q(T, "Schistosoma haematobium",
  "A 40-year-old farmer from the Nile delta has painless hematuria. Cystoscopy shows a bladder mass. Urine microscopy shows the egg pictured, with a terminal spine. What type of bladder cancer is associated with this infection?",
  ["Squamous cell carcinoma", "Urothelial (transitional cell) carcinoma", "Adenocarcinoma of the urachus", "Small cell carcinoma", "Rhabdomyosarcoma"],
  "Schistosoma haematobium lives in the vesical venous plexus. Eggs with terminal spines pass in urine and cause chronic granulomatous cystitis, hematuria, obstructive uropathy, and female genital schistosomiasis. Chronic irritation and squamous metaplasia lead to squamous cell carcinoma of the bladder. Treat with praziquantel, which increases the worm's calcium permeability and causes paralysis.",
  img="schisto-haem.jpg"),
Q(T, "Clonorchis & Paragonimus",
  "A 55-year-old man from Korea who often eats raw freshwater fish has recurrent biliary obstruction and cholangitis, and is later diagnosed with cholangiocarcinoma. What is the most likely parasite?",
  ["Clonorchis sinensis", "Paragonimus westermani", "Schistosoma japonicum", "Fasciola hepatica", "Echinococcus multilocularis"],
  "Clonorchis sinensis and Opisthorchis (Chinese liver fluke) come from undercooked freshwater fish and live in the bile ducts. They cause cholangitis, pigmented stones, and cholangiocarcinoma. Paragonimus westermani (lung fluke) comes from undercooked crabs and crayfish and causes hemoptysis and cavitary lung lesions that mimic TB. Both are treated with praziquantel. Fasciola hepatica comes from watercress."),
# ---------------- Immunology & drugs ----------------
Q(T, "Helminth immunity: eosinophils",
  "Which immune mechanism is most important for defense against tissue-invasive helminths?",
  ["IgE-coated worms trigger eosinophil degranulation (major basic protein) via ADCC, driven by Th2 cytokines (IL-4, IL-5, IL-13)", "Neutrophil oxidative burst driven by IL-17", "Cytotoxic CD8 T-cell killing of infected cells", "Complement-mediated lysis by C5b-9", "Interferon-α from plasmacytoid dendritic cells"],
  "Helminths are too large to be engulfed. Th2 responses (IL-4, class switch to IgE; IL-5, eosinophil production; IL-13, mucus and gut motility) coat worms with IgE. Eosinophils bind through FcεRI and release major basic protein and other toxic granule proteins. Eosinophilia is typical when helminths invade tissue (Strongyloides, Ascaris larval migration, Trichinella, Toxocara, filariae, Schistosoma). Protozoa usually do not cause eosinophilia."),
Q(T, "Anthelmintic drugs",
  "Which pairing of anthelmintic and mechanism is correct?",
  ["Albendazole — binds β-tubulin and blocks microtubule polymerization and glucose uptake", "Praziquantel — binds glutamate-gated chloride channels", "Ivermectin — increases calcium permeability", "Pyrantel pamoate — inhibits β-tubulin", "Diethylcarbamazine — inhibits DNA gyrase"],
  "Albendazole and mebendazole bind β-tubulin and block glucose uptake. They are broad for nematodes and some cestodes (cysticercosis, hydatid). They are teratogenic. Pyrantel pamoate is a nicotinic agonist causing depolarizing (spastic) paralysis. Ivermectin activates glutamate-gated chloride channels (Strongyloides, Onchocerca, scabies, lice). Praziquantel increases calcium permeability (trematodes and cestodes: schistosomes, tapeworms, flukes). Diethylcarbamazine is used for Loa loa and Wuchereria."),
]
