from qcore import Q
T = "Infections by System & Vaccines"
QUESTIONS = [
Q(T, "Meningitis by age",
  "A 2-week-old neonate has fever, poor feeding, and a bulging fontanelle. CSF shows neutrophilic pleocytosis and low glucose. Which empiric regimen covers the three most common causes at this age?",
  ["Ampicillin plus cefotaxime (or gentamicin)", "Ceftriaxone plus vancomycin", "Vancomycin alone", "Acyclovir alone", "Azithromycin plus ceftriaxone"],
  "Meningitis by age: 0–6 months — group B strep, E. coli, Listeria (ampicillin covers Listeria; cefotaxime or gentamicin covers GBS and E. coli; add acyclovir if HSV is possible). 6 months to 6 years — S. pneumoniae, N. meningitidis, Hib (unvaccinated), enteroviruses. 6–60 years — N. meningitidis, enteroviruses, S. pneumoniae, HSV. Over 60 — S. pneumoniae, N. meningitidis, Listeria. Ceftriaxone is avoided in neonates with hyperbilirubinemia or IV calcium."),
Q(T, "CSF interpretation",
  "A 40-year-old man from Haiti has 3 weeks of headache, low-grade fever, and new cranial nerve VI palsy. CSF: opening pressure elevated, 250 WBC/μL (mostly lymphocytes), protein 250 mg/dL, glucose 25 mg/dL. MRI shows basilar meningeal enhancement. What is the most likely cause?",
  ["Mycobacterium tuberculosis", "Enterovirus", "Neisseria meningitidis", "HSV-1", "Guillain-Barré syndrome"],
  "CSF patterns: Bacterial — neutrophils, high protein, low glucose. Viral — lymphocytes, normal or slightly high protein, normal glucose. TB and fungal — lymphocytes, very high protein, low glucose, high opening pressure. TB meningitis is subacute and involves the base of the brain, causing cranial neuropathies and hydrocephalus. Guillain-Barré shows high protein with a normal cell count (albuminocytologic dissociation)."),
Q(T, "Pneumonia by host",
  "Which pairing of patient setting and most characteristic pneumonia pathogen is correct?",
  ["Cystic fibrosis — Pseudomonas aeruginosa", "Healthy college student with walking pneumonia — Klebsiella pneumoniae", "Post-influenza cavitary pneumonia — Mycoplasma pneumoniae", "Alcohol use disorder with currant-jelly sputum — Legionella", "Neonate in the first week — Streptococcus pneumoniae"],
  "Typical associations: neonates — GBS, E. coli. Infants and children — RSV, other viruses, S. pneumoniae. Young adults (dorms, military) — Mycoplasma, C. pneumoniae. Community-acquired overall — S. pneumoniae. Post-influenza — S. aureus, S. pneumoniae, H. influenzae. Alcoholism/aspiration — Klebsiella, anaerobes. CF — S. aureus (early), Pseudomonas, Burkholderia cepacia. Hospital/ventilator — Pseudomonas, S. aureus, Gram-negative rods. AIDS — Pneumocystis."),
Q(T, "UTI organisms & urinalysis",
  "A 22-year-old woman has dysuria. Urinalysis shows leukocyte esterase positive and nitrite negative. Culture grows Gram-positive cocci in chains that are catalase-negative and grow in 6.5% NaCl. Why was the nitrite test negative?",
  ["Enterococcus does not reduce nitrate to nitrite", "The organism is urease-positive", "The organism has no cell wall", "The urine pH was too low", "Nitrite is positive only in pyelonephritis"],
  "The nitrite test detects Enterobacterales (E. coli, Klebsiella, Proteus), which reduce dietary nitrate to nitrite. Gram-positives such as Enterococcus and S. saprophyticus, and Pseudomonas, usually do not, so nitrite can be negative. Leukocyte esterase shows pyuria. UTI causes: E. coli (most common), S. saprophyticus (young women), Klebsiella, Proteus (alkaline urine, struvite), Enterococcus, Pseudomonas and Serratia (hospital or catheter-associated)."),
Q(T, "Osteomyelitis associations",
  "Which pairing of clinical setting and likely osteomyelitis organism is correct?",
  ["Nail puncture through a sneaker — Pseudomonas aeruginosa", "Sickle cell disease — Pasteurella multocida", "Cat bite — Salmonella", "Injection drug use — Mycobacterium tuberculosis only", "Vertebral osteomyelitis in a TB-endemic region — Kingella kingae"],
  "S. aureus is the most common cause overall. Associations: sexually active young adults — N. gonorrhoeae (septic arthritis more than osteomyelitis). Sickle cell — Salmonella. Prosthetic joints — S. aureus, S. epidermidis. Vertebrae (Pott disease) — M. tuberculosis. Cat or dog bites — Pasteurella. Injection drug use — S. aureus, Pseudomonas, Candida. Sneaker puncture — Pseudomonas. Diabetic foot — polymicrobial. Young children — Kingella kingae."),
Q(T, "Bloody vs watery diarrhea",
  "Which organism typically causes bloody (inflammatory) diarrhea rather than watery (non-inflammatory) diarrhea?",
  ["Campylobacter jejuni", "Vibrio cholerae", "Enterotoxigenic E. coli", "Giardia lamblia", "Norovirus"],
  "Bloody diarrhea: Campylobacter, Salmonella (non-typhoidal), Shigella, EHEC (O157:H7), EIEC, Yersinia, C. difficile (sometimes), and Entamoeba histolytica. Watery diarrhea: V. cholerae, ETEC, C. perfringens, Giardia, Cryptosporidium, and viruses (norovirus, rotavirus, adenovirus). Fecal leukocytes and fever point to an invasive, inflammatory process."),
Q(T, "Food poisoning by incubation",
  "Which food poisoning organism has the shortest incubation period because of a preformed toxin?",
  ["Staphylococcus aureus", "Clostridium perfringens", "Salmonella enteritidis", "Listeria monocytogenes", "Campylobacter jejuni"],
  "Preformed toxins act within 1–6 hours: S. aureus (meats, mayonnaise, custards) and B. cereus emetic toxin (reheated rice). C. perfringens takes 8–16 hours (reheated meat). Infections needing growth in the gut take longer: Salmonella (poultry, eggs) and Campylobacter take 1–3 days. Listeria can take weeks. C. botulinum symptoms usually start 12–36 hours after eating preformed neurotoxin in canned foods."),
Q(T, "TORCH infections",
  "Which pairing of congenital infection and classic finding is correct?",
  ["Rubella — cataracts, sensorineural deafness, and patent ductus arteriosus", "CMV — diffuse intracranial calcifications with hydrocephalus", "Toxoplasmosis — periventricular calcifications and deafness as the main finding", "Syphilis — limb hypoplasia and cicatricial scars", "HSV — Hutchinson teeth"],
  "TORCHHeS: Toxoplasma — chorioretinitis, hydrocephalus, diffuse (scattered) calcifications. Rubella — PDA, cataracts, deafness, blueberry muffin rash. CMV — periventricular calcifications, microcephaly, sensorineural hearing loss (most common). HIV. HSV — skin, eye, mouth vesicles, encephalitis, disseminated disease. Syphilis — early: rhinitis, rash, osteochondritis. Late: Hutchinson teeth, saddle nose, saber shins, deafness. Varicella causes limb hypoplasia and scars. Parvovirus causes hydrops fetalis. Zika causes microcephaly."),
Q(T, "Genital ulcers",
  "Which pairing of genital ulcer and organism is correct?",
  ["Painful, soft ulcer with ragged edges and painful suppurative lymph nodes — Haemophilus ducreyi", "Painless indurated ulcer with rubbery nodes — HSV-2", "Painful grouped vesicles on an erythematous base — Treponema pallidum", "Painless beefy-red ulcer that bleeds easily, with Donovan bodies — Chlamydia trachomatis L1–L3", "Painless transient papule then painful inguinal buboes — Klebsiella granulomatis"],
  "Painful: HSV (grouped vesicles, then shallow ulcers; tender nodes) and chancroid (H. ducreyi; soft, purulent ulcer, suppurative buboes). Painless: primary syphilis (indurated clean-based chancre, rubbery nodes), LGV (C. trachomatis L1–L3; transient papule, then painful buboes and proctitis), and donovanosis (Klebsiella granulomatis; beefy-red, granulating ulcer with Donovan bodies in macrophages)."),
Q(T, "Childhood rashes",
  "Which pairing of childhood exanthem and cause is correct?",
  ["High fever for 3–5 days, then rash appearing as the fever resolves — HHV-6", "Slapped cheeks and a lacy rash — rubella", "Sandpaper rash, strawberry tongue, circumoral pallor — parvovirus B19", "Cough, coryza, conjunctivitis, Koplik spots, then a descending rash — coxsackie A", "Vesicles on the palms, soles, and mouth — measles"],
  "Roseola (HHV-6) — fever first, then rash as the fever breaks. Erythema infectiosum (parvovirus B19) — slapped cheeks, lacy reticular rash. Scarlet fever (GAS) — sandpaper rash, strawberry tongue, Pastia lines. Measles — 3 Cs, Koplik spots, descending maculopapular rash. Rubella — mild illness, postauricular nodes, descending pink rash. Hand-foot-mouth (coxsackie A) — oral ulcers and palm and sole vesicles. Varicella — crops of lesions in different stages. Kawasaki disease (not infectious) can mimic scarlet fever."),
Q(T, "Rashes on palms and soles",
  "Which infection characteristically involves the palms and soles?",
  ["Rocky Mountain spotted fever", "Epidemic typhus", "Pityriasis rosea", "Varicella in children", "Tinea versicolor"],
  "Rashes on the palms and soles ('you drive CARS using your palms and soles'): Coxsackie A (hand-foot-mouth), RMSF, secondary Syphilis. Others include Kawasaki disease (palm and sole erythema and desquamation), toxic shock syndrome (desquamation), and infective endocarditis (Janeway lesions). Epidemic typhus spares the palms and soles."),
Q(T, "Live vaccines",
  "A 28-year-old woman who is 12 weeks pregnant asks which vaccines she should avoid. Which vaccine is contraindicated in pregnancy?",
  ["Measles-mumps-rubella", "Tdap", "Inactivated influenza vaccine", "Hepatitis B vaccine", "RSV prefusion F vaccine (at 32–36 weeks)"],
  "Live attenuated vaccines are contraindicated in pregnancy and severe immunosuppression: MMR, varicella, live zoster (no longer used in the US), yellow fever, intranasal influenza, oral typhoid, oral polio, BCG, rotavirus, dengue, and oral cholera. HIV-positive patients with CD4 at or above 200 can receive MMR and varicella. Recommended during pregnancy: Tdap (27–36 weeks), inactivated influenza, COVID-19, RSV (32–36 weeks, seasonal). Live vaccines produce strong cellular and humoral immunity."),
Q(T, "Vaccine types",
  "Which vaccine consists of an inactivated bacterial exotoxin (toxoid)?",
  ["Tetanus", "Hepatitis B", "HPV", "Varicella", "Pneumococcal conjugate"],
  "Vaccine types: Toxoid — tetanus, diphtheria. Subunit/recombinant — HBV (HBsAg), HPV (L1 VLPs), recombinant zoster (gE), acellular pertussis, MenB proteins. Conjugate polysaccharide — Hib, pneumococcal (PCV), meningococcal (MenACWY). Pure polysaccharide — PPSV23, typhoid Vi. Killed/inactivated — rabies, influenza (injection), polio (IPV), hepatitis A ('RIP Always'). Live — MMR, varicella, yellow fever, rotavirus, intranasal flu, BCG, oral typhoid. mRNA — COVID-19, RSV (mRESVIA)."),
Q(T, "Passive immunization",
  "Which exposure is managed with both preformed antibodies (passive) and vaccine (active)?",
  ["Hepatitis B exposure in the newborn of an HBsAg-positive mother", "Influenza exposure in a healthy adult", "Measles exposure in an immune adult", "Pertussis exposure in a vaccinated adult", "Norovirus exposure on a cruise ship"],
  "Passive antibodies give immediate but short-lived protection. Preformed antibodies are used for Tetanus, Botulism, HBV, Varicella, Rabies, and Diphtheria ('To Be Healed Very Rapidly, Don't wait'), plus RSV (nirsevimab) and snake venom. Combined passive and active immunization is used for HBV in neonates, tetanus-prone wounds in the unvaccinated, and rabies post-exposure. Maternal IgG crosses the placenta, and IgA in breast milk protects the infant's gut."),
Q(T, "Bite wounds",
  "A 25-year-old man punched someone in the mouth and has a laceration over his knuckle that is now red and swollen. Which organism is especially associated with this injury?",
  ["Eikenella corrodens", "Pasteurella multocida", "Capnocytophaga canimorsus", "Bartonella henselae", "Francisella tularensis"],
  "'Fight bite' (clenched-fist injury) infections are polymicrobial with oral flora: Eikenella corrodens (a HACEK Gram-negative rod that pits agar), streptococci, S. aureus, and anaerobes. Treat with amoxicillin-clavulanate and often surgical exploration. Cat bites → Pasteurella. Dog bites → Pasteurella, and Capnocytophaga canimorsus (fulminant sepsis in asplenic or alcoholic patients). Cat scratches → Bartonella."),
Q(T, "Infections and cancer",
  "Which pairing of infectious agent and associated cancer is correct?",
  ["Schistosoma haematobium — squamous cell carcinoma of the bladder", "HHV-8 — nasopharyngeal carcinoma", "HTLV-1 — Burkitt lymphoma", "H. pylori — esophageal adenocarcinoma", "Clonorchis sinensis — hepatocellular carcinoma from aflatoxin"],
  "Oncogenic infections: EBV (Burkitt lymphoma, Hodgkin lymphoma, nasopharyngeal carcinoma, PTLD, primary CNS lymphoma). HBV and HCV (HCC). HHV-8 (Kaposi sarcoma, primary effusion lymphoma). HPV (cervical, anal, penile, oropharyngeal SCC). HTLV-1 (adult T-cell leukemia/lymphoma). H. pylori (gastric adenocarcinoma, MALT lymphoma). Schistosoma haematobium (bladder SCC). Clonorchis/Opisthorchis (cholangiocarcinoma). Merkel cell polyomavirus (Merkel cell carcinoma). Aspergillus flavus aflatoxin (HCC)."),
Q(T, "Hospital-acquired infections",
  "A patient with an indwelling urinary catheter for 10 days develops fever. Which organism is most often responsible for catheter-associated UTIs?",
  ["Escherichia coli", "Streptococcus pyogenes", "Legionella pneumophila", "Neisseria gonorrhoeae", "Mycoplasma pneumoniae"],
  "Common hospital infections: CAUTI — E. coli, Klebsiella, Enterococcus, Pseudomonas, Candida. Central line infections — S. epidermidis, S. aureus, Candida. Ventilator-associated pneumonia — Pseudomonas, S. aureus (MRSA), Acinetobacter, Klebsiella. Surgical site infections — S. aureus. Antibiotic-associated diarrhea — C. difficile. Water or air systems — Legionella, Aspergillus (construction)."),
Q(T, "Infections in immune deficiency",
  "Which pairing of immune defect and typical infection is correct?",
  ["X-linked (Bruton) agammaglobulinemia — recurrent encapsulated bacterial sinopulmonary infections and enteroviral encephalitis", "Terminal complement deficiency — Pneumocystis pneumonia", "DiGeorge syndrome — recurrent Neisseria bacteremia", "Chronic granulomatous disease — recurrent Giardia", "Asplenia — Candida esophagitis"],
  "B-cell defects (XLA, CVID) — encapsulated bacteria (S. pneumoniae, H. influenzae), enteroviruses, Giardia. T-cell defects (DiGeorge, HIV) — intracellular organisms, fungi (Candida, Pneumocystis), viruses (CMV, HSV). SCID — everything. Terminal complement (C5–C9) — Neisseria. Neutrophil and phagocyte defects (CGD, LAD, neutropenia) — S. aureus, catalase-positive organisms, Aspergillus, Candida. Asplenia — encapsulated organisms, Babesia, Capnocytophaga."),
Q(T, "Epidemiology: vectors",
  "Which pairing of vector and disease is correct?",
  ["Aedes mosquito — dengue, Zika, chikungunya, and yellow fever", "Anopheles mosquito — West Nile virus", "Ixodes tick — Rocky Mountain spotted fever", "Tsetse fly — Chagas disease", "Sandfly — African sleeping sickness"],
  "Vectors: Aedes — dengue, Zika, chikungunya, yellow fever. Anopheles — malaria. Culex — West Nile, St. Louis encephalitis, filariasis. Ixodes — Lyme, babesiosis, anaplasmosis, Powassan. Dermacentor — RMSF, tularemia, tick paralysis. Amblyomma — ehrlichiosis, southern tick-associated rash illness, alpha-gal. Body louse — epidemic typhus, trench fever, relapsing fever. Flea — plague, murine typhus. Reduviid bug — Chagas. Tsetse fly — African trypanosomiasis. Sandfly — leishmaniasis. Blackfly — onchocerciasis. Deer fly — Loa loa, tularemia."),
Q(T, "Epidemiology: geography",
  "A physician in Arizona evaluates a patient with pneumonia, erythema nodosum, and arthralgias after a dust storm. Which pairing of region and endemic fungus is correct?",
  ["Southwestern US — Coccidioides", "Great Lakes and Mississippi/Ohio basins — Paracoccidioides", "Latin America — Blastomyces", "Ohio and Mississippi River valleys — Coccidioides", "Worldwide pigeon droppings — Histoplasma only"],
  "Endemic fungi: Histoplasma — Ohio and Mississippi River valleys (bird and bat droppings, caves). Blastomyces — Great Lakes, Ohio and Mississippi basins, southeast. Coccidioides — southwestern US desert soil, dust storms, earthquakes. Paracoccidioides — Latin America. Cryptococcus neoformans — worldwide, pigeon droppings. C. gattii — Pacific Northwest and eucalyptus trees. Talaromyces marneffei — Southeast Asia (in HIV)."),
]
