from qcore import Q
GPC = "Gram+ Cocci"
GPR = "Gram+ Rods & Branching"
GNR = "Gram− Cocci & Respiratory Rods"
ENT = "Enteric Gram− Rods"
ZOO = "Zoonotic Bacteria"
SPI = "Spirochetes"
RIC = "Rickettsiae & Chlamydiae"
MYC = "Mycobacteria"
OTH = "Mycoplasma & Other Bacteria"
HIV = "HIV & Antiretrovirals"
QUESTIONS = [
# ---------------- Gram-positive cocci ----------------
Q(GPC, "S. epidermidis: contaminant vs true infection",
  "A 60-year-old man admitted for pneumonia has one of four blood culture bottles grow coagulase-negative staphylococci after 3 days. He has no intravascular devices and is improving on ceftriaxone. What is the most appropriate interpretation?",
  ["Likely skin contaminant; no treatment for the isolate is needed", "True bacteremia requiring 6 weeks of vancomycin", "Endocarditis requiring echocardiography and surgery", "Evidence of MRSA requiring decolonization", "Evidence of toxic shock syndrome"],
  "S. epidermidis is the most common blood culture contaminant because it colonizes skin. A single positive bottle out of several, slow growth, and no prosthetic material suggest contamination. It is a true pathogen when it grows in multiple sets in patients with central lines, prosthetic valves, joints, or shunts. Then treat with vancomycin (most strains are methicillin-resistant) and remove the device when possible."),
Q(GPC, "S. saprophyticus: virulence & treatment",
  "A 21-year-old woman has her first uncomplicated cystitis. Urine grows coagulase-negative, novobiocin-resistant staphylococci. Which statement is correct?",
  ["It adheres well to uroepithelial cells, is urease-positive, and is treated with standard cystitis regimens such as nitrofurantoin or TMP-SMX", "It is a skin contaminant and should not be treated", "It is intrinsically resistant to all oral antibiotics", "It causes cystitis mainly in catheterized elderly men", "It is identified by optochin sensitivity"],
  "S. saprophyticus is part of normal perineal and GI flora in some women. Surface adhesins let it bind uroepithelium well, so it is the second most common cause of uncomplicated cystitis in young, sexually active women. It is urease-positive (can raise urine pH), coagulase-negative, and novobiocin-resistant. It responds to nitrofurantoin, TMP-SMX, or fluoroquinolones."),
Q(GPC, "Viridans streptococci: caries & treatment",
  "Which viridans streptococcus is most responsible for dental caries, and how is viridans strep endocarditis treated when the isolate is highly penicillin-susceptible?",
  ["Streptococcus mutans; penicillin G or ceftriaxone for 4 weeks", "Streptococcus sanguinis; vancomycin plus rifampin", "Streptococcus mitis; clindamycin alone", "Streptococcus mutans; metronidazole", "Streptococcus anginosus; doxycycline"],
  "S. mutans ferments dietary sucrose into acid, which demineralizes enamel, and makes glucans (dextrans) that build plaque. Viridans streptococci are α-hemolytic, optochin-resistant, and bile-insoluble. Endocarditis from penicillin-susceptible strains is treated with IV penicillin G or ceftriaxone for 4 weeks. The S. anginosus (milleri) group causes abscesses (brain, liver, lung)."),
# ---------------- Gram-positive rods ----------------
Q(GPR, "Listeria: epidemiology",
  "A multistate outbreak of febrile illness, meningitis, and pregnancy loss is traced to cantaloupe and deli meat stored in refrigerators. Which property of the pathogen explains why refrigeration did not prevent the outbreak?",
  ["It can grow at 4°C", "It forms heat-resistant spores", "It produces a preformed heat-stable toxin", "It requires a mosquito vector", "It is killed only by boiling"],
  "Listeria monocytogenes multiplies at refrigerator temperatures, so it can reach high levels in ready-to-eat foods (deli meats, hot dogs, soft cheeses, smoked seafood, raw sprouts, melons). High-risk groups (pregnant women, neonates, adults over 65, immunosuppressed) are advised to avoid these foods or reheat them until steaming. Listeria does not form spores."),
Q(GPR, "Botulism: wound & adult",
  "A 32-year-old man who injects black tar heroin under the skin develops diplopia, ptosis, dysphagia, and descending weakness. He has no GI symptoms. What is the most likely mechanism of disease, and what is the key treatment?",
  ["Wound botulism: spores germinate in the abscess and make toxin; give equine heptavalent antitoxin", "Foodborne botulism: preformed toxin; give human botulism immune globulin (BabyBIG)", "Tetanus: toxin blocks glycine release; give diazepam only", "Myasthenia gravis: anti-AChR antibodies; give pyridostigmine", "Guillain-Barré: molecular mimicry; give IVIG"],
  "Wound botulism happens when spores in contaminated drugs or soil germinate in anaerobic, devitalized tissue (skin popping with black tar heroin). Adult botulism of any type is treated with heptavalent equine antitoxin as early as possible, plus wound debridement and ventilator support. Antitoxin neutralizes only circulating toxin, so recovery requires regrowth of nerve terminals over weeks. The same toxin (onabotulinumtoxinA) is used therapeutically for dystonia, spasticity, and migraine."),
Q(GPR, "Neonatal tetanus",
  "In a rural area without prenatal care, a 7-day-old infant develops poor feeding, irritability, rigidity, and spasms after the umbilical stump was covered with animal dung. What is the most effective prevention?",
  ["Tetanus toxoid vaccination of the mother before or during pregnancy, plus clean cord care", "Erythromycin eye ointment at birth", "Neonatal BCG vaccination", "Oral penicillin for all newborns", "Hepatitis B vaccine at birth"],
  "Neonatal tetanus comes from C. tetani spores contaminating the umbilical stump. It is prevented by immunizing women (maternal antitoxin IgG crosses the placenta) and by clean delivery and cord care. It remains a significant cause of neonatal death in some low-income regions."),
Q(GPR, "Actinomyces: pelvic infection",
  "A 38-year-old woman with an intrauterine device in place for 8 years has pelvic pain, weight loss, and an adnexal mass. Pathology shows abscesses with yellow granules containing branching Gram-positive filaments. What is the organism, and what is its normal habitat?",
  ["Actinomyces israelii; normal flora of the mouth and GI/genital tract", "Nocardia asteroides; soil", "Mycobacterium tuberculosis; human lungs", "Aspergillus fumigatus; decaying vegetation", "Clostridium perfringens; soil and colon"],
  "Actinomyces is an anaerobic, non–acid-fast, branching Gram-positive normal flora organism. It causes infection only after disruption of the mucosa or with foreign bodies: cervicofacial (dental), thoracic (aspiration), abdominal (appendicitis, bowel surgery), and pelvic (long-term IUD). It crosses tissue planes and forms sinus tracts. Treat with long-term penicillin and remove the IUD."),
Q(GPR, "Nocardia: skin & microbiology",
  "A farmer in Mexico has a chronic, painless swelling of his foot with multiple draining sinuses that discharge grains. Cultures grow aerobic, weakly acid-fast, branching filaments. What is the diagnosis?",
  ["Actinomycetoma from Nocardia brasiliensis", "Chromoblastomycosis", "Sporotrichosis", "Gas gangrene", "Cellulitis from Streptococcus pyogenes"],
  "Mycetoma is a chronic subcutaneous infection from traumatic inoculation, usually in the feet of rural workers. It forms swelling, sinus tracts, and grains. It can be bacterial (actinomycetoma: Nocardia brasiliensis, Actinomadura, Streptomyces), treated with TMP-SMX-based regimens, or fungal (eumycetoma), treated with antifungals plus surgery. Nocardia is aerobic, catalase-positive, urease-positive, and weakly acid-fast, unlike Actinomyces."),
# ---------------- Gram-negative cocci / respiratory ----------------
Q(GNR, "N. meningitidis: epidemiology",
  "Large epidemics of meningococcal meningitis occur during the dry season across sub-Saharan Africa from Senegal to Ethiopia. Travelers to this region and to Hajj pilgrimage in Saudi Arabia are advised to get which vaccine?",
  ["Quadrivalent meningococcal conjugate vaccine (MenACWY)", "Serogroup B vaccine only", "BCG", "Typhoid Vi vaccine", "Japanese encephalitis vaccine"],
  "The 'meningitis belt' of Africa historically had serogroup A epidemics, now reduced by MenAfriVac; serogroups C, W, and X also occur. MenACWY is required for Hajj and Umrah. In the US, disease is mostly serogroups B, C, and Y, affecting infants, adolescents, college dormitory residents, military recruits, MSM (outbreaks), and people with complement deficiency or asplenia. Nasopharyngeal carriage is common, and pili and the capsule are key virulence factors."),
Q(GNR, "H. influenzae: meningitis management",
  "An unvaccinated 18-month-old has meningitis with Gram-negative coccobacilli in the CSF. What is the appropriate treatment, and what is given to unvaccinated household children under 4?",
  ["Ceftriaxone (with dexamethasone); rifampin prophylaxis for household contacts", "Ampicillin alone; no prophylaxis", "Vancomycin; azithromycin prophylaxis", "Gentamicin; ciprofloxacin prophylaxis", "Penicillin G; penicillin V prophylaxis"],
  "Many H. influenzae strains make β-lactamase, so invasive Hib infection (meningitis, epiglottitis) is treated with ceftriaxone or cefotaxime. Dexamethasone given before antibiotics lowers hearing loss in Hib meningitis. Rifampin eliminates nasopharyngeal carriage and is given to household contacts when any child under 4 is not fully vaccinated or is immunocompromised. H. influenzae is naturally transformable and makes IgA protease."),
Q(GNR, "Pertussis: clinical stages",
  "A 30-year-old vaccinated in childhood has 5 weeks of cough. She had 1 week of mild cold symptoms, then violent coughing fits ending in gagging or vomiting, with normal breathing between attacks. Which stage is she in, and why do adults get pertussis despite vaccination?",
  ["Paroxysmal stage; immunity from acellular vaccine wanes over years", "Catarrhal stage; the vaccine is live and reverts", "Convalescent stage; she lacks complement", "Catarrhal stage; she has IgA deficiency", "Paroxysmal stage; the vaccine protects only against parapertussis"],
  "Pertussis stages: catarrhal (1–2 weeks, cold-like, most contagious), paroxysmal (2–6 weeks, coughing fits, whoop, post-tussive emesis), convalescent (weeks to months, 'the 100-day cough'). Adults may just have a prolonged cough. Acellular pertussis vaccines (pertussis toxoid, filamentous hemagglutinin, pertactin, fimbriae) provide immunity that wanes, so boosters (Tdap) are given. Diagnose with nasopharyngeal PCR. Culture uses Bordet-Gengou or Regan-Lowe."),
Q(GNR, "Legionella: laboratory",
  "Sputum from a patient with suspected Legionnaires' disease shows many neutrophils but no organisms on Gram stain. What explains this, and which culture medium is required?",
  ["The organism stains poorly with Gram stain (silver stain works better) and needs buffered charcoal yeast extract with L-cysteine and iron", "The organism lacks a cell wall and grows on Eaton agar", "The organism is acid-fast and grows on Löwenstein-Jensen medium", "The organism is an obligate intracellular pathogen that cannot be cultured", "The organism needs factor X and V on chocolate agar"],
  "Legionella pneumophila is a Gram-negative rod that stains poorly with Gram stain because it is mostly intracellular. It is seen with silver stain or fluorescent antibody. It needs buffered charcoal yeast extract agar with L-cysteine and iron. The urine antigen test detects only serogroup 1, so sputum culture on BCYE or PCR helps detect other serogroups. It lives in amoebae in water systems."),
Q(GNR, "Moraxella catarrhalis: epidemiology",
  "A 68-year-old man with COPD has a flare with increased sputum purulence. Which trio of organisms is most commonly responsible for bacterial COPD exacerbations?",
  ["Nontypeable H. influenzae, Moraxella catarrhalis, and S. pneumoniae", "S. aureus, S. pyogenes, and Enterococcus", "Legionella, Chlamydia psittaci, and Coxiella", "Klebsiella, Proteus, and E. coli", "Mycobacterium avium, Nocardia, and Aspergillus"],
  "The main bacterial causes of COPD exacerbations are nontypeable H. influenzae, M. catarrhalis, and S. pneumoniae (with Pseudomonas in severe disease). These same organisms cause otitis media and sinusitis in children. M. catarrhalis is a Gram-negative diplococcus that almost always makes β-lactamase."),
Q(GNR, "Burkholderia cepacia",
  "A 19-year-old with cystic fibrosis develops rapidly progressive necrotizing pneumonia and bacteremia. Sputum grows a Gram-negative rod resistant to aminoglycosides and polymyxins. This organism is a contraindication to lung transplant in many centers. What is it?",
  ["Burkholderia cepacia complex", "Pseudomonas aeruginosa", "Staphylococcus aureus", "Stenotrophomonas maltophilia", "Haemophilus influenzae"],
  "Burkholderia cepacia complex is an intrinsically resistant, catalase-positive, aerobic Gram-negative rod. In CF it can cause 'cepacia syndrome,' a fulminant necrotizing pneumonia with bacteremia. It spreads between CF patients, so they are separated in clinics. It also infects patients with chronic granulomatous disease. TMP-SMX or meropenem may be active."),
# ---------------- Enterics & others ----------------
Q(ENT, "Klebsiella: liver abscess & ESBL",
  "A 55-year-old diabetic man from Taiwan has fever, a single large liver abscess, and sudden vision loss from endophthalmitis. Culture grows hypermucoviscous Klebsiella pneumoniae that forms a long 'string' when a colony is stretched. The isolate makes an extended-spectrum β-lactamase. What is the treatment of choice?",
  ["A carbapenem such as meropenem", "Ceftriaxone", "Ampicillin-sulbactam", "Cefazolin", "Aztreonam"],
  "Hypervirulent K. pneumoniae (K1/K2 capsule, positive string test) causes community-acquired liver abscess with metastatic spread (endophthalmitis, meningitis), especially in East Asian diabetics. ESBLs hydrolyze penicillins, cephalosporins (including 3rd generation), and aztreonam, but not carbapenems, which are the treatment of choice. ESBL genes spread on plasmids by conjugation."),
Q(ENT, "Serratia & Enterobacter: AmpC",
  "A patient with Enterobacter cloacae bacteremia initially responds to ceftriaxone, but a repeat culture now shows resistance to all third-generation cephalosporins. What is the most likely mechanism, and which drug is preferred?",
  ["Derepression of chromosomal AmpC β-lactamase; cefepime or a carbapenem", "Acquisition of PBP2a; vancomycin", "Loss of 30S binding; tetracycline", "Target mutation in DNA gyrase; ampicillin", "Efflux of polymyxins; colistin"],
  "Enterobacter, Serratia, Citrobacter (and Morganella, Providencia) can overproduce chromosomal AmpC β-lactamase during therapy with 3rd-generation cephalosporins. Resistance emerges on treatment. Cefepime (stable to AmpC) or a carbapenem is preferred for serious infections. Serratia marcescens causes hospital UTIs and pneumonia, is catalase-positive (CGD), and may make a red pigment."),
Q(ENT, "Acinetobacter",
  "A soldier wounded in Iraq develops a wound infection and ventilator-associated pneumonia with a Gram-negative coccobacillus that is resistant to carbapenems. Which organism is most likely?",
  ["Acinetobacter baumannii", "Neisseria meningitidis", "Haemophilus influenzae", "Moraxella catarrhalis", "Bordetella pertussis"],
  "Acinetobacter baumannii is a non-fermenting Gram-negative coccobacillus that survives on dry hospital surfaces. It causes ventilator-associated pneumonia, bloodstream, and wound infections, including war wounds. It is often multidrug- or carbapenem-resistant. Options include ampicillin-sulbactam (sulbactam is active on its own against Acinetobacter), sulbactam-durlobactam, cefiderocol, and polymyxins."),
Q(ENT, "Salmonella Typhi: carriers & vaccines",
  "A cook who emigrated from an endemic area is linked to several cases of typhoid fever. She has no symptoms, but her stool cultures are persistently positive for Salmonella Typhi. Where does the organism most likely persist, and which vaccines exist?",
  ["The gallbladder, especially with gallstones; oral live attenuated (Ty21a) and injectable Vi polysaccharide vaccines", "The terminal ileum; there is no vaccine", "The liver; a toxoid vaccine", "Mesenteric lymph nodes; a conjugate pertussis-typhoid vaccine", "The spleen; BCG"],
  "Chronic carriers (like 'Typhoid Mary') shed S. Typhi from the gallbladder, where biofilms form on gallstones. Treatment is prolonged fluoroquinolone therapy and sometimes cholecystectomy. Travel vaccines: oral live attenuated Ty21a (not for immunocompromised) and injectable Vi capsular polysaccharide. Typhoid conjugate vaccines are used in endemic countries. Humans are the only reservoir."),
Q(ENT, "Shigella: treatment & complications",
  "A 4-year-old has high fever, bloody mucoid stools, and a brief seizure. Stool culture grows Shigella sonnei. Which statement is correct?",
  ["Antibiotics such as azithromycin shorten illness and shedding; complications include febrile seizures, reactive arthritis, and rarely HUS", "Antibiotics are contraindicated because they always cause HUS", "Shigella produces cholera-like toxin, so rehydration is the only treatment", "Shigella is spread mainly by undercooked poultry", "Shigella has a very high infectious dose"],
  "Unlike EHEC, shigellosis is usually treated with antibiotics (azithromycin, ciprofloxacin, or ceftriaxone, depending on resistance) to shorten illness and reduce spread in daycare. Complications: febrile seizures in children, reactive arthritis, and HUS (mostly S. dysenteriae type 1 with Shiga toxin). Shigella is non-motile and invades M cells."),
Q(ENT, "Vibrio parahaemolyticus",
  "Several people develop watery diarrhea with cramps 12–24 hours after eating raw oysters at a summer party. None have liver disease, and all recover within 3 days. What is the most likely organism?",
  ["Vibrio parahaemolyticus", "Vibrio vulnificus", "Clostridium botulinum", "Hepatitis E virus", "Diphyllobothrium latum"],
  "Vibrio parahaemolyticus is the most common cause of seafood-associated bacterial gastroenteritis in the US, especially from raw shellfish in warm months. It is halophilic (needs salt) and self-limited. V. vulnificus causes severe sepsis and bullae in people with liver disease or iron overload. Norovirus is also a common cause of oyster-associated outbreaks."),
Q(ENT, "Campylobacter: microbiology & treatment",
  "Which statement about Campylobacter jejuni is correct?",
  ["It is a comma- or S-shaped, oxidase-positive Gram-negative rod that grows at 42°C; severe cases are treated with azithromycin", "It is a spore-forming Gram-positive rod treated with vancomycin", "It is a non-motile rod spread only person to person", "It produces cholera toxin", "It is resistant to macrolides by nature"],
  "Campylobacter jejuni is microaerophilic, comma- or S-shaped, oxidase-positive, and grows at 42°C on selective media. Sources: undercooked poultry, unpasteurized milk, contaminated water, and puppies. It causes fever and bloody diarrhea that is usually self-limited. Severe or high-risk cases get azithromycin (fluoroquinolone resistance is common). Complications: Guillain-Barré and reactive arthritis."),
# ---------------- Zoonotic ----------------
Q(ZOO, "Plague: pneumonic form",
  "Several days after caring for a brother with fever and buboes, a woman develops fever, cough, and bloody sputum. The brother's illness had progressed to pneumonia. Which infection control measure is essential?",
  ["Droplet precautions and antibiotic prophylaxis for close contacts", "Contact precautions only, because plague is spread only by fleas", "Airborne precautions with negative pressure only, and no prophylaxis", "No precautions, because plague does not spread person to person", "Isolation of the patient's pets only"],
  "Pneumonic plague (primary from inhaled droplets or secondary from bacteremia) spreads person to person by respiratory droplets and is fatal without early treatment. Patients need droplet precautions until 48 hours of effective therapy. Close contacts get doxycycline or ciprofloxacin prophylaxis. Y. pestis is a Category A bioterrorism agent. Its virulence includes the F1 capsule, type III secretion of Yops, and plasminogen activator (Pla)."),
Q(ZOO, "Francisella: pathogenesis",
  "A landscaper in Martha's Vineyard mows over a dead rabbit and 3 days later develops high fever and pneumonia. What is the organism, and what is its key virulence strategy?",
  ["Francisella tularensis; it escapes the phagosome and replicates in macrophage cytoplasm", "Yersinia pestis; it forms a poly-D-glutamate capsule", "Bacillus anthracis; it forms spores in the lung", "Coxiella burnetii; it forms elementary bodies", "Brucella abortus; it is spread by fleas"],
  "Francisella tularensis is a tiny, fastidious Gram-negative coccobacillus. It is a facultative intracellular pathogen that escapes the phagosome into the macrophage cytoplasm to replicate. Very few organisms (10–50) cause infection. Routes: tick or deer fly bites, handling infected animals (rabbits, 'rabbit fever'), and inhaled aerosols (lawn mowing, pneumonic tularemia). Forms: ulceroglandular, glandular, oculoglandular, oropharyngeal, pneumonic, typhoidal. Treat with gentamicin or streptomycin."),
Q(ZOO, "Brucella: pathogenesis & lab safety",
  "Why do Brucella species cause abortion in cattle and goats, and why must the clinical lab be warned when brucellosis is suspected?",
  ["Erythritol in animal placentas promotes bacterial growth; the organism is easily transmitted to lab workers by aerosol", "They produce a toxin that cleaves hCG; they form spores that contaminate incubators", "They cross the placenta through a type III secretion system; they cause anaphylaxis", "They block progesterone receptors; they are acid-fast", "They are spread by ticks in barns; they need BSL-1 handling only"],
  "Brucella (B. melitensis from goats and sheep, B. abortus from cattle, B. suis from pigs, B. canis from dogs) concentrates in animal placentas rich in erythritol, causing abortion in livestock. Humans catch it from unpasteurized dairy, animal contact, or aerosols. It is one of the most common lab-acquired infections. It survives in macrophages and causes granulomatous disease of the reticuloendothelial system."),
Q(ZOO, "Capnocytophaga",
  "A 50-year-old man who had a splenectomy develops fulminant sepsis with DIC and gangrene of the fingers 2 days after being licked on a small wound by his dog. What is the most likely organism?",
  ["Capnocytophaga canimorsus", "Pasteurella multocida", "Bartonella henselae", "Eikenella corrodens", "Streptococcus pyogenes"],
  "Capnocytophaga canimorsus is a Gram-negative rod in dog (and cat) mouths. In asplenic patients, alcoholics, and people with cirrhosis, it can cause fulminant sepsis, DIC, and purpura fulminans after bites or licks. Treat with a β-lactam/β-lactamase inhibitor or a carbapenem. Asplenic patients should receive prophylaxis (amoxicillin-clavulanate) after dog bites."),
Q(ZOO, "Bartonella quintana",
  "A homeless man with body lice has recurrent fevers every 5 days, shin pain, and later culture-negative endocarditis. What is the most likely organism?",
  ["Bartonella quintana", "Rickettsia prowazekii", "Borrelia recurrentis", "Coxiella burnetii", "Bartonella henselae"],
  "B. quintana is spread by human body lice. It causes trench fever (periodic 5-day fever, shin pain), bacteremia, culture-negative endocarditis, and bacillary angiomatosis in HIV. Diagnose with serology or PCR. Treat endocarditis with doxycycline plus gentamicin. Body lice also spread epidemic typhus (R. prowazekii) and louse-borne relapsing fever (B. recurrentis)."),
# ---------------- Spirochetes ----------------
Q(SPI, "Lyme: serologic testing",
  "A 45-year-old man in Massachusetts has had knee swelling for 2 months. He recalls a rash the previous summer. Which approach to diagnosis is correct?",
  ["Two-tier serology: a screening EIA followed by a confirmatory immunoblot (or second EIA)", "Serology is negative in late Lyme disease, so diagnose clinically", "Blood culture on routine media", "Dark-field microscopy of synovial fluid", "Wright-stained blood smear showing spirochetes"],
  "Lyme serology (two-tier) is the test for disseminated or late disease, when nearly all patients are seropositive. It is often negative in early EM, so diagnose clinically then. Borrelia burgdorferi changes its outer surface proteins: OspA in the tick midgut, OspC during transmission, and VlsE antigenic variation in the host. Lyme arthritis is treated with 28 days of oral doxycycline. Synovial fluid PCR can support the diagnosis."),
Q(SPI, "Leptospira: reservoir & shedding",
  "Why do rats and dogs efficiently spread Leptospira interrogans into the environment?",
  ["The organism colonizes the proximal renal tubules of reservoir animals and is shed in urine for long periods", "It forms spores in animal feces", "It is carried in the salivary glands of fleas", "It persists in animal lung cavities", "It grows in the animals' red blood cells"],
  "Reservoir hosts carry Leptospira in the proximal renal tubules without symptoms and shed it in urine for months. It survives in warm fresh water and moist soil. Humans are infected through abraded skin, conjunctiva, or mucosa. The organism is a thin, motile spirochete with hooked ends. The Warthin-Starry stain shows it in kidney tissue. Doxycycline is used for prophylaxis in high-risk exposures."),
# ---------------- Rickettsiae ----------------
Q(RIC, "Anaplasma",
  "A 60-year-old man in Minnesota has fever, headache, and myalgias a week after a tick bite. Labs show leukopenia, thrombocytopenia, and elevated transaminases. Morulae are seen inside neutrophils on blood smear. Which tick carries this organism?",
  ["Ixodes scapularis, the same tick that carries Lyme disease and Babesia", "Amblyomma americanum, the lone star tick", "Dermacentor variabilis", "Ornithodoros soft tick", "Rhipicephalus sanguineus"],
  "Anaplasma phagocytophilum causes human granulocytic anaplasmosis. Its morulae are in granulocytes (neutrophils), while Ehrlichia chaffeensis (lone star tick) forms morulae in monocytes. Both cause fever with leukopenia, thrombocytopenia, and elevated LFTs, usually without rash. Both are obligate intracellular and treated with doxycycline."),
Q(RIC, "Murine typhus & Rickettsia summary",
  "A 30-year-old man in south Texas has fever, headache, and a truncal maculopapular rash that spares the palms and soles. He lives with feral cats and opossums, and fleas are in his home. Which organism is most likely?",
  ["Rickettsia typhi", "Rickettsia rickettsii", "Rickettsia prowazekii", "Coxiella burnetii", "Ehrlichia chaffeensis"],
  "Endemic (murine) typhus (R. typhi) is spread by rat and cat fleas (Xenopsylla, Ctenocephalides). Reservoirs include rats, cats, and opossums (south Texas, southern California, Hawaii). It causes fever, headache, and a centrifugal truncal rash, and is milder than epidemic typhus. The Weil-Felix reaction (antibodies cross-reacting with Proteus antigens) is historical. Serology or PCR is used now. Treat with doxycycline."),
# ---------------- Mycobacteria ----------------
Q(MYC, "Leprosy: tuberculoid",
  "A 30-year-old man from India has a single, well-demarcated, hypopigmented, anesthetic plaque on his arm with a palpably thickened ulnar nerve. Skin biopsy shows well-formed granulomas with few or no acid-fast bacilli. How is this form treated, and how is leprosy transmitted?",
  ["Dapsone plus rifampin; mainly by respiratory droplets from untreated multibacillary patients", "Isoniazid alone; by skin contact with the plaque", "Clofazimine alone; by mosquito bites", "Penicillin; by sexual contact", "No treatment; it is not transmissible"],
  "Tuberculoid (paucibacillary) leprosy reflects strong Th1 immunity: few lesions, sensory loss, nerve thickening, and granulomas with few bacilli. The lepromin test is positive. Treat with dapsone plus rifampin for 6 months (WHO now adds clofazimine for all). Leprosy spreads mostly by nasal droplets from untreated lepromatous patients, and armadillos transmit it in the southern US. Most exposed people do not develop disease. Nerve damage causes injuries and deformities from loss of sensation."),
Q(MYC, "Nontuberculous mycobacteria: overview",
  "Which statement about nontuberculous mycobacteria (NTM) is correct?",
  ["They are acquired from environmental water and soil and are not spread person to person", "They are all obligate human pathogens transmitted by aerosol", "They cause positive IGRA results in most cases", "They are treated with isoniazid monotherapy", "They cannot cause lung disease in immunocompetent hosts"],
  "NTM include M. avium complex (lung disease in bronchiectasis or COPD, disseminated disease in AIDS), M. kansasii (TB-like cavitary disease), M. marinum (fish tank granuloma), M. abscessus (rapid grower; lung disease in CF, post-procedure skin infections), and M. scrofulaceum (cervical lymphadenitis in children). They are environmental, not contagious, and many are resistant to standard TB drugs. Macrolide-based regimens are used for MAC."),
# ---------------- Mycoplasma & others ----------------
Q(OTH, "Mycoplasma: molecular features",
  "Mycoplasma pneumoniae attaches to ciliated respiratory epithelium and damages it with hydrogen peroxide and the CARDS toxin. Which structural feature is unique among bacteria?",
  ["Its cell membrane contains sterols taken from the host, and it has no cell wall", "It has a poly-D-glutamate capsule", "It has mycolic acids", "It has two membranes with LPS and a thick peptidoglycan wall", "It forms endospores"],
  "Mycoplasmas are the smallest free-living bacteria. They have no cell wall but have sterols in the membrane for stability. The P1 adhesin binds ciliated epithelium, causing ciliostasis and tracheobronchitis. It grows slowly on sterol-containing media (Eaton agar), so PCR is used. Extrapulmonary effects: cold agglutinin (IgM anti-I) hemolysis, erythema multiforme and Mycoplasma-induced rash and mucositis, bullous myringitis, encephalitis. Treat with macrolides, doxycycline, or fluoroquinolones."),
Q(OTH, "HACEK & Kingella",
  "A 2-year-old has a limp and fever. Joint aspirate of the knee shows neutrophils, but routine culture is negative. PCR detects a Gram-negative coccobacillus that is normal oral flora in young children and is part of the HACEK group. What is the organism?",
  ["Kingella kingae", "Haemophilus ducreyi", "Neisseria gonorrhoeae", "Salmonella enteritidis", "Pasteurella multocida"],
  "Kingella kingae is a major cause of septic arthritis and osteomyelitis in children aged 6 months to 4 years. It grows poorly in routine culture, so inoculating blood culture bottles or PCR helps. The HACEK group (Haemophilus parainfluenzae, Aggregatibacter, Cardiobacterium, Eikenella, Kingella) are slow-growing oral organisms that cause culture-negative endocarditis. Treat with ceftriaxone."),
Q(OTH, "Gardnerella: pathophysiology",
  "Why does bacterial vaginosis produce a vaginal pH above 4.5 and a fishy odor?",
  ["Loss of lactic-acid-producing lactobacilli and overgrowth of anaerobes that make volatile amines", "Candida overgrowth producing ammonia", "Trichomonas consuming lactic acid", "Neisseria gonorrhoeae producing urease", "Estrogen deficiency thinning the epithelium only"],
  "Normally, lactobacilli ferment glycogen to lactic acid and keep the vaginal pH at 3.8–4.5. In BV, lactobacilli are replaced by Gardnerella vaginalis and anaerobes (Prevotella, Mobiluncus, Atopobium). These make amines (putrescine, cadaverine, trimethylamine) that release a fishy odor when alkalinized with KOH. Few neutrophils are present. Risk factors include new or multiple partners and douching. BV in pregnancy increases the risk of preterm birth."),
# ---------------- HIV extras ----------------
Q(HIV, "HIV: monitoring",
  "A patient newly diagnosed with HIV starts bictegravir/emtricitabine/tenofovir alafenamide. Which pair of tests best tracks treatment response and immune status?",
  ["Plasma HIV RNA (viral load) and CD4+ T-cell count", "p24 antigen and Western blot", "HIV antibody titer and ESR", "Monospot and CBC", "IGRA and chest radiograph"],
  "Viral load is the main measure of ART success: the goal is fewer than 200 copies/mL, ideally undetectable, by about 3–6 months. The CD4 count shows immune status and guides opportunistic infection prophylaxis. Do genotype resistance testing before starting or at virologic failure. Undetectable means untransmittable (U=U) for sexual transmission. Antibody titers are not useful for monitoring."),
Q(HIV, "HIV: pathogenesis",
  "In acute HIV infection, which site suffers the earliest and most profound depletion of CD4+ T cells?",
  ["Gut-associated lymphoid tissue", "Thymus", "Bone marrow", "Peripheral blood B cells", "Spleen red pulp"],
  "HIV targets CCR5+ memory CD4+ T cells, which are densely concentrated in the gut mucosa (GALT). These are depleted within weeks of infection, and microbial translocation drives chronic immune activation. Over time, ongoing CD4 death (including pyroptosis of bystander cells), follicular dendritic cell trapping of virus in lymph nodes, and a latent reservoir in resting memory T cells lead to AIDS if untreated. The latent reservoir is why ART cannot cure HIV."),
Q(HIV, "HIV-associated conditions",
  "A 42-year-old Black man with untreated HIV has nephrotic-range proteinuria and enlarged, echogenic kidneys on ultrasound. Biopsy is most likely to show which lesion?",
  ["Collapsing focal segmental glomerulosclerosis", "Minimal change disease", "Membranous nephropathy", "Crescentic glomerulonephritis", "Diabetic nodular glomerulosclerosis"],
  "HIV-associated nephropathy is a collapsing variant of FSGS. It is strongly associated with APOL1 risk variants in people of African ancestry and presents with nephrotic proteinuria, enlarged kidneys, and rapid decline. ART slows progression. Other HIV-associated conditions: HIV-associated neurocognitive disorder, wasting, cardiomyopathy, lymphomas, and accelerated atherosclerosis."),
]
